### ISSUE TITLE
Add way to change JRE

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-App#1]
If that is possible with vanilla launcher

**Comment by fabm3n** [comment]
Example from my default Minecraft launcher_profiles.json:
`    "7cebef3d3088a02bbd502358b744fe99" : {
      "created" : "1970-01-01T00:00:00.000Z",
      "icon" : "Grass",
      "javaArgs" : "-Xmx20G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M",
      "javaDir" : "C:\\Program Files\\Java\\jre1.8.0_241\\bin\\javaw.exe",
      "lastUsed" : "2020-03-21T11:56:32.793Z",
      "lastVersionId" : "latest-release",
      "name" : "",
      "type" : "latest-release"
    }`

**Comment by hduelme** [comment]
Under Linux you must change the JRE manual every time you lance a modpack, when JRE 8 is not the default version. 
It would be great to have a way to set a default for all modpacks.

**Comment by CobaltSpace** [comment]
#264 has a workaround to set the JRE until there is a way to do it in UI.
