### ISSUE TITLE
Apps JAVA settings not transferring to instance settings

### ISSUE THREAD

**Issue by Zetharion** [FTBTeam/FTB-App#10]
I went under the app settings and set memory allocation and my put usual arguments there.  I downloaded Omnia and when I go to the instances settings, it has defaulted to 3GB of memory ( I set the app settings to 6GB) and no arguments.  It looks like the packs don't grab them settings from the app settings.

**Comment by Jake-E** [comment]
This is probably a mixture of both backend and frontend.. @Gaz492 @Rushmead can you confirm which?

**Comment by Gaz492** [comment]
We decided to remove the memory setting from the main settings page as this can be set on a per-instance basis and defaults to the recommended value for the modpack.
