### ISSUE TITLE
Issue to connect my Microsoft Account to FTB

### ISSUE THREAD

**Issue by Showpix** [FTBTeam/FTB-App#1001]
### What Operating System

Windows 11

### Debug Code

FTB-AUTH-000006

### Describe the bug

I can't connect to FTB due to a login problem

### Steps to reproduce

1 Go to FTB app
2 Click to play 
3 Send me to connect my microsoft account
4 I do and it's good
5 After i receive that message and code error
6 I send it to you

### Expected behaviour

I want to connect to my microsoft/minecraft account to play ftb

### Screenshots

![Problem FTB](https://github.com/FTBTeam/FTB-App/assets/150737882/37949a93-27a6-4e97-a484-555f983a35f9)

### Additional information

Please help me,

Thank you.

**Comment by AntonioPliru** [comment]
I am having the same issue... Not sure what was happening I was logged in playing FTB Skies under the username Ejelthefirst. Suddenly the app started showing an error where I couldn´t launch the modpack and advice online was to log out and log back in. Well... now I can´t log in and I don´t know what is going on, please help.

**Comment by Craeoc** [comment]
I am having the same issue, but with me it is only unable to connect to Xbox Live. I have tried to connect my account logged in on the Minecraft launcher, on Microsoft and on Xbox, still having problems. My error code is FTB-AUTH-000001 "We've been unable to communicate with XBox live. It's possible that their services is down." On the Ftb Callback page I am getting a code to copy and paste, but no idea where to paste it into the FTB App.
