### ISSUE TITLE
Fatal exception whilst installing modpack

### ISSUE THREAD

**Issue by mcintosh109** [FTBTeam/FTB-App#1009]
### What Operating System

Windows 10

### Debug Code

FTB-DBGXIPIGIXUDI

### Describe the bug

Fatal exception whilst installing modpack

### Steps to reproduce

1. go to any mod pack
2. click on the download button 
3. click install
![error](https://github.com/FTBTeam/FTB-App/assets/11668482/c5d2f891-d202-4535-a473-878d29bcc37b)

### Expected behaviour

start modpack installation

**Comment by 0rthadox** [comment]
I had the same issue not to long ago, the only way I found to fix it was to go to your appdata folder by pressing Win and R and typing %localappdata% then deleting the entire .ftba folder It will sign you out, but it will fix the issue

**Comment by MichaelHillcox** [comment]
Your debug log does not appear to show any issues, please make sure you do not restart the app after having an issue and then running the debug tool.

Please:
- Reproduce the error
- Leave the app open
- Run the debug tool
- Attach the code here
