### ISSUE TITLE
Category dropdown not populating in version 1.6.0

### ISSUE THREAD

**Issue by nat212** [FTBTeam/FTB-App#1010]
### What Operating System

Windows 11

### Debug Code

FTB-DBGCOYUSILEPI

### Describe the bug

The category dropdown in instance settings doesn't show any of the categories previously created

### Steps to reproduce

1. Install an instance
2. Navigate to the instance's settings
3. Select the category dropdown
4. Click on "add new"
5. Enter a name for the new category
6. Install another instance
7. Navigate to the new instance's settings
8. Select the category dropdown
9. Note that the previously created category does not show up in the list

### Expected behaviour

The created category should appear in the dropdown

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/42024975/088dc1e2-7bf1-4974-b3a1-4e915b77e369)

![image](https://github.com/FTBTeam/FTB-App/assets/42024975/d3f1800d-5e0a-41a7-b6f3-c29ba0cb6a6e)

**Comment by MichaelHillcox** [comment]
Thanks for the report, I'll look into this asap. Restarting the app should fix this in the mean time
