### ISSUE TITLE
New version of app completely useless, install button does nothing

### ISSUE THREAD

**Issue by Xetaxheb** [FTBTeam/FTB-App#1012]
### What Operating System

Windows 10

### Debug Code

no, i already have to install your spyware owner, i'm not running other random closed source programs

### Describe the bug

Clicking install on a modpack takes me to my modpack library and nothing else happens

### Steps to reproduce

1. Click install, in any context, on any modpack
2. App goes to library and nothing else
Nothing in logs, no error messages anywhere

### Expected behaviour

App installs modpack

### Additional information

Some prior version of app worked 100% fine to install genesis 5 minutes earlier. So, not network issues. Closed app, reopened, guess it updated itself without permission to 1.6.0, suddenly it's completely worthless. Tried renaming .ftba, still useless.

**Comment by MichaelHillcox** [comment]
Please attach the debug.log from the .ftba/logs folder after attempting to install a modpack, hopefully this will help debug the issue as you don't want to use the debug tool. 

Many thanks

**Comment by MichaelHillcox** [comment]
Yeah, looks like the app can't find any existing instances, that's pretty strange, could you send over the two instances `instance.json` files from the instances folder? They may have currupted or something like that...

**Comment by Smashcakes** [comment]
I had a similar issue -- though mine showed these status messages briefly at the bottom of the screen after clicking to install FTB Genesis:

![Install Requested for FTB Genesis](https://github.com/FTBTeam/FTB-App/assets/11250643/7cb1e747-83af-4172-bbe1-126dc327531e)
![Failed to load minecraft versions](https://github.com/FTBTeam/FTB-App/assets/11250643/4441745c-f971-45b1-a4cf-c8296a7b5c29)

Reinstalling, deleting the .ftba folder, running as admin, moving folder locations, etc. Finally, instead of using the default options, I created a new category and selected the previous version of Genesis and it installed fine.

**Comment by MichaelHillcox** [comment]
> I had a similar issue -- though mine showed these status messages briefly at the bottom of the screen after clicking to install FTB Genesis:
> 
> ![Install Requested for FTB Genesis](https://private-user-images.githubusercontent.com/11250643/286811541-7cb1e747-83af-4172-bbe1-126dc327531e.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjMxMjcsIm5iZiI6MTcwNjI2MjgyNywicGF0aCI6Ii8xMTI1MDY0My8yODY4MTE1NDEtN2NiMWU3NDctODNhZi00MTcyLWJiZTEtMTI2ZGMzMjc1MzFlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5NTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYzFkNmFiZmZiZThlNWJmYmUzMTFmNzM1MmQxN2FmNjY4OWMzMjA0NzQ3ZGU5ZDU4MzlmNmFkNmI5OWY4MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pKbUM5H-xUlIEBWafQKqWWZcxw-aERpfKQbay4ExYcs) ![Failed to load minecraft versions](https://private-user-images.githubusercontent.com/11250643/286811594-4441745c-f971-45b1-a4cf-c8296a7b5c29.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjMxMjcsIm5iZiI6MTcwNjI2MjgyNywicGF0aCI6Ii8xMTI1MDY0My8yODY4MTE1OTQtNDQ0MTc0NWMtZjk3MS00NWIxLWE0Y2YtYzgyOTZhN2I1YzI5LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5NTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1N2MzNzBkODExOWU1OGZlODMyMGFiYjEzMmY4MWJkZjY5ODAwZmFkNzBkMDZhODVjNGE0M2YwMWJmZWU2NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6dVuEo0diTRu5Kp9zeG2RPhOqA4DTyYsq9Ix3MaFDl8)
> 
> Reinstalling, deleting the .ftba folder, running as admin, moving folder locations, etc. Finally, instead of using the default options, I created a new category and selected the previous version of Genesis and it installed fine.

This looks like networking issues, please open a new issue

**Comment by MichaelHillcox** [comment]
> I definitely am not getting either of those messages, though I can try Smashcakes' workaround when I have time.

Sorry for the long delay, is this still an issue for you?
