### ISSUE TITLE
cant install any modpack

### ISSUE THREAD

**Issue by 1n1t1al** [FTBTeam/FTB-App#1013]
### What Operating System

Windows 11

### Debug Code

FTB-DBGTOBUBIHIVO

### Describe the bug

when i try to install a modpack, it doesn´t work

### Steps to reproduce

1 - go to the home page in the app
2 - click on the green box of download in the modpack (any of them)
3 - the app shows me the mod library saying that i dont have any mods to launch and the download never gets started

### Expected behaviour

download the modpack i chose

**Comment by MichaelHillcox** [comment]
Could you confirm if you ran the debug tool after restarting the app? I'm not seeing anything super helpful in the logs. Some screenshots may help as well

**Comment by 1n1t1al** [comment]
yes i did, the problem is that the screenshots won´t show the problem that is happening, i tried to send you a video but the github doesnt allow me to send it to you

**Comment by MichaelHillcox** [comment]
If you did restart the app before running the debug tool, please rerun the app, see the issue, then without closing or restarting the app, run the debug tool again and send me the resulting code
