### ISSUE TITLE
downloading mod packs but sitting on 0.0% not moving

### ISSUE THREAD

**Issue by pezell6** [FTBTeam/FTB-App#1018]
### What Operating System

Windows 10

### Debug Code

FTB-DBGUFEWOYOYOS

### Describe the bug

i got to download and it just sits on 0.0%

### Steps to reproduce

1. click modpack
2. click install
3. click accept
4. wait for download

### Expected behaviour

to just download the mod pack

### Screenshots

https://gyazo.com/df722717780ad290a8cd41c477add547

**Comment by MichaelHillcox** [comment]
Looks like you've set your instance folder to `"instanceLocation": "C:/Program Files",`

This will not work as the app will not have permission to put files in there
