### ISSUE TITLE
First time after opening launcher, Home page only shows Featured packs

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-App#102]
**Operating System:**
OS: Windows

![image](https://user-images.githubusercontent.com/3844385/79457820-800ad800-7ff9-11ea-94f9-627a728a9e99.png)

**Log Files:**
https://pste.ch/kemasafuwa

**Describe the bug**
First time after opening launcher, Home page only shows Featured packs, instead of Installed and Featured

**To Reproduce**
Steps to reproduce the behaviour:
1. Open launcher
2. Dont click away from home page

**Expected behaviour**
It should show installed packs and featured packs

**Screenshots**
![image](https://user-images.githubusercontent.com/3844385/79457472-f0fdc000-7ff8-11ea-939f-1849859ef5fb.png)

**Additional context**
It doesn't always happen, sometimes if you close and reopen launcher, installed packs are there

**Comment by LatvianModder** [comment]
Additionally, when it *does* work, it doesn't show them all, only one pack (Omnia in this case) but when I click to My Modpacks and back to Home, it now shows them all

**Comment by AKTheKnight** [comment]
I've noticed this occurs when I first start the app after turning on my pc

**Comment by Spacarar** [comment]
I've noticed this issue as well, and sometimes, when it does show, it only shows the omnia pack while I've downloaded it, I've never played omnia. Since it's labeled "Recently Played" I don't think it should be showing a pack I've never once launched.

**Comment by Rushmead** [comment]
We hope that this has been fixed in the next release, please let us know!
