### ISSUE TITLE
FTB app won't launch properly

### ISSUE THREAD

**Issue by skelaria** [FTBTeam/FTB-App#1021]
### What Operating System

Windows 10

### Debug Code

FTB-DBGKOFULOQIZO

### Describe the bug

When I try to launch the app I get an oh... This doesn't look right.. Screen

### Steps to reproduce

Click shortcut to launch the FTB app 
Wait for it to do the loading bar for about 30 seconds

### Expected behaviour

The launcher to show me the list of all available modpacks.

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/76741172/1fdf3c50-ce65-4c19-a37a-dc8e28400405)

### Additional information

In the Debug.log file it says - Success after loading intances and cloadflare reports.
It does not show that there is an issue.

Attempted PC restart and complete reinstall and i still get this error.

Curseforge and other overwolf Apps are all working as intended.

**Comment by skelaria** [comment]
Yes that file exists, but if i click it i get a java exception.

All the files in the folder: 
![image](https://github.com/FTBTeam/FTB-App/assets/76741172/b04ab508-9d57-4833-85c3-c5748f544057)

**Comment by MichaelHillcox** [comment]
Do you have any antivirus software installed? Or windows firewall enabled?
