### ISSUE TITLE
Update username when account name changes

### ISSUE THREAD

**Issue by Electrenator** [FTBTeam/FTB-App#1022]
### What is your suggestion?

Would like to see the username updated within the client and game when changed over at https://minecraft.net. Currently this doesn't update resulting in your old name to be kept within your launcher & game, not allowing you to join multiplayer.

This issue can be resolved by logging out on the launcher and logging back in. Restarting the launcher does nothing to help this issue

### Alternatives ideas

Prompt the user with logging in again, since there client data is invalid for multiplayer usage.

### Additional information

This could be reproduced by;

- Logging into the launcher
- Possibly play a bit too
- Change your username on https://minecraft.net
- Relaunch game & join a server (which you can't, even after launcher restart)

**Comment by Electrenator** [comment]
Is that data required for this report? It's a bit much what it collects

**Comment by MichaelHillcox** [comment]
Ignore that message, the bot shouldn't be doing on that on feature requests. 

As for your issue, this is very edge-case but we can update the username data when we validate your account so I guess this is something we should do
