### ISSUE TITLE
[Feature request] Browse should have a final option section that just shows all modpacks in alphabetical order

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-App#103]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/15698722/79501689-15a36900-7ff4-11ea-9948-b33a103fa169.png)
You can only see 7 unique modpacks. There's no way to find modpacks you don't know the name of, like Continuum.

**Describe the solution you'd like**
There should be a final "All modpacks" section at the end that just shows all the modpacks.

**Comment by Cloudhunter** [comment]
An "All modpacks" button is unlikely to come for scalability reasons in the API. However, we are looking into the best ways of showing more packs to the user.

**Comment by Jake-E** [comment]
The All tab was added a little while back, closing this.
