### ISSUE TITLE
Cannot move FTBApp window.

### ISSUE THREAD

**Issue by jjubenv** [FTBTeam/FTB-App#1031]
### What Operating System

Linux (Debian)

### Debug Code

FTB-DBGEFIDAZOLUH

### Describe the bug

After the application is launched from the GNOME Activities menu, I cannot grab the window title bar and move it around.

### Steps to reproduce

1. Launch the FTP App from the GNOME Activities entry.
2. Mouse Click and hold the title bar (labelled FTB App).
3. Move the mouse, the application does not move around.  Resize and Maximize do work though.

### Expected behaviour

The application window should move around when I drag the title bar.

### Additional information

This started with the 1.6.x updates.

**Comment by MichaelHillcox** [comment]
Oh, interesting! Thanks for the report, I'll look into this.

In the meantime, if you go to settings -> app and toggle "Use system titlebar" (Or something like that) it should use Gnomes native toolbar instead of our custom one which should fix moving the app around.

**Comment by jjubenv** [comment]
That workaround was successful (Though not as nice looking).  Let me know if you need anything else.

**Comment by MichaelHillcox** [comment]
This should be fixed as of the latest version release

https://apps.modpacks.ch/FTBApp/release/202312062219-b2294521bd/FTBA_unix_202312062219-b2294521bd.sh

Please let me know if this issue has not be resolved
