### ISSUE TITLE
FTB app bug

### ISSUE THREAD

**Issue by catalinursu01** [FTBTeam/FTB-App#1037]
### What Operating System

MacOS (Latest)

### Debug Code

FTB-DBGUQUXUVIWIQ

### Describe the bug

All the downloaded instances disappear with all the data from the instance and i have to relog in my minecraft account once i reopen the app .

### Steps to reproduce

1.open the app
2.download the modpack
3.log in 
4.open the modpack
5.close the app 
6.reopen the app and your modpack is deleted

### Expected behaviour

The instances to save in the app folder.

**Comment by MichaelHillcox** [comment]
Your instance location seems to be set to `"instanceLocation": "/Users/catalin/Library/Application Support/.ftba/bin",`

Did you change it at any point? It should be `"instanceLocation": "/Users/catalin/Library/Application Support/.ftba/instances",`

**Comment by catalinursu01** [comment]
No i didn't change the location but i fixed it yesterday by changing back the location to the instances folder and i restored all the saved modpacks.

**Comment by MichaelHillcox** [comment]
Glad this is sorted. I wish I knew what went wrong but I'm happy it's resolved
