### ISSUE TITLE
Oceanblock Updater stuck on Preparing Installation

### ISSUE THREAD

**Issue by IanMcC99** [FTBTeam/FTB-App#1038]
### What Operating System

Windows 10

### Debug Code

Debug Code Not Given using win.exe application (failed to create pastebin file)

### Describe the bug

When attempting to download the new version of the Oceanblock modpack (1.16), i was unable to get past the Preparing Installation window, and it was stuck permanently at 0.0%. Left untouched for 1 hour with no avail. 

### Steps to reproduce

Open FTB application for Win.
Go to Library
Click the Updater for Oceanblock 1.11, and attempt to update to 1.16

### Expected behaviour

An update would occue, bringing the pack version from 1.11 to 1.16

**Comment by IanMcC99** [comment]
Unable to get debug code from application, runs into multiple errors writing to pastebin

**Comment by MichaelHillcox** [comment]
Ignore the bot. It's not very clever :P 

You can try the in-app version, go to settings -> app -> upload logs and then paste the link it gives you here. If that doesn't work. Ensure you've tried to update the pack and when it fails to progress, send over the debug log. You can get this from settings -> app -> actions -> logs. You'll be looking for a debug.log file

**Comment by IanMcC99** [comment]
01ygm31h7kkqu seems to be the code given

[debug.log](https://github.com/FTBTeam/FTB-App/files/13649571/debug.log)

**Comment by MichaelHillcox** [comment]
Hmm, this looks pretty wrong... Could you attach your instance.json from the instance folder you're trying to update

**Comment by IanMcC99** [comment]
[instance.json](https://github.com/FTBTeam/FTB-App/files/13652643/instance.json)

**Comment by MichaelHillcox** [comment]
Hmm, looks like your mcVersion isn't set... 

Try this file instead. 
[instance.json](https://github.com/FTBTeam/FTB-App/files/13653618/instance.json)

**Comment by MichaelHillcox** [comment]
I'm assuming this has been fixed. Please let me know if this isn't the case
