### ISSUE TITLE
Stoneblock 2 and 3 won't load

### ISSUE THREAD

**Issue by Path3onic** [FTBTeam/FTB-App#1042]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.1

### Describe the bug

I click the play button and it loads all the way to Validating Assets upon which both 2 and 3 stop and a little red box pops up in the bottom corner saying Unable to start pack please see instance logs and a yellow one with a lot more complicated things

### Steps to reproduce

Press Play
Let load to Validate Assets
Stops loading and the two boxes appear in the bottom left

### Expected behaviour

I expect it to be able to fully load

**Comment by MichaelHillcox** [comment]
Hay, thanks for the issue! Unfortunately it looks like you've not provided a `Debug code`... We require this as it helps us find your issue as quickly as possible.

## Please do the following

Please use the link below to download and run the FTB Debug tool. This is a tool built by our App Developers and will provide you a code that you need to attach to this issue. Please either edit your original issue or add a comment with this code. If you need more help running this tool, you can [follow our guide on how to use the FTB Debug tool](https://go.ftb.team/ftbdbg-support).

[Windows](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe) // [MacOS](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos) // [Linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux) // [Windows (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-arm64.exe) // [MacOS (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos-arm64) // [Linux (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux-arm)
