### ISSUE TITLE
Cant Launch Stoneblock 3

### ISSUE THREAD

**Issue by Tofuusushi** [FTBTeam/FTB-App#1043]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.1

### Log Files

[2023-11-26-1 log.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13469564/2023-11-26-1.log.txt)

### Describe the bug

can't launch the instance due to this weird java error Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Collection.iterator()" because "alternativeNames" is null. please help.

### Steps to reproduce

1.launch stoneblock 3
2.Doesnt launch

### Expected behaviour

I click launch/play button and error message appears with the same message after every attempt.

### Screenshots

<img width="1279" alt="Capture" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/152134189/951655b7-7b6e-4d01-b527-607ebcb0d1eb">

**Comment by borrowedgore801** [comment]
I got this issue about twenty minutes ago and did what Minah86 suggested and it still didn't work then noticed my system time was not even the right day and fixed that and now stoneblock 3 is working.
Ps. I hope this isn't annoying or considered necroposting this is my first comment lol
