### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Ironarc-corp** [FTBTeam/FTB-App#1044]
### What Operating System

Windows 11

### Debug Code

 FTB-DBGZOTIDEPIWU

### Describe the bug

un message me dit que la validation n'est pas bonne et le lien pour le discord fonctionne pas

### Steps to reproduce

je lance une instance et le message apparait

### Expected behaviour

que l'instance ce lance

### Screenshots

![Capture d'écran 2023-12-14 143541](https://github.com/FTBTeam/FTB-App/assets/108798657/a9523461-f783-40c2-8bb9-78c248c6d524)

**Comment by jo-ka** [comment]
Same thing happening to me.

**Comment by MichaelHillcox** [comment]
This should have already been resolved
