### ISSUE TITLE
App won't open

### ISSUE THREAD

**Issue by D-Dub25** [FTBTeam/FTB-App#1045]
### What Operating System

Windows 11

### Debug Code

FTB-DBGYAQASEHUTU

### Describe the bug

App won't open

### Steps to reproduce

1. go to comment.
2. run debug code tools. There may be problems with the app
3. try opening the app.

### Expected behaviour

App to open

**Comment by MichaelHillcox** [comment]
Could you confirm what overwolf version you have?
