### ISSUE TITLE
all the mods 8 and 9 not downloading any mods for feed the beast launcher

### ISSUE THREAD

**Issue by CoryNB** [FTBTeam/FTB-App#1049]
### Modpack

Other...

### Modpack version

all the mods 8, all the mods 9

### Describe the bug

tried downloading all the mods 8 or 9 with feed the beast and it failed to get any mods.

### Steps to reproduce

have feed the beast launched
look under curse forge, search with the word 'all'
find all the mods 8, all the mods 9
download them,
then check the profile of mod packs under mods.

### Expected behaviour

being able to see the list of mods

### Additional information

unknown issue, don't know how to fix it as this recently came up.

**Comment by MichaelHillcox** [comment]
Hay, thanks for the issue! Unfortunately it looks like you've not provided a `Debug code`... We require this as it helps us find your issue as quickly as possible.

## Please do the following

Please use the link below to download and run the FTB Debug tool. This is a tool built by our App Developers and will provide you a code that you need to attach to this issue. Please either edit your original issue or add a comment with this code. If you need more help running this tool, you can [follow our guide on how to use the FTB Debug tool](https://go.ftb.team/ftbdbg-support).

[Windows](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe) // [MacOS](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos) // [Linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux) // [Windows (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-arm64.exe) // [MacOS (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos-arm64) // [Linux (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux-arm)
