### ISSUE TITLE
Impossible to download any modpacks

### ISSUE THREAD

**Issue by Jerhyco** [FTBTeam/FTB-App#1050]
### What Operating System

Windows 11

### Debug Code

FTB-DBGESEJIXEYEP

### Describe the bug

Whenever I try to dowload a modpack it send me back on my library and nothing happends 

### Steps to reproduce

1. Go to browse
2. Select any modpack
3. Click install on the selected modpack
4. Look at the app sending you back to the library while nothing happend

### Expected behaviour

Modpack showing up in the library and downloading

**Comment by Mouthless-Stoat** [comment]
You need to have the Curseforge app open to install modpack for whatever reason. Maybe the source for the bug. Workaround is just to have Forge open ¯\_(ツ)_/¯

**Comment by Jerhyco** [comment]
Actually the "bug" desapeard after one or two days so yeah maybe having forge open is the solution ...

I dont really know what was the problem but it fixed by itself

**Comment by MichaelHillcox** [comment]
I think your `overwolf` version was a bit old. I'm pretty sure I've fixed the underlying issue here anyway so I'm happy to say this should fixed :+1:
