### ISSUE TITLE
Browser not listing any modpacks

### ISSUE THREAD

**Issue by ThemeIT** [FTBTeam/FTB-App#1057]
### What Operating System

Windows 10

### Debug Code

FTB-DBGINUSICUBAD

### Describe the bug

The launcher wont load any ads or modpacks in the Browse tab

I tried reinstalling overwolf and FTB Launcher with multiple restarts (also deleting folders). Didnt help.

Also: the curseforge app doesnt seem to have any issues loading online-content.

### Steps to reproduce

1. Launch
2. go to "Browse"

### Expected behaviour

App shows list of all modpacks

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/84239908/f15a6f09-7608-4602-b6c5-f70f020eb420)

### Additional information

Launcher Log:https://pastebin.com/rYutrhDC

**Comment by salihkilic** [comment]
I'm having the same problem. 

In addition: Can't get FTB Skies to start either. Tried repairing and I get a "Fatal Exception preparing installation task".

My log: https://pste.ch/wuxebuqufe

**Comment by JezZup** [comment]
Same here. I tried everything, i installed the whole launcher again deleted every folder on my PC thats in a connection with the launcher. All this because my Stoneblock 3 Instance doesnt wanted to start. :/

**Comment by ThemeIT** [comment]
Seems to be a known issue 

See discord " We are aware of an issue affecting all FTB app users. If you are stuck initialising, can't see your modpacks, can't search/browse - we know. We have identified the cause and are working to resolve it as quickly as possible."
