### ISSUE TITLE
gets stuck on initialize intances

### ISSUE THREAD

**Issue by koza1258** [FTBTeam/FTB-App#1058]
### What Operating System

Windows 10

### Debug Code

FTB-DBGOTAQEVUGIG

### Describe the bug

Unable to start any modpack instance

### Steps to reproduce

1 Start instance

### Expected behaviour

launching the game

### Screenshots

![all instances](https://github.com/FTBTeam/FTB-App/assets/18580612/2af354a1-949a-4377-bd23-1408c37f3220)

**Comment by JezZup** [comment]
same here, could you check if you can browse any FTB App Modpacks, because some other people got the same problem.

**Comment by bootlesshacker** [comment]
Same here this morning. Tried reinstaling the modpack but I can't even search or browse any to install them.

**Comment by Stapeslive** [comment]
I'm getting the same issue. The home page shows installed mod packs and nothing else. If I try to load a modpack then it says initialising but no logs appear and nothing happens.

**Comment by dorandoran** [comment]
Same, this is the error I am seeing - seems to a timeout issue with Minetogether during a mandatory precheck? I am just guessing:

`[13Jan2024 03:35:38.336] [MT Connect Friend Search Executor/ERROR] [net.creeperhost.minetogether.connect.ConnectHandler/]: An error occurred while searching for friend servers.
java.io.IOException: Timeout reached whilst waiting for server response.
	at net.creeperhost.minetogether.connect.netty.NettyClient.getFriendServers(NettyClient.java:296) ~[minetogether-forge-1.19.2-6.1.0.jar%23602!/:?]
	at net.creeperhost.minetogether.connect.ConnectHandler.lambda$updateFriendsSearch$4(ConnectHandler.java:220) ~[minetogether-forge-1.19.2-6.1.0.jar%23602!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]`

**Comment by Nihiraz** [comment]
Same here, but just now the Browse page started working again. But still I cannot open an instance or repair it.

**Comment by bootlesshacker** [comment]
Seems to be back, albiet intermitently. I was just able to successfully search, reinstall and launch the modpack

**Comment by dorandoran** [comment]
Ya, seemed to be server side, not our clients? I am seeing logs in FTB now

**Comment by Nihiraz** [comment]
Ok now my istances started launching again here.
