### ISSUE TITLE
[Feature Request] Modpack settings should have feedback when clicking Save

### ISSUE THREAD

**Issue by poloniusDergath** [FTBTeam/FTB-App#106]
**Is your feature request related to a problem? Please describe.**
Not really, just a suggestion for clarity.

**Describe the solution you'd like**
A message / popup of some kind as confirmation for a change in the settings for a specific modpack. Right now if you change, for example, the INSTANCE MEMORY and click on Save you get no feedback whether the changes have been persisted.

**Describe alternatives you've considered**
It can be either a quick popup on the bottom of the app, where the download bar usually appears, or a greying out of the Save button once clicked until the user changes any of the parameters again (window size, instance memory).

**Additional context**
Got this behaviour when changing settings for the FTB Interactions pack, changing the Instance Memory with the slider. Had to reset the app just to be sure the new memory value was being stored.

**Comment by mworzala** [comment]
The input automatically saves when it is edited, and the save button has no effect. I am not a developer I can't say exactly why it's there, but I can confirm that it does nothing.

**Comment by poloniusDergath** [comment]
I see! Then this behaviour is not needed. I suppose the button is there to accommodate future functionality? I'll close the issue regardless.
