### ISSUE TITLE
FTB app voice chat not connected Minecraft

### ISSUE THREAD

**Issue by NimphaCat** [FTBTeam/FTB-App#1062]
### What Operating System

Windows 10

### Debug Code

FTB-DBGXUBUJIFAHI

### Describe the bug

I cannot get voice chat working in minecraft. Setting seemed to be fine, using FTB app, Abe's pack, and SERVERMINER.COM for server. Cannot figure out whats wrong, Tried FTB discord, and someone said something about opening ports, but ports are open, unless I don't understand something.

### Steps to reproduce

1. Connect to FTB app Minecraft launcher
2. Launch Abe's pack
3. login to the server
4. press CAPSLOCK for push to talk
5. voice chat not connected error
![voice chat not connected](https://github.com/FTBTeam/FTB-App/assets/157025831/f0958ee6-be69-48c9-954a-a110c56a7e63)
![ports serverminer](https://github.com/FTBTeam/FTB-App/assets/157025831/a7b175b8-0240-4862-8b67-dc2a465ae5b3)

### Expected behaviour

I want voice chat to work 

### Screenshots

![voice chat not connected](https://github.com/FTBTeam/FTB-App/assets/157025831/fe642547-716f-4e79-8078-e07baaeac071)
![ports serverminer](https://github.com/FTBTeam/FTB-App/assets/157025831/9ad67e6e-affd-4184-95d6-e5debdcabf3e)

# Simple Voice Chat server config v1.19.2-2.4.27

# The port of the voice chat server
# Setting this to "-1" sets the port to the Minecraft servers port (Not recommended)
port=36980
# The IP address to bind the voice chat server on
# Leave empty to use 'server-ip' of server.properties
# To bind to the wildcard address, use '*'
bind_address=127.0.0.1
# The distance to where the voice can be heard
max_voice_distance=48.0
# The multiplier of the voice distance when crouching
crouch_distance_multiplier=1.0
# The multiplier of the voice distance when whispering
whisper_distance_multiplier=0.5
# The opus codec
# Possible values are 'VOIP', 'AUDIO' and 'RESTRICTED_LOWDELAY'
codec=VOIP
# The maximum size in bytes that voice packets are allowed to have
mtu_size=1024
# The frequency at which keep alive packets are sent
# Setting this to a higher value may result in timeouts
keep_alive=1000
# If group chats are allowed
enable_groups=true
# The host name that clients should use to connect to the voice chat
# This may also include a port, e.g. 'example.com:24454'
# Don't change this value if you don't know what you are doing
voice_host=
# If players are allowed to record the voice chat
allow_recording=true
# If spectators are allowed to talk to other players
spectator_interaction=false
# If spectators can talk to players they are spectating
spectator_player_possession=false
# If players without the mod should get kicked from the server
force_voice_chat=false
# The amount of milliseconds, the server should wait to check if the player has the mod installed
# Only active when force_voice_chat is set to true
login_timeout=10000
# The range where the voice chat should broadcast audio to
# A value <0 means 'max_voice_distance'
broadcast_range=-1.0

**Comment by MichaelHillcox** [comment]
This isn't an FTB App issue
