### ISSUE TITLE
stone block 3 doesn't launch

### ISSUE THREAD

**Issue by AgataKatsu** [FTBTeam/FTB-App#1063]
### What Operating System

MacOS (Latest)

### Debug Code

-

### Describe the bug

<img width="1432" alt="Снимок экрана 2024-01-21 в 12 59 49" src="https://github.com/FTBTeam/FTB-App/assets/157279879/d3e3dceb-9a06-4def-aa1b-a232add0ddff">
log:
[2024-01-21-1.log](https://github.com/FTBTeam/FTB-App/files/14000777/2024-01-21-1.log)

### Steps to reproduce

launch stoneblock 3 I suppose

### Expected behaviour

launching Minecraft

### Screenshots

<img width="1432" alt="Снимок экрана 2024-01-21 в 12 59 49" src="https://github.com/FTBTeam/FTB-App/assets/157279879/d3e3dceb-9a06-4def-aa1b-a232add0ddff">

### Additional information

-

**Comment by MichaelHillcox** [comment]
No debug code provided. So I'm gunna close this issue but it looks like the app side of things has worked. You likely need support with the modpack specifically. You can ask a question here https://github.com/ftbteam/ftb-modpack-issues
