### ISSUE TITLE
Skyfactory 3 

### ISSUE THREAD

**Issue by Basti0902** [FTBTeam/FTB-App#1066]
### What Operating System

Windows 11

### Debug Code

1

### Describe the bug

Minecraft is crashing at the end of the loading phase. When it loads eventually I can´t enter my World because its an infinite "loading World" screen.   

### Steps to reproduce

1. open Modloader 2. start Skyfactory 3 3. try joining world 

### Expected behaviour

load in just fine

**Comment by MichaelHillcox** [comment]
Not an app issue, please open an issue on the modpack tracker. https://github.com/ftbteam/ftb-modpack-issues
