### ISSUE TITLE
Modpack wont download

### ISSUE THREAD

**Issue by BonnieD12** [FTBTeam/FTB-App#1069]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.3

### Describe the bug

When trying to download it just wont and an error message just says "Unable to download for unknown reasons"

### Steps to reproduce

Try to download on mac air

### Expected behaviour

for it to just downlaod

**Comment by MichaelHillcox** [comment]
Is this still an issue for you?

**Comment by BonnieD12** [comment]
yes, it is.

**Comment by MichaelHillcox** [comment]
Can you attach a debug log after attempting an install?

[Windows](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe) [MacOS](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos) [Linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux)
[Windows (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-arm64.exe) [MacOS (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos-arm64) [Linux (arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux-arm)

**Comment by Damir-k** [comment]
I have the same issue, here is my debug code:
FTB-DBGURIJOXOQAK

**Comment by MichaelHillcox** [comment]
Looking at your logs I can't see anything obvious, is this crashing after launching the game?
