### ISSUE TITLE
[Bug]: Loaded FTB Sky Odyssey World into FTB Sky Odyssey on new Launcher; now I am given stacks of all items in Survival

### ISSUE THREAD

**Issue by Barberfluids** [FTBTeam/FTB-App#107]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: 1.5.0

**App Version:**
App: 1.0.8

**UI Version:**
UI:  fa03e62e

**Log Files:**
Put links to your logs here
https://pste.ch/kuluvacaqa

**Describe the bug**
If you take a world generated using Sky Odyssey 1.1.0 (uses MineCraft v1.12.2.) using the old FTB launcher (v1.5.1); Chosen Architect Template and load that onto Sky Odyssey that has been downloaded and setup using the new FTB launcher (v1.5.0); you get stacks of every item in Survival mode.  The only other mod used was Mr Crayfish's Controller Mod to use a PS4 joystick instead of a keyboard for movement.   This is Survival mode; not Creative.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the new FTB launcher
2. Download FTB Sky Odyssey inside the launcher
3. Download Mr Crayfish's controller mod
4. Copy the world files from your old FTB instance (v1.5.1) into the world directory of the new FTB Launcher instance (v1.5.0) of Sky Odyssey that was created using the new launcher.
5. Go to select an item in JEI and a stack of items will pop into your inventory on any item you select.
6. Effectively renders survival mode into creative mode.

**Expected behaviour**
I would expect JEI would provide the recipe to craft the item and I would have to go through the steps to craft it.  You shouldn't be provided every item.  This makes the quests easily achievable in minutes instead of weeks.

**Screenshots**
![download3](https://user-images.githubusercontent.com/50410992/79567608-8729f880-8082-11ea-894b-98fbbbdee20f.png)
![newftb](https://user-images.githubusercontent.com/50410992/79568059-34047580-8083-11ea-9da0-847cf924e232.png)
![versions](https://user-images.githubusercontent.com/50410992/79568983-d2dda180-8084-11ea-9e1e-d628be256196.png)
![image](https://user-images.githubusercontent.com/50410992/79565801-67dd9c00-807f-11ea-9c40-eb3be3b300e1.png)
![given2](https://user-images.githubusercontent.com/50410992/79565822-70ce6d80-807f-11ea-8755-63a2db6fc10b.png)

**Additional context**
I am sure every gamer out there has games they are in the middle of that need to be moved over to the new launcher to get updates.   I would imagine this will be a common issue at least FTB Sky Odyssey; not sure about other worlds and other modpacks if the same thing will occur.

**Comment by Jake-E** [comment]
This is not an issue with the FTB App. You have cheat mode enabled on JEI (CTRL + click the Spanner).

**Comment by Barberfluids** [comment]
Confirmed.  Thanks Jake-E!  Noob mistake.
