### ISSUE TITLE
unable to create instance 

### ISSUE THREAD

**Issue by 420blaze4231** [FTBTeam/FTB-App#1074]
### What Operating System

Windows 11

### Debug Code

ftb-DBGXIBAZUPEVU

### Describe the bug

it fails to create new forge instance 

### Steps to reproduce

create new instance 

### Expected behaviour

for instance  to fail

**Comment by CoryNB** [comment]
do you have bitlocker engaged?

**Comment by 420blaze4231** [comment]
i do not but i do have other security software also i specially allow all overwolf and java applications to bypass all firewalls or secure folders
