### ISSUE TITLE
App flickers rapidly on Linux with nVidia proprietary drivers

### ISSUE THREAD

**Issue by psybornut** [FTBTeam/FTB-App#1085]
### What Operating System

Linux (Other)

### Debug Code

FTB-DBGEFAMOMIRUB

### Describe the bug

While using the FTB App, the interface will sometimes flicker rapidly or not display at all. This seems to be especially true for sub-windows (i.e. version or settings windows from within a pack instance). In many cases, the interface displays the previous view, but the interface is unusable.

### Steps to reproduce

One example: Select a pack instance and go to the version selection screen. Version screen will appear briefly and then disappear, showing the pack instance screen. Buttons for pack instance don't work because the version screen is still active, just not visible.

Resizing the window or moving the mouse cursor around randomly gets the interface to display properly. Hit or miss if it's long enough to actually click anything and interact properly before having to repeat the move/resize step.

### Expected behaviour

Expect the subwindow to display correctly until closed by normal means (close button)

### Additional information

Reproduced on Garuda (Arch base) and Bazzite (Fedora Atomic base). All using nvidia proprietary graphics drivers.

**Comment by MichaelHillcox** [comment]
Could you confirm your app version? (Found in settings on the menu in the bottom left)
