### ISSUE TITLE
Offline mode doesn't work.

### ISSUE THREAD

**Issue by MajedAbura** [FTBTeam/FTB-App#1087]
### What Operating System

Windows 11

### Debug Code

FTB-DBGETETUKECOP

### Describe the bug

I can't play any modpack without having connection to the internet.
When I tried to launch the modpack (without internet) it gives me error.
Also, the "Play Offline" option when you hit the three dots next to the play button, doesn't come unless you are connected to the internet.

### Steps to reproduce

1. Go to the mode pack of your choosing (I tried it on Stoneblock 2).
2. Press on the icon of the mode.
3. Either press play or press the three dots and choose play offline.
4. Note: try this without any internet connection.

### Expected behaviour

it continuous to load without any output or with error message at the end.

**Comment by MichaelHillcox** [comment]
Hi, 

Yes, the offline mode in the app right now is poorly named. Really it's just an "Play if Microsofts auth is down" mode. We do plan on allowing the app to work in a offline manner in the future

**Comment by jerry1333** [comment]
And you can't change the name for 3 months? I got scammed by this name when I tried to play offline...
