### ISSUE TITLE
can not import curseforge packs

### ISSUE THREAD

**Issue by demoniclords** [FTBTeam/FTB-App#1089]
### What Operating System

Windows 11

### Debug Code

FTB-DBGUMAVAGATUZ

### Describe the bug

will not let me upload a curseforge pack anymore 

### Steps to reproduce

1. click create an instance
2. click curse import
3. click in the box 
4. click the curse forge zip folder

### Expected behaviour

it imports the pack and starts the download of the mods

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/114711675/b7dcf3c6-d7de-4b8b-9d03-cb9c7c8fb9d5)

### Additional information

https://github.com/FTBTeam/FTB-App/assets/114711675/226389ce-8d63-4567-ade3-3be130361ed5
the folder im using is a zip folder

**Comment by LandofHeros2234** [comment]
It states "Not a valid Curseforge Pack"

**Comment by demoniclords** [comment]
it can be imported into curseforge perfectly fine

**Comment by Radon8472** [comment]
I have the same issue, I can not import any curseforge pack, it always results in "File is not a valid curseforge modpack".

Even for a pack tha I successful imported in a older version of the launcher, I get the "not valid" message now.

![grafik](https://github.com/FTBTeam/FTB-App/assets/30496382/d827b9c0-207b-4ef6-84f0-3a9f19d2aa75)

**Comment by MichaelHillcox** [comment]
Thanks for the report! I've fixed this in dev and should be able to push a version soon :+1:

**Comment by MichaelHillcox** [comment]
This has been fixed as of `1.25.7` :+1:

**Comment by Radon8472** [comment]
I can confim, the import is working like expected now, thx 👍
