### ISSUE TITLE
Can't open FTBApp due to JVM not opening.

### ISSUE THREAD

**Issue by Lupalia** [FTBTeam/FTB-App#109]
Hello everyone, when I try to open the new FTBApp it gives me the error "The JVM could not be started. The maximum Heap size(-Xmx) might be too large or an antivirus or firewall tool could block the execution.". I've tried disabling Windows defender but it still didn't open. Can you help me with this? A screenshot with the error and the logs(I don't know if it is relevant or not) is being provided.
![Adsız](https://user-images.githubusercontent.com/59760038/79633198-adc45e00-816c-11ea-8f2d-4075ade423e2.png)
[main.log](https://github.com/FTBTeam/FTB-App/files/4496356/main.log)

**Comment by xzillen** [comment]
I have the same error with a slightly different log file content the error comes directly when trying to install
[i4j_nlog_32.log](https://github.com/FTBTeam/FTB-App/files/4498610/i4j_nlog_32.log)

**Comment by Jake-E** [comment]
https://github.com/FTBTeam/FTB-App/issues/77#issuecomment-614341836

**Comment by Lupalia** [comment]
[i4j_nlog_2.log](https://github.com/FTBTeam/FTB-App/files/4512832/i4j_nlog_2.log)
