### ISSUE TITLE
Unable to Start the Launcher

### ISSUE THREAD

**Issue by twofrind1** [FTBTeam/FTB-App#1090]
### What Operating System

Windows 11

### Debug Code

FTB-DBGUVOYAPIFIQ

### Describe the bug

The launcher says "Connecting" and then pulls an error I was reading the FTB Discord and apparently other users might have this bug too.

### Steps to reproduce

1.Install FTB APP
2.Attempt to launch with internet
3.That's it

### Expected behaviour

I expected it to launch.

### Screenshots

![Screenshot 2024-03-21 065908](https://github.com/FTBTeam/FTB-App/assets/82464711/7f958859-47c2-41ca-9129-39f6a4cfcd50)
![Screenshot 2024-03-21 070107](https://github.com/FTBTeam/FTB-App/assets/82464711/53e70c8b-f91f-4eab-9268-30c10b2d9270)
![Screenshot 2024-03-21 070157](https://github.com/FTBTeam/FTB-App/assets/82464711/abbe7a61-f3ba-4641-a1b6-4ed8d95b70de)

### Additional information

I tried disabling my firewall,restarting my pc,uninstalling/reinstalling the app,etc

**Comment by twofrind1** [comment]
Update to this, uninstalling overwolf extensions folder and .ftba folders did the trick with the uninstallation process

**Comment by BriarThorn94** [comment]
This is similar to what's happening to me except it doesn't say that "somethings gone wrong" it just doesn't work. It acts like it'll launch/load up and then nothing happens.
