### ISSUE TITLE
Lost all Stoneblock 3 data unexpectadly

### ISSUE THREAD

**Issue by Trippsterx** [FTBTeam/FTB-App#1093]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Describe the bug

last night before i shutodwn my pc i was playing stoneblock with a friend and when i logged in this morning the FTB app had and still has no recolection of stoneblock ever being played on this system no backup folders no screenshot folders nothing remained, i still dont know what happend and im hoping somone could direct me to getting my save files back and running

### Steps to reproduce

there are no steps ive found to reproduce this issue since it happend without warning and without me being able to see when and where things went wrong

### Expected behaviour

As i said i dont know what happend

### Additional information

the only remaing info i have of this world ever existing if need be i will provide them

**Comment by MichaelHillcox** [comment]
Could you confirm if you have an instances folder in `%localappdata%/.ftba/instances` if you do, please could you also upload your `settings.json` from the `%localappdata%/.ftba/storage` folder.

**Comment by Trippsterx** [comment]
I am not quite sure but it all just reappeared back into my FTB launcher saves instance and everything, if this was a mod here thank you for the help!
