### ISSUE TITLE
crash on loading world

### ISSUE THREAD

**Issue by valivaly1** [FTBTeam/FTB-App#1094]
### What Operating System

Windows 11

### Debug Code

 FTB-DBGYIDAMUCEBE

### Describe the bug

- When i launch the game via tlancher it i have error in console and the game is freezing on world join

### Steps to reproduce

https://github.com/valivaly1/minecraft/blob/main/log

On the link is the log

### Expected behaviour

to run the game

**Comment by MichaelHillcox** [comment]
I can't see any reason why this would be a app issue. Please open an issue on https://go.ftb.team/support-modpack
