### ISSUE TITLE
StartupWMClass incorrect on Debian

### ISSUE THREAD

**Issue by Did-Nikole** [FTBTeam/FTB-App#1098]
### What Operating System

Linux (Debian)

### Debug Code

FTB-DBGMOHOZUSORI

### Describe the bug

ftb-app.desktop specifies the incorrect StartupWMClass for Debian 12-bookworm, have had to change this to show correct icon and link to current running app instance.

running
~/xprop WM_Class
returns
WM_CLASS(STRING) = "ftb electron app", "FTB Electron App"

in desktop file its listed as 
[Desktop Entry]
.
.
.
StartupWMClass=FTB App

when changed to the first one listed without the quotes it works correctly.

### Steps to reproduce

1) install the deb file
2) execute
3) icon on launch bar is incorrect

### Expected behaviour

Launching App should show correct icon

### Screenshots

Current
![Screenshot from 2024-04-07 15-40-55](https://github.com/FTBTeam/FTB-App/assets/107393605/4ee1fb75-fb8e-494a-a4c3-f592d206da2c)

After Editing
![Screenshot from 2024-04-07 15-41-42](https://github.com/FTBTeam/FTB-App/assets/107393605/47a11a8d-b8d7-41ab-b427-85a242b9a75e)

**Comment by MichaelHillcox** [comment]
Oh! Very interesting, thanks for pointing this out, I'll take a look into seeing if I can fix this <3
