### ISSUE TITLE
Can't install All The Mods - Gravitas²

### ISSUE THREAD

**Issue by thisischrys** [FTBTeam/FTB-App#1099]
### What Operating System

Windows 11

### Debug Code

FTB-DBGAXAQASACAJ

### Describe the bug

Fatal exception preparing installation task.
Possibly because of the ²?

### Steps to reproduce

Try to install pack
Get error

### Expected behaviour

Succesful installation

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/2012611/792d0744-a80c-46e8-bb0a-567cd406270e)

**Comment by MichaelHillcox** [comment]
You can fix this temporarily by changing the pack name in the install modal that comes up. We've fixed this in dev and I'll ship a fix relatively soon
