### ISSUE TITLE
Changelog isn't functioning correctly

### ISSUE THREAD

**Issue by fuhrriel** [FTBTeam/FTB-App#11]
#### Description:
Can't scroll to the bottom of changelog. Issue persists in both windowed and full-screen mode.

![image](https://user-images.githubusercontent.com/49496299/78290989-eb967500-7524-11ea-8f4c-35854e8ee47c.png)
Impossible to scroll lower.

Can't hide changelog to display other versions or other changelogs
![image](https://user-images.githubusercontent.com/49496299/78291195-3fa15980-7525-11ea-8e5b-c782aa7b3569.png)

Pressing `Changelog` in that does nothing. 

My screen size is 1920x1080

**Comment by Zetharion** [comment]
Yeah the app has scaling issues and gives you no scroll bars.  I noticed that too.
