### ISSUE TITLE
Could not find or load main class java

### ISSUE THREAD

**Issue by Shadow-player** [FTBTeam/FTB-App#1100]
### What Operating System

Windows 11

### Debug Code

FTB-DBGUBENOMIDIT

### Describe the bug

FTB SKIES EXPERT
1.7.0
FTB app
1.25.7

FTB app fails to validate client
"The instance has crashed or has been externally closed"
INSTANCE FOLDER LOG:
Error: Could not find or load main class java
Caused by: java.lang.ClassNotFoundException: java

I have previous played 
FTB Skies
Stoneblock 3
FTB OceanBlock
on this install with zero problems.  I have not moved or erased my JAVA and my curseforge instances work fine

### Steps to reproduce

Install FTB SKIES EXPERT 1.7.0
Launch
Launch stops

### Expected behaviour

Instance to launch

**Comment by MichaelHillcox** [comment]
Could you attach your debug.log, console.log, and latest.log from your instance folder?

**Comment by Shadow-player** [comment]
The only log is the console log:

Error: Could not find or load main class java
Caused by: java.lang.ClassNotFoundException: java
