### ISSUE TITLE
Cant play ATM 9

### ISSUE THREAD

**Issue by Wildmanarmy** [FTBTeam/FTB-App#1101]
### What Operating System

Windows 11

### Debug Code

does not work either

### Describe the bug

just bought brand new laptop to play FTB.  after first launching minecraft, i used ftb app to download ATM9 and after selecting play the loading screen comes up, loads, and when it displays loading world the whole thing freezes..  i literally bought a gaming laptop only for ftb and direwolf. please help

### Steps to reproduce

go to ftb app and hit play on atm9, let it load, and afer a minute or two it will just freeze on the loading world screen after selecting a world

### Expected behaviour

expected to play

**Comment by Wildmanarmy** [comment]
FTB-DBGABOGAHEXOS

**Comment by MichaelHillcox** [comment]
Sorry, missed this issue, are you saying the app won't start the pack or the pack is having an issue on startup?
