### ISSUE TITLE
privacy/ad vendors text

### ISSUE THREAD

**Issue by SteseDav** [FTBTeam/FTB-App#1102]
### What Operating System

Windows 10

### Debug Code

n/a

### Describe the bug

When 'managing' FTB-App privacy options, references to Overwolf are present. 

![image](https://github.com/FTBTeam/FTB-App/assets/8818293/d44370bc-cd79-4ba6-88b4-5f724426fef3)

### Steps to reproduce

View the 'Manage Ads', under privacy in settings

### Expected behaviour

the new FTB does not use Overwolf, apparently...

### Additional information

not sure if this is intended or just left in accidentally.

**Comment by MichaelHillcox** [comment]
Our app no longer requires the overwolf platform but our ads are still powered by Overwolfs ad platform
