### ISSUE TITLE
I can't open this mod

### ISSUE THREAD

**Issue by CungHuy** [FTBTeam/FTB-App#1104]
### What Operating System

Windows 11

### Debug Code

1

### Describe the bug

My instance appears to be hanging at this point on load, not throwing any errors
Tried closing and opening the app again
Tried restarting PC as well

### Steps to reproduce

I opened the game as usual and it showed the error as shown

### Expected behaviour

the mod will run

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/133656190/ffd52e4d-d1d2-4a2e-a0bf-ad3ad38bd3f1)

**Comment by CungHuy** [comment]
And can anyone explain why my ip got banned?
![image](https://github.com/FTBTeam/FTB-App/assets/133656190/79a8d2ea-9308-4a05-8abb-d06dd8ef0ee7)

**Comment by MichaelHillcox** [comment]
> And can anyone explain why my ip got banned? 

At some point a big range of IP's were banned, it's nothing against your account, if you @ righthuggingnow in discord, they can help get you unbanned

**Comment by MichaelHillcox** [comment]
I need your debug code before I can help you with your issue here, please follow the instructions from the bot above
