### ISSUE TITLE
Neoforge  Fails to install  1.20.5

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-App#1107]
### What Operating System

Windows 10

### Debug Code

Unable

### Describe the bug

Neoforge 1.20.5  unable to  install

### Steps to reproduce

make pack with neo 1.20.5

### Expected behaviour

to make pack

### Additional information

latest.log:  https://pste.me/@Lv_ckdMdxGM
debug.log:  https://pste.me/@9ILHhTAX74Q
Standalone:  1.25.8

**Comment by MichaelHillcox** [comment]
Same issue as #1117
