### ISSUE TITLE
crashed transfer

### ISSUE THREAD

**Issue by demoniclords** [FTBTeam/FTB-App#1109]
### What Operating System

Windows 11

### Debug Code

FTB-DBGCOCOSERIWU

### Describe the bug

when i was attempting to move the mod packs and i accidentally ended the task in task manager and when i opened it to try to transfer them again it says java.lang.RuntimeException: Old location is still being moved

### Steps to reproduce

1. start moving some packs
2. open task manager and hit end process on the app

### Expected behaviour

allows to restart the transfer

### Screenshots

![Screenshot 2024-03-19 200914](https://github.com/FTBTeam/FTB-App/assets/114711675/5f2e0a6e-a81a-4b7d-8181-ffaab01d5d7b)

**Comment by MichaelHillcox** [comment]
Remove the `.moving` from `C:\Users\bryca\AppData\Local\.ftba\instances`. Then try again
