### ISSUE TITLE
Can't Choose Where To Download Instancee

### ISSUE THREAD

**Issue by jmrox2001** [FTBTeam/FTB-App#1110]
### What Operating System

Windows 10

### Debug Code

FTB-DBGYATUHAXIQO

### Describe the bug

I downloaded the app to my boot drive and now it will only install games there. Since it's a boot drive, I don't have space for the pack on there. 

### Steps to reproduce

1. Install ftb app on small drive
2. try to install a game 
3. See no option to choose where to download game

### Expected behaviour

I expect a launcher/app to allow me to select where i want to download large files. Cool modpacks though!

**Comment by MichaelHillcox** [comment]
App -> Settings -> Instances -> Scroll to bottom -> Change instance location :+1:

**Comment by jmrox2001** [comment]
@MichaelHillcox Thank you so much. Not sure if I just had a brain fart, but I was literally in that menu for a while.
