### ISSUE TITLE
Instance Java ARGs unable to change garbage collector, but the default works fine

### ISSUE THREAD

**Issue by Griffk97** [FTBTeam/FTB-App#1111]
### What Operating System

Windows 11

### Debug Code

FTB-DBGLAKEPOXESU

### Describe the bug

If you put in arguments in this base instance java args it will FULLY overwrite any other arguments.
See Screenshot 1
Running Instance
See Screenshot 2
If I put the exact same java args in the per instance setting it will always crash because somehow has gotten a G1GC flag without my input.
Running instance 
See Screenshot 4
[console.log](https://github.com/FTBTeam/FTB-App/files/15118786/console.log)
The issue seems to be one of its always adding its own default G1GC flags even over per instance settings. I have my instance on Adoptium JRE 17 with flags and GC from [This](https://github.com/brucethemoose/Minecraft-Performance-Flags-Benchmarks
)

### Steps to reproduce

1. Make an instance
2. Setup the instance to use Adoptium 17 with these flags -XX:+UseShenandoahGC -XX:ShenandoahGCMode=iu -XX:ShenandoahGuaranteedGCInterval=1000000 -XX:AllocatePrefetchStyle=1 -XX:ConcGCThreads=2 
3. Try and run instance, should fail, and in the instance logs there should be the same console.log.
4. Move flags to Settings->Instances.
5. Try and run instance, should work.

### Expected behaviour

I expected my per instance flags to FULLY overwrite anything in my instance settings and anything in the default JVM args for minecraft.

### Screenshots

1. ![image](https://github.com/FTBTeam/FTB-App/assets/188442/f1c5119a-0d5b-484e-829c-53fcae0f8f2c)
2. ![image](https://github.com/FTBTeam/FTB-App/assets/188442/438b40cb-abac-4b4a-af98-7ffeded18627)
3. ![image](https://github.com/FTBTeam/FTB-App/assets/188442/f6d2c54e-4a2c-4a91-a270-183e144f1d32)
4. ![image](https://github.com/FTBTeam/FTB-App/assets/188442/0d3ee2de-7d24-4b67-960f-6160811cd3b5)

**Comment by MichaelHillcox** [comment]
Oh, this one is fixed now :+1:
