### ISSUE TITLE
process using CPU even after app close

### ISSUE THREAD

**Issue by VitasLoWang** [FTBTeam/FTB-App#1112]
### What Operating System

Windows 10

### Debug Code

FTB-DBGDIMIJEBOYO

### Describe the bug

not very good for battery on laptop and for performance of Minecraft or anything else ;-)
I have started the app, closed it later and now I see in the task manager FTB electron app energy usage very high and constant CPU usage around 9% (I have 12 logical processors). i don't see any window or tray icon, so the app should not be running.

### Steps to reproduce

start the app, close it and look into task manager

### Expected behaviour

no process running after closure

**Comment by MichaelHillcox** [comment]
Oh, that's strange, that shouldn't be happening. Can you reproduce this?

**Comment by VitasLoWang** [comment]
> Oh, that's strange, that shouldn't be happening. Can you reproduce this?

couldn't reproduce it now, so probably not important to look at...

**Comment by Gaz492** [comment]
> > Oh, that's strange, that shouldn't be happening. Can you reproduce this?
> 
> couldn't reproduce it now, so probably not important to look at...

Ok, as we have not found a way to replicate this i am going to close the issue, if the issue returns feel free to either reopen this or open a new issue.
