### ISSUE TITLE
Unable to make 1.20.6 Neo Instance

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-App#1116]
### What Operating System

Windows 10

### Debug Code

Unable

### Describe the bug

Unable to install Neo  1.20.6

### Steps to reproduce

Make 1.20.6 neo

### Expected behaviour

install

### Screenshots

https://pste.me/@pFPZd3G2J8M
https://pste.me/@EvK-D21me10

**Comment by MichaelHillcox** [comment]
Same issue as #1117
