### ISSUE TITLE
Unable to install forge 1.20.6

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-App#1117]
### What Operating System

Windows 10

### Debug Code

Its borked

### Describe the bug

Unable to install forge 1.20.6

### Steps to reproduce

Make forge 1.20.6 instance

### Expected behaviour

to install

### Screenshots

App  Logs:
https://pste.me/@FIsUcPSDyrg
https://pste.me/@SoCWPcDlX7k

**Comment by MichaelHillcox** [comment]
I think I've located the issue. I'm waiting to get confirmation atm.

A work around for anyone having an issue with this is to download Java 21 and select it in the instance settings :+1:

**Comment by manmaed** [comment]
Strange how fabric installs fine just neo and forge doesn't install

**Comment by manmaed** [comment]
as of App 1.25.8: Neo 1.20.6 https://pste.ch/arapegusak

**Comment by MichaelHillcox** [comment]
This should be fixed now
