### ISSUE TITLE
FTB App Trojan.Win32.Generic

### ISSUE THREAD

**Issue by seabokas** [FTBTeam/FTB-App#1118]
### What Operating System

Windows 11

### Debug Code

No Need

### Describe the bug

Kaspersky recognizes app as virus.

### Steps to reproduce

When installing the FTB app, Kaspersky detects the virus and removes the program from the system.

### Expected behaviour

Explain and fix the problem.

### Screenshots

![Screenshot 2024-05-04 110711](https://github.com/FTBTeam/FTB-App/assets/1898635/b64833ca-880e-4994-9c5b-c8da88c53f31)

### Additional information

BTW its a brand new PC

**Comment by manmaed** [comment]
This is a false positive.  please update the virus definitions and report as false positive
Virus Total:
https://www.virustotal.com/gui/file/c0145807f5d2013a59bdabcbc63ba3a456610021ffaef3a017d102440f67634f
