### ISSUE TITLE
Unable to launch the ftb app

### ISSUE THREAD

**Issue by maciejduk** [FTBTeam/FTB-App#1119]
### What Operating System

Apple M1 Max Sonoma 14.4.1

### Debug Code

FTB-DBGYATANEXOBO

### Describe the bug

Unable to Launch FTB Electron App (crashes on start after a few minutes without an error)
<img width="1657" alt="image" src="https://github.com/FTBTeam/FTB-App/assets/97241456/50f0d47b-7685-4589-aaea-e6c9abc5010c">
This is as far as I get, then window closes.

Old FTB App starts and stays on this screen:
<img width="1432" alt="image" src="https://github.com/FTBTeam/FTB-App/assets/97241456/80298789-9f98-4872-8a4e-25de4974c1b6">

### Steps to reproduce

Start either FTB App for the error message or FTB Electron App for it to close on it's own.

### Expected behaviour

Get to main screen of the launcher

### Additional information

FTB Electron App was just installed.

I am on slow connection but browse internet and Netflix fairly OK (80-120ms, 4G cellular)

System information:

>   Model Name:	MacBook Pro
>   Model Identifier:	MacBookPro18,4
>   Model Number:	Z15G000QBB/A
>   Chip:	Apple M1 Max
>   Total Number of Cores:	10 (8 performance and 2 efficiency)
>   Memory:	64 GB
>   System Firmware Version:	10151.101.3
>   OS Loader Version:	10151.101.3
>   Activation Lock Status:	Disabled

**Comment by maciejduk** [comment]
I believe this might be something to do with the Mac Sonoma & Electron framework, as another app no longer works as expected (Notion) which is based on Electron framework.

**Comment by maciejduk** [comment]
Updating from 14.4.1 to 14.5 MacOS fixed the issue...

**Comment by MichaelHillcox** [comment]
Oh, good to hear, it might just be an issue with older versions of MacOS and newer versions of electron
