### ISSUE TITLE
[Bug] Avast detecting IDP:Generic virus in windows install exe  (Avast false positive)

### ISSUE THREAD

**Issue by Pete-p** [FTBTeam/FTB-App#112]
**Operating System:**
OS: Windows 10 pro

**Installer Version:**
Installer:  64x 1.0.8

**App Version:**
App:  n/a

**UI Version:**
UI: n/a

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app
No logs produced

**Describe the bug**
Upon launching Avast anti-virus stops process stating "We've blocked FTBA_windows-x64_1_8.exe because it was infected with IDP.Generic"

**To Reproduce**
Steps to reproduce the behaviour:
Start launcher.. avast does not allow it to run for long.

**Expected behaviour**
No virus

**Screenshots**
![Capture](https://user-images.githubusercontent.com/58970385/79901796-40f7d080-83c5-11ea-9103-61eb2df2242e.PNG)

**Additional context**
Virustotal.com does not detect any issues, avast is throwing a false positive.
https://www.virustotal.com/gui/file/4f6a409d6cc0f2a045e2bd409e69c1cbb95d2910031b6a57c537eb7ba66f4f0c/community

**Comment by manmaed** [comment]
ill put issue  #130 here
Please make sure avast is upto date with the program and the definitaons

**Comment by Sunekaer** [comment]
If you continue having issues feel free to re-open.
