### ISSUE TITLE
App not showing anything

### ISSUE THREAD

**Issue by Shoebadoebadoe** [FTBTeam/FTB-App#1120]
### What Operating System

Windows 11

### Debug Code

FTB-DBGISUJURATAC

### Describe the bug

Launching the app (both standalone and through Overwolf) works, yet there is nothing to see in any of the tabs. Looking for a modpack also does not give any result. Trying to login with Microsoft account gives FTB-AUTH-000001 error code and FTB-F-AUTH-000001

### Steps to reproduce

1. Open the app
2. Nothing is displayed in the app

### Expected behaviour

The Home tab would show Featured packs, and searching for Mod pack would work too, and logging in with Microsoft account should also work

### Screenshots

![Screenshot 2024-05-13 134505](https://github.com/FTBTeam/FTB-App/assets/134702652/37afc164-f314-4eca-8489-12c57655e35c)

**Comment by MichaelHillcox** [comment]
Looks like a funky firewall acting up

**Comment by Shoebadoebadoe** [comment]
Do you have a way for me to check this? The only firewall, if any, should be the router provided by the provider and it hasn't given any issues before

> Looks like a funky firewall acting up

**Comment by Shoebadoebadoe** [comment]
I have 2 firewalls on the PC, windows defender and sophos home. Turning either of these off does not change anything

**Comment by Shoebadoebadoe** [comment]
A recent update on my computer seems to have fixed this problem. Thank you for your help!
