### ISSUE TITLE
Changing Windows Display scaling affects Privacy Settings popup

### ISSUE THREAD

**Issue by WyFryMU** [FTBTeam/FTB-App#1121]
### What Operating System

Windows 11

### Debug Code

FTB-DBGEQICUZUDUW

### Describe the bug

When having windows display scaled 150%, the Reject all, Accept all, Save & Quit buttons don't show up on the Privacy settings.

### Steps to reproduce

1. Change Display scale to 150%
2. Open ftb app
3. Open the privacy settings
4. See that the buttons arent there

### Expected behaviour

Buttons should show up no matter the scaling

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/47251130/3dace05d-7c89-4f52-bd68-43a349aacf50)

### Additional information

FTB Electron App v1.25.8
I'm making this for tudsamfa from the FTB Discord. (https://discord.com/channels/372448486723158016/1240402356613677147)
"1680x1050, though i tried many resolutions before tinkering with scaling, all with buttons hidden"

**Comment by MichaelHillcox** [comment]
Thanks for reporting this, I'll forward it on.
