### ISSUE TITLE
Can't connect on initial load of the launcher

### ISSUE THREAD

**Issue by LandonCalling** [FTBTeam/FTB-App#1125]
### What Operating System

Windows 10

### Debug Code

FTB-DBGDIDENIBIQO

### Describe the bug

When initially loading the FTB app, the app sits on the loading screen and eventually a window pops up in the app that says " Something's Gone Wrong!" with a short message and then prompts me to either restart, connect to discord, or "Let me in anyway".  I have restarted the app and my machine and it is still happening.  

### Steps to reproduce

Open the app.

### Expected behaviour

App should open and load to home screen.

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/52553841/0311a6c3-a3c6-4f4c-adb2-6e29ca0e068c)

**Comment by ezwaydev** [comment]
Seems like JAR contents are compiled with JAVA 21 but JRE 17 is provided

(ERROR) </dist/background/main.js> (:71) - Error: LinkageError occurred while loading main class net.creeperhost.creeperlauncher.CreeperLauncher
 (ERROR) </dist/background/main.js> (:71) - 	java.lang.UnsupportedClassVersionError: net/creeperhost/creeperlauncher/CreeperLauncher has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

**Comment by ezwaydev** [comment]
v1.25.10 works (Java21)  thanks!

**Comment by MichaelHillcox** [comment]
Yeah, this should be fixed now, please let me know if it isn't
