### ISSUE TITLE
Cancelling ftb electron app update authentication prompt causes infinite loop.

### ISSUE THREAD

**Issue by PGKan** [FTBTeam/FTB-App#1126]
### What Operating System

Linux (Debian)

### Debug Code

FTB-DBGHUBOHUJEHA

### Describe the bug

when ftb app update available and it prompts for installation authenticate. if the prompt has been cancelled, the app will enter infinite loop of terminate and restart.

### Steps to reproduce

1. start ftb electron app (through terminal or desktop environment) while there is update available
2. press cancel at the password prompt

### Expected behaviour

prompt failure of installation or update

**Comment by PlusLake** [comment]
Same issue with Ubuntu 23.10
I need to kill all FTB related process to stop the infinite loop.

```
ps -aux | grep ftb | awk  '{print $2}' | xargs -I {} kill {}
```

**Comment by MichaelHillcox** [comment]
Thanks, I'll have a look into this, likely something I've missed on the linux side of things

**Comment by MichaelHillcox** [comment]
Oh, this should be fixed now :D
