### ISSUE TITLE
Stoneblock 3 is not downloading due to unknown error

### ISSUE THREAD

**Issue by Zattier** [FTBTeam/FTB-App#1129]
### What Operating System

Windows 10

### Debug Code

FTB-DBGWOZUREWAKO

### Describe the bug

I'm trying to download modpack and nothing is worrking 

### Steps to reproduce

1.start downloading modpack

### Expected behaviour

download the modpack and start it

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/84408839/2c483e62-956a-4a73-9805-77a33d3d8eeb)

**Comment by MichaelHillcox** [comment]
Your log seems to only show that you've tried to start a different pack... This might just be an issue on the loggers part. Could you try and install this modpack again, once it fails, go into settings -> app -> then press upload logs and provide that link here for me? 

Thanks

**Comment by dedliner** [comment]
> Your log seems to only show that you've tried to start a different pack... This might just be an issue on the loggers part. Could you try and install this modpack again, once it fails, go into settings -> app -> then press upload logs and provide that link here for me?
> 
> Thanks

hello, i have too this problem. can you help, please? my logs: https://pste.ch/ibunigezus

**Comment by MichaelHillcox** [comment]
> > Your log seems to only show that you've tried to start a different pack... This might just be an issue on the loggers part. Could you try and install this modpack again, once it fails, go into settings -> app -> then press upload logs and provide that link here for me?
> > Thanks
> 
> hello, i have too this problem. can you help, please? my logs: https://pste.ch/ibunigezus

This looks like a different problem, try deleting ` C:\Users\Даниил\AppData\Local\.ftba\bin\runtime\installations.json` this file and trying again

**Comment by MichaelHillcox** [comment]
@Zattier 

Can you confirm if this file exists `AppData\Local\.ftba\bin\runtime\jdk-17.0.2+8-jre\bin\javaw.exe`
