### ISSUE TITLE
loading/launching modpack doesn't work

### ISSUE THREAD

**Issue by fishman54345** [FTBTeam/FTB-App#1131]
### What Operating System

Windows 11

### Debug Code

FTB-DBGSAZUGUROSA

### Describe the bug

when i try to launch stonepack 2 it either doesn't load or it shows me a error for no account when i already have submitted a account

### Steps to reproduce

1. not really sure

### Expected behaviour

I would like either the launch system be a bit better  or the loading system to be improved

**Comment by MichaelHillcox** [comment]
Looks to me like the app installed the pack but it's crashing on pack startup, do you see an error instantly or does it take a minute to show after pressing start?

**Comment by lechcyrax** [comment]
https://pste.ch/kitijoponu   I have same issue and this is the url for app logs. I can not lunh any modpacks or I can not load stoneblock 3

**Comment by MichaelHillcox** [comment]
> https://pste.ch/kitijoponu I have same issue and this is the url for app logs. I can not lunh any modpacks or I can not load stoneblock 3

Does this file exist for you? `AppData\Local\.ftba\bin\runtime\jdk8u312-b07-jre\bin\javaw.exe`

**Comment by MichaelHillcox** [comment]
@lechcyrax please see the above. If you can also attach your installations.json from the `AppData\Local\.ftba\bin\runtime` folder as well, that would help a lot
