### ISSUE TITLE
Stoneblock 3 wont start

### ISSUE THREAD

**Issue by Jejozz** [FTBTeam/FTB-App#1132]
### What Operating System

Windows 11

### Debug Code

 FTB-DBGILIXOZUFUY

### Describe the bug

Keep saying Failed to execute Java.Io

### Steps to reproduce

1. Go to STB3
2. Start
3. Get the issue

### Expected behaviour

just wanna play

### Screenshots

![Screenshot 2024-05-31 201031](https://github.com/FTBTeam/FTB-App/assets/171375537/8ae85346-e929-4e00-b080-7cc061a51437)

**Comment by MichaelHillcox** [comment]
Ugh, mojang being silly.

Download this file `https://resources.download.minecraft.net/15/15f38314274e759c44f50ac641d11bde12474a25` and put it here `C:\Users\emanu\AppData\Local\.ftba\bin\assets\objects\15\`

**Comment by Jejozz** [comment]
> Ugh, mojang being silly.
> 
> Download this file `https://resources.download.minecraft.net/15/15f38314274e759c44f50ac641d11bde12474a25` and put it here `C:\Users\emanu\AppData\Local\.ftba\bin\assets\objects\15\`

thanks a lot!!!
