### ISSUE TITLE
FTB App Instance Crashes When Validating Client

### ISSUE THREAD

**Issue by zZVizualZz** [FTBTeam/FTB-App#1134]
### Modpack

FTB Academy 1.16

### Modpack version

1.4.0

### Log Files

[AUTH][INFO] Starting authentication flow finished successfully
[AUTH][INFO] Contacting Xbox Live started
[AUTH][INFO] Contacting Xbox Live finished successfully
[AUTH][INFO] Authenticating with Xbox Services started
[AUTH][INFO] Authenticating with Xbox Services finished successfully
[AUTH][INFO] Logging in with Xbox Live started
[AUTH][INFO] Logging in with Xbox Live finished successfully
[AUTH][INFO] Getting Minecraft Profile started
[AUTH][INFO] Verifying ownership started
[AUTH][INFO] Getting Minecraft Profile finished successfully
[AUTH][INFO] Verifying ownership finished successfully
[FTB APP][INFO] Pre-Start Tasks
[FTB APP][INFO] Validate Java Runtime
[FTB APP][INFO] Validate assets
[FTB APP][INFO] Validate libraries
[FTB APP][INFO] Validate client

_No response_

### Describe the bug

I cannot get any modpacks to launch in the FTB app, specifically with FTB Academy. When I open the app and hit play, the modpack begins to load and then gets to '[FTB APP] [INFO] Validate client' and then crashes instantly. Additionally, I cannot make any changes within the modpack settings. (RAM allocation, fullscreen, Java version etc.) When I change any settings, it says "Failed to Save Settings" I have tried uninstalling and reinstalling the FTB App, downgrading the modpack version, redownloading Java 8 etc with no results.

### Steps to reproduce

1. Open FTB App
2. Hit play on a modpack
3. Modpack begins loading, and then crashes

### Expected behaviour

The modpack should open and load FTB Academy

### Screenshots

![Screenshot (131)](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/170955671/fca39fc1-ab03-4ce5-8145-0f7a95a50175)

**Comment by MichaelHillcox** [comment]
After this issue presents, please kill the instance, then go to settings -> app -> upload logs and provide the link it gives you here for me :+1:
