### ISSUE TITLE
FTB Unleashed fatal exception while installing modpack

### ISSUE THREAD

**Issue by Menroc** [FTBTeam/FTB-App#1137]
### Modpack

Other...

### Modpack version

1.1.7

### Describe the bug

When I try download FTB Unleashed, I get error with "fatal exception while installing modpack"
The other modpacks can be download. I have enough space and memory for this.
I tried import as CurseForge modpcak zip, but I have no lucky.

### Steps to reproduce

1. Go to browse in FTB app.
2. Click on CurseForge modpack.
3. Type "FTB Unleashed" into the text box.
4. Select FTB Unleashed.
5. Click on the install.
6. Choose the newest relased version. (1.1.7)

### Expected behaviour

Download the modpack successfull

**Comment by MichaelHillcox** [comment]
Please try and install the modpack again, if you still have an error, go to settings -> app -> upload logs and provide me the link it gives you.
