### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by magnumfire16** [FTBTeam/FTB-App#1138]
### Modpack

FTB StoneBlock 3

### Modpack version

ver. 1.9.0

### Log Files

the file is too big - 208 mb

### Describe the bug

when I'm trying to install the modpack it's crashes with an error, what you can see in the screenshot

### Steps to reproduce

1. Go to the browse
2. Search for the Stoneblock 3
3. Press the install button
4. Press the play button in the instance
5. Wait for a few seconds
6. Get the crash

### Expected behaviour

Start the install, finish the install, start to play

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/162021153/443e3140-49cc-4588-b1a0-c27de4f8b121)

### Additional information

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/162021153/309ccc3a-bacb-40cc-b59c-76fdd1aca8bd)

**Comment by MichaelHillcox** [comment]
Please attempt to install this modpack again but after you see this error (if) please go to settings -> app -> upload logs and provide me the link it gives you
