### ISSUE TITLE
[Bug] Modpacks not finishing Install

### ISSUE THREAD

**Issue by Surawsome** [FTBTeam/FTB-App#114]
**Operating System:**
OS: Windows 10.0.18363

**App Version:**
App: 1.0.8

**UI Version:**
UI: fa03e62e

**Log Files:**
https://pste.ch/ivudonojub

**Describe the bug**
Tried  installing multiple modpacks. Searched for Stoneblock 2 and clicked install. It installed all the way and hangs on "Installing - 94.89% (0.02mbps)". I tried installing a different modpack and chose Academy. Same issue and sitting at 94.89%.

**To Reproduce**
Stated above ^

**Screenshots**
![Capture](https://user-images.githubusercontent.com/19805611/80076194-727db280-8511-11ea-8b2e-b112bcdf2d44.PNG)

**Comment by Surawsome** [comment]
Also, this is a fresh install of the FTB app on an almost fresh install of windows.

**Comment by Surawsome** [comment]
Fixed by closing the FTB app and reopening. So, still a bug, but a visual one.

**Comment by Gaz492** [comment]
Hi,

This issue should now be resolved in the latest versions of the app.

If you still notice visual bugs such as this when installing modpacks please open a new issue.
