### ISSUE TITLE
Special Characters in PC usernames cause Java issues

### ISSUE THREAD

**Issue by WyFryMU** [FTBTeam/FTB-App#1144]
### What Operating System

Windows 11

### Debug Code

FTB-DBGERAWONUFOZ

### Describe the bug

(That code is from efetarkgkc in the ftb discord)
When a player has a special character in their name, the ftb app tries to access it's included java.exe which fails due to the special character.

### Steps to reproduce

1. Have a PC user with a special character in their name
2. Boot up FTB App
3. Try to launch a modpack
4. Fail to launch modpack

### Expected behaviour

Modpack launches

### Additional information

More examples from other people in the FTB Discord. (First one is taken from the above debug code)

`Java.io.IOException: Cannot run program "C:\Users\Efe Tarýk Gökçe\AppData\Local\.ftba\bin\runtime\jdk-17.0.2+8-jre\bin\javaw.exe" (in directory "C:\Users\Efe Tarık Gökçe\AppData\Local\.ftba\bin"): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor`

`java.io.IOException: Cannot run program "C:\Users\Lu�s Leimig\AppData\Local\.ftba\bin\runtime\jdk-17.0.2+8-jre\bin\javaw.exe" (in directory "C:\Users\Luís Leimig\AppData\Local\.ftba\instances\ftb stoneblock 3"): CreateProcess error=2, O sistema não pode encontrar o arquivo especificado`

`java.io.IOException: Cannot run program "C:\Users\Jo�o\AppData\Local\.ftba\bin\runtime\jdk-17.0.4+8-jre\bin\javaw.exe" (in directory "C:\Users\João\AppData\Local\.ftba\bin"): CreateProcess error=2, O sistema não conseguiu localizar o ficheiro especificado`

` java.io.IOException: Cannot run program "C:\Users\Usu�rio\AppData\Local.ftba\bin\runtime\jdk-17.0.7+7-jre\bin\javaw.exe"
CreateProcess error=2, The system cannot find the file specified`

`java.io.IOException: Cannot run program "C:\Users\Lukas Hoßfeld\AppData\Local\Overwolf\Extensions\cmogmmciplgmocnhikmphehmeecmpaggknkjlbag\1.25.10\launcher-3fd58fbe04-all.jar" (in directory "C:\Users\Lukas Hoßfeld\AppData\Local\.ftba\instances\ftb skies expert"): CreateProcess error=193, %1 ist keine zulässige Win32-Anwendung`

`java.io.IOException: Cannot run program "C:\Users\Basia i sp�ka\AppData\Local\.ftba\bin\runtime\jdk-17.0.2+8-jre\bin\javaw.exe" (in directory "C:\Users\Basia i spółka\AppData\Local\.ftba\instances\361c0652-779b-4a61-903f-edc74537aedc"): CreateProcess error=2, Nie można odnaleźć określonego pliku`

**Comment by WyFryMU** [comment]
The workaround that I've been telling people is to install their own java versions then point the modpack at it. That will hit C:/Program Files and avoid hitting their special character name.

**Comment by WyFryMU** [comment]
Another instance: https://pste.ch/cilusorave
This same player's installations.json: 
[installations.json](https://github.com/user-attachments/files/15840513/installations.json)

**Comment by MichaelHillcox** [comment]
This should be fixed as of `1.25.17`
