### ISSUE TITLE
FTB Launcher Not launching any mod

### ISSUE THREAD

**Issue by Nightfan507** [FTBTeam/FTB-App#1146]
### What Operating System

Windows 11

### Debug Code

https://pste.ch/ewazafuvaq

### Describe the bug

I'm trying to play stoneblock 3 and every time I launch it says "looks like the instance has crashed during startup or whilst running..." any idea how fix this.

### Steps to reproduce

1. Launch FTB App
2. Launch Stoneblock 3 
3. The issue happens
4. 

### Expected behaviour

I expect the game to open but it doesn't

**Comment by Gaz492** [comment]
Just wanted to check, are you still running into this issue with the latest version of the app?
If you are would you be able to upload a fresh log for us?
