### ISSUE TITLE
can't download stoneblock 3

### ISSUE THREAD

**Issue by zedo9878** [FTBTeam/FTB-App#1147]
### Modpack

FTB StoneBlock 3

### Modpack version

all of them

### Pack has been modified

- [ ] Yes

### Log Files

https://pste.ch/petonekixo

### Describe the bug

i click the download button and vary soon after I get this  

### Steps to reproduce

download ftb with overwolf or just ftb
then go to download stoneblock 3

### Expected behaviour

error

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/172443163/4c985272-6edd-4dc2-97d8-cf52727fae32)

### Additional information

help

**Comment by Gaz492** [comment]
Just to check, is this still an issue for you on the latest version of the app (1.25.15)?
