### ISSUE TITLE
I cant install the FTB APP

### ISSUE THREAD

**Issue by Correia9990** [FTBTeam/FTB-App#115]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: FTBA_windows-x64_1_0_4 (1)

**App Version:**
App: ?

**UI Version:**
UI: ?

**Log Files:**
Put links to your logs here
how to find logs: https://pastebin.com/fpVRBqGq

**Describe the bug**
when i try to open the installer an error occurs

**To Reproduce**
Steps to reproduce the behaviour:
Double click in the installer

**Expected behaviour**

It be installed

**Screenshots**
![unknown](https://user-images.githubusercontent.com/48302737/80182366-1a13e700-85dd-11ea-8f84-d6bc14077af1.png)

**Additional context**
I dont have any antivirus in my pc

**Comment by Correia9990** [comment]
And the version  FTBA_windows-x64_1_0_8 have the same problem

**Comment by Cloudhunter** [comment]
Duplicate of #77 - please add more information as per my comment there

**Comment by Correia9990** [comment]
I already gave all the information that was requested in # 77
