### ISSUE TITLE
Can't launch the NeoTech modpack

### ISSUE THREAD

**Issue by Eminexu18** [FTBTeam/FTB-App#1154]
### What Operating System

Windows 10

### Debug Code

FTB-DBGJIJIHIJARE

### Describe the bug

when I try to launch NetTech i encounter the same error, even after lots of restarts.
![image_2024-06-18_212151098](https://github.com/FTBTeam/FTB-App/assets/173194334/e6802c9f-0d37-4304-a88d-26ddb7b8ae75)

### Steps to reproduce

go to home ,click on the play button ,watch in disbelief

### Expected behaviour

I expected to open a minecraft tab

### Screenshots

![image_2024-06-18_212300803](https://github.com/FTBTeam/FTB-App/assets/173194334/f207ed16-4816-4c6f-b354-48a6b112d395)

**Comment by cviars** [comment]
Are your CPU drivers up to date? My app was doing that for years till I updated my CPU drivers.

**Comment by Eminexu18** [comment]
> Are your CPU drivers up to date? My app was doing that for years till I updated my CPU drivers.

ye , it seems to have a problem with the new modpacks

**Comment by MichaelHillcox** [comment]
It looks like your app is out of date? Is this still an issue for you? What version of the app are you using?
