### ISSUE TITLE
Cant change the relocate instance

### ISSUE THREAD

**Issue by jcccp1211** [FTBTeam/FTB-App#1156]
### What Operating System

Windows 11

### Debug Code

FTB-DBGKOQIKAQEBU

### Describe the bug

1-the other day I relocated my ftb files to my external hard drive 

 2-but u see yesterday that same external hard drive stopped working so now I no longer have access to anything on it 
 I have been trying to change the relocate instance but everytime it tries cause it doesnt have access to the old files it doesnt let me change it .

 which is also not letting me reinstall any mc modpack because of it
 I have tried uninstalling and reinstalling ,I have tried to run as administrator and it also doesnt change anything . 
  

### Steps to reproduce

1. open ftb app
2. go to settings
3. relocate instance
4. try to change it when u no longer have access to the old files anywhere on ur laptop or pc
5. because u no longer have access to those files u probably an error message

### Expected behaviour

u  should get an error message saying java.lang.RuntimeException:Failed to create marker file in old location

### Screenshots

![Screenshot 2024-06-20 191633](https://github.com/FTBTeam/FTB-App/assets/56971739/9f526fc0-b45b-459a-87a9-d8310f808688)
![Screenshot 2024-06-20 192632](https://github.com/FTBTeam/FTB-App/assets/56971739/fcb587bc-557c-4c76-9f64-35d1e991846d)
![Screenshot 2024-06-20 192714](https://github.com/FTBTeam/FTB-App/assets/56971739/0f06010c-90b5-4b6d-999d-db81436f542f)

### Additional information

I was wondering if there's a way I could reset it or something so that I can change the relocate instance

**Comment by ZacxzInsta** [comment]
I just fixed this by going to C:\Users\(user)\AppData\Local then deleting the .ftba AFTER uninstalling from Overwolf, youll lose your saves and instances but thats the only way i found to fix this.
