### ISSUE TITLE
Can't launch the any modpack 

### ISSUE THREAD

**Issue by slmx00** [FTBTeam/FTB-App#1157]
### What Operating System

Windows 11

### Debug Code

i dont no wt to do

### Describe the bug

I Can't launch the any modpack 

### Steps to reproduce

hilp

### Expected behaviour

i want to play

**Comment by MichaelHillcox** [comment]
No debug code = No support.

You can use the in-app version of the log uploader if you would prefer. Go to settings -> app -> upload logs and provide the link it gives you here.
