### ISSUE TITLE
Missing taskbar icon under Linux Mint

### ISSUE THREAD

**Issue by hduelme** [FTBTeam/FTB-App#116]
**Operating System:**
OS: Linux Mint 19.3 Cinnamon

**Installer Version:**
Installer: FTBA_unix_1_0_8.sh

**App Version:**
App: 1.0.8 

**UI Version:**
UI: fa03e62e

**Describe the bug**
The launcher opens, but has no icon in the taskbar.

**Screenshots**
![Bildschirmfoto vom 2020-04-24 12-29-19](https://user-images.githubusercontent.com/46139144/80204048-72240b00-8628-11ea-89d2-4275ac9c447e.png)
I mark the missing icon.

**Comment by 0x4323** [comment]
I'm also seeing this under Ubuntu 20.04. I have the shortcut to FTBA pinned (as a favourite), but when I click on it to launch the app, the icon appears inactive (as though it isn't running), but the app instead gets a new blank icon on the taskbar.

This is a screenshot when using the Gnome dash to panel extension

![image](https://user-images.githubusercontent.com/1747010/80577553-ff87a680-89fe-11ea-915d-91109d83599b.png)

This is a screenshot using the stock Ubuntu dash.

![image](https://user-images.githubusercontent.com/1747010/80577721-42497e80-89ff-11ea-90e9-7dd748b67b72.png)

**Comment by Septem151** [comment]
Fresh Ubuntu 20.04 install, same issue. 
![ftba-missing-icon](https://user-images.githubusercontent.com/32029081/82720560-3b1e3500-9c7a-11ea-9c6e-25d593e79670.png)

**Comment by hduelme** [comment]
Problem still exist in App Version 1.0.9.

**Comment by Jake-E** [comment]
This should be fixed in the latest release.
