### ISSUE TITLE
Cant run most modpacks

### ISSUE THREAD

**Issue by Feretsensei** [FTBTeam/FTB-App#1160]
### What Operating System

Windows 10

### Debug Code

FTB-DBGATIPADAQEM

### Describe the bug

Well i was creating some space on my pc and it looks like i deleted some files that i shoudent and now most modpacks dont run and some of them wont even download

### Steps to reproduce

1.Open the FTB luncher 2.Try dowlnloading like Stone block 3 or dierwolf 20 pack for example 3.If they manage to download try runing them they wont open 4.Well thats all thanks

### Expected behaviour

well its an easy fix i youst nead to downlad the file i am missing so hope it gets done soon

### Screenshots

![Screenshot (2)](https://github.com/FTBTeam/FTB-App/assets/173133121/9d8c4efb-6c4e-488b-b85a-39f465be8658)

**Comment by MichaelHillcox** [comment]
It looks like your debug tool was run at a strange time, can you make sure you run it right after you see this error? Ideally, please use the one within the app. Go to settings -> app -> upload logs and provide the code it gives you here

**Comment by Feretsensei** [comment]
> It looks like your debug tool was run at a strange time, can you make sure you run it right after you see this error? Ideally, please use the one within the app. Go to settings -> app -> upload logs and provide the code it gives you here

https://pste.ch/obafuhaput  FTB-DBGASUWACOGEF

**Comment by Feretsensei** [comment]
i used the debug tool now right away after the erorr so here so i put another code of it there in chase is i dident provide the in game debug tool corectly

**Comment by WyFryMU** [comment]
@Feretsensei Can you close the FTB App, then go to `C:\Users\Džezbica\AppData\Local\.ftba` then delete the `runtimes` folder. Then start up the FTB App and try again please :)

**Comment by Feretsensei** [comment]
@WyFryMU yup done that still not working il give you another 2 codes in case somthing changed https://pste.ch/niraduleva  FTB-DBGGEYEPIDAHO

**Comment by Feretsensei** [comment]
@MichaelHillcox any good news or shoud i keap trying on my own

**Comment by WyFryMU** [comment]
@Feretsensei  when you deleted the runtime folder, you had the ftb app closed and exited right?  Can you close the ftb app, and if youre using overwolf, exit overwolf then try deleting the runtime folder again then load up the app.

**Comment by MichaelHillcox** [comment]
> @WyFryMU yup done that still not working il give you another 2 codes in case somthing changed https://pste.ch/niraduleva FTB-DBGGEYEPIDAHO

`Caused by: java.io.IOException: Cannot run program "C:\Users\Dezbica\AppData\Local\.ftba\bin\runtime\jdk-17.0.2+8-jre\bin\javaw.exe" (in directory "C:\Users\Džezbica\AppData\Local\.ftba\bin"): CreateProcess error=2, The system cannot find the file specified`

Looks like's something to do with the username on your system. We thought we fixed this but it looks like we're not quite there... 

In the meantime, you can try and change your instance settings to use your own systems java version, in this specific case, it would need to be java 17

**Comment by Gaz492** [comment]
We have shipped out an update to the app today that we hope will resolve these issues you are running into.

If you still have these issues please let us know!
