### ISSUE TITLE
Having this code from debug app FTB-DBGEYOLEPODEQ

### ISSUE THREAD

**Issue by Paramveer9090** [FTBTeam/FTB-App#1163]
### What Operating System

Windows 11

### Debug Code

FTB-DBGEYOLEPODEQ

### Describe the bug

Anything that i try to install or update does not work, opened the debug app it gave me this code FTB-DBGEYOLEPODEQ

### Steps to reproduce

Nothing is installing or updating

### Expected behaviour

should immediately start update but just says requested for update and then nothing happens

### Screenshots

help

### Additional information

help

**Comment by MichaelHillcox** [comment]
Try using the in-app log uploader instead. Go to settings -> app -> upload logs and provide that code here please.
