### ISSUE TITLE
everything dont loads

### ISSUE THREAD

**Issue by Robbi381** [FTBTeam/FTB-App#1164]
### What Operating System

Windows 11

### Debug Code

FTB-DBGMUBUQOVOVA

### Describe the bug

after opening app and trying to download any modpack nothing hapenes and 

### Steps to reproduce

1 opening ftb app
2 clicking on any modpack
3 trying download
4 message about "any modpack queued on instalation" appearing and NOTHING happens after any time

### Expected behaviour

downloading any modpack and launching it

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/174151088/2d8d09bc-6f50-405a-8219-3a743842a966)
![image](https://github.com/FTBTeam/FTB-App/assets/174151088/05a09cb6-ce14-4b11-b644-ffcc593b33c1)

### Additional information

yesterday afternoon I was playing on SB3 and everything was fine, but in the evening it started.
+repair and launching of modpack also dont work

**Comment by MichaelHillcox** [comment]
Looks like your network or system as randomly stopped trusting our network requests from within the app

**Comment by Robbi381** [comment]
> Looks like your network or system as randomly stopped trusting our network requests from within the app

What can I do to solve this?

**Comment by MichaelHillcox** [comment]
It's hard for me to say specifically because all I can see is the after effects of what ever has happened. Have you installed any new applications since it last worked? Changed any settings, changed networks, vpns, etc, etc. Basically anything that might effect your network and or firewalls.

**Comment by Robbi381** [comment]
> It's hard for me to say specifically because all I can see is the after effects of what ever has happened. Have you installed any new applications since it last worked? Changed any settings, changed networks, vpns, etc, etc. Basically anything that might effect your network and or firewalls.

when everything was fine, I went with a friend to play roblox and immediately after this appeared

**Comment by Robbi381** [comment]
and after disabling windows firewall and antivirus its didnt work

**Comment by Gaz492** [comment]
Apologies for the delay in getting back to you, is this still an issue for you?
If it is, would you be able to upload a new log for us?
