### ISSUE TITLE
 FTB-DBGEHOHADIGON

### ISSUE THREAD

**Issue by Eupha-1** [FTBTeam/FTB-App#1166]
### What Operating System

Windows 10

### Debug Code

 FTB-DBGEHOHADIGON

### Describe the bug

unsuccessful to authorize with xbox

### Steps to reproduce

hit play and this error pops up x3 connect to xbox services, successful, connection successful, authorization failed, happed after I died, and the the app froze, waited for the app to respond, nothing happened, had to do a soft reset of the system, after that did a normal shut down, waited for a 1 minute restarted system, and app, still failure, did a repair, still failure, shut down system, restarted  pc, restarted app, still same problem, dl debug tool, and was produced with the for mentioned error code

### Expected behaviour

hit play, and majong to start the files and relog into the server

### Screenshots

![Screenshot (1) FTB](https://github.com/FTBTeam/FTB-App/assets/174530733/23e47011-20ff-4a23-82fe-220f4e32d619)

**Comment by Eupha-1** [comment]
![Screenshot (2)](https://github.com/FTBTeam/FTB-App/assets/174530733/9458b23f-98fd-43db-a2fc-31c5fadaa89d)

**Comment by Eupha-1** [comment]
current xbox services offline, status is pending for fix, major outage, resolution: pending

**Comment by Gaz492** [comment]
The authentication issues should be resolved now, is this still an issue for you?
