### ISSUE TITLE
FTB Infinity Evolved 1.7 3.1.0, Launching error

### ISSUE THREAD

**Issue by jfit1452** [FTBTeam/FTB-App#1167]
### What Operating System

Windows 11

### Debug Code

FTB-DBGREDESAKEVO

### Describe the bug

The Modpack launches. While in game, I look move my cursor around in game and it makes my whole screen a shade of the color of the block I'm looking at. It only does this for a few block types. Certain mobs don't show up like villagers or zombies. Some blocks and entities are just blacked out. Some loot drops are blank squares. The error code says something about my capitalization of the pack names being wrong.

### Steps to reproduce

GO to the mod pack. Open it. Play it and you will see. I'm not sure if you are able to launch my downloaded mod file, im assuming not. My download file is just messed up and I keep redownloading it but nothing changes. I tried setting up a server through this modpack and I think I Fd it up cause all of the other FTB modpacks work fine but I want to play this one. 

### Expected behaviour

Screen is one solid color most of the time. Attached my mobs I can't see cause they're invisible.

### Additional information

The fact that other mod packs work and just this one is messed up makes me think I messed something up while I was trying to create a server. I unistalled everything that I know of that was linked to me setting up a server. I also uninstalled everything I know for FTB but it still doesnt workl.

**Comment by Gaz492** [comment]
This may be a graphics driver issue, could you try making sure that your graphics drivers are up-to-date?
