### ISSUE TITLE
[Bug] Modpack duplicate installation

### ISSUE THREAD

**Issue by Moutard3** [FTBTeam/FTB-App#117]
**Operating System:**
OS: Windows 10

**App Version:**
App: 1.0.8

**UI Version:**
UI: fa03e62e

**Log Files:**
https://pste.ch/mumutebuco

**Describe the bug**
I got two times the same pack installed. Now I played on one of them, but I'm afraid uninstalling one will remove the other, or the saves.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the modpacks list
2. Click on install on a modpack
3. Wait until it's installed
4. Click one more time on install
5. Check your library

**Expected behaviour**
I would expect a message saying the pack is already installed or even the button to disappear.

**Screenshots**
![My library](https://i.imgur.com/3Uhmz2v.png)

**Additional context**
When I change something like RAM or Launch args, it change only on one, not both.

**Comment by Jake-E** [comment]
You can have multiple instances of a modpack - this is not a bug.
