### ISSUE TITLE
Importing a modpack from a CurseForge zip with NeoForge is broken

### ISSUE THREAD

**Issue by Camxcamx5000** [FTBTeam/FTB-App#1170]
### What Operating System

Windows 10

### Debug Code

FTB-DBGSAXUTIMIGU

### Describe the bug

Importing a modpack from a CurseForge zip with NeoForge as the mod loader results in an Unknown Error.
(Release Version 1.25.14)
[unknownerr.txt](https://github.com/user-attachments/files/16170886/unknownerr.txt)

### Steps to reproduce

1. Export a zip file from CurseForge of any NeoForge Pack.
2. Attempt to import zip to FTB App
3. Error!

### Expected behaviour

The app installs the NeoForge modpack

**Comment by MichaelHillcox** [comment]
This should now be fixed :+1:
