### ISSUE TITLE
Very slow download in app

### ISSUE THREAD

**Issue by Nequ18** [FTBTeam/FTB-App#1174]
### What Operating System

Windows 11

### Debug Code

FTB-DBGROMICUVIMA

### Describe the bug

When downloading modpacks, the download speed is extremaly low.

### Steps to reproduce

1. download a modpack

### Expected behaviour

normal speed of my internet

### Screenshots

![image](https://github.com/user-attachments/assets/eed3c0a5-1b53-4377-8f8f-947f6de8f4ee)

**Comment by Gaz492** [comment]
Is the entire download for the modpack slow or just the very start of the download?
Would you also be able to take a screenshot of the Settings > Downloads page and reply with it?
