### ISSUE TITLE
Can't install any 1.16.5 Modpack

### ISSUE THREAD

**Issue by WaterElementFR** [FTBTeam/FTB-App#1177]
### What Operating System

Windows 10

### Debug Code

FTB-DBGIMEDITUDEJ

### Describe the bug

I can't install any modpack in 1.16.5 "due to an unknown error". I even tried to upload a modpack from a .zip file, to create an new on from scratch, nothing worked. The first modpack I had the issue with was Sky Capsule Project but after several test it is with any kind of 1.16.5 modpack.
The download fails at 0% really fast (after like 3s)
Btw I can download and launch any other version's modpack

### Steps to reproduce

Just try to download or create any 1.16.5 modpack

### Expected behaviour

SHould just work

**Comment by Gaz492** [comment]
Make sure the app is closed then press the windows key + r then type `%localappdata%\.ftba\bin` and press enter, in the window that opens you should see a `runtime` folder. Could you try deleting this folder then start the app up again and try installing the pack again
