### ISSUE TITLE
Modpacks running Minecraft 1.12.2 crash on initialization

### ISSUE THREAD

**Issue by ewickham24** [FTBTeam/FTB-App#1178]
### What Operating System

MacOS (Latest)

### Debug Code

FTB-DBGFUGOVOTISO

### Describe the bug

I've been playing FTB Builder's Paradise (I, not II) for the past month or so with minimal issues. Last week, it suddenly began crashing on the initialization screen (after all the mods load). In the crash logs, it looks to be an issue with the narrator. This is the error I am getting: java.lang.NoClassDefFoundError: com/mojang/text2speech/NarratorOSX. I am getting this error only when trying to start 1.12.2. I am able to launch FTB BP II without issue. 

I've done just about everything I can think of and that I can find on the internet. I've uninstalled and reinstalled both Minecraft and the FTB Electron App. I've seen in some places that the file "java-objc-bridge-1.0.0-natives-osx.jar" is missing for some people and that's why I am hitting this error. I've made sure that file is present in the filepath. Also, I can open 1.12.2 through the Minecraft launcher without issue. 

The only thing that I can think of is that it may be a bug in the FTB electron app. I'm really not sure though. Also if this isn't the place to report this problem, please recommend me to where I should ask this. 

Attached is the most recent crash report I got. 

[crash-2024-07-28_18.11.49-client.txt](https://github.com/user-attachments/files/16405567/crash-2024-07-28_18.11.49-client.txt)

### Steps to reproduce

1. Run Builder's Paradise
2. Crash on Initialization

(May not be helpful but this is exactly what I'm doing to get the error)

### Expected behaviour

Minecraft 1.12.2 runs as expected

**Comment by Gaz492** [comment]
This looks like it potentially affects all 1.12.2 modpacks

**Comment by Gaz492** [comment]
Also closing this in favour of #1173
