### ISSUE TITLE
Stoneblock 2 fails to launch to completion

### ISSUE THREAD

**Issue by shrimpwheels** [FTBTeam/FTB-App#1179]
### What Operating System

MacOS (Latest)

### Debug Code

FTB-DBGYALOMIBASO

### Describe the bug

Opening FTB and launching Stoneblock 2 works as expected. The launcher runs and the java window opens. It gets to step 7/7 and acts as if it's finishing but then says "an error during startup prevented minecraft from starting" but says "Unknown" for the modpack in question. 

### Steps to reproduce

Open FTB
Launch Stoneblock 2
Wait for it to finish

### Expected behaviour

Stoneblock 2 should launch

### Screenshots

<img width="1071" alt="Screenshot 2024-07-29 at 8 30 52 PM" src="https://github.com/user-attachments/assets/6046039a-1c05-4fb4-91cb-48c5e9add959">

### Additional information

This world is hosted on my Windows PC server. I am able to launch this instance on that computer without issue. Here is the crash report 
[crash-2024-07-29_20.07.29-client.txt](https://github.com/user-attachments/files/16420376/crash-2024-07-29_20.07.29-client.txt)

**Comment by Gaz492** [comment]
I'm going to close this issue in favour of #1178
