### ISSUE TITLE
[Feature request] Downloading individual mods

### ISSUE THREAD

**Issue by JackOverlord** [FTBTeam/FTB-App#118]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add an option to browse all hosted mods and add them to a pack.

**Describe alternatives you've considered**
Downloading mods from their source and adding them manually.

**Additional context**
So, the only reason I still use twitch over other available launchers is the ability to add mods to packs on the fly without having to go to curse forge (or somewhere else) for it.
Of course it wouldn't really be worth it if not many people are going to use it, but it would still be nice to have.

**Comment by Jake-E** [comment]
It's a modpack launcher, not a mod downloader. I'm afraid this isn't in scope.
