### ISSUE TITLE
probleme installation 

### ISSUE THREAD

**Issue by Shade50** [FTBTeam/FTB-App#1180]
### Modpack

FTB NeoTech

### Modpack version

1.20.4

### Has the pack been modified

No

### Describe the bug

au moment ou il commence l'installation il y a une erreur 
![image](https://github.com/user-attachments/assets/4abc2380-698e-4111-b505-37f7cb719cc2)

### Steps to reproduce

dans la liste des mods je clics sur install
apres il charge 
et bug au moment de linstallation
![image](https://github.com/user-attachments/assets/4abc2380-698e-4111-b505-37f7cb719cc2)

### Expected behaviour

je voudrai pouvoir l'installais 

### Screenshots

![image](https://github.com/user-attachments/assets/4abc2380-698e-4111-b505-37f7cb719cc2)

**Comment by Shade50** [comment]
FTB-DBGOPUMEDAXEL

**Comment by Gaz492** [comment]
If you go to the settings in the app then click on the app tab, you should se 3 blue buttons in a row, click on the first one that says Home.
Once the explorer window opens, close the FTB App then in the explorer window rename the bin folder to bin_old.
Now start the app back up and try installing the modpack again.

For any existing packs you may have installed, you may need to right click on them, click on settings then click the repair button.

**Comment by Shade50** [comment]
thx is very good solution
