### ISSUE TITLE
Can't install FTB Endeavour

### ISSUE THREAD

**Issue by Charliespelar** [FTBTeam/FTB-App#1181]
### What Operating System

Windows 11

### Debug Code

FTB-DBGMIHUREYAQE

### Describe the bug

Everytime i try to install FTB Endeavour an error message pops up saying "Failed to Install FTB Endeavour due to unknown error" please help

### Steps to reproduce

1. Go to FTB App 2. Try installing FTB Endeavour 3. Message pops up

### Expected behaviour

The modpack should install like normal

### Screenshots

![image](https://github.com/user-attachments/assets/eded8ef1-02c0-467a-8fa3-1bd06c423067)

**Comment by Gaz492** [comment]
If you go to the settings in the app then click on the app tab, you should se 3 blue buttons in a row, click on the first one that says Home.
Once the explorer window opens, close the FTB App then in the explorer window rename the bin folder to bin_old.
Now start the app back up and try installing the modpack again.

For any existing packs you may have installed, you may need to right click on them, click on settings then click the repair button.
