### ISSUE TITLE
StoneBlock 3 broken? 

### ISSUE THREAD

**Issue by SGlyph** [FTBTeam/FTB-App#1182]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5

### Has the pack been modified

No

### Describe the bug

The pack refuses to launch? It began a few days ago after it crashed out of the blue.

The modpack exists in a sort of limbo where it's in my library until I try to launch it. then it disappears. 
I've not modified any files so I really can't tell where its gone wrong

I've uninstalled the pack, deleted instance files, but I've no clue what has caused this or how to fix it. 
I've even reinstalled FTB from Overwolf but to no avail

### Steps to reproduce

Unless other people have experienced this, I don't know how

### Expected behaviour

.

### Screenshots

![image](https://github.com/user-attachments/assets/c63a5c37-be04-438d-83bf-38356af7e52c) 
This is what I experienced the day before yesterday. 

![image](https://github.com/user-attachments/assets/e4c14f6e-550a-4a75-8ba6-c91ae6b8f587)
![image](https://github.com/user-attachments/assets/13144c21-0a6f-4083-a012-6d6063107632)
This is what happens when I try to launch or install it from FTB

**Comment by SGlyph** [comment]
> We are not aware of any issues with Stoneblock 3, would you be able to go to the settings in the app then click on the app tab and then click on the upload logs button then reply with the url it gives you?

This is probably very irresponsible, but I'm not super tech savvy. So I'll post the latest log and hope you can figure it out from there. 
[latest.log](https://github.com/user-attachments/files/16444828/latest.log)
I also installed the debug tool like the bot suggested and got the following code: FTB-DBGUJIPIKEPOJ 

I'm sure this whole thing is from my own incompetence somewhere down the line, but its really out of the blue from my perspective.

**Comment by SGlyph** [comment]
> Could you try clicking on the settings button in the app, then if you click on App in the sidebar you will be taken to a page where there are 3 blue buttons in a row.
> 
> Click on the Home button, this should open windows explorer to where the app stores its data. Now close the app and then in the explorer window right click on the bin folder and rename it to bin_broken. Start the app up again then try starting the modpack up again, you might need to right click the modpack in the app, click on settings and then click the repair button if it still doesnt start up for you.

I think this has worked?? 
It let me install the modpack properly, but as it was validating assets, it seemed to have found something it didn't like 
![image](https://github.com/user-attachments/assets/4d357cfa-2701-4950-99b1-8029e256fc56)

But then a minute after showing this pop-up the game launched and seems to be working fine. 
I closed and relaunched to test and it seems to all be good! 
Sadly all my previous worlds didn't get saved but that's not such a big deal. 

Hopefully I won't need to add to this reply chain any longer

**Comment by Gaz492** [comment]
If this issue returns feel free to either reopen this issue or create a new one.
