### ISSUE TITLE
1.7.10 is not launching

### ISSUE THREAD

**Issue by Wazender** [FTBTeam/FTB-App#1183]
### What Operating System

Windows 11

### Debug Code

FTB-DBGEVETEMIKAB

### Describe the bug

Vanilla and modded 1.7.10 minecraft are not launching, modded 1.7.10 is not installing

### Vanilla
1. Install vanilla 1.7.10
2. Launch instance
3. Get this error:

![Без имеguyhgujyhgbyhни](https://github.com/user-attachments/assets/8d152879-3fd7-494a-89ba-d84a865b7380)
### Modded
1. Try to install 1.7.10 with forge
2. Get this error:

![Беdsfsdffsdfsdз имени](https://github.com/user-attachments/assets/f4193238-00eb-4124-a1e8-b9a4a464def5)

### Expected behaviour

1.7.10 installing and running normally

**Comment by Gaz492** [comment]
Could you go into the settings of the FTB app then click on the app tab and then click the upload logs button and reply with the url it gives you?

This should give us more logs that we can use to debug this issue for you.

**Comment by Wazender** [comment]
https://pste.ch/vagahedopi

**Comment by Gaz492** [comment]
If you go to the settings in the app then click on the app tab, you should se 3 blue buttons in a row, click on the first one that says Home.
Once the explorer window opens, close the FTB App then in the explorer window rename the bin folder to bin_old.
Now start the app back up and try installing the modpack again.

For any existing packs you may have installed, you may need to right click on them, click on settings then click the repair button.
