### ISSUE TITLE
Cant launch FTB Unstable 1.21 1.0.1

### ISSUE THREAD

**Issue by dittlau1** [FTBTeam/FTB-App#1193]
### Modpack

FTB Unstable 1.21

### Modpack version

1.0.1

### Has the pack been modified

No

### Log Files

https://pastebin.com/DFvJAXUK
https://pastebin.com/Huqn0Xhr

### Describe the bug

Cant start the instance. installed from launcher, instance wont load. Tested a repair through the FTBapp, did not work.

### Steps to reproduce

install, launch

### Expected behaviour

launch and instance

### Screenshots

![image](https://github.com/user-attachments/assets/25638e29-4475-4c05-9aa9-2bc87d8ddfd8)
![image](https://github.com/user-attachments/assets/0a71ffc4-0154-40a1-87e4-117d263a1e42)

### Additional information

Ran on windows 11 build 23H2

**Comment by Gaz492** [comment]
Could you try going to settings in the app then click the App tab, now click on the blue "Home" button, this should open a file explorer window to where the app stores data.

Once the window opens, close the app then open the bin folder and delete the runtime folder.

Now start the app again and try starting the pack up. You may need to right click the app, select settings and then click the repair button if it still doesnt start up.

If the above doesnt work for you, would you be able to go to the setting page of the app and click the upload app logs button then reply with the URL it copies to your clipboard?

**Comment by in2erval** [comment]
@Gaz492 I was also experiencing similar issues, deleting the runtime folder fixed the issue for me - thank you!
