### ISSUE TITLE
FTB App can't connect to Microsoft even logged in.

### ISSUE THREAD

**Issue by VirtualGamer01** [FTBTeam/FTB-App#1195]
### Modpack

FTB StoneBlock 3

### Modpack version

1.10.0

### Has the pack been modified

No

### Log File

(https://pste.ch/yajuqiqumo)

### Describe the bug

When the game launches it tries to connect to the server but gets refused or just doesn't have access to the auth server. I have tried to reinstall the app, modpack, even vanilla minecraft launcher itself, nothing works. I don't have my skin, or am able to access minetogether. I also can't play multiplayer. In public minetogether chat it saids cannot chat unless client is verified. I have logged out of microsoft on all I can think of. Microsoft store, vanilla minecraft, ftb app, curseforge, and xbox app still won't let me connect in ftb app. I can play with skin in curseforge, and vanilla so its only ftb app. 

### Steps to reproduce

Go to FTB App, Launch any modpack, then try to use minetogether to connect to the chat server. 

### Expected behaviour

connect to microsoft authIn server and chat in minetogether, see minecraft skin, and play multiplayer.

### Screenshots

![2024-08-26_07 30 22](https://github.com/user-attachments/assets/849f924e-006e-493b-af30-d1afbcbf86a7)
![2024-08-26_07 30 32](https://github.com/user-attachments/assets/12611075-c819-4ffc-bdb5-44e770298857)

### Additional information

Figured out the issue, If you have StarLink Internet, it will block the connection from minecraft auth servers and keep you from using minetogether by not connecting to their servers as well as creeperhost. turning on a VPN with P to P connection or Port forwarding will fix the issue.

**Comment by VirtualGamer01** [comment]
Ping

**Comment by Gaz492** [comment]
Could you try logging your minecraft account out of the FTB App then log it back in and see if that resolves your issue?

**Comment by VirtualGamer01** [comment]
tried that I have logged out if it on vanilla, curseforge, and ftb app still the same.

**Comment by VirtualGamer01** [comment]
also getting this now 
![image](https://github.com/user-attachments/assets/0cd41e56-4039-4c4e-981c-08cf8491c5ac)

**Comment by Ptituf** [comment]
Can't connect today same pb , and when i want to relog im getting ![image](https://github.com/user-attachments/assets/bd552547-7c9c-4c43-bb34-400322758a78)

**Comment by VirtualGamer01** [comment]
Found out my problem it was because I have starlink internet. I have to use a vpn to connect to multiplayer uh hope they can fix this soon.

**Comment by MichaelHillcox** [comment]
Glad you managed to find a way around this. Definitely needs to be a network issue. Not sure if there is anything we can action on here so gunna close this one :+1:
