### ISSUE TITLE
Failed to install FTB modpack

### ISSUE THREAD

**Issue by zygomatique9** [FTBTeam/FTB-App#1197]
### What Operating System

Windows 10

### Debug Code

 dbg:UnfnFvGIaQA

### Describe the bug

Bonjour,

Lorsque je tente de télécharger un modpack celui-ci ne charge pas et un message d'erreur apparait.

### Steps to reproduce

1) Je clic sur l'app
2) je recherche le modpack
3) je lance le téléchargement
4) un message d'erreur apparait

### Expected behaviour

Pouvoir telecharger le modpack

### Screenshots

![image](https://github.com/user-attachments/assets/228b0324-e97f-4d04-b8d0-49478b35743c)

**Comment by zygomatique9** [comment]
C'est bon j'ai reussi

**Comment by Amdixer** [comment]
@zygomatique9 Would you care to elaborate _how_ you fixed it for the rest of us?

**Comment by WyFryMU** [comment]
> @zygomatique9 Would you care to elaborate _how_ you fixed it for the rest of us?

It should work now. I think the FTB staff had to do a backend fix. I was able to download the pack successfully just now.

**Comment by MichaelHillcox** [comment]
Yeah, this should be fixed now, you may need to downgrade + update
