### ISSUE TITLE
FTB Omnia on the New FTB App doesn t work

### ISSUE THREAD

**Issue by Thomsn22** [FTBTeam/FTB-App#12]
i have the launche open to klick play but it wont load it it sends me a message to change configuration. but not what is to do

**Comment by Jake-E** [comment]
Can you post a screenshot of the message you are seeing?
This modpack has been confirmed working by a lot of users.

**Comment by Thomsn22** [comment]
Jes of course

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by Thomsn22** [comment]
ill have now a problem where i cant launch the ftb app but if ican ill send later a foto

**Comment by Jake-E** [comment]
Do you have any further information for this @Thomsn22?

**Comment by Thomsn22** [comment]
Im sorry no because i cant Open the Modpacks anymore i cant open the Ftb app anymore

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by Rushmead** [comment]
Can you upload the log found in the installation directory? Both the launcher.log and the error.log. You'll find them in the installation folder the launcher which you would have picked at install time. If you just set it as default it would be in %appdata%/FTBA. You can upload them to https://pste.ch or directly to this issue.

**Comment by Thomsn22** [comment]
Ok ill try

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by Thomsn22** [comment]
Theres a Problem its not located in there, ill try reinstalling, because i have also Twitch app installed. Or should i not ?

**Comment by Thomsn22** [comment]
i have only one folder or should i upload it?

**Comment by Thomsn22** [comment]
its in %appdata% installed but with %appdata%/FTBA i cant find it also these Logs i cant find

**Comment by Thomsn22** [comment]
i reinstalled the app now if it wont work then anymore ill tell it
