### ISSUE TITLE
Failed to install "X" due to an unknown error

### ISSUE THREAD

**Issue by Drahnier0161** [FTBTeam/FTB-App#1200]
### What Operating System

Windows 11

### Debug Code

https://pste.ch/seqadalici

### Describe the bug

Pretty much the same as in Report #1020

### Steps to reproduce

1. open FTB app
2. install FTB Presents Direwolf20 1.21

### Expected behaviour

Installing the descibed pack

### Screenshots

![image](https://github.com/user-attachments/assets/cdcba5b3-df80-4398-8033-79c442aad0b3)
[version_manifest.json](https://github.com/user-attachments/files/17007195/version_manifest.json)
[ftb-app-electron.log](https://github.com/user-attachments/files/17007199/ftb-app-electron.log)
[latest.log](https://github.com/user-attachments/files/17007200/latest.log)
[debug-5.log.gz](https://github.com/user-attachments/files/17007201/debug-5.log.gz)
[instance.json](https://github.com/user-attachments/files/17007208/instance.json)

### Additional information

I´v testet Stoneblocks 3 and it did install just fine.
Deleting "C:\Users\rbili\AppData\Local\.ftba\bin\versions\version_manifest.json" didnt do the trick either.

**Comment by Drahnier0161** [comment]
Also added the FTB App to be ignored by my Antiv Virus

**Comment by MoonStalk** [comment]
I have the exact same error in my logs, unable to download client.jar from Mojang.

I went the drastic route to fix the issue:
Uninstall FTB app, delete the .ftba directory and all it's contents
Reinstall FTB app
Add Microsoft account
Install (works this time)

maybe you could try removing your Microsoft account from the FTB App and re-add it.

**Comment by Gaz492** [comment]
Looking at the logs, it looks like the app was unable to download some files from mojang, is this still an issue for you now?

**Comment by Drahnier0161** [comment]
@MoonStalk 
Just did remove the account and readded it . didnt solve the issue.
@Gaz492 
Yes still the same situation.
Im wondering on why Stoneblocks 3 was able to be installed just fin or Project architect for that matter but the dire pack just dont want to.

**Comment by Drahnier0161** [comment]
Just found out something odd.
When i login to my minecraft.net account with microsoft it shows the accountname "NONEXISTENT4336" when i use the same credentials aka use microsoft login it shows my real username "Drahnier0161"
Afer loging in multiple times it still shows me the Sign in button althoe i should be logged in.
Whats that causing?

![image](https://github.com/user-attachments/assets/ebf46bbb-0e59-4597-bec5-5443b05a3a64)
![image](https://github.com/user-attachments/assets/8dd0d99e-9941-446d-bbf0-a8e7f80f3f44)
![image](https://github.com/user-attachments/assets/108a174c-f6b6-4de8-a3ec-171fcadb1b82)

**Comment by Gaz492** [comment]
Thanks, this looks like it may be an API issue, bear with us while we take a look

**Comment by JoeWhizer** [comment]
Thank you! I can confirm its working now!

**Comment by Drahnier0161** [comment]
https://pste.ch/akazerolac
