### ISSUE TITLE
Modpack Library Empty On Launch

### ISSUE THREAD

**Issue by suchtrashley** [FTBTeam/FTB-App#1201]
### What Operating System

Windows 11

### Debug Code

https://pste.ch/kuqaculuza

### Describe the bug

I opened the FTB App for the first time in a while only to find that all the modpacks I had downloaded and stored in my Library were no longer there. Not a single one. I am still signed into my Microsoft account, and all my files are still in the .ftba folder. I tried logging out and logging back in again, but this didn't change anything.

### Steps to reproduce

1. Open FTB App
2. See empty Library

### Expected behaviour

I expected my Library of installed modpacks (or at least previously installed or played modpacks) to be listed.

### Screenshots

![Screenshot 2024-09-21 215256](https://github.com/user-attachments/assets/6ecd10e0-c47a-45da-8796-a453e1bb5748)
![Screenshot 2024-09-21 215616](https://github.com/user-attachments/assets/371b49dc-b75e-4c77-94cc-d0cc51d74d44)

### Additional information

All my files in the .ftba folder are intact and as they should be. It's just the FTB App not showing anything in my Library.

I don't recall if I'd set any modpacks to my Favourites in the past, but that's completely empty, too.

**Comment by WyFryMU** [comment]
Can you close the FTB App, go to `C:/Users/Ashley/AppData/Local/.ftba/storage`. Open up `settings.json` with NotePad (or any text editor). Add \\instances to your instanceLocation. So it would look like `C:\\Users\\Ashley\\AppData\\Local\\.ftba\\instances`. Save the file. Open the FTB App. Lemme know. Seems the ftb app wasn't looking at the correct instance location.

**Comment by suchtrashley** [comment]
> Can you close the FTB App, go to `C:/Users/Ashley/AppData/Local/.ftba/storage`. Open up `settings.json` with NotePad (or any text editor). Add `\\instances` to your instanceLocation. So it would look like `C:\\Users\\Ashley\\AppData\\Local\\.ftba\\instances`. Save the file. Open the FTB App. Lemme know. Seems the ftb app wasn't looking at the correct instance location.

I'm both relieved and slightly annoyed by this being all it was. Thankyou very much!
