### ISSUE TITLE
Black box on the right side of the App

### ISSUE THREAD

**Issue by N4melessP4nd4** [FTBTeam/FTB-App#1203]
### What Operating System

Windows 11

### Debug Code

https://pste.ch/sagoyufubo

### Describe the bug

The App shows a big black box on the right side. - _See attached screenshot!_

### Steps to reproduce

1. Open the App

### Expected behaviour

Instead of showing that black box it should be filled out with the app screen itself.

### Screenshots

![image](https://github.com/user-attachments/assets/40db3569-a64d-4588-86cb-fda2b6b36ca4)

### Additional information

**Version of the App:**
1.25.18

**Downloaded from website on:**
03.10.2024

**Windows Version:**
23H2 - 22631.4169

**Comment by WyFryMU** [comment]
That box is where ads normally show, which they show for me. Not sure why they dont show for you.

**Comment by MichaelHillcox** [comment]
Yeah, this is the ad space, I'm assuming you've got a system / network wide ad block? Gunna close as this isn't an issue but please feel free to keep replying :+1:
