### ISSUE TITLE
Unknown error trying to download 1.20.1 modpacks

### ISSUE THREAD

**Issue by corngoblin** [FTBTeam/FTB-App#1204]
### What Operating System

Linux (Other)

### Debug Code

https://pste.ch/xugudahelu.md

### Describe the bug

I can download and install other modpacks just not 1.20.1 for some reason. 
I try to download the direwolf20 1.20 pack and it fails due to unknown error.
I can't even make my own instances with 1.20.1

I'm on fedora 40 using the appimage.

### Steps to reproduce

Click browse  
search direwolf20
click install direwolf20 1.20
fails

### Expected behaviour

For it to install 1.20.

**Comment by Gaz492** [comment]
May I ask what exact linux os you are running?

There are known issue with fedora regarding how files are extracted which causes file validation to fail.

Would you be able to see if the following workaround works for you?
https://docs.feed-the-beast.com/docs/app/Troubleshooting/Workarounds/disable-neo-forge-hash-check
