### ISSUE TITLE
launcher says "error while downloading modpack"

### ISSUE THREAD

**Issue by Joshua1526** [FTBTeam/FTB-App#121]
**Operating System:**
OS:Mac

**Installer Version:**
Installer:1.5.1

**App Version:**
App: 

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app

**Describe the bug**
it says error halfway while downloading modpack and stops 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'ftb launcher'
2. Click on 'launch modpack '
3. wait 

**Expected behaviour**
I should be able to download modpacks 
**Screenshots**

**Additional context**

**Comment by Gaz492** [comment]
Hi,

If you are still having issues with downloading modpacks please open a new issue and provide all the information requested by the bug template.
