### ISSUE TITLE
[Feature request] Advisories

### ISSUE THREAD

**Issue by jamierocks** [FTBTeam/FTB-App#122]
**Is your feature request related to a problem? Please describe.**

Some pack versions may have game-breaking bugs (bug that corrupts worlds, or prevents the game from launching), or mods that are found to be malicious.

To be clear I am not talking about every issue, I am talking about issues that are particularly severe - the only issue I can think of at this time is https://github.com/FTBTeam/FTB-Omnia/issues/2, where players are unable to play the game.

**Describe the solution you'd like**

It would be nice if the modpacks.ch API had a system to expose advisories - notes attatched to packs / pack versions to document these issues.

An example for FTB Omnia 1.0.0 could be:

```json
    "advisories": [
        {
            "severity": "warn",
            "message": "This build contains a version of MineTogether that prevents players from playing if they decline the MineTogether Privacy Policy. This is fixed in newer versions.",
            "url": "https://github.com/FTBTeam/FTB-Omnia/issues/2"
        }
    ]
```

Where `severity` could inform the client as to how to interpret the advisory; `message` would be the text; and `url` could be an optional "Learn More" link.

**Describe alternatives you've considered**

I suppose there is not absolute need to have a system for this, it could be included in the pack description or version changelog (in this case, there is no issue here).

However, I believe that having a system would work best here:
- It would allow external consumers of the API to be able to consume the advisories easily.
- The App **could** display these advisories when a player goes to install a pack.

**Additional context**

**Comment by CH-Paul-T** [comment]
As the person who wrote this API - My philosophy is, if the version is that broken, the pack author should pull it.

**Comment by jikuja** [comment]
As developer of the previous launcher:

People does not read any information, warning or error dialogs unless game crashes. Even then they tend to ignore all messages which are displayed by the launcher before starting game/vanilla launcher and read final two lines from the log.
