### ISSUE TITLE
[Bug] Starting up the App

### ISSUE THREAD

**Issue by tokizowa** [FTBTeam/FTB-App#123]
**Operating System:**
OS:Windows 10 Home

I've downloaded and installed the new launcher to give it a try and i'm having an issue that i haven't seen reported on the forums yet.

Most of the time when i go to launch the new application, and i get this window

![image](https://user-images.githubusercontent.com/64554263/80635475-e9dba680-8a29-11ea-8476-3c39b6194855.png)

and it just sits there. I've left it up and I've gone somewhere for a couple hours and its still at that screen.

Any help or ideas to try to get past this?

**Comment by Rushmead** [comment]
Could you please provide me the logs of the %appdata%/ftb-app/logs/main.log (upload the contents to https://pste.ch) as well as %appdata%/FTBA/launcher.log and %appdata%/FTBA/error.log

**Comment by tokizowa** [comment]
%appdata%/ftb-app/logs/main.log
https://pste.ch/ejokikexig.sql

%appdata%/FTBA/launcher.log
https://pste.ch/lonanitapu.sql

%appdata%/FTBA/error.log
https://pste.ch/ayezehuziv.sql

**Comment by Gaz492** [comment]
Hi,
The issues you were having with starting the app should now be resolved in newer versions of the app.
If you continue to have issues with openign the app please open a new issue.
