### ISSUE TITLE
[Bug] Can't install/start the new FTB APP (JVM could not be started)

### ISSUE THREAD

**Issue by Sulavin** [FTBTeam/FTB-App#125]
I have a bit trouble with installing the new FTBApp.

**Operating System:**
OS: Windows 10 Pro Build 17763

**Installer Version:**
Installer: "FTBA_windows-x64_1_0_8.exe

**App Version:**
App: -

**UI Version:**
UI: -

**Log Files:**
[i4j_nlog_7.log](https://github.com/FTBTeam/FTB-App/files/4559871/i4j_nlog_7.log)
[i4j_nlog_8.log](https://github.com/FTBTeam/FTB-App/files/4559872/i4j_nlog_8.log)
[i4j_nlog_9.log](https://github.com/FTBTeam/FTB-App/files/4559873/i4j_nlog_9.log)
[i4j_nlog_10.log](https://github.com/FTBTeam/FTB-App/files/4559874/i4j_nlog_10.log)

**Describe the bug**
When i start the "FTBA_windows-x64_1_0_8.exe" the install4j Wizard downloads the Java Runtime Environment. After that i get the error below.
![2020-04-30_18h25_44](https://user-images.githubusercontent.com/64605298/80738426-5384af00-8b15-11ea-84ad-7cf86031fae7.png)

the last lines in the log are only :
`[65:8] used stack size 0
[65:16] Creating JVM
[65:34] ERROR: could not initialize JVM
[65:34] ERROR: Could not start JVM
[65:106] Java window visible`

I deactivated full Antivirus (Kaspersky) and Firewall.

I also tried different Heap size's like 1Gb up to 10Gb.

![2020-04-30_18h37_09](https://user-images.githubusercontent.com/64605298/80738520-744d0480-8b15-11ea-8ea4-9fd9d9a08c40.png)

at this point i don't actually have a clue what to try else.

**Comment by Sulavin** [comment]
Btw other Java Apps work fine. For example JDownloader 2

**Comment by mowense** [comment]
up, i have the same problem here :(

**Comment by sketchmacaw** [comment]
Same here

**Comment by Jake-E** [comment]
Please see the comments in #77 to see if any of the information in there fixes your issues.
If not, please comment with the extra debug information per Cloudhunters post.
