### ISSUE TITLE
[Bug] KubeKS scripts aren't overwritten/deleted when updating/downgrading

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-App#127]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: not sure

**App Version:**
App: 1.0.8

**UI Version:**
UI: fa03e62e

**Log Files:**
https://pste.ch/osazocokol

**Describe the bug**
Academy 1.1.0 installed
![image](https://user-images.githubusercontent.com/15698722/81082243-a2856800-8eb8-11ea-8a60-8edb7680a4e2.png)

Updated to 1.2.0
![image](https://user-images.githubusercontent.com/15698722/81082332-c0eb6380-8eb8-11ea-9f0e-622feb8b8816.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Install FTB Academy
2. Check /kubejs/, there's no dynamic_trees_warning.js
2. Downgrade to 1.1.0
3. Check /kubejs/, there is now a dynamic_trees_warning.js, which is correct
4. Upgrade to 1.2.0
5. Check /kubejs/, the dynamic_trees_warning.js didn't get deleted

**Expected behaviour**
dynamic_trees_warning.js should have been deleted

**Comment by aaronhowser1** [comment]
The launcher downloaded 1.2 first. That was the update that added this line `addSimpleOverlay("finished_school", "academy.overlay.finished_school.title", "academy.overlay.finished_school.1");` to `overlays.json`.

When I downgraded to 1.1, where that line shouldn't exist, it was still there.

**Comment by Cloudhunter** [comment]
This should be fixed in the latest develop build. If people would like to test it, you can find it here: https://apps.modpacks.ch/FTBApp/develop/1.0.9dev-develop-9-24c0779986/FTBA_windows-x64_1_0_9dev-develop-9-24c0779986.exe

**Comment by Cloudhunter** [comment]
Now in release
