### ISSUE TITLE
Not finding Modpacks[Bug]

### ISSUE THREAD

**Issue by YamiNoRyu** [FTBTeam/FTB-App#128]
**Is your feature request related to a problem? Please describe.**
the Problem is when installing the New launcher App from FTB it doesnt recognize the earlier Modpacks you have installed, ergo any changes you have done to the modpack by adding new mods ect.
**Describe the solution you'd like**
Great solution would be to let the new launcher be installed over the old one or find the modpack folders , For example, when installing a question popup asking if you have already installed modpacks and then asking for the location so that the new launcher automatically integrated the "old" modpacks that you have already installed and adds them into its own interface or something like that 

**Describe alternatives you've considered**

**Additional context**

**Comment by Jake-E** [comment]
Are you talking about your legacy launcher modpacks not moving into the new App?
Please provide more information, including versions/OS information.
