### ISSUE TITLE
Upload launcher.log and error.log from app

### ISSUE THREAD

**Issue by ewancolyer** [FTBTeam/FTB-App#13]
An option for users to go into settings and click "send logs to server", then give the user an ID for the upload. This would then send the logs off to whatever system.

This would make it easier to troubleshoot issues with less technically inclined people.

**Comment by Jake-E** [comment]
@Gaz492 @Rushmead could we get some feedback when logs are uploaded? Unsure currently how best to implement that.

See https://github.com/FTBTeam/FTB-App/commit/3663dc951689deedf756c26433a9351b0f1e8c1e#diff-3e1c024da3c5134c611acb257eafa7e1R138
