### ISSUE TITLE
FTB Launcher detected as virus

### ISSUE THREAD

**Issue by ThatAlecs** [FTBTeam/FTB-App#130]
I don't know what caused it but while I finished downloading FTB Academy the download stopped at 100% and I restarted the app then my antivirus closed it and identified it as IDP.generic.

AV: avast

**Comment by jikuja** [comment]
Which file was detected as virus? Exact filename would be help.

**Comment by manmaed** [comment]
Just to make sure check to make sure avasts program and virus defomotopms are up todate as this may cuase this

**Comment by Jake-E** [comment]
If you continue having issues feel free to re-open.
