### ISSUE TITLE
Outdated java runtime

### ISSUE THREAD

**Issue by ofer-dev** [FTBTeam/FTB-App#131]
**Operating System:**
OS: Windows

**Installer Version:**
Installer: 1.0.8

**App Version:**
App: 1.0.8

**UI Version:**
UI:  fa03e62e

**Describe the bug**
The JREs bundled with the app are significantly outdated.
The openj9 jre is 2 versions behind. 11.0.5 vs 11.0.7
The hotspot jre is 24 versions behind. 8.0.51 vs 8.0.251
Aside from missing potential performance improvements, these version also have many unpatched vulnerabilities. 

**Expected behaviour**
Update to latest openj9/hotspot jre.

Thanks
Ofer

**Comment by jikuja** [comment]
Just commenting about background story of the JRE.

JRE bundle comes with Mojang's minecraft launcher. Mojang is distributing that version to maintain some hardware compatibility(1),

Changing it by FTB App probably requires lot of work and breaks support(1) for older hardware.

(1) https://github.com/LWJGL/lwjgl/issues/119#issuecomment-173782455

**Comment by Cloudhunter** [comment]
I'm not too concerned about the bundled JRE being that out of date, and the 8.0.51 is the Vanilla launchers issue. We'll bump up our OpenJ9 version at some point however, when we have the time to test it fully.
