### ISSUE TITLE
Multiple users cannot launch the game after Omnia 1.3.0 update. Issue 1 of 2

### ISSUE THREAD

**Issue by chadbob** [FTBTeam/FTB-App#132]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: Omnia 1.3.0

**App Version:**
App: 1.0.8

**UI Version:**
UI: fa03e62e

**Log Files:**
Put links to your logs here
https://pste.ch/kutugibiqe

**Describe the bug**
We updated to 1.3.0, Press play the Minecraft launcher opens and when you press Play you get a "Sorry, unable to start Minecraft, please check your configuration."

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to FTB Launcher with Omnia 1.2.0 already installed, 
2. Click on FTB Omnia Versions tab, Update to 1.3.0, Press Play and wait for the Minecraft Launcher to open, 
3. Press play

**Expected behaviour**
I expect the game the launch

**Screenshots**
![image](https://user-images.githubusercontent.com/64994707/81357436-a32d2280-90a1-11ea-985f-897af84821fb.png)

**Additional context**

**Comment by Jake-E** [comment]
Does this still happen after another update? Some files were missing but this should be fixed.

**Comment by Gaz492** [comment]
If this issue is still happening please open a new issue.
