### ISSUE TITLE
[Bug] Wrong forge version on Inventions

### ISSUE THREAD

**Issue by StealthDrifter** [FTBTeam/FTB-App#134]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: 64x 1_0_8

**App Version:**
App: 1.0.8

**UI Version:**
UI: fa03e62e

**Log Files:**
https://pste.ch/rajifisezi

**Describe the bug**
Wrong forge version

**To Reproduce**
Steps to reproduce the behaviour:
1. Download inventions on the FTB app
2. Run inventions from the FTB app
3. See error

**Expected behaviour**
Able to play the modpack

**Screenshots**
https://cdn.discordapp.com/attachments/560188834592063488/708317809175953418/unknown.png https://cdn.discordapp.com/attachments/560188834592063488/708317647888187442/unknown.png

**Comment by Sunekaer** [comment]
Issues has been fixed, restart the launcher and install the pack again.
