### ISSUE TITLE
[Bug] Failed to read /bin/launcher_profiles.json

### ISSUE THREAD

**Issue by Alge** [FTBTeam/FTB-App#137]
**Operating System:**
OS: ubuntu 20.04

**Installer Version:**
Installer: 1.0.8

**App Version:**
App: 1.0.8

**UI Version:**
UI: 

**Log Files:**
Error log: https://hastebin.com/ucevuruqop.sql
launcher log: https://hastebin.com/oraqokexec.sql

**Describe the bug**
Install of ftb omnia halts when setting up the launcher

**To Reproduce**
install ftb omnia

**Expected behaviour**
ftb omnia should install :)

**Additional context**
SEVERE: Failed to read /home/alge/FTBA/bin/launcher_profiles.json <- this seems to be the problem

**Comment by starlingfire** [comment]
What are the permissions of that file?

`ls -la launcher_profiles.json `

**Comment by Alge** [comment]
it wasn't created at all

**Comment by pskfyi** [comment]
I also had this issue. I just created an empty file with that name at the expected location. That allowed the application to move forward, but it surfaced #149.

**Comment by Jake-E** [comment]
Your log files look empty to me when visiting the hastebin links.
Can you use the Upload logs button on the app (in the settings menu)?

**Comment by Gaz492** [comment]
As Jake mentioned the log linked above appears to be empty, if you are still having this issue please open a new issue.
