### ISSUE TITLE
[Feature request] More human-readable names for downloaded modpacks in the instances folder

### ISSUE THREAD

**Issue by Venom31** [FTBTeam/FTB-App#138]
**Is your feature request related to a problem? Please describe.**
Being used to using the old FTB launcher, it was very handy to see all packs laid out with their respective names in FTB folder. But now, with FTB App, the downloaded packs are in the "instances" subdirectory, with cryptic unreadable names. I used to backup well-developed worlds from FTB, which will become much more error-prone with using the FTB App.

**Describe the solution you'd like**
Would it be possible to save the pack instances by their more human-readable names?

**Describe alternatives you've considered**
If not, and the hash-code-confetti must be in each instance's name on the disk, would it be possible to, say, append or prepend them with the modpack name, so that the players don't have to guess?

**Additional context**
Also, will those instance codes change over time? I'm using some automated means for backup, and it might get very bad if the intended backup location changes over time.

**Comment by Jake-E** [comment]
Each instance has it's own UUID, these won't be changing. If you need more information about the instance, each folder will have an instance.json inside of it. You can parse it for more information.

There's an open folder button on each instance via the App that will open that instances folder too.

**Comment by Venom31** [comment]
Thank you for the reply! I'm relieved, at least they stay the same.
