### ISSUE TITLE
Error while trying to install Omnia

### ISSUE THREAD

**Issue by jcaballero90** [FTBTeam/FTB-App#14]
A friend is getting this error when he tries to install Omnia:
https://gyazo.com/84598305add6d5078b08e1d64565b8ea

[error.log](https://github.com/FTBTeam/FTB-App/files/4423535/error.log)
[launcher.log](https://github.com/FTBTeam/FTB-App/files/4423536/launcher.log)

**Comment by Cloudhunter** [comment]
Try going to Settings, scroll down to the bottom and change the download thread count:

![image](https://user-images.githubusercontent.com/1624192/78300523-898f3d00-752f-11ea-92a7-9f786dafac6a.png)

Can you let me know how many CPU cores/threads you have so that we can look into this?

**Comment by jcaballero90** [comment]
It worked, he can install now. He has a potato PC:
Intel dual Core p8700  2.53ghz
