### ISSUE TITLE
[Bug] No icon on Linux ALT+TAB

### ISSUE THREAD

**Issue by enderger** [FTBTeam/FTB-App#140]
**Operating System:**
OS: Kubuntu 20.04 with OpenboxWM

**Installer Version:**
Installer: IDK

**App Version:**
App:  1.0.8

**UI Version:**
UI: fa03e62e

**Log Files:**
N/A

**Describe the bug**
There is no icon for ALT+TAB on a linux system. I presume this also applies to system trays

**To Reproduce**
Steps to reproduce the behaviour:
1. Install this on Linux with OpenBoxWM
2. Launch it
3. ALT+TAB to see the bug

**Expected behaviour**
The icon to be in the ALT+TAB menu

**Comment by Gaz492** [comment]
#116
