### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by Biciklee** [FTBTeam/FTB-App#141]
**Is your feature request related to a problem? Please describe.**

NO

**Describe the solution you'd like**

Pls somebody tell me why not available the FTB team releated mods on the Twitch launcher.
(i mean "politic, money")

**Describe alternatives you've considered**

pls put the mods available on twitch launcher

**Comment by mworzala** [comment]
The mods are still available on CurseForge, the modpacks are still there, they just arent getting updated anymore. I believe they said the mods are available under LatvianModder's account.

**Comment by Rushmead** [comment]
This repository is not for discussion on the FTB mods. You will find their own repositories for those mods.

**Comment by Biciklee** [comment]
@mworzala thanks
