### ISSUE TITLE
[Bug]Changed JRE seetings are not saved

### ISSUE THREAD

**Issue by Hojosa** [FTBTeam/FTB-App#142]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer:1.0.5

**App Version:**
App: 1.0.8

**UI Version:**
UI: fa03e62e

**Log Files:**

**Describe the bug**
After launching a Modpack, the MC Launcher will not save any changes to "Java Executable".

**To Reproduce**
Launch any Modpack. (tested with FTB Revelations)
Installations - Edit
Java Executable - set to any other installed JRE/JDK (tested with adoptjdk openj9 install)

**Expected behaviour**
Keep the changed setting

**Screenshots**
![grafik](https://user-images.githubusercontent.com/7524822/82216082-b39e9200-9918-11ea-8a1e-a0250e5c202b.png)

**Additional context**
While its understandable that the JRE provided by mojang is used, we should be able to change to a installed JRE if we want. This works with the Vanilla Launcher standalone.

**Comment by Sunekaer** [comment]
If you go to Modpacks/My Modpacks hover over the pack, click the 3 dots and click the settings tab, and enter your arguments in the "CUSTOM ARGUMENTS" box

**Comment by Rushmead** [comment]
The behaviour you are seeing is intended. Profiles are updated every time you press the "Play" button to ensure that it is up to date. This means that any settings that are changed outside of the FTB App will not persist.

This is more of a feature request to be able to change the JRE which already exists here #1 as such will close this issue.
