### ISSUE TITLE
[Bug] Internal link in news post not removed

### ISSUE THREAD

**Issue by Sunekaer** [FTBTeam/FTB-App#143]
**Operating System:**
OS: Windows

**App Version:**
App: 1.0.8

**UI Version:**
UI: fa03e62e

**Log Files:**
https://pste.ch/exosinejud

**Describe the bug**
internal link doesnt get removed from news posts

**To Reproduce**
Steps to reproduce the behaviour:
In each news right about the "Continue Reading..." is a line of text that is the same as the title and its also a link that you can click and it opens inside of the App.

**Expected behaviour**
This link was supposed to be filtered out by this line of code https://github.com/FTBTeam/FTB-App/blob/9a2e38605b24cf97e86bbd46396e43a70935bf84/src/modules/news/actions.ts#L19 but that doesn't work anymore

**Screenshots**
https://s1.sunekaer.com/i/19-05-2020_00-36-24_%25pn.gif

**Comment by Sunekaer** [comment]
Fix change linked line to const content: string = item['content:encoded'].replace(/<a\b[^>]* class="link link--internal">(.*?)<\/a>/gi, '');

**Comment by Rushmead** [comment]
Thanks, Sunekaer, I've pushed changes for this :)
