### ISSUE TITLE
[Bug] Opening FTB App without internet fails to display already installed modpacks

### ISSUE THREAD

**Issue by Spiker985** [FTBTeam/FTB-App#144]
**Operating System:**
OS: Windows 10 1909 build 18363.836

**Installer Version:**
Installer: FTBA_windows-x64_1_0_8

**App Version:**
App: 1.0.8

**UI Version:**
UI: fa03e62e

**Log Files:**
https://pste.ch/umirebufeb

**Describe the bug**
No locally installed modpacks will load if the host's internet is offline upon starting the host

**To Reproduce**
Steps to reproduce the behaviour:
1. Disconnect internet
2. Start computer
3. Attempt to start FTB App - this must be the first time starting the app since power on, otherwise the modpack will load in the UI
4. Click Cancel on the "Internet connection - FTBApp" dialog
5. The FTB App loads, however, navigating to "My Modpacks" nets an empty screen

**Expected behaviour**
The FTB App shouldn't need to contact the internet in order to display "My Modpacks"

**Screenshots**
Locally installed modpack, with Internet
![image](https://user-images.githubusercontent.com/7829451/82272968-c7aab980-9941-11ea-83f9-2429754b027f.png)
Dialog without internet, before the app launches
![image](https://user-images.githubusercontent.com/7829451/82273092-1bb59e00-9942-11ea-908f-04615ac6441b.png)

**Comment by Rushmead** [comment]
This should be fixed in the next release :)

**Comment by Spiker985** [comment]
Woot!
