### ISSUE TITLE
[Feature request] it should be made clear that the serverinstall filename alters the behavior of the executable

### ISSUE THREAD

**Issue by Kynolin** [FTBTeam/FTB-App#145]
**Is your feature request related to a problem? Please describe.**

Yes. The serverinstall binary uses its filename to determine what mod ID and version ID should be used for install, but that is not made clear by the binary itself, and that results in confusing behavior if the filename is changed such as renaming "serverinstall_6_51" to "ftb_server_install_omnia_1.4.0".

**Describe the solution you'd like**

The FTB Desktop App or serverinstall binary should at least provide more clarification that the downloaded server installer is not unique to that mod/version, and the filename is used to determine the mod ID and version ID for automated installations.

**Describe alternatives you've considered**

I've used the mod ID and version ID from the API to provide the installer with the appropriate information if named differently.

**Additional context**

This is primarily for automated installations. I build/run my server via Docker, and not knowing the serverinstall binary used its filename resulted in manual steps required to update the Dockerfile to point to the correct filename, when in fact I did not need to download a new server installer to get the latest version of the desired modpack. The FTB Desktop app just says "Download Server" and then "Windows/Linux/MacOS".

As an end-user of the FTB Desktop app, when I download serverinstall_6_51, there's no indication where that number came from or why it's important.

While I'm here, I'd also really love to see the updated date/time displayed by the app for each version. It's already available via the API, but it's not displayed anywhere in the app.

**Comment by Jake-E** [comment]
Suggestions on how we make this clearer? Not sure it's overly important for the average end-user.

**Comment by mworzala** [comment]
Kynolin is the average end user... I also think the name is confusing. 

This is actually another good usage for slugs instead of ids (#150), the file name could be something like serverinstall_ftb_omnia_51 instead which at least lets you tell which is which if you download it.

**Comment by Kynolin** [comment]
The simplest suggestion I can make is to at least inform the user that the "server_installer_x_y" filename is important and relevant to the installation process. This information is not available in the app, nor is the mod/version ID, and it's not entirely clear when running the installer.

If I run `./serverinstall_6_51 --help` it includes an example command:
```
Example: serverinstall_6_51 47 295 --path /home/ftb/omnia
```
If I run that command, it starts installing Omnia 1.4.0 as I would expect.

If I had changed the name of the file beforehand (like naming it something that makes sense to me on my local system as users often do), the help message shows the changed filename in the example, and it crashes with a NullPointerException when running the example command. If I run it without arguments, it asks me to enter a search term. The average end-user would not know why they now need to search for the correct modpack when they already downloaded it from the appropriate section of the app.

If both the app had a little note by the server download link, and the installer also made this more clear, both in the help message and execution, I would very quickly know what caused the problem if I changed the filename.

I would personally prefer internal metadata not being stored in a generic looking filename the user downloads, but that is obviously more involved. Adding a little bit of extra text to inform the user is simple and helps reduce frustration on both ends.

Here is an example below:

```
root@c39dc566bb24:~/ftb_server# ./ftb_omnia_1.4.0_serverinstall --help
                      _                  _              _
                     | |                | |            | |
  _ __ ___   ___   __| |_ __   __ _  ___| | _____   ___| |__
 | '_ ` _ \ / _ \ / _` | '_ \ / _` |/ __| |/ / __| / __| '_ \
 | | | | | | (_) | (_| | |_) | (_| | (__|   <\__ \| (__| | | |
 |_| |_| |_|\___/ \__,_| .__/ \__,_|\___|_|\_\___(_)___|_| |_|
                       | |
                       |_|
 modpacks.ch server downloader - build 13c20a7

Usage:
ftb_omnia_1.4.0_serverinstall - Start an interactive download and install.
ftb_omnia_1.4.0_serverinstall searchterm - Search for a modpack and start interactive download and install.
ftb_omnia_1.4.0_serverinstall <packid> - Download and install the latest Release version of a modpack by id.
ftb_omnia_1.4.0_serverinstall <packid> <versionid> - Download and install a specific version of a modpack by id and version id.

Additional arguments:
--help - Print this help information.
--path - Specify an install path instead of current working directory.
--auto - Automatically install a pack for filename based pack installs.
--noscript - Don't generate start.sh and start.bat files.
--latest - Ignore any specific modpack version id provided and always download the latest.
Example: ftb_omnia_1.4.0_serverinstall 47 295 --path /home/ftb/omnia

root@c39dc566bb24:~/ftb_server# ./ftb_omnia_1.4.0_serverinstall 47 295 --path /home/ftb/omnia
                      _                  _              _
                     | |                | |            | |
  _ __ ___   ___   __| |_ __   __ _  ___| | _____   ___| |__
 | '_ ` _ \ / _ \ / _` | '_ \ / _` |/ __| |/ / __| / __| '_ \
 | | | | | | (_) | (_| | |_) | (_| | (__|   <\__ \| (__| | | |
 |_| |_| |_|\___/ \__,_| .__/ \__,_|\___|_|\_\___(_)___|_| |_|
                       | |
                       |_|
 modpacks.ch server downloader - build 13c20a7

Exception in thread "main" java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:840)
        at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.NullPointerException
        at net.creeperhost.ftbserverdownloader.ServerPack.lambda$downloadManifest$1(ServerPack.java:39)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
        ... 11 more
```
