### ISSUE TITLE
[Bug] Can't launch modpacks; launcher.exe is not a valid Win32 application

### ISSUE THREAD

**Issue by pskfyi** [FTBTeam/FTB-App#149]
Thanks for this project, it's very inspiring. I'm having issues getting started.

**Operating System:**
OS: Windows 10 Pro 1903

**Installer Version:**
Installer: FTBA_windows-x64_1_0_8.exe

**App Version:**
App: 1.0.8

**UI Version:**
UI: fa03e62e

**Log Files:**
https://pste.ch/ayopujiraw

**Describe the bug**
Given an installed modpack, if I click the play icon, nothing happens.
`error.log` indicates that "launcher.exe" cannot be executed as it is not a valid Win32 application.
Happens on Omnia and Skyfactory - haven't tried others.

**To Reproduce**
Attempting to run any modpack induces the behavior.

**Comment by pskfyi** [comment]
Small update with additional info. I tried to install the app on a different machine and had no issues. Sadly this machine is not powerful enough to play for extended sessions though.

Encouraged by this I did a full reinstall on my first machine. Still no luck, and same errors in the logs.

The only notable difference between the two machines, as far as I can tell, is one is Win 10 Home and the other is Win 10 Pro. It worked on Home, but not Pro.

**Comment by Jake-E** [comment]
Is the launcher.exe actually present in that directory? Can you open it manually?

**Comment by pskfyi** [comment]
The launcher is present in that directory, and attempting to open it manually throws the same error. It seems the file is corrupted somehow. I'm happy to manually replace the launcher file to aide investigation.

**Comment by Jake-E** [comment]
@pskfyi give downloading it manually and putting it in that location a go..
I assume you're not using a 32bit windows?

**Comment by pskfyi** [comment]
@Jake-E that is correct, I'm on 64-bit.

Where can I find the `launcher.exe`? A search of this repo did not reveal a file by that name.

**Comment by Jake-E** [comment]
It's the Minecraft launcher, you can download it from the Minecraft website.

**Comment by Gaz492** [comment]
If you are still having issues with this please open a new issue.
