### ISSUE TITLE
[Feature request] Pack Slugs

### ISSUE THREAD

**Issue by jamierocks** [FTBTeam/FTB-App#150]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Pack slugs for packs that are human-readble and can be used in place of pack ids.

For example:
- 35, FTB Revelation, `ftb-revelation`
- 6, FTB Omnia, `ftb-omnia`

**Describe alternatives you've considered**

The suggested format above could be similar to how ATLauncher gives out slugs, e.g. `FtbRevelation`.

**Additional context**

With regards to adding third-party packs to the system, this could cause problems if the slug is user-generated - so I have a few suggestions:
- Restrict the use of `ftb-*`
- Could always add `ftb-revelation.35` for example (though I would suggest not, see Technic as an example)

I would take note of Technic on this occasion - all packs have a unique slug based on their names (with few exceptions*). e.g. tekxit-3-official-1122 is for Tekxit 3 (Official) 1.12.2.

* Renamed packs retain their original slug, e.g. Tekkit Classic's slug is `tekkit`.

**Comment by Jake-E** [comment]
I don't see a real need for this? This isn't something the App would use nor the FTB website.
Use cases?

**Comment by mworzala** [comment]
Legibility

Not sure if there are plans for this, but if there is going to be a frontend to modpacks.ch of any sort, a url something like https://modpacks.ch/modpacks/ftb-omnia is much nicer for the end user than https://modpacks.ch/modpacks/6. 

This also applies to the API but less convincing because it shouldn't really be used manually.

**Comment by Slowpoke101** [comment]
As things stand I dont really see how this would provide any benefit to our users.
