### ISSUE TITLE
[Bug] App doesn't respect default memory settings defined by pack

### ISSUE THREAD

**Issue by Naxanria** [FTBTeam/FTB-App#151]
OS: Windows 10
App: 1.0.8
UI: fa3e62e

Logs: https://pste.ch/kekevijiqi

App seems to pull memory settings from the settings.json in the app/bin/ folder instead of using the packs recommendations.
This setting is not editeable inside the launcher it self.

in the modpack.json (Material Energy pack):
``` json
 "versions": [
        {
            "specs": {
                "id": 69,
                "minimum": 4092,
                "recommended": 4092
            },
            "id": 53,
            "name": "1.0.5",
            "type": "Release",
            "updated": 1590164605
        }
    ],
```

![image](https://user-images.githubusercontent.com/3246224/82696583-95fa6100-9c67-11ea-8f96-aa60a7c26587.png)

**Comment by EmberQuill** [comment]
I'm experiencing the same issue. Memory is always initially set to 3GB no matter what the modpack recommends. I have to change it manually for each pack.

**Comment by ThePaul-T** [comment]
This should be fixed in the upcoming version.
