### ISSUE TITLE
FTBApp Stoneblock 2 1.18 update

### ISSUE THREAD

**Issue by Nerxxy** [FTBTeam/FTB-App#153]
i updated stoneblock 2 to 1.18 and it wouldnt launch, i tried downgrading, that then proceeded to also not launch, after that i upgraded again and its still not launching, restarted my pc (while on 1.18) then downgraded to 1.17 it then worked fine, upgraded again and still wouldnt launch (fyi when i say "it didnt launch" i mean i got as far as the vanilla minecraft launcher)

**Comment by Jake-E** [comment]
No logs provided, so there's not much we can do here.

**Comment by Nerxxy** [comment]
> No logs provided, so there's not much we can do here.

i didnt know i had too since i wasnt told too, plus i wouldnt know where to find them but ok
