### ISSUE TITLE
[Bug] Pack update not appearing in the FTB App

### ISSUE THREAD

**Issue by Fionnualla** [FTBTeam/FTB-App#155]
**Operating System:**
OS: Windows 10

**Log Files:**
https://pste.ch/futonidovi

**Describe the bug**
The update of FTB Pyramid Reborn 3.0 - 3.1.2, as put on discord yesterday, does not appear in the FTB App

**Additional context**
I  put the question, whether pack updates should appear in the FTB App on Discord. And I got the answer that they should appear, and if not, that I should open an issue what I now did.
Thanks :)

**Comment by Cloudhunter** [comment]
3.1.2 is showing on the app for me. Due to caches, it may not be instant to show new versions.

If you notice any further delays with packs, please feel free to let us know so we can make sure.

**Comment by Fionnualla** [comment]
How can I check whether it is due to caches that I still cannot see the new versions?

**Comment by Fionnualla** [comment]
Is there anybody here who reads this and can answer to me? Answer to my question in the last comment ...
Thanks :)
