### ISSUE TITLE
[Bug] I have an empty square in My Modpacks

### ISSUE THREAD

**Issue by AKTheKnight** [FTBTeam/FTB-App#157]
**Operating System:**
OS: W10

**Installer Version:**
Installer: Not a clue, installed it ages ago

**App Version:**
App: 1.0.8

**UI Version:**
UI: fa03e62e

**Log Files:**
https://pste.ch/fewurupija

**Describe the bug**
There is a blank square when looking in Home and My Modpacks

**Expected behaviour**
No empty spaces

**Screenshots**
![image](https://user-images.githubusercontent.com/7502848/83523237-c947b600-a4d9-11ea-95a3-b5210c3bd99a.png)

![image](https://user-images.githubusercontent.com/7502848/83523242-ccdb3d00-a4d9-11ea-8faf-9c9c2b8882fe.png)

**Comment by manmaed** [comment]
is it still there?

**Comment by AKTheKnight** [comment]
Nope, gone with the latest update :)
It looks like it was FTB Sky Odyssey causing the blank square.

![image](https://user-images.githubusercontent.com/7502848/83821734-1472ec00-a6c7-11ea-8ffc-a41e3946eed5.png)

**Comment by manmaed** [comment]
So #BlameGaz #BlameSlow #BlameRush :P
