### ISSUE TITLE
Server download not working with FTBApp

### ISSUE THREAD

**Issue by Hexa-ATS** [FTBTeam/FTB-App#159]
**Operating System:**
OS: Windows 10

**App Version:**
App: 1.0.9

**UI Version:**
UI: 0ef60e23

**Describe the bug**
When you download the server download and run the start the server doesn't start up, instead it just stops and ends the program, like a crash.

**To Reproduce**
1. Go to 'A FTBApp modpack and go to versions'
2. Click on 'Download Server'
3. Run the installer
4.Run start.bat or edit and run it
5. See error

**Expected behavior**
Server Launch

**Screenshots**
![Capture](https://user-images.githubusercontent.com/66444783/83814950-436c6c00-a68d-11ea-81a0-a41964dd8f59.PNG)

**Comment by manmaed** [comment]
This looks like the java installation is broken somehow i would suggest you reinstall Java and retry

**Comment by Hexa-ATS** [comment]
I reinstalled java and the error still persists.

**Comment by jikuja** [comment]
The java script is using is 32-bit version. The script requests server JVM with `-server` argument. 32-bit JVM does not ship it and launch fails.

Fix: install and use 64-bit java 8.

**Comment by Hexa-ATS** [comment]
I reinstalled 64-bit and it seemed to be working fine until this line pops up ```Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Server thread"```

**Comment by Cloudhunter** [comment]
This is not our issue - first your Java installation was 32 bit, and now there isn't enough memory.
