### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by CVaranese** [FTBTeam/FTB-App#161]
**Is your feature request related to a problem? Please describe.**
I want to run it on an ARM machine that I have, but the provided ftb-app executable is only compiled for x86-64.

**Describe the solution you'd like**
Provide an ARM executable (or instructions on compiling from source)

**Describe alternatives you've considered**
No considerations

**Additional context**
That's all I got

**Comment by Gaz492** [comment]
As the current vanilla launcher does not natively support ARM based devices this is not currently something that we would look into, however if the vanilla launcher adds support for ARM devices we will take another look at this.
