### ISSUE TITLE
[Bug] FTB App not Notarized

### ISSUE THREAD

**Issue by s0ph0s-2** [FTBTeam/FTB-App#163]
**Operating System:**
OS: macOS Catalina 10.15.5

**Installer Version:**
Installer: ?

**App Version:**
App: 1.0.9

**UI Version:**
UI: 0ef60e23

**Log Files:**
[Log Files Link](https://pste.ch/elovomicuw)

**Describe the bug**
The FTB App is not [notarized](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution), which causes a scary-looking warning when attempting to launch the app on recent versions of macOS.

**To Reproduce**
Steps to reproduce the behaviour:
1. Ensure that System Preferences → Security & Privacy → Allow apps downloaded from: is set to “App Store and identified developers” (which is the most permissive setting available on macOS 10.15)
2. Download the FTB App disk image from the website
3. Open the disk image
4. Drag the FTB App to `/Applications`
5. Double-click the FTB App
6. Observe this warning: ![Screen Shot 2020-06-10 at 13 49 59](https://user-images.githubusercontent.com/20545101/84301130-51a10900-ab21-11ea-9266-7e55dc819b14.png)

**Expected behaviour**
I expect the FTB App to be notarized so that there is an “Open” button in the Gatekeeper dialog on first launch.

**Known Workaround**
I can right-click (⌃-click) the application and select Open, which presents a different dialog that allows me to ignore the security warning.
![Screen Shot 2020-06-10 at 13 51 35](https://user-images.githubusercontent.com/20545101/84301271-81e8a780-ab21-11ea-9db4-e93f99d74f04.png)
**Additional context**
The Electron app embedded inside the FTB app (`Contents/Resources/app/bin/ftbapp.app`) is also not notarized, and it is not in one of the directories where a notarization on the parent app bundle would cover it.

**Comment by Cloudhunter** [comment]
I'm aware of this. We are having some issues with the process of notarising using our packaging system. I am still working on a fix!
