### ISSUE TITLE
[Bug] Launcher won't open

### ISSUE THREAD

**Issue by Tw3n7y** [FTBTeam/FTB-App#164]
**Operating System:**
OS: Windows 10

**App Version:**
App: 1.0.8

**UI Version:**
UI: fa03e62e

**Log Files:**
https://paste.ee/p/23QDh

**Describe the bug**
When I click play, nothing happens.

**Expected behaviour**
The game's launcher should open.

**Comment by Cloudhunter** [comment]
That log is clearly a log of a Minecraft instance starting.

However, we have fixed some issues regarding launching the game in the latest build. Please restart your client to get the latest update.

**Comment by Tw3n7y** [comment]
I restarted the launcher, waited for the update to install, and nothing's changed.

**Comment by Cloudhunter** [comment]
Can you go through the steps you're doing, including what pack etc, and let us know what you're seeing at each step?

Providing a launcher log would also be useful. You can export them in the Settings page.

**Comment by Tw3n7y** [comment]
I'm playing Sky Odyssey 1.2.0 with an updated MineTogether mod because the previous version is broken.

Here are the logs: https://pste.ch/iwufezonuw
The version is 1.0.8

**Comment by Cloudhunter** [comment]
You still don't have the latest launcher version. Please bear with me whilst I check that the auto update functionality is working correctly.

**Comment by Tw3n7y** [comment]
I must've closed it while the it was happening, because I remember it auto-updating.

**Comment by Tw3n7y** [comment]
Is there a way to manually update it?

**Comment by Tw3n7y** [comment]
I've updated the launcher to version 202006121223-ac73c94902 and the game launcher still won't open.

**Comment by Cloudhunter** [comment]
Please provide up to date logs from the new version

**Comment by Tw3n7y** [comment]
https://pste.ch/wacagofahe

**Comment by Tw3n7y** [comment]
Someone please help

**Comment by Jake-E** [comment]
Fixed by removing the launcher_profiles.json file - it seems if it doesn't contain valid json things don't launch at all. Should probably try and catch it.
https://pste.ch/epowukujud

**Comment by essarn** [comment]
Had the same problem. Deleting ~/.ftba/bin/launcher_profiles.json solved the problem.

**Comment by Gaz492** [comment]
If anyone is still having these issues, please open a new issue.
