### ISSUE TITLE
[Feature request] Show download count for modpacks

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-App#165]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It's nice to see what packs have a high download count, so you can see which packs are the most popular

**Additional context**
My inflated ego also requires that I drool over my pack's download count, which I can't do right now

**Comment by Jake-E** [comment]
The API has the data required to show this, feel free to implement @Gaz492

**Comment by Gaz492** [comment]
Added for next release of the app
