### ISSUE TITLE
Download error when installing app [Bug]

### ISSUE THREAD

**Issue by essarn** [FTBTeam/FTB-App#166]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: Latest installer from the website.

**App Version:**
App: https://apps.modpacks.ch/FTBApp/release/202006121223-ac73c94902/FTBA_windows-x64_202006121223-ac73c94902.exe

**UI Version:**
UI: NA

**Log Files:**
Not sure if there's any logs since the app wont start in the first place.

**Describe the bug**
The installation wizard fails when downloading the app in step two. The installer complains about that there's no internet connection available but there is. When selecting that there is an internet connection does this behavior repeats itself. 

Steps to reproduce the behaviour:
1. Download the latest installer from the website
2. Launch it and go through the wizard
3. Fails when downloading the app

**Expected behaviour**
The app should install as expected without the proxy error. 

**Screenshots**
![FTBApp Connection Error](https://user-images.githubusercontent.com/16906089/84590984-24af6780-ae3b-11ea-9d0d-3055d6b93d2f.PNG)

**Comment by essarn** [comment]
Can confirm that his seems to be a regional issue. When connecting with a VPN to USA is everything working as expected. The problem seems to be with the northern region of Europe and or possible others.

**Comment by LiamRoels** [comment]
Can confirm this is happening. Thanks for noticing it is a regional issue. This got me past the download and allowed me to play!

**Comment by Sunekaer** [comment]
Download server works for me now, so for the people who still get "Could not connect to the download server" please open CMD and ping dist.creeper.host and send the IP here
