### ISSUE TITLE
[Bug] Creation of environment fails on macOS 10.15.4

### ISSUE THREAD

**Issue by TilBlechschmidt** [FTBTeam/FTB-App#170]
**Operating System:**
OS: macOS 10.15.4

**Installer Version:**
Installer: FTBA_macos_202006121223-ac73c94902.dmg

**App Version:**
App: Version 0.1.0 (0.1.0.135)

**UI Version:**
UI: Version 0.1.0 (0.1.0.135)

**Log Files:**
https://pste.ch/udociramiv

**Describe the bug**
Start the launcher, download Omnia and wait a few seconds. It crashes right after "Creating Environment ..." with a macOS popup reading "launcher quit unexpectedly":
![image](https://user-images.githubusercontent.com/5037967/85224958-08c53c00-b3ce-11ea-8bee-890ecb399d03.png)

**To Reproduce**
Listed above.

**Expected behaviour**
The mod pack downloads and starts.

**Screenshots**

**Additional context**
The instance folder only contains art.png and instance.json.
[instance.json](https://github.com/FTBTeam/FTB-App/files/4809461/instance.txt)

**Comment by Cloudhunter** [comment]
Does this now work for you?

**Comment by TilBlechschmidt** [comment]
I unfortunately can not confirm whether or not it works on macOS 10.15.4 as I have moved to macOS 10.16/11 as of Monday. On there it gets past the "Creating Environment" to the "Installing Vanilla Launcher" step, seemingly downloads the Minecraft Launcher into `~/.ftba/bin/Minecraft.app` (which seemingly completes as the launcher starts normally when executed manually). However, it gets stuck there with not much happening. I'll leave it sitting for a few minutes but this is definitely unexpected behaviour. Not sure if it relates to the original issue though or has a different root cause (due to the macOS Big Sur Beta).

Here is an up-to-date app log:
[https://pste.ch/umumovetok](https://pste.ch/umumovetok)

**Comment by Cloudhunter** [comment]
Closed for now as we have a more recent issue which I am looking into this on https://github.com/FTBTeam/FTB-App/issues/200
