### ISSUE TITLE
App loses instance folder settings during update[Bug]

### ISSUE THREAD

**Issue by HL971** [FTBTeam/FTB-App#175]
**Operating System:**
OS: Windows 10

**Installer Version:**
Auto update

**App Version:**
App: 202006252122-d54460713e

**UI Version:**
UI: 8ff6da98

**Describe the bug**
An auto update occurred on my FTB app instance. On loading the updated application, it was unable to locate any installed instances.
A quick review showed that it had changed my instance location setting to a default instance location, rather than the custom location I had specified at an earlier date.
I was able to change the location and restart the app to fix the issue.

**Expected behaviour**
The application should not change the instance location when updating to newer versions.

**Comment by dflor003** [comment]
Getting this as well. Also noticing that _NONE_ of the settings are saving. Even after restarting the app, the settings revert back to all of their defaults. I have my FTB App installed in a non-standard place (`C:\Games\`), so wondering if the latest update may have broken support for that.

**Comment by Hachuurui** [comment]
Same issue, none of the settings are saving and it ignores my instance settings. Also setup for non-standard due to ssd, so I'm using a data drive. Changing the setting also makes it to where it no longer recognizes the packs that were installed previously.

**Comment by danbates1452** [comment]
Something to note is that installing another pack forces the app to notice your existing instances.

**Comment by Frytas53** [comment]
Same issues as well, but I'm glad my save wasn't removed

**Comment by Cloudhunter** [comment]
Can you try this build and see if it works any better?

NOTE: Whilst I do not expect it to remove any files, you can never be too careful. _PLEASE_ make a copy of your instances first.

https://apps.modpacks.ch/FTBApp/develop/202006261544-5e96a4aa3d-develop/FTBA_windows-x64_202006261544-5e96a4aa3d-develop.exe

**Comment by Hachuurui** [comment]
Sure give me a minute and I'll let you know how it goes @Cloudhunter

**Comment by Cloudhunter** [comment]
New build which should resolve the above issue in the edit note too https://apps.modpacks.ch/FTBApp/develop/202006261616-19576ac1ac-develop/FTBA_windows-x64_202006261616-19576ac1ac-develop.exe

**Comment by Hachuurui** [comment]
This build also is working fine for me @Cloudhunter

**Comment by Cloudhunter** [comment]
Closed as fixed in new build
