### ISSUE TITLE
[Bug] UI - Installation bar shows name of last open modpack page instead of modpack being installed

### ISSUE THREAD

**Issue by curvinho** [FTBTeam/FTB-App#176]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer:

**App Version:**
App: 2020006261451-949e05dd0e

**UI Version:**
UI: 8ff6da98

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app

**Describe the bug**
When installing a modpack, whenever you open another modpack's page, it changed the name on the install progress bar to the page you're in and marks the modpack as installing. Seems like it's adding to queue automatically (but not actually installing)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to browse modpacks.
2. Start installing modpack.
3. While it's installing, browse other modpack pages (information page)

**Comment by Gaz492** [comment]
I believe this has been fixed in a newer version of the app.
If you still have this issue on a newer version of the app please open a new issue.
