### ISSUE TITLE
[Bug]  Settings Not saving

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-App#177]
**Operating System:**
OS: Windows

**Installer Version:**
Installer: NA 

**App Version:**
App: 202006261451-949e05dd0e

**UI Version:**
UI: 8ff6da98

**Log Files:**
https://pste.ch/uhajedimin

**Describe the bug**
None of the Settings are saved!

**To Reproduce**
1. Go to Settings
2. Change any settings (for Instance Location see To Reproduce Instance)
3. Change to other page
4. go back to settings.
5. see that it hasnt saved

**To Reproduce Instance**
1. Go to Settings
2. Change Instance Location
3. Quit the app
4. open the app
5. go back to settings.
6. see that it hasnt saved

**Expected behaviour**
for it to save changes

**Screenshots**
https://ss1.manmaed.net/1593199951.mp4

**Additional context**

**Comment by manmaed** [comment]
#175 seems be the same

**Comment by Cloudhunter** [comment]
Closed as duplicate and fixed
