### ISSUE TITLE
[Bug]Installer not installing

### ISSUE THREAD

**Issue by ZeyuanZhao** [FTBTeam/FTB-App#179]
**Operating System:**
OS: Windows10

**Installer Version:**
Installer: No idea

**App Version:**
App: ???

**UI Version:**
UI: ???

**Log Files:**
No log

**Describe the bug**
The problem is that the installer won't work properly. Sometimes, when runned, the installer will disappear from my downloads folder. When it does succeed, it is always stuck on "preparing Install4j Wizard" screen. It is stuck there for a minute or two, then proceeds to say that the Java VM could not be started. I don't think this is happening to anyone else, since no one has posted online yet.

**To Reproduce**
No idea

**Expected behaviour**
I expected it to install the FTB launcher app

**Screenshots**
![image](https://user-images.githubusercontent.com/14340342/85910861-34418f80-b7ef-11ea-9d33-a7487af3974c.png)

**Additional context**

**Comment by Gaz492** [comment]
Thanks for reporting this to us, I'm going to close this issue and add a link to it in our installer issues mega thread over here https://github.com/FTBTeam/FTB-App/issues/77
