### ISSUE TITLE
[Bug] Linux Installers 

### ISSUE THREAD

**Issue by void206551** [FTBTeam/FTB-App#180]
**Operating System:**
OS: Ubuntu 20.04 LTS Focal Fossil / GNOME 3.36.2

**Installer Version:**
Installers: 
 * (Initial install) FTBA_unix_202006121223-ac73c94902.sh
 * Auto update
 * (Reinstalled with) FTBA_linux_202006271722-d5803963f2-release.deb

**App Version:**
App: Unavailable

**UI Version:**
UI: Unavailable

**Log Files:**
From `~/FTBA/`
[launcher.log](https://github.com/FTBTeam/FTB-App/files/4840905/launcher.log)
[error.log](https://github.com/FTBTeam/FTB-App/files/4840906/error.log)

**Describe the bug**
1. Modpacks are missing from launcher after update
2. Launcher won't open after closing after update

**To Reproduce**
Steps to reproduce the behaviour:
1. Install from `FTBA_unix_202006121223-ac73c94902.sh` then update from the launcher
2. Go to "My Modpacks"
3. See the lack of modpacks installed
4. Close launcher
5. Attempt to reopen launcher
6. See lack of launcher

**Expected behaviour**
1. Modpacks to be in "My Modpacks" after update
2. Launcher to open

**Comment by Cloudhunter** [comment]
Are the instances in /home/json/FTBA/instances or /home/json/.ftba/instances?

**Comment by void206551** [comment]
The instances are in /home/json/FTBA/instances. The same thing happened when I tried launching on Windows 10 after the update.

**Comment by Cloudhunter** [comment]
Can you reinstall using FTBA_unix_202006121223-ac73c94902.sh, and see if they are there? If not, can you go into "Settings" and pick the instance location and see if that works?

**Comment by void206551** [comment]
I reinstalled it and changed the instance folder with FTBA_unix_202006121223-ac73c94902.sh. I tried reopening the launcher to refresh everything, but nothing happened. The launcher didn't popup and no error file was created.

**Comment by Gaz492** [comment]
Does this issue still exist in newer versions of the app for you?

If they do, can you open a new issue for this?
