### ISSUE TITLE
FTP-APP update will forget all game installs

### ISSUE THREAD

**Issue by cnleo** [FTBTeam/FTB-App#181]
**Operating System:**
OS: Windows

**Installer Version:**
Installer: FTBApp.exe (last change from 2020-06-27T19:21+1UTC)

**App Version:**
App: 202006271817a3b3b73d4c-release

**UI Version:**
UI: 8b8de00b

**Describe the bug**
After updating of FTP-App my old Revelation Game is gone.
I installed the Revelation “again” it installed because only option without “play”.
Now I think I should not have installed Revelation again. I can’t find any World saves.
There is only one instance in .ftba (the "new" 3.2 Revelation I have installed).

**To Reproduce**
Steps to reproduce the behaviour:
1. start app, wait for update/install
2. now your game mod will installable but not playable
3. click your "mod" (revelation in my case), in next step it will install instead play (no way to select an old save/install)
4. folder of /instance with "new" instance replaced

**Expected behaviour**
Don't overwirte/delete old game saves

EDIT:  I see two folder:  **C:\FTBA\instances** and **~user\\.ftba\instances**
In C:\FTBA\instances\xxx\saves there is still a game/world save

Now I have no idee how I get the old game running?

Any suggestion would be nice.

**Comment by neil470** [comment]
I just got around this by copying the folders in the old "instances" folder into the new "instances" folder...

**Comment by Ricozero** [comment]
I have encountered the same problem, you can change the instance location in the "settings" menu.
After restarting the app, instances in the specified folder should show up.

**Comment by cnleo** [comment]
Ok, I try to backtracking my steps:

As I installed FTB-App few weeks or month ago I choosed a “custom” path for instances under settings in FTBA, like: `C:\FTBA\instances` all fine, worked, nice.
 
Now (with version wrote above) the custom path under settings are changed to “default” to `C:\Users\{username}\\.ftpa\instances` and if I change the path again they don’t have the permissions to copy the new Instances from `~default` to `~custom` but it is delete the content from `~custom` folder. There is a short message that they have not the permission to write. But to delete? Strange!

After that there is now a “copy” of the deleted `~custom` instance in `~default\instances` folder. But the App doesn’t recognized that. Same after restart the app.

To work you must delete the “new” instances in `~default\instances\*` folder—without yours: “I want to play” instance.

Maybe I missed something, but the custom path doesn’t work any more.

It is very uncomfortable and annoying.

**Comment by Cloudhunter** [comment]
A few weeks or months ago, custom paths did not exist.

I have made a lot of changes to the instance logic to fix some other bugs that were reported, and I'm confident that everything should work for you now in the latest development build. Please check it out at #194 and report any issues there.
