### ISSUE TITLE
App failed to install properly

### ISSUE THREAD

**Issue by LonelySauce** [FTBTeam/FTB-App#182]
**Operating System:**
OS: Windows 7

**Installer Version:**
Installer: FTBA_windows-x64_202006261451-949e05dd0e

**App Version:**
App: Unknown (Failed to install app)

**UI Version:**
UI: Unknown (Failed to load primary UI)

**Log Files:**
Put links to your logs here
https://pastebin.com/HNN8Y1mp

**Describe the bug**
When I attempted to load the installer, it managed to get past what I believe to be the first stage but then gave the error below after the bar was almost full.

**To Reproduce**
Steps to reproduce the behaviour:
1. I just ran the installer
2. I did nothing else that could have caused this bug to occur I swear

**Expected behaviour**
I expected it to install properly.

**Screenshots**
![FTB-launcher-bug01](https://user-images.githubusercontent.com/23504262/86200500-dc769180-bb2a-11ea-9d36-a9106369a19b.PNG)

**Additional context**
None.

**Comment by LonelySauce** [comment]
Important Note: Running the program as an administrator didn't help and in fact caused the installer to just straight up crash and not even give an error message

**Comment by Gaz492** [comment]
Hi, can you try a newer version of the app to see if the issue is still present?

If you still have issues with installing a newer version of the app can you open a new issue for us?
