### ISSUE TITLE
[Bug] Error while launching FTB App

### ISSUE THREAD

**Issue by whitebear60** [FTBTeam/FTB-App#183]
**Operating System:**
OS: OS X Yosemite 10.10 x64

**App Version:**
App: 202006271817-a3b3b73d4c-release

**UI Version:**
UI: 8b8de00b

**Log Files:**

App Logs: https://pste.ch/ojunulerod
install4jError.log: https://pste.ch/evapozoriv.sql

**Describe the bug**
When I launch FTB App, error window appears, but when I close it, app continues launching.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch FTB App from "/Applications" folder
2. See error

**Expected behaviour**
FTB App should launch without any error messages

**System Hardware**
CPU: 2.4 GHz Intel Core i5
Memory: 16 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 3000 512 MB

**Comment by Jake-E** [comment]
Are you still having issues on the latest version of the app? If so, please re-open with further information (ideally follow the steps in the new issue template).
