### ISSUE TITLE
[Bug] Close button on notification not working

### ISSUE THREAD

**Issue by Sunekaer** [FTBTeam/FTB-App#186]
**Operating System:**
OS: Windows

**Installer Version:**
Installer: FTBA_windows-x64_202007042254-9878310b16-develop

**App Version:**
App: 202007042327-9043a7dc05-develop

**UI Version:**
UI: 81c4f336

**Log Files:**
https://pste.ch/imesifejib

**Describe the bug**
Close button on notification not working

**To Reproduce**
Steps to reproduce the behaviour:
Open an  installed pack, go to settings, change like ram amount and a notification comes up, and you the close button on it doesn't work

**Expected behaviour**
That it closed

**Screenshots**
Open an  installed pack, go to settings 
![image](https://s1.sunekaer.com/i/05-07-2020_02-28-19_%25pn.gif)

**Comment by ThePaul-T** [comment]
Unsure if your gif isn't getting the point over, but it looks like the notification is closing in your gif?

I am noticing it doesn't have "pointer" assigned, so that needs fixed. (@Gaz492)

Can you provide a better gif or description?

**Comment by Gaz492** [comment]
So the button is working was just missing the pointer on hover.
Fix will be in next beta version
