### ISSUE TITLE
[Bug] Custom Arguments is prepending an extra space

### ISSUE THREAD

**Issue by Septem151** [FTBTeam/FTB-App#188]
**Operating System:**
OS: Ubuntu 20.04 LTS

**Installer Version:**
Installer: Not sure what this is referring to.

**App Version:**
App: `202006271817-a3b3b73d4c-release`

**UI Version:**
UI: `8b8de00b`

**Describe the bug**
When setting custom arguments via the "Settings" tab on modpacks, there is an extra space character added in between the instance memory declaration and the arguments. For example, with a specified Instance Memory of 4.00GB and Custom Arguments of: 
"-XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M"
the resulting JVM arguments in the Minecraft Launcher becomes:
"-Xmx4096M &nbsp;-XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M"
(notice the additional space between `-Xmx4096M` and `-XX:+UseConcMarkSweepGC`).

**To Reproduce**
Steps to reproduce the behaviour:
1. Open "FTBApp"
2. Click on "Modpacks", hover over the selected modpack and click the "..." option
3. Click on "Settings" and set some JVM arguments in the "CUSTOM ARGUMENTS" field, and Save
4. Click "Play" and the Minecraft Launcher opens
5. (LINUX ONLY) Click on "Installations" at the top of the Minecraft Launcher, and Edit the Modpack's Java Executable to point to the Java binary, and save
6. Click "PLAY" on the Minecraft Launcher with the modpack selected, receive an error: `ERROR: Game Crashed: An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience."

**Expected behaviour**
There should be only one space character between the allocated memory declaration and other custom JVM args.

**Additional context**
The game settings have to be modified within the Minecraft Launcher on Linux regardless, because for some reason the "Java Executable" being set to `<Use bundled Java runtime>` does not work. There is no setting to change the default JRE in FTBApp that I can find.

**Comment by ThePaul-T** [comment]
Didn't you fix this @gigabit101?

**Comment by Septem151** [comment]
@ThePaul-T I noticed this issue has been fixed in the most recent update (or at least since I've last used FTBapp)
