### ISSUE TITLE
[Bug] [Beta] My Modpack page refreshes constantly when installing a new modpack

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-App#190]
**Operating System:**
OS: W10

**Installer Version:**
Installer: FTBA_windows-x64_202007042254-9878310b16-develop

![image](https://user-images.githubusercontent.com/15698722/86527447-6349a800-be64-11ea-8410-9aedbcb2bd78.png)

**Log Files:**
https://pste.ch/toyohebepu

**Describe the bug**
When you install a modpack and then go to the My Modpacks page before it's done, it refreshes constantly

**To Reproduce**
Steps to reproduce the behaviour:
1. Begin the installation of a new modpack
2. While it's installing, go to My Modpack page

**Expected behaviour**
It should only update when the modpack is finished downloading

**Screenshots**
![ezgif-6-e9acbd243ff4](https://user-images.githubusercontent.com/15698722/86527433-444b1600-be64-11ea-8c63-9fb76244870f.gif)

**Comment by ThePaul-T** [comment]
Looks like the same issue Home had, please fix @Rushmead

**Comment by Cloudhunter** [comment]
As I commented when we first saw this, just needs some crab rave emojis 🦀🦀🦀

**Comment by Rushmead** [comment]
Yep this appears to be the same as the Home screen and is a simple fix, will come with the rest of the bug fixes later today :)

**Comment by Cloudhunter** [comment]
Pinging @Rushmead to update this if the build is out

**Comment by Rushmead** [comment]
This should be fixed on Preview, please let me know if this is not fixed @aaronhowser1

**Comment by aaronhowser1** [comment]
Works fine, as far as I can tell. However, it had an error when downloading so I can't be 100% sure it works perfectly.
![image](https://user-images.githubusercontent.com/15698722/87304790-fa54d680-c4da-11ea-82dd-050d2a818930.png)

**Comment by Rushmead** [comment]
As always please provide your log files so that this can be looked into.
