### ISSUE TITLE
[Bug] The default electron icon is shown in the Dock on MacOS

### ISSUE THREAD

**Issue by zervyvin** [FTBTeam/FTB-App#193]
**Operating System:**
OS: MacOS Catalina 10.15.5

**UI Version:**
UI: 8b8de00b

**Describe the bug**
When installing and running the app on MacOS the icon in the Dock (bottom bar on desktop) shows the default electron icon instead of a FTB relevant one.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install and start the FTB-app
2. Observe the Dock at the bottom of the desktop and screen

**Expected behaviour**
I expected a FTB-like icon in the dock instead of the electron default one.

**Screenshots**
<img width="209" alt="Screenshot 2020-07-05 at 23 36 48" src="https://user-images.githubusercontent.com/5826079/86542730-75851e00-bf18-11ea-8c31-02f1e72ec286.png">

**Comment by Cloudhunter** [comment]
I believe this is fixed in our internal build, but assigning @Rushmead to check
