### ISSUE TITLE
[Bug] Linux Version Does Not Follow Proper Platform Paradigm

### ISSUE THREAD

**Issue by john01dav** [FTBTeam/FTB-App#195]
The Linux version of this launcher does not follow the proper paradigm for a Linux program. Most Linux users like to use a package manager whenever possible, but, I recognize that packaging it for every Linux distribution can be a hassle. Therefore, there should be a simple option that allows Linux users to maintain control over their system. Instead of an installer wizard that does who knows what (so far, I found out that it messes with the global Java configuration, which, for many people like myself, is carefully calibrated), there should be a simple archive file (e.g. zip, tar.gz) that contains the launcher and, optionally (to the user, not the implementer) a Java runtime. This is what Jetbrains does for their IDEs, and it is the right way to do it on Linux when you don't want to make a package for each distribution.

**Comment by Rushmead** [comment]
Please format this in the Bug report format that is provided to you when creating an issue, this issue will be closed if it is not corrected.

**Comment by Rushmead** [comment]
![image](https://user-images.githubusercontent.com/1780637/87098928-5cde7600-c240-11ea-92db-11db688bd13e.png)
Closed as they do not wish to put the effort into formatting correctly.
