### ISSUE TITLE
[Bug]No settings.json is created

### ISSUE THREAD

**Issue by grandrolf** [FTBTeam/FTB-App#197]
**Operating System:**
OS: Windows10 2004

**Installer Version:**
Installer: FTBA_windows-x64_202006271817-a3b3b73d4c-release.exe

**App Version:**
App: 202006271817-a3b3b73d4c

**UI Version:**
UI: 8b8de00b

**Log Files:**
https://pste.ch/iyiyomevok
how to find logs: https://faq.ftb.world/books/ftb-app

**Describe the bug**
Installation doesn't save the selected location of installation "Instance location" - changed back to defaults.

At first run the folder .ftba in default location was created - even if other location was selected.

When doing troubleshooting I noticed that settings.json file is not created when installed - did installation with defaults + tried pointing to a different installation location - same issue.

Also cleared out the folders that was created after uninstall, just to make sure everything was gone before reinstalling.

**To Reproduce**
Steps to reproduce the behaviour:
Install the FTB app
Start the app - look for the settings.json-file
Try and change instance location (this might work when it's running from memory, but will be restored upon restart of the app)
Restart the app

**Expected behaviour**
Saving settings to disk
Being able to change location of installation and location of the instances.

**Comment by Cloudhunter** [comment]
This should be fixed in the latest release. Re-open if not!

**Comment by grandrolf** [comment]
> This should be fixed in the latest release. Re-open if not!

Thanks - I'll check and re-open if the issue is still there.
