### ISSUE TITLE
[Feature request] Custom Java executable location

### ISSUE THREAD

**Issue by alentoghostflame** [FTBTeam/FTB-App#198]
On Linux, installing vanilla MC with the deb file will also install OpenJDK 11 on your system. To play modded, you typically have to launch with Java 8. While I can tell the MC launcher that the FTB app opens to use my locally installed Java 8, it's annoying to have to do it every time.

Rather than uninstalling OpenJDK 11, I'd rather be able to tell the FTB app what Java executable to use.

Running Ubuntu 20.04, upgraded from 19.10

**Comment by Cloudhunter** [comment]
We include our own distribution of OpenJDK 11 for launching the FTBApp - is it this which is getting installed, or is the Vanilla launcher itself installing OpenJDK as part of its installation process - just so we're clear that it isn't something we're doing.

Setting the JVM version to launch with is part of our plans, regardless.

**Comment by alentoghostflame** [comment]
The vanilla launcher, at least when using the deb file, installs it's own copy of OpenJDK 11. Thanks!

**Comment by Irgendwer01** [comment]
@alentoghostflame just install openjdk 11 asfirst then openjdk 8, it overwrites the shortcuts of openjdk 8 in usr/bin/ and FTB Launcher installer will detect the openjdk 11 installation still

**Comment by peterfab9845** [comment]
Another option I found was to open the launcher with the JAVA_HOME environment variable to wherever you have Java 8 installed.

**Comment by Gaz492** [comment]
The app now has the ability to select a JRE from a drop-down list.
The app will check for any installed JREs and will display them in the drop-down on the settings page of an instance.

**Comment by dkowis** [comment]
What if the java version isn't "installed". Say on linux, I've got JDK/JRE's in `/opt/jvm/<some java>`

How do I select one of those?

Currently adoptium, a good provider of JDKs doesn't have packages, and so a tarball install works fine, but I can't tell the app to use it.
