### ISSUE TITLE
[Bug]Minecraft Launcher forgets instance settings

### ISSUE THREAD

**Issue by Irgendwer01** [FTBTeam/FTB-App#199]
**Operating System:**
OS: Debian 10 (buster)

**Installer Version:**
Installer:202006271817-a3b3b73d4c-release

**App Version:**
App: 202006271817-a3b3b73d4c-release

**UI Version:**
UI: 8b8de00b

**Describe the bug**
The Minecraft Launcher forgets all instance settings when restarting
**To Reproduce**
Steps to reproduce the behaviour:
1. Start Minecraft Launcher via FTB Launcher
2. edit any instance settings in Minecraft Launcher
3. Save new instance settings
4. close Minecraft Launcher and restart it with FTB Launcher
**Expected behaviour**
That it saves instance Settings
**Screenshots**

**Additional context**

**Comment by Cloudhunter** [comment]
This is intended. Any instance settings will need to be changed in the FTBApp instead.

If there are settings that aren't exposed in the FTBApp that you wish to change, please let us know so we can make sure to expose them.

**Comment by Irgendwer01** [comment]
alright, thanks for the information
