### ISSUE TITLE
Launcher doesn't open with invalid instances

### ISSUE THREAD

**Issue by tomgiagtz** [FTBTeam/FTB-App#20]
I was trying to port over an instance of FTB:Interactions from the Twitch Launcher, just to see if it would work. I tried the instance itself and then stealing the name of the folder from an instance installed through the FTB client. With both invalid, the launcher doesn't open. 

I deleted both instances and the launcher still does not open.

[launcher.log](https://github.com/FTBTeam/FTB-App/files/4423992/launcher.log)
[error.log](https://github.com/FTBTeam/FTB-App/files/4423993/error.log)

I understand that I jumped the gun a bit, but glad to report a bug and help in any way I can.

**Comment by CH-Paul-T** [comment]
Checked this, the code stops executing as soon as it's printed the initial error and stack. So something else is causing your launcher not to open... Going to add some more logging.

**Comment by Cloudhunter** [comment]
Is this still an issue in the latest build?
