### ISSUE TITLE
[Bug] Minecraft Launcher on Mac does not open initially

### ISSUE THREAD

**Issue by Frostist** [FTBTeam/FTB-App#200]
I copied this bug report from, https://github.com/CreeperHost/modpacklauncher/issues/14 as I don't know if anyone knows about this...

I am using App Version 202006271817-a3b3b73d4cd46fc91f731c0a18f918d9eadda1a8-release on macOS Catalina 10.15.6.

Trying to install a mod pack (with freshly installed FTB App) gets stuck on step 'Installing vanilla launcher' (Log file).
After digging in the code and finding this line

modpacklauncher/src/main/java/net/creeperhost/creeperlauncher/minecraft/GameLauncher.java

Line 56 in a3b3b73

 while (!file.exists()) 
I checked my data folder under ~./ftba/bin and no file launcher_profiles.json was created. So I copied over this JSON file from my vanilla Minecraft installation.
After this, the installation of the mod pack continued and finished (Log file).
So I tried starting the freshly installed mod pack which had no visible effect and didn't start the Minecraft Launcher (Log file).

So I tried starting it myself manually from the shell by running in my data directory ./Minecraft.app/Contents/MacOS/launcher --workDir /Users/daniel/.ftba/bin. This started the Minecraft Launcher and the mod pack profile was visible and I was able to play.

I am suspecting that the installation of the Minecraft Launcher got stuck because the Minecraft Launcher was never started and therefore launcher_profiles.json was never created.

TL;DR
For some reason on macOS starting the Minecraft Launcher from the FTB App fails.

**Comment by Cloudhunter** [comment]
https://github.com/CreeperHost/modpacklauncher/issues/14#issuecomment-660059494_
