### ISSUE TITLE
Bug on CrackPack Loding

### ISSUE THREAD

**Issue by Bladscope** [FTBTeam/FTB-App#201]
Im geting a error code when loding the mods what can i do to fix it
Error code: `The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: lib.enderwizards.sandstone.items.ItemToggleable.newItemStack()Lnet/minecraft/item/ItemStack;
`

**Comment by Cloudhunter** [comment]
Does reinstalling it fix it? I've tagged @Rushmead as he initially imported a lot of the packs, just in case that doesn't fix it.

**Comment by Bladscope** [comment]
reinstalling  dosent fix it @Cloudhunter

**Comment by Cloudhunter** [comment]
@Rushmead maybe something for you to check - there's extra logging on sha1 and filesize failures in internal builds

**Comment by gigabit101** [comment]
This issue has since been resolved,
