### ISSUE TITLE
[Bug]Installing FTB Interactions 2.0.3 throws SHA1 checksum error

### ISSUE THREAD

**Issue by Hachuurui** [FTBTeam/FTB-App#205]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: unknown

**App Version:**
App: 202007171359-226ecdo5aa-develop

**UI Version:**
UI:  39f37b8 d

**Log Files:**
https://pste.ch/duqeletili

**Describe the bug**
Unable to install latest ftb interactions due to checksum error.

**To Reproduce**
Steps to reproduce the behaviour:
Attempt to install the pack either via update or new install.
**Expected behaviour**
Pack updates or installs.

**Screenshots**
![2020-07-17 19_33_53-FTB Desktop App](https://user-images.githubusercontent.com/2464584/87838532-62057b80-c865-11ea-97bc-e12bf575df56.png)

**Additional context**

**Comment by Hachuurui** [comment]
Also, clicking on retry doesn't do anything

**Comment by Irgendwer01** [comment]
@Hachuurui have u tried to install an older version?

**Comment by Hachuurui** [comment]
not yet. I deleted the install, reinstalled ftb interactions, same error,
but there were files.. I tested the modpack and it appears to work fine and
matched the server files.

As for older versions. The FTB App auto updates.. I'm assuming you are
meaning the modpack? I can try that and see if the same error occurs. If
the App itself, I'll see if I can find an older install of it.

**Comment by Hachuurui** [comment]
It appears all versions are throwing the same error.

**Comment by Hachuurui** [comment]
Update: I have reinstalled the FTB App from the site and it appears to have fixed the issue. Apparently I was still on a dev version from an earlier bug report test and was updating via the dev version. Release version does not have this issue. I'll leave this open for you to see but feel free to close it unless you need to reference the dev build info in the original post to trace the bug.

**Comment by Saereth** [comment]
the issue was with the shetiphan jar which is in memory repo, this is dymically created on pack launch so no need to distribute with the pack. Version 2.0.4 and higher no longer distribute this file, although it may still be an issue for other packs in the future
