### ISSUE TITLE
[Bug] Window size not set by selecting a resolution under certain circumstances

### ISSUE THREAD

**Issue by SerLizar** [FTBTeam/FTB-App#211]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: 202007161516-479dedc615-release

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
https://pste.ch/bagidolaca

**Describe the bug**
Settings are not initialized correctly on install/first launch (Well that's what I believe is the cause).
When first installing the app I went into the settings right away, under game settings in window size, the default values for width and height where not the correct ones for my device, this is not actually a problem. Then I click on the little monitor icon and as expected there is dropdown of common screen sizes and my resolution in right there first on the list, I click on it, it does nothing, I do it again, nothing, again. At that point, knowing how this things usually are, I decide to just click on another one of the options, the values change as expected, I click on my resolution and now it does work and sets the values I actually wanted.

After some further testing, it actually doesn't update the value at all so long as you are choosing the same entry on the list again (and probably has the value set internally on first launch to the first entry of the list) if you have any other value (manually input) and select the same option again, it will not be overriden until you choose another entry.

Also as it's probably related, under App Display, the example display is that of list mode while the toggle under it is off by default, while list mode appears to not yet be a working feature, this default is currently incosistent with the UI.

In another note, having a copy button next to the UI Version and App Version would make making this bug reports much easier.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings.
2. Click on the screen icon under window size and select the first entry.
3. Manually input any value into the width or height fields.
4. Click on the screen icon under window size and select the first entry again.
5. See that the manually input values are still there.

**Expected behaviour**
Clicking the first option in the list of resolutions that popup when click the screen icon under the window size heading inside the game settings subsection should work the first time around to set the expected values.

In general selecting an entry from the list of resolutions should *always* overwrite the current value of the width and height feilds.

**Additional context**
Probably needs to be done on first launch of a clean install so some flags that are set during normal use are not present

**Comment by Gaz492** [comment]
I believe the issue has now been resolved in newer versions of the app.

If you still have the issue please open a new issue.
