### ISSUE TITLE
Pams Harvest Crash May be Issue

### ISSUE THREAD

**Issue by Cooth** [FTBTeam/FTB-App#212]
Trying to open FTB Interactions for the first time.  Keep getting error saying Pams Harvestcraft may be the issue to it not opening. Tried downgrading Interactions and it won't load at all. Just crashes at Minecraft loader screen. Tried downgrading Pams but same error! 

[crash-2020-07-21_22.42.49-client.txt](https://github.com/FTBTeam/FTB-App/files/4956511/crash-2020-07-21_22.42.49-client.txt)
[crash-2020-07-21_22.50.44-client.txt](https://github.com/FTBTeam/FTB-App/files/4956512/crash-2020-07-21_22.50.44-client.txt)
[crash-2020-07-21_22.25.59-client.txt](https://github.com/FTBTeam/FTB-App/files/4956513/crash-2020-07-21_22.25.59-client.txt)
[crash-2020-07-21_22.35.16-client.txt](https://github.com/FTBTeam/FTB-App/files/4956514/crash-2020-07-21_22.35.16-client.txt)

**Comment by Samwhell** [comment]
I am also experiencing this.

https://paste.feed-the-beast.com/view/b2744095

**Comment by Sunekaer** [comment]
This is not a launcher issue please report this issue on the modpack's issue tracker
