### ISSUE TITLE
[버그] grandrolf help

### ISSUE THREAD

**Issue by time0001234** [FTBTeam/FTB-App#213]
**Operating System:**
OS: win10

**Installer Version:**
Installer:FTBA_windows-x64_202007161516-479dedc615-release

**App Version:**
App: FTBA_windows-x64_202007161516-479dedc615-release

**UI Version:**
UI: I'm sorry. I'm not sure  :(

**Log Files:**
Put links to your logs here
[i4j_nlog_1.log](https://github.com/FTBTeam/FTB-App/files/4957032/i4j_nlog_1.log)

how to find logs: https://faq.ftb.world/books/ftb-app

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by Irgendwer01** [comment]
try to install java 11 on ur pc and see if it works

**Comment by Gaz492** [comment]
If you are still having the issue can you open a new issue and provide as much detail as possible?
