### ISSUE TITLE
[Feature] Java version selector

### ISSUE THREAD

**Issue by gab9281** [FTBTeam/FTB-App#215]
**Is your feature request related to a problem? Please describe.**
The problem comes when you're trying to launch a modpack with a version 1.12.2 and under.
If your java_home is set as java14, the game will automatically crash.

**Describe the solution you'd like**
The solution that could be used is to have a java version selector.
It could be either a global or by modpack selector.

**Describe alternatives you've considered**
I didn't though of a way to verify if the correct version of java is installed or placed as main.
If you have any other idea, i am all ears.

Have a nice day

**Comment by Gaz492** [comment]
This feature has now been added.
There is a dropdown in the settings page of your instances that will allow you to select a java version that is installed on your computer.
