### ISSUE TITLE
Cant download server files for Linux or Mac from launcher

### ISSUE THREAD

**Issue by erensevin** [FTBTeam/FTB-App#216]
hey! Im trying to download the server files for Linux / Mac, but with no success. It gives me a file called serverinstall_6_88 with no file extension. I have tried multiple browsers as well as both MacOS and Ubuntu/Linux, both up to date versions. (Also tried on 2 different Macs).

Would it be possible to download the server files manually from somewhere?

**Comment by Goof245** [comment]
Try running that file (i.e. "./serverinstall_6_88"). Yeah...... 

Absolutely insane server creation process they've got going on here now they've cut ties with curse....

**Comment by erensevin** [comment]
> Try running that file (i.e. "`./serverinstall_6_88`"). Yeah......
> 
> Absolutely insane server creation process they've got going on here now they've cut ties with curse....

I've tried that, doesnt work, the file doesnt have an extension and cant be identified by both systems.

**Comment by Goof245** [comment]
(I can't speak for MacOS as I don't own it, but I *believe* it's the same...)
You don't strictly need an extension to execute a file. What you *might* need to do is to set the file permissions to allow you to execute it.

Try this:
- Make a new folder somewhere convenient, then move the serverinstall file into it
- Open a terminal window in that folder, then type `./serverinstall_6_88`
- If you get a "permission denied" message, try `chmod +x serverinstall_6_88`.  Then try `./serverinstall_6_88` again

If it's working correctly, you should see a ton of messages that it's downloading files.

**Comment by s0ph0s-2** [comment]
macOS will not launch that file because it's not code signed. There are workarounds that users can take (after changing scary-looking settings in System Preferences), but by default Gatekeeper denies it.

**Comment by gigabit101** [comment]
Issue has been mentioned on the correct issue tracker
