### ISSUE TITLE
Game window never launches

### ISSUE THREAD

**Issue by praxis88** [FTBTeam/FTB-App#219]
Operating System:
Arch Linux  5.4.53-1-lts

**Log Files:**
[error.log](https://github.com/FTBTeam/FTB-App/files/4977563/error.log)
[launcher.log](https://github.com/FTBTeam/FTB-App/files/4977564/launcher.log)

**Describe the bug:**
When I press play for any modded version, the game does not launch. Gives error. Vanilla loads fine. The box that pops up says "error Game Crashed. An unexpected error issue has occured and the game has crashed. We're sorry for the inconvenience"

**To reproduce:** 
Download FTBapp for linux. 
Install it
Download any modded version of minecraft
Try to launch it

**Expected behavior:**
The Game launches

**Comment by colbiedison** [comment]
This is happening to me as well. I have a very slow internet connection and I'm attempting to download a large pack. If a download times out, it launcher doesn't complain and it lets me try to launch it anyway, and I get the same error. I've had to delete the modpack and retry, but I'm getter further every time.

**Comment by Gaz492** [comment]
Have you tried a newer version of the FTBApp and does the issue still happen?

If you still have issues with the app can you open a new issue?
