### ISSUE TITLE
[Bug] Updating a modpack only change the version tab

### ISSUE THREAD

**Issue by LemADEC** [FTBTeam/FTB-App#220]
**Operating System:**
OS: windows 10

**Installer Version:**
Installer: unknown

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
https://pste.ch/ukitopigaq

**Describe the bug**
I had Omnia 1.5.0 installed. Yesterday, I've asked updating to 1.6.1, the progress bar started, while updating I've asked to download the Linux server then moved to other tasks.
Today, I've found out my client modpack was still running 1.5.0 while the version tab was showing 1.6.1 as the current version.
I've downgraded to 1.5.0 from the version tab, then upgraded to 1.6.1. At this point, the version tab was showing 1.6.1 as current, but the modpack list and page title was showing as 1.6.0.
I've downgraded to 1.6.0 from the version tab, then upgraded to 1.6.1. At this point, the version tab and the modpack list and page title were finally showing as 1.6.1.
Note: I could see the invalid version just by checking the CC: Tweaked mod version, so it was no simple UI issue, the files were actually messed up.

**To Reproduce**
Steps to reproduce the behaviour:
see above

**Expected behavior**
1- Version tab should be in synchronization with the actual version
2- Updating should actually update

**Screenshots**
n/a

**Additional context**
n/a

**Comment by ThePaul-T** [comment]
Fixed in prototype build.
