### ISSUE TITLE
[Bug] Modpacks won't download

### ISSUE THREAD

**Issue by Scorpionpi** [FTBTeam/FTB-App#223]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: FTBA_windows-x64_202007161516-479dedc615-release

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
https://pste.ch/iwogewuwas

**Describe the bug**
Modpacks will not download, met with message saying 'error installing *modpack*'

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on 'get' on new modpack
2. See error

**Expected behaviour**
Modpack downloads

**Screenshots**
![Bug Screenshot](https://user-images.githubusercontent.com/69007904/88948514-045b3100-d260-11ea-9278-f195b1f5cff2.PNG)

**Additional context**
New PC, Installed a TP-Link Archer T6E WiFi card yesterday. Modpacks installed fine last week with Ethernet connection. I've checked my firewall.

**Comment by Gaz492** [comment]
Can you try downloading the modpack again and making sure you are on the newest version of the FTB App. You can download the app again from https://feed-the-beast.com.

If you are still having issues with downloading the modpack can you open a fresh issue?
