### ISSUE TITLE
[Feature request] Buttons shouldn't move when I mouse over them.

### ISSUE THREAD

**Issue by JannesP** [FTBTeam/FTB-App#224]
**Is your feature request related to a problem? Please describe.**
I find it really frustrating to use the "Play" and "More" buttons on modpacks. When you hover over one, the other disappears even though you might've just moved the mouse over it to get to the other one. Also the visual indicator for where to leave the mouse moves with it which makes it a bit awkward feeling.

**Describe the solution you'd like**
For the "grid view" you could display the button label instead of the version while hovering over a button. The text could slide the version away from the direction where the button is.
In the list view the text could just always be displayed because the buttons are big enough anyways.

**Additional context**
![image](https://user-images.githubusercontent.com/5788115/89189497-55409180-d5a0-11ea-8a1f-e49f35c7c162.png)
![image](https://user-images.githubusercontent.com/5788115/89189640-933db580-d5a0-11ea-8281-006fb9a6ca18.png)
![image](https://user-images.githubusercontent.com/5788115/89189846-e3b51300-d5a0-11ea-85de-774890a24088.png)

**Comment by GrumpyChunks** [comment]
Came here to post the same. It's extremely frustrating when you approach the button you want from the wrong direction, and the button you want disappears, meaning you have to move the mouse away from what you are trying to select and have another go. On occasion it can take me 2 or 3 attempts to hit the correct button.

A simple colour change is an effective hover indicator.
