### ISSUE TITLE
[Bug] [Linux] Moving instance directory to external HDD does not work

### ISSUE THREAD

**Issue by McModknower** [FTBTeam/FTB-App#226]
**Operating System:**
OS: Linux Mint 20

**Installer Version:**
Installer: FTBA_unix_202007161516-479dedc615-release.sh

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
[error.log](https://github.com/FTBTeam/FTB-App/files/5022826/error.log)
[launcher.log](https://github.com/FTBTeam/FTB-App/files/5022828/launcher.log)

**Describe the bug**
When i try to move my instance directory to my usb connected hard drive, i get an error. (See screenshots)

**To Reproduce**
1. Go to Settings
2. Click on Instance Location
3. Select a Folder on a different file system (in my case Hard drive)
4. Click ok
5. Click yes
6. See Error Message

**Expected behaviour**
That the instance directory gets moved without an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/26181230/89310494-13cde600-d675-11ea-980a-d6f576bed91d.png)

**Additional context**
Sadly i currently can't test this with an SSD or internal HDD/SSD. Because of that i can't do more accurate testing.

**Comment by Rushmead** [comment]
Could you please try again on our Preview branch, you can swap to this via the Settings tab of the app. If the issue still persists please provide us with the logs and version number :)

**Comment by McModknower** [comment]
With the Preview version it works. Thanks for fixing
