### ISSUE TITLE
Can't view full Overview or Versions tabs for some packs 

### ISSUE THREAD

**Issue by AKTheKnight** [FTBTeam/FTB-App#23]
e.g. Revelation

Needs a scroll bar or something

This is the default app opening size:
![image](https://user-images.githubusercontent.com/7502848/78310179-08db3b80-7545-11ea-8601-608b320e9711.png)

![image](https://user-images.githubusercontent.com/7502848/78310183-0c6ec280-7545-11ea-8e3e-0736d27fea42.png)

**Comment by Gaz492** [comment]
Linked to #11
