### ISSUE TITLE
[Bug]Server Downloader Totally Broken

### ISSUE THREAD

**Issue by phoenixburn119** [FTBTeam/FTB-App#230]
**Operating System:**
OS: Win10

**Installer Version:**
Installer: 5.95

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app

**Describe the bug**
The server installer will take hours to complete and use all my bandwidth but also when complete be missing large chunks of the data the server needs. (e.g. mods, configs).

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the server downloader.
2. It takes a very large amount of time.
3. Finishes missing key components to running 

**Expected behaviour**
I'd really like it to be a lot faster and not be missing any server files or just a have a zip file downloader like curse.

**Additional context**
My friend has 1 gb down and I have 100 gb down it takes him about 4 minutes and it come as a complete package. When I download it, it takes about two hours and is missing key server files. If you could help me help you I dont know if the installer writes a log or anything. I'd love to help any way I can.

**Comment by Jake-E** [comment]
There should be a log wherever you're running the server installer.
If you still have the log file, can you upload it for us to take a look?

**Comment by Sunekaer** [comment]
Issue closed due to asked information hasn't been provided
