### ISSUE TITLE
ransomeware?[Bug]

### ISSUE THREAD

**Issue by sirras** [FTBTeam/FTB-App#231]
**Operating System:**
OS:
windows 10
**Installer Version:**
Installer:
ftb launcher
**App Version:**
App: 
newest
**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app
https://paste.feed-the-beast.com/view/25385cd5
**Describe the bug**
got a ransomware notice it was blocked. Now java is missing from my launcher
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**
![ransomeware](https://user-images.githubusercontent.com/69538204/89941084-277ecc80-dbe0-11ea-9b6d-76e833a88921.png)

**Additional context**

**Comment by Jake-E** [comment]
This seems to be a Malware bytes issue in detecting Java as ransomware.
Add the javaw.exe to the allowlist:
https://support.malwarebytes.com/hc/en-us/articles/360038479234-Add-to-the-Allow-List-in-Malwarebytes-for-Windows-v4

https://forums.malwarebytes.com/topic/261756-java/page/2/
