### ISSUE TITLE
Include graal instead of or ontop of the java installation[Feature request]

### ISSUE THREAD

**Issue by royalmustard** [FTBTeam/FTB-App#232]
**Is your feature request related to a problem? Please describe.**
Graal offers (at least when I tried it) superior performance on all packs I have played so far.
**Describe the solution you'd like**
Since graal is also open source and (probably) distributed under similar terms as the openjdk (since the community edition is based on openjdk) it should be easy to change the vm provided with FTBApp.

**Describe alternatives you've considered**
Alternatively an option to set the java executable path in the FTBApp should enable users to select graal if they choose to do so.

**Comment by Alront** [comment]
I would add to that that currently, if you change the Java executable in the Minecraft Launcher, that setting will reset itself to the bundled JVM once you hit Play the next time in the FTB Launcher. 
On that note I can also say that I've been getting significantly better Performance with Graal.

**Comment by gigabit101** [comment]
The "jre" can be changed via the settings screen in the app, We are not planning on adding Graal support at this time
