### ISSUE TITLE
[Bug] My modpacks are not showing after updating the FTB app.

### ISSUE THREAD

**Issue by baronthered80** [FTBTeam/FTB-App#234]
**Operating System:**
OS: win 10

**Installer Version:**
Installer:

**App Version:**
App: 202007161516-479dedc615

**UI Version:**
UI: 39f37b8d

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Additional context**
Nothing much to add no modpacks showing after the app update.

**Comment by Gaz492** [comment]
Can you provide logs from the app?

**Comment by baronthered80** [comment]
Sorry for the delay Here are the logs


https://pste.ch/ceruyokadu

**Comment by Rushmead** [comment]
Are you still missing those modpacks after updating? If so please can you tell us what version you are now running.

**Comment by Gaz492** [comment]
If you still have this issue do let us know by opening a new issue.
Closing as no reply was received.
