### ISSUE TITLE
[Feature request] Global Memory Settings Option

### ISSUE THREAD

**Issue by AJM10565** [FTBTeam/FTB-App#235]
**Is your feature request related to a problem? Please describe.**
I download a new mod pack, but the memory settings are set to a fixed default (4gb).

**Describe the solution you'd like**
I'd like to modify the fixed initial default value in a global settings context.

**Describe alternatives you've considered**

**Additional context**

**Comment by MichaelHillcox** [comment]
From my understanding, each pack & pack version ships with a memory min and max config which the pack will use by default if the values have not already been changed in the packs config. This and the fact that having a global option would (and has been in the past) confusing for users trying to use the pack. This likely won't be added, or will be added back in a better way. Right now, this is low on our list :D
