### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by aZh2511** [FTBTeam/FTB-App#236]
**Operating System:**
OS: MacOS Mojave 10.14.5

**Describe the bug**
Game doesnt start

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'New Launcher app'
2. Click on 'Start' And Nothing happens
When I am trying to start the game with new FTB app it just does nothing. Pressing "start" button does nothing. I have already reinstalled the client - it didnt help

**Comment by aZh2511** [comment]
<img width="1033" alt="Снимок экрана 2020-08-19 в 01 18 51" src="https://user-images.githubusercontent.com/49492149/90571239-06a71000-e1ba-11ea-86f6-bc612f977154.png">
Trying to reinstall:
<img width="1005" alt="Снимок экрана 2020-08-19 в 01 20 02" src="https://user-images.githubusercontent.com/49492149/90571288-22121b00-e1ba-11ea-8d34-271846cc3a8e.png">

log: https://pste.ch/lukoqifufo

**Comment by Rushmead** [comment]
Please update your app and re-try. If you continue to have this problem, please re-open the issue.
