### ISSUE TITLE
CentOS 6 can't run server installer[Bug]

### ISSUE THREAD

**Issue by nothanz** [FTBTeam/FTB-App#238]
**Operating System:**
OS: CentOS 6.10 fully patched

**Installer Version:**
Installer: serverinstall_5_96

**App Version:**
App: 

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app

**Describe the bug**
The server installer doesn't seem to run on CentOS 6.  I downloaded it and when originally run I got the following error:

`[root@rubik INTERACTION]# ./serverinstall_5_96
./serverinstall_5_96: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./serverinstall_5_96)
./serverinstall_5_96: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./serverinstall_5_96)`

CentOS 6 only supports up to GLIBC 2.12 natively so I compiled and installed GLIBC_2.15 into /opt and updated LD_LIBRARY_PATH.  After doing that however I now get a Segmentation fault.

`[root@rubik INTERACTION]# export LD_LIBRARY_PATH=/opt/glibc-2.15/lib
[root@rubik INTERACTION]# ./serverinstall_5_96
Segmentation fault`

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by Gaz492** [comment]
The server installer has recently been remade so it may have resolved this issue however if the issue still exists its unlikely to be resolved for CentOS 6 as it has reached end of life and is no longer receiving maintenance updates.
