### ISSUE TITLE
[Feature request] Discord RPC

### ISSUE THREAD

**Issue by TheShadowGamer** [FTBTeam/FTB-App#239]
**Is your feature request related to a problem? Please describe.**
No it is not. My feature request is Discord RPC support.

**Describe the solution you'd like**
To add Discord RPC so in our status it says "playing FTB Ultimate Reloaded" or something like that

**Describe alternatives you've considered**
Adding it under the discord game activity, but I have to do it every time I open it and it doesn't show a image.

**Additional context**
None

**Comment by Sunekaer** [comment]
Hi 

The FTB App opens the MC Launcher with a profile and then the MC Launcher is doing the rest. the app doesn't know if the pack is running or closed it just launches MC Launcher, and therefor the app cant do RPC and it has to be a mod in the packs.
