### ISSUE TITLE
[Bug] Can't update modpack and when modpack is opened it opens vanilla minecraft

### ISSUE THREAD

**Issue by TheRealYaruzu** [FTBTeam/FTB-App#240]
**Operating System:**
OS: Windows 7

**Installer Version:**
Installer: FTB Desktop App (?)

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
https://pste.ch/jepegafibu

**Describe the bug**
I'm trying to continue playing FTB Infinity Evolved and when I opened the FTB launcher I noticed it had an update. I tried to update it by hitting more and clicking update. Nothing happens. I hit play which opens the normal minecraft launcher and that just opens up a normal version of minecraft with Minecraft Coder Pack, Forge Mod Loader and Minecraft Forge in it, all with 0 child mods even though the normal launcher had FTB Infinity Evolved selected as the game at the bottom.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to more for FTB Infinity Evolved
2. Click on update
3. Nothing Happens
Also
1. Hit play for FTB Infinity Evolved which opens the vanilla minecraft launcher
2. Hit play in the vanilla launcher
3. Game launches as either vanilla minecraft or with all of the mods missing.

**Expected behaviour**
I expected to be able to go to more and hit update for FTB Infinity Evolved, have it update, and then open the game no problem like I have been doing.

**Screenshots**
https://files.catbox.moe/ltbqca.PNG
https://files.catbox.moe/frg7lt.PNG
https://files.catbox.moe/dryia2.PNG
https://files.catbox.moe/u9cj90.PNG

**Comment by Rushmead** [comment]
Please update the FTBApp and re-try, we have made various improvements to problems over the past few months. Please re-open if the issue persists.
