### ISSUE TITLE
[Feature request] Modpack Library

### ISSUE THREAD

**Issue by KitoHub** [FTBTeam/FTB-App#245]
**Is your feature request related to a problem? Please describe.**
I would like to browse through all Modpacks that FTB offers, but i only can see some selected ones.

**Describe the solution you'd like**
I would like a Modpack Library that lists all available Modpacks

**Describe alternatives you've considered**
The alternative solution would be the FTB Website and the Wiki, that i'm using right now.

**Additional context**
Sorry for my bad English ^^

**Comment by Gaz492** [comment]
This is something we are planning on implementing in the future.
As this is a similar request to #103 I will close this issue.
