### ISSUE TITLE
API Issues - Mod Pack Searching - Effects App

### ISSUE THREAD

**Issue by DinnerBeef** [FTBTeam/FTB-App#246]
If you are searching for a pack like Direwolf20 1.12.2 and you enter "Direwolf20 1.12.2" in the App/API it will return all Direwolf20 packs and all 1.12.2 packs. Not just the Direwolf20 1.12.2 Pack. This goes for anything with two words in it.

Another Strange Part is if you put " " marks around the term is only seems to search the first word.

TLDR: It looks like each word is getting searched and not the whole term.

EDIT: I bit more looking into it seems like the searching of " " will search more than one word however its seems to drop the last word and not search it. Though it still is searching how i said two words where above

**Comment by ThePaul-T** [comment]
Unsure about the quotes, but the first part is working as intended.

Search is a search not a filter, it will search for things it thinks are relevant to your term, in a hierarchical order.

1. Direct match
2. Full text search of name and description
3. Tags on a modpack match any single word
