### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by edegeltje** [FTBTeam/FTB-App#248]
Operating System:
OS: Windows 10

Installer Version:
Installer: 55487.0.0.0

App Version:
App: 202007161516-479dedc615-release

UI Version:
UI: 39f37b8

cant install some modpacks. first i installed ftb infinity evolved skyblock, this worked. i am able to play it. then i installed ftb academy. i was able to play that as well. then i tried to install skyfactory 3, this didn't work. at the bottom it says "creating environment". i tried installing skyfactory 2.5 then there was another line saying "creating environment", so now there are two lines on the bottom of the interface saying "creating environment". i tried restarting the app. it took long to load, so i closed it, and started it again. then it immediately loaded. the lines are gone.

log:
https://pste.ch/geyagikiji

Edit: after restarting the app, installing skyfactory 3 went without a hitch (not in log)

**Comment by Rushmead** [comment]
Please update to the latest version and re-open know if this issue still exists.
