### ISSUE TITLE
[Bug]Example Card Download Button

### ISSUE THREAD

**Issue by edegeltje** [FTBTeam/FTB-App#249]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: 55487.0.0.0

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
https://pste.ch/ofocezawuc

**Describe the bug**
you are able to attempt to install the example modpack
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the settings tab
2. Scroll down to 'app display'
3. Click on 'download'
4. Click on 'download' in the pop up version selector
4. See error: the example modpack image gets a banner saying installing, and at the bottom of the interface a line appears saying "creating environment"

**Expected behaviour**
clicking on the download button there shouldn't do anything

**Screenshots**
![image](https://user-images.githubusercontent.com/12956354/91557453-c885bb00-e934-11ea-8f64-affdf9cce49b.png)

**Comment by MichaelHillcox** [comment]
This has been removed and thus has been fixed :D
