### ISSUE TITLE
[Bug] Download Progress Bar MC Launcher

### ISSUE THREAD

**Issue by edegeltje** [FTBTeam/FTB-App#250]
Operating System:
OS: Windows 10

Installer Version:
Installer: 55487.0.0.0

App Version:
App: 202007161516-479dedc615-release

UI Version:
UI: 39f37b8 

**Log Files:**
https://pste.ch/ejotomadow

**Describe the bug**
when i downloaded ftb infinity evolved, when launching for the first time, on the launching progress bar it said it had to download something. it says something along the lines of "downloading 17.4 Mb/16.2Mb". i tried to reproduce it with other modpacks. when i installed skyfactory 3, it did it as well. deleting it and doing it again, i failed to recreate it. it seems to do it only the first time launching with only specific packs, because the sky oddyssey modpack didn't do it. (i tried that one as well)

**To Reproduce**
Steps to reproduce the behaviour:
1. install ftb infinity evolved
2. launch it for the first time
3. See error: the downloaded filesize goes over the total filesize

**Expected behaviour**
the progress shouldn't go over the total

**Comment by Rushmead** [comment]
This appears to be an issue with the Minecraft launcher not the FTBApp. Please report this to Mojang if it is still happening.
