### ISSUE TITLE
Failed to load URL mojang://java-launcher/index.html with error ERR_FAILED (-2).

### ISSUE THREAD

**Issue by Cogswatch** [FTBTeam/FTB-App#251]
**Operating System:**
OS: Mac

**Installer Version:**
Installer: FTBA_macos_202007161516-479dedc615-release.dmg

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
Put links to your logs here
Logs/Crashes directory is missing in instance folder

**Describe the bug**

Starting up Stoneblock 2 this morning, there was an 'updating launcher' progress window which flashed on screen briefly before the actual launcher window opened to 'Failed to load URL mojang://java-launcher/index.html with error ERR_FAILED (-2).' (Image attached below). I tried downloading a different modpack and the behavior persisted. I've since uninstalled the twitch launcher, reinstalled minecraft and the ftb-app, and while MC boots up fine through the vanilla launcher, the ftb-app keeps hanging on this error code.

**To Reproduce**
Steps to reproduce the behaviour:
(Honestly unsure since step one was outside my control and only happened once)
Open FTB
Hit play on a pack
Launcher gets stuck polling mojang...

**Expected behaviour**
The game should start as normal.

**Screenshots**
<img width="1112" alt="Screen Shot 2020-08-29 at 1 51 22 PM" src="https://user-images.githubusercontent.com/29944513/91646076-364ae900-ea00-11ea-91ab-2c7d02e630ff.png">

Possibly related:
https://bugs.mojang.com/browse/MCL-11142

If there is anything else I can provide to aid in debugging, I'll be more than happy to reply with more, I've been at this long enough to not be sure as to what is or isn't helpful at this point.

**Comment by Rushmead** [comment]
Have you attempted to follow the instructions provided on the Mojang issue you linked? The FTB App downloads it's own Minecraft launcher so you will need to do this in the directory where you installed the FTBApp.
