### ISSUE TITLE
.Desktop file in wrong place in new install on Ubuntu

### ISSUE THREAD

**Issue by ecpoppenheimer** [FTBTeam/FTB-App#252]
The .desktop file get placed in the install folder, not on the desktop.  Launching the app by clicking the .desktop file from the file browser works, but moving the file to the desktop and clicking gives the error:
"This link cannot be used because its target ".install4j/install4j_127d8p8-FTBApp.desktop' doesn't exist."

I am guessing this error is because an absolute file path is being used somewhere instead of a relative one.

Here are the contents of the generated .desktop file:

#!/usr/bin/env xdg-open
[Desktop Entry]
Type=Application
Name=FTBApp
Exec="/home/eric/FTBA/FTBApp" %U
Icon=/home/eric/FTBA/.install4j/FTBApp.png
Categories=Application;
StartupWMClass=install4j-net-creeperhost-creeperlauncher-CreeperLauncher

**Comment by MichaelHillcox** [comment]
This should now be fixed if you switch to the electron only version of the app. You can do this via the FTB Website and redownloing the app. I recommend you uninstall your current app and backup your instances before doing this.
