### ISSUE TITLE
[Bug] Cannot connect to Sky Factory 3 server

### ISSUE THREAD

**Issue by PresidentRNixon** [FTBTeam/FTB-App#253]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: Idk what this means

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
Log URL: https://paste.feed-the-beast.com/view/8833322a

**Describe the bug**
After both FTB and my server host updated Sky Factory 3, I have not been able to connect to the server. Whenever I start the server, load up SF3, and join the server, "Fatally Missing Blocks and Items" pops up. I have made ZERO changes to anything client or server side and Idk how to fix this issue

**To Reproduce**
Steps to reproduce the behaviour:
1. Load up FTBApp
2. Click on SF3 and click play
3. Go to aternos.org
4. Start the server
5. Wait for SF3 and the server to start
6. Click on multiplayer and then on your server
7. Click join and wait a few seconds for the error to pop up

**Expected behaviour**
I expected to join the server and play the modpack as normal

**Comment by Sunekaer** [comment]
This not an FTB app issue, please report on the correct issue tracker

**Comment by PresidentRNixon** [comment]
I reported it to my server hosting company, and they said to report it to
the mod makers, not the server makers.
