### ISSUE TITLE
Modpack Availability

### ISSUE THREAD

**Issue by ShinyFamvil** [FTBTeam/FTB-App#254]
The FTB App only gives users access to new and popular modpacks. There are many other modpacks on the old launcher that are not featured in the FTB App. I and others would like to see older modpacks implemented into the FTB App.

There are tons of modpacks I still enjoy such as FTB Trident, FTB Inventions, and even older modpacks such as Monster or the original Horizons.

I am only able to play those modpacks on the classic launcher and I still want to be able to play new modpacks as they come out.

Will I have to keep using both launchers? Or will they be moved into the FTB App?

**Comment by Sunekaer** [comment]
They will be moved to the new app, we just have more important things to due first
