### ISSUE TITLE
[Feature request] Auto 'yes' parameter in the server installer.

### ISSUE THREAD

**Issue by TheFlash787** [FTBTeam/FTB-App#255]
**Is your feature request related to a problem? Please describe.**
A problem for server administrators is that we currently cannot automatically update our FTB servers in any automatic deployment process because we are unable to use the server installer without any user input. 

**Describe the solution you'd like**
I would like us to have the option to auto-yes the installer. Upon running the command:
```
./serverinstall 5 121 --path ./install
```
It asks us to confirm that we would like to install (which if the path is empty, it would be good to assume that it's intended anyways). I would like us to be able to add a `-y` parameter (or equivalent) to the command, which will allow us to go through with the installation just using the one command, without the need for manual user input.

Ideally we could use:
```
./serverinstall 5 121 --path ./install -y
```
**Additional context**
N/A

**Comment by TheFlash787** [comment]
Hey! Is it possible to get an update on this, please.

**Comment by Jake-E** [comment]
@TheFlash787 apologies this comes so late.. unsure why it hasn't been picked up.
The installer should have --auto which should do this already.
