### ISSUE TITLE
Pyramid reborn not working?

### ISSUE THREAD

**Issue by CardboardAgainstHumanity** [FTBTeam/FTB-App#256]
It all works fine until i load into my server, where theres no spawn place, only a void to fall in and die repeatedly. 
picking a team doesnt help either.

**Comment by Gaz492** [comment]
This sounds like a modpack issue and not an FTB App issue can you create the issue on the Modpack issue tracker https://github.com/FTBTeam/FTB-Pyramid-Reborn-3.0

**Comment by CardboardAgainstHumanity** [comment]
> This sounds like a modpack issue and not an FTB App issue can you create the issue on the Modpack issue tracker https://github.com/FTBTeam/FTB-Pyramid-Reborn-3.0

unfortunantly the ones in there havnt been answered for quite a while and ykno i plan on getting this fixed in the next few minutes instead of months
