### ISSUE TITLE
[Bug] Getting the error "Sorry, unable to start Minecraft. Please check your configuration."

### ISSUE THREAD

**Issue by MrFroop** [FTBTeam/FTB-App#257]
**Operating System:**
OS: Windows 10 Pro 1903

**Installer Version:**
Installer: FTBA_windows-x64_202007161516-479dedc615-release

**App Version:**
App: 20227161516-479dedc615-release

**UI Version:**
UI: 39f378d

**Log Files:**
There is no client logs in the modpack folder. Have tried both DW20 2.7.0 and Omnia 1.3.0
There are some logs in the native launcher folder that may be of use: 
launcher_log.log - https://paste.feed-the-beast.com/view/7b162bee

This is the FTBApp logs: https://pste.ch/itidaqazec

**Describe the bug**
When trying to launch a modpack from the Launcher the error "Sorry, unable to start Minecraft. Please check your configuration." and nothing happens.

**To Reproduce**
Steps to reproduce the behaviour:
1. Press play on the modpack
2. When the launcher appears wait for it to go online and then press play.

**Expected behaviour**
Minecraft launches with the modpack loaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/196700/92148496-f7ac9880-ee1c-11ea-849d-cc3f97e49b6e.png)

**Additional context**
Not sure what's going on since I can't get any clear hints in any log files what's actually fails.

I have tried to reinstall the modpacks, the FTBApp. Tried different modpacks, same problem. I also tried not using the bundle Java, didn't work either.

**Comment by Rushmead** [comment]
Could you please provide us with the file located at C:\Users\mrfroop\.ftba\bin\launcher_profiles.json

It appears the Minecraft launcher is having trouble reading that file correctly.
