### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by MergingFob** [FTBTeam/FTB-App#258]
**Operating System:**
 OS: Mac

**Installer Version:**
Installer: FTB launcher

**App Version:**
App:  Stoneblock 2 

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app

**Describe the bug**
Whenever I try to launch the stoneblock 2 mod pack it will never load the MC launcher it stays at a dark grey window and never loads. I have tried deleting the modpack and reinstalling then tried doing that with the FTB launcher and still doesn't fix anything. I tried uninstalling my java and reinstalling it as the java 8 64 bit ( i believe) still does not work. And then I tried launching from the twitch launcher and that doesn't work. I went to technic and it loads there but the modpack there is more updated which with the mods and it says the ones on the server (so the FTB modpack) has older versions of all the mods I have. MC will load on technic and normal mc except for FTB and twitch. 
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/70733390/92191097-71964f00-ee28-11ea-8e1c-d459591d8715.png)

**Additional context**

**Comment by Rushmead** [comment]
This appears to be an issue with the Minecraft Launcher, if you install just the normal Minecraft launcher on its own does it work?
