### ISSUE TITLE
[Bug] Doesn't remember set "Java Executable" between runs

### ISSUE THREAD

**Issue by joakime** [FTBTeam/FTB-App#264]
**Operating System:**
OS: Linux - Ubuntu 18.04
OS Windows 10 (happens here too)

**Installer Version:**
Installer: Latest from website

**App Version:**
App: 202007161516-479dedc615-release (you should make this easier to copy/paste from the app itself, will make more people provide it, and also reduce transcription errors)

**UI Version:**
UI: 39f37b8d (again, this should be able to be copy/pasted from the app itself)

**Log Files:**
No log files needed

**Describe the bug**
The `launcher_profiles.json` produced by the FTBApp is missing the `"javaDir"` option in the profile instances.
It has the `"javaArgs"`, but the `"javaDir"` is not used when read, and is not produced when rewriting the `launcher_profiles.json` prior to launching the minecraft_launcher.

The default `minecraft_launcher` supports alternate JVMs, the `minecraft_launcher` embedded within FTBApp should too.

If you use "play" to begin the modpack, the `minecraft_launcher` kicks off.
If you run, it fails, hard.
This is because the "Use bundled Java runtime" is invalid on a growing number of linux machines. (more on this if you want)
If you edit the "Java Executable" to point to a valid Java 8 (OpenJDK 8) `bin/java`, the modpack runs, and runs fine.

But if you exit the game, close all of the launchers and come back, then the "Java Executable" has been forgotten.

Now that Java 8 is no longer the default installed JVM on Linux, having it available is often as an alternate JVM, one that the `minecraft_launcher` cannot find/use.
On my machine, I need to run a more up to date Java 8 JVM (for NUMA reasons), so the bundled JVM is not ever an option for me.

Can we either get the FTBApp to provide an option to configure the "Java Executable"  setting (like the memory setting), or have the FTBApp just read/remember/use the "javaDir" configuration from the `launcher_profiles.json` (that the `minecraft_launcher` edited / created)

**Comment by ecpoppenheimer** [comment]
Also having this issue.  I have to manually set the java path in the Minecraft launcher every time I launch, because the FTB launcher keeps overwriting the path.

**Comment by joakime** [comment]
I have discovered that this isn't unique to Linux, and happens on Windows 10 as well.

**Comment by joakime** [comment]
A workaround for others that see this issue.

The `$HOME/.ftba/bin/settings.json` has 2 "hidden" properties you can set manually (no UI for them at present).

* The `jrepath` property can be set to point to a specific java executable.
* The `embeddedjre` property is a boolean.

So for my linux box I configure embeddedjre to be false, and jrepath to point to my specific / desired Java binary.

Example: *$HOME/.ftba/bin/settings.json* (not sure of the location for this file on Windows)

``` json
{
  "jvmargs": "-XX:+UseNUMA",
  "embeddedjre": "false",
  "jrepath": "/home/joakim/java/jvm/openjdk-8/bin/java",
  "enableAnalytics": "true",
  "memory": "3072",
  "enableBeta": "false",
  "cacheLife": "5184000",
  "enablePreview": "false",
  "instanceLocation": "/home/joakim/.ftba/instances",
  "speedLimit": "0",
  "verbose": "true",
  "listMode": "true",
  "keepLauncherOpen": "true",
  "packCardSize": "1",
  "width": "2100",
  "threadLimit": "8",
  "height": "840"
}
```

These 2 properties cause the generated profiles for the minecraft_launcher to always have my preferred JVM.

**Comment by Rushmead** [comment]
This is due to how we utilise the Minecraft Launcher in order to launch modpacks. No settings made to an instance inside the Minecraft Launcher will persist. 

The above comment is a valid workaround, however, we will likely be adding a UI option for this soon.

**Comment by Jake-E** [comment]
You can change the JRE via the settings of an instance
