### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by NomadicVoyager** [FTBTeam/FTB-App#265]
**Operating System:**
OS: Windows

**Installer Version:**
Installer: FTBApp

**App Version:**
App:  Latest

**UI Version:**
UI: -

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app

**Describe the bug**
javaw is running denoting that minecraft is working however there is no UI

**To Reproduce**
Steps to reproduce the behaviour:
1. Load  Stoneblocks 2 on FTBApp
2. Click on Play

**Expected behaviour**
Ability To Play Minecraft

**Screenshots**
![image](https://user-images.githubusercontent.com/71002087/92566942-16a1a380-f2d1-11ea-8d82-58fd2f0ddb64.png)

**Additional context**

**Comment by Gaz492** [comment]
Can you upload the logs from the app via the settings menu and if there are any upload any logs from the modpack folder?

**Comment by NomadicVoyager** [comment]
*Vincent R. Johnston-Forsyth
<https://www.linkedin.com/in/vincent-johnston-forsyth-5208a544/>*
(+64) 27-758-8603
jfvinnie@gmail.com

**Comment by NomadicVoyager** [comment]
[latest.log](https://github.com/FTBTeam/FTB-App/files/5345375/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-App/files/5345376/debug.log)

**Comment by Gaz492** [comment]
> [latest.log](https://github.com/FTBTeam/FTB-App/files/5345375/latest.log)
> [debug.log](https://github.com/FTBTeam/FTB-App/files/5345376/debug.log)

Sorry for the delay in getting back to you, it looks like this may be an issue with the modpack or a mod in the modpack.
Your best reporting this issue at https://github.com/FTBTeam/FTB-Presents-Stoneblock-2
