### ISSUE TITLE
[Feature request] Use Minecraft Launcher already on system

### ISSUE THREAD

**Issue by skypartan** [FTBTeam/FTB-App#266]
**Is your feature request related to a problem? Please describe.**

When a modpack is installed, a copy of the official Minecraft Launcher is also downloaded and installed locally for the FTB-App to use, the app then register the downloaded modpack in this installation of the mc launcher.

**Describe the solution you'd like**

Since the app is utilizing the official launcher it should use the one already present in the system (or install it if not present), preventing duplicates of the software in the system, as well as centralizing all minecraft instance management in one single launcher.

**Comment by gigabit101** [comment]
Unfortunately, we need to edit the lancher_profiles.json (This stores all of the instance data for the Minecraft launcher) Due to this, we do not want to edit your existing Minecraft Launcher as this could lead to your default instances going missing.
