### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ppIol** [FTBTeam/FTB-App#267]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: FTB Installer

**App Version:**
App: StoneBlock 2

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
https://paste.feed-the-beast.com/view/71c42998

**Describe the bug**
Whenever I launch the mod in the mine craft launcher thing, it opens up and goes past the moving FTB logo but after that in the loading screen it always says not responding at the same place every time I launch. It grays out and then does not respond. the same results happen after trying to relaunch or reinstall.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to mine craft game launcher for modpack
2. Click on play and wait for it to load
3. Not responding at same loading place and crashes

**Expected behaviour**
I wanted it to just load up the game when I launch the mod but crashes every time.

**Screenshots**
![image](https://user-images.githubusercontent.com/71042296/92653372-1ab6cc80-f2a3-11ea-8b18-2a9c1bb15a3b.png)
![image](https://user-images.githubusercontent.com/71042296/92653482-45a12080-f2a3-11ea-95b4-86d55da41204.png)

**Additional context**
My friends i'm playing it with can run it fine and don't run into this problem

**Comment by Sunekaer** [comment]
Hi pplol

this is not a launcher issue, please report this on the issue tracker for Stoneblock 2
