### ISSUE TITLE
[Feature request] Sort/Search Feature for Specific Mods

### ISSUE THREAD

**Issue by Skarrum** [FTBTeam/FTB-App#268]
**Is your feature request related to a problem? Please describe.**
It's really annoying trying to look for a specific mod in a modpack when they are neither sorted by alphabetical order nor is there a way to search for it.

**Describe the solution you'd like**
A search bar around where I marked on the image, or the mods being sorted into alphabetical order.
![FTB](https://user-images.githubusercontent.com/55517360/92800224-1ad5cb80-f37a-11ea-80cd-c8211621be85.png)

**Additional context**
An image I think elaborates why this is needed
![FTB](https://user-images.githubusercontent.com/55517360/92801587-5c1aab00-f37b-11ea-8cdb-1e55873b303d.png)

**Comment by MichaelHillcox** [comment]
I've added this :+1: It'll be in the next release
