### ISSUE TITLE
[Bug] Error installing Material Energy^5: Enity - only one mod loader is currently supported

### ISSUE THREAD

**Issue by Pyro213** [FTBTeam/FTB-App#269]

**Comment by Maverician** [comment]
Having the same issue, cannot update Material Energy^5 entity from 1.05 to 1.11. The above error just appears at the bottom of the window with a RETRY button next to it, that seems not to do anything. 

I just deleted the mod pack, and no when trying to INSTALL Material Energy^5 it comes up with this error too.

**Comment by Gaz492** [comment]
HI,

Can you provide the information that is requested in the bug report template?
This will allow us to help debug your issue.

**Comment by Sunekaer** [comment]
Hi
This issue has been closed due to its not using the issue template.
Feel free to open a new issue using the template.
