### ISSUE TITLE
[Bug] Extreme performance hit when launching app on Linux

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-App#271]
**Operating System:**
OS: Kubuntu 20.04.1

**Installer Version:**
Installer: FTBA_unix_202007161516-479dedc615-release.sh

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
https://pste.ch/agovuvonej

**Describe the bug**
Extreme performance hit when launching. When screen recording the issue, the screen capture froze until it was done loading. Also, the mouse inputs get messed up. If I was moving my in a circle, the cursor would drift away from where I was moving it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on FTB app
2. Move mouse around while it is loading (then you will experience the mouse randomly move different)

**Expected behaviour**
The app would open with no performance hit or mouse issues.

**Screenshots/Videos**
https://youtu.be/Z2PoOg29Uyo - This OBS screen recording shows a brief freeze (was not visible to me, only shows in recording)

https://youtu.be/LUJ8qtUv8us - This phone recording of my screen shows what I see. For some reason, opening the launcher causes my mouse to mess up. I was moving my mouse in circle, not deviating, but in the video you can see that it randomly slows down and moves from the middle of my screen more upright.

(Note for the videos: I recorded these videos while I was running an older build and while using Pop!_OS 20.04 on Gnome. However, I experience the exact same system slowdowns while on Kubuntu with KDE).

**Additional context**
Relevant Computer Specs
- Intel i5-6500, 4 Cores @ 3.2GHz
- Nvidia 1660 Ti on driver version 440.100
- 16GB RAM
- Kernel 5.4.0-47 generic

**Comment by gigabit101** [comment]
Is this issue still persisting?

**Comment by MichaelHillcox** [comment]
Going around putting the same thing on most issues like this, our linux version of the app has had a lot of updates since this issue, please create a new issue if you're still having issues
