### ISSUE TITLE
Server connection

### ISSUE THREAD

**Issue by tomatopapa** [FTBTeam/FTB-App#272]
I'm playing on sky odyssey 1.2.0 and was playing on a server but now it won't let me connect and I've Tried redownloading everything but it just won't let me. It either says - " java.oi.IOexception: An established connection was aborted by the software in your host machine" or "Internal server error" can someone please help me

**Comment by Sunekaer** [comment]
Hi Tomatopapa,

This is not a launcher issue, please report on the packs issue tracker
