### ISSUE TITLE
Shortcut path still specifies executable in "/bin" and will not launch from taskbar

### ISSUE THREAD

**Issue by MrPipperz** [FTBTeam/FTB-App#273]
**Operating System:**
OS: Win 7

**Installer Version:**
Installer: FTBA_windows-x64_202007161516-479dedc615-release

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
Put links to your logs here
https://pste.ch/ixuvedefus

**Describe the bug**
See title.

**To Reproduce**
Attempt to launch app from taskbar.

**Expected behaviour**
App launches.

**Comment by Rushmead** [comment]
Please try pinning the actual exe instead of the running application. Please also provide more information on how to re-create this bug.
