### ISSUE TITLE
Stone Block 2 integrated tunnels dependencies

### ISSUE THREAD

**Issue by Tedber13** [FTBTeam/FTB-App#275]
So i updated stoneblock2 on the FTB app and when I try to open it to play it says it's missing a dependency and looking into the mods folder the missing mod is still there. the two mods it mentions are "Integrated tunnels" and "integrated Dynamics". here the prompt it gives me when trying to launch the modpack.   " You must include the right dependencies for **Integrated tunnels**: Requires **Intergrateddynamics** 1.0.9 or above (missing)"

**Comment by Sunekaer** [comment]
Hi
This issue has been closed due to its not using the issue template.
Feel free to open a new issue using the template.
