### ISSUE TITLE
[Feature request] Version Number in my modpacks page. 

### ISSUE THREAD

**Issue by Salnex** [FTBTeam/FTB-App#278]
**Is your feature request related to a problem? Please describe.**
Playing on servers requires specific versions of packs, often these are slow to update, or will remain on a certain version of the pack for awhile. The lack of a easily visible version number of the currently installed pack can be minor annoying in this case.

**Describe the solution you'd like**
On the my modpacks page an inclusion of the version number somewhere near the modpack's name.

**Comment by MichaelHillcox** [comment]
This is fixed in production :+1:
