### ISSUE TITLE
I downloaded skyfactory 2.5 but when ever i try to open it, it says "sorry unable to start minecraft please check your configuration " im stumped on what to due plz help

### ISSUE THREAD

**Issue by stacy7777** [FTBTeam/FTB-App#280]
**Operating System:**
OS: windows 10

**Installer Version:**
Installer: java

**App Version:**
App: 

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by Rushmead** [comment]
Please fill out the template correctly and also check that your issue has not already been reported or fixed.
