### ISSUE TITLE
Golem Factory

### ISSUE THREAD

**Issue by ViniEvil** [FTBTeam/FTB-App#282]
On the old launcher, you could use the code "captalism" to play a modpack called golem factory. Its one of my favorites modpacks.
but at the new launcher, there aren't any code button, and the modpack doesn't exist. I would like you to add the modpack or add the code bar

**Comment by Gaz492** [comment]
Hi,

The new App does not support the legacy launcher modpack codes feature.
You can download the legacy FTB launcher from the feed the beast website to install and play those modpacks

**Comment by ViniEvil** [comment]
thanks for the help!
