### ISSUE TITLE
Can't play FTB Presents Stoneblock 2

### ISSUE THREAD

**Issue by zKyros** [FTBTeam/FTB-App#283]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: idk

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app
https://paste.feed-the-beast.com/view/14674580
https://pste.ch/uqavuquwew

**Describe the bug**
I play the FTB Presents Stoneblock 2 Pack, I hit play also on the Minecraft launcher but after a while, it says that Minecraft is not responding, and I can only abort the process from Activity Monitor.

**To Reproduce**
I open the FTB App,
I click play of the FTB Presents Stoneblock 2 Pack
I hit play on the Minecraft launcher window that open ups
The game starts but stops loading.

**Expected behavior**
I open the FTB App,
I click play of the FTB Presents Stoneblock 2 Pack
I hit play on the Minecraft launcher window that open ups
The game starts but DON'T stops loading
I play the pack in a very funny way, hihihihi

**Screenshots**
![image](https://user-images.githubusercontent.com/54596161/94350172-f7827000-004b-11eb-8529-84c9f76c728d.png)
![image](https://user-images.githubusercontent.com/54596161/94350181-0ff28a80-004c-11eb-8a80-f1d62ed4fe95.png)

**Additional context**

**Comment by Sunekaer** [comment]
Hi zKyros, 

This is not an launcher issue please report this on Stoneblock 2's issue tracker
