### ISSUE TITLE
cant sign in

### ISSUE THREAD

**Issue by zmc13an** [FTBTeam/FTB-App#284]
there is no option for me to sign in with my mojang/minecraft account any fixes?

**Comment by Gaz492** [comment]
Hi,

You will be able to sign in to your Mojang/Minecraft account after pressing the play button on a modpack

**Comment by samscodesus** [comment]
whenever I sign in with Microsoft it will say I can Safley close the browser but when I go back to the ftb app it still has been waiting for a response.
