### ISSUE TITLE
[Bug] [Beta] Cannot stretch window from top edge

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-App#285]
**Operating System:**
OS: W10

**Installer Version:**
Installer: `FTBA_windows-x64_202007042254-9878310b16-develop`

![image](https://user-images.githubusercontent.com/15698722/94656407-ac739180-02c5-11eb-8e95-62a9c8ed2bca.png)
Can't copy from these, sorry

**Log Files:**
https://pste.ch/efitedeqay

**To Reproduce**
Move mouse over any other edge, see how it does the whole ↕↔ thing, then watch it not happen on the top

https://dl.dropboxusercontent.com/s/hrxfe2qpgqc9tm6/2020-09-30_02-34-25.mp4

**Comment by Gaz492** [comment]
This issue has been fixed in an upcoming version
