### ISSUE TITLE
A few points...

### ISSUE THREAD

**Issue by plaguewolf** [FTBTeam/FTB-App#287]
The ability to select an option in settings that will display the debug log, to enable users to diagnose problems in a timely manner. the ability for the main app window to remeber the size the window is previously resized to, or manually set the window size to something other than 800x400. this is esspecially annoying when viewed on a 4k monitor, as the window is super tiny.

**Comment by Rushmead** [comment]
Please follow the feature request template that is provided when creating an issue or this will be closed.
