### ISSUE TITLE
Clicking install on a modpack seems to make an already installed modpack be shown as installing

### ISSUE THREAD

**Issue by AKTheKnight** [FTBTeam/FTB-App#29]
I installed Omnia a few hours ago, now when I install FTB Revelation, Omnia is also apparently installing?

![image](https://user-images.githubusercontent.com/7502848/78311348-7f2d6d00-7548-11ea-8fae-e46bb9f541c2.png)

**Comment by Jake-E** [comment]
Is this still an issue or did we get this fixed @Gaz492?

**Comment by AKTheKnight** [comment]
Just checked and I can't reproduce it, so I'll close this for now :)

**Comment by manmaed** [comment]
i do bleave this issue is still around
