### ISSUE TITLE
"Sorry, unable to start Minecraft" Whenever I attempt to launch a pack.

### ISSUE THREAD

**Issue by DragonmasterDJ** [FTBTeam/FTB-App#290]
I decided to install ftb interactions but currently, I am having no luck in starting it. 
Here is the log pasted from the settings menu, not too sure if this helps, but here: https://pste.ch/kijegatese
I even tried to set it to freshly instal 1.12.2 but this offered no help.

**Comment by Rushmead** [comment]
Please provide more details or follow the bug report template provided. Please also check that the issue you are having has not already been reported.
