### ISSUE TITLE
[Feature request] Add an "All Packs" button

### ISSUE THREAD

**Issue by TeksuneStudio** [FTBTeam/FTB-App#292]
The pack search only shows me 10 items at a time, and there are no arrows for me to go from page to page. I want to find new modpacks and unless I know the name of the pack I won't be able to explore to new ones.

Please add an All Packs button so I can see all packs available to play.

Alternative: Add a Random Pack button to choose a pack that I don't have installed to try something new out. That'd be really cool.

Requested Solution: Add an All Packs button or give us a scroll wheel.

**Comment by Gaz492** [comment]
Hi,

Thanks for opening this feature request, as we already have a feature request open for this I will close this one to avoid clutter.

You can view the open feature request at #103
