### ISSUE TITLE
Linux FTB-App error

### ISSUE THREAD

**Issue by toddratson** [FTBTeam/FTB-App#293]
I have set up 3 Manjaro clients and an Ubuntu server to play Omnia on. The server runs great and two of the clients run without issue. The other client runs the .sh installer fine but when the app runs and I ask it to download Omnia it does nothing. I have openjdk 8, 11 and 14 installed and I have 8 as the default (same as a running machine). Using other methods (including the old FTB app) I can get other modded packs to run - just not the new app. I tried copying the pack from one client to another but the new app won't run it that way either. No errors, just nothing... I am running Manjaro plasma 5.8.11 on all three clients. I am at a complete loss. Anyone know where I should look next?

**Comment by DDR0** [comment]
I had a similar issue, just hung on a step. It worked the second time I tried it however, although Minecraft instantly exited with code 0 when I tried to run Sky Factory 3.

**Comment by Gaz492** [comment]
Hi,

Please follow the bug reporting template, without the information that is requested in the bug reporting template we are unable to diagnose what the issue may be.

**Comment by toddratson** [comment]
I know that you are volunteers and I appreciate your work in producing these modpacks. That being said @Gaz492 giving this comment nine days later with no link to the template I find not helpful.

**Comment by Jake-E** [comment]
The template is there when you create an issue. Feel free to open a new issue if you'd like to report it properly.
