### ISSUE TITLE
[Feature request] Follow/Support the XDG Base Directory Specification for Linux

### ISSUE THREAD

**Issue by CobaltSpace** [FTBTeam/FTB-App#294]
**Is your feature request related to a problem? Please describe.**
There is one more item in my home directory than there should be. I would like for my HOME directory to not have `.ftba` in it.

**Describe the solution you'd like**
Config files should be stored in `$XDG_CONFIG_HOME/ftba` or `~/.config/ftba` if `XDG_CONFIG_HOME` isn't set, instead of `~/.ftba`.

My request is to either change the config location or to make the launcher to use that location if it exists and `~/.ftba` doesn't exist.

If the default config location is changed, the default instance location should also be changed to `$XDG_DATA_HOME/ftba` or `~/.local/share/ftba` if `XDG_DATA_HOME` isn't set instead of `~/.ftba/instances`

**Additional context**
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by CobaltSpace** [comment]
Looking at installer, default Install location should be `$XDG_DATA_HOME/ftba` or `$XDG_DATA_HOME/FTBA` (`~/.local/share/ftba` or `~/.local/share/FTBA` if `XDG_DATA_HOME isn't defined), and the instance folder should be in that.

**Comment by MichaelHillcox** [comment]
Closing this as the one on modpacklauncher is the correct place :+1:

**Comment by Blacksmoke16** [comment]
@MichaelHillcox Is this actually resolved? I tried via the Arch AUR package and the official installer and `~/.ftba` was created in both cases even with all my preferred `XDG` env vars set.

**Comment by CobaltSpace** [comment]
I think this should be reopened. CreeperHost/modpacklauncher#15 is marked as complete, but this still appears to be broken here. Also, CreeperHost/modpacklauncher has been archived. Is that still being used as the backend, or is the backend here now?
