### ISSUE TITLE
[Bug] Cannot launch any modpacks. Exit code 0

### ISSUE THREAD

**Issue by Bupher** [FTBTeam/FTB-App#295]
**Operating System:**
OS: Windows 10 2004 19041.508

**Installer Version:**
Installer: 02007161516-479dedc615

**App Version:**
App: 02007161516-479dedc615

**UI Version:**
UI: 39f37b8d

**Log Files:**
Put links to your logs here
https://pste.ch/pinupubati
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**
Cannot launch any modded pack. Gives Exit Code: 0
I can get to the Minecraft launcher, with Omnia, Infinity, and Revelations. And I can launch vanilla from that launcher, but I cannot launch any modded pack. They all error out. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open FTB APP
2. Click on play pack
3. Click play in launcher

**Expected behaviour**
I expected the pack to launch.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/17689133/95663441-4e3c7f00-0b0d-11eb-9ea9-4dbf41ed66c4.PNG)

**Additional context**
Cannot launch packs through twitch, the old FTB app, or the new ftb app.
Updated to the latest verision of Java 8 (261)
![Capture](https://user-images.githubusercontent.com/17689133/95663470-7af09680-0b0d-11eb-8a57-db9e7e904686.PNG)

**Comment by DreadsCasey** [comment]
Same thing happening for me. Open the app, launch a mod pack and it crashes with error code 0
Running the same version of the app Bupher is (Latest i believe)

On Ubuntu 20.0 (Kernel 5.4.0-48)
Java version:
`
user@ubuntu:~$ java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
`

**Comment by masonrtomlinson** [comment]
Same thing is happening here.

Windows 10 1909
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

**Comment by c00ky1970** [comment]
Same error message and issue with Linux Mint

Linux Mint 19 Cinnamon - 3.8.9
Kernel - 4.15.0-121-generic

Gui:39f37b8d
App version:  02007161516-479dedc615
App File uploaded:
https://pste.ch/otogovevuh

**Comment by Rushmead** [comment]
Please can you provide the logs of the Minecraft launcher itself to do this you can do the following:

Press play on a modpack and then go to the Settings page of the Minecraft Launcher
![image](https://user-images.githubusercontent.com/1780637/96746640-4e673500-13bf-11eb-84f9-75eb6e653683.png)

Then tick the "Open output log when games start" option
![image](https://user-images.githubusercontent.com/1780637/96746741-68087c80-13bf-11eb-911a-9c4d6d746c95.png)

Then go back to Minecraft: Java Edition on the left sidebar and press play. This will open an output window like this:
![image](https://user-images.githubusercontent.com/1780637/96746930-98501b00-13bf-11eb-8296-f93cba60cf7c.png)

Please provide the logs from that window to us in a pastebin or gist.

**Comment by c00ky1970** [comment]
Hi,

Did as you requested and the log output is empty?? It just shows waiting for log output...

**Comment by c00ky1970** [comment]
[minecraft-game-output.txt](https://github.com/FTBTeam/FTB-App/files/5417619/minecraft-game-output.txt)

I uninstalled ftb app and re-installed the app, I have now attached output from Minecraft game output log.

**Comment by Bupher** [comment]
I had to reinstall windows, for unrelated reasons (corrupted primary partition somehow). And now it launches fine, sorry for my lack of data.

**Comment by masonrtomlinson** [comment]
I ended up deleting all Minecraft data on my computer, and then starting
with the install of FTB launcher. That ended up getting it working.

**Comment by DreadsCasey** [comment]
The solution I found was to install and use Java 8 instead of Java 11.

On Debian we can do this with
```
sudo update-alternatives --config java
```

**Comment by c00ky1970** [comment]
Hi!

That sudo update-alternatives command fixed my Linux Mint Issue - selected Java 8 and now it runs fine!

Many thanks!
