### ISSUE TITLE
[Bug] dates for news in the launcher is all wrong

### ISSUE THREAD

**Issue by DumbGameMaker** [FTBTeam/FTB-App#297]
**Operating System:**
OS: Windows 10 

**Installer Version:**
Installer: idk

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

probably not related

**Describe the bug**

In the news tab, the year for the date is always 2020 and the ordering is also wrong. for example: it says that on thursday, 28 may 2020 there was a post saying 'on the 31st october 2019, the partnership between FTB and twitch will be ending.' I haven't checked the date of that but i know it wasn't 2020 because it was referring to 2019 as the future. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to news
2. look at the dates of different news

**Expected behaviour**
the dates should be correct

**Screenshots**

**Additional context**

**Comment by DumbGameMaker** [comment]
ok, only news from 2019 was set to 2020

**Comment by Gaz492** [comment]
Hi,

Unfortunately, this is something that we are unable to fix due to an issue with the software we get the news feed with.
We will keep an eye out for any software updates that may fix the issue.
