### ISSUE TITLE
News tab doesn't sort news items alphabetically descending

### ISSUE THREAD

**Issue by Novocastrian** [FTBTeam/FTB-App#299]
![image](https://user-images.githubusercontent.com/4601813/96288929-e8ca2000-102f-11eb-8576-3446c316c55e.png)

This should be sorting alphabetically descending (ie, second news item in screenshot first, then 1st, then 3rd).

**Comment by Sunekaer** [comment]
This is due to the api that provides that news feed are showing the wrong date, the news is tho in the right order
