### ISSUE TITLE
[Bug] Browse and Home tabs load nothing

### ISSUE THREAD

**Issue by Novocastrian** [FTBTeam/FTB-App#300]
**Operating System:**
OS: Window 10

**Installer Version:**
Installer: FTBA_windows-x64_202007161516-479dedc615-release

**App Version:**
App: 202007161516-479dedc615-release (FYI this was painful to type out manually, as your app doesn't allow the user to highlight plaintext - it hyperlinks to https://github.com/CreeperHost/modpacklauncher, which is useless to the user). 
**UI Version:**
UI: 39f37b8d (same as above to here https://github.com/FTBTeam/FTB-App). 

**Log Files:**
https://pste.ch/doluxoyevu

**Describe the bug**
Home and Browse Tabs load no content.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install application and launch.
2. Click on tabs.

**Expected behaviour**
Whatever is meant to load here loads. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4601813/96289859-75c1a900-1031-11eb-9d6b-f81973d3b39d.png)

![image](https://user-images.githubusercontent.com/4601813/96289848-722e2200-1031-11eb-80af-7b8dc540f799.png)

**Additional context**
Uninstalled, rebooted, reinstalled and still experiences the same problem.

**Comment by GreenTheGamerPlayz21** [comment]
Same.

**Comment by DigitalBeef** [comment]
I'm also having this issue.

**Comment by hevans90** [comment]
same

**Comment by GreenTheGamerPlayz21** [comment]
Possibly a server issue?

**Comment by Sunekaer** [comment]
Fix for error in API has been deployed, please give it about 30min for caches to clear and then restart the app.
