### ISSUE TITLE
PlusTiC crashing on load

### ISSUE THREAD

**Issue by Icarius89** [FTBTeam/FTB-App#301]
in the Pre-menu loader, the game crashes at the loading stage for PlusTiC
[crash-2020-10-17_19.20.04-client.txt](https://github.com/FTBTeam/FTB-App/files/5396890/crash-2020-10-17_19.20.04-client.txt)

**Comment by Icarius89** [comment]
This is for FTB Interactions V2.0.9

**Comment by Gaz492** [comment]
This looks to be an issue with the modpack that you are trying to start.

To get the best support please report the issue on the issue tracker related to the modpack.
You can find the Interactions issue tracker here https://github.com/FTBTeam/FTB-Interactions/issues
