### ISSUE TITLE
[Bug] FTB University Server Install fails

### ISSUE THREAD

**Issue by KaziArmada** [FTBTeam/FTB-App#302]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: FTBA_windows-x64_202007161516-479dedc615-release

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
https://pste.ch/ojuvuresov

**Describe the bug**
Attempting to install server files for FTB University. 
Choosing Linux gives me a file that I am unable to actually do anything with in my current copy of Ubuntu. No instructions exist in the wiki for said file.
Choosing Windows gives an installer. Running said installer downloads the Mods, Mod Config, and a 'kubejs' folder containing some JavaScript files. Nothing else is downloaded. 
No attempt to manually install these to a forge server was made due to not easily finding what version of forge was expected. 

**To Reproduce**
Noted in bug description, simply do the basic act of server install. Managed 3 times with each version. 

**Expected behaviour**
A completed server install. 

**Screenshots**
N/A

**Additional context**
Noted in the launch thread for the pack on /r/feedthebeast, was suggested to report here as a possible app issue.

**Comment by Gaz492** [comment]
Hi on linux you may need to run chmod +x serverinstall_x_y (replace x and y with the numbers at the end of the serverinstall file you downloaded) then running ./serverinstall_x_y

In regards to the files not being downloaded correctly can you provide the output from the server installer?

**Comment by KaziArmada** [comment]
No idea why I didn't try that command, I blame minimal sleep. File was set to 777 when the following was done. 

Attempted ./serverinstall_52_134 on ubuntu, command ran and downloaded 100% fine, a full server with all the bits and bobs I'd expect from a server. 

Attempted a Windows Server install again to double check, everything worked fine today. Not sure what the issue was yesterday, but today it's either self-resolved or something else got fixed in the background. Issue resolved, closing.
