### ISSUE TITLE
[Bug] FTB University Server Pack fails to install OTG.

### ISSUE THREAD

**Issue by DrewSin-4** [FTBTeam/FTB-App#304]
FTBTeam/FTB-University/issues/13 

**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: serverinstall_52_134

**Describe the bug**
Server Installer installs all mods apart from OTG fine, OTG fails to download.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the Windows Server Install
2. Run it
3. Check the mods folder
4. o: OTG didn't download!

**Expected behaviour**
OTG should download.

**Screenshots**
https://i.imgur.com/kGS4awp.mp4

**Additional context**

**Comment by Gaz492** [comment]
Hi,
We are currently looking into this issue. From the video you posted it looks like the installer is running out of memory while downloading the files.

**Comment by Rushmead** [comment]
This should now be fixed, please download a new version of the installer and let us know :)

**Comment by mk12321** [comment]
i got the same problem with the newest installer, i got 10gb free memory it just goes down QUICKLY and than at some point it just quits itself with half the files missing

**Comment by DennisBengel** [comment]
I have exactly the same issue. When loading the exe from a bat file with a pause statement. I get the following error:

java.lang.OutOfMemoryError: Could not allocate an aligned heap chunk

Pc has 32gb of ram so that isn't an issue.

**Comment by DennisBengel** [comment]
When changing the maximum size of my paging file it went through. At the maximum (the end of the program) it used 44gb of ram, that is 32gb of physical and the rest was page file usage. No other applications were running at that moment.

**Comment by MichaelHillcox** [comment]
This should be resolved with the new server installer. Please reopen if this is not the case
