### ISSUE TITLE
[Bug] FTB Academy mods arent there?

### ISSUE THREAD

**Issue by Smushballs** [FTBTeam/FTB-App#306]
So i just rented a server for me and my friend to play FTB Academy, i have it downloaded in the FTP app but when i click modlist it doesn't show any mods, or when i open the folder and click mods there is nothing there.. I have tried deleting the modpack and redownload it several times now and still doesn't work. plz halp

**Comment by Gaz492** [comment]
Hi,

If you redownload the pack it should now download all the files
