### ISSUE TITLE
[Bug] FTB Infinity Launcher Can Only Select "Play Demo"

### ISSUE THREAD

**Issue by onlyusemebishops** [FTBTeam/FTB-App#307]
**Operating System:**
OS: macOS Catalina 10.15.3

**Installer Version:**
Installer: 

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**

https://pste.ch/zuputadumo

**Describe the bug**
Launcher only displays "Play Demo."  Can't connect to creeperhost server.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on FTBApp in Applications (or wherever it was saved)
2. Under "My Modpacks" on the left hand menu click on "FTB Infinity Evolved 1.7" or redownload.
3. Ensure you are on the "Minecraft: Java Edition" screen.  See "Play Demo" button.

**Expected behaviour**
Clicking on "Play Demo" opens up java app, but crashes before anything other than a black screen is displayed.

**Screenshots**

<img width="1003" alt="FTBApp" src="https://user-images.githubusercontent.com/73081653/96386568-e9ff6800-1169-11eb-882c-22507960e0e4.png">
<img width="1000" alt="Infinity Evolved Launcher" src="https://user-images.githubusercontent.com/73081653/96386569-ea97fe80-1169-11eb-987b-1e0581625408.png">

**Additional context**
Restarting internet connect, deleting/redownloading launcher, and deleting/redownloading modpack has no effect.  Not sure if this problem is local to my computer/connection or to an external source.

**Comment by Gaz492** [comment]
Hi,

Do you own a premium Minecraft account?

If not then you will need to buy one from https://minecraft.net

**Comment by onlyusemebishops** [comment]
> Hi,
> 
> Do you own a premium Minecraft account?
> 
> If not then you will need to buy one from https://minecraft.net

Is a premium account required?  I've been playing with this setup for the past month with no issues.

**Comment by onlyusemebishops** [comment]
Resolved!  Thanks @Gaz492 I just relogged into my profile.  I must have logged into an alternate account.  Don't know if I have premium but I can play now.
