### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by AngrySasukee** [FTBTeam/FTB-App#309]
**Operating System:**
OS:windows

**Installer Version:**
Installer:

**App Version:**
App: 

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**
when i open a modpack it opens the launcher, then i press play and on the top left it says unable to start minecraft
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/73162448/96559286-825e2f80-12c5-11eb-86c6-9b38712ba977.png)

**Additional context**

**Comment by Rushmead** [comment]
Please provide logs for this by following this guide: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs
