### ISSUE TITLE
[Bug] java.lang.UnsatisfiedLinkError: could not load i4jinst from true

### ISSUE THREAD

**Issue by whitebear60** [FTBTeam/FTB-App#310]
**Operating System:**
OS: Mac OS Yosemite 10.10

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

https://pste.ch/edovogomok.sql
https://pste.ch/apotazunod

**Describe the bug**
When FTB App opens, it shows an error:
![Screen Shot 2020-10-20 at 14 31 52](https://user-images.githubusercontent.com/42472132/96580517-11c50c00-12e1-11eb-9d6e-81050437d606.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Open FTBApp
2. See error

**Screenshots**

**Additional context**
My system:
![Screen Shot 2020-10-20 at 14 33 06](https://user-images.githubusercontent.com/42472132/96580600-3325f800-12e1-11eb-991b-7af424bef2f4.png)

**Comment by MichaelHillcox** [comment]
Going around putting the same thing on most issues like this, our macos version of the app has had a lot of updates since this issue, please create a new issue if you're still having issues
