### ISSUE TITLE
[Bug] change instance location modal

### ISSUE THREAD

**Issue by Sunekaer** [FTBTeam/FTB-App#311]
**Operating System:**
OS: Windows 10

**App Version:**
App: 202010211552-d057dc2cdf-prototyping

**UI Version:**
UI: e0241aa3

**Log Files:**
Not needed

**Describe the bug**
So if you go to settings and change your Instance Location, it will pop a modal saying please wait moving instances...
If you click outside of the modal it closes the modal and you would think it cancelled the moving but its actually still moving the files.

Fix make it so you cant close the modal until its done or make it cancel the change the and move the files back.

**Expected behaviour**
To not be able to close it

**Screenshots**
this modal im talking about: 
![image](https://user-images.githubusercontent.com/18720460/96765402-5d0f1580-13da-11eb-93f4-fcb10f42c3bb.png)

**Comment by MichaelHillcox** [comment]
This should now be fixed
