### ISSUE TITLE
[Feature request] Loading bar on modal for moving instances 

### ISSUE THREAD

**Issue by Sunekaer** [FTBTeam/FTB-App#312]
**Describe the solution you'd like**
On this modal below it would be nice to have a loading bar and also it to say "moving instance 1 out of 11" when it's moving the instances and moving the local cache, say moving local cache files or something.
Just to indicate that it is doing something
![image](https://user-images.githubusercontent.com/18720460/96766116-e45c8900-13da-11eb-85de-e5aff1c80f69.png)

**Comment by MichaelHillcox** [comment]
This should be sorted now
