### ISSUE TITLE
[Bug] change instance location modal doesnt close after move is done

### ISSUE THREAD

**Issue by Sunekaer** [FTBTeam/FTB-App#313]
**Operating System:**
OS: Windows

**App Version:**
App: 202010211552-d057dc2cdf-prototyping

**UI Version:**
UI: e0241aa3

**Log Files:**
https://pste.ch/oqejazarut

**Describe the bug**
After the app had moved all the instances it didn't close the modal, leaving the user to think it's still moving files.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to settings
2. Change install location
3. Just leave it and see it never close the modal

**Expected behaviour**
Modal to close after move is done

**Comment by MichaelHillcox** [comment]
@FTBTeam/app-team

**Comment by MichaelHillcox** [comment]
This looks to be fixed :+1:
