### ISSUE TITLE
FTBapp not launching on Mac (Stuck on "creating environment" and "Installing Vanilla Launcher"

### ISSUE THREAD

**Issue by chrisrk** [FTBTeam/FTB-App#316]
Hi! I am on Mac OS and want to use the FTBapp. The launcher sadly does not even allow me to install the mods. But when I close the app and re-open it, the mod is somehow installed but then does not open and gets stuck on "creating environment" and "Installing Vanilla Launcher". I have seen previous users from a couple years ago with the similar issue, but this seems to be a new one and the old fixes do not work. 

Thank you.

**Comment by Gaz492** [comment]
Please follow the bug report template and provides the information requested in the template
