### ISSUE TITLE
[Bug] When i click play on the FTB app it takes me to the Minecraft Launcher and when i click play on that is says "Exit code: 0" 

### ISSUE THREAD

**Issue by PrinceShadow995** [FTBTeam/FTB-App#317]
**Operating System:**
OS: Windows 

**Installer Version:**
Installer: i don't know 

**App Version:**
App: i don't know

**UI Version:**
UI: i don't know 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs
https://pste.ch/awinaruwus
**Describe the bug**
When i click play on the FTB app it takes me to the Minecraft Launcher and when i click play on that is says "Exit code: 0" 
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
i want to be able to play Stoneblock 2. but when i launch it says exit code; 0
**Screenshots**
![image](https://user-images.githubusercontent.com/73453413/97129070-d2d4f300-16f2-11eb-8eff-fe98941bd715.png)
**Additional context**

**Comment by Quetzi** [comment]
Please could you link your client logs https://faq.ftb.world/books/ftb-app/page/finding-your-client-logs will tell you how to find them.
