### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by chrisrk** [FTBTeam/FTB-App#318]
**Operating System:**
OS: Catalina 10.15.7

**Installer Version:**
Installer: Don't know what this should be.

**App Version:**
App: "FTBA_macos_202007161516-479dedc615-release"

**UI Version:**
UI: "39f37b8d"

**Log Files:**
Put links to your logs here : It is not allowing me to upload my logs/nothing happens when I click "upload logs"
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**

I download the FTBapp and then attempt to download a modpack. Once I attempt to download it, the installer gets stuck on "creating environment" or "installing vanilla launcher". After 20 minutes of attempting to let it load, I force quit the program and restart it. After I reopen it, the mod that I wanted to install is automatically installed, but will not let me open it then. I click on "play" and nothing happens.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

What is supposed to happen is that the mod I want to install fully installs and then lets me click on play. Then the game launcher should open and I would be good to go.

**Screenshots**

N/A

**Additional context**

**Comment by pie-flavor** [comment]
If you have the Minecraft launcher open in any capacity, try fully closing it.

**Comment by Quetzi** [comment]
We need the App logs to begin debugging this, please follow the instructions at https://faq.ftb.world/books/ftb-app/page/uploading-app-logs and reply with a link to your logs.
