### ISSUE TITLE
[Bug] OTG presets portals not working

### ISSUE THREAD

**Issue by Nidaelie** [FTBTeam/FTB-App#320]
**Operating System:**
OS:

**Installer Version:**
Installer:

**App Version:**
App:  ftba

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**

New update gives u now the blocks needed to form the portals to other preset dims. Formed them like the nether portal as the questbook says, used the flint and nothing happens.

**To Reproduce**
Steps to reproduce the behaviour:
1. complete the quest
2. form the portals frames
3. try to ligth with the flint and steel
4. nothing happens

**Expected behaviour**

**Screenshots**
![2020-10-28_13 33 27](https://user-images.githubusercontent.com/31002746/97436742-be773d00-1922-11eb-9d33-1b2b205332fe.png)

**Additional context**

**Comment by Rushmead** [comment]
This repository is not for issues with modpacks. Please report this on the repository for the modpack: https://github.com/FTBTeam/FTB-University
