### ISSUE TITLE
[Bug] Stoneblock 2

### ISSUE THREAD

**Issue by Agingerboy99** [FTBTeam/FTB-App#321]
**Operating System:**
OS: Windows

**Installer Version:**
Installer: Latest

**App Version:**
App: Latest

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**
when i click play in the Minecraft launcher it loads the mods and the it gives me the error that i show down below

**To Reproduce**
1. Go to 'Stoneblock 2'
2. Click on 'play'
4. See error ender io fatal recipe error

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/73605001/97467597-bddaa880-191a-11eb-957a-ad0e7bcf8955.PNG)

**Additional context**

**Comment by StephJ2Fan** [comment]
Hey AGingerboy99 complete the form like the rest of us. Putting your issue in the title doesn't help the devs determine anything.

**Comment by Gaz492** [comment]
HI,

This appears to be a modpack issue, could you report it at https://github.com/FTBTeam/FTB-Presents-Stoneblock-2 so the modpack developer can take a look at it.
