### ISSUE TITLE
[Bug] Packs with long names cut the entire last word, instead of just cutting off the last 3 characters for the "..."

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-App#322]
**Operating System:**
OS: W10

**Installer Version:**
Installer: FTBA_windows-x64_202007161516-479dedc615-release

![image](https://user-images.githubusercontent.com/15698722/97497800-0e60fe80-1939-11eb-8c88-752daffe5914.png)
(These should really be right-clickable to copy them, clicking them just sends you to the issue trackers)

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**
The ... replaces the word entirely, so it just gets left showing as "FTB ..."

**To Reproduce**
Steps to reproduce the behaviour:
1. Install FTB Interactions
2. Go to the tile form
3. Look at it

**Expected behaviour**
It should say like, `FTB Intera...`

**Screenshots**
![image](https://user-images.githubusercontent.com/15698722/97497477-87ac2180-1938-11eb-9580-fb5bd36edfdf.png)

**Additional context**

**Comment by MichaelHillcox** [comment]
Fixed in production :+1:
