### ISSUE TITLE
[Bug] So. I've got a bit of an issue with the FTB launcher, specifically, when I hit play and it redirects me to the old MC launcher, it doesn't do anything. It's in a perpetual state of loading. Anyone know what to do?

### ISSUE THREAD

**Issue by TheJoker112103** [FTBTeam/FTB-App#324]
**Operating System:**
OS:

**Installer Version:**
Installer:

**App Version:**
App: 

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by Gaz492** [comment]
Please provide all the information requested by the bug report template
