### ISSUE TITLE
FTB App Only launches at the end of (from within) the install process

### ISSUE THREAD

**Issue by Grimjahk** [FTBTeam/FTB-App#325]
After i close the installer, any time I try to launch the app, It runs as a process (Seen from task manager) but i can't access it on either screen.

After that I have to scrub the install to reinstall it again.

**Comment by Gaz492** [comment]
Could you tell me how you attempt to start the FTB App when not using the installer?
Are you starting it from a shortcut you pinned to the task bar or desktop?
If you are can you go to the start menu > programs > FTBApp and start it from there to see if it works.
If it does remove the old shortcut you had ben create one using the FTBApp in the start menu

**Comment by Grimjahk** [comment]
I've done all those things. Desktop, Task Bar, Fast Start Menu.

But, after a hour long google search, in the end, I was only launching from the start menu (too afraid to even put a second copy inside the start menu)

**Comment by Jonathany25** [comment]
I can open the app if I open the .exe from C:\Users\[User]\AppData\Roaming\FTBA

**Comment by VMichailidis** [comment]
I have encountered the same problem on Linux. After the installation, the launcher worked just fine. However, after I closed the programme I haven't been able to relaunch either with dmenu or by running FTBApp.desktop in my terminal. The app is installed at ~/.local/share

**Comment by VMichailidis** [comment]
> I have encountered the same problem on Linux. After the installation, the launcher worked just fine. However, after I closed the programme I haven't been able to relaunch either with dmenu or by running FTBApp.desktop in my terminal. The app is installed at ~/.local/share

Apparently running $bash ~/.local/share/FTBLauncher/FTBApp runs the app just fine

So I run:
# ln -s /home/basil/.local/share/FTBLauncher/FTBApp /usr/bin/FTBApp
and
#sudo chmod +x FTBApp

and now my system treats it like an app.
