### ISSUE TITLE
Im having issues downloading and updating modpacks, its just not working at all

### ISSUE THREAD

**Issue by HazeCapra** [FTBTeam/FTB-App#328]
pretty much all in title

**Comment by Grimjahk** [comment]
I maybe can save you a bit of a wait... you will be asked all sorts of details like where, with what, and how...

In a nutshell, if you don't give more information to help them help you, it takes them time to do so.

**Comment by Gaz492** [comment]
Please follow the bug reporting template when reporting bug reports.
