### ISSUE TITLE
[Bug] With a server install

### ISSUE THREAD

**Issue by CodeMastr3** [FTBTeam/FTB-App#329]
**Operating System:**
OS: Windows 10

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Describe the bug**
I am experiencing a bug installing a server for a modpack and was directed here I think. https://github.com/FTBTeam/FTB-University/issues/138

**To Reproduce**
Steps to reproduce the behaviour:
1. Download FTB University server exe for windows
2. Try to install it
3. Watch as it crashes from memory allocation error

**Expected behaviour**
Server gets installed

**Comment by Jake-E** [comment]
We pushed out an update of the server installer that should have fixed this, please let me know if you're still seeing issues.
