### ISSUE TITLE
FTB Launcher exe disappeared after launch attempt

### ISSUE THREAD

**Issue by TheAsianJewMan** [FTBTeam/FTB-App#33]
I downloaded the launcher to a folder in my documents folder. When I double clicked the .exe to launch the .exe disappeared and nothing launched. Re-downloaded with the same issue.

Running Windows 10

**Comment by Cloudhunter** [comment]
This sounds like it is your anti-virus/anti-malware or other software removing it, as there is no code that could possibly be doing this.

Can you make sure it is whitelisted on these and see if you still have the same issue?
