### ISSUE TITLE
Old Modpacks

### ISSUE THREAD

**Issue by Leloutachi** [FTBTeam/FTB-App#331]
Why aren't all the old Modpacks in the new FTB launcher? 
I tried playing FTB Lite like in the good old times, but then I had to realize that it is only on the twitch launcher available, and that you can't play the very old versions, just the "newer" versions that dont include e.g. Not enough items.

**Comment by Gaz492** [comment]
Our priority was to get the most recent modpacks working on the new app first as the older modpacks are available to download via the FTB Legacy launcher which can still be downloaded from the FTB website.

Our plan is to eventually the older modpacks working on the app.
