### ISSUE TITLE
[Feature request] "ModList tab" to be available before installation of the pack

### ISSUE THREAD

**Issue by MrGREGhimself** [FTBTeam/FTB-App#332]
**Describe the solution you'd like**
An ability to see/preview what mods are included in the pack before installing it.

**Additional context**
Currently, the mod list comes up briefly during the installation of the pack and the ModList tab is available when the pack has been installed.
This feature would allow users to save some time installing and uninstalling packs they might not want to play (or to check if the pack contains mods they wish to play with).

**Comment by Gaz492** [comment]
duplicate issue see #168
