### ISSUE TITLE
[Bug] (1st) My world save has just disappeared and (2nd) Now when i click play on the modpack FTB Revelation the mods just wont load now, it only says 4 mods loaded

### ISSUE THREAD

**Issue by XTinxt** [FTBTeam/FTB-App#333]
**Operating System:**
OS: Windows 10 pro

**Installer Version:**
Installer: 3.3.0

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Log Files:**
https://pste.ch/ulofipojib
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**
A clear and concise description of what the bug is. Mentioned above in title

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'FTB launcher and press play on the modpack Revelations, load up minecraft and look at bottom left, 4 mods installed, check singleplayer, world save is gone, *shock ensues*'

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by Gaz492** [comment]
Your world is likely still located where the app previously-stored the modpack data, regarding the modpack not loading do you still have issues with this on the latest versions of the app?

If you do still have issues would you be able to open a new issue and follow the bug reporting template for your operating system?
