### ISSUE TITLE
[Bug] Server Files for FTB University aren't downloading correctly

### ISSUE THREAD

**Issue by LaLamborghini331** [FTBTeam/FTB-App#334]
When trying to download the server files for FTB University from the FTB App, the installer downloads perfectly fine, but during the installation of the actual server files, it says it is failing to download a majority of them. When checking the files in the directory, the file size of most of the files sits at 0KB. 

My internet runs at 55Mbps / 7 MB/s with a ping of 10. That shouldn't be a problem.
![image](https://user-images.githubusercontent.com/56442864/98455524-8b079e80-21bd-11eb-95c8-a5469107778e.png)

**Comment by Gaz492** [comment]
If you are still having issues with downloading the server files would you be able to create a new issue over at https://github.com/CreeperHost/modpacksch-serverdownloader/issues
