### ISSUE TITLE
[Bug] Uninstalling the launcher does NOT remove the instances directory.

### ISSUE THREAD

**Issue by olfMombach** [FTBTeam/FTB-App#335]
**Operating System:**
OS: Windows 10 (64bit)

**Installer Version:**
Installer: ?

**App Version:**
App: 202007161516-479dedc615-release

**UI Version:**
UI: 39f37b8d

**Describe the bug**
When uninstalling the launcher (through the programs and apps settings) the uninstaller removes neither the directory that is set as a default instances directory ( %USER%/.ftba/ ) nor any arbitrary directory that has been set as the instances directory in the time the launcher has been installed (the launcher also does not remove the original instances directory while moving instances directories, but that's another story). The instances directory includes data that adds up to a significant amount, so it is not acceptable to just leave it on the host system when uninstalling.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install
2. Do stuff, like downloading modpacks
3, Uninstall

**Expected behaviour**
Every trace of the launcher is removed, including all instances directories that have been created over the lifespan of the application.

**Comment by Quetzi** [comment]
Actual pack instances are considered user data, it is entirely feasible that a player uninstalling the App intends to use those instances in the future, either via another launcher, or by reinstalling the FTB App at a later date.

**Comment by ObviouslyImDoingSomethingWrong** [comment]
I'm having the same issue, but even after uninstalling the app, and trying to delete the instance manually, it tells me it's in use. The app won't let me delete the instance either.
