### ISSUE TITLE
[Bug] Revelation silently fails to launch

### ISSUE THREAD

**Issue by mcronce** [FTBTeam/FTB-App#336]
**Operating System:**
OS: Arch x86-64

**Installer Version:**
Installer: `FTBA_unix_202007161516-479dedc615-release.sh` (is this the correct thing about which you're looking for the version?)

**App Version:**
App: `202007161516-479dedc615-release`

**UI Version:**
UI: `39f37b8d`

**Log Files:**
https://pste.ch/lajopupacu

**Describe the bug**
After installing Revelation, when I try to launch it, nothing happens.  I didn't notice anything that seemed to be a smoking gun in the logs.  There's no error reported in the GUI, nor anything to stdout/stderr.

**To Reproduce**
Steps to reproduce the behaviour:
1. Starting with no FTB launcher state (e.g. `rm -Rf ~/.local/share/FTBA ~/.ftba`), fire up `FTBApp`
2. Manually create `~/.ftba/bin/launcher_profiles.json`
3. Install Revelation
4. After install completes, try to launch Revelation

**Expected behaviour**
Revelation launches :) or, at the very least, whatever problem is causing it to not launch is surfaced clearly to me - preferably in a UI error, but to a log would certainly work much better than nothing.

**Additional context**
The only thing noteworthy is that I had to manually `touch ~/.ftba/bin/launcher_profiles.json` in order for downloading to work - otherwise downloading the modpack doesn't work either, it just hangs forever on "creating environment" - but does immediately pick up as soon as I create that file; I don't need to restart the launcher or click "get" again or anything.

I've tried a couple other modpacks and they seem to fail to install/launch but I haven't dug into why yet.  This is the particular one I'm interested in, as the server I'm looking to play on uses it.

**Comment by mcronce** [comment]
As it turned out, `FTBApp` was failing to start `minecraft-launcher` because I didn't have a locale generated (amazing that anything has worked on this machine at all, TBH)

I still think that surfacing errors to the user could be done a whole lot better, though, if anybody wants to purpose this issue for that specifically.

**Comment by trickymelts** [comment]
Hey I am having this same problem after playing without any issue for 2 days, It started today after while playing my dog unplug my power cord and the pc shut off. After turning it on i clicked on play and it didnt load the minecraft launcher it stays in the ftb launcher without doing anything

**Comment by Gaz492** [comment]
If any of you are still having issues with launching modpacks on the app, could you try downloading the latest version of the app and see if the issue is resolved. If the issue is still happening would you be able to open a new issue and follow the bug reporting guide for your operating system,?
