### ISSUE TITLE
[Bug] 'Browse' displays already installed packs with 'Get' option

### ISSUE THREAD

**Issue by MrGREGhimself** [FTBTeam/FTB-App#338]
**App Version:**
App: Closed Beta

**UI Version:**
UI: Closed Beta

**Log Files:**
https://pste.ch/tozafiloma

**Describe the bug**
After installing a few packs and checking the 'Browse' menu, I've noticed that the 'Get' icon is displayed (on hover) on packs already installed. 
Clicking on 'Get'  and then 'Install' in the above view actually creates a new instance of the pack.
Clicking on 'more' takes you to a page where 'Install' button is available, even tho the pack is already installed and visible in 'My Modpacks menu'.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install a pack
2. Go to 'Browse' and search for the already installed pack.
3. Notice 'Get' option

**Expected behaviour**
In 'Browse' packs should allow installation (if required) but should show that the pack is already installed if this is the case.

**Comment by Jake-E** [comment]
I don't see a reason for this to change, we support multiple instances per pack.
