### ISSUE TITLE
[Bug]FTB app failed to launch

### ISSUE THREAD

**Issue by Jonathany25** [FTBTeam/FTB-App#339]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: FTBA_windows-x64_202007161516-479dedc615-release

**App Version:**
App:  202007161516-479dedc615-release

**UI Version:**
UI:  39f37b8d

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**
When I try to open the app it wont load, but a workaround I found is running the installer and updating the app, but everytime
I want to open the app, I have to update it

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the FTB app

**Expected behaviour**
The app will load normally

**Screenshots**

**Additional context**

**Comment by Gaz492** [comment]
Can you upload the logs from the app as detailed in the guide at https://faq.ftb.world/books/ftb-app/page/uploading-app-logs and reply with a link to the logs?

**Comment by Jonathany25** [comment]
can't open the app, any alternative to seeing the logs?

**Comment by Jonathany25** [comment]
Is it the same as main.log?

**Comment by Gaz492** [comment]
Can you navigate to C:\Users\<yourname>\.ftba I believe there may be a log there that you can upload.
If there is not a log there you will need to navigate to where you installed the app then there should be a log in there

**Comment by Jonathany25** [comment]
https://pastebin.com/aNz6aVSU
The log I could find

**Comment by Jonathany25** [comment]
I can open the app if I open the .exe from C:\Users\[User]\AppData\Roaming\FTBA
