### ISSUE TITLE
Launcher tried to install *already installed* vanilla launcher

### ISSUE THREAD

**Issue by Commandore32** [FTBTeam/FTB-App#34]
I clicked download on FTB continuum, then the pack downloaded. While the launcher said "installing vanilla launcher", the Minecraft Vanilla launcher loaded and ran the pack successfully. However, it now appeared like the pack was running flawlessly while the FTB launcher was still trying to install it. As someone with no programming experience what so ever, I was a little concerned. I closed both the game and the launcher, and when I tried to reopen the FTB launcher, I was greeted with this. 

https://drive.google.com/file/d/1S-he4BfAkbxcqJPg1bRQWeg0816pqyMJ/view?usp=sharing

I asked for and received the go-ahead from slowpoke to attempt a reinstall. I tried both options, saving to my desktop with the second, and neither of them worked. I tried deleting the previous installation (including the FTBApp.exe and installer) but when I tried to delete the old FTBA folder in my roaming folder or the FTBApp.exe, it wouldn't allow me to. 

 https://drive.google.com/file/d/1_bWZ_HsEEeJW3tIvptRP5U69ljV9sfKa/view?usp=sharing
 
https://drive.google.com/file/d/1zvA_qScZ9dxaFMilXrXdU9QKTZ-6JT0A/view?usp=sharing

The end! 
        
[error.log](https://github.com/FTBTeam/FTB-App/files/4424613/error.log)

[error.log](https://github.com/FTBTeam/FTB-App/files/4424624/error.log)

**Comment by Gaz492** [comment]
Can you upload the log found in the installation directory?

**Comment by Commandore32** [comment]
Specific file name?

**Comment by Commandore32** [comment]
[error.log](https://github.com/FTBTeam/FTB-App/files/4424611/error.log)

**Comment by Commandore32** [comment]
Is this the one?

**Comment by Commandore32** [comment]
[error.log](https://github.com/FTBTeam/FTB-App/files/4424626/error.log)

This one's from my roaming folder

**Comment by Commandore32** [comment]
Sorry if these aren't the ones. I feel like this is a very hectic first day, and looking at the other issues, I see that you're working hard. Keep going!

**Comment by Rushmead** [comment]
This is installed as a normal Windows application, you need to uninstall it from the Control panel like a normal program. Then you'll be able to re-run the installer to re-install the launcher.

**Comment by Cloudhunter** [comment]
Deleted Rushmead's reply as it was a bit confusing.

Can you try closing FTBApp via the task manager if it is there, and then try reinstalling?
