### ISSUE TITLE
Can't download modpacks in the FTB-app

### ISSUE THREAD

**Issue by S1mpleLogic** [FTBTeam/FTB-App#340]
I can't download modpacks any more in the ftb app.
When I start the app up and I click download on any modpack, then at the bottom of the window there stands: "Creating Environment". But this text does not disappear. I already tried to restart the app and then it is installed, but when I start the modpack, in the minecraft launcher there is an error that my minecraft version instance is not installed properly.

**Comment by Gaz492** [comment]
Please follow the bug reporting template when reporting issues with the app
