### ISSUE TITLE
Can't download modpacks

### ISSUE THREAD

**Issue by iphimedeia** [FTBTeam/FTB-App#341]
**Operating System:**
OS: 10.15.7

**Installer Version:**
Installer: FTBA_macos_202007161516-479dedc615-release.dmg

**App Version:**
App: 202010030938-ffcddc491e-preview

**UI Version:**
UI: cbdcbgc3

**Log Files:**
Put links to your logs here
how to find logs: https://pste.ch/lududorezo

**Describe the bug**
If I try and download a modpack, it will be stuck on Installing vanilla launcher and not move for hours (longest I've left it is 6 hours). But if I quit the app and open it again, it will say its been installed but when I press play nothing happens, it's like the click isn't even registered. Redownloaded the app around 5 times already.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open app
2. Download modpack (Press get)
3. Spinning circle forever
4. Quit app
5. Reopen app
6. Press "play"
7. Nothing happens.

**Expected behaviour**
For the modpack to download and actually launch?

**Screenshots**
<img width="992" alt="Screenshot 2020-11-17 at 10 23 38 AM" src="https://user-images.githubusercontent.com/74578147/99338342-fa1c7b80-28be-11eb-9cd4-547d248f551e.png"> - nothing will happen if I press play.

**Additional context**
Redownloaded the whole app and invidividual modpacks multiple times.

**Comment by callan517** [comment]
I experienced the same issue and had managed to fix it by; 
1. Closing the launcher down
2. Open the launcher again
3. Going to my modpacks
4. deleting the modpack
5. search for the modpack
6. instead of pressing get on the small box click more
7. go into versions and download the latest version from there.
The get button seems to be a bit buggy I would assume.
Hope this fixes your issue!

**Comment by interficere** [comment]
Exact same problem here. Downloading from the latest version does not do it for me.

**Operating System:**
OS: 11.0.1

Rest identical to op

**Comment by Sorcuring** [comment]
Same Problem here with macOS Mojave 10.14.6 and

java --version
java 14 2020-03-17
Java(TM) SE Runtime Environment (build 14+36-1461)
Java HotSpot(TM) 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

**Comment by Gaz492** [comment]
If you are still having issues with downloading modpacks could you make sure to download the latest version of the app from the FTB website then create an issue if the issue still persists.
