### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Kalistijo** [FTBTeam/FTB-App#343]
Look im not sure about all this other crap i just need an bloody answer as to why i have to keep reinstalling this goddamn app. It says its installing the app, but its nowhere on my compuuter and instead I have to click on ftb.exe which only fucking makes me have to reinstall the whole blopdy thing. Mind you I can still pickup where i left off, but that dosent take away from the fact that I just want the app to fuking open so I dont have to keep reinstalling to the same goddamn place. Fucks sake this should be simple shit man.

**Comment by Gaz492** [comment]
Without the logs from the app/steps to reproduce/more information about how you are starting the app we are unable to assist you as we have little information to help debug the issue.

Filling out as much information as you can in the bug reporting template gives us the best chance in resolving the issue you are having.
I would also ask you to stop using abusive language
