### ISSUE TITLE
I'm not being able to run the modpack

### ISSUE THREAD

**Issue by Davigo47** [FTBTeam/FTB-App#344]
When I click on the "Play" button of a modpack nothing happens I don't know if I'm doing something wrong or not. Help, please.

**Comment by Beckerbreken** [comment]
I have the problem. The launcher starts preparing the game but never finishes. If I then close it the launcher will not open again if I try to relaunch the game.

**Comment by trickymelts** [comment]
I have a similar problem, today i was playing ftb revelations without any issue until my dog unplug my power cord while playing. After turning the pc back on and trying to load the game from the ftb launcher, it wont launch the minecraft launcher nor do anything else it just stays at the ftb launcher

**Comment by Beckerbreken** [comment]
I bumped up the ram allocated to the pack from the settings menu and the
game decided to launch. I do not now if this was the actual fix or not.

**Comment by Gaz492** [comment]
If anyone is still having issues launching modpacks please open a new issue.
