### ISSUE TITLE
[Bug]Whenever I try to open the App, the window never shows up. 

### ISSUE THREAD

**Issue by N3tflix** [FTBTeam/FTB-App#345]
**Operating System:**
OS:Windows Version 1909

**Installer Version:**
Installer:FTBA_windows-x64_202007161516-479dedc615-release (2)

**App Version:**
App: idk

**UI Version:**
UI: idk

**Log Files:**
Put links to your logs here
This is the error log in the FTBA folder
[error.log](https://github.com/FTBTeam/FTB-App/files/5576950/error.log)
This is the launcher log
[launcher.log](https://github.com/FTBTeam/FTB-App/files/5576951/launcher.log)
**Describe the bug**
My window menu thing wont open. It runs as a background application with 63.6 mb of memory but never shows up. I run it through appdata - roaming - FTBA - then the exe. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'appdata'
2. Click on 'roaming'
3. Scroll down to 'FTBA'
4. Click on it
5. Run the 'FTBApp.exe'
6. Never see it pop up

**Expected behaviour**
In the error log it shows that 
net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: Not a valid instance '.localCache', skipping... 
as well as
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
Something is missing. I dont know what or how to find it. 
**Screenshots**

**Additional context**
Many people are having this problem currently.

**Comment by Gaz492** [comment]
Could you try downloading the newest version from the FTB website and try again.
If the issue still happens could you open a new issue?
