### ISSUE TITLE
[Bug] Linux Launcher dying immediately

### ISSUE THREAD

**Issue by Rando-Khan** [FTBTeam/FTB-App#346]
**Operating System:**
OS: Debian 10 / Buster, aarch64

**Installer Version:**
Installer: See below.

**App Version:**
App: 

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

I'd do this, but the launcher doesn't open long enough for me to interact with it.

**Describe the bug**

It looks like electron starts and immediately dies, and it isn't clear to me why.

**To Reproduce**
Steps to reproduce the behaviour:
$ java -jar launcher-202007161516-479dedc615-release-all.jar 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Nov 21, 2020 11:09:57 P.M. net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: Not a valid instance '.localCache', skipping...
Nov 21, 2020 11:09:57 P.M. net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Loaded 0 out of 1 instances.
Nov 21, 2020 11:09:57 P.M. net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: Not a valid instance '.localCache', skipping...
Nov 21, 2020 11:09:57 P.M. net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Loaded 0 out of 1 instances.
Nov 21, 2020 11:09:57 P.M. net.creeperhost.creeperlauncher.CreeperLogger info
INFO: No PID args
Nov 21, 2020 11:09:58 P.M. net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Starting Electron: /home/pi/FTBA/bin/ftb-app --ws 17286:52e340c3-539f-4ab3-afe8-7e556aeea20e --pid 6798
Nov 21, 2020 11:09:58 P.M. net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Server started successfully - 202007161516-479dedc615-release

**Expected behaviour**

The launcher displays the Electron Renderer.

**Screenshots**

**Additional context**

**Comment by Jake-E** [comment]
There's not enough information here to go off.. can you still reproduce? There should be an ftbapp.log which may help.
