### ISSUE TITLE
FTB Lib and Quest crashing the game

### ISSUE THREAD

**Issue by matis2303** [FTBTeam/FTB-App#350]
![image](https://user-images.githubusercontent.com/45946266/100326102-d3023000-2fc9-11eb-9cb2-e7fff1807d91.png)
![image](https://user-images.githubusercontent.com/45946266/100326138-e01f1f00-2fc9-11eb-9eea-cc17b243bb73.png)

When i create a save or just load a save game crashes

**Comment by Quetzi** [comment]
This is not App related, please post this issue to the FTB Quests issue tracker https://github.com/FTBTeam/FTB-Quests
