### ISSUE TITLE
[Feature request] Auto close Overwolf

### ISSUE THREAD

**Issue by faminecode** [FTBTeam/FTB-App#351]
**Is your feature request related to a problem? Please describe.**
No desire to keep Overwolf running outside of the context of associated apps.

**Describe the solution you'd like**
Similar to the Overwolf+CurseForge app, add an option to automatically close Overwolf when the FTB App is closed

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Jake-E** [comment]
We (finally) have this available to us via the Overwolf APIs, we'll add an option in the next release.

**Comment by Gaz492** [comment]
This feature is now available
