### ISSUE TITLE
FTB, Game wont launch

### ISSUE THREAD

**Issue by CantoLanian** [FTBTeam/FTB-App#353]
**Operating System:**
OS: Mac OS

**Installer Version:**
Installer: N/A

**App Version:**
App: 202011261605-2be2c6a678-release

**UI Version:**
UI: e49e04d4

**Describe the bug**
When I click the Install button for a mod pack on the FTB app, it stays on "Creating Environment" For extremely long and never changes or shows up in the "My Modpacks" folder.

**To Reproduce**
Idk how to reproduce because it just does it for me and I've never actually played it without any problems

**Expected behavior**
For it to work and load the mod

**Screenshots**
![Screen Shot 2020-11-30 at 19 56 53 2](https://user-images.githubusercontent.com/75270619/100646514-c887c380-3346-11eb-9d63-cea985f6144b.png)

**Additional context**
I tried deleting the app and redownloading it multiple times, but it still never works

**Comment by OldestTrickInTheBook** [comment]
I am having the same problem as you, Doing things just doesn't work (opening packs or downloading packs)

**Comment by Gaz492** [comment]
If you are still having issues with launching modpacks please open a new issue and follow the bug reporting template for your operating system
