### ISSUE TITLE
Can't Download Launcher[Bug]

### ISSUE THREAD

**Issue by brashtopher** [FTBTeam/FTB-App#354]
**Operating System:**
OS:

**Installer Version:**
Installer:

**App Version:**
App: 

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**
I am unable to download the launcher, as every time I try (on both chrome and Microsoft Edge) it says "This site can’t provide a secure connectiondownload.overwolf.com sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR"

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by Bright-Shard** [comment]
Probably an issue on your end, make sure you have a good internet connection and there's not any blocking/filtering software on your network or computer. I can load download.overwolf.com in Firefox just fine.

**Comment by Gaz492** [comment]
If you are still having issues with download the app, make sure your operating system is up to date and also make sure your operating system clock is set correctly. If none of those work open a new issue and provide as much information as you can.
