### ISSUE TITLE
[Bug] MacOS - Launcher gets stuck at Creating Environment when installing modpack

### ISSUE THREAD

**Issue by blue-tack45** [FTBTeam/FTB-App#355]
**Operating System:**
OS: MacOS Catalina v10.15.7

**Installer Version:**
Installer:

**App Version:**
App: 202011261605-2be2c6a678-release

**UI Version:**
UI: e49e04d4

**Describe the bug**
Trying to install a new modpack it seems to get stuck at Creating Environment, 30 minutes later its not moved on and hasn't created any files. I've tried different modpacks and different versions of different modpacks. Ideally I'm trying to install SkyFactory 3. 
I'm also having an issue when I click login I get a white screen that goes nowhere. See screenshots. 
Anyone else having issues with FTB on Mac? Any help much appreciated! 

**Screenshots**
<img width="216" alt="Screenshot 2020-12-01 at 16 55 26" src="https://user-images.githubusercontent.com/75328186/100771522-6ab2b480-33f6-11eb-8de6-d94db7e97246.png">
<img width="548" alt="Screenshot 2020-12-01 at 16 55 33" src="https://user-images.githubusercontent.com/75328186/100771525-6b4b4b00-33f6-11eb-9e89-a73126ae4d66.png">

**Update**
I've tried to get it to generate a log following the steps on the website, but I never get the confirmation message. So I've attached my ftbapp.log 

[ftbapp.log](https://github.com/FTBTeam/FTB-App/files/5624206/ftbapp.log)

**Comment by Sorcuring** [comment]
Same Problem here with macOS Mojave 10.14.6 and 

java --version
java 14 2020-03-17
Java(TM) SE Runtime Environment (build 14+36-1461)
Java HotSpot(TM) 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

**Comment by Pautrik** [comment]
I'm getting the same error but on Linux (running Manjaro xfce with OpenJDK 1.8), worked fine a week ago. The instance for the modpack I'm trying to download when it gets stuck on 'Creating environment' only contains `art.png` and `instance.json`.

**Comment by demosthien** [comment]
Confirm, I am also having issues with installing Modpacks via the new FTB app on an iMac.

Attempting to install FTB Interactions.

iMac: Late 2012 (3.2Ghz i5)
macOS Version: 10.14.6

Jave Cersion 8 Update 271

FTB App
UI Version: e49e04d4
App Version: 202011261605-2be2c6a678-release

Installing FTB Interactions (any version)
Message states: "Creating environment..."
Creates a folder: "ec41e4eb-f7d7-4f77-8b87-e9bc0e9c37a4" this seems to be different each time.
Containing two files: "art.png" and "instance.json"
On occasion, but not everytime, an additional file is created called: "modpack.json"

**Comment by AndreGtz** [comment]
I managed to make it work by uninstalling ftb-app and installing the previous version (ftba-202007161516_479dedc615_release-2-any). The first time you launch it you can install the modpacks you want and it worked for me. But after the first launch the ftb-app updated automatically and couldn't get any more modpacks. So be sure to install every modpack you plan playing on first launch.

This also works on linux.

**Comment by demosthien** [comment]
> I managed to make it work by uninstalling ftb-app and installing the previous version (ftba-202007161516_479dedc615_release-2-any). The first time you launch it you can install the modpacks you want and it worked for me. But after the first launch the ftb-app updated automatically and couldn't get any more modpacks. So be sure to install every modpack you plan playing on first launch.
> 
> This also works on linux.

Where would we likely find a previous version of the FTB app though? I can't seem to find a historical version download page anywhere.

**Comment by AndreGtz** [comment]
@demosthien https://apps.modpacks.ch/FTBApp/release/202007161516-479dedc615-release/

**Comment by Gaz492** [comment]
If anyone is still having issues with this would you be able to open a new issue?
