### ISSUE TITLE
[Bug] FTB Revelation, Game won´t start

### ISSUE THREAD

**Issue by SickRazor** [FTBTeam/FTB-App#356]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer:

**App Version:**
App: 202012011513-e41fa8b327-debugging

**UI Version:**
UI: 9e6200dd

**Log Files:**
Put links to your logs here
https://pste.ch/zehuzepomu

**Describe the bug**
When i have installed the FTB Revelation and i click on Play when the Minecraft Launcher is open, an error shows up (Screenshot will be below).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to FTB-App
2. Click on FTB Revelation
3. Click on the Play-Button '....'
4. Minecraft-Launcher get up
5. Click on PLay
6. See error

**Expected behaviour**
i don´t know, but maybe it´s related to that i bought it yesterday

**Screenshots**
![Error](https://user-images.githubusercontent.com/75336861/100907468-a7e87680-34ca-11eb-9c9a-59ca6181d24c.PNG)

**Additional context**
When i tried to start FTB Revelation over MultiMc, i can´t sign in with the microsoft acc. I don´t know if that will help that much.
I play Minecraft on Java.

**Comment by sebastiansam55** [comment]
I have this error too, my FTB log has the following:
```
INFO: Starting Mojang launcher
Dec 03, 2020 6:12:24 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.pack.LocalInstance.play(LocalInstance.java:545)
Unable to initialize MineTogether Connect!
```

I see that there is a toggle switch in the FTB app settings to disable minetogether but it is greyed out

**Comment by Quetzi** [comment]
@SickRazor you should post this issue on the Revelation issue tracker as it is not App related: https://github.com/FTBTeam/FTB-Revelation-2

@sebastiansam55 Your error is unlikely to be the same, the log snippet you posted is unrelated to a crash, if you still have issue open a new issue on the correct issue tracker (whichever pack it is you are trying to play)
