### ISSUE TITLE
FTB won't start any mods in minecraft, comes up with a blank minecraft launcher window, macOS

### ISSUE THREAD

**Issue by xmusicxmakerx** [FTBTeam/FTB-App#358]
I've completely deleted and reinstalled FTB app and Minecraft App. Still just comes up with blank launcher. Was working fine yesterday, zero things have changed since then. Also I'm pretty computer illiterate so asking for code files and stuff is probably over my head :(

**Comment by keapton** [comment]
Hi, so this happened to me after updating to big sur, idk what was the issue i just installed a fresh version of macos (only took like 1 hour) and everything started working again.

**Comment by xmusicxmakerx** [comment]
@keapton Alright, I’ll try that. What’s weird is I updated to Big Sur like a week ago and it worked fine until yesterday so I didn’t connect those dots, if it works I’ll let you know, thanks bud.

**Comment by Gaz492** [comment]
If you are still having issues with the app please open a new issue and follow the bug reporting template for your operating system.
