### ISSUE TITLE
Log In Error

### ISSUE THREAD

**Issue by themoocow12** [FTBTeam/FTB-App#359]
Hello. I just opened the FTB app. And there was something new, a door with a arrow pointed to the left. I tried tp login, but know it's just infinitely loading. I tried to delete the app, but it's still there. Can someone help me with this? Thanks. 
![Screen Shot 2020-12-03 at 3 14 47 PM](https://user-images.githubusercontent.com/75454054/101094929-657e7280-357a-11eb-904a-d4e9a68c8519.png)

**Comment by jbaig77** [comment]
I also get the same error, did you ever figure it out?

**Comment by Gaz492** [comment]
If you are still having an issue logging in could you open a new issue and follow the bug reporting template for your operating system?
