### ISSUE TITLE
Server file download problems

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-App#36]
It is very weird that it downloads an exe instead of a zip for the server files. It should totally be a zip that you just extract to wherever you want, having an exe is just weird and I don't understand it.

The exe was blocked by Windows Defender
![](https://cdn.discordapp.com/attachments/613467918176616458/695567575626547250/unknown.png)

It installs all the files to the folder the exe is in, instead of letting you choose where it goes. I know you can move the exe, but that's still weird.
![](https://cdn.discordapp.com/attachments/613467918176616458/695568096961888316/unknown.png)

**Comment by Gaz492** [comment]
Not an issue as the server download links downloads a download manager of sorts where you run the exe and it will download the files needed to run the server. 
This was done to remove the need to manage 2 different releases of a version as the server downloader will only download the files needed to run a server.

If someone else wants to clarify this better feel free.

**Comment by aaronhowser1** [comment]
Still has the problem of it showing as a virus, and it installing to the Downloads folder.

**Comment by CH-Paul-T** [comment]
Does not show as a virus (read your screenshot) and you chose to install it to the downloads folder as the first thing it asks is if you want to install it into that path with a y/n

**Comment by aaronhowser1** [comment]
It doesn't give you a choice of where to actually install it, nor does it tell you to move the exe to the folder you want to install it in though.

And the screenshot says running the program might put your computer at risk, which makes it look dangerous.

**Comment by CH-Paul-T** [comment]
I have added this line for future versions of the server installer;

> If you are unhappy with this installation location, please move this executable to your desired location or use the arguments available by running this with --help to customise your install.

The SmartScreen (a windows feature) isn't something we can fix without cost, and it'll be fixed when it is fixed for the main launcher.
