### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DamienTC** [FTBTeam/FTB-App#363]
**Operating System:**
OS: Windows

**Installer Version:**
Installer: 

**App Version:**
App: 

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**
![Screenshot 2020-12-06 032031](https://user-images.githubusercontent.com/75565734/101277621-f7e96680-3772-11eb-9e98-f62de22dc5b5.png)

**Additional context**

**Comment by Bright-Shard** [comment]
1. You're supposed to fill out all parts of the form. What OS are you on? Do you have the latest app version?
2. Make sure you are actually connected to the right network. You probably are but just double check.
3. Make sure there's no filtering/blocking software on your network/computer. If there is you'll need to whitelist the app.

**Comment by Quetzi** [comment]
This looks like an Overwolf issue, they lost connectivity to something required for new installs for an hour or two last week. This should now be resolved.
