### ISSUE TITLE
Revelation client version is only up to 3.3.0 on the overwolf client

### ISSUE THREAD

**Issue by EpicDepart** [FTBTeam/FTB-App#365]
It does not have any option anywhere to update to 3.4.0. I tried manually updating the files by installing the server files and replacing the client's mods with the server's, it somewhat worked, however this new version did not detect Xtones, even though it was in the folder, which prevented me from connecting to a friend's revelation 3.4.0 server.

**Comment by Quetzi** [comment]
This issue tracker is for the FTB App, where the 3.4.0 update has always been available. That said, following the recovery of our CurseForge account Revelation has now been updated on CurseForge to 3.4.0
