### ISSUE TITLE
Minecraft Crashes on launch

### ISSUE THREAD

**Issue by SingleThreadedEzkail** [FTBTeam/FTB-App#366]
**Operating System:**
OS: MacOS Catalina 10.15.5 (19F101)

**Installer Version:**
Installer: FTBA_macos_202012101153-ce008c54b4-release

**App Version:**
App: 202012101153-ce008c54b4-release

**UI Version:**
UI: e49e04d4

**Log Files:**
Put links to your logs here

[FTBApp launcher crash log.txt](https://github.com/FTBTeam/FTB-App/files/5675840/FTBApp.launcher.crash.log.txt)

**Describe the bug**
At launch, the game doesn't properly launch, instead it trows a crash report.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a modpack installed
2. Attempt to launch the modpack
3. See the error

**Expected behaviour**
The game won't launch.

**Screenshots**
![Captura de pantalla 2020-12-10 a las 19 00 00](https://user-images.githubusercontent.com/75813138/101835028-eceb5900-3b19-11eb-9e3d-39a581f1a5a8.png)

**Comment by Quetzi** [comment]
Closing as this is currently being tracked at #160
