### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by brashtopher** [FTBTeam/FTB-App#369]
**Operating System:**
OS: Windows

**Installer Version:**
Installer:

**App Version:**
App: 

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**
When I try to launch any modpack from the FTB launcher, it says "Error: Unable to create Mojang launcher profile. Please ensure you do not have any security software blocking access to the FTB App data directories." How can I allow FTB to get past my computer's security?

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by Gaz492** [comment]
Would you be able to provide the logs that are requested by the template?
