### ISSUE TITLE
[Bug] Changing instance location to nothing deletes files

### ISSUE THREAD

**Issue by Oddthorn** [FTBTeam/FTB-App#370]
**Operating System:**
OS: windows 10

**Installer Version:**
Installer:

**App Version:**
App: 202012021741-eaf41def11-debugging

**UI Version:**
UI: 9e6200dd

**Log Files:**
I did a restore folder to recover my saves so this got overwritten

**Describe the bug**
If you set the instance location to nothing it will attempt to move your files to no where effectively deleting them.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to settings
2. Click instance location and delete everything
3. Click anywhere else
4. Dialog pops up asking if you want to move.
5. Click yes
6. cry as you watch weeks of progress disappear.

**Expected behaviour**
If you have nothing in the field it should probably spit out an error, but I understand you never expected someone to be dumb enough to do this.

**Screenshots**
![bad location](https://user-images.githubusercontent.com/76077080/102285544-20ecc280-3efc-11eb-848b-4d712f752fc4.PNG)

**Additional context**
So I'm not actually sure how the field was cleared...I would normally never do something like that, I was actually trying to find a way to make it so it stopped trying to launch the modpacks within the app I liked the old way, and I failed to follow my number 1 rule don't click something if you are not sure what its doing or why.

**Comment by Gaz492** [comment]
Would you be able to test if this is still an issue for us and make sure you are on the latest version of the app?
As of right now, the current version of the app that is displayed on the Library page of the Overwolf app is Ver 1.21.13.1631

**Comment by gigabit101** [comment]
This has been fixed in newer versions of the app, Currently the app will not allow the location string to be blank
