### ISSUE TITLE
FTBApp stalled at FTB logo screen

### ISSUE THREAD

**Issue by pooves** [FTBTeam/FTB-App#372]
**Operating System:**
OS:linux mint 20.0

**Installer Version:**
Installer:FTBA_unix_202012101153-ce008c54b4-release.sh

**App Version:**
App: 

**UI Version:**
UI: 

**Log Files:**
https://pastebin.com/yj7dQf9P
https://pastebin.com/AWunK2bH

will provide others / post what you need to see

**Describe the bug**
FTBApp stalls at the opening screen

**To Reproduce**
install with provided .sh file, no errors, launch FTBApp, and wait till doomsday.

**Expected behaviour**
expected to proceed to the "choose modpack screen"

**Screenshots**

**Additional context**

vanilla minecraft requires jre11, old FTB launcher requires jre 8, new app won't work with either

**Comment by maxybaer123** [comment]
This issue is just called [bug] please rename

**Comment by yaeyewon112** [comment]
I can prove this in Windows.

**Comment by MichaelHillcox** [comment]
This version is super old now, please update and confirm if this is still an issue
