### ISSUE TITLE
[Bug] macOS typo makes modpacks not launch

### ISSUE THREAD

**Issue by Zettt** [FTBTeam/FTB-App#373]
**Operating System:**
OS: macOS Big Sur

**Installer Version:**
Installer: Version 0.1.0 (0.1.0.567)

**Describe the bug**
Mac modpack won't launch. 

The log has this line:

```
WARNING: /usr/bin/open /Users/me//Library/Application Support/.ftba/bin/Minecraft.app --args --workDir /Users/me//Library/Application Support/.ftba/bin
```

Please notice the **double slashes** after the username. This should be only one. I did not test whether this solves all launch issues for other modpacks too, because I don't know what the launcher does after running that command.

**Comment by Zettt** [comment]
Just tried running the command, the spaces need to be escaped. 

This command here does at least launch the Minecraft app for me:

```
/usr/bin/open /Users/me/Library/Application\ Support/.ftba/bin/Minecraft.app --args --workDir /Users/me/Library/Application\ Support/.ftba/bin
```

**Comment by jvdoorn** [comment]
Can confirm that I have the same issue. Indeed the spaces do not get properly escaped. Also running macOS Big Sur. Running `/usr/bin/open /Users/julian/Library/Application\ Support/.ftba/bin/Minecraft.app --args --workDir /Users/julian/Library/Application\ Support/.ftba/bin` properly launches the Minecraft Launcher and lets me play the mod pack.

**Comment by EmlJnke** [comment]
> Can confirm that I have the same issue. Indeed the spaces do not get properly escaped. Also running macOS Big Sur. Running `/usr/bin/open /Users/julian/Library/Application\ Support/.ftba/bin/Minecraft.app --args --workDir /Users/julian/Library/Application\ Support/.ftba/bin` properly launches the Minecraft Launcher and lets me play the mod pack.

Thanks man, directly launching the modpack from the app does (still) not work for me but this works perfectly fine!

**Comment by PeterTheMango** [comment]
@s104739 Open up a terminal and replace **julian** with the name of your system. 

This definitely fixed it for me!

**Comment by MichaelHillcox** [comment]
This'll be fixed as we no longer use the Minecraft Launcher to launch packs.
