### ISSUE TITLE
[Bug] Starting pack overrides settings page

### ISSUE THREAD

**Issue by the1ts** [FTBTeam/FTB-App#374]
OS: Windows 10

App: 202012191727-46b0d45df5-preview

UI: 2c223e0c

If you are starting a pack then click on settings page, you will be taken back to the pack starting page each time that page updates i.e. another mod examined.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to pack and start it
2. Click on settings
3. Be taken back to pack starting screen.

**Expected behaviour**
I would expect to be left at the settings or other screen during startup.

**Comment by MichaelHillcox** [comment]
Can you provide a video of this?

**Comment by the1ts** [comment]
Not played in months. But checked today, it no longer has this behaviour, closing out.
