### ISSUE TITLE
[Feature request] Lower quality images for gridview

### ISSUE THREAD

**Issue by profjb58** [FTBTeam/FTB-App#377]
**Is your feature request related to a problem? Please describe.**
Framerate lag when displaying too many images from within gridview on a 4k screen

**Describe the solution you'd like**
Lower quality images or a hard limit on the filesize of the gridview artwork. Additionally a system whereby if it only needs to render a few boxes it uses the full quality image but if loading excess of say 30+ it defaults to the lower quality one

**Additional context**
Gif recorded at 60fps shows the framerate lag
https://streamable.com/iz8mtu

**Comment by MichaelHillcox** [comment]
Can you reupload the video? This may have been resolved in dev
