### ISSUE TITLE
[Feature request] serverinstall_x_x return none zero

### ISSUE THREAD

**Issue by runih** [FTBTeam/FTB-App#379]
Is it possible to get serverinstall_x_x to exit with none zero if one chooses 'n' to install the modpack?

I like to use it for: https://github.com/runih/ftb-server-update ;)

**Comment by jikuja** [comment]
Also different failure codes for

- forge failures
- download failures
- data failures
- anything else

**Comment by Gaz492** [comment]
A rewrite of the sever install is coming, I will forward this to the developers of the installer to see if these features can be added.

**Comment by Gaz492** [comment]
Would you also be able to create server installer issues at the following repo?
https://github.com/CreeperHost/modpacksch-serverdownloader/issues
It makes it easier to track issues related to the server installer.

**Comment by Jake-E** [comment]
I imagine as the new installer is written in go that it fails with non-zero exit codes.
Feel free to correct me with a new issue on the server installer issue tracker linked above.
