### ISSUE TITLE
FTB Omnia Install Issue

### ISSUE THREAD

**Issue by Luke094** [FTBTeam/FTB-App#38]
When I try to download FTB Omnia I receive this message:
"Error installing FTB Omnia - Download file is not the same size. - Retry?"

I have removed it and tried to download again and the same happened. I also tried with another modpack (SF3) to see if the issue would happen again and it did.

![Capture](https://user-images.githubusercontent.com/63099503/78348484-035c1080-759a-11ea-8fa1-f7c59f768a45.PNG)

**Comment by Jake-E** [comment]
See #37
