### ISSUE TITLE
[Bug] app reopens sort of idk it starge have a peek of the vid

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-App#380]
**Operating System:**
OS: Windows 10 2004 build: 19041.685

**Installer Version:**
Installer: NO there is no installer who needs this now

**App Version:**
App: 202012191727-46b0d45df5-preview

**UI Version:**
UI: 2c223e0c

**Platform:**
Platform: Overwolf

**Log Files:**
Put links to your logs here
https://pste.ch/oyogimarub

**Describe the bug**
Reopening of the App when click more on a pack server
Just See VID

**To Reproduce**
Steps to reproduce the behaviour:
https://ss1.manmaed.net/1609439881.mp4

**Expected behaviour**
To Move back to the overview tab

**Comment by Gaz492** [comment]
Does this issue still happen on the newest version of the app?

**Comment by manmaed** [comment]
as of: 202101031227-c13fc1b2e5-prototyping it still dose it

**Comment by MichaelHillcox** [comment]
Still happening?

**Comment by manmaed** [comment]
can reporduce as cant find any servers on MT so ¯\_(ツ)_/¯
