### ISSUE TITLE
[Bug] Launcher Crashing

### ISSUE THREAD

**Issue by datcat31** [FTBTeam/FTB-App#381]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer:

**App Version:**
App: 202101031227-c13fc1b2e5-prototyping

**UI Version:**
UI: 85b019e3

**Log Files:**
https://pste.ch/orafojupuv
https://pastebin.com/CfWJkJuh

**Describe the bug**
My Minecraft launcher gives me an error message when I launch 'FTB Presents Stoneblock 2' (Ver. 1.21.1)

**Expected behavior**
I was expecting it to launch Stoneblock 2

**Screenshots**
![image](https://user-images.githubusercontent.com/62666721/103584480-41be8d00-4e96-11eb-90be-d3de0a6e691c.png)

**Comment by Gaz492** [comment]
Are you still having issues with installing this modpack?

**Comment by datcat31** [comment]
yes im am still having issues

**Comment by datcat31** [comment]
i fixed it

**Comment by datcat31** [comment]
There was multiple Stoneblock 2 Installations
