### ISSUE TITLE
[Bug] FTB App says modpack updates are complete and modpack is updated but is not due to failed download

### ISSUE THREAD

**Issue by baronthered80** [FTBTeam/FTB-App#382]
**Operating System:**
OS:Windows 10

**Installer Version:**
Installer: no idea what or where this is.

**App Version:**
App: 202007161516-479dedc615-release  (why can this info not be copy pasted?)

**UI Version:**
UI: 39f37b8d (why no copy paste again)

**Log Files:**
Put links to your logs here  Logs https://pste.ch/fenoxijise
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**
The FTB App fails a modpack update (download of a new pack as well) and the modpack is showing fully updated except it failed. No way to revert pack or to be able to retry the download short of deleting the pack and starting from new. The retry button in the app shows no info when I try using it. Halfway afraid to update the app because the last time I did update it deleted my packs and worlds.

**To Reproduce**
Steps to reproduce the behaviour:
Have a modpack update fail. Retry button never appears to work either. 

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by MichaelHillcox** [comment]
We have begun shipping a new version of the app with a completely rewritten install and launch system. If your issue is still happening, please create a new issue once you have tested against the new version. Any version after (ui: bdf8bdbaca, subprocess: 202112101445-bdf8bdbaca-release.
