### ISSUE TITLE
[Bug] FTB App not launching

### ISSUE THREAD

**Issue by lovglomas** [FTBTeam/FTB-App#389]
**Operating System:**
OS:Ubuntu 20.04.1

**Installer Version:**
Installer: Direwolf20 1.16

**App Version:**
App: 202012101145-0e92584e6c-preview

**UI Version:**
UI: e49e04d4

**Describe the bug**
the application downloads the packs but does nothing when launching a pack

**To Reproduce**
1.Install mod pack
2. Click Play to launch

**Expected behaviour**
Launch a pack

**Screenshots**

https://user-images.githubusercontent.com/34251731/105568885-b65d4c80-5d1b-11eb-883c-5ec310748781.mp4

**Comment by Gaz492** [comment]
Could you upload the logs as requested by the bug report template?
Without the logs we are unable to track down the issue.

**Comment by randomusernameee** [comment]
I have the exact same issue on Windows 10. Photo of the logs:
![20210210_190043](https://user-images.githubusercontent.com/78871664/107551456-94484300-6bd2-11eb-874a-6fe57d73c271.jpg)

I painted over my Windows account name for personal reasons. Let me know if you need additional info.

**Comment by randomusernameee** [comment]
Also, I am unable to start the normal minecraft launcher.

I've had this problem yesterday and the day before as well (I installed the launcher and the Revelation modpack 3 days ago). I just restarted my PC and it fixed itself, but today I've tried that 20 times and it won't fix itself.

**Comment by randomusernameee** [comment]
I added the issue as a seperate post with more info.

**Comment by MichaelHillcox** [comment]
We have begun shipping a new version of the app with a completely rewritten install and launch system. If your issue is still happening, please create a new issue once you have tested against the new version. Any version after (ui: bdf8bdbaca, subprocess: 202112101445-bdf8bdbaca-release.
