### ISSUE TITLE
[Bug (Windows)] Instances randomly not loading.

### ISSUE THREAD

**Issue by MaverickMartyn** [FTBTeam/FTB-App#392]
**Operating System:**
OS: Windows 10

**App Version:**
App: 202101031227-c13fc1b2e5-prototyping

**UI Version:**
UI: 85b019e3

**Log Files:**
https://pste.ch/sedahizuna

** Debug Code: **
Please run the following tool and provide the code given.
https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe
**FTB-DBGRUXUJIYIWI**

**Describe the bug**
I have 3 instances of FTB Revelation: one normal on the latest version (3.4.0) and two customized packs on version 3.2.0.
After moving my instances folder to a folder on another drive, the launcher will seemingly fail to load all instances.
There seems to be no logic as to which ones or how many, but it never seems to load all 3.
According to the log file all 3 instances load just fine. They just don't show up under My Modpacks.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have 3 instances of a modpack.
2. Launch FTBApp.
3. Go to My Modpacks.

**Expected behaviour**
See all 3 instances.

**Screenshots**
I don't see much reason to screencap anything.

**Additional context**
I doubt it has much to do with moving my instances folder, as I seem to recall having seen the issue before doing this.

**Comment by MichaelHillcox** [comment]
We have begun shipping a new version of the app with a completely rewritten install and launch system. If your issue is still happening, please create a new issue once you have tested against the new version. Any version after (ui: bdf8bdbaca, subprocess: 202112101445-bdf8bdbaca-release.
