### ISSUE TITLE
[Bug (Windows)] FTB instance won't launch.

### ISSUE THREAD

**Issue by randomusernameee** [FTBTeam/FTB-App#394]
**Operating System:**
OS:Windows 10

**App Version:**
App: 202101031227-c13fc1b2e5-prototyping

**UI Version:**
UI: 85b019e3

**Log Files:**
![20210210_190043](https://user-images.githubusercontent.com/78871664/107555437-76311180-6bd7-11eb-82fa-398e1ece9e43.jpg)
Photo of logs (when i try to start the instance) for personal reasons. (Windows account name painted over).

** Debug Code: **
FTB-DBGMISEPELOWU

**Describe the bug**
When I open the FTB App launcher and click play the Minecraft launcher won't start.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch FTB App
2. Choose an instance to play (Revelation in this case)
3. Click "Play"
4. Nothing happens

**Expected behaviour**
The Minecraft launcher should open when I click "Play".

**Screenshots**

**Additional context**
I downloaded both the FTB App and Revelation modpack 3 days ago. I had this issue yesterday and the day before, but I solved it by restarting my PC and launching the modpack again. Today however, I tried that 20 times with no success. I am also unable to start the normal Minecraft launcher.

**Comment by randomusernameee** [comment]
Reinstalling FTB App and Minecraft solved the problem for now.

**Comment by randomusernameee** [comment]
Happened again, reinstalling just Minecraft also works.

**Comment by Jake-E** [comment]
If this is still happening for you... can you zip up your bin folder in .ftba when it isn't working... and also when it is?
If you can send that to help(at)ftb.team it might help give some further insight.

**Comment by randomusernameee** [comment]
I zipped it while it worked and it still works. I'll let you know if
zipping it while it doesnt work fixes it (it works currently so I have to
wait until it doesnt).

**Comment by randomusernameee** [comment]
I haven't had this problem since.
