### ISSUE TITLE
[Bug (Windows)] Mod pack will not launch

### ISSUE THREAD

**Issue by Asashins** [FTBTeam/FTB-App#395]
**Operating System:**
OS: Windows 10

**App Version:**
App: 3.4.0

**UI Version:**
UI: 

**Log Files:**
https://pste.ch/kiguqipixu
** Debug Code: **
Please run the following tool and provide the code given.
https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe

**Describe the bug**
when i click the mod pack to play nothing happens

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'start
2. Click on 'FTB Revolations
3. Nothing happens

**Expected behaviour**
I click play and it brings up the minecraft launcher
**Screenshots**

**Additional context**

**Comment by Gaz492** [comment]
Hi,

Would you be able to provide the debug code as requested by the issue template?

**Comment by MichaelHillcox** [comment]
Closed due to no response. Also looks like it's some failure on the api.
