### ISSUE TITLE
[Bug (Windows)] Instances don't always load into the App correctly

### ISSUE THREAD

**Issue by redgoblin88** [FTBTeam/FTB-App#396]
**Operating System:**
OS: windows 10

**App Version:**
App: 202101031227-c13fc1b2e5-prototyping

**UI Version:**
UI: 85b019e3

**Log Files:**
https://pste.ch/izediseloq

** Debug Code: **
FTB-DBGOHONORONOR

**Describe the bug**
im not sure how it happens, but yesterday i was playing the direwolf 1.12 modpack, today when i came on my pc i decided i wanted to play a bit more, so i opened the launcher but found the pack was... missing? so i decided to look at the launcher directory as i know each pack is saved as a unique string (of sorts). i found four modpacks, but only three were being shown. so i dedcided to try closing and re-opening the launcher and although the direwolf20 modpack did come back, some bizzare reason academy, which was shown previously, was now hidden
so i decided to restart the launcher yet AGAIN and now all four came up.
out of curiosity i decided to restart the launcher for a fourth time in which, lo and behold, this time diepack was still visible but academy was hidden. a fith time? direpack hidden and academy back

**To Reproduce**
im not sure, it seems to randomly occur when i open/close the launcher and swaps modpacks. hoever this does not seem to happen with university nor sky oddysey

**Expected behaviour**
i expect to see all  my downloaded modpacks to be visible upon launching, not some of them to be "hidden" from view

**Screenshots**
contains:
image of direpack, university sky oddysey
image of sky oddysey, academy and university
image of direpack, sky oddysey, uni and academy
image of the four instances in the file explorer

**Comment by gigabit101** [comment]
We pushed a recent fix that should help with invalid instances, If the issue continues please feel free to re-open this issue
