### ISSUE TITLE
[Bug] Install modal closing on search page

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-App#397]
**Operating System:**
OS: Mac OS High Sierra 10.13.6

**App Version:**
App: 202101041428-54016a89dc-release

**UI Version:**
UI: 6f769022

**Log Files:**
https://pste.ch/betoxuwuda

** Debug Code: **
FTB-DBGFARIBOGUKA

**Describe the bug**
When installing an new instance of a mod pack versoin window closes before you can choose what version to install

**To Reproduce**
Steps to reproduce the behaviour:
See Video

**Expected behaviour**
For the window not to close

**Screenshots**
See Video

**Additional context**
https://ss1.manmaed.net/1614025095.mp4

**Comment by Jake-E** [comment]
This is only happening on packs listed in the search section. Presumably, something is causing it to re-render and close the modal.

**Comment by manmaed** [comment]
#Fixed? Will reopen if found
