### ISSUE TITLE
Permissions problem when installed in Program Files

### ISSUE THREAD

**Issue by fuhrriel** [FTBTeam/FTB-App#4]
#### Description:
Installed FTB-App in Program Files, when downloading any pack it errors out due to lack of permissions
![image](https://user-images.githubusercontent.com/49496299/78283768-96576500-751e-11ea-8798-cc71776bf27c.png)

#### Current workarounds: 
Run FTB-App as administrator
Reinstall FTB-App in sane location

#### Proposed fixes:
Warn during instalation that installing there could cause issues
Allow to install modpacks in different customizable directory than FTB-App

**Comment by Cloudhunter** [comment]
Can I confirm what OS you are using please? I did actually foresee this issue and put code in to account for this, but perhaps despite testing said code it decided not to work anyway!

**Comment by MichaelHillcox** [comment]
This should be fixed now
