### ISSUE TITLE
Linux application does not install all files

### ISSUE THREAD

**Issue by Mudartastisch** [FTBTeam/FTB-App#40]
Suspected Error:
Linux App is not downloading the Minecraft Launcher correctly.

Full Report:
As it seems, the Linux App fails to download all files.
After a fresh install under Ubuntu 18.04, the App had problems downloading the pack, after a restart it seemed to be fine (actually it did not download all files). It did not start, so checking the error log:

java.io.FileNotFoundException: /home/mudar/FTBA/bin/launcher_profiles.json (No such file or directory)

After some messing around I figured out that this file is created by the Minecraft launcher, copying a file from a Minecraft install did not work properly. So I figured I'd try to paste in the install of the Minecraft launcher. This worked to the point that I could log in, but it failed to start as it did not have all the files. Exiting and redownloading the pack worked to the point that I could see the forge install in the launcher.

temporary fix:
Download and install a Minecraft Launcher from the Mojang website and copy the folder into the FTBApp/bin/ directory.

**Comment by gamer4life1** [comment]
Same problem

**Comment by Jake-E** [comment]
Does this still happen on a fresh installation of the latest version?

**Comment by tylergale** [comment]
I just grabbed the latest copy of the FTBApp and had the same issue (it created the environment, then "downloaded" the vanilla launcher which did nothing).

**Comment by Alge** [comment]
@tylergale which launcher file(s) did you use?

**Comment by Jake-E** [comment]
I know some stuff in the backend got changed to try and alleviate this problem.. so I'm unsure if this is still broken.
Can anyone verify?

**Comment by ken-noland** [comment]
Yes, this still happens

**Comment by Gaz492** [comment]
As you are still having the issue can you provide the following information?

**Operating System:**
OS:

**Installer Version:**
Installer:

**App Version:**
App: 

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by RaphaelJenni** [comment]
**Operating System:**
OS: Linux Ubuntu 20.04

**Installer Version:**
Installer: FTBA_unix_202011261605-2be2c6a678-release.sh

**App Version:**
App: `202011261605-2be2c6a678-release`

**UI Version:**
UI: `e49e04d4`

**Log Files:**
Doesn't work as well. When clicking on the "Upload App Logs"-Button nothing happens.

**Describe the bug**
The install of modpacks does not work.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to FTB Revelations
2. Click on Versions
3. Click on the Install button next to version 3.4.0
4. Downloads starts and an error appears
![image](https://user-images.githubusercontent.com/14369284/100887614-71ecc780-34b5-11eb-8561-a42e52a7b8c5.png)
5. Installation continues and finishes
6. Klick the "Play" button
7. Nothing happens

Additional context
Java Versions 8,11,15 installed

**Comment by CobaltSpace** [comment]
Temporary workaround: run `minecraft-launcher -w ~/.ftba/bin` and sign in.  Also run `ln -s /opt/minecraft-launcher ~/.ftba/bin`

**Comment by Gaz492** [comment]
Installer issues on Linux should now be resolved if you continue to have issues with the installer on Linux do let us know.
