### ISSUE TITLE
[Bug (Windows)] api.modpacks.ch detected as Trojan

### ISSUE THREAD

**Issue by ymmac01913** [FTBTeam/FTB-App#401]
**Operating System:**
OS: Windows 10 Pro V 2004

**App Version:**
App: 202101031227-c13fc1b2e5-prototyping

**UI Version:**
UI: 85b019e3

**Log Files:**
https://pste.ch/zosezokoxu

** Debug Code: **
FTB-DBGTEVOSUQIRA

**Describe the bug**
api.modpacks.ch is detected as a Trojan by Malwarebytes, preventing modpack browser from displaying.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch FTB APP
2. Malwarebytes popup appears
3. Change to Browse and no packs appear

Can Repeat error by leaving page and 

**Expected behaviour**
No warning from Malwarebytes and modpacks appear in list

**Screenshots**
![image](https://user-images.githubusercontent.com/80195739/110235151-7bf3eb80-7f26-11eb-8223-bd7d59626711.png)

![image](https://user-images.githubusercontent.com/80195739/110235187-95953300-7f26-11eb-8165-3b09742beab6.png)

**Additional context**
Malwarebytes has been updated to the latest version. Logfile:

Malwarebytes
www.malwarebytes.com

-Log Details-
Protection Event Date: 07/03/2021
Protection Event Time: 09:20
Log File: 52151aaa-7f26-11eb-8a3a-4ccc6ab5c561.json

-Software Information-
Version: 4.3.0.98
Components Version: 1.0.1173
Update Package Version: 1.0.37853
Licence: Premium

-System Information-
OS: Windows 10 (Build 19041.804)
CPU: x64
File System: NTFS
User: System

-Blocked Website Details-
Malicious Website: 1
, C:\Program Files (x86)\Overwolf\0.166.1.16\OverwolfBrowser.exe, Blocked, -1, -1, 0.0.0, , 

-Website Data-
Category: Trojan
Domain: api.modpacks.ch
IP Address: 104.22.6.108
Port: 443
Type: Outbound
File: C:\Program Files (x86)\Overwolf\0.166.1.16\OverwolfBrowser.exe

(end)

**Comment by MichaelHillcox** [comment]
Can confirm, is not a Trojan, allow the domain past your anti-virus
