### ISSUE TITLE
[Bug (Windows)] Installer not starting

### ISSUE THREAD

**Issue by tommaier123** [FTBTeam/FTB-App#406]
**Operating System:**
OS: Windows 10

**App Version:**
App: latest

**UI Version:**
UI: 

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

** Debug Code: **
Won't run

**Describe the bug**
I am trying to install the ftb app using the lates version of the installer downloaded from feed-the-beast.com
When I run it I get the missing certificates warning, click "run anyways" but nothing happens. The debug tool also won't run. 
I have already tried uninstalling and reinstalling the .net framework and Java and I have no Antivirus (except the default windows defender) I have also tried compatibility mode and running the installer as admin.

**Comment by MichaelHillcox** [comment]
Can you confirm if you are still having this issue? Can you also confirm if you have any kind of anti-virus?

**Comment by tommaier123** [comment]
I can confirm the bug is still present. I even reinstalled windows to be sure, so no antivirus except windows defender.

**Comment by MichaelHillcox** [comment]
Could you possibly take a short screen capture and show your issue?

**Comment by tommaier123** [comment]
Here is the screen capture:
https://youtu.be/iD_38S7KDzA

**Comment by MichaelHillcox** [comment]
Oh... odd... I'll ping some people and see what's going on

**Comment by gigabit101** [comment]
Is this still happing with the latest release?

**Comment by tommaier123** [comment]
Yes, I just redownloaded and tried it and its still happening

**Comment by MichaelHillcox** [comment]
Your OS looks odd... Are you running anything special? Anything non-standard?

**Comment by tommaier123** [comment]
I am running a custom dark theme and modified file explorer but thats about it.
Just in case I tried switching back to the defualt theme but the issue still happened.
When I first reported the bug I was on a pretty much clean install of win10.
I had only added the custom stuff by the time I recorded the video.

**Comment by gigabit101** [comment]
Unfortunately, we do not have any control over the Overwolf installer, This issue will need to be reported to Overwolf

**Comment by MichaelHillcox** [comment]
We have begun shipping a new version of the app with a completely rewritten install and launch system. If your issue is still happening, please create a new issue once you have tested against the new version. Any version after (ui: bdf8bdbaca, subprocess: 202112101445-bdf8bdbaca-release.
