### ISSUE TITLE
Cant Download any Modpacks

### ISSUE THREAD

**Issue by Flameboy321** [FTBTeam/FTB-App#41]
Every time it tries to download a pack it takes so long I cant download any pack. Im on Mac OS X if thats helps.

**Comment by Flameboy321** [comment]
I took a picture of what is shows it has said this fro the past 2 hours
![Screen Shot 2020-04-03 at 10 11 19 AM](https://user-images.githubusercontent.com/63112522/78376210-9b0a3080-7593-11ea-994e-4d97316a5ca9.png)

**Comment by Rushmead** [comment]
Can you upload the log found in the installation directory? Both the launcher.log and the error.log Please.

**Comment by Flameboy321** [comment]
How do you do that?

**Comment by Rushmead** [comment]
You'll find them in the installation folder the launcher which you would have picked at install time. If you just set it as default it would be in %appdata%/FTBA. You can upload them to https://pste.ch or directly to this issue.

**Comment by Flameboy321** [comment]
I'm not on Windows I dont have %appdata%

**Comment by Rushmead** [comment]
Apologies I did not read the issue properly! Did you drag the icon into your Applications folder or are you double-clicking it inside the .dmg file?

**Comment by Flameboy321** [comment]
It is inside of my applications folder and there is were im clicking to open it.

**Comment by Jake-E** [comment]
Right click the app file in the Application folder, click open package contents. Browse through there, you should see a 'launcher.log' and/or a 'error.log' in there.

**Comment by Flameboy321** [comment]
I found both of them.
[error.log](https://github.com/FTBTeam/FTB-App/files/4428498/error.log)
[launcher.log](https://github.com/FTBTeam/FTB-App/files/4428499/launcher.log)

**Comment by Flameboy321** [comment]
Did you find the issue?

**Comment by Jake-E** [comment]
We don't have enough information in the logs to give an accurate answer. We're working on a new release with, hopefully, a little better logging.

Have you quit the app completely and opened it back up and tried a new install?

**Comment by Flameboy321** [comment]
3 times and the message always repeats

**Comment by Jake-E** [comment]
Does this persist after updating the app (re-opening should update)?
If so, please provide us with new logs after trying:
https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Comment by Jake-E** [comment]
If your issue re-occurs, please feel free to re-open this.
