### ISSUE TITLE
[Bug (Windows)]

### ISSUE THREAD

**Issue by ItsChase7** [FTBTeam/FTB-App#412]
When playing a 1.16 modpack Seaopolis my game crashes after like 10-30 min even if I am just afk doing nothing or sometimes when I open things with an interface. I've played many other modpacks like sky factory and ATMs and have never crashed like this before. I am going to put the exact crash report below Please help!!!!
[crash-2021-05-08_15.31.20-client.txt](https://github.com/FTBTeam/FTB-App/files/6542385/crash-2021-05-08_15.31.20-client.txt)

**Comment by Gaz492** [comment]
This looks like an issue with the modpack you are playing, you will need to contact the author of the modpack.
