### ISSUE TITLE
[Bug] Linux Support complete broken

### ISSUE THREAD

**Issue by druuuhl** [FTBTeam/FTB-App#414]
**Operating System:**
OS: Debian Linux 10

**Installer Version:**
Installer: FTBA_unix_202105051818-5b1f30277f-release.s

**App Version:**
App:  Newest

**UI Version:**
UI: ???

**Log Files:**
Launching FTBApp with java11 (add debug flag (-x) to bash interpreter)
- https://paste.feed-the-beast.com/view/2cdcbd3d

Latest.log
- https://paste.feed-the-beast.com/view/b6e20ffe

**Describe the bug**
The Launcher needs Java11, but with java11 mods cant start. i cant set another java version in mod than the newest one, so launcher needs java11, but java 11 is noch allowd for mod.
Please fix the this, in the moment THE LINUX CLIENT SUPPORT IS BROKEN!
i tried this with

- Fresh installed Debian Linux 10
- Fresh installed FTBApp (FTBA_unix_202105051818-5b1f30277f-release.sh)
- Fresh installed Direwolf
- Installed Java 8 / 11

Or is there another way to start the mod instance ?

**To Reproduce**
Install Linux, install a mod, try to start mod

**Expected behaviour**
Run Mod

**Screenshots**
https://easyupload.io/u0bkvy

**Additional context**
The whole story
https://forum.feed-the-beast.com/threads/ftba-for-linux-is-broken.304569/

**Comment by MichaelHillcox** [comment]
I've been able to launch multiple packs on the Linux version of the app. You can also select the java version you wish the packs to start with in the settings (or their packs settings IIRC).

Your screenshot has expired, could you confirm if this is still an issue for you?

**Comment by druuuhl** [comment]
Another 30 Days, tested today, same issue

 - https://easyupload.io/9f5vs0

**Comment by MichaelHillcox** [comment]
Do you have both java 11 and java 8? You shouldn't need both but you could try and have the app running java 11 for the app then specify java 8 for your game instance. The error you got from the MC Launcher might be more telling. Can you run the MC Launcher normally?

**Comment by druuuhl** [comment]
Vanilla MC works fine with java 11,15,18. before update in march or april, FTBapp and mods aer working fine with java 15, after that, java 11 is forced for app and i cant choose other for instance, you see that in the screen film.

I have newer Java version, because of other software need it, but it doesnt need to be the main (link to /usr/bin/java).

Java 8 and 11 is only an example. Eleven is mandatory for the FTBApp, but the mod doesnt run with it and you can see, i cant choose another than  the newest java version (if i have installed java15 or 18, i can choose only the newest) for the instance when both are installed, but without java 11, the App doesnt start,because its hard coded. 
Test with only java 8, FTBApp doesnt start
Test with only java 11, FTBApp starts, but mod doesnt start, with error

 - terminate called after throwing an instance of 'std::logic_error'

which means, the minecraft launcher is not able to start
