### ISSUE TITLE
[Bug (MacOS)] Unable to mount installer dmg on macOS Monterey

### ISSUE THREAD

**Issue by TilBlechschmidt** [FTBTeam/FTB-App#418]
**Operating System:**
OS: macOS 12.0 Monterey Dev Beta 1 (21A5248p)

**Installer Version:**
Installer: Latest aka `FTBA_macos_202105051818-5b1f30277f-release.dmg`

**App Version:**
App: Unknown

**UI Version:**
UI: Unknown

**Log Files:**
N/A

** Debug Code: **
<img width="788" alt="image" src="https://user-images.githubusercontent.com/5037967/122758244-dbd58e80-d298-11eb-8e1e-e783d3c72ff7.png">

**Describe the bug**
When attempting to unpack/mount the `.dmg` archive on the pre-release version of macOS, it fails with the error shown below:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/5037967/122758319-f3ad1280-d298-11eb-87a5-77dd58ec983a.png">

**To Reproduce**
Steps to reproduce the behaviour:
1. Install macOS Monterey
2. Download the FTB Launcher Installer
3. Open the downloaded `.dmg` file by double clicking it in Finder
4. See error shown above

**Expected behaviour**
It mounts correctly and proceeds to show an installer of some sort.

**Relevant information**
Mounting manually through the command line works as expected. However, the average user may not have the knowledge to do so.
<img width="656" alt="Screenshot 2021-06-21 at 14 03 17" src="https://user-images.githubusercontent.com/5037967/122758885-9b2a4500-d299-11eb-8202-9aea307b670c.png">

**Additional context**
I am fully aware that this is a pre-release problem. For this reason, I do not expect you to fix this before the official release (or public beta) of the next macOS version. However, I'd like to raise awareness of the issue so it can be fixed as early as reasonably possible so that you do not receive a huge influx of issues once the new macOS version hits the public.

Note that the fact that mounting via command-line works might indicate that it, in fact, is an issue on the macOS side. However, other `.dmg` files work just fine — so either the FTB one is special or something else is amiss.

**Comment by Jake-E** [comment]
We'll see if this persists once Monterey has released - for now, I'm closing as we don't support OS betas.
