### ISSUE TITLE
[Bug (Windows)]

### ISSUE THREAD

**Issue by b-roby** [FTBTeam/FTB-App#419]
**Operating System:**
OS: Windows 11 Pro

**App Version:**
App: - 

**UI Version:**
UI: -

**Log Files:**
Put links to your logs here https://pastebin.com/07JR7HEn
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

** Debug Code: **
Please run the following tool and provide the code given. FTB-DBGMELESIDUVE
https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe

**Describe the bug**
A clear and concise description of what the bug is. Opening the launcher works well, it just stays in the color-changing state and doesn't leave. It's pretty much stuck here.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'FTB App'
2. Click on 'Run'

**Expected behaviour**
A clear and concise description of what you expected to happen. I would get sent to the menu where I can chose what modpack I want to play

**Screenshots**
![image](https://user-images.githubusercontent.com/85584170/123015327-cb283400-d3d0-11eb-9dc0-fb4a6cd327f9.png)

**Additional context**

**Comment by Sunekaer** [comment]
Not support as that OS isn't released.
