### ISSUE TITLE
Installer has invisible text when using certain dark themes on Linux 

### ISSUE THREAD

**Issue by SynthRose** [FTBTeam/FTB-App#42]
When opening the installer on Linux, if your window manager has a dark theme, the text may be invisible: [Image](https://cdn.discordapp.com/attachments/608088354042544139/695664648573419530/unknown.png) (using GTK Adawaita Dark)

When I open the application with a different user, there is no issue: [Image](https://cdn.discordapp.com/attachments/629568084188987413/695665897901391953/unknown.png)

Other screens are still visible, so it's not necessarily a critical issue. It may also be a general problem with Swing apps, which looks to be what the installer uses.

**Comment by Jake-E** [comment]
We're hoping to have other methods of installing on Linux. Please see #8.
