### ISSUE TITLE
[Feature request] Change the current file explorer dialogue to the generic Windows one to maintain all functionality

### ISSUE THREAD

**Issue by Novocastrian** [FTBTeam/FTB-App#422]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that the "Browse" button to open the instances folder uses some other file explorer to Windows Explorer. This doesn't provide the same functionalities (or add useful new ones) that necessitate a new file explorer. In this current state, it doesn't correctly follow the system's dark mode setting, which is poor for accessibility (I cannot use the default windows theme w/o getting migraines - gotta use dark mode for everything!
![image](https://user-images.githubusercontent.com/4601813/125418302-819ce6fe-5450-4208-ab63-20532bdce1a6.png)

**Describe the solution you'd like**
Just use Windows' file explorer "select folder" dialogue so user preferences are maintained. 
**Describe alternatives you've considered**
Manually navigating to the instance location and adding a desktop bookmark to the location *shudders*

**Comment by MichaelHillcox** [comment]
As we're using Overwolf for windows, we're tied to their internal handling of systems, we can't fix this sorry.
