### ISSUE TITLE
[Feature request] Allow updating/downloading multiple modpacks simultaneously (+ while playing)

### ISSUE THREAD

**Issue by Novocastrian** [FTBTeam/FTB-App#423]
**Is your feature request related to a problem? Please describe.**
Would like to update/download multiple modpacks simultaneously (match curseforge client capability)
**Describe the solution you'd like**
Capability to download/update modpacks simultaneously. Bonus points if we can do that while playing. 
**Describe alternatives you've considered**
None possible, as the client disables navigation while it (painstakingly slowly) downloads the update/installation files

**Comment by MichaelHillcox** [comment]
This is now supported :+1: (Although, not whilst playing but this is planned for the future)
