### ISSUE TITLE
[Bug]: Cannot update FTB Academy 1.16 to v1.1.0 from v1.0.1

### ISSUE THREAD

**Issue by Novocastrian** [FTBTeam/FTB-App#424]
### What Operating System

Windows 10

### App Version

202106032039-901edde0d3-prototyping

### UI Version

98ddb468

### Log Files

https://pste.ch/huyalodoqa

### Debug Code

FTB-DBGUQEKUHAXIQ

### Describe the bug

App gets stuck on downloading modpack

### Steps to reproduce

1. Open the app
2. Navigate to FTB Academy 1.16 from My Modpacks
3. Click the Update button next to the play button
![image](https://user-images.githubusercontent.com/4601813/125420830-382ab2bb-7855-405f-8b1d-691ceb6a933d.png)
4. Get stuck at "Creating Environment" step. Was waiting for 20 minutes before I gave up and force quit the application.
![image](https://user-images.githubusercontent.com/4601813/125420949-04974493-2bbf-43df-96a6-ebefecfc68a1.png)
Note: see menu items greyed out, so I was unable to fetch log files via settings. I've provided logs beforehand, cause I can't find where these are stored locally. 

### Expected behaviour

Downloads and installs the modpack quickly

### Additional information

I tried reinstalling to a clean directory. The installer from https://feed-the-beast.com/ recognised other Overwolf installations (Overwolf + Curseforge app), and took over the installation from there. I can not locate a `i4j_nlog_X.log` file anywhere in `%localappdata%/temp`, or anywhere else on my system for that matter. 

### Information

- [X] I have provided as much information as possible

**Comment by gigabit101** [comment]
Not seeing any issues in the log and it seems to have worked fine on my side, Can you attempt to update the pack once again and see if the issue persists?
