### ISSUE TITLE
[Bug]: Keep not loading the app

### ISSUE THREAD

**Issue by yaeyewon112** [FTBTeam/FTB-App#425]
### What Operating System

Windows Insider Preview

### App Version

202106032039-901edde0d3-prototyping

### UI Version

?

### Log Files

nothing

### Debug Code

FTB-DBGRUXICUROVI

### Describe the bug

Cannot start FTB App

### Steps to reproduce

1. Run Overwolf
2. Click on FTB App
3. Infinite Loading :(

### Expected behaviour

Run FTB App

### Screenshots

<img width="960" alt="ftb" src="https://user-images.githubusercontent.com/86336662/125706831-b0320b29-bfc2-445e-b72a-7b8d9071b04a.png">

### Information

- [X] I have provided as much information as possible

**Comment by yaeyewon112** [comment]
Windows 11 Build 22000.65

**Comment by Gaz492** [comment]
This is a known issue with windows 10 insider builds and windows 11, we have a fix for this coming hopefully within the next week or so I believe
