### ISSUE TITLE
Feature: View mods in modpack

### ISSUE THREAD

**Issue by AuroraBTH** [FTBTeam/FTB-App#43]
When I press the three dots (More information) on a modpack, a list view that displays the mods and their version would be nice. An addition to this could be an option to disable/enable mods.

From what I can tell, `version.json` contains most of the necessary information.

**Comment by Gaz492** [comment]
Installed modpacks will now have a mod list displaying the name, version, size and SHA1 of the mod.
Added in 01139b2

**Comment by zedekblue** [comment]
Why only installed modpacks? This should be applied to all modpacks, as the mods/content itself effects whether I want to download them to begin with.

**Comment by Gaz492** [comment]
We are looking into adding a modlist to non-install packs but this will take more time to implement.
