### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by infelicitatis** [FTBTeam/FTB-App#430]
### What Operating System

Linux (Arch)

### App Version

202105051818-5b1f30277f-release

### UI Version

3e720d86

### Log Files

https://pastebin.com/K13YezeK

### Debug Code

ICantRunThe"ftb-debug-linux"FileAndDontKnowHowSORRY

### Describe the bug
crash on world load when the keyboard button "ö" is assigned to anything

### Steps to reproduce

1. be on linux and have a german qwertz keyboard
2. start ftb revelations
3. change "walking backwards" to "ö" in controls
4. try to load world
5. crash

### Expected behaviour

world loading and having fun playing

### Additional information

I can't play, because i am a left handed german:
So under Windows this is no problem, because if i use ö ä ü etc. buttons it recognizes them as graves, semicolon etc. 
on linux (garuda linux latest) it actually assgigns the ö ä ü buttons. Something really doesnt like those buttons (could be inv.tweaks from what i have seen in the logs, but i am really not qualified to know) so the game crashes when trying to join a multiplayer or singleplayer world. Game also crashes if you are already in a world and then assign something to the button "ö"

(also if you assign strafe right" to "ä" you can start strafing by pressing ä, but you can't stop strafing by releasing ä. so you just keep strafing till you quit once.

My system:
Operating System: Garuda Linux
KDE Plasma Version: 5.22.4
KDE Frameworks Version: 5.85.0
Qt Version: 5.15.2
Kernel Version: 5.13.12-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 1600X Six-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: Radeon RX Vega 64

installed ftb with the script provided on the website, so legacy launcher and whatever java version it installs automatically

I cant run the file from which i should get the Debug code, and if i open it with kate it only shows gibberish. Sry i tried, but i am really not an expert in linux by any means, and your file doesnt even tell me, what kind of file it is (.jre, .sh, etc.) so i cant google on how to run it.

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Are you having an issue with the app or playing in game?

**Comment by infelicitatis** [comment]
well hard to tell for a person like me, who doesn't know which part of the whole FTB program manages the keybaord passthrough to minecraft. but if this is a sarcastic note, that i posted the bug in the wrong place, i am happy to be enlighted where the correct location would be.

**Comment by MichaelHillcox** [comment]
This isn't an app issue, you'll figure out what ever mod is causing your issue and report it to them. We don't pass through input, we just start minecraft for you like any other launcher does.

**Comment by infelicitatis** [comment]
> This isn't an app issue, you'll figure out what ever mod is causing your issue and report it to them. We don't pass through input, we just start minecraft for you like any other launcher does.

how the heck am i supossed to figure that out?
i tried, and the only thing familiar i saw in all those logs after hours of trying to play, was inv.tweaks.

i asked on discord, but they said its a general ftb issue that ö,ä and ü dont get renamed to semicolon, graves and so on...

**Comment by MichaelHillcox** [comment]
I can ensure you, this is not our issue and you could have figured it out based on the fact we physically launch the Minecraft Launcher
