### ISSUE TITLE
[Bug]: Modpack crashes instantly on any version

### ISSUE THREAD

**Issue by mcmodderHD** [FTBTeam/FTB-App#433]
### Modpack

FTB OceanBlock

### Modpack version

any

### Log Files

https://pastebin.com/BiYfeKWp

### Describe the bug

Modpack is unable to start

### Steps to reproduce

1. Install Modpack (Any version)
2. Click on Play in the FTB App
3. Click Play in the Minecraft Launcher
4. Launcher closes and reopens with Exit Code 0

### Expected behaviour

Modpack should start

**Comment by p18sch** [comment]
Not the OP but your solution fixed it for me! Thanks!

**Comment by Leonardo6270** [comment]
it still doesn't work for me

**Comment by MichaelHillcox** [comment]
We have begun shipping a new version of the app with a completely rewritten install and launch system. If your issue is still happening, please create a new issue once you have tested against the new version. Any version after (ui: bdf8bdbaca, subprocess: 202112101445-bdf8bdbaca-release.
