### ISSUE TITLE
[Feature request]Hello

### ISSUE THREAD

**Issue by Gaz492** [FTBTeam/FTB-App#435]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DinnerBeef** [comment]
Mikey Closed This Issue!!!!!

**Comment by UnRealDinnerbone** [comment]
Can Cofirmed!

**Comment by DinnerBeef** [comment]
Yes its emailing me
