### ISSUE TITLE
Launcher doesn't install

### ISSUE THREAD

**Issue by FluffyTowels** [FTBTeam/FTB-App#44]
It downloads and installs java runtime then closes and it's the same thing every time I launch it.

**Comment by Gaz492** [comment]
Could you upload the launcher.log and error.log from the location you installed the app too?
Could you also make sure you disable any anti-virus/malware you may have

**Comment by FluffyTowels** [comment]
It didn't ask me for an installation folder and I did try disabling the anti-virus, it changed nothing

**Comment by Jake-E** [comment]
This needs the launcher installer log @Gaz492. Do you recall where that is?

**Comment by Gaz492** [comment]
From looking at my installation its in a folder called .install4j where the app is installed

**Comment by FluffyTowels** [comment]
And where is that folder supposed to be?

**Comment by AKTheKnight** [comment]
That would probably be C:\Users\YourUsername\roaming\FTBA\.install4j

**Comment by FluffyTowels** [comment]
It's not there

**Comment by jeremiah-dev** [comment]
Hey, I had this exact same issue yesterday. 
JRE would download (even though I have the latest version - is this a separate bug?) and then it would say it's launching the installer and then nothing would happen - no new window. 
So I downloaded the latest version of the FTB launcher today (1.0.4) and ran that after uninstalling the older version - it now opens the Windows installation wizard correctly! 

@FluffyTowels maybe try this? 

I also made sure to delete any references to the FTB app in [Username]/AppData/Roaming/ as the uninstall didn't remove everything (this is already logged as a separate issue).

**Comment by FluffyTowels** [comment]
I just tried the new version of the launcher. Same result, and I can't really delete the older version because _nothing_ was installed.

**Comment by jeremiah-dev** [comment]
Apologies - I meant after uninstalling the old FTB launcher, from before the Twitch integration.

**Comment by Gaz492** [comment]
Could you go to the following folder for me by pressing the `Windows key + R` then in the text box enter `%localappdata%\Temp`

In the folder it takes you you will need to find a file named similar to `i4j_nlog_1.log` and `i4j_log_FTBA_7150034062115045105.log`

Could you upload those log files for us?

**Comment by FluffyTowels** [comment]
[i4j_nlog_1.log](https://github.com/FTBTeam/FTB-App/files/4432488/i4j_nlog_1.log)
I didn't see one similiar to the second one

**Comment by sem1colon00** [comment]
![image](https://user-images.githubusercontent.com/63216602/78626516-f73dbf00-78c9-11ea-9f63-09ada2d9baf3.png)
error...

**Comment by sem1colon00** [comment]
[i4j_nlog_10.log](https://github.com/FTBTeam/FTB-App/files/4441870/i4j_nlog_10.log)
error log. 1.0.5 version

**Comment by sem1colon00** [comment]
@Jake-E

**Comment by Jake-E** [comment]
Does this still happen with the latest installer?
https://apps.modpacks.ch/FTBApp/release/1.0.6/FTBA_windows-x64_1_0_6.exe

**Comment by sem1colon00** [comment]
Yes... same error...

**Comment by sem1colon00** [comment]
How can i fix it?

**Comment by Jake-E** [comment]
Can we get the new log, please?

**Comment by sem1colon00** [comment]
#77 i wrote...
