### ISSUE TITLE
Changelog encoding

### ISSUE THREAD

**Issue by jamierocks** [FTBTeam/FTB-App#454]
The endpoint for the FTB Inventions 1.0.2 changelog doesn't work - it returns a 200, but no content.

https://api.modpacks.ch/public/modpack/21/21/changelog

**Comment by MichaelHillcox** [comment]
@ThePaul-T is this still valid? If not, please close

**Comment by ThePaul-T** [comment]
Unsure, the move to using an OS that is based on musl has likely resolved a lot of the encoding issues, but I cannot be sure they're all resolved.

I know the known one regarding single quotes has been resolved.

**Comment by MichaelHillcox** [comment]
Gunna close as it's mostly fixed if not completely
