### ISSUE TITLE
Verify Files / Integrity check

### ISSUE THREAD

**Issue by JosEffigy** [FTBTeam/FTB-App#462]
### What version of the app is the feature intended for?

Windows

### What is your feature request?

Add an option for an Integrity Check. When downloading on unstable connections there is no way to detect whether the modpack is complete or not. Despite not being complete, It gives me the feedback that it is done installing. I have over half the mods at 0KB and there is no way to download only those specific corrupted downloads. I am unsure whether to make a feature request or an issue report

### Does your request solve an issue?

It fixes when you install a modpack and the files are corrupted.

### Describe alternatives you've considered

Fixing the download system to not drop a download and wait for retransmits or retry downloads. The download threads arent all that efficient even at 12 threads.

**Comment by MichaelHillcox** [comment]
This has been resolved as we now validate each file as it's downloaded :+1:
