### ISSUE TITLE
Only FTB Apps show up in my library or in the search feature

### ISSUE THREAD

**Issue by ManuelRauda** [FTBTeam/FTB-App#464]
### What Operating System

Windows 11

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

https://pste.ch/vuwazamuzi and https://pste.ch/hozizaxevu

### Describe the bug

The issue I am having is that any and all curseforge mods are missing from my ftb launcher. Basically all the curseforge mods are not in my library  and when I try to search them up in the search function ftb works as expected but the curseforge section displays a blank page when searching up a mod. Due note that all mods are still in the instances folder. As I switched to the curseforge app and copied my worlds saved file over to the mod I wanted to play and so far the world is perfectly fine.

### Steps to reproduce

All I did was turn on the ftb app and I was faced with that issue.

### Expected behaviour

To find all my curseforge download mods and to be able to search for them

### Screenshots

![Screenshot 2021-12-30 113339](https://user-images.githubusercontent.com/80341053/147782819-4b24c10b-f444-476d-9179-08447ee2c54e.png)
![Screenshot 2021-12-30 113401](https://user-images.githubusercontent.com/80341053/147782820-85ff7074-575b-41d6-82c8-6c0c52b9f33c.png)
![Screenshot 2021-12-30 113434](https://user-images.githubusercontent.com/80341053/147782821-a710dea6-87e2-46d7-93ab-aea4d56536e4.png)

**Comment by MichaelHillcox** [comment]
Hay, this is all on quite an old version of the app, can anyone confirm if you're still having this issue?
