### ISSUE TITLE
Problem while installing ftb launcher

### ISSUE THREAD

**Issue by Halaiksse** [FTBTeam/FTB-App#47]
![Capture](https://user-images.githubusercontent.com/63127846/78406551-db3bd400-75d0-11ea-809d-ce134b82a9fd.PNG)
It's stuck at the first screenshot and disk usage/internet usage is at 0.
Using BitDefender, had the old launcher and just uninstalled it.
minecraft working perfectly fine and jre is up to date.

**Comment by Jake-E** [comment]
Try running the installer as admin

**Comment by Halaiksse** [comment]
> Try running the installer as admin

Didn't work, had another problem too while trying to uninstall old launcher : 
![image](https://user-images.githubusercontent.com/63127846/78458255-f6185200-767d-11ea-83ea-a50fc20bc73c.png)

**Comment by Jake-E** [comment]
Can you get us logs, please see this for location:
https://github.com/FTBTeam/FTB-App/issues/44#issuecomment-609026147

**Comment by Halaiksse** [comment]
[_logs.zip](https://github.com/FTBTeam/FTB-App/files/4432525/_logs.zip)
there you go, there were a lot so i zipped them all in a file for you. 
Thanks a lot by the way !

**Comment by Jake-E** [comment]
Does still happen with the latest version?
https://apps.modpacks.ch/FTBApp/release/1.0.6/FTBA_windows-x64_1_0_6.exe
