### ISSUE TITLE
[Bug]: Can't install FTB Infinity Evolved 1.7

### ISSUE THREAD

**Issue by Reymai** [FTBTeam/FTB-App#470]
### What Operating System

Linux (Arch)

### App Version

202202111343-da0b2207d4-release

### UI Version

da0b2207d4

### Log Files

https://pastebin.com/RTSsTUCD

### Debug Code

FTB-DBGKOXEGUGODA

### Describe the bug

When trying to install FTB Infinity Evolved 1.7, shows error with message "Install failure The modpack has failed to install. please check the logs"

### Steps to reproduce

1. Go to search
2. Search to "FTB Infinity Evolved"
3. Click the green install button

### Expected behaviour

Modpack installation

### Additional information

Others modpacks, which I checked out, installing without any troubles

### Information

- [X] I have provided as much information as possible

**Comment by maratnureev** [comment]
I have the same issue and only with infinity evolved

**Comment by aPicklePlum** [comment]
I am having the same issue and only with Infinity evolved too. I am on Mac fully updated

**Comment by s104739** [comment]
I am having the same issue with infinity evolved and infinity evolved skyblock. I am on Mac and i can't find the logs.

**Comment by Reymai** [comment]
After today's update, it has been fixed
