### ISSUE TITLE
Problem when trying to start Infinity evolved 1.7

### ISSUE THREAD

**Issue by Engzlt** [FTBTeam/FTB-App#471]
Problem: When trying to start Infinity Evolved I get the error 'Potentially invalid instance'. To solve this I have to deinstall the FTB App and reinstall everything every single time I close the game and open it when I want to play again. I tried looking at the instances and deleted the supposedly duplicated ones but it does not fix the problem.

![image](https://user-images.githubusercontent.com/99609264/153766323-2672508d-3dc5-4e0d-b628-fb4040cb7954.png)

The scripts folder is empty and there are 0 duplicated mods.

**Comment by Gaz492** [comment]
Please follow the bug reporting template, as this will give us the information required to debug the issue
