### ISSUE TITLE
[Bug]:FTB app can't connect to Xbox live

### ISSUE THREAD

**Issue by YK59** [FTBTeam/FTB-App#472]
### What Operating System

Windows 10

### App Version

202202141200-45844bd46c-release

### UI Version

45844bd46c

### Debug Code

FTB-DBGUTEWARONAR

### Describe the bug

While launching minecraft, because of the migration to Windows, I have to login to Xbox Live but even if the browser page say that the operation is succesful, the FTB app doesn't recognize the Microsoft Account so I can't play.

### Steps to reproduce

1. Go to Library page
2. Launch a modpack
3. Sign in with Microsoft
4. New Browser window open, connect to Windows account
5. On Browser window it says "You're in! You can now safely close this tab and return to the FTB App."
6. Go back on FTB app
7. FTB app show an error message "Something went wrong. Somethings gone wrong with checking your login with Xbox live!"

### Expected behaviour

I expected to play but I can't because I'm not connected with windows

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
This should be fixed, if it's still an issue, please let us know
