### ISSUE TITLE
[Bug]: Cannot Launch FTB infinity evolved

### ISSUE THREAD

**Issue by JohnStorm19** [FTBTeam/FTB-App#475]
### What Operating System

MacOS (Current)

### App Version

202202141200-45844bd46c-release

### UI Version

45844bd46c

### Debug Code

I don't know how to do this

### Describe the bug

I cannot use the launcher to open FTB infinity evolved.  Mods stop loading midway through opening.

### Steps to reproduce

1.open ftb app
2.click play for FTB infinity evolved
3. wait for it to load Java, but it stops at the 2/7 stage. on mod 43/179 (extra trees)
4. If you close the FTB app, minecraft will load all the mods, but then disappear.  

### Expected behaviour

It will get stuck at the 1/7 initializing mods stage.

### Information

- [X] I have provided as much information as possible

**Comment by JohnStorm19** [comment]
Update: Every time that I attempt to use the launcher, it always gets stuck in the 2/7 stage with the "Extra trees" mod (43/179)

**Comment by Jake-E** [comment]
A fresh install of FTB Infinity Evolved seems to work now. Closing this as I see no issue.
