### ISSUE TITLE
[Bug]: Modpack Installation Failure

### ISSUE THREAD

**Issue by muhammedesadcomert** [FTBTeam/FTB-App#476]
### What Operating System

Windows 11

### App Version

202202141200-45844bd46c-release

### UI Version

45844bd46c

### Log Files

https://pste.ch/agatapefuc.sql

### Debug Code

FTB-DBGEJERELELIP

### Describe the bug

Fail to install or update some modpacks (Enigmatica 8, Medieval Minecraft Forge 1.18.1)

### Steps to reproduce

1. Go to Browse
2. Choose Curseforge
3. Search Enigmatica 8
4. Click the install/get button
5. Wait a few seconds
6. See the error in the bottom right corner: "The modpack has failed to install, please check the logs."

### Expected behavior

Successful installation for the modpack

### Screenshots

![Install Failure](https://user-images.githubusercontent.com/46245749/154259378-77beee56-284c-4f8e-a07a-ab7570dfb1fa.png)

### Additional information

I tried refreshing the cache. However, it didn't work.

### Information

- [X] I have provided as much information as possible

**Comment by covers1624** [comment]
This was an issue when Forge 1.18 was freshly released. This was resolved a little while ago.
