### ISSUE TITLE
[Bug]: Lost of my internet speed when minecraft is launched

### ISSUE THREAD

**Issue by playlucoo** [FTBTeam/FTB-App#478]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

FTB-DBGVAJOVILEBO

### Describe the bug

FTB-DBGVAJOVILEBO

### Steps to reproduce

1. Download FTP App
2. Install a modPack
3. Launch the modPack

### Expected behaviour

Lost of the internet speed from 150 to 0.40 Mbps

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Reduce the amount of threads & download speed the app can use in the settings :+1:
