### ISSUE TITLE
[Bug]: Unable to download essential assets due to SSL issues

### ISSUE THREAD

**Issue by moonbeast32** [FTBTeam/FTB-App#479]
### What Operating System

Linux (Other)

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Log Files

[error.log](https://github.com/FTBTeam/FTB-App/files/8100147/error.log)
I don't know where the latest.log file is located. THis is the only one I could find, other than the install log.

### Debug Code

FTB-DBGYUMUKUFAMA

### Describe the bug

Modpacks fail to start after installation and clicking "play." 

### Steps to reproduce

1. Use OS Linux Mint 20.1
2. Install latest version of FTB app
3. Install a modpack (all modpacks I've tried have failed thus far, including 1st party and 3rd party modpacks)
4. Click "play."

### Expected behaviour

I expect a game instance to appear after at most a minute. Nothing happens at all.

### Additional information

The button changes to "loading" for a while, and then back to "play." Nothing happens after 10-20 minutes of waiting.

the CLI debugger reports 1 error: "  ERROR   open /home/mcjonmor/FTBA/bin/resources/app.asar: no such file or directory" I have tried moving the FTBA folder to the expected location, but I am denied permmission to do so.

I know others have submitted tickets like this, but I felt it appropriate to submit another after reading MichaelHilcox say "If your issue is still happening, please create a new issue once you have tested against the new version" in issue  414 a week ago.

You know, a mirror download would be really nice. Why can't we download packs without using the app?

### Information

- [X] I have provided as much information as possible

**Comment by moonbeast32** [comment]
UPDATE: I managed to sort out permissions and re-install the app in the expected location. My new debug code is: FTB-DBGKUKUNIROFE

This did not fix the issue. The app still behaves as before.

**Comment by MichaelHillcox** [comment]
https://appsdl-overwolf-com.akamaized.net/prod/apps/cmogmmciplgmocnhikmphehmeecmpaggknkjlbag/1.23.622.1340/app.opk

Please try with this version of the app. Make sure your current version of the app is closed. Let me know if you have any more issues.
