### ISSUE TITLE
Unable to launch a modpack 

### ISSUE THREAD

**Issue by Zleub** [FTBTeam/FTB-App#48]
Hi !

I've been able to launch a modpack a few hours ago but it seems to be broken after some update.
Here is my [log](https://pste.ch/azuyimuruh) 

It search for a bin folder in my home directory, which is not here but I'm assuming it's the one in ~/AppData/Roaming/FTBA

**Comment by AKTheKnight** [comment]
https://pste.ch/cilutoroma

It's looking in C:\Users\alex_\bin\ instead of the correct C:\Users\alex_\AppData\Roaming\FTBA\bin

**Comment by Rushmead** [comment]
Fixed and released in 1.0.4
