### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by Jtrinca** [FTBTeam/FTB-App#481]
I'm having trouble logging in. In the bottom left corner of the launcher, I'm signed out. When I sign into my Microsoft account (in browser) it tells me that I'm all logged in and should be good to go. When I click back to the launcher, it says I'm still not logged in and won't let me play any modpacks.

**Comment by Jtrinca** [comment]
More context: 

Browser: Chrome 
macOS Monterey 12.1 
UI Version da0b2207d4
Subproces Version 202202111343-da0b2207d4-release

**Comment by NomadicDaggy** [comment]
Same on manjaro, 202202111343_da0b2207d4_release-1

**Comment by MichaelHillcox** [comment]
Can anyone confirm if this is still an issue
