### ISSUE TITLE
[Bug]: Launch problem / Connection problem

### ISSUE THREAD

**Issue by PredaBear** [FTBTeam/FTB-App#482]
### What Operating System

Windows 10

### App Version

202202111343-da0b2207d4-release

### UI Version

da0b2207d4

### Log Files

https://pste.ch/wonisekeho

### Debug Code

FTB-DBGUGUQOSAJOP

### Describe the bug

Trying to open the 3.5 beta revelation game, but it says i need to relog into my account. Now im trying to log into my acc, receive the code, then it says that i can close the browser page and go back to the FTB launcher. But on the FTB launcher, it keeps saying "Waiting for response" no matter how long i wait.

### Steps to reproduce

See the description and screen shot

### Expected behaviour

To be able to log in and play.

### Screenshots

![FTB 2](https://user-images.githubusercontent.com/100111158/154892905-f1814333-d3fe-4f66-b4fb-76e0de417bdc.JPG)
![FTB 1](https://user-images.githubusercontent.com/100111158/154892906-d730f69b-e50c-46f4-a553-46093e5b4da9.JPG)

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Hi, can you confirm if you're still having this issue on the latest version of the app?
