### ISSUE TITLE
[Bug, macOS]: Launching a second copy of FTB App using `open -n /path/to/ftbapp.app` causes a segmentation fault

### ISSUE THREAD

**Issue by williamleuschner** [FTBTeam/FTB-App#484]
### What Operating System

macOS 12.2.1 (21D62)

### App Version

202202141200-45844bd46c-release

### UI Version

45844bd46c

### Log Files

https://pastebin.com/RwQ44EQv

### Debug Code

FTB-DBGBOHEYAXICE

### Describe the bug

Launching FTB App regularly, then launching a second copy using `open -n /path/to/ftbapp.app` causes the second copy to fail to launch with a segmentation fault.

### Steps to reproduce

1. Double-click FTB App in the Finder to launch it regularly
2. Open a Terminal window and run `open -n /Applications/FTBApp.app` (substituting the path for wherever your copy of FTB App is located)
3. Observe the second FTB App icon bouncing in the dock for a few moments
4. Observe the macOS Crash Report notification indicating that FTB App encountered a segmentation violation

### Expected behaviour

FTB App does not segfault when I run two copies simultaneously

### Additional information

Why would someone do this? Well, when they discover a bug in the application, they may want to start launching Minecraft in the background, since modded Minecraft takes a while to load. They can report the bug while the game is launching, and then they aren't wasting that launching time! They immediately discover that the bug report wizard on GitHub requires that they get information from places inside the launcher that are locked out while Minecraft is running, and the window opened by the "About ftbapp…" menu option doesn't display any of the version information requested by the bug reporting wizard. So, knowing some power-user macOS tricks, they try to open a second copy of the FTB App launcher, hoping that they'll be able to avoid closing Minecraft and incurring another delay. This fails miserably, and they end up having to close Minecraft anyway :(

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Unable to reproduce this on the latest version of the app. As a note, the app will normally automatically close as having two user agents will cause issues due to the way the user agent is designed at this time. Any changes to this fact are very low on the priorty list thus far.
