### ISSUE TITLE
[Bug]: Microsoft authentication failing to authenticate

### ISSUE THREAD

**Issue by JukieB0f** [FTBTeam/FTB-App#486]
### What Operating System

Windows 10

### Debug Code

FTB-DBGUNOVIQEXUV

### Describe the bug

when signing in with a microsoft account to feed the beast, it continually fails to authenticate meaning I can not use the app.

### Steps to reproduce

open app
log in with microsoft account

### Expected behaviour

expecting to be able to sign in properly

### Information

- [X] I have provided as much information as possible

**Comment by TheRealQuentin765** [comment]
My setup:
OS: Microsft Windows 10 Home
     version: 10.0.19044 Build 19044
Browsers: 
     Firefox
           version: 97.0.2 (64-bit)
     Edge
          version:Version 98.0.1108.62 (64-bit)
FTB app:
     UI Version: 3d94342396
     App Version: 202203021109-3d94342396-release
     App log (with verbose on) (restarted app then when through process listed below): https://pste.ch/iwefegewid
My age (maybe helpful?): 17

When the issue started:
Today is the first day with this issue, I migrated accounts before I started using the FTB app in the first place.

Steps to produce:
1. Click the play button on a mod pack =>
     i. Minecraft Login popup appears
     ii. In the bottom a red notification like thing appears and it says: 'Error: not able to update, validate or find your profile, please sign in again.'
2. Click the big Microsoft button =>
     i. Opens a tab in Firefox with a button to sign in with Microsoft (msauth.feed-the-beast.com)
     ii. The FTB app's popup now says 'Waiting for response...'
3. Press the big Microsoft button (in Firefox this time) => Takes me to the Microsoft login page (login.live.com)
4. Enter my username and password then click sign in =>
     i. The tab in Firefox goes now says 'You're in!' (msauth.feed-the-beast.com/callback)
     ii. FTB app says 'Loading...'
     iii. FTB app says 'Waiting for response...'
     iv. FTB app says 'Something when wrong.' with the subtext 'Failed to authenticate Microsoft authentication' with a button labeled 'Close'
     v. All of these occur with in the span of a couple seconds

Attempted fixes:
Restart Overwolf 
Copy link from Firefox to edge then sign in there
Restart my computer
Disable McAfee firewall
Restart Overwolf again
Refresh Cache

Video of the issue:
https://cdn.discordapp.com/attachments/819813080380866580/949735236328103976/2022-03-05_10-27-27.mp4

**Comment by raflowers** [comment]
I'm experiencing the same issue using FTB via Overwolf on Windows 10 but mine just gets stuck on "Waiting for response ..." and the Microsoft logo despite the fact that (https://msauth.feed-the-beast.com/callback) says "You're in! You can now safely close this tab and return to the FTB App"

**Comment by raflowers** [comment]
> I'm experiencing the same issue using FTB via Overwolf on Windows 10 but mine just gets stuck on "Waiting for response ..." and the Microsoft logo despite the fact that (https://msauth.feed-the-beast.com/callback) says "You're in! You can now safely close this tab and return to the FTB App"

I resolved this by deleting the file located at  ~/.ftba/profiles.json and relaunching the FTB app. Hopefully this will help someone else

**Comment by Glen4Mayor** [comment]
I managed to resolve this by uninstalling FTB app from overwolf and reinstalling it

**Comment by ClassySpaceman** [comment]
#

> > I'm experiencing the same issue using FTB via Overwolf on Windows 10 but mine just gets stuck on "Waiting for response ..." and the Microsoft logo despite the fact that (https://msauth.feed-the-beast.com/callback) says "You're in! You can now safely close this tab and return to the FTB App"
> 
> I resolved this by deleting the file located at ~/.ftba/profiles.json and relaunching the FTB app. Hopefully this will help someone else

deleting / renaming the old profiles.json file worked for me also.  Thanks!

**Comment by MichaelHillcox** [comment]
Most of these issues are fixed now, please let me know if anyone else has this problem
