### ISSUE TITLE
[Bug]: Unable to start Stoneblock 2 worlds after the most recent FTB App update

### ISSUE THREAD

**Issue by moosetwin0** [FTBTeam/FTB-App#488]
### What Operating System

Windows 10

### App Version

202203051730-9df8355f62-release

### UI Version

9df8355f62

### Log Files

https://pste.ch/atetalavix.md

### Debug Code

FTB-DBGITEMIPUXEW

### Describe the bug

Upon trying to enter a world after starting the pack, the game crashes.

### Steps to reproduce

Open FTB App
Hover mouse over 'FTB Presents StoneBlock 2'
Click 'Play'
After the modpack loads, open 'New World++'

### Expected behaviour

The world to load, and for me to be able to play

### Additional information

World File:
[New World++.zip](https://github.com/FTBTeam/FTB-App/files/8210125/New.World%2B%2B.zip)

### Information

- [X] I have provided as much information as possible

**Comment by moosetwin0** [comment]
Starting the pack, and then closing FTB Launcher has gotten me further into the world starting, but it still hasn't loaded yet.

**Comment by MichaelHillcox** [comment]
I can't see any major issues here, the app doesn't appear to be the cause, can you confirm if this is still happen on the latest update?

**Comment by moosetwin0** [comment]
Hello, I've just checked it again, (with and without Optifine) and it is still crashing in the same stage of the process.
Here's the crash log for the [Optifine](https://pste.ch/muzinimuva.md) and [No Optifine](https://pste.ch/yiceseceme.md) crash logs.
