### ISSUE TITLE
[Bug]: Can't open Oceanblock

### ISSUE THREAD

**Issue by Fortcraftmonster** [FTBTeam/FTB-App#492]
### What Operating System

Windows 10

### App Version

202203051730-9df8355f62-release

### UI Version

9df8355f62

### Log Files

https://pste.ch/ekivezajah

Minecraft Log: https://pastebin.com/X31Qxxb2

### Debug Code

FTB-DBGERERUMOMIT

### Describe the bug

When trying to launch oceanblock since the new update tying my microsoft account to the ftb app. It starts to load then a minecraft app opens and says I have 512mb of ram dedicated when I set it to 10gb.  Then the minecraft app goes away and the ftb app starts loading all the mods, at the end when its about to launch it just crashes. I tried to reinstall and the same thing happened

### Steps to reproduce

1.Go to Ftb App
2.Launch Oceanblock
3.Wait for crash

### Expected behaviour

To be able to play oceanblock

### Screenshots

https://i.imgur.com/a8q3XAV.png

### Additional information

It only started happening today when I tried to launch the game. Yesterday I had no problems. The only difference is Ftb app being connected to my microsoft account now

### Information

- [X] I have provided as much information as possible

**Comment by Fortcraftmonster** [comment]
It was happening before I added the -Xmx10G

**Comment by MichaelHillcox** [comment]
Can you confirm if this is still an issue?
