### ISSUE TITLE
[Bug]: Modpack Instances Terminates While loading

### ISSUE THREAD

**Issue by tallabomba** [FTBTeam/FTB-App#493]
### What Operating System

Windows 10

### App Version

202203051730-9df8355f62-release

### UI Version

9df8355f62

### Log Files

https://pste.ch/nalujesoxa

### Debug Code

FTB-DBGNIYOVEKOPI

### Describe the bug

Modpacks terminate while loading/deep scanning. 

### Steps to reproduce

1. Open mod pack in FTB app

### Expected behaviour

Loading the modpacks like a few days ago.

### Additional information

I see "picked up argument -Xmx256M" in the logs but I set that arg to -Xmx6G or leave empty in settings

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
This should have been fixed as of the latest version, let me know if it's still an issue.
