### ISSUE TITLE
[Bug]: All The Mods 7 Installation Failure

### ISSUE THREAD

**Issue by chasingpink** [FTBTeam/FTB-App#495]
### What Operating System

Windows 10

### App Version

202203051730-9df8355f62-release

### UI Version

9df8355f62

### Log Files

https://pste.ch/ruxisacixi

### Debug Code

FTB-DBGMAQIDIJOZU

### Describe the bug

Installation of All The Mods 7 ver 0.2.45 Fails

### Steps to reproduce

1. Go to Browse Menu
2. Click Curseforge tab
3. Seach All The Mods 7
4. Download All The Mods 7 - ATM7 - 1.18.1
5. Choose latest release (ver. 0.2.45)
6. Wait for installation to fail

### Expected behaviour

Successful Modpack Installation

### Screenshots

![Screenshot 2022-03-10 083634](https://user-images.githubusercontent.com/57080736/157685151-b7e74d15-ce88-4e95-bc93-c248feea286b.png)
![Screenshot (515)](https://user-images.githubusercontent.com/57080736/157685315-4279962e-46dd-4fcb-9399-1f96524877ab.png)

### Additional information

Each attempted installation creates a new folder with the modpack jpg and instance.json under C:\Users\User\AppData\Local\.ftba\instances\ (see image above for example)

Does not install for previous versions of All The Mods 7 either, but it did install two days ago when I had re-installed the app. The instance did not launch today though so I decided to re-install the modpack and got this issue. Re-installing the app does nothing now. Unfortunately I forgot to save the log from the failed instance launch :(

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Updating coming in the next week for 1.18 packs, sorry about that

**Comment by chasingpink** [comment]
thanks for your work <3

**Comment by CoryNB** [comment]
I am experiencing this as well, It affects every version. the version of public server is 0.2.45

**Comment by MichaelHillcox** [comment]
This seems to work now as of the latest version of the app
