### ISSUE TITLE
[Bug]: No licenses.json

### ISSUE THREAD

**Issue by vierbaum** [FTBTeam/FTB-App#496]
### What Operating System

Linux (Other)

### App Version

"Missing Version File" (probably due to unloaded code?)

### UI Version

"Missing Version File"

### Debug Code

zsh: no such file or directory: ./ftb-debug-linux

### Describe the bug

in src/views/Settings/Licenses.vue, line 45 "../../../licenses.json" is imported, this file, at least on my machine, does not exist, therefore cannot be imported. app doesnt start

### Steps to reproduce

1. $ git clone https://github.com/FTBTeam/FTB-App.git
2. yarn install
3. yarn serve

### Expected behaviour

The app to start (duh)

### Additional information

Im using gentoo, not experienced with JS, so probably a stupid issue on my side

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Generate the license using the yarn task...
