### ISSUE TITLE
[Bug]: Instance Crashes While Loading

### ISSUE THREAD

**Issue by Skiboist** [FTBTeam/FTB-App#499]
### What Operating System

Windows 10

### App Version

202203051730-9df8355f62-release

### UI Version

9df8355f62

### Debug Code

FTB-DBGOSUXONIYIR

### Describe the bug

instance crashes while loading a modpack,, the is no message on what happened it just says instance crashed

### Steps to reproduce

Open FTB Launcher 
Go to FTB Revelation 
Star FTB Revelation

### Expected behaviour

start the modpack and let me play the modpack

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Can you confirm if this is still an issue?
