### ISSUE TITLE
Server Files Installer Wipes Folder

### ISSUE THREAD

**Issue by Bennyboy1695** [FTBTeam/FTB-App#5]
Upon running the server files.exe for Omnia my folder i had selected for the download was wiped clean. Luckily i had it running in a place with files i don't care about. But i believe it should at least have a warning that it will clear the folder as there was no warning before i selected the folder

**Comment by Jake-E** [comment]
@CH-Paul-T we may want to check if the folder is empty and throw a warning if it isn’t? Although I didn’t think it did delete anything if I’m being honest.

**Comment by CH-Paul-T** [comment]
It's a change to the API made earlier to resolve path formating mistakes by the import which has caused this, it's being resolved with both a new version of the server downloader and changes to the API, but caching will delay fixes.

**Comment by Rushmead** [comment]
A new version has now been released that prevents this from happening. Please let us know if you have any other issues with this.

**Comment by Cloudhunter** [comment]
I'm going to close this as it should now definitely be fixed as we've cleared some caches, but please do reply if you have further issues.
