### ISSUE TITLE
[Bug]: Instances wont open, stuck at validating

### ISSUE THREAD

**Issue by Onyxxed** [FTBTeam/FTB-App#503]
### What Operating System

Windows 10

### App Version

202203051730-9df8355f62-release

### UI Version

9df8355f62

### Log Files

https://pste.ch/fesisosoxu

### Debug Code

FTB-DBGFULIHEXITO

### Describe the bug

Stoneblock 2, or any other mod wont start

### Steps to reproduce

1. Go to library
2. Click on play (any mod, but stoneblock 2 in particular)
3. Instance failure - unable to start pack. Please see the instance logs

### Expected behaviour

Download more ram. jk. 

### Additional information

Mods download just fine, but when i click play, it initializes, validates and stops right there. I have done a clean installation of overwolf, ftb app, minecraft and ofcourse deleted mod folders and whatnot at the same time. Tried to search for a crash log, or any log from the mods folder but didnt find any. The app, and stoneblock 2 worked just fine yesterday, i did play for a couple of hours and closed the game normally. Havent changed anything after that. Oh, and i have Avast, but i turned that completely off for my bug finding mission with no luck.

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Hay, sorry for the delay, I've just been able to take a look at your code and it looks like the app failed to download some assets from Minecraft causing the app to fail the validation step, this definitely needs a better error on it. I'm going to look into this for you. 

Could you let me know if you were able to solve this?

**Comment by Onyxxed** [comment]
Yeah it was solved ages ago by some wizard in your discord server. Took 6
hours of intense problem solving btw, but it is fixed now.

to 2. kesäk. 2022 klo 12.27 Michael Hillcox ***@***.***)
kirjoitti:
