### ISSUE TITLE
[Bug]: Can't log in with Mojang Account

### ISSUE THREAD

**Issue by PalowPower** [FTBTeam/FTB-App#504]
### What Operating System

Windows 10

### App Version

202203051730-9df8355f62-release

### UI Version

9df8355f62

### Log Files

https://pste.ch/nezafuqoho

### Debug Code

FTB-DBGIHOLAKEMEK

### Describe the bug

I can't log in with my Mojang Account and I don't want to migrate my account to microsoft

### Steps to reproduce

1. Open the App
2. Click Play on a Modpack
3. You'll only see the Microsoft Button

### Expected behaviour

Two Buttons: Microsoft Log in and Mojang Log in

### Screenshots

![image](https://user-images.githubusercontent.com/73285163/159161175-7039254b-165e-4d6b-9f7e-7e07ed35a227.png)

### Additional information

I've lost access to my Mojang Account linked E-Mail years ago and therefore I can't migrate my Account to Microsoft, what I don't want either.

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
We've added the Mojang login back whilst Mojang fully migrate to Microsoft login
