### ISSUE TITLE
[Bug]: Cannot get modpacks to fully load

### ISSUE THREAD

**Issue by MulletMechanic** [FTBTeam/FTB-App#506]
### What Operating System

Windows 10

### App Version

202203051730-9df8355f62-release

### UI Version

202203051730-9df8355f62-release

### Log Files

https://pste.ch/ezumifarux

### Debug Code

FTB-DBGUZELODIQIK

### Describe the bug

I can download the FTB app fine as well as modpacks. When I go to play them, it goes through the load sequence but always fails to fully load and gets stuck on the progress bar loading. Everything is up to date and I've allocated more than enough RAM. 

### Steps to reproduce

1. open FTB app
2. download any modpack
3. go to play modpack
4. wait for modpack to open
5. nothing happens

### Expected behaviour

I expect it to open minecraft with the selected modpack that I have downloaded. 

### Additional information

I am running Windows 11 if that makes a difference. 

### Information

- [X] I have provided as much information as possible

**Comment by PeterTheMango** [comment]
I have the same issue but on macOS.

**Comment by MulletMechanic** [comment]
> 

Me too, super frustrating. I've been wanting to play the updated versions of all these modpacks but the I've never been able to get a modpack to open on the FTB app.

**Comment by crispyphone** [comment]
@PeterTheMango: Same here. Also running MacOs and trouble started with the latest version oft the FTBApp. The loading process will always get stuck at the very end (Atlas Stitching : minecraft:textures/atlas/chest.png) or anywhere close to that, no matter which modpack I try.

**Comment by ItsAlexWeber** [comment]
@crispyphone Mine does the same thing as well, I have let it sit open for hours and it just keeps sitting on 

> Atlas Stitching : minecraft:textures/atlas/

normally each time it'll get stuck on something new but can never get the pack to fully load.

**Comment by 1sanazar** [comment]
I have the same issue. Stuck on atlas stitching for multiple hours on Mac. I have fabric API and loader the correct version installed. The app simply doesn't work for me. I used to play FTB often (Unleashed 1.7 anyone?) but because all the updated packs are only on this platform I can't play them. The UI is also really laggy. It's cool that they've developed it but I would rather have something that works.

**Comment by crispyphone** [comment]
@ItsAlexWeber @1sanazar 
Since FTB Support unfortunately did not react to this thread by now, I had to look out for an alternative. A friend of mine suggested using GDLauncher, which worked fine for me. It also takes care of the required Java packages.

**Comment by MichaelHillcox** [comment]
Hay, sorry for not getting back to you sooner, looks like the game was running out of memory... It could be due to an old bug that has been fixed now. I'm going to close this issue for now but if it's still happening, please let me know and I'll ask out developers to take a look
