### ISSUE TITLE
Constant Crashing

### ISSUE THREAD

**Issue by RealBytesGC** [FTBTeam/FTB-App#507]
I run the FTB and instantly I get the message that something went wrong but it allows me to proceed to the various packs. I click to play Endeavour and during the process which takes almost 10 minutes it stops and crashes again on gray loading screen

**Comment by RealBytesGC** [comment]
I deleted it due to the duplication message I received changed the folder where mod packs are stored hoping that fixes my issue

**Comment by MichaelHillcox** [comment]
Please follow the issue template if this is still an issue.
