### ISSUE TITLE
[Bug]: Login error

### ISSUE THREAD

**Issue by Dreden94** [FTBTeam/FTB-App#508]
### What Operating System

Windows 10

### App Version

202203051730-9df8355f62-release

### UI Version

9df8355f62

### Log Files

# System Information

 INFO  OS: Microsoft Windows 11 Home (10.0.22000)
 INFO  CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (GenuineIntel)
 INFO  Memory: 7.65 GiB / 15.69 GiB (48.00% used)

# FTB App Checks

 SUCCESS  FTB App directory (AppData): file/directory exists

## Validating App structure

 SUCCESS  Minecraft bin directory: file/directory exists

## App info

 INFO  Located app at C:\Users\Utente\AppData\Local/.ftba
 INFO  App version: 1.22.305.1730
 INFO  Backend version: 202203051730-9df8355f62-release
 INFO  Web version: 9df8355f62
 INFO  Branch: release
 SUCCESS  Does app_settings.json exist?: file/directory exists
 INFO  Instance Location:  C:\Users\Utente\AppData\Local\.ftba\instances

# Check for instances

 SUCCESS  instances directory: file/directory exists
 INFO  found instance:  3a48d70d-faf4-426b-b59e-74e39e14b5f2
 INFO  Name: FTB Endeavour
 INFO  Version: 1.9.0
 INFO  Version ID: 2112
 INFO  Memory: 6144
 INFO  Min/Rec Memory: 4096/6144
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 WARNING  3a48d70d-faf4-426b-b59e-74e39e14b5f2 logs folder: file/directory does not exist
 SUCCESS  3a48d70d-faf4-426b-b59e-74e39e14b5f2 instance.json: file/directory exists
 SUCCESS  3a48d70d-faf4-426b-b59e-74e39e14b5f2 instance.json: json is valid

# Upload logs

 SUCCESS  Uploaded bin/settings.json: https://pste.ch/eqebohogod
 WARNING  Uploading bin/launcher_log.txt: failed to open file
 WARNING  Uploading bin/launcher_cef_log.txt: failed to open file
 SUCCESS  Uploaded logs/latest.log: https://pste.ch/hivuzucuba
 SUCCESS  Uploaded logs/debug.log: https://pste.ch/quyunayozu
 SUCCESS  Overwolf Logs: file/directory exists
 SUCCESS  Uploaded Overwolf/Log/Apps/FTB App/index.html.log: https://pste.ch/luyisibuwo
 SUCCESS  Uploaded Overwolf/Log/Apps/FTB App/background.html.log: https://pste.ch/fijezuduni
 WARNING  Uploading Overwolf/Log/Apps/FTB App/chat.html.log: failed to open file

# Debug Report Completed

### Debug Code

FTB-DBGCOROMOVIWE

### Describe the bug

I try log my account but ftb tell we have problem but web page tell "You're in! You can now safely close this tab and return to the FTB App."...

### Steps to reproduce

Open FTB , try click sign in with Microsoft, a web page is open, use my password and page tell we are in.
Go in FTB launcher and see error massage "Failed to authenticate Microsoft authentication"

### Expected behaviour

Log and play FTB

### Information

- [X] I have provided as much information as possible

**Comment by KurkumaApp** [comment]
Same issue

**Comment by MichaelHillcox** [comment]
Hi, sorry for the slow reply, can you confirm what browser you're using

**Comment by MichaelHillcox** [comment]
No reply, closed
