### ISSUE TITLE
Feature: Modpack list view

### ISSUE THREAD

**Issue by Glaceon575** [FTBTeam/FTB-App#51]
Like different views in windows explorer, the centered tile view just doesn't rub me the right way. A list view, or maybe a detail view, similar to windows explorer. Or maybe an option to toggle the centered view of installed modpack. More options, maybe for things I haven't thought of for things like this would be greatly appreciated.

**Comment by CH-Paul-T** [comment]
View toggle was planned just didn't get implemented for initial release.

**Comment by Jake-E** [comment]
This has been implemented, closing.
