### ISSUE TITLE
[Bug]: Modpack Construction Memory Size

### ISSUE THREAD

**Issue by AfOFyi** [FTBTeam/FTB-App#512]
### What Operating System

Windows 10

### App Version

a5e4f8b1e5

### UI Version

202203251547-a5e4f8b1e5-release

### Log Files

[crash-2022-04-03_11.41.22-client.txt](https://github.com/FTBTeam/FTB-App/files/8404987/crash-2022-04-03_11.41.22-client.txt)
[crash-2022-04-03_12.09.34-client.txt](https://github.com/FTBTeam/FTB-App/files/8404988/crash-2022-04-03_12.09.34-client.txt)
[crash-2022-04-03_11.36.30-client.txt](https://github.com/FTBTeam/FTB-App/files/8404989/crash-2022-04-03_11.36.30-client.txt)
https://pste.ch/zupatikiha

### Debug Code

FTB-DBGUVOQURONAR

### Describe the bug

Java is overwriting the memory allocation settings

### Steps to reproduce

1. Open FTB Desktop app
2. Open Library
3. Click FTB Sky Odyssey play button
4. Change memory allocation after first crash
5. Repeat steps 3-4, adding java arguments

### Expected behaviour

Modpack should run without a problem

### Additional information

I've reinstalled the modpack. I've tried changing the settings for memory allocation, the java arguments within the FTB Launcher instance for Sky Odyssey, and the launcher itself. Nothing seems to be working. I've been struggling with this for over an hour with only backwards progress. 

Most recent log file, the java arguments are: JVM Flags: 17 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=512M -Xmx2g -Xmx8256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xmx512M

I have no idea what's going on, please help.

### Information

- [X] I have provided as much information as possible

**Comment by CoryNB** [comment]
mine craft can exceed specs of computer. lower end lite versions can work without GPU unit, but newer ones require a 4gb or higher GPU unit with more than 20gb of ram.

**Comment by AfOFyi** [comment]
the pack runs fine from the curseforge launcher, so i dont know what the problem is

**Comment by MichaelHillcox** [comment]
This has been fixed now, thank you for reporting the issue

**Comment by MichaelHillcox** [comment]
If you are still having this issue, please let us know. You can fix your issue by editing your systems environment variables and removing the `_JAVA_OPTIONS` entry.
