### ISSUE TITLE
[Bug]: Constant "Instance crashed or externally closed"

### ISSUE THREAD

**Issue by raflowers** [FTBTeam/FTB-App#513]
### What Operating System

Windows 10

### App Version

202203251547-a5e4f8b1e5-release

### UI Version

a5e4f8b1e5

### Log Files

https://pste.ch/gujigayeni

### Debug Code

FTB-DBGJUYAKEROYI

### Describe the bug

When I click play on DW20 1.16 pack it starts loading and stops after about 5 seconds giving the error message "The instance has crashed or been externally closed."

### Steps to reproduce

Install DW20 1.16 pack
Click play
Game begins to load
Loading stops and error message appears

### Expected behaviour

The moadloader should run and launch minecraft

### Additional information

I've been playing on this world for weeks and had some instability - which I expect considering how heavily the game is modded - but now it won't run at all.

### Information

- [X] I have provided as much information as possible

**Comment by Carter-Hosking** [comment]
I have the same issue, please help!

**Comment by MichaelHillcox** [comment]
Hmm, stange, it's saying it can't read a config file. Can you delete the `C:\Users\{username}\AppData\Local\.ftba\instances\7cd0abbe-29c1-4eff-98d2-00be225b138a\config\fml.toml` file from the pack and see if your issue goes away?

**Comment by ZEYDEN88** [comment]
bonjour, j'ai exactement le même problème sur tout les mod packs, une solution ?
