### ISSUE TITLE
[Feature request] Output log deleted when game crashes

### ISSUE THREAD

**Issue by morgybc** [FTBTeam/FTB-App#515]
**Is your feature request related to a problem? Please describe.**
The output log is deleted when the game crashes, making it impossible to access.

**Describe the solution you'd like**
Keep the output log on the screen until it is closed, store it in a text file somewhere, or have an option to keep it at least.

**Describe alternatives you've considered**
There are no alternatives. This is a completely basic necessary feature and I'm shocked it doesn't exist.

**Additional context**
I've been having crashes in academy 1.16 and I can't give people all the information I would otherwise have

**Comment by MichaelHillcox** [comment]
We've implemented this change, the logs will not close when the game crashes. I will note, you can also just look in the logs folder of the instance dir.
