### ISSUE TITLE
[Bug]: Can't log into the app, broken entirely

### ISSUE THREAD

**Issue by CaptainTheGamer** [FTBTeam/FTB-App#516]
### What Operating System

Windows 10

### App Version

202204061044-ef5313e696-release

### UI Version

ef5313e696

### Debug Code

FTB-DBGLUCEQASIGU

### Describe the bug

When trying to sign in through my microsoft account it just refuses to log in, profile icon is bugged too, showing the broken link image

### Steps to reproduce

click add account
sign in w/microsoft
then it'll keep waiting on the confirmation then it just gives up

### Expected behaviour

being able to actually sign into my account

### Screenshots

![Screenshot (30)](https://user-images.githubusercontent.com/103205646/162245524-da2bbc95-e0be-4331-86e5-b55e118fe4c5.png)

### Additional information

for context i've uninstalled the app several times along with minecraft as a whole, keep having this problem

### Information

- [X] I have provided as much information as possible

**Comment by Godchiru** [comment]
Got the EXACT same issue

**Comment by dgwallace92** [comment]
I've been having this issue for a month or two. I've tried uninstalling and reinstalling.

**Comment by MichaelHillcox** [comment]
Please delete your .profiles.json in the `%LOCALAPPDATA%/.ftba` folder. A version of the app at one point was causing this to currupt, sorry for this.
