### ISSUE TITLE
Waiting for response[Bug]: 

### ISSUE THREAD

**Issue by ModFabriek** [FTBTeam/FTB-App#517]
### What Operating System

Windows 10

### Debug Code

FTB-DBGNOLADEMAFU

### Describe the bug

If you try to login with an microsoft account it doesnt recoginze that you alredy finished the authentication

### Steps to reproduce

1. Go to add profile
2. click on microsoft
3. fill in the authentification
4. go back to ftb app
5. see that you are still in the waiting for response mode

### Expected behaviour

Normaly it would just close the waiting for response window and then let me in my microsoft account

### Additional information

I was using a microsoft account after the migration

### Information

- [X] I have provided as much information as possible

**Comment by LapisSea** [comment]
Having the same issue

**Comment by KyleLivingstone** [comment]
![ftb app](https://user-images.githubusercontent.com/105546793/168424081-e9a69435-af86-4fe7-8525-b6ec5ebaaf25.JPG)


same with me, I think the issue with the login is this file seems to have failed in some sort of way, it's extremely frustrating trying to resolve the issue by reinstalling everything, and its still the same issue

**Comment by KyleLivingstone** [comment]
![ftb 3](https://user-images.githubusercontent.com/105546793/168424205-6fab4675-4271-4443-a44c-e79e2527c1fb.JPG)

![ftb 2](https://user-images.githubusercontent.com/105546793/168424206-d9f5d064-3245-4af4-aa75-af1c6c57ac60.JPG)


screenshots of before and after closing the window, again it still is frozen on the same screen "waiting for response"

**Comment by KyleLivingstone** [comment]
again just showing that even after sending in the previous response, the app is still stuck on the same "waiting for response", again this can be left for as long as you desire and it is still stuck and will not log you into your account 
![ftb 4](https://user-images.githubusercontent.com/105546793/168424295-80aee20d-b447-4009-9d18-3e7b09225084.JPG)

**Comment by KyleLivingstone** [comment]
![ftb error message](https://user-images.githubusercontent.com/105546793/168424331-7b89062e-b14f-449f-a623-5cf10da45702.JPG)
this is the error message that has been appearing at the bottom right of the app if you click off of the "waiting for response" screen and attempt to relog

**Comment by KyleLivingstone** [comment]
This of course does not mean anything because it does not matter how many times you try to log in, you will not be able to log in because the screen will never go away no matter if you close the window after the login or not and no matter how many times you attempt to log in

**Comment by KyleLivingstone** [comment]
FYI: I am also using a windows migrated account

**Comment by MichaelHillcox** [comment]
Please delete your `%LOCALAPPDATA%/.ftba/profiles.json`, there was a version of the app that caused this file to currupt. This should be fixed. Sorry for the slow reply to this issue.
