### ISSUE TITLE
[Bug]: severe issue, atm are broken right now whenever I exceed 16gb or more(I have 64gb of ram, so I use 60gb total only)

### ISSUE THREAD

**Issue by CoryNB** [FTBTeam/FTB-App#518]
### What Operating System

Windows 10

### Log Files

version is not an issue, files not an issue, boot up failure has been affecting ATM 6 and 7, no setup phases found to occur. only works in curse forge launcher compared to ftb launcher, which I used recently.

### Debug Code

Windows 10

### Describe the bug

crashes upon opening and activating newest modack of atm 6 and 7 in the app

### Steps to reproduce

go to browse, click the curse forge icon, search for "ATM", download any ATM game version, change ram settings to your maximum your machine has.  

### Expected behaviour

a screen showing a bootup of minecraft.

### Screenshots

N/A

### Additional information

please find out why the game is not running well in any version of atm. 

### Information

- [X] I have provided as much information as possible

**Comment by CoryNB** [comment]
there is no debug for this bug, it is related to minecraft directly

**Comment by MichaelHillcox** [comment]
I'm assuming it's this 

> You can fix your issue by editing your systems environment variables and removing the _JAVA_OPTIONS entry.

As you've not run the debug tool, I'm able to help any more. Please open a new issue if this is still having problems
