### ISSUE TITLE
[Bug]: path localisation issues

### ISSUE THREAD

**Issue by MatonaB** [FTBTeam/FTB-App#522]
### What Operating System

Windows 10

### App Version

202204061044-ef5313e696-release

### UI Version

ef5313e696

### Debug Code

FTB-DBGUZEWUKORAY

### Describe the bug

instance failure(unable to start pack)

### Steps to reproduce

start any modpack by clicking the button"play".
wait a sec and then red message show with the words-
"instance failure"
"unable to start pack... please see the instances logs"

### Expected behaviour

the modpack needs to be work clearly

### Screenshots

<img width="824" alt="ftb problem1" src="https://user-images.githubusercontent.com/103906176/163735194-a6fb561f-57db-4961-afec-1c5c81df29d1.png">
<img width="526" alt="image" src="https://user-images.githubusercontent.com/103906176/163735215-2088bcb0-4179-4fc6-9589-562415904b19.png">

### Additional information

1. the problem happend on the all the modpacks and not just stoneblocks 2
2. i restart the app and also deleted the app and then install again, nothing works.

### Information

- [X] I have provided as much information as possible

**Comment by MoeHunt3r** [comment]
Same Issue but with error popup 
Here's the launcher log
https://pste.ch/tihuhojene

**Comment by CoryNB** [comment]
remove modpack and reinstall it. that helps, if thatdoesn't, add more ram for the computer to use for the game.

**Comment by david2084** [comment]
Not sure if that'll solve your problem but I had a similar issue. Turns out in my case it was my antivirus that was blocking the log4j files despite there being a fix and thus preventing the launch.

**Comment by MichaelHillcox** [comment]
These issues should have been fixed, please let me know if you're still experiencing these issues
