### ISSUE TITLE
[Bug]: Nothing happenes when i open the app

### ISSUE THREAD

**Issue by Eliaslp2047** [FTBTeam/FTB-App#525]
### What Operating System

Windows 10

### App Version

202204211116-ac2e189d70-release

### UI Version

ac2e189d70

### Debug Code

FTB-DBGAJIKOWESUG

### Describe the bug

If i open the app i get an error message

### Steps to reproduce

1. Open the app

### Expected behaviour

I should see the main menu

### Screenshots

![Screenshot (25)](https://user-images.githubusercontent.com/78426947/164973099-e1a8264d-16a5-4aa5-b32e-90f4fbda4592.png)

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
`Error: Could not create the Java Virtual Machine.` @covers1624

**Comment by Jake-E** [comment]
This should be fixed in latest versions of the app, if your issue persists please re-open.
