### ISSUE TITLE
ftb app stoped launching ftb university over night

### ISSUE THREAD

**Issue by ashey218** [FTBTeam/FTB-App#526]
### What Operating System

Windows 11

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Log Files

https://pste.ch/qiqigozeva

### Debug Code

FTB-DBGXAHAYIRIJA

### Describe the bug

app was working perfectly last night but today its not i have changed nothing at all 

### Steps to reproduce

1.open ftb app
2.press play 
3.nothing happens 

### Expected behaviour

minecraft launcher opens

### Screenshots

https://www.reddit.com/r/feedthebeast/comments/suxdl3/neither_modpack_is_working_do_you_have_any_idea/

**Comment by MichaelHillcox** [comment]
Hi, can you confirm if this is still an issue?
