### ISSUE TITLE
FTB App Window Sizing Issue

### ISSUE THREAD

**Issue by jmbly** [FTBTeam/FTB-App#527]
### What Operating System

MacOS (Beta)

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Log Files

https://pste.ch/rovumumalu

### Debug Code

Debug text file of generic document type is unable to be run as a program or script in macOS

### Describe the bug

Window default size too large for standard scaling on default on built-in display. Window unable to be resized down or moved to reach a lower corner as the default sizing leaves window edges off-screen.

### Steps to reproduce

1. Open App, 2. Experience issue described

### Expected behaviour

As the previous version, I expected a smaller window that was able to be resized and not take up more screen space than available

### Screenshots

<img width="1440" alt="Screen Shot 2022-02-19 at 12 32 36 PM" src="https://user-images.githubusercontent.com/47805357/154812135-4f51fbd1-9a74-4d63-8615-42b21edbb7a8.png">

### Additional information

Machine specs: https://support.apple.com/kb/SP748?locale=en_US&viewlocale=en_US

Display set at default scaling of 1440x900

**Comment by MichaelHillcox** [comment]
This was fixed a good few versions ago :D
