### ISSUE TITLE
FTB Presents Stoneblock 2

### ISSUE THREAD

**Issue by JJ1389** [FTBTeam/FTB-App#528]
### What Operating System

Windows 11

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

 12897635-ed78-4c5e-953b-c8ef4910be08

### Describe the bug

Stoneblock 2 will not launch from the ftb minecraft launcher after updating 

### Steps to reproduce

open ftb app

select ftb presents stoneblock 2 

press play

when minecraft launcher loads 

select play and nothing happens 

waiting for over 10 min before restarting computer and trying again with the same result

### Expected behaviour

stoneblock 2 to launch and play the game

**Comment by MichaelHillcox** [comment]
Can you confirm if this is still happening?
