### ISSUE TITLE
FTB Endeavour

### ISSUE THREAD

**Issue by iShaggyR** [FTBTeam/FTB-App#529]
### What Operating System

Windows 10

### App Version

1.9.0

### UI Version

bdf8bdbaca

### Log Files

NA

### Debug Code

FTB-DBGREMABEQUVE

### Describe the bug

I click Load-In , it will not bridge over to the main screen of the game. If I roll back the server to 1.8.0 it will bridge over correctly. But when updating it to 1.9.0 it will not. It acts like it has in the background but it doesn't full execute the process. 

### Steps to reproduce

1.Open FTB APP
2.Click on FTB Endeavour
3. Click Play
4. Wait till you get to "Load-In Game" Or "Stop Mod"
5. Click Load in ( Nothing happens after that.)

### Expected behaviour

Click Load-In - Then game bridges from App to Main Screen of FTB Endeavour.

### Screenshots

NA

### Additional information

NA

**Comment by MichaelHillcox** [comment]
Can you update your app and see if this is still happening?
