### ISSUE TITLE
Incompatible FML modded server

### ISSUE THREAD

**Issue by Dsyon** [FTBTeam/FTB-App#53]
i am currently on the same version as the server and other people have had zero issues getting on im assuming this is just a issues while downloading the files but would love some help or a modpack link so i can use multiMC

**Comment by Dsyon** [comment]
this is on FTB omnia

**Comment by Gaz492** [comment]
Could you upload the launcher logs by pressing the Upload App Logs in settings and upload the client logs for the modpack?
You can use this guide to find the client logs https://faq.ftb.world/books/ftb-app/page/finding-your-client-logs

**Comment by Dsyon** [comment]
i think i figured it out it has a little to do with the server and some to do with that play together mod/addon... it causes issues with people getting a good connection to the server

**Comment by Cloudhunter** [comment]
MineTogether currently requires to be both on the server and the client. If this is not done, then you will have server connection issues.

This will be changed in a future build. Closing this as not a launcher issue.
