### ISSUE TITLE
no sound on any modpack on the ftb launcher

### ISSUE THREAD

**Issue by Gameover123321** [FTBTeam/FTB-App#530]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

FTB-DBGSIKEGEVADA

### Describe the bug

i get no sound from any modpack i try to run via the ftb launcher. i have sound on other apps and i know that i have nothing muted,  i have also tried to reset my sound using f2 and s but no luck

### Steps to reproduce

NA

### Expected behaviour

NA

**Comment by MichaelHillcox** [comment]
Can you update to the latest version of the app and see if this is still an issue?
