### ISSUE TITLE
Downloader getting stuck on "Creating environment..."

### ISSUE THREAD

**Issue by Rainmar7788** [FTBTeam/FTB-App#531]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

https://pste.ch/afaqiwehox

### Describe the bug

Any modpack i try to install, it gets stuck on "creating environment"

### Steps to reproduce

1. try install any modpack (well for my case its stoneblock 1.22.0 beta)
2. watch the program pretty much freeze

### Expected behaviour

The program would install the modpack.

### Screenshots

![image](https://user-images.githubusercontent.com/93010291/156063462-25799350-2610-488f-bbe6-337d907ecd63.png)

**Comment by MichaelHillcox** [comment]
Likely resolved in the latest release, let me know if it isn't.
