### ISSUE TITLE
Problem downloading and opening mod packs

### ISSUE THREAD

**Issue by jduece** [FTBTeam/FTB-App#532]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

FTB-DBGVASEKOTIMU

### Describe the bug

crashes trying to start pack/ stops mid way when starting pack ect ect

### Steps to reproduce

find pack you want to play click play.
wait for about 5 min come back and check on load process.
load process is stuck.
i try to load in game wont work
so have to close ftb completely 
start over...

### Expected behaviour

click play does pre load then i get to play 

### Screenshots

![image](https://user-images.githubusercontent.com/71295057/156242618-191baf66-e7b9-4a96-afc2-5b27883ca941.png)

**Comment by MichaelHillcox** [comment]
Can you update to the latest version of the app and see if this is still an issue?
