### ISSUE TITLE
Modpacks missing

### ISSUE THREAD

**Issue by wlava109** [FTBTeam/FTB-App#534]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

FTB-DBGXOBILOMUZO

### Describe the bug

Some of my modpacks have disappeared.

### Steps to reproduce

I really don't know what happened, but when I opened the app, some of the modpacks I play weren't in the library/home tabs. I couldn't find them on browse either. The instance files are still there, but I can't run them through the app. One that I know is missing is "Dungeons, Dragons, and Space Shuttles." I haven't deleted any instances.

### Expected behaviour

I'd expect them to be there when I open the pack

### Additional information

There are 12 instances in the .ftba/instances folder but only 9 show up in the library.

**Comment by MichaelHillcox** [comment]
@covers1624 we've had multiple reports of this, could you take a look at the report

**Comment by MichaelHillcox** [comment]
This should be fixed now due to new discovery systems for the packs.
