### ISSUE TITLE
FTB app ignoring the JRE version selected for the instance (Adoptium 8.0.322.6), despite being saved to `instance.json`

### ISSUE THREAD

**Issue by Kage-Yami** [FTBTeam/FTB-App#535]
### What Operating System

Windows 11

### App Version

202203251547-a5e4f8b1e5-release

### UI Version

a5e4f8b1e5

### Log Files

https://pste.ch/migoxexoni.md (incomplete log as I killed the instance during startup, as the first few lines mentions the Java version used).

### Debug Code

FTB-DBGOPAZAZOLOX

### Describe the bug

FTB app ignoring the Java version select for the instance, despite being saved to `instance.json`

### Steps to reproduce

1. Install an alternative Java version (e.g. Adoptium Temurin JRE 8.0.322.6)
2. Restart FTB App, or launch if not already running
3. Install a modpack (e.g. OceanBlock 1.12.0)
4. Edit settings of the modpack to use newly installed JRE as the "Java version"
5. Go "back to instance"
6. Launch

Line 4 of the logs will show `1.8.0_312` still being used

### Expected behaviour

I should see Temurin 8.0.322.6 being used

### Additional information

I specifically installed the Temurin JRE (not the JDK), given that was available (from memory, historically, AdoptOpenJDK did not provide JREs, so I imagine JDK was the "default" for a while rather than JRE).

`instance.json` file showing the saved JRE path: https://pste.ch/ayiwoverel.json

**Comment by shinji257** [comment]
I've been able to confirm this issue. I have only Oracle versions installed system wide and I chose Oracle JDK 17.0.3.1 but it still uses it's included Adoptium 17.0.3 instead.

Instance JSON: https://gist.github.com/shinji257/6610f3950a1011e8820458d9cab6e149
Installations JSON: https://gist.github.com/shinji257/7438b03e65076fd73a7a0ea2ca270bf7

Actual binary ran to launch game:
![image](https://user-images.githubusercontent.com/261005/169714833-cd13ed87-25a9-4f24-b46b-82e3c2055dec.png)
Full command line execution: `C:\Users\shinj\AppData\Local\.ftba\bin\runtime\jdk-17.0.3+7-jre\bin\javaw.exe -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Djava.library.path=C:\Users\shinj\AppData\Local\.ftba\bin\versions\1.18.2-forge-40.1.19\1.18.2-forge-40.1.19-natives-1000560885982100 -Dminecraft.launcher.brand=FTBApp -Dminecraft.launcher.version=202205171618-14abefffbf-release -cp C:\Users\shinj\AppData\Local\.ftba\bin\libraries\cpw\mods\securejarhandler\1.0.3\securejarhandler-1.0.3.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\ow2\asm\asm\9.2\asm-9.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\ow2\asm\asm-commons\9.2\asm-commons-9.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\ow2\asm\asm-tree\9.2\asm-tree-9.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\ow2\asm\asm-util\9.2\asm-util-9.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\ow2\asm\asm-analysis\9.2\asm-analysis-9.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\net\minecraftforge\accesstransformers\8.0.4\accesstransformers-8.0.4.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\antlr\antlr4-runtime\4.9.1\antlr4-runtime-4.9.1.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\net\minecraftforge\eventbus\5.0.3\eventbus-5.0.3.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\net\minecraftforge\forgespi\4.0.10\forgespi-4.0.10.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\net\minecraftforge\coremods\5.0.1\coremods-5.0.1.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\cpw\mods\modlauncher\9.1.3\modlauncher-9.1.3.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\net\minecraftforge\unsafe\0.2.0\unsafe-0.2.0.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\com\electronwill\night-config\core\3.6.4\core-3.6.4.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\com\electronwill\night-config\toml\3.6.4\toml-3.6.4.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\apache\maven\maven-artifact\3.6.3\maven-artifact-3.6.3.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\net\jodah\typetools\0.8.3\typetools-0.8.3.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\net\minecrell\terminalconsoleappender\1.2.0\terminalconsoleappender-1.2.0.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\jline\jline-reader\3.12.1\jline-reader-3.12.1.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\jline\jline-terminal\3.12.1\jline-terminal-3.12.1.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\spongepowered\mixin\0.8.5\mixin-0.8.5.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\openjdk\nashorn\nashorn-core\15.3\nashorn-core-15.3.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\cpw\mods\bootstraplauncher\1.0.0\bootstraplauncher-1.0.0.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\net\minecraftforge\fmlloader\1.18.2-40.1.19\fmlloader-1.18.2-40.1.19.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\com\mojang\logging\1.0.0\logging-1.0.0.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\com\mojang\blocklist\1.0.10\blocklist-1.0.10.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\com\mojang\patchy\2.2.10\patchy-2.2.10.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\com\github\oshi\oshi-core\5.8.5\oshi-core-5.8.5.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\net\java\dev\jna\jna\5.10.0\jna-5.10.0.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\net\java\dev\jna\jna-platform\5.10.0\jna-platform-5.10.0.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\slf4j\slf4j-api\1.8.0-beta4\slf4j-api-1.8.0-beta4.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\apache\logging\log4j\log4j-slf4j18-impl\2.17.0\log4j-slf4j18-impl-2.17.0.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\com\ibm\icu\icu4j\70.1\icu4j-70.1.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\com\mojang\javabridge\1.2.24\javabridge-1.2.24.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\net\sf\jopt-simple\jopt-simple\5.0.4\jopt-simple-5.0.4.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\io\netty\netty-all\4.1.68.Final\netty-all-4.1.68.Final.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\com\google\guava\guava\31.0.1-jre\guava-31.0.1-jre.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\commons-io\commons-io\2.11.0\commons-io-2.11.0.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\commons-codec\commons-codec\1.15\commons-codec-1.15.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\com\mojang\brigadier\1.0.18\brigadier-1.0.18.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\com\mojang\datafixerupper\4.1.27\datafixerupper-4.1.27.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\com\google\code\gson\gson\2.8.9\gson-2.8.9.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\com\mojang\authlib\3.3.39\authlib-3.3.39.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\apache\commons\commons-compress\1.21\commons-compress-1.21.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\apache\httpcomponents\httpclient\4.5.13\httpclient-4.5.13.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\apache\httpcomponents\httpcore\4.4.14\httpcore-4.4.14.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\it\unimi\dsi\fastutil\8.5.6\fastutil-8.5.6.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\apache\logging\log4j\log4j-api\2.17.0\log4j-api-2.17.0.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\apache\logging\log4j\log4j-core\2.17.0\log4j-core-2.17.0.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\lwjgl\lwjgl\3.2.2\lwjgl-3.2.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\lwjgl\lwjgl-jemalloc\3.2.2\lwjgl-jemalloc-3.2.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\lwjgl\lwjgl-openal\3.2.2\lwjgl-openal-3.2.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\lwjgl\lwjgl-opengl\3.2.2\lwjgl-opengl-3.2.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\lwjgl\lwjgl-glfw\3.2.2\lwjgl-glfw-3.2.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\lwjgl\lwjgl-stb\3.2.2\lwjgl-stb-3.2.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\org\lwjgl\lwjgl-tinyfd\3.2.2\lwjgl-tinyfd-3.2.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries\com\mojang\text2speech\1.12.4\text2speech-1.12.4.jar;C:\Users\shinj\AppData\Local\.ftba\bin\versions\1.18.2-forge-40.1.19\1.18.2-forge-40.1.19.jar -DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,client-extra,fmlcore,javafmllanguage,mclanguage,forge-,1.18.2-forge-40.1.19.jar -DmergeModules=jna-5.10.0.jar,jna-platform-5.10.0.jar,java-objc-bridge-1.0.0.jar -DlibraryDirectory=C:\Users\shinj\AppData\Local\.ftba\bin\libraries -p C:\Users\shinj\AppData\Local\.ftba\bin\libraries/cpw/mods/bootstraplauncher/1.0.0/bootstraplauncher-1.0.0.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries/cpw/mods/securejarhandler/1.0.3/securejarhandler-1.0.3.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar;C:\Users\shinj\AppData\Local\.ftba\bin\libraries/org/ow2/asm/asm/9.2/asm-9.2.jar --add-modules ALL-MODULE-PATH --add-opens java.base/java.util.jar=cpw.mods.securejarhandler --add-exports java.base/sun.security.util=cpw.mods.securejarhandler --add-exports jdk.naming.dns/com.sun.jndi.dns=java.naming -Dmt.disablechat=true -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UseCompressedOops -XX:-UsePerfData -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=2 -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=50 -XX:G1HeapRegionSize=1 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=8 -Dchtray.port=54085 -Dchtray.instance=5e4a9a3a-bca4-4c76-a315-b02d37d91b68 -javaagent:log4jfixer.jar -Xmx8192M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M cpw.mods.bootstraplauncher.BootstrapLauncher --username shinji257 --version 1.18.2-forge-40.1.19 --gameDir C:\Users\shinj\AppData\Local\.ftba\instances\5e4a9a3a-bca4-4c76-a315-b02d37d91b68 --assetsDir C:\Users\shinj\AppData\Local\.ftba\bin\assets --assetIndex 1.18 --uuid (remove uuid) --accessToken (remove access token) --clientId ${clientid} --xuid ${auth_xuid} --userType msa --versionType release --width 1720 --height 840 --launchTarget forgeclient --fml.forgeVersion 40.1.19 --fml.mcVersion 1.18.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220404.173914`

In game: 
![image](https://user-images.githubusercontent.com/261005/169715230-07fd1154-535c-4f36-8a48-510ab2d1b95f.png)

Note Oracle 17 release version installed is 17.0.3.1 but screenshot says 17.0.3.

**Comment by xXPerditorXx** [comment]
I have the same Issue. The app just ignores it. In the FTB Forum is MultiMC as choice, but i cannot use it because someone is just too incompetent to add all versions to FTB Legacy, like FTB Revelation 3.6.0 or 3.5.0. They should just show it along with a Beta badge.
