### ISSUE TITLE
[Bug]: If i want to download a Modpack, than comes an Error

### ISSUE THREAD

**Issue by Maubinius** [FTBTeam/FTB-App#537]
### What Operating System

Windows 10

### App Version

202204211116-ac2e189d70-release

### UI Version

ac2e189d70

### Log Files

https://pste.ch/gapajiboza

### Debug Code

FTB-DBGALAGOHEKUY

### Describe the bug

If i want to download any Modpack, it comes an error.

### Steps to reproduce

1. Open the App
2. Start to download any Modpack
3. He makes a chop at the first few
4. Than comes a Error

### Expected behaviour

That he download the Modpack normaly...

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
duplicate of #479
