### ISSUE TITLE
Feature: Add a filter for Minecraft versions under the "Browse" section.

### ISSUE THREAD

**Issue by Akuma-U1** [FTBTeam/FTB-App#54]
It would be nice to be able to have a small filter to select modpacks based on MC version.

![image](https://user-images.githubusercontent.com/33059719/78423314-cf4e2180-7665-11ea-853c-4598841d4a2e.png)

**Comment by Jake-E** [comment]
The tag system should allow for searching of versions now, not sure this is needed now?
Thoughts @Gaz492?

**Comment by Gaz492** [comment]
Might be able to add popular tag bubbles/tags under the search bar to aid
in tag searching
