### ISSUE TITLE
[Bug]: severe issue with mod management. the val mod is not being replaced with newer one

### ISSUE THREAD

**Issue by CoryNB** [FTBTeam/FTB-App#540]
### What Operating System

Windows 10

### Debug Code

N/A

### Describe the bug

I just encountered the bug while launching the atm sky, 

### Steps to reproduce

![image](https://user-images.githubusercontent.com/94322419/167276253-79555010-de50-4f11-80dd-359a990ad698.png)
![image](https://user-images.githubusercontent.com/94322419/167276261-302d3f5b-16a4-4e4c-a589-9a589838b8b4.png)

### Expected behaviour

to be able to remove old mods so newer ones can be prioritzed during mod loading

### Screenshots

![image](https://user-images.githubusercontent.com/94322419/167276274-70e03f5e-bfe9-4dcd-863c-3549d718b975.png)

### Additional information

this was just recently encountered. so the ftb launcher didn't have any failsafe or controls for people to either remove or replace a mod that is old and needs to be updated

### Information

- [X] I have provided as much information as possible

**Comment by CoryNB** [comment]
this issue is related directly with modpack control from curseforge. check and see if you can remove mods from a modpack once it is installed.

**Comment by MichaelHillcox** [comment]
Closing: not an app issue
