### ISSUE TITLE
[Bug]: Illegal char <:> at index 9

### ISSUE THREAD

**Issue by Sn3akr** [FTBTeam/FTB-App#542]
### What Operating System

Windows 10

### App Version

202204211116-ac2e189d70-release

### UI Version

ac2e189d70

### Log Files

https://pste.ch/okidotomin

### Debug Code

FTB-DBGODEYEPENUZ

### Describe the bug

Attempting to install Valhelsia Enhanced Vanilla gives error

### Steps to reproduce

open FTB app, search for valhelsia 1.18 try and install - error

rinse and repeat.

### Expected behaviour

Expected it to install the pack, but i just get error, and nothing show up in instances

### Information

- [X] I have provided as much information as possible

**Comment by ThePaul-T** [comment]
Is this still happening?

**Comment by MichaelHillcox** [comment]
This has been resolved
