### ISSUE TITLE
[Bug]: Program can't run `javaw`

### ISSUE THREAD

**Issue by Ahlbin1983** [FTBTeam/FTB-App#544]
### What Operating System

Windows 10

### App Version

202204211116-ac2e189d70

### UI Version

ac2e189d70

### Log Files

https://pste.ch/adobeqiqor 

### Debug Code

FTB direwold20 1.18.2

### Describe the bug

i try to download the instance but it is starting and then it says oh no 

### Steps to reproduce

i just click on the instance and same issue is coming 

### Expected behaviour

i have cleared the catch and stuff like that dont know what more i can do

### Screenshots

![bug](https://user-images.githubusercontent.com/105601072/168484072-1775a1ac-b6b1-4217-a005-1f9bb4580941.jpg)

### Information

- [X] I have provided as much information as possible

**Comment by Ahlbin1983** [comment]
FTB-DBGKOMEQOJUPO

**Comment by Jake-E** [comment]
If you run into this issue on the latest version of the App, please re-open this issue.
