### ISSUE TITLE
[Bug]: Can't log in with microsoft

### ISSUE THREAD

**Issue by OffDeadPixel** [FTBTeam/FTB-App#545]
### What Operating System

Windows 10

### App Version

202204211116-ac2e189d70-release

### UI Version

ac2e189d70

### Debug Code

unknown

### Describe the bug

can't log with microsoft

### Steps to reproduce

1. go to the louncher
2. click login
3. select with microsoft
4. login to microsoft
5. something went wrong, unable to fetch profile from minecraft account.

newly bought the game.

### Expected behaviour

exptected to able to login 

### Information

- [X] I have provided as much information as possible

**Comment by ThePoshTux** [comment]
could be the issue with microsoft/mojang
https://twitter.com/MojangStatus/status/1526155959336423429

but unsure as this player has a fresh copy of the game, one to follow up once mojang stuff gets sorted.

**Comment by LordYuri2** [comment]
i am having the same trouble as that guy did.  an i had ftb app on my labtop before an didnt have this isusse.   FTB-DBGUMOSETUNIL       but then the when im online to do the long in its said im all set an longed in but the app still nothing an cant get the info.   thanks   jeff

**Comment by MichaelHillcox** [comment]
> i am having the same trouble as that guy did. an i had ftb app on my labtop before an didnt have this isusse. FTB-DBGUMOSETUNIL but then the when im online to do the long in its said im all set an longed in but the app still nothing an cant get the info. thanks jeff

This is saying your account doesn't exist, make sure you're using the correct Microsoft account that owns Minecraft: Java edition
