### ISSUE TITLE
[Bug]: Modpack installation error

### ISSUE THREAD

**Issue by foghagymatyi** [FTBTeam/FTB-App#547]
### What Operating System

Windows 10

### App Version

202204211116-ac2e189d70-release

### UI Version

ac2e189d70

### Log Files

https://pste.ch/etareyusuv

### Debug Code

FTB-DBGOTEBONEFAH

### Describe the bug

When i try to install and FTB modpack i get the following massage: Installation error.

### Steps to reproduce

1. I go to install modpack.
2. I select the version and press install again.
3. I get the error.

### Expected behaviour

The installation of the modpack.

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Duplicate of #479
