### ISSUE TITLE
[Bug]: Mac- Cannot get past "initialising install" 

### ISSUE THREAD

**Issue by luborkechelt** [FTBTeam/FTB-App#548]
### What Operating System

MacOS (Latest)

### Debug Code

didnt get code

### Describe the bug

Freezes on initialising install on all modpacks tried, 

### Steps to reproduce

Just use the application as instructed and try to download any modpack.

### Expected behaviour

Tried to download direwolf20 modpack for 1.18.2

### Additional information

I have never run this program before and this is the first time trying it, the program is not unresponsive, as I can click on the help '?' button, but it doesnt seem to be doing anything. It isnt putting any strain on my computer, it is just not doing anything. I am not getting an error message either.

### Information

- [X] I have provided as much information as possible

**Comment by luborkechelt** [comment]
Fixed the issue and brought up a new one. Changed something in the settings about using the beta version of something. But now I cannot create a new world, crashes just as I am about to spawn in, gives me error code 255, saying the ID and username cannot both be blank or something.

**Comment by MichaelHillcox** [comment]
Please run the debug tool
