### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kenk199** [FTBTeam/FTB-App#551]
### What Operating System

Windows 10

### App Version

202007161516-479dedc615-release

### UI Version

39f37b8d

### Log Files

Failed to download file.
Name: 1.18.2-forge-40.1.20.jar
URL: https://s3.amazonaws.com/Minecraft.Download/versions/1.18.2-forge-40.1.20/1.18.2-forge-40.1.20.jar
Filename on disk: 1.18.2-forge-40.1.20.jar
Path: C:\Users\ken\.ftba\bin\versions\1.18.2-forge-40.1.20\1.18.2-forge-40.1.20.jar
Exists: Nonexistent

### Debug Code

FTB-DBGCECUHIWANO

### Describe the bug

I am able to launch the Minecraft Launcher but I get that error when I hit play for the new Direwolf20 1.18 pack.

### Steps to reproduce

Click play on Direwolf20 1.18
Click play on the Minecraft launcher.

### Expected behaviour

I would be able to play the game.

### Additional information

something with file de

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Is this still happening?
