### ISSUE TITLE
[Bug]: Crash Landing modpack does not import correctly from CurseForge

### ISSUE THREAD

**Issue by peterix** [FTBTeam/FTB-App#553]
### What Operating System

Linux (Arch)

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Log Files

N/A

### Debug Code

The tool doesn't run for some reason.

### Describe the bug

Crash Landing does not import correctly, the API is not listing any of the separate mods it requires.

### Steps to reproduce

1. Try to download Crash Landing.
2. Try to run Crash Landing.
3. It breaks because it's missing Applied Energistics and likely many other mods...

### Expected behaviour

The pack works.

### Information

- [X] I have provided as much information as possible

**Comment by CoryNB** [comment]
this problem is a port over issue I have experienced with certain mods that existed longer than the new ftb launcher.

**Comment by MichaelHillcox** [comment]
https://dist.creeper.host/FTB2/cdn/app/ftbdbg/ftb-debug-linux-static 

Can you try this one as we'll need the logs to see what's going on here

**Comment by ThePaul-T** [comment]
Should be resolved, older manifest versions where not supported until the update yesterday.
