### ISSUE TITLE
[Bug]: Curseforge ATM7 missing changelog

### ISSUE THREAD

**Issue by jerry1333** [FTBTeam/FTB-App#556]
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Debug Code

FTB-DBGEPUJEGARUQ

### Describe the bug

App doesn't show pack changelog

### Steps to reproduce

1. Install ATM7 modpack (https://www.curseforge.com/minecraft/modpacks/all-the-mods-7)
2. Click on Versions button

### Expected behaviour

Show changelog visible on curseforge website

### Screenshots

![image](https://user-images.githubusercontent.com/984193/169586657-d4a7afe5-636f-44b4-8130-9515cc435cab.png)
![image](https://user-images.githubusercontent.com/984193/169586718-afe822cc-e1e5-4c32-9b90-7b60d0e774eb.png)

### Information

- [X] I have provided as much information as possible

**Comment by CoryNB** [comment]
I have been experiencing this as well. the team needs to contact curse forge or try and get the list of mod updates/changes/addition/removals for it between each version.

**Comment by ThePaul-T** [comment]
API has never supported curseforge change logs, I may add that in a later update.
