### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Earthdragons** [FTBTeam/FTB-App#559]
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Log Files

something

### Debug Code

FTB-DBGRULEQAWENU

### Describe the bug

cant sign into my account

### Steps to reproduce

ftb app
click to sign in
sign in to Microsoft account 
close the browser

### Expected behaviour

to be able to sign into ftb app 

### Screenshots

![bug](https://user-images.githubusercontent.com/105172225/169655752-33624d4e-9639-44b7-a409-2cd634f60100.png)

### Information

- [X] I have provided as much information as possible

**Comment by alybloodshade** [comment]
I have that problem too.  I tried calling xbox, who transferred me to microsoft, who hung up on me, and then I called xbox again and they looked into it further and said it's on Mojangs end but after awhile I was able to access Minecraft normally and still can't log in to FTB!

**Comment by MichaelHillcox** [comment]
The microsoft account you're trying to use does not have Minecraft: Java edition

I'm going to close this for now but if you need more help, please feel free to ask for help in our discord https://go.ftb.team/discord
