### ISSUE TITLE
[Bug]: Cannot use app, error on launch, will not connect.

### ISSUE THREAD

**Issue by kamodius** [FTBTeam/FTB-App#561]
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Debug Code

FTB-DBGEYESOCIFUR

### Describe the bug

App cannot connect on launch

### Steps to reproduce

1. Launch app
2. "Oh... This is a bit awkward" error appears, currently on Reconnect tries: 77
3. Wait.

### Expected behaviour

Expect to launch normally and arrive at main menu.

### Screenshots

![image](https://user-images.githubusercontent.com/35677803/169834857-d3d7e5b3-266f-4895-a815-4bb2fdaf568d.png)

### Additional information

Have reinstalled the app in Overwolf and reinstalled Overwolf.  Rebooted.  Disabled firewall/antivirus temporarily and asked for help about 12 hours ago on Discord.

### Information

- [X] I have provided as much information as possible

**Comment by kamodius** [comment]
Had in the course of trying to make a localhost server work used _JAVA_OPTIONS -Xmx8192 -Xms2048 environmental variable in Windows and this apparently breaks the app.  Thanks to @Mikey for the help.

**Comment by mikey** [comment]
@kamodius wrong @mikey

**Comment by kamodius** [comment]
> @kamodius wrong @mikey

My bad, sorry about that!
