### ISSUE TITLE
[Bug]: Install Error Project ozone 2

### ISSUE THREAD

**Issue by kanduu92** [FTBTeam/FTB-App#562]
### What Operating System

Windows 10

### App Version

1.2.3

### UI Version

14abefffbf

### Log Files

https://pste.ch/uxufolayop

### Debug Code

FTB-DBGOYIPAREGAJ

### Describe the bug

FTB-DBGOYIPAREGAJ

### Steps to reproduce

Go to Browse search ozone on curse packs.
press get on project ozone 2
Press install.
Then its going to download the mods and when that finishes it gives an install error.

### Expected behaviour

that the launcher installs the pack

### Additional information

Project ozone 3 installs just fine.
and my other modpacks are playable to

### Information

- [X] I have provided as much information as possible

**Comment by kanduu92** [comment]
Describe the bug: that it not installs project ozone 2. and get an install error.

**Comment by CoryNB** [comment]
if it is an older mod, then it might not have been ported over sucessfully from the original classic ftb launcher or curseforge. Please check between the old and new version of ftb and curseforge to find what could of gone wrong.

**Comment by MichaelHillcox** [comment]
Closing as I've been made aware that the systems behind these features have been completely reworked. Please open a new issue if you're still having issues
