### ISSUE TITLE
[Bug]: Modded pokemon pixelmon server IP add/remove funtion for modpacks

### ISSUE THREAD

**Issue by CoryNB** [FTBTeam/FTB-App#564]
### What Operating System

Windows 10

### App Version

202204211116-ac2e189d70-release

### UI Version

ac2e189d70

### Debug Code

 FTB-DBGEMACAYENUK

### Describe the bug

i wanted to add my own IP as a server hosting an instance of modded minecraft of any profile from ftb to curseforge within the ftb launcher

### Steps to reproduce

This was the method I found within the ftb app to find public servers,
first if you don't have any modp[acks installed in ftb launcher, go look through browse. 
2nd, click the ftb or next to ftb image icon is curseforge icon, then type what modpack your looking for.
3rd, download the modpack latest version. 
4th wait untill instance is fully downloaded before clicking view mod-pack/instance. 
5th, click libary, then click the most recently download modpack.
6th. click public servers, and wait for it to download. 
the process of adding my own IP for a server to play with everyone publicly without any server side plugins. please allow people to share their ip if they want to find people entering their own games remotely.

### Expected behaviour

To be able to find my IP and copy it for use with the ftb launcher so others can find my live game

### Screenshots

![image](https://user-images.githubusercontent.com/94322419/169906915-a78c931f-966f-4463-9afd-06cdbefa0c75.png)
 

### Additional information

I noticed there was no server ip listed in google search for public modded servers for certain mod-packs, as there appears to be a recent calamity from 2b2t hacks that thrown a wrench in finding a working server.

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Unfortunately, this isn't how this works, the servers listed there are part of the Creeperhost / Minetogether systems
