### ISSUE TITLE
[Feature request] adding an option to publicly release your ip for players to join your world.

### ISSUE THREAD

**Issue by CoryNB** [FTBTeam/FTB-App#565]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
TO have a ftb dedicated list for mod-packs of IP for server/client players to share between friends.
**Describe alternatives you've considered**

**Additional context**
Please allow people to pinpoint their address if possible so others know where it is found.

**Comment by MichaelHillcox** [comment]
This won't be part of the app but from my understanding, Minetogether Connect can do this
