### ISSUE TITLE
APP will not fully open [Bug]: 

### ISSUE THREAD

**Issue by KittenPunkGamer** [FTBTeam/FTB-App#567]
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Debug Code

FTB-DBGJEGURIGANU

### Describe the bug

app wont fully open.

### Steps to reproduce

1 click to open app
2 watch it fail to fully open.
3 cry

### Expected behaviour

i would like it to fully open so i can then click what mod i want to play and you know play it.... with friends

### Screenshots

![lifesucks](https://user-images.githubusercontent.com/106158875/170032421-ab23bf1a-6979-42db-9007-2170955a709a.png)
![still sucks](https://user-images.githubusercontent.com/106158875/170032444-bc2434dc-e9a1-4e6f-b8a9-899d76387c6a.png)

### Additional information

  i have tried uninstalling it and even overwolf. then clearing the cash, then rebooting computer... then reinstalling it from the newest update on tfb website... it installs.  i click to lanch.... it fails to open....
  
   nothing worked.
   please help

### Information

- [X] I have provided as much information as possible

**Comment by CoryNB** [comment]
what is your cpu? windows 11 is now supported for ftb launcher. use curseforge first before opening ftb

**Comment by MichaelHillcox** [comment]
Caused by `_JAVA_OPTIONS` please remove that key from your environment variables. Although, this should be fixed as of the latest update to the app
