### ISSUE TITLE
new version wont download

### ISSUE THREAD

**Issue by rbcxassassin** [FTBTeam/FTB-App#57]
Every time i try to download the new version of the launcher it downloads FTBA_Windows-64x_1_0_3.exe and even when i have this version it wont even give me the setup guide. what do i do?

**Comment by Sunekaer** [comment]
I just downloaded the app from our website and it downloads 1.0.5, could you test again?

**Comment by rbcxassassin** [comment]
It is still giving me 1.0.3

**Comment by rbcxassassin** [comment]
when i go to try to open the app it installs the file then it says the setup will tell me what to do then closes and nothing happens.

**Comment by Sunekaer** [comment]
Okay so you have installed it, and what happens when you go to start and opens FTB App?

**Comment by rbcxassassin** [comment]
When i go to open the app it goes through the download procedure then it does nothing

**Comment by Sunekaer** [comment]
Could you upload your logs please?
They are in the folder where you installed the app

**Comment by rbcxassassin** [comment]
[launcher_log.txt](https://github.com/FTBTeam/FTB-App/files/4432713/launcher_log.txt)

**Comment by rbcxassassin** [comment]
is this it?

**Comment by Rushmead** [comment]
Please see this issue for how to get the logs [#44 (Comment)](https://github.com/FTBTeam/FTB-App/issues/44#issuecomment-609026147)

**Comment by rbcxassassin** [comment]
[i4j_nlog_1.log](https://github.com/FTBTeam/FTB-App/files/4432732/i4j_nlog_1.log)
[i4j_log_FTBA_8427670721916638457.log](https://github.com/FTBTeam/FTB-App/files/4432735/i4j_log_FTBA_8427670721916638457.log)

**Comment by Jake-E** [comment]
Can you try this version of the installer:
https://apps.modpacks.ch/FTBApp/release/1.0.5/FTBA_windows-x64_1_0_5.exe

**Comment by Jake-E** [comment]
Closing, please continue feedback in #44.
