### ISSUE TITLE
[Bug]: FTB Mod packs not launching

### ISSUE THREAD

**Issue by zoozoo121** [FTBTeam/FTB-App#570]
### What Operating System

Windows 10

### Debug Code

FTB-DBGIMAQUFEWUS

### Describe the bug

When I downloaded the new beta (3.6.0) the game was working fine. However after joining my friends server, the game crashed after 10 minutes and everyone time I try to reopen the game, it says validating assests and then closes the log and doesnt start the game. If tried deleting the mod pack and the downgraded aswell but nothing changes.

### Steps to reproduce

1. Run the app like normal and try to load up FTB Revelation

### Expected behaviour

It wont load the game or any mods, it will only show validating assets and a couple other small things.

### Information

- [X] I have provided as much information as possible

**Comment by CoryNB** [comment]
I don't know what could go wrong. the GPU needs to have more than 4gb of ram and the ram needed in game must be greater than 30gb for uncompressed game-play. have you updated it, or got curse-forge? that works as a bypass.

**Comment by zoozoo121** [comment]
I fixed the issue. My GPU drivers were just out of date. It worked after updating them. Thank you.
