### ISSUE TITLE
[Bug]: Crashes kernel on linux

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-App#571]
### What Operating System

Linux (Arch)

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-App/files/8775324/latest.log)

### Debug Code

FTB-DBGLIFIGENOFO

### Describe the bug

FTB app crashes linux kernel quietly

### Steps to reproduce

1. Attempt to launch the Direwolf20 1.18 pack
2. wait less than 2 minutes
3. notice that your PC has completely shut down.

### Expected behaviour

I expect the app to not crash the kernel.

### Information

- [X] I have provided as much information as possible

**Comment by ChristopherJTrent** [comment]
> Hay, thanks for the issue! Unfortunately it looks like you've not provided a `Debug code`... We require this as it helps us find your issue as quickly as possible.
> ## Please do the following
> 
> Please use the link below to download and run the FTB Debug tool. This is a tool built by our App Developers and will provide you a code that you need to attach to this issue. Please either edit your original issue or add a comment with this code.
> 
> [Windows](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe) // [MacOS](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos) // [Linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux)

This tool is nonfunctional on linux.

**Comment by ChristopherJTrent** [comment]
> 

Ugh, thanks in no part to any of your documentation, here's the fucking code.
FTB-DBGLIFIGENOFO

**Comment by ChristopherJTrent** [comment]
OK, after extensive debugging, I was able to narrow down the problem.
on Manjaro Linux, the launcher will crash to shutdown if MUSL isn't installed. No log message is generated, and no system logs are created either. 

Potential fixes:
Add a dependency check to the install shell script
Allow use of other glibc providers
Have launcher crash with an error and log if musl and other dependencies aren't installed.

**Comment by MichaelHillcox** [comment]
Hey, sorry for the lack of response with this issue. I understand that this must be super annoying. We've recently shipped an Electron Only version of our app that no longer uses `install4j` which we found was causing most of the issues for linux users. You can find this new version on our website (https://feed-the-beast.com/ftb-app). Could you let me know if this resolves your issue?
