### ISSUE TITLE
[Bug]: Game and App crashes at seemingly random times, all modpacks.

### ISSUE THREAD

**Issue by NovaCrypt** [FTBTeam/FTB-App#572]
### What Operating System

Linux (Debian)

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Log Files

[error.log](https://github.com/FTBTeam/FTB-App/files/8778165/error.log)

### Debug Code

Tool won't run... I tried GUI & terminal, neither ran.

### Describe the bug

When playing any modpack through the launcher, I get anywhere between 10 minutes and 2 hours of play time before both minecraft and the app crash to desktop. Aside from looking for the error.log in the FTBApp directory, I receive no minecraft error log that I can find in the instance directory.

### Steps to reproduce

1. Open a mod-pack on Ubuntu 22.04
2. Play in a world for 10 minutes - 2 hours
3. Game and app will crash to desktop without warning or explanation.

### Expected behaviour

I would expect to be able to play any of the minecraft modpacks without having the FTB app crash itself and minecraft to the linux desktop.

### Information

- [X] I have provided as much information as possible

**Comment by ChristopherJTrent** [comment]
> ### Debug Code
> 
> Tool won't run... I tried GUI & terminal, neither ran.

The devs haven't marked it as such, but this is a known issue with the debug tool on linux. Make sure that you have `musl` installed. FTBA and the debug tool are both linked against that non-standard version of libc, which doesn't come preinstalled on most linux distros.a

Musl is on APT, usual recommendation to double check anything anyone tells you to install.

**Comment by MichaelHillcox** [comment]
Please can you attach a debug code to the issue, this version of the tool should work correctly https://dist.creeper.host/FTB2/cdn/app/ftbdbg/ftb-debug-linux-static 

I need to update the github app to show more links for dynamic and staticly linked versions of the app. Hopefully this one works properly
