### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SirBecalo** [FTBTeam/FTB-App#574]
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Debug Code

FTB-DBGTECILELOSU 

### Describe the bug

server setup guide link needs to be updated

### Steps to reproduce

open ftb app
on the right section where helpful links are listed, click on "server setup guide"
observe that this guide is outdated for newer versions, with the new guide living at [feedthebeast nortonsite new guide](https://feedthebeast.notion.site/Installing-a-Feed-the-Beast-Server-aeaea8a7220945d0ad0357c80c6c9d12) that includes old steps for legacy, but newer steps for newer verisons

### Expected behaviour

to launch the newest most relevant guide

### Additional information

this is inconvenient since most players are used to setting the server a specific way, (through start.bat and through forge jar.)

lots of confusion occurs due to the requirements of java 17, no mention of needing to use run.bat instead of start.bat, and the lack of any idea what "insert jar here" is in start.bat.

these are minor issues that compound, since i figured out insert jar here would be the jar, but lost lots of time troubleshooting why forge jar deletes itself.

even worse, when you execute start.bat, there is a high chance you'll get a java compile error " Unsupported major.minor version  <blah blah>" due to the need for java 17, but that is hard to figure out on your own when java's website recommends to use java8 because its the "latest"

these combined errors make it a nightmare to even know if you are doing anything right or not.

### Information

- [X] I have provided as much information as possible

**Comment by SirBecalo** [comment]
note that usually players needed to update the JRE, not the JDK.

**Comment by MichaelHillcox** [comment]
This is the most up to date guide we have for the server installer. Our server installer binary has been updated to manage the java complications for you now and from what I understand, the start.sh/bat is still the correct one.

Closing as this isn't really an app issue
