### ISSUE TITLE
[Bug]: FTB refuses to open/connect

### ISSUE THREAD

**Issue by Gremory-Lost** [FTBTeam/FTB-App#575]
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Debug Code

FTB-DBGVIMOXURUPU

### Describe the bug

FTB App seems to refuse to connect to the internet/server

### Steps to reproduce

1. Download FTB App from Overwolf
2. Launch FTB
3. Reach page with two buttons: Report Issue and Quit

### Expected behaviour

To sit on that page and keep trying to reconnect

### Screenshots

![FTB Screenshot](https://user-images.githubusercontent.com/34218752/170793406-df57ae0d-3d4e-4bf1-bf32-0d6b7eda6611.PNG)

### Additional information

I have uninstalled and reinstalled FTB and Overwolf multiple times. I have gone through and tried downloading it all with my firewall off, removed my java server line from windows environment variables, and even gone through and deleted everything FTB related in  %appdata%. At this point I don't know what the issue is. 

### Information

- [X] I have provided as much information as possible

**Comment by CoryNB** [comment]
I am using a windows 11 version that works with ftb launcher. it didn't like the beat when it was first rolled out.

**Comment by aaminy** [comment]
I am also having this issue on Windows 10. I have attempted a reinstall with no success.

**Comment by MichaelHillcox** [comment]
Although this should now be fixed as of the latest version of the app. You can double confirm the fix by removing `_JAVA_OPTIONS` from your system env vars
