### ISSUE TITLE
[Bug]: click play game quickly opens window then closes

### ISSUE THREAD

**Issue by Flubberrass101** [FTBTeam/FTB-App#576]
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Log Files

[2022-05-28-1.log](https://github.com/FTBTeam/FTB-App/files/8793047/2022-05-28-1.log)
[debug-1.log](https://github.com/FTBTeam/FTB-App/files/8793084/debug-1.log)

### Debug Code

FTB-DBGOMECIJOXAN

### Describe the bug

click play start running then window opens and closes. 

### Steps to reproduce

1. open ftb launcher
2. download any 1.18.2 modpack
3. click play button
4. start launching 

### Expected behaviour

the modpack running and play the game

### Information

- [X] I have provided as much information as possible

**Comment by spriiieeet** [comment]
Hi there. Had the same problem i think. I've updated my amd driver to AMD software: Adrenaline version 22.5.2. Seems to work now. Hope it does for you too.

**Comment by MichaelHillcox** [comment]
Hi, this is intended behaviour. If the game does not launch once the log starts to slow down, you can use the little Eye icon on the right of the logs area to force show the game :+1: hope this helps
