### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ThatGuyFishy** [FTBTeam/FTB-App#577]
### What Operating System

Linux (Other)

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Log Files

https://pste.ch/ekuzizotos

### Debug Code

N/A

### Describe the bug

can't install 

### Steps to reproduce

attempt to install modpacks in current stable release with no success

### Expected behaviour

app gets stuck at "Prepare installation"

### Additional information

the issue is fixed on the beta release, but but packs won't launch with Mojang error code 1

### Information

- [X] I have provided as much information as possible

**Comment by ThatGuyFishy** [comment]
the debug tool won't launch on opensuse tumbleweed 20220525

**Comment by MichaelHillcox** [comment]
https://dist.creeper.host/FTB2/cdn/app/ftbdbg/ftb-debug-linux-static

Please try this version
