### ISSUE TITLE
[Bug]: Version selector has wrong proportions

### ISSUE THREAD

**Issue by RaeTheGit** [FTBTeam/FTB-App#578]
### What Operating System

Linux (Debian)

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Debug Code

FTB-debugger-cannot-be-executed

### Describe the bug

When Choosing e-g- the ATM7 pack from Curseforge for installation, the version information is cut off in the dropdown list

### Steps to reproduce

1. Open app, click on magnifying glass, select CurseForge symbol, search for 'atm7'
2. Click on the result and select install button
3. Open the dropdown menu to look at available releases

App window size also has no influence on the dimensions of that list.

### Expected behaviour

Either the dropdown list is sized to fit its content, or the font is scaled to fit, or I at least get a tooltip when hovering over an entry to see its full text.

### Screenshots

![image](https://user-images.githubusercontent.com/65011289/170888772-3ac2ca0e-43b8-448a-bbf5-e51f88e02a5b.png)

### Information

- [X] I have provided as much information as possible

**Comment by RaeTheGit** [comment]
The debug tool cannot be executed, see attached screenshot
![image](https://user-images.githubusercontent.com/65011289/170889144-68aa31a6-bc73-41c1-99d0-300e7f31859a.png)

**Comment by ChristopherJTrent** [comment]
@RaeTheGit This is a known issue. the debug tool is linked against Musl instead of a more common glibc provider. You can install it from APT. Usual recommendations to double check anything that someone on the internet tells you to install.
If you want to check for yourself which version it's linked to, you can also run `ldd ./ftb-debug-linux`

**Comment by MichaelHillcox** [comment]
https://dist.creeper.host/FTB2/cdn/app/ftbdbg/ftb-debug-linux-static

Please run this version. Although I don't really need it, I'm gunna go make that box bigger now :D
