### ISSUE TITLE
[Bug]: FTB App is Intel app on Mac and cannot be opened due to unable to check it for malware/virus!

### ISSUE THREAD

**Issue by WillRRRR** [FTBTeam/FTB-App#579]
### What Operating System

MacOS (Latest)

### Debug Code

No code given

### Describe the bug

Not able to open app

### Steps to reproduce

1. Download FTB App on MacBook Pro 16" 2021
2. Open FTB App and unable to be opened
3. Apple cannot check FTB app for malware/virus!
4. FTB App is not optimized for Apple Silicon!

### Expected behaviour

Unable to open app

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
settings -> security -> general -> open app
