### ISSUE TITLE
Making servers on the new launcher

### ISSUE THREAD

**Issue by Simtoko** [FTBTeam/FTB-App#58]
I Just installed the new launcher for FTB and wanted to make a server for me and my two friends and everything went ok. The only problem is that I can't seem to find the place where you give the server more ram because it feels like it needs more (avg tick time is ca. 6ms). I answer the EULA and ran the forge universal thingy but I feel I did something wrong. Maybe jumped over a step or something. How do you exactly make a server from the new launcher?

**Comment by Rushmead** [comment]
You should be running the start script that is included with the server, if you're running windows that'll be the start.bat or on Linux start.sh. To add more memory you can increase the "-Xmx8092M" number inside the start script.
