### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kaiakrystal** [FTBTeam/FTB-App#580]
### What Operating System

Linux (Debian)

### App Version

FTBA_unix_202205171618-14abefffbf-release

### Log Files

There was a problem opening the file "/home/.../FTB/FTBA_unix_202205171618-14abefffbf-release.sh".
The file you opened has some invalid characters. If you continue editing this file you oculd corrupt this document.
You can also choose another character encoding and try again.
Character encoding: Current Locale (UFT-8)

### Debug Code

do not know how to run the tool

### Describe the bug

i double click the .sh file and the above is what happens.

### Steps to reproduce

1. on Pop!_OS (ubuntu)
2. Download folder
3. double click on the .sh folder
4. wait for file to load
5. program freezes or lags

### Expected behaviour

not sure

### Screenshots

https://i.imgur.com/rkPlHkx.png 

### Information

- [X] I have provided as much information as possible

**Comment by kaiakrystal** [comment]
I tries to open the Debugger, but I don't know what program to use to open the Linux version.

**Comment by MichaelHillcox** [comment]
Please see #536
