### ISSUE TITLE
[Bug]: I updated Direwolf20 Modpack and now can't run instance. Get error saying it can't verify my account.

### ISSUE THREAD

**Issue by Thaivias** [FTBTeam/FTB-App#582]
### What Operating System

Windows 10

### Debug Code

FTB-DBGAJEJUFIQIW

### Describe the bug

[Bug]: I updated Direwolf20 Modpack and now can't run instance. Get error saying it can't verify my account.

### Steps to reproduce

Not sure how you can reproduce what I can't do. Sorry

### Expected behaviour

[Bug]: I updated Direwolf20 Modpack and now can't run instance. Get error saying it can't verify my account.

### Information

- [X] I have provided as much information as possible

**Comment by Thaivias** [comment]
I have tried re-logging in on Overwolf and FTB but nothing new happens

**Comment by MichaelHillcox** [comment]
Can you could if this still happens or not?
