### ISSUE TITLE
[Bug]:  not starten direwolf20 up also minecraft

### ISSUE THREAD

**Issue by kom30** [FTBTeam/FTB-App#583]
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-App/files/8805749/latest.log)

### Debug Code

FTB-DBGPOQAXEBOHE

### Describe the bug

not starten minecraft

### Steps to reproduce

Cant

### Expected behaviour

the startede

### Information

- [X] I have provided as much information as possible

**Comment by kom30** [comment]
FTB-DBGPOQAXEBOHE

**Comment by kom30** [comment]
> Hay, thanks for the issue! Unfortunately it looks like you've not provided a `Debug code`... We require this as it helps us find your issue as quickly as possible.
> ## Please do the following
> 
> Please use the link below to download and run the FTB Debug tool. This is a tool built by our App Developers and will provide you a code that you need to attach to this issue. Please either edit your original issue or add a comment with this code.
> 
> [Windows](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe) // [MacOS](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos) // [Linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux)

FTB-DBGPOQAXEBOHE

**Comment by kom30** [comment]
> ### What Operating System
> 
> Windows 10
> ### App Version
> 
> 202205171618-14abefffbf-release
> ### UI Version
> 
> 14abefffbf
> ### Log Files
> 
> [latest.log](https://github.com/FTBTeam/FTB-App/files/8805749/latest.log)
> ### Debug Code
> 
> FTB-DBGPOQAXEBOHE
> ### Describe the bug
> 
> not starten minecraft
> ### Steps to reproduce
> 
> Cant
> ### Expected behaviour
> 
> the startede
> ### Screenshots
> 
> _No response_
> ### Additional information
> 
> _No response_
> ### Information
> 
>     * [x]  I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
We'll be shipping an update around this to give some better logging. Can you confirm if this is still an issue

**Comment by kom30** [comment]
it has ben fix thx for the help

**Comment by MichaelHillcox** [comment]
Awesome!
