### ISSUE TITLE
Having an issue logging in to my minecraft account on the FTB app

### ISSUE THREAD

**Issue by TheGodfather6671** [FTBTeam/FTB-App#584]
Im having an issue logging into my minecraft account on the FTB app. Tried logging in via mojang, and it said migrated (which makes sense since i did migrate my account). Tried with Microsoft, (since i migrated my account), and it said failed, even though i made sure it was the right account information. It says something went wrong and its unable to fetch profile from minecraft account (no id found). But i logged into the minecraft with the same account information that i tried on the app. Im not sure how to fix it or how it works... Ive run minecraft multiple times through the official launcher and its still not working
<img width="581" alt="Screen Shot 2022-05-31 at 10 52 50 PM" src="https://user-images.githubusercontent.com/106641588/171318420-1b53f7e4-0b7f-4d31-924b-a5610376aed9.png">
.

**Comment by BlueRyno** [comment]
Same here. The browser window seems successful, but I get the same error in the app. Looking at the log, requests to https://api.minecraftservices.com/minecraft/profile return a 404 for me.

**Comment by MichaelHillcox** [comment]
If it returns a 404, you don't have a `Minecraft: Java Edition account` this likely means you have the Minecraft Bedrock edition or you've used the wrong Microsoft account.

That goes for everyone in this issue.

**Comment by Valentine-petrichor** [comment]
> If it returns a 404, you don't have a `Minecraft: Java Edition account` this likely means you have the Minecraft Bedrock edition or you've used the wrong Microsoft account.
> 
> That goes for everyone in this issue.

so you're saying we have to stick to a mojang account to use FTB ?

**Comment by MichaelHillcox** [comment]
No. I'm saying your Microsoft account has to own Minecraft: Java editon, be it from a migrated mojang account or you having bought the game with your Microsoft account

**Comment by BlueRyno** [comment]
> If it returns a 404, you don't have a `Minecraft: Java Edition account` this likely means you have the Minecraft Bedrock edition or you've used the wrong Microsoft account.
> 
> That goes for everyone in this issue.

Thanks Michael! I feel like an idiot, but that was it. I have 2 Microsoft accounts and I was using the wrong sign in. Thanks again!

**Comment by OliverKarger** [comment]
I'v had the same issue, i forgot the set a Profile ID after i purchased Minecraft: Java Edition. When i set the ID, it worked.
