### ISSUE TITLE
[Bug]: pop-up does not appear when clicking button to sign in with Microsoft accoutn

### ISSUE THREAD

**Issue by LLCoolClay** [FTBTeam/FTB-App#585]
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Log Files

https://pste.ch/eravoqabiy

### Debug Code

FTB-DBGCEWIFAXAQU

### Describe the bug

No Pop Up to Sign In Can't sign into account to launch mod

### Steps to reproduce

1.  click 'Play' button on mod
2. Minecraft Login window pops up with two buttons, "Microsoft" or "Mojang"
3. Click "Microsoft" button
4. 'Waiting for response...' window pops up and at bottom it says 'A window should have just popped up. Follow the instructions on the screen, once you've finished, you'll see that you've been signed in here."
5. Issue: No pop-up window to be found. So can't proceed from here.

### Expected behaviour

Expected Pop-up window to appear

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
You can manually navigate to https://msauth.feed-the-beast.com if no window pops up, this tends to be an issue with your browser being odd... Just make sure you only navigate to the URL whilst you can see the "waiting for response" screen

**Comment by LLCoolClay** [comment]
That worked. Thanks for your help
