### ISSUE TITLE
[Bug]: cannot download modpacks

### ISSUE THREAD

**Issue by CSCTACG** [FTBTeam/FTB-App#587]
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Debug Code

FTB-DBGPUGIBUTUBI

### Describe the bug

cannot download modpacks

### Steps to reproduce

Select a modpack, click "Get", click "Install", after "Prepare installation" done, the download progress will be stuck.

### Expected behaviour

I just want to play ftb modpacks.

### Screenshots

![image](https://user-images.githubusercontent.com/82568154/171560519-aa903e26-ba87-4b51-91db-588342a03ce2.png)

### Additional information

Is it because curseforge has replaced the new API that the download of modpacks cannot be completed?

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Looks like the debug tool was run after an app restart. Please run the debug tool after you've had the issue on the app but without restarting or stopping the app. Many thanks

**Comment by JoeNoIce** [comment]
i am having the same issue as well.

**Comment by JoeNoIce** [comment]
ok i fixed it by changing instance download location

**Comment by MichaelHillcox** [comment]
You're running a pretty outdated version of the app, please update the app and see if this is still an issue. If it is, please create a new issue with an updated debug code

**Comment by JoeNoIce** [comment]
I was running the latest version

**Comment by MichaelHillcox** [comment]
The screenshot and version number in the original report would infer otherwise. Our install screen no longer looks like that, could you double check you're on the latest version 

You can run the debug tool again and I can verify if you're running the latest version :)

**Comment by JoeNoIce** [comment]
i fixed the problem by changing the instance install location. thats why i
forgot about the bug post.
