### ISSUE TITLE
[Bug]: I cannot open FTB Stoneblock 2 game with FTB app

### ISSUE THREAD

**Issue by newspa1** [FTBTeam/FTB-App#588]
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Debug Code

FTB-DBGQEWASAMEWE

### Describe the bug

I cannot open Stoneblock 2 game.Like the view of the screenshot.It had a ringbell voice,but it didn't open the game.

### Steps to reproduce

I don't no what this step mean

### Expected behaviour

Did anyone ever encountered this? Can someone tell me what happened and how to fix it?Thanks.

### Screenshots

![image](https://user-images.githubusercontent.com/106799070/171798457-884017de-4621-4b60-b441-4b393aab5657.png)

### Information

- [X] I have provided as much information as possible

**Comment by sisyamo2236** [comment]
i am having the same issue as well.

**Comment by baspoldervaart** [comment]
I'm having the same issue aswell. It keeps stuck at "Finished Aspect ItemStack Thread." 
![image](https://user-images.githubusercontent.com/20210668/171807457-29537aa8-2492-4b0d-a6d3-965e28add89b.png)

**Comment by newspa1** [comment]
So sad. Maybe we should wait for official application.TT

**Comment by mixd304** [comment]
I got the same problem but in FTB Revelation 3.5.0

**Comment by newspa1** [comment]
Oh,mine is working now,too.

**Comment by MichaelHillcox** [comment]
Anyone that's having this issue, please try again, it may have been fixed in a recent update
