### ISSUE TITLE
[Bug]: ftb interactions 開けません

### ISSUE THREAD

**Issue by imoimo6038** [FTBTeam/FTB-App#589]
### What Operating System

Windows 10

### App Version

ftb interactions　2.12.1

### UI Version

1.2.3

### Debug Code

FTB-DBGCOSIBEDESE

### Describe the bug

止まる

### Steps to reproduce

プレイ実行　ロード中８０％から進まない

### Expected behaviour

へるぷ

### Screenshots

![スクリーンショット 2022-06-03 160927](https://user-images.githubusercontent.com/106801334/171805350-78b4f538-c19c-4910-94d9-72b323ec5ae4.png)

### Additional information

昨日までできていたのに。今日プレイしようとしたらできなくなりました。

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Hmm, I think this may have been fixed, could you confirm if this is still an issue, sorry for the slow reply
