### ISSUE TITLE
Add a way to type in amount of RAM

### ISSUE THREAD

**Issue by RoyalReject** [FTBTeam/FTB-App#59]
Cant get it set exactly to what i want, allow to type in amount or disable slider and only use arguments

**Comment by Jake-E** [comment]
You can edit the instance.json manually to set custom RAM amounts.

**Comment by hayestalb** [comment]
Where is the slider? How can I find it?

**Comment by Jake-E** [comment]
@hayestalb You can find the slider under the Settings section of each instance (click the ... when hovering over the pack).
