### ISSUE TITLE
i cant download RAD (Roguelike Adventure and Dungeons)

### ISSUE THREAD

**Issue by flobig2001** [FTBTeam/FTB-App#590]
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Log Files

https://pste.ch/suyesuwihi

### Debug Code

FTB-DBGEKEDOLEKIG

### Describe the bug

i cant download RAD (Roguelike Adventure and Dungeons)

### Steps to reproduce

1. i start the launcher
2. i search for RAD
3. i try to install any off the versions
4. modpack install Failure

### Expected behaviour

i can download and play the modpack with friends

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
We've released an update recently that should have solved this, please retry, let me know if it's not working
