### ISSUE TITLE
direwolf20 1.18 wont start up

### ISSUE THREAD

**Issue by Stacio69** [FTBTeam/FTB-App#591]
hi
i have installed ftb app, installed direwolf20 1.18 latest mod pack
wont load, only goes to last line "dispatching module FIRST_CLIENT_TICK  does not load past that, have uninstalled and restarted several times but dont go past

ftb-debug gives the following code FTB-DBGDOKEYUZIJ
please help
![Screenshot 2022-06-04 170733](https://user-images.githubusercontent.com/106877991/172010484-11bc7615-98a8-429f-8acf-b389e0982a2c.png)
![Screenshot 2022-06-04 170756](https://user-images.githubusercontent.com/106877991/172010487-93160ce0-123e-454c-a261-ac74d03156e0.png)
I

**Comment by Senbotsu81** [comment]
I have having the same issue, has anyone found a fix for it?

**Comment by Stacio69** [comment]
Not that I know off, are you using windows 11? Because that's now the only thing I can think off that might be the issueSent from my Galaxy
-------- Original message --------From: Senbotsu81 ***@***.***> Date: 2022/07/17  20:54  (GMT+02:00) To: FTBTeam/FTB-App ***@***.***> Cc: Stacio69 ***@***.***>, Author ***@***.***> Subject: Re: [FTBTeam/FTB-App] direwolf20 1.18 wont start up (Issue #591) 
I have having the same issue, has anyone found a fix for it?

**Comment by Dr69onS6mur6i** [comment]
I'm still in Win 10. Unless Windows decided to update to 11 behind my back after being told not to.

I ended up switching launchers to GD Launcher and that's been working fine for me since.

**Comment by MichaelHillcox** [comment]
We've attempted to fix this, could you confirm if this is still an issue?

**Comment by Stacio69** [comment]
Awesome thanksI can confirm it's working now. Thanks a lotSent from my Galaxy
-------- Original message --------From: Michael Hillcox ***@***.***> Date: 2022/07/24  16:52  (GMT+02:00) To: FTBTeam/FTB-App ***@***.***> Cc: Stacio69 ***@***.***>, Author ***@***.***> Subject: Re: [FTBTeam/FTB-App] direwolf20 1.18 wont start up (Issue #591) 
We've attempted to fix this, could you confirm if this is still an issue?
