### ISSUE TITLE
Issue on Revelation startup with new launcher, please help.

### ISSUE THREAD

**Issue by Ma5terBaiter** [FTBTeam/FTB-App#6]
Hey guys, I've just downloaded the new launcher, along with FTB's Revelation pack. Now when launching the pack it returns this msg; "You must include the right dependencies for Just Enough HarvestCraft: Requires harvestcraft 1.12.2z or above (missing)" and fails to launch. Attached is the latest.log produced when the error occurs.
[latest log 0204.txt](https://github.com/FTBTeam/FTB-App/files/4422996/latest.log.0204.txt)

Many thanks for the new launcher, either way, hope you can help! :)

**Comment by Jake-E** [comment]
@Rushmead is looking into this. Once fixed he’ll update you here to try another download of the modpack.

**Comment by Ma5terBaiter** [comment]
Thank you very much!

**Comment by Jake-E** [comment]
This should be fixed now, may take a little while because of caching but try re-downloading the modpack now.

**Comment by Ma5terBaiter** [comment]
It's working now, thanks for the rapid response and fix! Stay safe :)
