### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by sem1colon00** [FTBTeam/FTB-App#60]
It says i can't make JVM...

#
[i4j_nlog_5.log](https://github.com/FTBTeam/FTB-App/files/4435462/i4j_nlog_5.log)

**Comment by Jake-E** [comment]
Could you try with the latest version of the installer:
https://apps.modpacks.ch/FTBApp/release/1.0.5/FTBA_windows-x64_1_0_5.exe

**Comment by Jake-E** [comment]
Please continue feedback in #44.
