### ISSUE TITLE
Direwolf20 1.18 stuck in loading screen

### ISSUE THREAD

**Issue by Robotgiggle** [FTBTeam/FTB-App#600]
When I try to load up the new Direwolf20 pack, the launcher gets stuck on the step "Processing work OBJECT_HOLDERS". I've tried reinstalling the pack, and that didn't fix the problem. I've also tried googling the error, but that gives me zero results. Any idea what I should do?

The step it gets stuck on:
<img width="857" alt="Screen Shot 2022-06-09 at 6 19 58 PM" src="https://user-images.githubusercontent.com/88736742/172954753-64bd6ca3-71a9-447b-bf6f-7eb0024e2b42.png">
169-4362-a8a8-aeb08f518b77.png">

**Comment by MichaelHillcox** [comment]
Closing: Please follow the issue template
