### ISSUE TITLE
[Bug]: Cannot find (using search) certain curseforge modpacks that contain generic terms in their title

### ISSUE THREAD

**Issue by Senjar** [FTBTeam/FTB-App#602]
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Debug Code

Irrelevant

### Describe the bug

Searching curseforge modpacks that contain generic terms in their name is not possible due to a hard limit of 10 results and search not searching the title exclusively but also the description

### Steps to reproduce

1. Try to find this pack in the FTB App (https://www.curseforge.com/minecraft/modpacks/fabric-adventure-pack)
2. Search "[FABRIC] Adventure Pack"
3. 10 other modpacks appear in total without the specific modpack (
- Better Minecraft [FABRIC]
- Medieval Minecraft [FABRIC]
- All of Fabric 5
...

### Expected behaviour

The "[FABRIC] Adventure Pack" should appear

### Screenshots

![image](https://user-images.githubusercontent.com/11983420/173094940-08f82944-1d53-4dd6-a41d-f22aa684bb8e.png)

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
We've resolved this in our backend systems, this should now work again
