### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by saddlepaddle** [FTBTeam/FTB-App#604]
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Log Files

https://pste.ch/ugurikutar

### Debug Code

FTB-DBGCEWOVOSINO

### Describe the bug

Null Pointer Exception When Signing In With Microsoft

### Steps to reproduce

1. Click on the sign in icon
2. Click on the Microsoft signin option
3. Follow the instructions to sign in through Microsoft's Oauth
4. I should be logged into the FTB launcher

### Expected behaviour

I should be able to sign in after doing this, but instead I'm hanging on the screen in the screenshots section.

### Screenshots

![image](https://user-images.githubusercontent.com/14907857/173273878-1688eecc-8469-4895-92ed-94f559ff1e93.png)

### Additional information

I can't sign in to the launch as a result of this. 

### Information

- [X] I have provided as much information as possible

**Comment by saddlepaddle** [comment]
Just tested on my mac, I can't sign in on my mac either. I'm stuck on the same step there too.

**Comment by Smelllly** [comment]
Made an account just to say I am having the same problem. My friend was also having the same problem. He fixed it by deauthorizing FTB on his Microsoft account and reauthorizing it. However, that didn't work for me.

**Comment by YallKee** [comment]
I also made account to say I have the same issue. but I just fixed it. I logged out of my Microsoft account on the webpage and signed back in. I'm unsure if that fixed it but I overall kept trying to login till I got in

**Comment by wimos-ai** [comment]
Can confirm that removing and re-adding FTB from Apps and services that can access your data fixed the issue for me.

**Comment by lutzenfamily** [comment]
I didnt change anything and now its working again
