### ISSUE TITLE
Can't connect account after it was already linked

### ISSUE THREAD

**Issue by TheShapeless97** [FTBTeam/FTB-App#605]
Have been playing revelations mod for a few days now.
Jumped on today and there was an error with my account, so I removed it and went to link it again. Now I just end up with a waiting for response window that doesn't go away.

**Comment by MrTetas** [comment]
yeah same issue here

**Comment by ripley5555** [comment]
I have the exact same issue as well

**Comment by TheShapeless97** [comment]
Are you guys having issues with the windows store and minecraft launcher as well? Wondering whether it is a problem with Microsoft

**Comment by wimos-ai** [comment]
Can confirm that removing and re-adding FTB from Apps and services that can access your data fixed the issue for me.

**Comment by TheShapeless97** [comment]
First thing I tried, still no luck
I see heaps of people having issues with Java and bedrock so I assume there is some internal issue going on

**Comment by lutzenfamily** [comment]
They fixed whatever the issue was. I am on now

**Comment by TheShapeless97** [comment]
We're back in business boys
