### ISSUE TITLE
[Bug]: Unable to launch FTB revelations

### ISSUE THREAD

**Issue by thehartbros** [FTBTeam/FTB-App#607]
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Log Files

https://pste.ch/ocuhuveciq

### Debug Code

FTB-DBGOPAQUSUKUR

### Describe the bug

when trying to launch FTB revelations, it says initializing for a little bit with nothing appearing in the log before it gives the error: "Error! Unable to update, validate or find your profile, please sign in again"

### Steps to reproduce

1. go to FTB app
2. attempt to launch FTB Revelations beta version 3.6.0

### Expected behaviour

expected to get stuck on the initializing process with nothing appearing in the log before showing the error previously mentioned

### Additional information

I had just tried to add the energyconverters_1.12.2-1.3.7.30 mod on my client before this error started to show up, which made me think it was an issue on my end but my friend who hasn't messed with his mods at all is having the same exact error when trying to launch the modpack

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
This has been fixed locally so that this kind of issue won't happen again but the root cause of this issue was that the auth servers were down. You should be good to play the pack again now
