### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nfinch23** [FTBTeam/FTB-App#608]
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Debug Code

                                               ███████ ████████ ██████                                                ██         ██    ██   ██                                                █████      ██    ██████                                                ██         ██    ██   ██                                                ██         ██    ██████                                                   Version: 1.0.1-576c95d2                                              Mon, 13 Jun 2022 04:09:03 UTC   # System Information   INFO  OS: Microsoft Windows 10 Home (10.0.19043)  INFO  CPU: Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (GenuineIntel)  INFO  Memory: 7.17 GiB / 23.95 GiB (29.00% used)  # FTB App Checks   SUCCESS  FTB App directory (AppData): file/directory exists  ## Validating App structure   SUCCESS  Minecraft bin directory: file/directory exists  ## App info   INFO  Located app at C:\Users\noahf\AppData\Local/.ftba  INFO  App version: 1.22.608.1143  INFO  Backend version: 202206081143-2e021f8e74-release  INFO  Web version: 2e021f8e74  INFO  Branch: release  SUCCESS  Does app_settings.json exist?: file/directory exists  INFO  Instance Location:  C:\Users\noahf\AppData\Local\.ftba\instances  # Check for instances   SUCCESS  instances directory: file/directory exists  INFO  found instance:  23964283-3437-4edb-ad30-7a41466922f1  INFO  Name: FTB Presents Direwolf20 1.18  INFO  Version: 1.4.1  INFO  Version ID: 2138  INFO  Memory: 6144  INFO  Min/Rec Memory: 4096/6144  INFO  Custom Args:  INFO  Embedded JRE: true  INFO  Is Modified: false  SUCCESS  23964283-3437-4edb-ad30-7a41466922f1 logs folder: file/directory exists  INFO  Latest log timestamp: 2022-06-12 18:37:30  SUCCESS  Uploaded 23964283-3437-4edb-ad30-7a41466922f1/logs/latest.log: https://pste.ch/eqahipewib  SUCCESS  23964283-3437-4edb-ad30-7a41466922f1 instance.json: file/directory exists  SUCCESS  23964283-3437-4edb-ad30-7a41466922f1 instance.json: json is valid  INFO  found instance:  3c60c72f-4cee-409d-a899-29345f78c583  INFO  Name: FTB Presents Direwolf20 1.18  INFO  Version: 1.0.0  INFO  Version ID: 2125  INFO  Memory: 6144  INFO  Min/Rec Memory: 4096/6144  INFO  Custom Args:  INFO  Embedded JRE: true  INFO  Is Modified: false  WARNING  3c60c72f-4cee-409d-a899-29345f78c583 logs folder: file/directory does not exist  SUCCESS  3c60c72f-4cee-409d-a899-29345f78c583 instance.json: file/directory exists  SUCCESS  3c60c72f-4cee-409d-a899-29345f78c583 instance.json: json is valid  INFO  found instance:  498d9cf4-8dd4-444d-8f2f-fb7d1a56a349  INFO  Name: FTB Interactions  INFO  Version: 2.0.1  INFO  Version ID: 85  INFO  Memory: 5632  INFO  Min/Rec Memory: 4250/5500  INFO  Custom Args:  INFO  Embedded JRE: true  INFO  Is Modified: false  SUCCESS  498d9cf4-8dd4-444d-8f2f-fb7d1a56a349 logs folder: file/directory exists  INFO  Latest log timestamp: 2020-07-27 20:42:05  SUCCESS  Uploaded 498d9cf4-8dd4-444d-8f2f-fb7d1a56a349/logs/latest.log: https://pste.ch/xukigusuru  SUCCESS  498d9cf4-8dd4-444d-8f2f-fb7d1a56a349 instance.json: file/directory exists  SUCCESS  498d9cf4-8dd4-444d-8f2f-fb7d1a56a349 instance.json: json is valid  INFO  found instance:  565e967f-8d26-453c-bde8-15f3897a65e4  INFO  Name: Enigmatica 6 - E6 - 1.16.5  INFO  Version: 0.5.8  INFO  Version ID: 3405630  INFO  Memory: 6132  INFO  Min/Rec Memory: 4096/6132  INFO  Custom Args:  INFO  Embedded JRE: true  INFO  Is Modified: false  WARNING  565e967f-8d26-453c-bde8-15f3897a65e4 logs folder: file/directory does not exist  SUCCESS  565e967f-8d26-453c-bde8-15f3897a65e4 instance.json: file/directory exists  SUCCESS  565e967f-8d26-453c-bde8-15f3897a65e4 instance.json: json is valid  INFO  found instance:  588eba59-005e-464d-8aed-c7d8615a5d85  INFO  Name: FTB Presents Direwolf20 1.16  INFO  Version: 1.2.0  INFO  Version ID: 213  INFO  Memory: 6144  INFO  Min/Rec Memory: 4096/6144  INFO  Custom Args:  INFO  Embedded JRE: true  INFO  Is Modified: false  SUCCESS  588eba59-005e-464d-8aed-c7d8615a5d85 logs folder: file/directory exists  INFO  Latest log timestamp: 2021-01-01 17:42:34  SUCCESS  Uploaded 588eba59-005e-464d-8aed-c7d8615a5d85/logs/latest.log: https://pste.ch/niruxukudi  SUCCESS  588eba59-005e-464d-8aed-c7d8615a5d85 instance.json: file/directory exists  SUCCESS  588eba59-005e-464d-8aed-c7d8615a5d85 instance.json: json is valid  INFO  found instance:  683334a0-0c86-49cd-8da0-0cd7a63ba539  INFO  Name: FTB Presents Direwolf20 1.18  INFO  Version: 1.0.0  INFO  Version ID: 2125  INFO  Memory: 6144  INFO  Min/Rec Memory: 4096/6144  INFO  Custom Args:  INFO  Embedded JRE: true  INFO  Is Modified: false  WARNING  683334a0-0c86-49cd-8da0-0cd7a63ba539 logs folder: file/directory does not exist  SUCCESS  683334a0-0c86-49cd-8da0-0cd7a63ba539 instance.json: file/directory exists  SUCCESS  683334a0-0c86-49cd-8da0-0cd7a63ba539 instance.json: json is valid  INFO  found instance:  9cfe107a-2fac-4d87-8cf4-66ed356f6229  INFO  Name: Not Too Complicated 2  INFO  Version: 1.3.9Release  INFO  Version ID: 3647264  INFO  Memory: 6132  INFO  Min/Rec Memory: 4096/6132  INFO  Custom Args:  INFO  Embedded JRE: true  INFO  Is Modified: false  SUCCESS  9cfe107a-2fac-4d87-8cf4-66ed356f6229 logs folder: file/directory exists  INFO  Latest log timestamp: 2022-03-20 15:32:26  SUCCESS  Uploaded 9cfe107a-2fac-4d87-8cf4-66ed356f6229/logs/latest.log: https://pste.ch/qivawegete  SUCCESS  9cfe107a-2fac-4d87-8cf4-66ed356f6229 instance.json: file/directory exists  SUCCESS  9cfe107a-2fac-4d87-8cf4-66ed356f6229 instance.json: json is valid  INFO  found instance:  9ea0bbd9-980c-4edd-b4d3-0c8d352e0721  INFO  Name: FTB Presents Direwolf20 1.16  INFO  Version: 1.2.0  INFO  Version ID: 213  INFO  Memory: 6144  INFO  Min/Rec Memory: 4096/6144  INFO  Custom Args:  INFO  Embedded JRE: true  INFO  Is Modified: false  SUCCESS  9ea0bbd9-980c-4edd-b4d3-0c8d352e0721 logs folder: file/directory exists  INFO  Latest log timestamp: 2021-01-01 12:09:28  SUCCESS  Uploaded 9ea0bbd9-980c-4edd-b4d3-0c8d352e0721/logs/latest.log: https://pste.ch/yimaderado  SUCCESS  9ea0bbd9-980c-4edd-b4d3-0c8d352e0721 instance.json: file/directory exists  SUCCESS  9ea0bbd9-980c-4edd-b4d3-0c8d352e0721 instance.json: json is valid  INFO  found instance:  b09c89b4-9ad0-4d39-84ae-094b7ffef77a  INFO  Name: FTB OceanBlock  INFO  Version: 1.7.0  INFO  Version ID: 2090  INFO  Memory: 6144  INFO  Min/Rec Memory: 4096/6144  INFO  Custom Args:  INFO  Embedded JRE: true  INFO  Is Modified: false  SUCCESS  b09c89b4-9ad0-4d39-84ae-094b7ffef77a logs folder: file/directory exists  INFO  Latest log timestamp: 2021-11-15 18:01:57  SUCCESS  Uploaded b09c89b4-9ad0-4d39-84ae-094b7ffef77a/logs/latest.log: https://pste.ch/qekofigoho  SUCCESS  b09c89b4-9ad0-4d39-84ae-094b7ffef77a instance.json: file/directory exists  SUCCESS  b09c89b4-9ad0-4d39-84ae-094b7ffef77a instance.json: json is valid  INFO  found instance:  f6f937ed-df76-426a-9905-abeae94a21da  INFO  Name: FTB OceanBlock  INFO  Version: 1.7.0  INFO  Version ID: 2090  INFO  Memory: 6144  INFO  Min/Rec Memory: 4096/6144  INFO  Custom Args:  INFO  Embedded JRE: true  INFO  Is Modified: false  SUCCESS  f6f937ed-df76-426a-9905-abeae94a21da logs folder: file/directory exists  INFO  Latest log timestamp: 2021-11-17 20:38:22  SUCCESS  Uploaded f6f937ed-df76-426a-9905-abeae94a21da/logs/latest.log: https://pste.ch/jiveqefiya  SUCCESS  f6f937ed-df76-426a-9905-abeae94a21da instance.json: file/directory exists  SUCCESS  f6f937ed-df76-426a-9905-abeae94a21da instance.json: json is valid  # Upload logs   SUCCESS  Uploaded bin/settings.json: https://pste.ch/atucowosur  SUCCESS  Uploaded bin/launcher_log.txt: https://pste.ch/mopokaburu  SUCCESS  Uploaded bin/launcher_cef_log.txt: https://pste.ch/oyucivoqap  SUCCESS  Uploaded logs/latest.log: https://pste.ch/zegoqiroja  SUCCESS  Uploaded logs/debug.log: https://pste.ch/ufemumukir  SUCCESS  Overwolf Logs: file/directory exists  SUCCESS  Uploaded Overwolf/Log/Apps/FTB App/index.html.log: https://pste.ch/vepuluxeqe  SUCCESS  Uploaded Overwolf/Log/Apps/FTB App/background.html.log: https://pste.ch/xahasijoye  WARNING  Uploading Overwolf/Log/Apps/FTB App/chat.html.log: failed to open file  # Debug Report Completed  Please provide this code to support: FTB-DBGLAZOCEGINO   INFO  Press ESC to exit...

### Describe the bug

Unable to sign into Microsoft account on FTB app even though verifcation was validated.

### Steps to reproduce

I tried to launch a modpack I was just playing a couple hours ago when I got the error "Unable to update, validate or find your profile, please sign in again.
I clicked the sign in button in bottom left and clicked sing in with Microsoft.
I was redirected to https://msauth.feed-the-beast.com/ where I clicked Microsoft login.
I correctly logged into my Microsoft account and I was redirected to https://msauth.feed-the-beast.com/callback where it said I can close the tab and return to the app. I did so but on ftb app it still says "Waiting for response" and I am still not logged in or able to launch an instance.
I restarted computer, reinstalled ftb app, launched vanilla Minecraft with the same account and still the bug persists.
![image](https://user-images.githubusercontent.com/80540827/173278486-f20cd464-f73e-4b38-b090-4c0811ba38c5.png)
![image](https://user-images.githubusercontent.com/80540827/173278530-71f43d6f-3e94-42c5-89e1-13c4feb1e065.png)

### Expected behaviour

I should have been able to log in.

### Screenshots

![image](https://user-images.githubusercontent.com/80540827/173278640-d228e775-49f5-43b6-b41c-3e62be09e1b6.png)
![image](https://user-images.githubusercontent.com/80540827/173278664-00f5dcb2-7b17-4429-b232-c37729c4e386.png)

### Information

- [X] I have provided as much information as possible

**Comment by wimos-ai** [comment]
Can confirm that removing and re-adding FTB from Apps and services that can access your data fixed the issue for me.

**Comment by nfinch23** [comment]
That worked thank you! I will close report now.
