### ISSUE TITLE
Modpack search total is wrong

### ISSUE THREAD

**Issue by AKTheKnight** [FTBTeam/FTB-App#61]
https://api.modpacks.ch/public/modpack/search/50?term=1.12
Returns 14 but total is 2

https://api.modpacks.ch/public/modpack/search/50?term=1.15
Returns 1 but total is 0

**Comment by CH-Paul-T** [comment]
Fixed (Current results are, however, cached)

**Comment by AKTheKnight** [comment]
Thanks you Paul :)
