### ISSUE TITLE
[Bug]: Cannot Verify Account with microsoft

### ISSUE THREAD

**Issue by GrueOfDoom** [FTBTeam/FTB-App#610]
### What Operating System

Windows 10

### App Version

1.3.0

### UI Version

2e021f8e74

### Log Files

https://msauth.feed-the-beast.com/error/em-2

### Debug Code

FTB-DBGRUHACEYOHA

### Describe the bug

Cannot Verify Microsoft Account

### Steps to reproduce

1. Try to launch a pack
2. Get told to connect Microsoft or Mojang account
3. Do process to connect Microsoft account
4. Get page telling me FTB can't verify with Microsoft, despite FTB being in my list of Authorised Apps

### Expected behaviour

To have my account linked

### Screenshots

![image](https://user-images.githubusercontent.com/28618208/173630189-84844e9f-3144-4028-ac16-7467a5e2f91d.png)
![image](https://user-images.githubusercontent.com/28618208/173630300-7174a059-7de4-4a3d-9408-db4b46151773.png)

### Additional information

That's All

### Information

- [X] I have provided as much information as possible

**Comment by GrueOfDoom** [comment]
Nope, still the same thing, tried removing it from authorised apps then trying it again and still no dice

**Comment by MichaelHillcox** [comment]
Try a different browser?

**Comment by Tuho89** [comment]
@GrueOfDoom I had this issue couple of weeks ago, I found out that 1 of my browser extensions like adblocker / cookie blocker was causing this. The Microsoft website needs cookies to be able to sign you in. Afterwards you can remove the cookies of the website.

Try it

**Comment by MichaelHillcox** [comment]
^ also closing as it's a browser issue
