### ISSUE TITLE
Can't Play imported modpacks[Bug]: 

### ISSUE THREAD

**Issue by CanBoy67** [FTBTeam/FTB-App#612]
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Debug Code

FTB-DBGVIHETIPOPI

### Describe the bug

I am not able to play my custom curseforge modpack. It loads in the background and I am unable to bring it to the foreground, even clicking the button to do so it does not it remains in the background with no way to actually access the window

### Steps to reproduce

1. Import curseforge Zip
2. See it's loading in the background
3. wait for game to load
4. Click the eye button to bring it to the front
5. See that it is still running in background 

### Expected behaviour

The window to be brought to the foreground for playing

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Looks like even our force start fix isn't working. Thanks for the report, we'll look into this

**Comment by CanBoy67** [comment]
Ok

**Comment by MichaelHillcox** [comment]
We've updated our mod that handles some of the logic here, can you see if it's still an issue?

**Comment by CanBoy67** [comment]
Everything is working now
