### ISSUE TITLE
[Bug]: When I try to log in the Microsoft opcion , says that something went wrong

### ISSUE THREAD

**Issue by GoldSilver271** [FTBTeam/FTB-App#613]
### What Operating System

Windows 10

### App Version

Version 1.3.0, 202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Log Files

![Erro FTB](https://user-images.githubusercontent.com/107684479/174287117-35374214-0724-4247-a0b9-2e67d59d1877.PNG)

### Debug Code

FTB-DBGZOQIVISASU

### Describe the bug

When i click in play, the app asks me to log in, with the Microsoft or Mojang account. My account is Microsoft, so I try to enter with Microsoft and then when I do the log in process, appears a message that says that was "unable to fetch profile from Minecraft account ( no ID found). I also tryed to log in with Mojang, but then says that my account was migrated, and it was.

### Steps to reproduce

1. Go to FTB;
2. Click in play;
3. Choose the option for your account, Mojang or Microsoft:;
4. Then log in, wait for the FTB response, and then you´ll see the error.

### Expected behaviour

When I do the log in , normaly the app should accept the log in and then inicialise the game.

### Screenshots

![Erro FTB](https://user-images.githubusercontent.com/107684479/174288655-c8f8c4a9-e01d-41c6-b030-d95bfb227bb9.PNG)

### Information

- [X] I have provided as much information as possible

**Comment by Wounsch** [comment]
I have the Same Problem. Pls Help
