### ISSUE TITLE
[Bug]: Can't Update Modpacks

### ISSUE THREAD

**Issue by DizzyDJW** [FTBTeam/FTB-App#615]
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Debug Code

FTB-DBGIFEZAHIQIJ

### Describe the bug

Unable to update modpacks. Any attempt leaves a screen stating: "Preparing..." and nothing happens. If left like this for hours, eventually, closing and re-opening the app creates an ENTIRELY NEW modpack of the selected updated version.

### Steps to reproduce

1. Open FTB App
2. Choose Modpack (Direwolf20 1.18 for example)
3. Update Modpack.
4. See issue.

### Expected behaviour

Self-explanatory

### Screenshots

![image](https://user-images.githubusercontent.com/26727521/174450295-6fa176af-28be-4b19-80dd-f8135193ce34.png)

### Information

- [X] I have provided as much information as possible

**Comment by Maverick044** [comment]
Having the exact same problem trying to update direwolf20 1.18.2 beta 1.7

the download just sits at "preparing".. nothing is downloading... 

been sitting here watching it for over 20 minutes..

![image](https://user-images.githubusercontent.com/76850367/178094674-4d65486e-c760-424a-9d36-29f0910ae957.png)

**Comment by MichaelHillcox** [comment]
I think it finished but didn't update the UI to show that it had actually updated. Something I'll need to look into

**Comment by MichaelHillcox** [comment]
This should have been fixed :+1:
