### ISSUE TITLE
[Bug]: Cannot open the FTB App

### ISSUE THREAD

**Issue by Supawawa** [FTBTeam/FTB-App#616]
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Debug Code

FTB-DBGFAKEROKOGA

### Describe the bug

I cannot open the FTB App and it just gives me this

### Steps to reproduce

I open the game and it just ends up like this

### Expected behaviour

I expected to be able to open the App

### Screenshots

![image](https://user-images.githubusercontent.com/107878140/174648752-d70eb03d-9a19-41f7-8a20-3c37e25c6071.png)
![image](https://user-images.githubusercontent.com/107878140/174648880-f80099eb-b528-4d80-a35f-711797869b8a.png)

### Information

- [X] I have provided as much information as possible

**Comment by ChipmunkCraft** [comment]
I believe I am having the same issue.  I am unable to get past the "Setting Up" screen which then leads to the screenshot posted above saying "Oh... This doesn't look right..."

I've tried uninstalling/reinstalling both ftb app and overwolf including trying to run as administrator.  Also tried whilst having the firewall and anti-virus disabled.

I'm curious about the debug info below saying "Unable to find app install" as if it has not finished installing.

Log:  https://pastebin.com/qjJFaua3

**Debug Tool Info:**
                                                Version: 1.0.1-576c95d2
                                             Mon, 25 Jul 2022 23:43:27 UTC


**# System Information**

 INFO  OS: Microsoft Windows 10 Pro (10.0.19044)
 INFO  CPU: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (GenuineIntel)
 INFO  Memory: 8.23 GiB / 31.89 GiB (25.00% used)
 INFO  Java Home: C:\Program Files\Java\jdk-16.0.2\

**# FTB App Checks**

 WARNING  FTB App directory (AppData): file/directory does not exist
 WARNING  FTB App directory (home): file/directory does not exist
  ERROR   Unable to find app install

**# Debug Report Completed**

Please provide this code to support: FTB-DBGFERURIZOKI

**Comment by Tasselab34** [comment]
I have the same problem. really annoying when whole friggen app is not working...
