### ISSUE TITLE
[Bug]: Fatal exception whilst installing modpack.

### ISSUE THREAD

**Issue by Arzether** [FTBTeam/FTB-App#619]
### What Operating System

Windows 10

### App Version

1.3.0

### UI Version

92092905

### Log Files

https://pste.ch/iqejisibed

### Debug Code

FTB-DBGCEBIWUFIBA

### Describe the bug

Unable to download modpacks due to " Fatal Error "

### Steps to reproduce

* Select a Modpack
* Download ( Any verison / Any modpack )
* Downlaod screen pops up, then shows " Fatal exception whilst installing modpack "

### Expected behaviour

Downlaod should have started and finished

### Screenshots

![Folders Generated](https://user-images.githubusercontent.com/108029854/175131974-d87d75f9-76d7-4496-9f60-7c62822283c5.png)
![Bug](https://user-images.githubusercontent.com/108029854/175131976-df3e7eef-98f0-4f25-a648-04c297aff2ee.png)

### Additional information

Whenever I am trying to download a modpack ( can be the same over and over again ) it will always generate an additional folder in the Instances folder.

Error Message when trying to download: Fatal exception whilst installing modpack

### Information

- [X] I have provided as much information as possible

**Comment by Arzether** [comment]
Update: 
Suddenly, it let me download the Modpack I wanted. I haven't try / done anything to solve it, it just got fixed on it's own.

If by any chance this happens again, could you please leave a potential fix here, or just point out what causes the issue?

**Comment by goofygabe8** [comment]
How long did it take to fix because I'm having the same problem

**Comment by Tuho89** [comment]
Hey mate, 
I have the same issue, but might have found the reason for it. 
Could you test it like me and write your finding?
https://github.com/FTBTeam/FTB-App/issues/633

Basically, download and check if you have this issue with EVERY modpack? or only modpacks that have BETA versions?

**Comment by MichaelHillcox** [comment]
Closing as this is most likely resolved.
