### ISSUE TITLE
API: Is 50 the upper limit for totals?

### ISSUE THREAD

**Issue by AKTheKnight** [FTBTeam/FTB-App#62]
https://api.modpacks.ch/public/modpack/popular/plays/100

Returns a limit of 50.

Say I wanted to get the most popular 51-100 is there a way or are we capped at top 50?

**Comment by CH-Paul-T** [comment]
Capped to the top 50 at the moment, plan is to allow popular top 50 via tag also in the near future.

**Comment by CH-Paul-T** [comment]
https://modpacksch.docs.apiary.io/#reference/0/modpacks/most-played-with-tag
https://modpacksch.docs.apiary.io/#reference/0/modpacks/most-installed-with-tag

**Comment by AKTheKnight** [comment]
Thank you Paul :)

**Comment by CH-Paul-T** [comment]
Np

https://modpacksch.docs.apiary.io/#reference/0/tags/most-assigned/used

Added that too, which may be of use.

Also tweaked some limits to 250 (popular packs etc) and the limit for tags is quite high.
