### ISSUE TITLE
[Bug]: Modpack download stuck at preparing, and then creates unplayable instance

### ISSUE THREAD

**Issue by ISamka** [FTBTeam/FTB-App#620]
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Log Files

https://pste.ch/ufamuhedip

### Debug Code

FTB-DBGDUSULOYUQI

### Describe the bug

The installing modpack screen gets stuck on ''Preparing...'' (and 0%) when the app is restarted a new instance is visible)

### Steps to reproduce

1. Attempt to install any modpack
2. The process gets stuck at preparing
3. Close the installing window
4. Restart FTB app
5. New instance visible in library
6. Launching the instance results in the screenshot

### Expected behaviour

For the installation process to progress normally, and the game to launch with text.

### Screenshots

![Textless Minecraft](https://user-images.githubusercontent.com/108028938/175175250-bc876109-2f1a-4ab0-8730-65c926ffc4cd.PNG)
![World Creation](https://user-images.githubusercontent.com/108028938/175178396-57908d7f-c4ba-4000-9bf8-ed022a420da4.PNG)

### Additional information

Updating the pack results in the instance failing to launch. Reinstalled app couple of times. Also the first modpack installation progresses normally whenever the app is restarted but the instance doesnt work all the same. Attempting to create a world in the textless instances causes ftb app to crash and minecraft to freeze. I have windows in Turkish. (I know this sometimes causes text problems)

### Information

- [x] I have provided as much information as possible

**Comment by ThatCoffeeGuy** [comment]
Same happened here, both on Windows 10 and M1 mac - Updating is just stuck at 0% for a very long time, then it creates a new, unconfigured instance.

**Comment by ant4N7** [comment]
I was able to get it to work after clearing my cache in the settings, then closing ftb and overwolf and relaunching. Hope this works for you too!

**Comment by Sveet** [comment]
Windows 10

Installation was stuck at preparing for 10-15 minutes. I quit CurseForge/Overwolf which killed FTB App. I reloaded FTB App and deleted the partial instance(s). I quit CurseForge/Overwolf again, and restarted FTB App. Installation was successful on the next attempt.

**Comment by ISamka** [comment]
Neither of these helped unfortunately

**Comment by ISamka** [comment]
I found a solution on the modpacks github. It seems it was related to me having windows in turkish.
-Duser.language=en -Duser.country=US adding this line solved it.
