### ISSUE TITLE
[Bug]: Searching for additional mod to add to a modpack provides no output

### ISSUE THREAD

**Issue by CrystalSpore** [FTBTeam/FTB-App#621]
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Log Files

https://pste.ch/heyajafudo
^ These are verbose logs

### Debug Code

FTB-DBGEPIHOSAXEB

### Describe the bug

Adding mod to existing pack either doesn't show anything or will show similar results but not the exact mod

### Steps to reproduce

1. Go to Library & Select Modpack (In this case Direwolf20 1.18 v1.4.0 - Old version due to server provider)
2. Select Mods tab
3. Click green "Add more mods" button
4. Search "Simple Voice Chat", which returns no output (or poor output).

### Expected behaviour

Being able to view mod in the search list to allow installing into the pack

### Screenshots

Example of no output (screenshot from 2022.06.22):
![image](https://user-images.githubusercontent.com/6373584/175182911-055267e6-bd5e-4def-82aa-d847fa7d3d9e.png)

Example of poor output (screenshot from 2022.06.19, this output is better, but odd that an exact match isn't at the top of the list): 
![image](https://user-images.githubusercontent.com/6373584/175183032-d3fa386a-a963-4b60-a17b-941005a2a0d8.png)

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
This is fixed now
