### ISSUE TITLE
SSL tag mismatch

### ISSUE THREAD

**Issue by nickydg1993** [FTBTeam/FTB-App#623]
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-App/files/8984841/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-App/files/8984842/debug.log)

### Debug Code

FTB-DBGBAXIHULUPA

### Describe the bug

Issue started with failed to update mod pack, and now continues with new mod pack instal

### Steps to reproduce

Tried to update mod pack
update failed

Deleted mod pack
tried to reinstall mod pack
install failed

restarted FTB
tried to reinstall mod pack
install failed

Restarted computer
tried to reinstall mod pack
install failed

### Expected behaviour

Mod pack to update/install

### Additional information

                                               ███████ ████████ ██████
                                               ██         ██    ██   ██
                                               █████      ██    ██████
                                               ██         ██    ██   ██
                                               ██         ██    ██████

                                                Version: 1.0.1-576c95d2
                                             Sat, 25 Jun 2022 13:19:45 UTC

# System Information

 INFO  OS: Microsoft Windows 11 Home (10.0.22000)
 INFO  CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (GenuineIntel)
 INFO  Memory: 5.19 GiB / 15.88 GiB (32.00% used)

# FTB App Checks

 SUCCESS  FTB App directory (AppData): file/directory exists

## Validating App structure

 SUCCESS  Minecraft bin directory: file/directory exists

## App info

 INFO  Located app at C:\Users\nicky\AppData\Local/.ftba
 INFO  App version: 1.22.517.1618
 INFO  Backend version: 202205171618-14abefffbf-release
 INFO  Web version: 14abefffbf
 INFO  Branch: release
 SUCCESS  Does app_settings.json exist?: file/directory exists
 INFO  Instance Location:  C:\Users\nicky\AppData\Local\.ftba\instances

# Check for instances

 SUCCESS  instances directory: file/directory exists
 INFO  found instance:  4dc09bc3-d4ea-4634-9536-28e9e398fa2b
 INFO  Name: FTB Presents Direwolf20 1.18
 INFO  Version: 1.4.1
 INFO  Version ID: 2138
 INFO  Memory: 6144
 INFO  Min/Rec Memory: 4096/6144
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 WARNING  4dc09bc3-d4ea-4634-9536-28e9e398fa2b logs folder: file/directory does not exist
 SUCCESS  4dc09bc3-d4ea-4634-9536-28e9e398fa2b instance.json: file/directory exists
 SUCCESS  4dc09bc3-d4ea-4634-9536-28e9e398fa2b instance.json: json is valid
 INFO  found instance:  58635ad1-36ff-4834-8295-0437862206ed
 INFO  Name: FTB Presents Direwolf20 1.18
 INFO  Version: 1.5.1
 INFO  Version ID: 2142
 INFO  Memory: 6144
 INFO  Min/Rec Memory: 4096/6144
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 WARNING  58635ad1-36ff-4834-8295-0437862206ed logs folder: file/directory does not exist
 SUCCESS  58635ad1-36ff-4834-8295-0437862206ed instance.json: file/directory exists
 SUCCESS  58635ad1-36ff-4834-8295-0437862206ed instance.json: json is valid
 INFO  found instance:  5b9e0849-7b08-432a-84b3-9d00f4928fe3
 INFO  Name: FTB Presents Direwolf20 1.18
 INFO  Version: 1.5.1
 INFO  Version ID: 2142
 INFO  Memory: 6144
 INFO  Min/Rec Memory: 4096/6144
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 WARNING  5b9e0849-7b08-432a-84b3-9d00f4928fe3 logs folder: file/directory does not exist
 SUCCESS  5b9e0849-7b08-432a-84b3-9d00f4928fe3 instance.json: file/directory exists
 SUCCESS  5b9e0849-7b08-432a-84b3-9d00f4928fe3 instance.json: json is valid
 INFO  found instance:  5e19b1b6-70a1-4eaf-88fd-28afb6c56b56
 INFO  Name: FTB Presents Direwolf20 1.18
 INFO  Version: 1.5.1
 INFO  Version ID: 2142
 INFO  Memory: 6144
 INFO  Min/Rec Memory: 4096/6144
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 WARNING  5e19b1b6-70a1-4eaf-88fd-28afb6c56b56 logs folder: file/directory does not exist
 SUCCESS  5e19b1b6-70a1-4eaf-88fd-28afb6c56b56 instance.json: file/directory exists
 SUCCESS  5e19b1b6-70a1-4eaf-88fd-28afb6c56b56 instance.json: json is valid
 INFO  found instance:  868801a7-397b-4735-a6b7-41d03a4b59fb
 INFO  Name: FTB Presents Direwolf20 1.18
 INFO  Version: 1.5.1
 INFO  Version ID: 2142
 INFO  Memory: 6144
 INFO  Min/Rec Memory: 4096/6144
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 WARNING  868801a7-397b-4735-a6b7-41d03a4b59fb logs folder: file/directory does not exist
 SUCCESS  868801a7-397b-4735-a6b7-41d03a4b59fb instance.json: file/directory exists
 SUCCESS  868801a7-397b-4735-a6b7-41d03a4b59fb instance.json: json is valid
 INFO  found instance:  8d263729-50ae-4171-b347-5a08f15ed05a
 INFO  Name: FTB Presents Direwolf20 1.18
 INFO  Version: 1.5.1
 INFO  Version ID: 2142
 INFO  Memory: 6144
 INFO  Min/Rec Memory: 4096/6144
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 WARNING  8d263729-50ae-4171-b347-5a08f15ed05a logs folder: file/directory does not exist
 SUCCESS  8d263729-50ae-4171-b347-5a08f15ed05a instance.json: file/directory exists
 SUCCESS  8d263729-50ae-4171-b347-5a08f15ed05a instance.json: json is valid
 INFO  found instance:  cda7f18f-f748-42b7-94e1-204d36c03aab
 INFO  Name: FTB Presents Direwolf20 1.18
 INFO  Version: 1.5.1
 INFO  Version ID: 2142
 INFO  Memory: 6144
 INFO  Min/Rec Memory: 4096/6144
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 WARNING  cda7f18f-f748-42b7-94e1-204d36c03aab logs folder: file/directory does not exist
 SUCCESS  cda7f18f-f748-42b7-94e1-204d36c03aab instance.json: file/directory exists
 SUCCESS  cda7f18f-f748-42b7-94e1-204d36c03aab instance.json: json is valid

# Upload logs

 SUCCESS  Uploaded bin/settings.json: https://pste.ch/vorunibemu
 SUCCESS  Uploaded bin/launcher_log.txt: https://pste.ch/kibebemowi
 SUCCESS  Uploaded bin/launcher_cef_log.txt: https://pste.ch/imavadobag
 SUCCESS  Uploaded logs/latest.log: https://pste.ch/abuwegupoj
 SUCCESS  Uploaded logs/debug.log: https://pste.ch/boputepayo
 SUCCESS  Overwolf Logs: file/directory exists
 SUCCESS  Uploaded Overwolf/Log/Apps/FTB App/index.html.log: https://pste.ch/ugovofecug
 SUCCESS  Uploaded Overwolf/Log/Apps/FTB App/background.html.log: https://pste.ch/awanabopak
 WARNING  Uploading Overwolf/Log/Apps/FTB App/chat.html.log: failed to open file

# Debug Report Completed

Please provide this code to support: FTB-DBGBAXIHULUPA

 INFO  Press ESC to exit...

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Extension of #479

**Comment by MichaelHillcox** [comment]
https://appsdl-overwolf-com.akamaized.net/prod/apps/cmogmmciplgmocnhikmphehmeecmpaggknkjlbag/1.23.622.1340/app.opk

Please try with this version of the app. Make sure your current version of the app is closed. Let me know if you have any more issues.
