### ISSUE TITLE
[Feature request] Can't delete modpacks?

### ISSUE THREAD

**Issue by naptimeshadows** [FTBTeam/FTB-App#624]
**Is your feature request related to a problem? Please describe.**
I don't seem to have the ability to delete/uninstall a modpack through the FTB App, nor am I able to find the installation location.

**Describe the solution you'd like**
A right-click option to go to the folder and delete a pack.

**Describe alternatives you've considered**

**Additional context**

**Comment by yablock0** [comment]
When you left click the pack there is a "Settings" button. In there you should see a red "Delete" button on the bottom.

**Comment by MichaelHillcox** [comment]
^
