### ISSUE TITLE
[Bug]: I cannot install any modpacks

### ISSUE THREAD

**Issue by PatrickEther** [FTBTeam/FTB-App#625]
### Operating System:
Windows 10 Pro Build 19044
### App Version:
202206081143-2e021f8e74-release
### UI Version
2e021f8e74
### Log Files
https://pste.ch/efawamofoz
### Debug Code
FTB-DBGVAVICUCAXI
### Describe the Bug
After installing the FTB App, I cannot install modpack. 
Every Modpack I've attempted has resulted in the error: "Fatal Exception whilst installing modpack"
 ### Steps to Reproduce
 Attempt to install modpacks
 ### Expected Behavior
 The install to complete without errors.
 ### Screenshot
![image](https://user-images.githubusercontent.com/92234292/175833605-2b1c7f12-6dd8-4d07-a9ac-28f6a94b025d.png)
### Additional Information
**Modpack Installs Attempted**
FTB Ultimate: Anniversary Edition Version 1.3.0
FTB Presents Direwolf20 1.18 Version 1.5.1
FTB Academy 1.16 Version 1.3.0
FTB University 1.16 Version 1.6.1
FTB University 1.16 Version 1.4.0
_Note: Various attempts to install occurred between closing and reopening the app_

**Attempts to Fix**
Uninstalled and re-installed the FTB app
Moved the instance folder location to an alternate drive
Manually installed jdk-17.0.2+8-jre 
Restarted PC and reattempted to install modpacks
### Information
- [x] I have provided as much information as possible

**Comment by PatrickEther** [comment]
If needed I can provide further information on my system

**Comment by Rithari** [comment]
Same here, macOS.

**Comment by PatrickEther** [comment]
Thanks for the recommendation. After reading your mention of public network I remembered that the someone put an antivirus on the PC I'm using. Once I disabled that I was able to download them without issue.
