### ISSUE TITLE
[Bug]: Sharing Failed! "An IO error occurred whilst uploading pack"

### ISSUE THREAD

**Issue by GotoFinal** [FTBTeam/FTB-App#626]
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Log Files

https://pste.ch/bomucenire

### Debug Code

FTB-DBGEVICOPEWOK

### Describe the bug

Sharing Failed! "An IO error occurred whilst uploading pack"

### Steps to reproduce

1. Click share modpack 

### Expected behaviour

I dont know, it never worked, i guess some kind of link?

### Screenshots

![image](https://user-images.githubusercontent.com/6942692/176069099-a9737ccb-5873-482e-b84e-2276e87e9d64.png)

### Additional information

Modpack ATM 7 with added mod timeout_fixes-1.18.1-1.0.0.jar

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Has this continued to happen?

**Comment by GotoFinal** [comment]
The few days i was trying to use the launcher, yes. But given up and got something that works and does not install malware. Thanks, closing as wont be able to provide more info anymore.

**Comment by MichaelHillcox** [comment]
> But given up and got something that works and does not install malware

To be clear our app is not malware. I'm sorry the sharing feature wasn't able to work nicely for you and I would have hoped to be able to debug the issue to resolve it for yourself and others.

If you're curious what malware is, here is a good article: https://en.wikipedia.org/wiki/Malware

**Comment by GotoFinal** [comment]
@MichaelHillcox Yep, pretty good article: 

> Many types of malware exist, including computer viruses, worms, Trojan horses, ransomware, *spyware*, **adware**

https://en.wikipedia.org/wiki/Adware

Spyware matches too, with all of the stuff overwolf does, especially with that fake personalisation of collected data, that you "can" disable, but if you read the rules: 
![image](https://user-images.githubusercontent.com/6942692/180661371-106291c2-c5d2-44a2-9858-f137cfc4375d.png)
And then you chekc the list of 3rd parties, every ad company is somehow responsible for preventing frauds and security, not sure if thats even legal in europe....

**Comment by OrvGull** [comment]
I'm having this same error while trying to share a customized modpack. Here's my app log: https://pste.ch/jofopakuse

**Comment by MichaelHillcox** [comment]
How strange, could you open a new issue with a new debug code and we can take another look as this issue has gotten a little off topic
