### ISSUE TITLE
[Bug]: Fatal exception whilst installing modpack.

### ISSUE THREAD

**Issue by 2865954690** [FTBTeam/FTB-App#627]
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Debug Code

FTB-DBGJEBURUSEGU

### Describe the bug

Unable to download modpacks due to " Fatal Error "

### Steps to reproduce

1.Select a Modpack
2.Download ( Any verison / Any modpack )
3.Downlaod screen pops up, then shows " Fatal exception whilst installing modpack "

### Expected behaviour

Downlaod should have started and finished.

### Screenshots

![KYZWJTQI2CTS81EB(TSFNHG](https://user-images.githubusercontent.com/108395068/176393238-c95908c3-f427-434c-b679-7ad25473e242.png)

### Additional information

The interface in the above image loads but the progress does not increase.
Whenever I am trying to download a modpack ( can be the same over and over again ) it will always generate an additional folder in the Instances folder.

Error Message when trying to download: Fatal exception whilst installing modpack.

### Information

- [X] I have provided as much information as possible

**Comment by 2865954690** [comment]
Hopefully someone can answer my question.

**Comment by goofygabe8** [comment]
Im having the same problem and I dont know how to fix

**Comment by Darkenvar** [comment]
I am also having this issue. Can upload logs if needed.

**Comment by Tuho89** [comment]
Hey mate, 
I have the same issue, but might have found the reason for it. 
Could you test it like me and write your finding?
https://github.com/FTBTeam/FTB-App/issues/633

Basically, download and check if you have this issue with EVERY modpack? or only modpacks that have BETA versions?

**Comment by MichaelHillcox** [comment]
`Caused by: okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR` interesting...

**Comment by QWERTY555222333** [comment]
i am having the same issue and all the other modpacks download exept the FTB StoneBlock 3 Beta

**Comment by QWERTY555222333** [comment]
right after i sent this review it fixed itself
my recomendation let it be and try to download the modpack a few times. hope this helps.

**Comment by MrBear2305** [comment]
i have tried every possible fix i have seen on the internet to fix this and have no luck. i have been trying for the last 3 days to install stoneblock 3 and keep getting the same message. please someone help me

**Comment by Tuho89** [comment]
Windows has a built-in RAM testing tool. It’s included on Windows 10, Windows 11, Windows 7, and all other modern versions of Windows.

To launch the Windows Memory Diagnostic tool, open the Start menu, type “Windows Memory Diagnostic”, and press Enter.

You can also press Windows Key+R, type “mdsched.exe” into the Run dialog that appears, and press Enter.

**Comment by Tuho89** [comment]
See, the issue with this bug is that the RAM module of your PC / Laptop has issues, it's either dying or faulty.
Run the windows diagnostic and have patience, wait for it to complete, it will tell you if you have an issue or not.
If you have 2 or more RAM modules, and are able / capable of removing 1 or more and test them 1 by one.

Remember, this testing will take nearly 30-45 minutes per RAM module depending on its speed and defect.

**Comment by MrBear2305** [comment]
i tried doing this and im still unable to download the mod

**Comment by Tuho89** [comment]
> 

what I posted is not a fix, it shows if you're having memory issues or not. or other hardware failures.

For me, it was simply that my ram didn't work anymore.

**Comment by MrBear2305** [comment]
it said no issues were detected

**Comment by Tuho89** [comment]
well, my knowledge only strikes this far. 
Hope you find the solution to your problem.. 

The issue is most definitely either RAM or Cache or SSD/HDD. 

Or even perhaps some sort of network issue where you can't download the modpack. 

But if you get BluescreenofDeath (BSOD google it)  at random moments. Then you're having hardware issues.

**Comment by MichaelHillcox** [comment]
Looks like the debug code has expired, sorry about that, could you open a new issue if this is still a problem? Thanks :D
