### ISSUE TITLE
[Bug]: Searching for certain modpacks in the curseforge tab shows no matching packs and the loading symbol without returning any results.

### ISSUE THREAD

**Issue by 5ully** [FTBTeam/FTB-App#628]
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Debug Code

FTB-DBGEPEGITOBED

### Describe the bug

The curseforge tab doesnt seem to manage to find all packs

### Steps to reproduce

1. Start the app
2. Go to Browse
3. Click on the curseforge tab
4. Search for different packs (I had issues with Equivalent skies and Crop Block) but those worked for Slowpoke.

### Expected behaviour

To find all curseforge packs

### Screenshots

![image](https://user-images.githubusercontent.com/9050688/176418426-2096ecc8-9cc7-49f5-878e-342ee3bfc78d.png)

### Additional information

Tried to figure out this with slowpoke on teamspeak, i was having different results today (29/6) than yesterday. Yesterday i was able to find packs like All the MOds, while today i could only find Direwolf and Agrarian Skies from the set of 6 words i was looking up.

I can be found most of the time in teamspeak or in the discord. (Slow knows who i am) if i can assist in any other way.

List of words i have been looking up:
- Direwolf (this one works)
- Equivalent
- Crop
- All the Mods
- TolkienCraft
- Agrarian Skies (This works)

### Information

- [X] I have provided as much information as possible

**Comment by 5ully** [comment]
This was supposedly a easy fix based on what slowpoke said, just gonne mention that this is still not fixed as of the 7/4/2022.
![image](https://user-images.githubusercontent.com/9050688/177216114-a8fa99ac-3240-4a68-8f30-68ae1bc780ac.png)

Im not stressing it, just wanted to mention that if there was a change at the 29th it didnt make a change for me at least.

**Comment by Lemon-Juiced** [comment]
I've been having the same problem recently, to download almost anything that doesn't appear on the front page of the CurseForge site I have to download the instance and import it. This is very annoying as that is the only way I can find to play CurseForge packs on Linux since MultiMC stopped supporting them recently.

**Comment by Folanlron** [comment]
Still is doing this....

**Comment by instinxx** [comment]
Still doing this. @Slowpoke101 does this feature unlock when a certain number of ads have been viewed in the client?

**Comment by Slowpoke101** [comment]
I’ve just spoke to Paul. The fix that we had broke other things. So they
had to put it on hold. They are currently looking at alternative solutions.

**Comment by dparkinson101** [comment]
Can you guys add a way to insert modpack links manually in that case? Just as an easy work around while you figure out this issue with the search function.

**Comment by 5ully** [comment]
This is now fixed per 17/7/2022. If anyone have similar issues still, than please provide a new report with log etc.

**Comment by 5ully** [comment]
Im reopening this since ive found new modpacks that the app doesnt manage to find on curseforge. The packs ive found is any of the Modern Skyblock modpacks are not possible to find using the app,

Link to one of the packs for testing purpose:
https://www.curseforge.com/minecraft/modpacks/modern-skyblock-classic

**Comment by dparkinson101** [comment]
Yeah I noticed this initially with trying to find the Create Flavor pack which worked only a few days prior. Looks like the search is only giving a few results back.

**Comment by ThePaul-T** [comment]
Likely resolved, it's about as good as it can get now, as we're passing results back in the right order (The CF API defaults to worst match first... -sigh- and ordered by "match")

**Comment by 5ully** [comment]
Very good, nicely fixed Paul.
