### ISSUE TITLE
[Bug]: FTB App Gets Stuck Loading PlexiGlass Mountain 1.18 (v1.1.1)

### ISSUE THREAD

**Issue by TMGMike** [FTBTeam/FTB-App#630]
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Log Files

https://pste.ch/kokakenofe
https://pste.ch/wesalamugi
https://pste.ch/coheviledi

### Debug Code

FTB-DBGVAGAGIDEBU

### Describe the bug

At some point, the app gets stuck loading the pack on "building mod list". 30 minutes later there will be no new console outputs, and pressing Kill Instance does nothing. Pressing the "eye" icon throws a java access violation which finally exits the hung instance. Pressing Play again sometimes works, but 80% of the time it hangs.

### Steps to reproduce

* Download FTB Plexiglass mountain
* Load pack
* Nothing happens.

### Expected behaviour

The pack should load.

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
@TMGMike is this still an issue for you?
