### ISSUE TITLE
[Bug] Cannot add mods to existing modpack

### ISSUE THREAD

**Issue by PhilGooodInc** [FTBTeam/FTB-App#631]
When clicking "Add more mods" in the mods tab, no results are found. (Using the Direwolf 20 1.18 Pack, v1.7.0 in this example)
![image](https://user-images.githubusercontent.com/8851040/178103550-0d0d8e70-0746-4b81-8d20-9402c7dadcd2.png)

Depending on the search term, might get this result, but still no results shown.
![image](https://user-images.githubusercontent.com/8851040/178103710-230aa3ab-c765-4a08-9a80-522ec32799e9.png)

UI Version - 2e021f8e74
Subprocess - 202206081143-2e021f8e74-release
Latest version of Overwolf - 0.199.0.15 (64 bit)

**Comment by MichaelHillcox** [comment]
Fixed in dev

Duplicate #621
