### ISSUE TITLE
[Bug]: Fatal exception while installing modpack

### ISSUE THREAD

**Issue by Tuho89** [FTBTeam/FTB-App#633]
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Log Files

-No log generated

### Debug Code

FTB-DBGXIZOQESAVE

### Describe the bug

Failure downloading modpacks with BETA version.

### Steps to reproduce

Failure steps:
1. Start up FTB APP
2. Clock on discover / browse
3. Select ANY mod pack that has a beta version
4. Select download / get.
5. Installation will fail.

Succesful steps:
1. Start up FTB APP
2. Clock on discover / browse
3. Select ANY mod pack that has no beta version
4. Select download / get.
5. Installation will succeed.

### Expected behaviour

Succesful installation of the modpack

### Screenshots

Failed: 
![image](https://user-images.githubusercontent.com/78901454/178430777-db8c3c1f-434f-4046-b346-162579e80e00.png)

Succeeded:
![image](https://user-images.githubusercontent.com/78901454/178430854-ae076c3c-86dd-4d7c-bc8b-874e321d15d1.png)

### Additional information

It seems as though the app is unstable or the servers are unstable.
I would HIGHLY recommend that the dev team has a look at this. 
If you check the bug reports the issue keeps being reported by more and more people.

As a software tester, I myself would prioritize this one as an urgent one.
![image](https://user-images.githubusercontent.com/78901454/178431234-f4a83e97-c19b-4448-8a75-27207b636e41.png)

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
I'm not able to reproduce your error by the steps given so I'll assume it's machine sepecific issue, I'll assign the right person

Main issue:

`java.io.IOException: Cannot run program "C:\Users\***\AppData\Local\.ftba\bin\runtime\jdk-17.0.2+8-jre\bin\javaw.exe" (in directory "C:\Users\*****\AppData\Local\.ftba\bin"): CreateProcess error=2, The system cannot find the file specified`

**Comment by Tuho89** [comment]
@MichaelHillcox 

I seem to have found the issue. 
For me it seems to be a RAM issue. I've downclocked my ram from 3600 on XMPII to 3400. 
Seems as though the program is not stable enough to work under these speeds. 

Ever since the downclock the Launcher (APP) and the games work fine **for now** The moment it happens again I will provide full specs and even if possible an event log and bug log.

**Comment by ChimeraGaming** [comment]
I’m also having this issue:

Ran memory test, no issues. 
I can download any that pack that do not have beta. 
Trying to download SB3 and it keeps failing. Over 400GB of free space.
Windows 10.
I’ve uninstalled and reinstalled both the launcher and the AppStore for over wolf.

solution: manually downloaded all the mods (which took over an hour)

Please fix!

**Comment by joao-leal** [comment]
I deleted the folders in AppData/Local, both from Overwolf and FTB, and also deleted they're entries in the ProgramData folder. That did the trick for me
