### ISSUE TITLE
Offline Mode[Feature request]

### ISSUE THREAD

**Issue by cornuetjusn** [FTBTeam/FTB-App#636]
**Is your feature request related to a problem? Please describe.**
I am in the United States Navy and thus am underway on a ship without internet. I can not play any of my modpacks due to the internet required to launch.

**Describe the solution you'd like**
Please offer some option for offline mode. I can be out to sea for months so it would have to be something that lasts a few months.

**Describe alternatives you've considered**
Not playing till I hit a port or return home which is sad.

**Additional context**
I understand Mojang and most likely Microsoft wouldnt like this but I would be grateful to have someone look into the possibility of it. I go on deployment in Aug which isnt long but I can always get an update in a port later.

**Comment by poboy975** [comment]
I too would like an offline option. I'm a truck driver and I'm not always able to get internet when i stop for the night. 

Yeah i understand the need to verify your account the first time you log in, but there isn't a need every single time. Even the official Minecraft launcher allows offline play. 

When i try to play offline a window pops up asking for either a direct internet connection or proxy information. 

According to your archives in the FTB forums there used to be an offline option, but either there is a bug, or the option has been removed.

**Comment by i00** [comment]
Really want this too.. take long flights for work several times a week in busy seasons!

**Comment by MichaelHillcox** [comment]
Implemented :+1:
