### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nebegavas** [FTBTeam/FTB-App#637]
### What Operating System

Windows Insider Preview

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Debug Code

FTB-DBGESIVIREGEB

### Describe the bug

i try to login on the app with my microsoft minecraft account and it sends me to https://msauth.feed-the-beast.com/ as it should but the site has an error as follows "503 Service Temporarily Unavailable nginx" that makes it so i can't log in

### Steps to reproduce

1. change your mc profiles java edition username (that's what i did before this happened, i could play fine yesterday (the 18th))
2. go to play a modpack
3. it tells you there's an error with your account instance or something
4. log out of the account
5. try logging back in
6. error on website happen
![503ERROR](https://user-images.githubusercontent.com/109621523/179819273-971b89ed-0815-4c2c-a269-8fd7e1288815.png)

### Expected behaviour

I expected to be able to log in

### Screenshots

![image](https://user-images.githubusercontent.com/109621523/179819367-660b8a44-d124-4b48-bd35-1639a189cea3.png)
![503ERROR](https://user-images.githubusercontent.com/109621523/179819442-41111f8a-73ab-417d-b565-73ba6293dfbe.png)

![image](https://user-images.githubusercontent.com/109621523/179819471-975bdc1e-ab13-494c-9bcd-5b1d4ae7e684.png)

### Additional information

everything worked fine yesterday, even after i changed my username, then today all of a sudden it stopped working, i urgently need help. thank you

### Information

- [x] I have provided as much information as possible

**Comment by Firekiking** [comment]
The same problem for me and all my friends !

**Comment by nebegavas** [comment]
> The same problem for me and all my friends !

hopefully this gets resolved quickly if it's an issue for more than one person

**Comment by nebegavas** [comment]
> The same problem for me and all my friends !

keep in mind, the error now says "500 Internal Server Error
nginx" which is a different error than earlier

**Comment by Bobby365279** [comment]
Same thing here error 500

**Comment by nebegavas** [comment]
UPDATE: IT WORKS FOR ME NOW

not sure if it works for anyone else, keep me posted!

**Comment by Bobby365279** [comment]
Same , They got them fast fixes

**Comment by Firekiking** [comment]
Work for me !
