### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 59Degrees** [FTBTeam/FTB-App#638]
### What Operating System

MacOS (Old)

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Log Files

No log files. The Debug tool was just a text document. No code was provided. If these needs to run through terminal, please let me know.

### Debug Code

FTB-DBGGOVOTOKOMA

### Describe the bug

I am unable to download any modpacks. It downloads most of the files, but before it completes, it says a fatal exception has occurred whilst installing modpack. 

### Steps to reproduce

1. Open FTB Launcher
2. Go to any modpack
3. Click the download button.
4. Click instal
5. Wait until the error appears.

### Expected behaviour

I expect the modpack to download so I can play it.

### Screenshots

![FTB Error](https://user-images.githubusercontent.com/109759913/180295019-31944e12-f923-4d2a-9ec1-85ae60b90c71.jpg)
![FTB Error 2](https://user-images.githubusercontent.com/109759913/180295020-d41e0453-862c-481d-a2b3-f4c9f743ce18.jpg)

### Additional information

I ensured I have the most recent update for both java and FTB app.
OS Monteray version 12.2.1
Furthermore, I get this message when opening up FTB: The update information could not be downloaded from https://apps.modpacks.ch/FTBApp/release.xml Please check your network connection.

### Information

- [X] I have provided as much information as possible

**Comment by 59Degrees** [comment]
As mentioned, the debug "tool" is just a text file that does not do anything. I ran it through terminal and nothing happened, so please let me know what I need to do to get the debug to work.

**Comment by MichaelHillcox** [comment]
`cd {location of the ftb-debug-macos file}`
`chmod +x ftb-debug-macos`
`./ftb-debug-macos`

**Comment by 59Degrees** [comment]
Would you mind explaining what I need to do with this information? I tried searching for what you are stating in finder and in terminal, but nothing is showing up. I kept getting no directory found or some errors.

**Comment by MichaelHillcox** [comment]
- Download the MacOs debug tool from the comments
- Open terminal,
- Type `cd` then type or copy the folder location of where the `ftb-debug-macos` file is. Most likely your downloads so you could use this if it's in your downloads `cd ~/Downloads` (`~` means your user folders, you could type the full thing, for example `/Users/mikey/Downloads/`)
 - Then type the last two commands I listed
 - You should now see it run and show you a debug code that you should copy here

**Comment by 59Degrees** [comment]
Thanks! The code is FTB-DBGGOVOTOKOMA

**Comment by MichaelHillcox** [comment]
Thanks, did you run the tool after the pack failed to install?

**Comment by 59Degrees** [comment]
So I was able to download the first mudpack. I tried doing another one, but it is stuck on preparing with no progress. Also, there are a few other issues occurring. 

First, when I open up the app for the first time, it says “ The update information could not be downloaded from https://apps.modpacks.ch/FTBApp/release.xml Please check your network connection.”

Secondly, the app won’t authenticate with Microsoft/xbox that I have a Minecraft Java purchase. So you are aware, I have played Minecraft vanilla in the official launcher once already, and I only have one Microsoft account.  I have also been able to play this launcher and other modpackt through my windows computer (but my windows computer is low end and can’t support some of the modpacks I want to play).
