### ISSUE TITLE
[Bug]: Fatal Exception Whilst Installing Modpack and modpack deleted itself overnight

### ISSUE THREAD

**Issue by ctufn1** [FTBTeam/FTB-App#639]
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Debug Code

FTB-DBGQOYEDAQEYA

### Describe the bug

Been playing FTB Ultimate: Anniversay edition perfectly for 2 weeks, turned computer on today to find my modpack was dissappeared. tried to re-download and get install failed: fatal exception whilst installing modpack, everything is gone and wont download

### Steps to reproduce

1. Open app
2. download ftb ultimate anniversary edition
3. install failed, fatal exception

### Expected behaviour

a) modpack to not dissapear overnight / b) modpack to download even after deleting and uninstalling everything

### Screenshots

![image](https://user-images.githubusercontent.com/109802166/180434580-e17d117f-a20d-4934-816f-8f8dab12aca9.png)

### Additional information

works perfectly fine for my wife and cousin that i play with, literally as i write this report

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Your machine seems to have suddenly made a required file readonly `C:\Users\corre\AppData\Local\.ftba\bin\libraries\net\minecraft\client\1.16.5-20210115.111550\client-1.16.5-20210115.111550-srg.jar` this one to be spectific. 

If you've not made any progress on the pack, I'd recommend reinstalling the pack to see if that resolves the issue
