### ISSUE TITLE
Cannot install Omnia or play other modpacks 

### ISSUE THREAD

**Issue by ChunkySpider** [FTBTeam/FTB-App#64]
Hello,
I cannot install the Omnia modpack. It says "**Error installing FTB Omnia**", and asks me to retry. Clicking that button does nothing.
I _can_ install other modpacks but I cannot play them. I get the following error:
"**Sorry, unable to start Minecraft. Please check your configuration**." 
I have reinstalled the app multiple times and tested multiple modpacks with different amounts of memory, it did nothing. Vanilla game and modpacks in twitch launcher work fine.

I am running Windows 10 and have 8GB of RAM, my app version is 1.0.5
Logs are below, I can find other ones if those will help.
[error.log](https://github.com/FTBTeam/FTB-App/files/4440539/error.log)
[launcher.log](https://github.com/FTBTeam/FTB-App/files/4440540/launcher.log)
https://pste.ch/iyonabawim

**Comment by Rushmead** [comment]
It looks like you're having issues connecting to where the files are located. Please check your DNS settings or try using Google or Cloudflare DNS (https://developers.google.com/speed/public-dns).

**Comment by ChunkySpider** [comment]
Hello again,
I see the issue is listed as closed but the same problems persist on my end despite changing to the Google DNS as recommended. I have no other problems downloading or using the internet, and I did not have any before, besides this one. 

I am attaching new logs if it helps:

[error.log](https://github.com/FTBTeam/FTB-App/files/4441465/error.log)
[launcher.log](https://github.com/FTBTeam/FTB-App/files/4441466/launcher.log)
https://pste.ch/ehinuhoted

**Comment by Jake-E** [comment]
Please see the latest reply in #65
