### ISSUE TITLE
[Bug]: wrong font

### ISSUE THREAD

**Issue by code-h0** [FTBTeam/FTB-App#643]
### What Operating System

Windows 10

### App Version

202206081143-2e021f8e74-release

### UI Version

2e021f8e74

### Debug Code

FTB-DBGWUGEMUZOYI

### Describe the bug

The UI of the Launcher has a strange font

### Steps to reproduce

unknown. Bug was there after installation.

### Expected behaviour

normal readable font 

### Screenshots

![image](https://user-images.githubusercontent.com/67474247/181062438-e86e69fa-fefa-4f5e-875b-e62e40f6d42b.png)

### Additional information

Maybe the launcher has the wrong path or filename to the correct font. Where does the launcher get the font for the UI? Is there a setting for that?

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Looks fancy 🤔
