### ISSUE TITLE
[Bug]: Invalid HTTPS Certificate for Microsoft Login

### ISSUE THREAD

**Issue by DarkIlluminatus** [FTBTeam/FTB-App#645]
### What Operating System

Windows 10

### App Version

1.3.0

### UI Version

2e021f8e74

### Debug Code

FTB-DBGOCIGOQOBOR

### Describe the bug

Login to Microsoft redirects to an insecure website that does not support the https security.

### Steps to reproduce

1. Go to FTB App and attempt to launch any instance and you will be redirected to a website that is insecure at msauth.feed-the-beast.com that has a mismatched https certificate
2. that's all you have to do to reproduce the error

### Expected behaviour

the login page and it's https certificate to match so log in can proceed safely and the game can launch.

### Screenshots

![image](https://user-images.githubusercontent.com/18306454/181354268-dea270a1-5b8c-493d-ab71-72f989dfc875.png)

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Unable to reproduce, try a different browser

**Comment by DarkIlluminatus** [comment]
Nevermind.  Apparently it was because of my DNS settings.  This issue was resolved by changing to cloudflare DNS.
