### ISSUE TITLE
Once the native launcher open I can't play because it saids that my configuration is incorrecto

### ISSUE THREAD

**Issue by LucasBarrios21** [FTBTeam/FTB-App#65]
I install ftb revelation instance, I don't touch anything in the configuration and I hit run, then the native launcher open but when I click the play button a message appears in the uper right corner.

I think there is a problem when I download the packs because it happened to me with all of the packs.
[error.log](https://github.com/FTBTeam/FTB-App/files/4443694/error.log)

**Comment by CH-Paul-T** [comment]
Hello,

Can you provide a copy of 'profiles.json' from the native(vanilla) launcher and also a screenshot of the error it provides.

Knowing your OS will also help us resolve this issue.

Thank you.

**Comment by LucasBarrios21** [comment]
Sure. I use Windows 10 64 bit
![Anotación 2020-04-07 162550](https://user-images.githubusercontent.com/54243598/78681226-bd31e480-78ec-11ea-89d7-1cae617e6e61.png)

[instance.zip](https://github.com/FTBTeam/FTB-App/files/4445161/instance.zip)

**Comment by CH-Paul-T** [comment]
We need the profiles.json from the Minecraft launcher dir (open instance, up two directories, inside "bin"). As the issue is the conversion between the instance.json and the profiles.json somehow.

**Comment by ChunkySpider** [comment]
Hello
I don't mean to butt in or be repetitive but I reported this exact issue and one I discovered at the same time  #64 it is closed but the proposed solution did not resolve the issue. I attach the error log and the json files as requested, I hope it helps all involved:

[profile_json.zip](https://github.com/FTBTeam/FTB-App/files/4446671/profile_json.zip)
[error.log](https://github.com/FTBTeam/FTB-App/files/4446673/error.log)

**Comment by CH-Paul-T** [comment]
Thanks, we're looking into it now.

Please remove any personal information from any uploaded files before uploading them in future.

**Comment by Cloudhunter** [comment]
HI,

Can you provide us with this file?

C:\Users\yourusername\AppData\Roaming\FTBA\bin\versions\1.12.2-forge1.12.2-14.23.5.2846\1.12.2-forge1.12.2-14.23.5.2846.json

You should be able to access the folder it is in by going to %APPDATA%\Roaming\FTBA\bin\versions\

**Comment by LucasBarrios21** [comment]
The problem is that when I open the folder is empty somehow. Could be that the problem?

**Comment by Jake-E** [comment]
Can you re-start the app to get the update (1.0.6 - check Settings page).
Then re-install the modpack. This should be resolved now.

**Comment by LucasBarrios21** [comment]
> Can you re-start the app to get the update (1.0.6 - check Settings page).
> Then re-install the modpack. This should be resolved now.

It works. Thank you. Keep up with the good work and stay safe everyone.
