### ISSUE TITLE
[Bug]: Sharing causes "An IO error occurred whilst uploading pack"

### ISSUE THREAD

**Issue by MisterErwin** [FTBTeam/FTB-App#660]
### What Operating System

Windows 10

### App Version

202207271710-0f9644f5fc-release

### UI Version

0f9644f5fc

### Log Files

debug.log snippet: https://pste.ch/igawodapim.sql

### Debug Code

FTB-DBGOLODETAZIQ

### Describe the bug

Modpack sharing times out after 10 seconds

### Steps to reproduce

1. Modify a modpackl
2. Click share modpack
3. wait 10 seconds
4. Sharing failed with a timeout

### Expected behaviour

The upload to upload.share.modpacks.ch should not timeout after 10 seconds

### Additional information

Just an educated guess, but:
The OkHttpClient is being built with a connect timeout and read timeout of 5 Minutes ([src](https://github.com/FTBTeam/FTB-App/blob/003ca732cd24d7bcc039d284faa12dafda732b48/subprocess/src/main/java/net/creeperhost/creeperlauncher/Constants.java#L79)).

But no `writeTimout `is specified, which means the default timeout of 10 seconds appears to be used ([docs](https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#writeTimeout-java.time.Duration-)).

By also setting the `writeTimeout `to 5 minutes, the upload should be able to succeed (I was only able to push about 4MB during these 10 seconds 😄  ).

(In addition the upload.share.modpacks.ch service returned 500 errors earlier, but a truly blazing fast response by CreeperHosts support team fixed that issue :) )

Cheers

### Information

- [X] I have provided as much information as possible

**Comment by MisterErwin** [comment]
Sorry for the ping @MichaelHillcox, but the issue described in #626 appears to have been a downtime of the transfer.sh of share.modpacks.ch 
(at least the error/debug message appears to be identical to the one I had before contacting CreeperHosts support - The transfer.sh service replying with `500: Error occurred copying to output stream\n` )

**Comment by MisterErwin** [comment]
To my knowledge this issue is still relevant.

**Comment by MichaelHillcox** [comment]
Should be resolved as we had an issue on our upload server, can you confirm if this is still happening or not? Could you also share your internet speed with me?

**Comment by MisterErwin** [comment]
If I would have to guess, the upload server still does have issues (again?).
> Got: 500 body: Could not save metadata

(Which is an error thrown by transfer.sh)

My upload and download speed to a speedtest server in my area is about 700 Mbps and still at about 500 Mbps to a server in London.

**Comment by MichaelHillcox** [comment]
Looks like something was going wrong on our end, could you try again? We've just pushed a couple of fixes

**Comment by MisterErwin** [comment]
Just tried it and it works.
Thanks a lot :)
