### ISSUE TITLE
Server installation fails when --path argument is used

### ISSUE THREAD

**Issue by jikuja** [FTBTeam/FTB-App#67]
Looks like forge installer invocation fails when `--path` argument is used:

> 26259 execve("/usr/lib/jvm/java-8-openjdk-amd64//bin/java", ["java", "-jar", "forge-1.15.2-31.1.35-installer.j"..., "--installServer", "/home/j/omnia"], 0x7ffd86c3ebd8 /* 36 vars */ <unfinished ...>
> ....
> openat(AT_FDCWD, "forge-1.15.2-31.1.35-installer.jar", O_RDONLY) = -1 ENOENT (No such file or directory)

Invocation improperly assumes that forge installer in in the current work directory. Because --path was used target directory != current work dir.

**Comment by CH-Paul-T** [comment]
Interesting, I assume @Cloudhunter didn't use my install dir variable when he implemented forge installation.

I will resolve and get a new build out today.

**Comment by CH-Paul-T** [comment]
Issue has been fixed but I am unable to log into cloudflare's dashboard to clear the cache at this time.

So it may be a couple of hours before you see an updated version.
