### ISSUE TITLE
[Bug]: can't launch FTB app

### ISSUE THREAD

**Issue by NightSickle** [FTBTeam/FTB-App#672]
### What Operating System

Windows 10

### App Version

1.3.2

### UI Version

e5790011d3

### Debug Code

FTB-DBGTEYODEREBE

### Describe the bug

I could play normally yesterday, it became like this today

### Steps to reproduce

1. double click FTBApp
![image](https://user-images.githubusercontent.com/94214250/187682111-dc161c47-ab66-427b-b5c2-abfd307a103f.png)

### Expected behaviour

Hope to know how to solve it

### Screenshots

![image](https://user-images.githubusercontent.com/94214250/187682626-787b720b-9f76-44c9-b0cf-8fee8238c096.png)

### Additional information

The last mod pack to play is FTB oceanblock

### Information

- [X] I have provided as much information as possible

**Comment by stacode123** [comment]
logs?

**Comment by NightSickle** [comment]
> logs?

How do I find the logs?

**Comment by MichaelHillcox** [comment]
Please remove `_JAVA_OPTIONS` from your environment variables
