### ISSUE TITLE
[Bug]: java.io.IOException: Download task failed

### ISSUE THREAD

**Issue by wsmith415** [FTBTeam/FTB-App#673]
### What Operating System

Windows 10

### App Version

1.3.2

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-App/files/9465595/latest.log)

### Debug Code

FTB-DBGOCAHIXAWOL

### Describe the bug

When I try to launch FTB Ultimate Anniversary Edition it spits out a java.io.IOException error

### Steps to reproduce

Open the FTB app
launch FTB Ultimate: Anniversary Edition
Error occurs

### Expected behaviour

The launch of FTB Ultimate Anniversary Edition and the ability to play the game

### Screenshots

![image](https://user-images.githubusercontent.com/99105478/187799636-7896e0c1-820e-4621-a737-42914228e777.png)

### Information

- [X] I have provided as much information as possible

**Comment by golost2202** [comment]
Same with FTB Oceanblock
I can't play anymore

![image](https://user-images.githubusercontent.com/50000521/187800885-8ebc2b33-f610-4f78-9f66-7d7ee271fd2a.png)

**Comment by Axarsam** [comment]
And Direwolf20 1.18, i wonder if its some automated task set to start at midnight on the 1st of the month.
![bug ftb](https://user-images.githubusercontent.com/112592273/187801723-5a7c160d-2d04-44bf-b41c-d0420493f4e0.JPG)

**Comment by rbneville** [comment]
The launcher is trying to connect to the mod host dist.modpacks.ch which is currently returning ERR_SSL_PROTOCOL_ERROR causing the launcher to throw an exception.

**Comment by Brontalos** [comment]
also infinity evolved.

![bug](https://user-images.githubusercontent.com/112592608/187802386-94c54117-534b-4499-b418-54be9f9ec1ab.png)

**Comment by Mavial** [comment]
Related: Installing mod packs in generally not available 
![Screenshot 2022-09-01 013510](https://user-images.githubusercontent.com/35010625/187802974-c26c0041-427f-4af9-ace3-40266e78883a.png)

**Comment by MisterMemetic** [comment]
I tried reinstalling everything, and nothing worked, glad it's not just me!

**Comment by TPoltergeist** [comment]
I had this issue on Endeavor 1.19 as well, and after uninstalling I am now unable to install anything related to any modpack.

**Comment by MisterMemetic** [comment]
Also I'm not seeing preview pictures
![FTB App 8_31_2022 4_37_26 PM](https://user-images.githubusercontent.com/112592939/187803251-fabbeb5e-3f73-4f05-9ed0-92f95573b849.png)

**Comment by TPoltergeist** [comment]
![image](https://user-images.githubusercontent.com/112592933/187803371-c84efc96-5fc8-45c8-bb2f-cee0b49ea06c.png)
I am seeing the same thing as above.

**Comment by curtiseast** [comment]
Seems like this is a global issue, hopefully they fix it soon

**Comment by aarong2051** [comment]
Having the same issue. Tried uninstalling the program and deleting all files. No luck. Also glad its not just me having issues

**Comment by InkPara** [comment]
^

**Comment by Marqin** [comment]
Why does it even need to connect to external servers to play a localy installed version? This is terrible UX

**Comment by Brontalos** [comment]
Launcher is working again for me.

**Comment by Axarsam** [comment]
Yep, works for me too. Fixed in under an hour, Bravo
