### ISSUE TITLE
[Bug]: Stuck on initializing instance, also unable to install new modpacks

### ISSUE THREAD

**Issue by thatpissedginger** [FTBTeam/FTB-App#676]
### What Operating System

Windows 10

### App Version

202208131844-e5790011d3-release

### UI Version

202208131844-e5790011d3-release

### Log Files

https://pste.ch/yacizejahi

### Debug Code

FTB-DBGIBANAJAKIH

### Describe the bug

Unable to launch installed modpacks or browse for new modpacks for reinstall

### Steps to reproduce

1. Open Launcher
2. Modpack may or may not appear
3. If modpack does appear, it will only get stuck on Initializing Instance
4. If not, browsing for any new modpacks only errors out.

### Expected behaviour

I hoped to open the launcher and launch the modpack

### Screenshots

![image](https://user-images.githubusercontent.com/8212334/188250841-ea65318d-74ed-4ff7-aa5c-6a1070c3dc9b.png)

![image](https://user-images.githubusercontent.com/8212334/188250849-084c48d9-b3b6-4fa1-a301-ff00ffec7bac.png)

![image](https://user-images.githubusercontent.com/8212334/188250886-306a9aa3-d903-41c1-813d-c56d07133bf5.png)

![image](https://user-images.githubusercontent.com/8212334/188250897-17b6aa96-3e6e-426e-94c1-7cd72a98ff73.png)

![image](https://user-images.githubusercontent.com/8212334/188250904-05b4a8b0-5cd0-43e3-a521-f5f7a3f7b8a4.png)

![image](https://user-images.githubusercontent.com/8212334/188250926-e3c01d72-b715-42e8-b3d5-c5d7726f9233.png)

### Additional information

Verified allowing communication through windows firewall (
![image](https://user-images.githubusercontent.com/8212334/188250935-4511e274-30a2-4db2-982e-6a7f964b54bc.png)
)

Verified no hits in my UDM-PRO for anything FTB, CurseForge, or anything of that matter.

### Information

- [X] I have provided as much information as possible

**Comment by ed-girard** [comment]
@thatpissedginger - you mention UDM-PRO in your issue, I've the same, try this:
Settings > Security > Internet Threat Management > Toggle off/Toggle on
This restored pulling of modpack info from api.modpacks.ch for me
