### ISSUE TITLE
[Bug]: Cant change java version

### ISSUE THREAD

**Issue by Joly0** [FTBTeam/FTB-App#683]
### What Operating System

Windows 10

### App Version

202208131844-e5790011d3-release

### UI Version

e5790011d3

### Debug Code

FTB-DBGFOHUNEBEDE

### Describe the bug

I cant change the java version used by an instance

### Steps to reproduce

1. Select instance
2. Go to settings
3. Click on "browse" next to the java version selector
4. Select one of the following things: Java root folder, java bin folder, java.exe, javaw.exe
5. Start the instance and check the used java version through task manager; the instance still uses the default instance java version, not the one selected

### Expected behaviour

The used java version should change to the one selected

### Additional information

I have tried multiple java versions from adoptium and have tried installations and portables, none work.

### Information

- [X] I have provided as much information as possible

**Comment by Joly0** [comment]
This is still an issue

**Comment by Joly0** [comment]
Still an issue

**Comment by MichaelHillcox** [comment]
Merging with #698
