### ISSUE TITLE
cant plant on Rich soil farmland[Bug]: 

### ISSUE THREAD

**Issue by Badspud** [FTBTeam/FTB-App#687]
### What Operating System

Windows 10

### App Version

FTB Inferno

### Debug Code

no

### Describe the bug

bad dirt

### Steps to reproduce

in FTB Inferno rich soil takes only mushrooms even when tilled

### Expected behaviour

to plant seeds

### Information

- [X] I have provided as much information as possible

**Comment by n1306** [comment]
I have the same problem: I can not plant any seeds except for the industrial hemp seeds from Immersive Engeniering. 
Nothing else can be planted.
