### ISSUE TITLE
[Bug]: app opens empty have tryied everything ive found in support to fix

### ISSUE THREAD

**Issue by Bountynz** [FTBTeam/FTB-App#692]
### What Operating System

Windows Insider Preview

### App Version

202209221900-9dcfe8c658-release

### UI Version

9dcfe8c658

### Log Files

https://pste.ch/ajuvoqolaz

### Debug Code

FTB-DBGKEZEBAHENE

### Describe the bug

FTB-DBGKEZEBAHENE

### Steps to reproduce

open ftp launcher 
no errors show
says loading
nothing loads 

### Expected behaviour

modpacks to be displayied so i can isntall them rather than blank pages

### Screenshots

modpacks to be displayied so i can isntall them rather than blank pages

### Additional information

windows 11

### Information

- [X] I have provided as much information as possible

**Comment by wjrwilton** [comment]
Friend had this issue, but went away after they deleted their user account (click on your account face bottom left) and re-added it.
I would presume it is an authentication issue.
