### ISSUE TITLE
[Feature request] Let user rename instance folder to logical name i.s.o. unreadable name

### ISSUE THREAD

**Issue by Nemelis** [FTBTeam/FTB-App#697]
**Is your feature request related to a problem? Please describe.**
As a programmer myself I like to be able to quickly see what a folder is about by looking at the name of the folder.
But FTB creates garbled names as folder names for its instances. For example: af2486b0-5caf-453e-ac79-c2a50f78a026 for my FTB Academy 1.16 folder.
"FTB Academy 1.16" would tell me directly what the instance is about, where the garbled name is a mystery if you have multiple different instances.

Note: in the attached picture I did a strikethrough of all Curseforge instances (which btw all have logical names)
![FTB_instance_names](https://user-images.githubusercontent.com/35840579/197175420-d4477468-23a6-48d7-95cb-0c0a272bca8c.JPG)

**Describe the solution you'd like**
An option in the app to let the user choose/rename the name of the folder i.s.o. forcing a garbled name.

**Describe alternatives you've considered**
Creating a copy of the original garbled folder and import that in the app - tried it, it did not work. 
(See yellow marked folder in the attached picture)

**Additional context**

**Comment by leagris** [comment]
The instance folder name shall not be a human-hostile UUID. This is garbage for humans to read. It makes navigating the instances filesystem from file managers, shells whatever, humanly impracticable.

**Comment by MichaelHillcox** [comment]
This has been fixed as of `1.25.7` :+1: Instances are now stored in human readable folder names
