### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PharoCat** [FTBTeam/FTB-App#699]
### What Operating System

Windows 10

### App Version

202209221900-9dcfe8c658-release

### UI Version

9dcfe8c658

### Log Files

https://pste.ch/pikixevize

### Debug Code

FTB-DBGMIVAKAFALU

### Describe the bug

When launching a modpack (atm7 to the sky) the launcher is indefinetely stuck on Pre-Start Task

### Steps to reproduce

1. Open the FTB launcher 
2. Launch Modpack

### Expected behaviour

I expected the pack to load correctly and start playing

### Screenshots

![image](https://user-images.githubusercontent.com/111052208/198274501-66024ae7-73dd-4080-bc60-e41cea2ad8ab.png)

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Looks like the debug code has expired, sorry about that, could you open a new issue if this is still a problem? Thanks :D
