### ISSUE TITLE
Erro while downloading FTB Omnia pack

### ISSUE THREAD

**Issue by AmumuSouls** [FTBTeam/FTB-App#70]
Hi, I get the next error while starting to install FTB Omnia pack:

"Error installing FTB Omnia - C:\...\AppData\Roaming\FTBA\instances\29652dea-ace4-42ab-961a-06c72ac3c52e\installer.jar"

I tried installing other mod packs and they work without problems.

I attach the logs available in the folder.
[error.log](https://github.com/FTBTeam/FTB-App/files/4455450/error.log)
[launcher.log](https://github.com/FTBTeam/FTB-App/files/4455451/launcher.log)

**Comment by Jake-E** [comment]
This should be fixed in 1.0.6.
