### ISSUE TITLE
[Bug]: Fatal exception whilst installing curseforge modpack

### ISSUE THREAD

**Issue by loleq2105** [FTBTeam/FTB-App#700]
### What Operating System

Windows 10

### App Version

202209221900-9dcfe8c658-release

### UI Version

9dcfe8c658

### Log Files

https://pste.ch/ufeyeyohoh

### Debug Code

FTB-DBGUVEKUXOTIB

### Describe the bug

A fatal exception occurs when attempting to download a certain curseforge modpack.

### Steps to reproduce

1. visit the page of the "Practical Engineering- Advanced Technology" modpack
2. attempt to install it
3. fail miserably

### Expected behaviour

I expected the pack to install

### Screenshots

![obraz](https://user-images.githubusercontent.com/52840858/198905104-926b11d9-c979-4aec-9535-759cc750576c.png)

### Additional information

The pack is an odd one overall, but I _have_ successfully installed it using an alternative launcher.

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
We've confirmed this is an issue and will have it fixed in the next or following update :+1:

**Comment by MichaelHillcox** [comment]
This has been fixed and released. If you're having any more issues related to this, please let me know
