### ISSUE TITLE
Your shitty app doesn't work with windows insider, which isn't a problem, but since you don't put your modpacks on your website or on modrinth, i'm stuck without the ability to use them. 

### ISSUE THREAD

**Issue by Zequiz** [FTBTeam/FTB-App#701]
### What Operating System

Windows Insider Preview

### Debug Code

FTB-DBGUNOBAZAWIR

### Describe the bug

Your shitty app doesn't work with windows insider, which isn't a problem, but since you don't put your modpacks on your website or on modrinth, i'm stuck without the ability to use them. 

### Steps to reproduce

> Run Windows Insider
> Try to open FTB
> Fails
> Look for the modpack elsewhere
> Don't find it
> Cry

### Expected behaviour

Modpacks are hosted on feed-the-beast.com as well as reputable mod distributors like Modrinth.

### Screenshots

You told me to go here and whine, so even though this isn't a bug i'm just following your instructions. Don't you dare complain about that.
![image](https://user-images.githubusercontent.com/61996958/199342871-74185de1-f050-4652-8a05-7e813ef20afe.png)
doesn't work
![image](https://user-images.githubusercontent.com/61996958/199342986-57b5d0da-99b4-4273-89db-a4193807f1fd.png)

### Information

- [X] I have provided as much information as possible

**Comment by ThePaul-T** [comment]
Stop using pre-release versions of operating systems then blaming other people for not searching the internet for how to bypass things designed to ensure stuff works correctly?

If you use pre-release software, expect pain, simple, that is not our fault.

https://support.overwolf.com/en/support/solutions/articles/9000197893-running-overwolf-on-windows-insider#override2

**Comment by sudolev** [comment]
> Stop using pre-release versions of operating systems

I said myself that the fact that you don't support Windows Insider isn't a problem. Read the fucking title.

What I take issue with is your anti-consumer, fascistic choice to buck standard practice and release your modpacks only on your proprietary app. If you cared about anything other than profit they would be mirrored on Modrinth, Github, Curseforge, or any other easily-accessible established distribution system.

You even brag about your moral corruption--"Our app is the only officially supported place to get our Modpacks!" with a revolting exclamation point like restricting your packs to a spyware-dependent, slow, single-purpose app with bad support is a good thing.
