### ISSUE TITLE
[Bug]: On Windows11 unable to align my Microsoft acc't to FTB launcher

### ISSUE THREAD

**Issue by JoelHud** [FTBTeam/FTB-App#702]
### What Operating System

Windows 11

### App Version

202209221900-9dcfe8c658-release

### UI Version

9dcfe8c658

### Log Files

https://pste.ch/odozewowuw

### Debug Code

FTB-DBGLEDIDATESA

### Describe the bug

Authorization FAIL not accepting successfull auth from Microsoft

### Steps to reproduce

1, try to start StoneBlock 3, 
2. log  into minecraft (microsoft) to authenticate [Successfull]
3. there was a problem... No Game For YOU!

### Expected behaviour

I wanna play!

### Screenshots

![Screenshot_20221101_084148](https://user-images.githubusercontent.com/73862168/199391404-3ab9eb2a-c968-41a2-91c2-a04eb3966cb6.png)
![Screenshot_20221101_084206](https://user-images.githubusercontent.com/73862168/199391409-95a845c0-0017-4501-9f05-1de88bc6c794.png)

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
```
404|https://api.minecraftservices.com/minecraft/profile responded with: {"path":"/minecraft/profile","error":"NOT_FOUND","errorMessage":"Not Found"}
```

This error indicates you have used the wrong Microsoft account or your Microsoft account doesn't own a paid copy of Minecraft.
