### ISSUE TITLE
[Bug]: Update Window without Text

### ISSUE THREAD

**Issue by kaiand1** [FTBTeam/FTB-App#703]
### What Operating System

Linux (Debian)

### App Version

202211021238-4322c4d8d1-release

### UI Version

4322c4d8d1

### Debug Code

FTB-NoDebugCode

### Describe the bug

Update Window without Text and a  Button ?

### Steps to reproduce

Use Old Version
Auto Update Enable
Start FTB App and wait for Auto Update....
Update Installed and no reproduce available......

### Expected behaviour

Fix the Informatin for Auto Update Window ;)

### Screenshots

![Screenshot_20221102_152916](https://user-images.githubusercontent.com/44444152/199516972-435e22b6-d7d2-4430-b077-e2ef3f98549f.png)

Start FTB App and Update Auto Installing.
But Window have a Button without Text...
Update works.

### Additional information

nothing...

### Information

- [X] I have provided as much information as possible

**Comment by tommyrobot666** [comment]
if you need to use an old version then that means it might have been fixed in a newer version
