### ISSUE TITLE
[Bug]: i cant load into a modpack bcz of instances issue

### ISSUE THREAD

**Issue by Knockbuck** [FTBTeam/FTB-App#705]
### What Operating System

Windows 10

### App Version

202211021238-4322c4d8d1-release

### UI Version

4322c4d8d1

### Log Files

m

### Debug Code

FTB-DBGCUSEVUDOMA

### Describe the bug

when i to launch sb3 modpack it says that it failed to prepare instance for it 

### Steps to reproduce

idk

### Expected behaviour

when i lounch the modpack for it to go into minecraft launcher and i can play it

### Screenshots

![image](https://user-images.githubusercontent.com/117300951/199545587-8e68ad74-15e4-40cf-84f4-192eb05bb6e7.png)
![image](https://user-images.githubusercontent.com/117300951/199545867-4613d802-bf28-45de-9f2a-3bf91faea170.png)

### Additional information

i have launched it yestruday and it worked when i want to launch it now it says a error occured in instances and idk what to do bcz this has never heppend to me

### Information

- [X] I have provided as much information as possible

**Comment by Knockbuck** [comment]
i re installed ftb app and it works for now but if it heppens again i would like to know how to fix it

**Comment by MichaelHillcox** [comment]
Looks like a temp networking issue. Looks to be solved :+1:
