### ISSUE TITLE
[Bug]: Fatal exception whilst installing modpack.

### ISSUE THREAD

**Issue by DeltaDzbanie** [FTBTeam/FTB-App#706]
### What Operating System

Windows 10

### App Version

202211021238-4322c4d8d1-release

### UI Version

4322c4d8d1

### Log Files

https://pste.ch/pilaqeyuwe

### Debug Code

FTB-DBGGAQORAHAZE

### Describe the bug

Fatal exception whilst installing modpack.

### Steps to reproduce

1. Try downloading FTB StoneBlock 3 trough the app
2. Fail

### Expected behaviour

I expected to normally download modpack

### Screenshots

![image](https://user-images.githubusercontent.com/117315900/199598400-34f660d5-6866-4be7-9067-984defe133e0.png)

### Information

- [X] I have provided as much information as possible

**Comment by MrBear2305** [comment]
i have the same problem and have tried everything to fix it and nothing is working

**Comment by Ragnadom** [comment]
I have also run into this problem. Has anything been found for it yet?

**Comment by MichaelHillcox** [comment]
https://appsdl-overwolf-com.akamaized.net/prod/apps/cmogmmciplgmocnhikmphehmeecmpaggknkjlbag/1.23.622.1340/app.opk

Please try with this version of the app. Make sure your current version of the app is closed. Let me know if you have any more issues.
