### ISSUE TITLE
[Bug]: FTB Inferno crashes after muting Minetogether chat

### ISSUE THREAD

**Issue by Reaper9802** [FTBTeam/FTB-App#708]
### What Operating System

Windows 10

### App Version

202211021238-4322c4d8d1-release

### UI Version

4322c4d8d1

### Debug Code

FTB-DBGJOXAREMEGU

### Describe the bug

Muted myself from the Minetogether chat window. Game crashed right afterwards

### Steps to reproduce

1. Boot up FTB Inferno
2. Select Single Player
3. Log into saved world
4. Started seeing chat scroll vertically on the left side of the screen
5. Pressed '/' to open chat line
6. Could barely see a "Mute" button behind the text. Clicked on it
7. The side chat stopped and then the game crashed
8. Restarted instance -> Single Player -> Load Saved World
9. Pressed '/' again
10. Command/Minetogether window opened, see the minetogether logo then the game crashes

### Expected behaviour

Be able to mute the chat and still be able to open the command window without crashing

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
This should be fixed, if not, report the issue here https://github.com/CreeperHost/MineTogether/issues
