### ISSUE TITLE
Can't download modpacks

### ISSUE THREAD

**Issue by 0something0** [FTBTeam/FTB-App#71]
The modpack hangs on "creating environment" for about 15 minutes and now on "Installing vanilla launcher" for who knows how long. 

https://pste.ch/ulamoyaqaq

**Comment by egor100500** [comment]
OS: Ubuntu 18.04.4

App stays on "Installing Vanilla Launcher" forever
Logs: https://pste.ch/jarelazari

![image](https://user-images.githubusercontent.com/33977079/79114408-e38fce00-7d8b-11ea-9219-644272a62c0a.png)

**Comment by staircrusher** [comment]
I have exactly the same issue on Linux Mint 19
Endless "Starting download of the vanilla launcher"
https://pste.ch/pefilovoqo.sql

**Comment by erus** [comment]
Same issue here on an up to date Archlinux, stuck at "Installing Vanilla Launcher..." with "INFO: Starting download of the vanilla launcher" as the last line in the logs.

**Comment by bithorder** [comment]
I had the same problem in Ubuntu 20.04, found out my issue was a missing libgconf-2.so.4
fixed by running:
sudo apt install libgconf-2-4

**Comment by erus** [comment]
> I had the same problem in Ubuntu 20.04, found out my issue was a missing libgconf-2.so.4
> fixed by running:
> sudo apt install libgconf-2-4

THANKS !

Issue fixed for me after installing gconf package from AUR.

**Comment by jleonardfl** [comment]
I'm also having this problem on arch, I've installed gconf from the AUR and it's just started installing the vanilla launcher after about 20 minutes creating the environment.  Does the "creating environment" hang deserve its own thread?

My log doesn't have any related errors, but there's also an error about a missing jar for logging so I don't know how much that's worth.

**Comment by EmberQuill** [comment]
I have the same issue even after installing gconf. It's stuck on Creating Environment right now. I checked the log and saw a whole bunch of checksum failure warnings, 404 errors, and file size mismatches, and then nothing for the last 15 minutes.

Here's my log: https://pste.ch/unudopihof.sql

**Comment by john01dav** [comment]
It's stuck on the vanilla launcher thing for me on Debian 10, in a VM with libgonf-2.4 installed.

**Comment by csonyi** [comment]
same problem on an up-to-date Manjaro installation.
i have gconf installed, it hangs on "Downloading Vanilla Launcher..."
I even tried installing lib32-gconf, but it didnt help either...

**Comment by john01dav** [comment]
@csonyi Until the launcher team fixes this, [this](https://github.com/jamiemansfield/mcinstall) tool works a lot better on Linux, and it doesn't try to do questionable things like installing its own JRE.

**Comment by csonyi** [comment]
> @csonyi Until the launcher team fixes this, [this](https://github.com/jamiemansfield/mcinstall) tool works a lot better on Linux, and it doesn't try to do questionable things like installing its own JRE.

thanks man, I managed to solve the problem.
I ran the launcher on windows, and copied the instance folder over to MultiMC on linux and created the instance files for it.
It works like a charm.
I know the ppl at FTB want us to use their launcher, and I would have no problem with that (it looks good, tho it could be more intuitive). But if they can't make it work 100% (and no, linux is NOT an edgecase...), they could at least provide .zip downloads on their site for the packs only available through the FTB-App, or add them to the legacy launcher too or smth.
I've been trying to get this godforsaken thing to work for almost a week, I was at the point where I downloaded the front and backend separately (why would you create something this way is beyond me too, its insanely convoluted to install from source),
and Tinker around until I can Construct a version that works for me. At some point I gave up and had the idea that eventually worked.

**Comment by verticaljelly** [comment]
This problem is reported for several months, I have it on all my machines, including on Windows 10 latest update. Is it going to be resolved in any way? 
on MacOS it just won't go past downloading the Minecraft.app file from Mojang... downloading it works perfectly as I could play with that version (although I changed the password immediately after as I already don't trust this system)
Can you guys just make packaged zip files to download the packs and leave the app to be just a convenience feature ? (Curse had it that way since like... forever)

**Comment by Gaz492** [comment]
Hello,

Does everyone that reported the issue here still have this issue with the latest version of the app?

**Comment by chrisrk** [comment]
I have the same issue on the latest version for MacOS! My launcher is stuck on "Installing Vanilla Launcher" and nothing will happen. Another issue when I use the Twitch launcher, my server does not work because it says "Incompatible FML modded server" "237 mods present"! 

Is there any way you can help me with this?  Thanks.

**Comment by chrisrk** [comment]
> Hello,
> 
> Does everyone that reported the issue here still have this issue with the latest version of the app?
> If you do can you open a new issue regarding this so we can track this issue better?

I have the same issue on the latest version for MacOS! My launcher is stuck on "Installing Vanilla Launcher" and nothing will happen. Another issue when I use the Twitch launcher, my server does not work because it says "Incompatible FML modded server" "237 mods present"! 

Is there any way you can help me with this?  Thanks.

**Comment by Gaz492** [comment]
> > Hello,
> > Does everyone that reported the issue here still have this issue with the latest version of the app?
> > If you do can you open a new issue regarding this so we can track this issue better?
> 
> I have the same issue on the latest version for MacOS! My launcher is stuck on "Installing Vanilla Launcher" and nothing will happen. Another issue when I use the Twitch launcher, my server does not work because it says "Incompatible FML modded server" "237 mods present"!
> 
> Is there any way you can help me with this? Thanks.

Can you go into the settings page and enable the preview 
Could you open a new issue for us and provide the information requested in the bug report template.
The issue may look the same, however its possible that you are experiencing a different issue.

**Comment by filippo95poli** [comment]
<img width="999" alt="Screenshot 2020-10-28 at 11 27 31" src="https://user-images.githubusercontent.com/73562884/97424130-92eb5700-1910-11eb-8792-f0de045d1a38.png">
The ftb launcher is continuing unsuccessfully to install the vanilla launcher. I've tried to fix the issue by enabling the preview versions, by reinstalling the launcher and by uninstalling the old ftb launcher. Can someone help me?

**Comment by jth1903** [comment]
x-special/nautilus-clipboard
copy
file:///home/jth1903/.ftba/ftbapp.log

I am having the same issue when it tries to install vanilla launcher it cannot configure for linux 20
