### ISSUE TITLE
[Bug]: Can not install modpack

### ISSUE THREAD

**Issue by Yuqi154** [FTBTeam/FTB-App#710]
### What Operating System

Windows 10

### App Version

202211021238-4322c4d8d1-release

### UI Version

4322c4d8d1

### Log Files

(http://file.yousatown.cn/debug.log)

### Debug Code

FTB-DBGEZAHUCIVEH

### Describe the bug

can't install the modpack

### Steps to reproduce

1.open ftbapp
2.install stoneblock3
3.fatal exception

### Expected behaviour

install sucess

### Screenshots

![Snipaste_2022-11-04_23-43-09](https://user-images.githubusercontent.com/92249309/200017244-6ff4f19c-f139-4509-912e-29a4acadc7bc.png)
![Snipaste_2022-11-04_23-43-14](https://user-images.githubusercontent.com/92249309/200017248-7b89a153-2159-472d-93ab-34944e60b58f.png)

### Information

- [x] I have provided as much information as possible

**Comment by Yuqi154** [comment]
file.yousatown.cn/debug.log

**Comment by zekoo96** [comment]
hello I'm having the same problem and I could not fix, if you fix it can you tell me how?

**Comment by mz0-5** [comment]
me too please give me a solution

**Comment by Yuqi154** [comment]
l got the modpack successfully from prism lancher instead

**Comment by Yuqi154** [comment]
> hello I'm having the same problem and I could not fix, if you fix it can you tell me how?


> me too please give me a solution

you can got it here
https://file.yousatown.cn/modpack/
use MMC PRIEM HMCL PCL to lancher
