### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by POUKY** [FTBTeam/FTB-App#711]
### What Operating System

Windows 10

### App Version

202211021238-4322c4d8d1-release

### UI Version

4322c4d8d1

### Debug Code

FTB-DBGZILAXUMUJI

### Describe the bug

Add Mods page Load not all Mods

### Steps to reproduce

First you go on any instance,
click then on "Add More Mods" tipe for example villager in the searchbar.
Then results 5/50.

### Expected behaviour

Show me the Mods so i can add them to the Modpacks

### Additional information

I want to see what Mods i will add to the modpacks and not only a few most of the time I get 2 from 7 resuts so not all,
ore it get stuck in the loading from the mods and show nothing at all.

Is that because not all mads are one the Game version? If thats so why im getting not allways the same mods?

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Did you try to click load more?
