### ISSUE TITLE
[Bug]: Error Installing and Launching the game failed

### ISSUE THREAD

**Issue by baransocksatthis** [FTBTeam/FTB-App#712]
### What Operating System

Windows 10

### App Version

202007161516-479dedc615-release

### UI Version

39f37b8d

### Log Files

"There was an error uploading your logs"

### Debug Code

FTB-DBGAFEMAGOVIB

### Describe the bug

I downloaded and tested out Stoneblock 3. I closed the modpack and reopened it a day later. The launcher opened but i could not open the modpack it said "Launching the game failed". There was more important information there aswell but i cannot access the launcher anymore. I reinstalled the modpack tried it out again it worked, closed it and then returned in a couple of hours.  I got the prior error message so i tried to reinstall the modpack again but i could not reinstall it instead i got a message saying "Error installing FTB Stoneblock 3 - C:\Users\[Name]\.ftba\instances\6894dd7d-7c3b-4a1a-9974-326ed1dfd117\installer.jar"

### Steps to reproduce

Cannot Install
1. Go to "Browse"
2. Search for "Stoneblock 3"
3. Click "Get"
4. "Error installing"
Cannot open when installed
1. Open "Stoneblock 3" launcher
2. Press play
3. "Launching the game failed"

### Expected behaviour

Installing/ Launching

### Screenshots

![image](https://user-images.githubusercontent.com/73852773/200071120-5defc813-503d-49f4-803a-eface5a8af0d.png)

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Please update your app :D
