### ISSUE TITLE
[Bug]: i cant login with minetogether on the app

### ISSUE THREAD

**Issue by gus637** [FTBTeam/FTB-App#715]
### What Operating System

Windows 10

### App Version

202211021238-4322c4d8d1-release

### UI Version

4322c4d8d1

### Debug Code

FTB-DBGWOTEMEQICO

### Describe the bug

when i try to login with mine together in the ftb app, nothing hapens

### Steps to reproduce

1. go to setting then Integrations
2. click on "Login to setup"
3. login on browser

### Expected behaviour

to have login to the app

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Debug code seems to not be valid, likely super old. Closing for now but can you confirm if this is still an issue?

**Comment by norm1000100** [comment]
Old issue but i'd like to reopen it if possible

**Comment by CarbonFoggy** [comment]
same issue, nothing helps

**Comment by Spontini** [comment]
Same issue
