### ISSUE TITLE
[Bug]: Minecraft starts to load but after a second it crashes

### ISSUE THREAD

**Issue by BeepBoop123333** [FTBTeam/FTB-App#717]
### What Operating System

Windows 10

### App Version

202211021238-4322c4d8d1-release

### UI Version

4322c4d8d1

### Log Files

https://pste.ch/ovobenarav

### Debug Code

FTB-DBGOZICEZAHOW

### Describe the bug

I added some mods to FTB One, and it starts to load, but it crashes after a second of actually launching minecraft. I've attached a screenshot of the mods I added.

### Steps to reproduce

Can't really reproduce it unless you download all the mods and add them to the pack, the launch it

### Expected behaviour

These are my favorite mods and I thought they would work if I added them to this pack.

### Screenshots

![image](https://user-images.githubusercontent.com/117519884/200119847-d10811a9-1b2b-489a-8e4f-834e8f081c9a.png)

### Information

- [x] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Pack needs more ram. Also not an app issue.
