### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TavyReal** [FTBTeam/FTB-App#718]
### What Operating System

Windows 10

### App Version

202211021238-4322c4d8d1-release

### UI Version

4322c4d8d1

### Debug Code

FTB-DBGEWIHOPIHOT

### Describe the bug

Fatal exception whilist installing modpack

### Steps to reproduce

1. Go to Browse
2. Find FTB StoneBlock 3
3. Click on download button
4. wait until the error appear

### Expected behaviour

I want to install/download the modpack

### Screenshots

![Screenshot_2](https://user-images.githubusercontent.com/62476147/200127336-977fe1e0-8215-4c57-9841-151118c1a262.png)

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Firewall / Antivirus / Network issue. Please ensure this domain `modpacks.ch` is allow.
