### ISSUE TITLE
[Bug]: StoneBlock 3 crashes on startup - java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by llflory** [FTBTeam/FTB-App#719]
### What Operating System

Windows 10

### App Version

202211021238-4322c4d8d1-release

### UI Version

4322c4d8d1

### Log Files

[crash-2022-11-05_20.30.17-client.txt](https://github.com/FTBTeam/FTB-App/files/9944496/crash-2022-11-05_20.30.17-client.txt)

### Debug Code

FTB-DBGUGAMOSOFAZ

### Describe the bug

StoneBlock 3 crashes on startup

### Steps to reproduce

1. Click on Play button from FTB StoneBlock 3
2. Minecraft fails to start

### Expected behaviour

Minecraft starts correctly

### Additional information

I assume that this has something to do with me disabling "Mine Together Chat" on my last session (earlier today), since I saw the message in the crash report that mentions that one of the MineTogetherChat classes has not been found.
I am playing in single-player-mode and found the chat annoying, and I clicked a button to disable it.

I've tried tweaking the JVM arguments, but there shouldn't be any issue there, since they are the ones that I've been using so far.

I haven't added or tried to remove any of the mods, and haven't changed any of the game files.

### Information

- [X] I have provided as much information as possible

**Comment by llflory** [comment]
I was able to play by removing the mineTogether jar-file from the mods folder (I moved it into a new directory, outside the mods directory).

**Comment by MichaelHillcox** [comment]
Should be fixed in newer versions of the pack, not an app issue.

**Comment by Terminator81** [comment]
same problem here, i tried other launcher like gdlauncher too, yesterday it worked fine ...today error...

**Comment by djantonio96** [comment]
> same problem here, i tried other launcher like gdlauncher too, yesterday it worked fine ...today error...

bro,just unistall better than lamas mod in mods folder,
it is this mod that crashes

**Comment by snuke704** [comment]
I tried to look for this mod in the folder but there is no

**Comment by weouthereinthesun** [comment]
> Should be fixed in newer versions of the pack, not an app issue.

crashed today as of 3 am, tried every beta version of the pack, including the latest one, and the very first release

**Comment by DrunkTaank** [comment]
Also coming to confirm that disabling Better Than Llamas fixed the crash for me as well.
