### ISSUE TITLE
Linux Issue by trying to install the New FTB Launcher.

### ISSUE THREAD

**Issue by Storyboard-MC** [FTBTeam/FTB-App#72]
Hello I have an issue when using the Linux Installer on Ubuntu 18.04 LTS 
and the installer does an error about the Downloaded file is corrupted.

Heres the Image of what is says: https://drive.google.com/file/d/1YW_SWIZ39PnZ8gtywXsUMnr2hPbIO_ts/view?usp=sharing

Please could you fix this issue ! Thanks

**Comment by Rushmead** [comment]
Have you tried restarting the installer or pressing "ok" to try again? Does it do the same everytime you try to install?

**Comment by Jake-E** [comment]
Can you try using the latest version of the installer:
https://apps.modpacks.ch/FTBApp/release/1.0.6/FTBA_windows-x64_1_0_6.exe

**Comment by gameskip** [comment]
I have a similar issue, in that it's similar to #44 but I am on linux Ubuntu 20.10 i believe
![Screenshot_20211106_122120](https://user-images.githubusercontent.com/93346414/140606257-57c9e0fb-d054-40ba-89cd-de8a0971d1d3.png)

Installer: FTBA_unix_202110071354-4bdfd15050-release.sh
.
