### ISSUE TITLE
[Bug]: not installing the modpack

### ISSUE THREAD

**Issue by tttminer** [FTBTeam/FTB-App#720]
### What Operating System

Windows 10

### App Version

202211021238-4322c4d8d1-release

### UI Version

202211021238-4322c4d8d1-release

### Log Files

https://pste.ch/muroxekeha
https://pste.ch/nizomewoza
https://pste.ch/yinawimexo
https://pste.ch/lahomufine
https://pste.ch/ujepuluvon
https://pste.ch/wekijiradi

### Debug Code

FTB-DBGOVEZIPISAJ

### Describe the bug

i try to install stoneblock 3 it gets stuck on installing the modloader

### Steps to reproduce

go to stoneblock 3 
click install the newest version 

### Expected behaviour

to dowload the modpack

### Screenshots

![imagem](https://user-images.githubusercontent.com/112357576/200138695-41be4386-3c8f-4a90-975a-084752290a90.png)

### Information

- [X] I have provided as much information as possible

**Comment by MomJeans1** [comment]
have you figured the issue yet because i have the same problem

**Comment by MichaelHillcox** [comment]
`Failed to connect to apps.modpacks.ch/188.114.97.5:443`

Please ensure modpacks.ch is allowed through your firewall & network. In some cases, antivirus software can also cause this.
