### ISSUE TITLE
[Bug]: StoneBlock 3 crashes on startup

### ISSUE THREAD

**Issue by MrPogoreniym** [FTBTeam/FTB-App#721]
### What Operating System

Windows 10

### App Version

202211021238-4322c4d8d1-release

### UI Version

4322c4d8d1

### Log Files

[crash-2022-11-05_23.35.45-client.txt](https://github.com/FTBTeam/FTB-App/files/9944734/crash-2022-11-05_23.35.45-client.txt)

### Debug Code

FTB-DBGELOBAPAQIL

### Describe the bug

StoneBlock 3 crashes on startup

### Steps to reproduce

1. Click on Play button from FTB StoneBlock 3
2, FTB StoneBlock 3 has crashed! Looks like the instance has crashed during startup or whist running,

### Expected behaviour

StoneBlock 3 starts correctly

### Additional information

I played FTB Stoneblock 3 for a few days and everything was fine. Today I decided to increase the amount of RAM for the modpack from the standard 6 GB in the FTB launcher settings. After that, it started crashing when starting FTB Stoneblock 3.

I haven't added or tried to remove any of the mods, and haven't changed any of the game files.

### Information

- [x] I have provided as much information as possible

**Comment by MrPogoreniym** [comment]
I was able to play by removing the minetogether-forge-1.18.2-6.0.8.jar - file from the mods folder (I moved it into a new directory, outside the mods directory).

**Comment by MichaelHillcox** [comment]
This is fixed in newer versions of the modpack, not an app issue
