### ISSUE TITLE
[Bug]: Basic Induction Cell recipe not available in REI.

### ISSUE THREAD

**Issue by adamras** [FTBTeam/FTB-App#722]
### What Operating System

Windows 10

### App Version

1.0.2

### Debug Code

FTB-DBGESIZUHARIQ

### Describe the bug

Hitting "U" in REI for Basic Induction Cell by Mekanism does not show how to make it.  All other cells show how to make them.

### Steps to reproduce

Click "U" when hovering over "Basic Induction Cell". 

### Expected behaviour

Show how to make the item 

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Wrong repo
