### ISSUE TITLE
[Bug]: Fatal excemption whilst trying to install modpack

### ISSUE THREAD

**Issue by Danydew** [FTBTeam/FTB-App#725]
### Modpack

FTB Stoneblock 3

### Modpack version

any

### Log Files

https://pastebin.com/NT23Y1x0

### Describe the bug

Randomly today after being able to download all modpacks I went to download Stoneblock 3 , it says preparing for download, then initializing modloader and after that gives an error "Fatal excemption whilst trying to install modpack", the same happens for Inferno or Direwolf, the only one that installs is Ocean
![Screenshot_27](https://user-images.githubusercontent.com/104875529/200196053-159c7aac-f988-40f1-b0f6-b08d8839b498.png)

### Steps to reproduce

1. Open FTB app
2. Go to browse
3. Choose Stoneblock 3, install any version

### Expected behaviour

Instance install

### Screenshots

![Screenshot_27](https://user-images.githubusercontent.com/104875529/200196163-be20dbbc-39c5-4568-88df-5be69231393b.png)

### Additional information

I tried shutting down the program and Java in task manager, I also reinstalled Overwolf and FTB and the same thing happens

**Comment by Tychee** [comment]
im having same issue did u find a fix for this?

ive reinstalled both ftb/overwolf and java
turned off firewall and i dont have a antivirus

**Comment by Onikage056** [comment]
> im having same issue did u find a fix for this?
> 
> ive reinstalled both ftb/overwolf and java turned off firewall and i dont have a antivirus

Try using AT Launcher to install it.
I couldn't get it to work on Overwolf for w/e raisin.

**Comment by Hawkeye131** [comment]
idk it seems to work now

**Comment by billsKatie** [comment]
I am having this problem also.

**Comment by MichaelHillcox** [comment]
Looks like SSL issues, please ensure the following domains are allowed in your network and firewall settings. This includes anti-viruses 

`modpacks.ch`
`api.modpacks.ch`
`*.curseforge.com`
`mojang.com`
`microsoft.com`
