### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by bithhub** [FTBTeam/FTB-App#727]
### What Operating System

Windows 10

### App Version

1.4.0

### UI Version

1.4.0

### Debug Code

FTB-DBGBASESISIJI

### Describe the bug

Yesterday I could play Stoneblock 3 then today i can't run it. I tried to log in again by deleting my current account on FTB app and now i can't log back in. When i try, an error shows up

### Steps to reproduce

click account
press the red bin button
can't log back in with Minecraft microsoft account

### Expected behaviour

To be able to launch stoneblock3

### Screenshots

![Screenshot (23)](https://user-images.githubusercontent.com/117700333/200461764-0840a7ab-c60b-4b42-b342-0174a2935037.png)

### Information

- [X] I have provided as much information as possible

**Comment by SkittleRL** [comment]
Having the same issue

**Comment by MichaelHillcox** [comment]
Auth server issues, should be fixed now
