### ISSUE TITLE
[Bug]: Microsoft Account

### ISSUE THREAD

**Issue by SkittleRL** [FTBTeam/FTB-App#728]
### What Operating System

Windows 10

### App Version

1.4.0

### UI Version

4322C4d8d1

### Debug Code

FTB-DBGIGOGISOLUB

### Describe the bug

Cannot verify software owned on microsoft account

### Steps to reproduce

1. Open FTB App
2. Launch modpack
3. Prompt opens asking for a login
4. login using microsoft login
5. Error Unable to login with xbox live to your Minecraft account

### Expected behaviour

Expected to log in and run SF3, works on curseforge

### Screenshots

![image](https://user-images.githubusercontent.com/117702038/200466318-a5385fc3-2333-4bd6-8898-07cb16ca1a88.png)

### Additional information

I do own minecraft java edition

### Information

- [X] I have provided as much information as possible

**Comment by PhazedPheonix** [comment]
I am having the same exact issue.

**Comment by Nieblue** [comment]
We are all having the same issues and it involves Stoneblock 3 ... unfortunatly none of my instances work in FTB app now, but it was not an issue this morning.  The only thing I did was adjusted how much memory it uses and now it doesn't work

**Comment by Zppj0** [comment]
Same

**Comment by PhazedPheonix** [comment]
Yep, that was the last mod pack I used. Didn't think that was the issue.

**Comment by NisusAlcanta** [comment]
It is the authentication serves not Curseforge or FTB app. This from down detector: 
"@mojangsupport finally acknowledged the outage:
"We are aware that some players are having trouble accessing servers right now. We are actively working on a fix. jhp""

**Comment by ii-richie** [comment]
I installed StoneBlock 3 and after crashing a few times, went back to playing Plexiglass Mountain. After closing and relaunching that modpack to test for this issue I can no longer play any modpacks; having the same symptoms as described above.

**Comment by MadCreature** [comment]
im also having the same problem, game crash after that i could not log back in FTB app can even log me in  or find my profile,
we never had this problem with mojang.

**Comment by tyler489** [comment]
> im also having the same problem, game crash after that i could not log back in FTB app can even log me in or find my profile, we never had this problem with mojang.

This is a mojang isssue, not an ftb issue.

**Comment by Rik034** [comment]
Can confirm this is a Mojang issue, I had trouble logging in to the Minecraft website and the vanilla launcher says it can't connect to the Minecraft services.

**Comment by SoCal-Absol** [comment]
I wanted to play a skyfactory 3 world I built up but now I can't. I'm having the same error as everyone else.

**Comment by MadCreature** [comment]
Lets see how long it will take them to fix this problem

**Comment by Rik034** [comment]
![1667886521_grim](https://user-images.githubusercontent.com/60218806/200485212-28f59ef9-a3b0-4018-86d3-39a5f8eb0fd1.png)
This is what I get from MultiMC, definitely a Mojang issue.

**Comment by MadCreature** [comment]
ya im having the same message

**Comment by zrx2021** [comment]
Same

**Comment by goooosty** [comment]
Have been having this issue for three days now. 
Just want to play my block game with my friends

**Comment by Rik034** [comment]
> Have been having this issue for three days now. Just want to play my block game with my friends

I just opened FTB App and MultiMC and they work now.
I am able to play block game.

**Comment by MichaelHillcox** [comment]
Auth server issues,s hould be fixed
