### ISSUE TITLE
[Feature request] Clearer names on ftb instances

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-App#729]
**Is your feature request related to a problem? Please describe.**
When looking in the FTB folders, FTB Instances are a random string of characters rather than a pack name

**Describe the solution you'd like**
Replace this string with some sort of better pack identifer, like a pack name. 

**Describe alternatives you've considered**

**Additional context**
https://gyazo.com/fef788d8bcc1faa4d2f2004db361257b FTB
https://gyazo.com/325d543817921e41ba52e1a9cf73a068 Curseforge
A lot easier to figure out which pack is which on curseforge.

**Comment by MichaelHillcox** [comment]
This has been fixed as of `1.25.7` :+1: Instances are now stored in human readable folder names
