### ISSUE TITLE
[Bug]: Launcher Gets Stuck Loading

### ISSUE THREAD

**Issue by Linkling64** [FTBTeam/FTB-App#730]
### What Operating System

MacOS (Latest)

### App Version

202211021238-4322c4d8d1-release

### UI Version

4322c4d8d1

### Debug Code

How am I supposed to run this. It is just a text file. Sorry

### Describe the bug

When I try launching the game, the launcher always gets stuck at some point trying to load.

### Steps to reproduce

1. Go to the launcher
2. Try launching Stoneblock 3
3. Wait and eventually it gets stuck loading some file (not always the same file)

### Expected behaviour

Minecraft launches

### Screenshots

<img width="911" alt="Screenshot 2022-11-08 at 11 50 01 AM" src="https://user-images.githubusercontent.com/117760628/200625977-b986a86e-8d46-43c6-9fb6-649047fa9728.png">
This is the screen where it gets stuck on.

### Additional information

I downloaded the Launcher yesterday to play Stoneblock 3 and I had never used it before this. I have tried several modpacks, and they all get stuck loading in various places.
The most common places for it to get stuck are "Processing transition LOAD_REGISTRIES" or "Processing work UNFREEZE_DATA"
There is a Java application shown as open on the dock, but it doesn't open anything when I click on it.
I have tried restarting my computer, redownloading it, etc. and nothing has worked.
Also, I'm not sure where to get the log file for this, I will attach it if I can

### Information

- [X] I have provided as much information as possible

**Comment by SNIAPA** [comment]
same here it gets stuck on either UNFREEZE_DATA, INJECT_CAPABILITIES or LOAD_REGISTRIES

**Comment by KuddlBarmstedt** [comment]
Ich habe das selbe Problem. Ich habe vor Monaten den Launcher runtergeladen um ein paar Modpacks auszubrobieren. Auch bei mir ist es MacOS und auch bei mir bleibt es an unterschiedlichen Stellen stecken egal welches Modpack. Schade. Dann gehe ich wohl doch wieder zurück zu CurseForge. Da laden wenigstens alle Modpacks ohne Probleme. Scheinbar gibt es für MacJuser Null Hilfe. Traurig.

I have the same problem. I downloaded the launcher months ago to try out a few modpacks. it's MacOS for me too and it also gets stuck in different places, no matter which modpack. Too bad. I guess I'll go back to CurseForge after all. At least all modpacks load without problems. Apparently there is zero help for MacJuser. Sad.

**Comment by jikuja** [comment]
Can you all provide exact OS X versions?

**Comment by Linkling64** [comment]
I'm closing this issue because I reposted it over on the modpack page, and I have gotten more response there. I have been having this problem with the Stoneblock 3 modpack.
[Here is the other issue](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1807)
