### ISSUE TITLE
[Bug]: Fatal exception whilst installing modpack.

### ISSUE THREAD

**Issue by B34Rr** [FTBTeam/FTB-App#731]
### What Operating System

Windows 10

### App Version

1.4.0

### UI Version

4322c4d8d1

### Log Files

https://pste.ch/ecasuqakox.sql

### Debug Code

FTB-DBGHOFICISAJO

### Describe the bug

Unable to download any modpack.

### Steps to reproduce

- Select a Modpack
- Download ( Any verison / Any modpack )
- Downlaod screen pops up, then shows " Fatal exception whilst installing modpack "

### Expected behaviour

Install modpack and be able to play

### Screenshots

![error](https://user-images.githubusercontent.com/117764198/200635529-25b8d1bf-1c34-4d5b-966a-7f8705ebedb0.PNG)

### Information

- [X] I have provided as much information as possible

**Comment by KaspianU** [comment]
Same Problem, its with all modpacks

**Comment by ZackZeed** [comment]
This only happens to me when downloading Stoneblock 3 (which is the modpack i wanted to play...).

**Comment by MichaelHillcox** [comment]
Failed due to network issues, `Caused by: java.net.ConnectException: Failed to connect to launchermeta.mojang.com/134.209.132.125:443`

Please ensure that domain is not changed in your hosts file and that no firewall, school, collage, etc network is blocking it.
