### ISSUE TITLE
[Feature request] UI/UX: Don't block/lock the interface

### ISSUE THREAD

**Issue by aytimothy** [FTBTeam/FTB-App#732]
**Is your feature request related to a problem? Please describe.**
When an operation is happening (ie. downloading a modpack, launching a modpack, etc.) the interface locks up and I can't do anything else.
![image](https://user-images.githubusercontent.com/7418834/200707540-be669fcb-c968-45a7-8e8e-ed90ee0077da.png)

**Describe the solution you'd like**
The interface should not lock up like it does in the initial CurseForge App.
You should be free to launch a second pack or another instance of the same pack, otherwise what is the point of linking multiple Minecraft accounts when you can only use one at a time?

For update operations, it would be great if progress was tucked into a small bubble or another screen, for example (CurseForge/Steam/Epic Games Launcher):
![CurseForge In-UI Download Status](https://user-images.githubusercontent.com/7418834/200708478-ea4a8642-74b2-4bcd-b1bf-2a02555d01d6.png)
![Steam Downloads Screen](https://user-images.githubusercontent.com/7418834/200708134-3a938acc-53e7-4464-878c-84da999d05d4.png)
![Epic Games Launcher Download Side Panel](https://user-images.githubusercontent.com/7418834/200708285-12f3f67b-a82b-4a12-bb06-8e39853ba903.png)

**Describe alternatives you've considered**
I can log into multiple accounts in MultiMC then manually import the instances from FTB App, and then launch multiple accounts from there because the interface does not lock up when you do something (other than update MultiMC itself).

**Comment by MichaelHillcox** [comment]
We've fixed this in the up-coming `1.6.0` release. Although, I'll be keeping this issue open as the app will still lock up when launching a modpack sadly.
