### ISSUE TITLE
[Bug]: Microsoft Login Failure. Localhost CORS issue

### ISSUE THREAD

**Issue by Someoneamzing** [FTBTeam/FTB-App#733]
### What Operating System

Windows 10

### App Version

202211021238-4322c4d8d1-release

### UI Version

4322c4d8d1

### Log Files

```
Access to fetch at 'http://localhost:7755/' from origin 'https://msauth.feed-the-beast.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Private-Network' header was present in the preflight response for this private network request targeting the `local` address space.
TypeError: Failed to fetch
    at App.js:26:26
    at s (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at i (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at x (main.4f85d2ff.chunk.js:1:857)
```

### Debug Code

FTB-DBGEJOYICAXUY

### Describe the bug

Microsoft Authentication fails to find the FTB App. Browser Console complains of CORS issue.

### Steps to reproduce

1. Click Play on Modpack
2. Receive Prompt for Login between Microsoft / Mojang
3. Pick Microsoft
4. Browser tab opens complaining that it can't find the app. App says it's waiting for the browser.

### Expected behaviour

The broswer would allow me to sign in to my microsoft account.

### Screenshots

![image](https://user-images.githubusercontent.com/20350682/200816046-b5b77478-f522-4d81-91b3-59c6e7a6de5b.png)
![image](https://user-images.githubusercontent.com/20350682/200816150-772dce88-0443-48ae-9e2c-5498eb32971b.png)

### Additional information

Using Chrome 107.0.5304.88 (Official Build) (64-bit) (cohort: Stable)

I have tried this multiple times. No change in behaviour.

### Information

- [X] I have provided as much information as possible

**Comment by Someoneamzing** [comment]
After some further research it turns out this is a security measure Chrome has introduced recently that prevents connections to localhost.

[https://developer.chrome.com/blog/private-network-access-update/](https://developer.chrome.com/blog/private-network-access-update/)

They are in a deprecation trial period meaning only domains who have applied for exemptions can still use it.

The intended method for accessing local network resources is through the use of CORS policies. 

As the error log suggests, all that needs to happen is the internal auth response web server needs to respond with the `Access-Control-Allow-Private-Network` header. A simple fix could be to respond to all requests with that header, or to only respond to requests with the `Access-Control-Request-Private-Network` header.

For now the workaround is using another browser like Firefox and Safari, but I'm assuming this issue will become more prevalent as other browsers follow suit.

**Comment by Auryannae** [comment]
I use FireFox and I haven't been able to log into my microsoft account through the FTB app.

**Comment by MichaelHillcox** [comment]
We're updating this soon, for now, try a different browser. Thanks for the detailed report :+1:

**Comment by MichaelHillcox** [comment]
Should be sorted now
