### ISSUE TITLE
[Bug]: Server installer does not install everything, start.bat closes immediately

### ISSUE THREAD

**Issue by jkautz11** [FTBTeam/FTB-App#734]
### Modpack

Stoneblock 3

### Modpack version

1.2.0

### Describe the bug

The server files are not working for me. I'm using the installer provided, which fails to install some files every time I run it. Sometimes there will be 60 files failed sometimes there will be like 500. This is the message I get on the installer: Downloaded 1208 successful, 66 failed, 0 incomplete.
Some downloads failed. Would you like to continue anyway? (y/n) [y]. If I continue, the files will get set up normally and it does not look like anything is missing but when I try to run the bat file it closes immediately. I added pause to the end and it does not provide a message. 

### Steps to reproduce

Literally just use the server installer and run start.bat.

### Expected behaviour

Server should be running normally, not closing immediately.

### Screenshots

![image](https://user-images.githubusercontent.com/79385217/200712571-c5ff3ee5-3778-47c5-9bc2-86745c1adb68.png)

This is what happens when I add "Pause" to the end of start.bat. The console is just empty.
![image](https://user-images.githubusercontent.com/79385217/200712972-d64e2b8c-4627-4f8e-89c4-7517f5da264a.png)

**Comment by ninjrdevelop** [comment]
Issue seems to be resolved for Windows server installer, but a freshly downloaded copy of the Linux installer still has the issue.
Tested on a fresh install of Debian 11.

**Comment by Fade-Alchemist** [comment]
NO it is *not* resolved for windows users. 
![image](https://user-images.githubusercontent.com/29619427/201583784-786dc64b-19c2-4e9a-806d-a44076c539be.png)

**Comment by 5ully** [comment]
Im still not able to reproduce it @Fade-Alchemist , are you using the latest server installer found here?
https://www.feed-the-beast.com/modpacks/100-ftb-stoneblock-3 

And please add any extra info like OS if it isnt windows

**Comment by MichaelHillcox** [comment]
Please report ant server install issues here https://github.com/CreeperHost/modpacksch-serverdownloader
