### ISSUE TITLE
A machine not working

### ISSUE THREAD

**Issue by giovmer** [FTBTeam/FTB-App#735]
### What Operating System

Windows 10

### Log Files

[crash-2022-11-09_17.42.32-client.txt](https://github.com/FTBTeam/FTB-App/files/9973254/crash-2022-11-09_17.42.32-client.txt)

### Debug Code

FTB-DBGAWUNUWIZOF

### Describe the bug

I try to use alloy smelter and it doesn't work

### Steps to reproduce

.

### Expected behaviour

.

### Information

- [x] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Not an app issue, please use this tracker https://go.ftb.team/support-modpack
