### ISSUE TITLE
[Bug]: game crashes on start-up

### ISSUE THREAD

**Issue by mysticdevil98** [FTBTeam/FTB-App#736]
### What Operating System

Windows 10

### App Version

1.4.0

### UI Version

4322c4d8d1

### Log Files

[hs_err_pid4796.log](https://github.com/FTBTeam/FTB-App/files/9974679/hs_err_pid4796.log)

### Debug Code

FTB-DBGESOMUTEPEM

### Describe the bug

game crashes on start-up, unexpected error whilst running the game or on start-up

### Steps to reproduce

1. go to ftb-app
2. open stone block 3
3. run stoneblock 3
4. game doesnt start and crashes, updated version of stoneblock 3 before starting version 1.2.0, 

### Expected behaviour

game starts and is playable

### Screenshots

<img width="546" alt="image" src="https://user-images.githubusercontent.com/117859934/200929222-aefc5d1f-ae0a-4435-ac27-419d4eb5a6c9.png">

<img width="542" alt="image" src="https://user-images.githubusercontent.com/117859934/200929325-8f854d17-984e-4a89-8d03-ea7749cb5ffb.png">

<img width="543" alt="image" src="https://user-images.githubusercontent.com/117859934/200929360-f120ee8c-5ace-428a-8e45-ca5c5c7d90ef.png">

### Additional information

updated the game today, worked yesterday on previous version, 

tried to download new instance of game and it worked fine, no problems with it.

### Information

- [X] I have provided as much information as possible

**Comment by lambo89** [comment]
bonjour j'ai exactement le meme probleme mais je nais pas de solution !

**Comment by mysticdevil98** [comment]
> Hello I have exactly the same problem but I do not have a solution!

let me know here if you find a solution.

**Comment by jeroenwienk** [comment]
@lambo89 @mysticdevil98 

It crashing on ` Could not initialize class net.creeperhost.minetogether.chat.MineTogetherChat` I think. I had the same issue on 1.2.1 and deleted the minetogether mod from the mods folder and now it's working.

**Comment by mysticdevil98** [comment]
> @lambo89 @mysticdevil98 
> 
> It crashing on ` Could not initialize class net.creeperhost.minetogether.chat.MineTogetherChat` I think. I had the same issue on 1.2.1 and deleted the minetogether mod from the mods folder and now it's working.

Yeah i figured that out myself and its working for me now, but thanks for the reply.
