### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by jc2xs** [FTBTeam/FTB-App#737]
**Is your feature request related to a problem? Please describe.**
I run a linux server using AMP.  As a result, I have always manually installed mod packs after AMP configures an instance for server forge version I need.   What I would like is a manual download of the server files for a mod pack like similar to what I get off of curse forge.

**Describe the solution you'd like**
A way to just download the server files without going through some installer.  AMP sets up everything I need and I should have to do is copy up the mods, config and any additional folders that are part of the modpack.

**Describe alternatives you've considered**
There is no other option for me, and I really hate the new FTB App and how any type manual download is just not an option for FTB packs.

**Comment by MichaelHillcox** [comment]
Please forward any installer issues to the pack installer repo here https://github.com/CreeperHost/modpacksch-serverdownloader
