### ISSUE TITLE
[Bug]: Clicking the Update button for modpacks doesn't do anything

### ISSUE THREAD

**Issue by stefonio** [FTBTeam/FTB-App#738]
### What Operating System

Windows 10

### App Version

202211021238-4322c4d8d1-release

### UI Version

4322c4d8d1

### Debug Code

No Such Host error

### Describe the bug

The "Update Available" button doesn't initiate anything and doesn't show feedback when being clicked.

### Steps to reproduce

Try to update Stoneblock 3 from 1.2.0 to 1.2.1

### Expected behaviour

Stoneblock 3 updating

### Screenshots

![image](https://user-images.githubusercontent.com/118033183/201453290-ab0f8d3a-ba88-4a63-8dfd-6bb66c8b90d0.png)

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Closing, no debug code attached
