### ISSUE TITLE
[Bug]: Game Wont save after some hours destroying hours of progress for friend (LAN Using zero tier)

### ISSUE THREAD

**Issue by NorwegianNarpex** [FTBTeam/FTB-App#739]
### What Operating System

Windows 10

### App Version

202211021238-4322c4d8d1-release

### UI Version

4322c4d8d1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-App/files/9996022/latest.log)

### Debug Code

FTB-DBGLENEZIXOQE

### Describe the bug

After hours of playing with friend using (lan) the app is called zero tier the modpack fails to save repeatedly destroying hours of progress for him its happend twice 

### Steps to reproduce

i have no idea

### Expected behaviour

Maybe giving me a bug fix or somthing to solve the issue

### Screenshots

we closed our game without taking a screen shot it would take hours to recreate

### Additional information

not really we know nothing

### Information

- [X] I have provided as much information as possible

**Comment by NorwegianNarpex** [comment]
Narpex#7438 if you need to contact me add me on discord

**Comment by MichaelHillcox** [comment]
Closing due to lack of information.
