### ISSUE TITLE
Windows installer - Norton claims invalid signature

### ISSUE THREAD

**Issue by voysinmyhead** [FTBTeam/FTB-App#74]
![image](https://user-images.githubusercontent.com/63424372/78935357-97d2e100-7a7a-11ea-81e3-18b8d0fe37e4.png)

Cut the bottom half of the image off to avoid displaying my IP.. but there you go- Windows installer invalid signature

**Comment by Cloudhunter** [comment]
Windows installer doesn't have a digital signature currently. This will be resolved in the future with signing improvements.
