### ISSUE TITLE
[Bug]: error while installing or updating different modpacks

### ISSUE THREAD

**Issue by bartvkraaij** [FTBTeam/FTB-App#744]
### What Operating System

Windows 10

### App Version

202211021238-4322c4d8d1-release

### UI Version

4322c4d8d1

### Log Files

https://pste.ch/icolaziruf

### Debug Code

 FTB-DBGOMETOQIBIR

### Describe the bug

got the error whilst updating stoneblock 3, uninstalled pack, app everything... now some ack will install and update and some don't

### Steps to reproduce

modpack version 1.1.0

play

update to latest
crash

### Expected behaviour

expecting to update stoneblock 3

### Screenshots

![Knipsel](https://user-images.githubusercontent.com/118300513/201991409-1c893304-92d2-4df3-8291-9838fff71207.PNG)

### Information

- [X] I have provided as much information as possible

**Comment by Xkappa2** [comment]
I have the same problem how do I solve it?

**Comment by bartvkraaij** [comment]
i don't know how to solve this, i uninstalled the ftb app completely, re-installed, added a different folder for the pack instances, and the problem keeps happening.

right now i use the ATlauncher app, but when installing a modpack i need to manually download some mods to complete the pack, but otherwise this is my best sollution

**Comment by Xkappa2** [comment]
Do you already know how to fix it?
