### ISSUE TITLE
[StoneBlock 3 1.3.0] Refined Storage Wireless Crafting monitor crashes client.

### ISSUE THREAD

**Issue by jonno57** [FTBTeam/FTB-App#747]
Attached below are the two crash reports. One is from me and one is from a player on the server. Opening the wireless crafting monitor crashes the client but not the server. 

This issue started soon after updating to 1.3.0

[crash-2022-11-16_16.13.27-client.txt](https://github.com/FTBTeam/FTB-App/files/10026123/crash-2022-11-16_16.13.27-client.txt)
[crash-2022-11-16_12.57.59-client.txt](https://github.com/FTBTeam/FTB-App/files/10026131/crash-2022-11-16_12.57.59-client.txt)

**Comment by shinji257** [comment]
Please report this issue here: https://github.com/FTBTeam/FTB-Modpack-Issues
This repository is for the FTB App launcher.

**Comment by MichaelHillcox** [comment]
Not an app issue, please use this tracker https://go.ftb.team/support-modpack
