### ISSUE TITLE
[Suggestion]: use a different way to upload server files PLEASE

### ISSUE THREAD

**Issue by Xplodin** [FTBTeam/FTB-App#749]
### Modpack

ftb stoneblock 3

### Is your suggestion related to a problem? Please describe.

for the love of everything holy just upload normal server files.

I cannot count how many reinstalls of a linux server has been done to figure out why recipes dont work.
Its because your server files dont download them properly.

occasional times its missed kubejs files.
I legit have to copy a client install over to the server just to make sure it works. Client works fine but server install scripts are bugged

### Mod suggestion

just use a normal method of installing ftb stoneblock 3 server side

**Comment by MichaelHillcox** [comment]
Please report any install issues to here https://github.com/CreeperHost/modpacksch-serverdownloader
