### ISSUE TITLE
I can't install.......

### ISSUE THREAD

**Issue by sem1colon00** [FTBTeam/FTB-App#75]
![78626516-f73dbf00-78c9-11ea-9f63-09ada2d9baf3](https://user-images.githubusercontent.com/63216602/78950959-6524f900-7b0b-11ea-844e-8227d0cbc74a.png)

I can't download app...
[i4j_nlog_1.log](https://github.com/FTBTeam/FTB-App/files/4459185/i4j_nlog_1.log)
How can i fix it???

**Comment by Jake-E** [comment]
Please use the latest version of the installer at this current time:
https://apps.modpacks.ch/FTBApp/release/1.0.6/FTBA_windows-x64_1_0_6.exe
