### ISSUE TITLE
[StoneBlock 3 1.3.0]: Game crashes when you press any button in "SERVER TYPE" section.

### ISSUE THREAD

**Issue by LayZ4ever** [FTBTeam/FTB-App#750]
### What Operating System

Windows 10

### App Version

202211151621-329441ed6d-release

### UI Version

329441ed6d

### Log Files

[crash-2022-11-17_20.17.07-client.txt](https://github.com/FTBTeam/FTB-App/files/10034602/crash-2022-11-17_20.17.07-client.txt)

### Debug Code

 FTB-DBGEKUZOWUNUC

### Describe the bug

Every button in server type section crashes my game

### Steps to reproduce

1.Open the game
2.Press multiplayer
3.Press server list
4.By pressing one of the three buttons (public, community, closed)
5. A "saving world" is displayed on the screen and the game crashes

### Expected behaviour

I should let me see all the servers in the specific section, like in version 1.2

### Screenshots

![image_2022-11-17_204935527](https://user-images.githubusercontent.com/118476308/202532623-f7cb7505-da0f-43c9-8cc6-a754888d3437.png)
Couldn't catch it on time, but you can bearly see the "saving world" text.

### Information

- [X] I have provided as much information as possible

**Comment by covers1624** [comment]
This is a bug in MineTogether and has already been resolved: https://github.com/CreeperHost/MineTogether/issues/666
