### ISSUE TITLE
[Bug]: msauth.feed-the-beast.com returns 503

### ISSUE THREAD

**Issue by hairlessOrphan** [FTBTeam/FTB-App#752]
### What Operating System

Windows 10

### App Version

202211151621-329441ed6d-release

### UI Version

329441ed6d

### Debug Code

none

### Describe the bug

SSO into Microsoft account directs you to https://msauth.feed-the-beast.com/, but that URL returns a 503. Can't login, which means can't play anything, because there's no way to just launch a modpack from the real Minecraft Launcher.

### Steps to reproduce

1. Visit https://msauth.feed-the-beast.com/

![ftb](https://user-images.githubusercontent.com/3323307/202630399-1cd962c8-436d-4e5b-a202-b84724046819.png)

### Expected behaviour

https://msauth.feed-the-beast.com/ loads with 200 and SSO login flow.

### Information

- [X] I have provided as much information as possible

**Comment by TigerSystem1** [comment]
I am also experiencing this problem

**Comment by aanus123** [comment]
me too

**Comment by Jax1366** [comment]
same here

**Comment by Anirra** [comment]
same problem

**Comment by Zhurt** [comment]
im also experiencing this bug

**Comment by TheBromancer** [comment]
Same Here! :'(

**Comment by matthewmurno** [comment]
Same here

**Comment by MinionKiller3** [comment]
Can confirm I have also gotten this. I have re downloaded the app. Restarted PC and still error

**Comment by Luckyludog** [comment]
Same, sad

**Comment by TheBromancer** [comment]
Anyone how long they take to respond to issues like this?

**Comment by MinionKiller3** [comment]
> Anyone know how long they take to respond to issues like this?

Hopefully not too long its my day off and I was keen to play Stoneblock 2 or 3

**Comment by Tripwire117** [comment]
I am experiencing the same issue.

**Comment by glow921** [comment]
same here, I was originally logged in but couldn't launch Stoneblock 3, I then logged out and can't get back in anymore

**Comment by Liam-Havens** [comment]
First time using the app and just my luck

**Comment by Luckyludog** [comment]
> First time using the app and just my luck

Sorry bud. Definitely worth playing, just probably not tonight :( Problem with Microsoft identification and I haven't seen anything FTB saying they're working on it yet

**Comment by alreadydad** [comment]
Same problem

**Comment by TigerSystem1** [comment]
if you are trying to play Stone Block 3 and already have it downloaded, open the instance folder, copy all the files, and if you have Cursed forge installed make a custom profile, finally open the folder for the cursed forge instance, and replace the files in there. that was the work around I found

**Comment by Destinyshadow98** [comment]
Same here, who know when we got any information?

**Comment by alreadydad** [comment]
It's nigh time in US so it can take hours to solve

**Comment by northmatt** [comment]
I'd recommend MultiMC5 personally, it also works.

**Comment by BambusbjoernX** [comment]
Problem is still there

**Comment by hairlessOrphan** [comment]
> > First time using the app and just my luck
> 
> Sorry bud. Definitely worth playing, just probably not tonight :( Problem with Microsoft identification and I haven't seen anything FTB saying they're working on it yet

Unfortunately, this isn't a problem with MS SSO, it's a problem with FTB's integration with MS SSO. And it's only an issue because FTB forces us to login via their app instead of the real Minecraft Launcher, presumably so they can collect user data. No other Minecraft modpack manager requires this as an attempt to monetize our user data, including other Overwolf apps. Even CurseForge, also built on Overwolf, uses the real Minecraft Launcher.

**Comment by LeD0c4** [comment]
Same  problem, for bypass this bug. I create a new instance minecraft forge 1.18.2 40.1.85 on curseforge et copy past the whole folder on this instance...

**Comment by DanyaMarchenko** [comment]
It fixed

**Comment by MichaelHillcox** [comment]
Fixed a while ago
