### ISSUE TITLE
[Bug]: Can not log in into microsoft

### ISSUE THREAD

**Issue by DanyaMarchenko** [FTBTeam/FTB-App#753]
### What Operating System

Windows 10

### App Version

202211151621-329441ed6d-release

### UI Version

329441ed6d

### Log Files

![image](https://user-images.githubusercontent.com/86123594/202646676-5e0ffc37-c018-4aca-961a-2dc73d3ff07e.png)

### Debug Code

There's no debug Code

### Describe the bug

I cant log in, I thought I should log out, and log in because app tell me about that, and then I cant log in

### Steps to reproduce

Log out of account, try to log into microsoft

### Expected behaviour

Can't log in microsoft, 503 Service Temporarily Unavailable error

### Screenshots

![image](https://user-images.githubusercontent.com/86123594/202647902-08f36bb3-346b-4dce-8e9d-40e7858a95c2.png)

### Additional information

I live in Belarus, maybe its because of my internet, but vpn doesn't help

### Information

- [X] I have provided as much information as possible

**Comment by alreadydad** [comment]
Issue already exists https://github.com/FTBTeam/FTB-App/issues/752
