### ISSUE TITLE
[Bug]: Linux App Doesn't Open or Load any Modpacks

### ISSUE THREAD

**Issue by LandonCalling** [FTBTeam/FTB-App#754]
### What Operating System

Linux (Debian)

### App Version

202211151621-329441ed6d-release

### UI Version

329441ed6d

### Log Files

https://pste.ch/urafiyolav

### Debug Code

running the tool/program didn't open any windows or produce any code

### Describe the bug

When I try to open or load any pack it gives me the error "unable to update, validate, or find your profile.  please sign in again."

### Steps to reproduce

Go to any modpack installed on the profile
Try to load the modpack

### Expected behaviour

Should load the modpack

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
I mean, stupid question but, have you logged in?

**Comment by MichaelHillcox** [comment]
This was due to Minecraft authentication issues, should be resolved now :+1:
