### ISSUE TITLE
[Bug]: startup progress stalled

### ISSUE THREAD

**Issue by Kitsune2137** [FTBTeam/FTB-App#759]
### What Operating System

Windows 10

### App Version

202211151621-329441ed6d-release

### UI Version

329441ed6d

### Debug Code

FTB-DBGNOBUXUHIYE

### Describe the bug

FTB stuck

### Steps to reproduce

1. Play FTB Sky Odyssey
2. Get stuck a "Simple Inventory Sorting" forever
3. Go to step 2

### Expected behaviour

Minecraft will turn on

### Screenshots

![image](https://user-images.githubusercontent.com/118659465/202894619-d5e06d6b-fde2-4d37-b6a5-874eaaaa273d.png)

### Information

- [x] I have provided as much information as possible

**Comment by xerminator** [comment]
Yeah idk what it is but every version even the 1.2.0 (first release version) ain't working on the FTBApp.

The one on curseforge seems to work fine though (version 1.3.0).

You might wanna try that if you wanna give this pack a go.

**Comment by MichaelHillcox** [comment]
Related to #765

**Comment by Sly-444** [comment]
the new 1.4.2 version solved the problem though it may not be stable
