### ISSUE TITLE
Featured packs only takes into account whether there is space for items horizontally 

### ISSUE THREAD

**Issue by Cloudhunter** [FTBTeam/FTB-App#76]
When viewed at the default resolution, despite there being space for multiple icons, only the first three are shown. More are added only if the horizontal width is changed, even if there isn't enough room. Example video.

https://ss.cl.mk/LawfulGnu08.mp4

**Comment by Rushmead** [comment]
We've changed up how we are doing our scaling for the pack-cards, hopefully this fixing this problem, please let us know if this is fully resolved.
