### ISSUE TITLE
[Bug]: loading modpack slows down pc

### ISSUE THREAD

**Issue by NLgamer2000** [FTBTeam/FTB-App#760]
### What Operating System

Windows 10

### Debug Code

FTB-DBGFULIWUQETI

### Describe the bug

loading modpack slows down pc

### Steps to reproduce

just loading any pack

### Expected behaviour

being able to watch youtube with no lag and browse through discord

### Additional information

it slows down my pc and youtube videos just start lagging and freezing. cant even browse through discord.

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Would need 100% more information. Sounds like what happens when you have an underpowered pc and try to play a modpack. It's common. Gunna close due to lack of information
