### ISSUE TITLE
[Bug]: Some Curse mods failing to install

### ISSUE THREAD

**Issue by AndroPups** [FTBTeam/FTB-App#761]
### What Operating System

Windows 10

### App Version

1.4.1

### UI Version

329441ed6d

### Debug Code

FTB-DBGACEDUMUZEN

### Describe the bug

App will not allow adding mods onto packs, specifically SB3. Could now download Quark or Refined Cooking

### Steps to reproduce

1. Get to Mods in the modpack Stoneblock 3
2. Click Add more Mods
3. Find mod to install, like Quark or Refined Cooking
4. Will display screen saying Installing but 0% progress, 0 B/s and 0 downloaded

### Expected behaviour

To be able to download the mod

### Screenshots

https://imgur.com/a/uToHUrB

### Information

- [X] I have provided as much information as possible

**Comment by lordtrickster** [comment]
Same issue on Stoneblock 3.  Tried to add MineColonies, had the same issue.  Decided to try the dependencies, Multi-Piston is having the problem but the others downloaded fine.

**Comment by astarace** [comment]
I've been facing the same issue with installing Thaumic Augmentation with the Direwolf20 1.12.2 pack. Stalls at 0%.

**Comment by CoryNB** [comment]
I've been having trouble installing new mods, but not like failing, just failing to load when adding mods.
