### ISSUE TITLE
[Bug]: Install failed on all modpacks

### ISSUE THREAD

**Issue by MRBillionWithAB** [FTBTeam/FTB-App#762]
### What Operating System

Windows 10

### App Version

202211151621-329441ed6d-release

### UI Version

329441ed6d

### Debug Code

 FTB-DBGUREBEHUPIW

### Describe the bug

Unable to open existing instances, or download new ones

### Steps to reproduce

1. Go to FTB app
2. Go to any mod pack
3. download or launch
4. starts preparing 
5. stays at 0% for about 2-3 minutes
6. install failed
7. say fatal exception

### Expected behaviour

To be able to play the game

### Screenshots

![Screenshot_20221120_040934](https://user-images.githubusercontent.com/118694740/202928985-e81caaf5-1472-4395-a94e-26302cfe87da.png)
![Screenshot_20221120_041033](https://user-images.githubusercontent.com/118694740/202928986-7a5b29a1-2bea-4d5b-88bc-67b82aa6e43e.png)

### Additional information

Started today i have tried every fix. The only remaining thing i saw was to wait for it to fix itself. (applies on other mod launchers as well only for FTB based mod packs (ALL of them) )

### Information

- [X] I have provided as much information as possible

**Comment by cr4ckp0t** [comment]
I dug through the logs a bit, since I am having the same issue, it seems as though it is due to a 504 response the app is receiving from CreeperHost when it tries to list the modpacks. I am not super familiar with the code, but this seems to be the issue.

**Comment by MichaelHillcox** [comment]
Looks like our API was having issues when you tried to install, please try again
