### ISSUE TITLE
[Bug]: i can't get the flint pickaxe achievment can anyone help me with this and i do have the flint pickaxe

### ISSUE THREAD

**Issue by SANSFANorig** [FTBTeam/FTB-App#766]
### What Operating System

Windows 10

### Debug Code

?

### Describe the bug

itss not allowing me to to progress through the mod inferno

### Steps to reproduce

help me plz

### Expected behaviour

it should have been completed due to me having the pickaxe

### Information

- [X] I have provided as much information as possible

**Comment by SANSFANorig** [comment]
and its the inferno mod

**Comment by MichaelHillcox** [comment]
Not an app issue, please use this tracker https://go.ftb.team/support-modpack
