### ISSUE TITLE
[Bug]: Trying to open Refined Storage system after load, crashes game

### ISSUE THREAD

**Issue by reginlyngsoe** [FTBTeam/FTB-App#767]
### What Operating System

Windows 10

### Log Files

[crash-2022-11-22_11.51.14-client.txt](https://github.com/FTBTeam/FTB-App/files/10066661/crash-2022-11-22_11.51.14-client.txt)

### Debug Code

 FTB-DBGOPAWUSUFAN

### Describe the bug

Crash when opening the Refined storage crafting grid after load

### Steps to reproduce

load the game.
Access Refined storage grid.
Crash

### Expected behaviour

Seeing the grid and playing the game

### Additional information

I do not know what content my refined storage system has

### Information

- [X] I have provided as much information as possible

**Comment by ItsChase7** [comment]
I'm having a very similar problem with the refined storage wireless crafting grid crashing the game
This is my crash report
[crash-2022-11-22_10.02.54-client.txt](https://github.com/FTBTeam/FTB-App/files/10068651/crash-2022-11-22_10.02.54-client.txt)

**Comment by SoftGuardian** [comment]
I think you have to wait for REI to "initialize" You can check the progress by normally opening your inventory.

**Comment by MichaelHillcox** [comment]
Not an app issue, use this tracker https://go.ftb.team/support-modpack
