### ISSUE TITLE
cant join my own server

### ISSUE THREAD

**Issue by SirLeguan** [FTBTeam/FTB-App#768]
### What Operating System

Windows 10

### App Version

202211151621-329441ed6d-release

### UI Version

329441ed6d

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-App/files/10069234/latest.log)

### Debug Code

FTB-DBGPEMOHOYIMO

### Describe the bug

 An error occurred building event handler  java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because the return value of "java.lang.Thread.getContextClassLoader()" is null

### Steps to reproduce

look at the bug discribtion idk how to produce the bug it just happens when i try to go on my server

### Expected behaviour

 it just happens when i try to go on my server

### Screenshots

![Screenshot 2022-11-22 114900](https://user-images.githubusercontent.com/118838327/203368733-b1cf0e33-4e24-4bfb-8b18-95b2449e3f32.png)

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Not an app issue
