### ISSUE TITLE
Issues Installing FTB App

### ISSUE THREAD

**Issue by Jake-E** [FTBTeam/FTB-App#77]
If you have issues installing the FTB App, on any OS, please provide the following as a comment:
- OS & Version
- The `i4j_nlog_1.log` file, found in `%localappdata%/Temp`
- Installer version (Please ensure you are using the latest at time of posting your comment)

Further discussion regarding the following issues will be had here:
#44 #47 #72 #75 

We will update as new installers are pushed out for further testing.

**Comment by sem1colon00** [comment]
windows10, lastest version.
[i4j_nlog_12.log](https://github.com/FTBTeam/FTB-App/files/4461629/i4j_nlog_12.log)
1.0.6
how can i fix it... :(

**Comment by sem1colon00** [comment]
How can i fix it?

**Comment by Cloudhunter** [comment]
Currently you can't as we don't know what I'd wrong yet. We've contacted the people who make the installer software with logs and will let you know when we have not information.

**Comment by Cloudhunter** [comment]
I've heard back from the developers, and to all having issues, we need this information in order to debug this further:

```
Please let us know what stage the failure occurs. If they never see a window or only a very small window with a progress bar, it's a problem in the native launcher. In that case, you can get more information by executing

<installer>.exe /create-i4j-log

from the command line. This produces a log file and a message box will help to find the log file in the Windows explorer.

If the installer wizard is shown, there is a log file in the %TEMP% directory whose name starts with "i4j_log". The user can open the explorer, enter %TEMP% in the address bar and sort by modification date (descending). The topmost files should then include that log file.

If the installation completes and is non-functional, the log file is located in the .install4j/installation.log file in the installation directory.
```

**Comment by sem1colon00** [comment]
I have a problem while installing lancher.

**Comment by Jake-E** [comment]
> 
> 
> I have a problem while installing lancher.

Read the comment above yours and provide the logs.

**Comment by samil25** [comment]
Hello, I am having an issue too.
OS =  Windows 10 Pro 1909
Log File = https://paste.feed-the-beast.com/view/11815aed
Installer Version = FTBA_windows-x64_1_0_8
Thank you so much, you can also find the physical log file in the attachment
[installation.log](https://github.com/FTBTeam/FTB-App/files/4499950/installation.log)

**Comment by Cloudhunter** [comment]
When providing logs, please also provide this information:

> Please let us know what stage the failure occurs.

As specified in this comment: https://github.com/FTBTeam/FTB-App/issues/77#issuecomment-614341836

**Comment by solaris765** [comment]
For what its worth I solved this issue for myself by checking the logs @Cloudhunter is directing everyone to and found that the JRE was failing to download on my system.

In my case the url in the logs was  `https://apps.modpacks.ch/FTBApp/jres/windows-amd64-11.0.5.tar.gz`

I downloaded that and extracted it's contents to `%HOMEPATH%/jre.bundle/contents/home`

Then run the installer again. Should work fine.

System Information
OS: Windows 10 Pro
Installer Version: FTBA_windows-x64_1_0_8
Error occurs before installation.
https://paste.feed-the-beast.com/view/d5a15dc7

**Comment by andyglover** [comment]
I'm also getting an error in my installation log, even after following @solaris765 suggestion. The installation appears to complete successfully but when launcher is run from FTBApp.exe in Roaming/FTBA/ directory, nothing happens, and when run from ftbapp.exe in Roaming/FTBA/bin/
the launcher hangs on the "Starting FTB App, please wait"

output from "FTBA_windows-x64_1_0_8.exe /create-i4j-log" is attached.
[i4j_log_FTBA_3492388756233034939.log](https://github.com/FTBTeam/FTB-App/files/4537749/i4j_log_FTBA_3492388756233034939.log)

error.log from Roaming/FTBA/ directory also attached.
[error.log](https://github.com/FTBTeam/FTB-App/files/4537787/error.log)

**Comment by Sulavin** [comment]
I also have a bit trouble with installing the new FTBApp.

**Operating System:**
OS: Windows 10 Pro Build 17763 64bit

**Installer Version:**
Installer: "FTBA_windows-x64_1_0_8.exe
**Log Files:**
[i4j_nlog_7.log](https://github.com/FTBTeam/FTB-App/files/4559871/i4j_nlog_7.log)
[i4j_nlog_8.log](https://github.com/FTBTeam/FTB-App/files/4559872/i4j_nlog_8.log)
[i4j_nlog_9.log](https://github.com/FTBTeam/FTB-App/files/4559873/i4j_nlog_9.log)
[i4j_nlog_10.log](https://github.com/FTBTeam/FTB-App/files/4559874/i4j_nlog_10.log)


**Describe the bug**
When i start the "FTBA_windows-x64_1_0_8.exe" the install4j Wizard downloads the Java Runtime Environment. After that i get the error below.
![2020-04-30_18h25_44](https://user-images.githubusercontent.com/64605298/80738426-5384af00-8b15-11ea-84ad-7cf86031fae7.png)

the last lines in the logs are only :
`[65:8] used stack size 0
[65:16] Creating JVM
[65:34] ERROR: could not initialize JVM
[65:34] ERROR: Could not start JVM
[65:106] Java window visible`

I deactivated full Antivirus (Kaspersky) and Firewall.

I also tried different Heap size's like 1Gb up to 10Gb.

![2020-04-30_18h37_09](https://user-images.githubusercontent.com/64605298/80738520-744d0480-8b15-11ea-8ea4-9fd9d9a08c40.png)

at this point i don't actually have a clue what to try else.

**Comment by totorcmwa** [comment]
I have a very problematic trouble whil installing FTBApp.

**OS:**
Windows 10 Pro Build 18362.778 64 bits

**Installer Version:**
"FTBA_windows-x64_1_0_8.exe"

**Log Files:**
[i4j_nlog_2.log](https://github.com/FTBTeam/FTB-App/files/4564328/i4j_nlog_2.log)
[i4j_nlog_1.log](https://github.com/FTBTeam/FTB-App/files/4564329/i4j_nlog_1.log)

**Bug:**
While installing, this window open:
![Capture2](https://user-images.githubusercontent.com/64645623/80808733-6dc79700-8bc0-11ea-975b-75a0c5842f58.JPG)

When I click on "Yes" the message reappear

**Comment by MaxiHXy** [comment]
Hallo Community!! 
My Friend have also the same problem with the launcher. 
He tries to install several times but it not works. Every time the issue with the installation.
Always the java error. I see that the last post with this kind of problem is several days far, is ther any solutin for this Problem?
Now the files and the Datasheet of the pc:

System Information
OS: Windows 10 Pro 64Bit
Java: 64Bit Java8 251
Installer Version: FTBA_windows-x64_1_0_8
Error occurs during installation.
Log: https://cdn.discordapp.com/attachments/626835831507779619/707305329137811550/i4j_nlog_14.log
Picture of the Issue window:
https://cdn.discordapp.com/attachments/626835831507779619/707226874765377536/unknown.png

Thanks in advance
MaxiHXy

**Comment by xzillen** [comment]
there is already something new regarding the installation problem

**Comment by mowense** [comment]
Hello

I have the same problem as some of us, I have this image that appears when I launch the launcher.
![Screenshot_1](https://user-images.githubusercontent.com/65122583/82726174-8704c480-9ce2-11ea-86bc-7b12bcba8542.png).

Here is the log file : 
[i4j_nlog_2.log](https://github.com/FTBTeam/FTB-App/files/4671420/i4j_nlog_2.log)

System Information
OS: Windows 10 family 64Bit
Java: 64Bit Java8 251
Installer Version: FTBA_windows-x64_1_0_8

If you have advice, I am interested 👯 

Thank you in advance for your answers 🌞

**Comment by hgsorensen** [comment]
I was having this same problem last night. I managed to get around it, so I will share my 10 cents.
I deleted the folder %appdata%\FTBA and did a search in the registry for FTBA values, I cannot recall what keys I deleted exactly. Then I reinstalled the exe on my D: drive and that worked. One or more of the below seemed to have been causing the problem.

- I have Danish characters in my path to %appdata%
- I have spaces in my path to %appdata%
- I have an SSD M.2 drive that my %appdata% is on.
- (less likely) my path to %appdata% is 43 characters long, maybe some of the file lengths exceed the windows/ Dos limit.

My D drive is a good old fashioned SATA spinning disc, and I installed the FTBA in D:\FTBA. Now there are no problems with starting the applicataion.

Hope this is valuable to someone.

**Comment by mowense** [comment]
> I was having this same problem last night. I managed to get around it, so I will share my 10 cents.
> I deleted the folder %appdata%\FTBA and did a search in the registry for FTBA values, I cannot recall what keys I deleted exactly. Then I reinstalled the exe on my D: drive and that worked. One or more of the below seemed to have been causing the problem.
> 
> * I have Danish characters in my path to %appdata%
> * I have spaces in my path to %appdata%
> * I have an SSD M.2 drive that my %appdata% is on.
> * (less likely) my path to %appdata% is 43 characters long, maybe some of the file lengths exceed the windows/ Dos limit.
> 
> My D drive is a good old fashioned SATA spinning disc, and I installed the FTBA in D:\FTBA. Now there are no problems with starting the applicataion.
> 
> Hope this is valuable to someone.

@hgsorensen 

WAAAAAAAAAAAAAAW it worked for me 👍 
I was in %appdata% I deleted FTBA, I downloaded ftb in my second hard drive, and I also installed it in my second hard drive, and now it works 🥇  <3 <3
![ftb](https://user-images.githubusercontent.com/65122583/83861430-e02c1980-a720-11ea-8692-65e217d9660b.png)

Thank you very much dude <3 <3

**Comment by Sulavin** [comment]
> 
> 
> I was having this same problem last night. I managed to get around it, so I will share my 10 cents.
> I deleted the folder %appdata%\FTBA and did a search in the registry for FTBA values, I cannot recall what keys I deleted exactly. Then I reinstalled the exe on my D: drive and that worked. One or more of the below seemed to have been causing the problem.
> 
>     * I have Danish characters in my path to %appdata%
> 
>     * I have spaces in my path to %appdata%
> 
>     * I have an SSD M.2 drive that my %appdata% is on.
> 
>     * (less likely) my path to %appdata% is 43 characters long, maybe some of the file lengths exceed the windows/ Dos limit.
> 
> 
> My D drive is a good old fashioned SATA spinning disc, and I installed the FTBA in D:\FTBA. Now there are no problems with starting the applicataion.
> 
> Hope this is valuable to someone.

Sadly those hints could not help in my case. But regarding to those hints i can provide some further Informations to my case above.
[https://github.com/FTBTeam/FTB-App/issues/77#issuecomment-622378772](url).

1. I tested the new installer FTBA_windows-x64_1_0_9.exe
2. I have no Folder %appdata%\FTBA
3. I tried to install on M.2 SSD's, Sata SSD's and HDD's
4. I have the character "é" in my %appdata% path

[i4j_nlog_1.log](https://github.com/FTBTeam/FTB-App/files/4741766/i4j_nlog_1.log)
[i4j_nlog_2.log](https://github.com/FTBTeam/FTB-App/files/4741768/i4j_nlog_2.log)
[i4j_nlog_3.log](https://github.com/FTBTeam/FTB-App/files/4741769/i4j_nlog_3.log)

**Comment by JulikGame** [comment]
hi 
OS Windows 10 Version 2004
[i4j_nlog_2.log](https://github.com/FTBTeam/FTB-App/files/4781183/i4j_nlog_2.log)
[i4j_nlog_1.log](https://github.com/FTBTeam/FTB-App/files/4781184/i4j_nlog_1.log)
![image](https://user-images.githubusercontent.com/66960588/84674331-7b986800-af33-11ea-8b9d-137605d8916f.png)
![image](https://user-images.githubusercontent.com/66960588/84674383-88b55700-af33-11ea-8e2b-5a07520c9db6.png)
i cant open FTB Launcher

**Comment by DzhonDias** [comment]
Same problem here!!

**Comment by Sunekaer** [comment]
JulikGame's problem was solved yesterday on Discord by installing the app in a place there wasn't he's users folder, seems to be non-ascii characters causing issues @Cloudhunter

**Comment by JulikGame** [comment]
Sunekaer, grandrolf#1426 helper me

**Comment by Exillium313** [comment]
> For what its worth I solved this issue for myself by checking the logs @Cloudhunter is directing everyone to and found that the JRE was failing to download on my system.
> 
> In my case the url in the logs was `https://apps.modpacks.ch/FTBApp/jres/windows-amd64-11.0.5.tar.gz`
> 
> I downloaded that and extracted it's contents to `%HOMEPATH%/jre.bundle/contents/home`
> 
> Then run the installer again. Should work fine.
> 
> System Information
> OS: Windows 10 Pro
> Installer Version: FTBA_windows-x64_1_0_8
> Error occurs before installation.
> https://paste.feed-the-beast.com/view/d5a15dc7

Spent almost 2 hours trying to figure this out, and i used your download link, deleted the contents of FTBA/jre and extracted the file there and everything works just fine...

THANK YOU!

**Comment by Gaz492** [comment]
Installer hanging on update process https://github.com/FTBTeam/FTB-App/issues/179

**Comment by JulikGame** [comment]
Moderator helped me

Don't using Roaming folder it error installer


сб, 27 июн. 2020 г. в 19:42, Gareth Williams <notifications@github.com>:

**Comment by xzillen** [comment]
i think the problem has to do with the path to the roaming directory
I had the cliente reinstalled yesterday but directly on C: / ftba and there was no problem with the start

**Comment by FluffyTowels** [comment]
My issue described in #44 still persists
[i4j_nlog_5.log](https://github.com/FTBTeam/FTB-App/files/5029760/i4j_nlog_5.log)
I'm using windows 7 and the latest version of the FTBApp(I would give the exact version, but I can't find where it's written)

**Comment by Jake-E** [comment]
> My issue described in #44 still persists
> [i4j_nlog_5.log](https://github.com/FTBTeam/FTB-App/files/5029760/i4j_nlog_5.log)
> I'm using windows 7 and the latest version of the FTBApp(I would give the exact version, but I can't find where it's written)

Can you try installing in a location that doesn't have non-ascii characters?

**Comment by windybut** [comment]
Windows 10 version 1903 Build 18362.1016 Fully updated.


FTBA_windows-x64_202007161516-479dedc615-release.exe (downloaded 5 mins ago)

Error:- “the update information could not be downloaded from
             http://apps.modpacks.ch/FTBApp/Release.xml
             Please check you internet connection”

After clicking OK button then the two next buttons to install(to default location I get the following error.

“ Could not download content files.  Do you want to try again? “

The OK button is an infinite loop of the same error and cancel well cancels it.

I have no issues with any other online apps and there are NO firewall issues either.  I have no antivirus software either.

I have ran the app in various compatibility modes and even admin mode too same errors.  I have all my games installed on a SATA drive with 1.7TB of free space and I get the same error when I change the location to this drive too.

I posted this problem on the FTB forums in the support section and got no help there.  I do not know what else to try so any help will be appreciated.

[i4j_nlog_1.log](https://github.com/FTBTeam/FTB-App/files/5084174/i4j_nlog_1.log)

**Comment by FluffyTowels** [comment]
> > My issue described in #44 still persists
> > [i4j_nlog_5.log](https://github.com/FTBTeam/FTB-App/files/5029760/i4j_nlog_5.log)
> > I'm using windows 7 and the latest version of the FTBApp(I would give the exact version, but I can't find where it's written)
> 
> Can you try installing in a location that doesn't have non-ascii characters?

It doesn't get to the point where I can set a location for to install it to

**Comment by Wolfguard94** [comment]
Windows 10 v1909
[i4j_nlog_1.log](https://github.com/FTBTeam/FTB-App/files/5249264/i4j_nlog_1.log)
I can't find the version number cleanly written, but I downloaded it today 9/19/20 FTBA_windows-x64_202007161516-479dedc615-release.dat

**Comment by Wolfguard94** [comment]
Hol'up I'm an idiot. There is a .exe file in the FTBA/bin folder. THe installer crashed when I was first installed it so it didn't create a shortcut.

**Comment by taehyoung1301** [comment]
![image](https://user-images.githubusercontent.com/59105716/96362163-5b3d1c00-1166-11eb-8daf-7477f4b13c2a.png)
![image](https://user-images.githubusercontent.com/59105716/96362173-642ded80-1166-11eb-9190-2769987639ca.png)
lemme just upload the entire image with.. the log file here,
[i4j_nlog_5.log](https://github.com/FTBTeam/FTB-App/files/5397211/i4j_nlog_5.log)

**Comment by AlvinKamaraGuy** [comment]
Please help me. My friend cannot open the FTB App. It's the "The JVM could not be started" issue. We did not understand anything from Cloudhunter's comment and the comments below. Is there a video to help? Sorry for any spelling mistakes, English is not my first language.

**Comment by AlvinKamaraGuy** [comment]
Please help me. My friend cannot open the FTB App. It's the "The JVM could not be started" issue. We did not understand anything from Cloudhunter's comment and the comments below. Is there a video to help? Sorry for any spelling mistakes, English is not my first language

**Comment by N3tflix** [comment]
Microsoft Windows
Version 1909 (OS Build 18363.1139)
[i4j_nlog_1.log](https://github.com/FTBTeam/FTB-App/files/5576926/i4j_nlog_1.log)
FTBA_windows-x64_202007161516-479dedc615-release

I dont know if I am supposed to give as much information as possible but... basically the program runs as a backup program with 63.6 mb of memory. Nothing else. It was working fine 3 days ago on the 17th. Now it wont work at all. I would talk about stuff I noticed in the error log, but I think you will see it from the ij4 log.

**Comment by MichaelHillcox** [comment]
The app installer is no longer being used, all these issues should now be fixed with the use of overwolf
