### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ArtTheMan** [FTBTeam/FTB-App#772]
### What Operating System

Windows 8.1

### UI Version

202211151621-329441ed6d-release

### Log Files

No Log file

### Debug Code

FTB-DBGRAFEHATINE

### Describe the bug

Update Available Icon displayed even when "no Beta" selected and on latest build

### Steps to reproduce

1. Install FTB StoneBlock3 1.3.0 instance
2. Relaunch FTB Launcher again. 
3. "Update Available" option is set next to the icon page of instances, and on the specific instance page. 

### Expected behaviour

Update Available should only displayed if there is an available update, that matches users setting (Read: no Beta)

### Screenshots

![stoneblock3_instance_update_available_page](https://user-images.githubusercontent.com/12237391/204107322-40a530ac-7f7e-473d-8716-16d011ca6a75.PNG)
![stoneblock3_beta_channel_disabled](https://user-images.githubusercontent.com/12237391/204107323-89555a39-ac06-477e-88b7-760734357b47.PNG)
![stoneblock3_instance_is_latest](https://user-images.githubusercontent.com/12237391/204107324-780faf4a-0e27-4556-a941-75c86c8b16fd.PNG)
![stoneblock3_instance_update_available_icon](https://user-images.githubusercontent.com/12237391/204107326-6615be55-877c-480b-91d8-557f08204e17.PNG)

### Additional information

https://github.com/FTBTeam/FTB-App/blob/329441ed6d302dcafc466dc6f6b9d9dc9578a7b2/src/components/molecules/modpack/PackBody.vue#L24

^ I think there needs to be some logic here like `isInstalled && ~(isLatestVerstionBeta && BetaAvailable || isLatestVersionRelease)`

Based on quick look through the code. 

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Ah yeah, I can see the confusion here, that toggle is for the app not the packs, we will be added an opt-out for the unstable pack versions very soon. 

Thanks for the detailed report :+1:
