### ISSUE TITLE
[Bug]: Alloying not working on KnightSlime/SoulSteel + they are the same thing 

### ISSUE THREAD

**Issue by ChimeraGaming** [FTBTeam/FTB-App#774]
### What Operating System

MacOS (Latest)

### App Version

1.4.1

### Debug Code

FTB

### Describe the bug

Not alloying Items

### Steps to reproduce

Smelt EnderSlime (Purple Slime)
Smelt Seared Stone
Smelt Iron
=
KnightSlime or SoulSteel (prefer soulsteel)

### Expected behaviour

Alloy Items

### Screenshots

![Screen Shot 2022-11-26 at 6 56 39 PM](https://user-images.githubusercontent.com/54367698/204118557-a42148b4-9b0e-41b5-91ba-8f94072a8f94.png)
![Screen Shot 2022-11-26 at 6 56 59 PM](https://user-images.githubusercontent.com/54367698/204118562-6ac71344-d860-4218-be34-87d1b90d5335.png)
![Screen Shot 2022-11-26 at 6 57 06 PM](https://user-images.githubusercontent.com/54367698/204118565-a0c62c71-2cb2-46d0-822e-dcc687cf9cd5.png)
![Screen Shot 2022-11-26 at 6 57 12 PM](https://user-images.githubusercontent.com/54367698/204118568-5e18f35e-7314-4b64-b949-4abc8766085c.png)

### Information

- [X] I have provided as much information as possible

**Comment by ChimeraGaming** [comment]
Stone Block 3

**Comment by MichaelHillcox** [comment]
Not an app issue, please go here https://go.ftb.team/support-modpack
