### ISSUE TITLE
[Bug]: stuck on "installing modloader"

### ISSUE THREAD

**Issue by radvinboi** [FTBTeam/FTB-App#778]
### What Operating System

Windows 10

### App Version

202211151621-329441ed6d-release

### UI Version

329441ed6d

### Log Files

https://pste.ch/ecujizusix
https://pste.ch/icomudabab

### Debug Code

FTB-DBGHEJUYOHUVU

### Describe the bug

when i try to download any modpack, it gets stuck on "installing modloader". i've tried using a vpn and i even have reinstalled FTB and Overwolf but nothing seems to work

### Steps to reproduce

I don't know how to reproduce this.

### Expected behaviour

modpack should be downloaded without problems

### Screenshots

don't have a screenshot

### Additional information

I live in Iran
windows is actually 11 but there was no option for it so I put in 10

### Information

- [x] I have provided as much information as possible

**Comment by WhyNotCthulhu** [comment]
I'm having the same issue. I know someone pointed out DNS issues but some of us can't change our DNS settings to specifically allow api.adoptium.net to come through.

**Comment by CerealHealer** [comment]
Same issue, have tried every related guide online (open in administrator, restart, different internet, etc.) Unable to solve after 2 hours. Trying to download Stoneblock 2

**Comment by cosmo5001** [comment]
https://www.windowscentral.com/how-change-your-pcs-dns-settings-windows-10
This is a great guide to change your DNS settings on windows, using Google's free DNS server completely fixed the problem for me.

**Comment by MichaelHillcox** [comment]
Closed, as the debug tool was not run after the app encountered the error. Also, this issue is super old, try updating and let me know if this still happens.
