### ISSUE TITLE
[Bug]: instance never finishes loading

### ISSUE THREAD

**Issue by tommyrobot666** [FTBTeam/FTB-App#779]
### What Operating System

Windows 10

### App Version

202211151621-329441ed6d-release

### UI Version

329441ed6d

### Log Files

Instance log: https://pste.ch/okocadefuw.md
 SUCCESS  Uploaded settings.json: https://pste.ch/tazarosayi
 SUCCESS  Uploaded version_manifest.json: https://pste.ch/joximidoje
 SUCCESS  Uploaded debug.log: https://pste.ch/erakobageh
 SUCCESS  Uploaded latest.log: https://pste.ch/nadogegabi
 SUCCESS  Uploaded thuttech.log: https://pste.ch/iconifabuw
 SUCCESS  Uploaded debug.log: https://pste.ch/dexipalihe
 SUCCESS  Uploaded latest.log: https://pste.ch/tigucezozu
 SUCCESS  Uploaded hs_err_pid13476.log: https://pste.ch/wuzururiku
 SUCCESS  Uploaded hs_err_pid364.log: https://pste.ch/tayuhivale

### Debug Code

yvuiyvdifuyge bsphunfdvr edxj bpnfgj o xvduh9z[pnTAPU DHTG7HUfdx bi

### Describe the bug

i can't run modpacks and i don't know why, instance never finishes loading or i walk away and my computer gos into sleep mode and when i come back the ftb app isn't open.

### Steps to reproduce

1.try to run a modpack

### Expected behaviour

never finishing loading or crashing

### Additional information

DEBUGER DIDN'T GIVE A CODE, SO DON'T TRUST DEBUG CODE
debuger:
                                               ███████ ████████ ██████
                                               ██         ██    ██   ██
                                               █████      ██    ██████
                                               ██         ██    ██   ██
                                               ██         ██    ██████

                                                Version: 1.0.1-e79a6679
                                             Fri, 02 Dec 2022 04:04:34 UTC

# System Information

 INFO  OS: Microsoft Windows 10 Pro (10.0.19044)
 INFO  CPU: Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz (GenuineIntel)
 INFO  Memory: 5.09 GiB / 11.89 GiB (42.00% used)
 INFO  Java Home: C:\Program Files\Eclipse Adoptium\jdk-17.0.2.8-hotspot\
 INFO  Killing FTB App

# FTB App Checks

# Network requests checks

 SUCCESS  https://api.modpacks.ch/public/api/ping returned expected results
 SUCCESS  https://api.creeper.host/api/health returned expected results
 SUCCESS  https://maven.creeperhost.net returned expected results
 SUCCESS  https://maven.fabricmc.net returned expected results
 SUCCESS  https://maven.minecraftforge.net/net/minecraftforge/forge/maven-metadata.xml returned expected results
 SUCCESS  FTB App directory (AppData): file/directory exists

## Validating App structure

 SUCCESS  Minecraft bin directory: file/directory exists

## App info

 INFO  Located app at C:\Users\tommyrobot\AppData\Local/.ftba
 INFO  App version: 1.22.1115.1621
 INFO  Backend version: 202211151621-329441ed6d-release
 INFO  Web version: 329441ed6d
 INFO  Branch: release
 SUCCESS  Does app_settings.json exist?: file/directory exists
 INFO  Instance Location:  C:\Users\tommyrobot\AppData\Local\.ftba\instances

# Check for instances

 SUCCESS  instances directory: file/directory exists
 INFO  found instance:  01995538-fc7f-4c1f-9095-070380e21453
 INFO  Name: FTB Horizons III
 INFO  Version: 1.9.0
 INFO  Version ID: 151
 INFO  Memory: 5120
 INFO  Min/Rec Memory: 3072/4096
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 SUCCESS  01995538-fc7f-4c1f-9095-070380e21453 logs folder: file/directory exists
 INFO  debug.log last modified: 16/02/2021 11:28:13
 INFO  latest.log last modified: 16/02/2021 11:28:13
 INFO  thuttech.log last modified: 16/02/2021 10:44:02
 SUCCESS  01995538-fc7f-4c1f-9095-070380e21453 instance.json: file/directory exists
 SUCCESS  01995538-fc7f-4c1f-9095-070380e21453 instance.json: json is valid
 INFO  found instance:  2704b094-452a-4850-a0d0-92c9bedefd1a
  ERROR   Error reading instance.json: unexpected end of JSON input
 INFO  Name:
 INFO  Version:
 INFO  Version ID: 0
 INFO  Memory: 0
 INFO  Min/Rec Memory: 0/0
 INFO  Custom Args:
 INFO  Embedded JRE: false
 INFO  Is Modified: false
 WARNING  2704b094-452a-4850-a0d0-92c9bedefd1a logs folder: file/directory does not exist
 WARNING  2704b094-452a-4850-a0d0-92c9bedefd1a instance.json: file/directory does not exist
  ERROR   instance.json failed to validate
 INFO  found instance:  35860630-a9ed-40d5-8bfe-e5b49887633f
 INFO  Name: FTB Presents Stoneblock 2
 INFO  Version: 1.21.1
 INFO  Version ID: 153
 INFO  Memory: 6122
 INFO  Min/Rec Memory: 4096/6122
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 SUCCESS  35860630-a9ed-40d5-8bfe-e5b49887633f logs folder: file/directory exists
 INFO  debug.log last modified: 01/03/2021 23:27:15
 INFO  latest.log last modified: 01/03/2021 23:27:15
▀  Checking for 35860630-a9ed-40d5-8bfe-e5b49887633f instance.json (0s)ctory exists
 SUCCESS  35860630-a9ed-40d5-8bfe-e5b49887633f instance.json: json is valid
 INFO  found instance:  40ecbb26-b27d-47e7-9882-bdb05d7fb0c9
 INFO  Name: FTB University
 INFO  Version: 1.2.1
 INFO  Version ID: 216
 INFO  Memory: 5000
 INFO  Min/Rec Memory: 3000/5000
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 SUCCESS  40ecbb26-b27d-47e7-9882-bdb05d7fb0c9 logs folder: file/directory exists
 INFO  2021-01-06-5.log last modified: 06/01/2021 23:41:24
 INFO  console.log last modified: 30/11/2022 17:48:16
 INFO  debug.log last modified: 30/11/2022 17:48:16
 INFO  latest.log last modified: 30/11/2022 17:48:16
 SUCCESS  40ecbb26-b27d-47e7-9882-bdb05d7fb0c9 instance.json: file/directory exists
 SUCCESS  40ecbb26-b27d-47e7-9882-bdb05d7fb0c9 instance.json: json is valid
 INFO  found instance:  4a20774f-d5af-4329-ba18-907c7b5ac12b
 INFO  Name: FTB Continuum
 INFO  Version: 1.7.0
 INFO  Version ID: 149
 INFO  Memory: 4096
 INFO  Min/Rec Memory: 3072/4096
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 SUCCESS  4a20774f-d5af-4329-ba18-907c7b5ac12b logs folder: file/directory exists
 INFO  debug.log last modified: 28/01/2021 23:02:30
 INFO  latest.log last modified: 28/01/2021 23:02:30
 SUCCESS  4a20774f-d5af-4329-ba18-907c7b5ac12b instance.json: file/directory exists
 SUCCESS  4a20774f-d5af-4329-ba18-907c7b5ac12b instance.json: json is valid
 INFO  found instance:  4b6ac73c-8891-4921-83a1-df036d6bf5a6
 INFO  Name: FTB University 1.12
 INFO  Version: 1.2.1
 INFO  Version ID: 216
 INFO  Memory: 5000
 INFO  Min/Rec Memory: 3000/5000
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 SUCCESS  4b6ac73c-8891-4921-83a1-df036d6bf5a6 logs folder: file/directory exists
 INFO  console.log last modified: 30/11/2022 19:24:47
 INFO  debug.log last modified: 30/11/2022 19:24:46
 INFO  latest.log last modified: 30/11/2022 19:24:46
 SUCCESS  4b6ac73c-8891-4921-83a1-df036d6bf5a6 instance.json: file/directory exists
 SUCCESS  4b6ac73c-8891-4921-83a1-df036d6bf5a6 instance.json: json is valid
 INFO  found instance:  503a6ef0-0343-40e6-b802-e9ffcfaba52d
 INFO  Name: FTB Interactions
 INFO  Version: 2.12.1
 INFO  Version ID: 2130
 INFO  Memory: 5500
 INFO  Min/Rec Memory: 4250/5500
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 SUCCESS  503a6ef0-0343-40e6-b802-e9ffcfaba52d logs folder: file/directory exists
 INFO  console.log last modified: 01/12/2022 18:45:49
 INFO  debug.log last modified: 01/12/2022 18:45:49
 INFO  latest.log last modified: 01/12/2022 18:45:49
 SUCCESS  503a6ef0-0343-40e6-b802-e9ffcfaba52d instance.json: file/directory exists
 SUCCESS  503a6ef0-0343-40e6-b802-e9ffcfaba52d instance.json: json is valid
 INFO  found instance:  7a6ee8e0-1957-47ce-9adb-a64bdf6b5c6f
 INFO  Name: FTB Tech World
 INFO  Version: 1.2.0
 INFO  Version ID: 197
 INFO  Memory: 4096
 INFO  Min/Rec Memory: 4096/4096
 INFO  Custom Args:  -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Dminecraft.applet.TargetDirectory=C:\Users\tommyrobot\AppData\Local\.ftba\instances\7a6ee8e0-1957-47ce-9adb-a64bdf6b5c6f
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 WARNING  7a6ee8e0-1957-47ce-9adb-a64bdf6b5c6f logs folder: file/directory does not exist
 SUCCESS  7a6ee8e0-1957-47ce-9adb-a64bdf6b5c6f instance.json: file/directory exists
 SUCCESS  7a6ee8e0-1957-47ce-9adb-a64bdf6b5c6f instance.json: json is valid
 INFO  found instance:  7b3e0500-0a51-4cec-b2cb-ffe6b9620b54
  ERROR   Error reading instance.json: unexpected end of JSON input
 INFO  Name:
 INFO  Version:
 INFO  Version ID: 0
 INFO  Memory: 0
 INFO  Min/Rec Memory: 0/0
 INFO  Custom Args:
 INFO  Embedded JRE: false
 INFO  Is Modified: false
 WARNING  7b3e0500-0a51-4cec-b2cb-ffe6b9620b54 logs folder: file/directory does not exist
 WARNING  7b3e0500-0a51-4cec-b2cb-ffe6b9620b54 instance.json: file/directory does not exist
  ERROR   instance.json failed to validate
 INFO  found instance:  89f691ef-397b-4ff1-9e12-157429147124
 INFO  Name: FTB OceanBlock
 INFO  Version: 1.11.0
 INFO  Version ID: 2105
 INFO  Memory: 8576
 INFO  Min/Rec Memory: 4096/6144
 INFO  Custom Args:
 INFO  Embedded JRE: false
 INFO  Is Modified: false
 SUCCESS  89f691ef-397b-4ff1-9e12-157429147124 logs folder: file/directory exists
 INFO  debug.log last modified: 19/01/2022 16:53:54
 INFO  latest.log last modified: 19/01/2022 16:53:54
▀  Checking for 89f691ef-397b-4ff1-9e12-157429147124 instance.json (0s)ctory exists
 SUCCESS  89f691ef-397b-4ff1-9e12-157429147124 instance.json: json is valid
 INFO  found instance:  ccf25d6c-ad07-4b98-ab94-5917449af1bd
 INFO  Name: FTB Presents Direwolf20 1.16
 INFO  Version: 1.4.1
 INFO  Version ID: 220
 INFO  Memory: 7168
 INFO  Min/Rec Memory: 4096/6144
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 SUCCESS  ccf25d6c-ad07-4b98-ab94-5917449af1bd logs folder: file/directory exists
 INFO  debug.log last modified: 21/01/2021 23:18:02
 INFO  latest.log last modified: 21/01/2021 23:18:02
 SUCCESS  ccf25d6c-ad07-4b98-ab94-5917449af1bd instance.json: file/directory exists
 SUCCESS  ccf25d6c-ad07-4b98-ab94-5917449af1bd instance.json: json is valid
 INFO  found instance:  d66dfe04-fa77-419f-9b4d-7a0f99c93c13
 INFO  Name: FTB Mage Quest
 INFO  Version: 1.2.0
 INFO  Version ID: 207
 INFO  Memory: 4096
 INFO  Min/Rec Memory: 4096/4096
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 WARNING  d66dfe04-fa77-419f-9b4d-7a0f99c93c13 logs folder: file/directory does not exist
▀  Checking for d66dfe04-fa77-419f-9b4d-7a0f99c93c13 instance.json (0s)ctory exists
 SUCCESS  d66dfe04-fa77-419f-9b4d-7a0f99c93c13 instance.json: json is valid
 INFO  found instance:  e43ef5e6-f2e0-4ba5-a999-29555a1299fd
 INFO  Name: FTB Inventions
 INFO  Version: 1.0.2
 INFO  Version ID: 114
 INFO  Memory: 4096
 INFO  Min/Rec Memory: 4096/4096
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 SUCCESS  e43ef5e6-f2e0-4ba5-a999-29555a1299fd logs folder: file/directory exists
 INFO  latest.log last modified: 18/01/2021 23:12:37
 SUCCESS  e43ef5e6-f2e0-4ba5-a999-29555a1299fd instance.json: file/directory exists
 SUCCESS  e43ef5e6-f2e0-4ba5-a999-29555a1299fd instance.json: json is valid
 INFO  found instance:  ee641802-b16e-4753-b53d-bcd466214451
 INFO  Name: FTB Sky Adventures
 INFO  Version: 1.5.0
 INFO  Version ID: 148
 INFO  Memory: 4096
 INFO  Min/Rec Memory: 3072/4096
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 SUCCESS  ee641802-b16e-4753-b53d-bcd466214451 logs folder: file/directory exists
 INFO  debug.log last modified: 15/04/2021 22:47:12
 INFO  latest.log last modified: 15/04/2021 22:47:12
▀  Checking for ee641802-b16e-4753-b53d-bcd466214451 instance.json (0s)ctory exists
 SUCCESS  ee641802-b16e-4753-b53d-bcd466214451 instance.json: json is valid
 INFO  found instance:  f40e5684-d5cb-4afb-8fab-744c1b696a32
 INFO  Name: FTB Omnia
 INFO  Version: 1.7.0
 INFO  Version ID: 91
 INFO  Memory: 5120
 INFO  Min/Rec Memory: 4096/5120
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 SUCCESS  f40e5684-d5cb-4afb-8fab-744c1b696a32 logs folder: file/directory exists
 INFO  debug.log last modified: 07/01/2021 21:17:20
 INFO  latest.log last modified: 07/01/2021 21:17:20
 SUCCESS  f40e5684-d5cb-4afb-8fab-744c1b696a32 instance.json: file/directory exists
 SUCCESS  f40e5684-d5cb-4afb-8fab-744c1b696a32 instance.json: json is valid
 INFO  found instance:  fe6ace47-ced5-492d-a47c-fd453ded19cb
 INFO  Name: FTB Sky Odyssey
 INFO  Version: 1.4.1
 INFO  Version ID: 2248
 INFO  Memory: 7168
 INFO  Min/Rec Memory: 4096/4096
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 SUCCESS  fe6ace47-ced5-492d-a47c-fd453ded19cb logs folder: file/directory exists
 INFO  console.log last modified: 30/11/2022 21:03:40
 INFO  debug.log last modified: 01/12/2022 18:33:49
 INFO  latest.log last modified: 01/12/2022 18:33:49
 SUCCESS  fe6ace47-ced5-492d-a47c-fd453ded19cb instance.json: file/directory exists
▀  Checking for fe6ace47-ced5-492d-a47c-fd453ded19cb instance.json (0s) SUCCESS  fe6ace47-ced5-492d-a47c-fd453ded19cb instance.json: json is valid

# Upload logs

 SUCCESS  Uploaded settings.json: https://pste.ch/tazarosayi
 SUCCESS  Uploaded version_manifest.json: https://pste.ch/joximidoje
 SUCCESS  Uploaded debug.log: https://pste.ch/erakobageh
 SUCCESS  Uploaded latest.log: https://pste.ch/nadogegabi
 SUCCESS  Uploaded thuttech.log: https://pste.ch/iconifabuw
 SUCCESS  Uploaded debug.log: https://pste.ch/dexipalihe
 SUCCESS  Uploaded latest.log: https://pste.ch/tigucezozu
 SUCCESS  Uploaded hs_err_pid13476.log: https://pste.ch/wuzururiku
 SUCCESS  Uploaded hs_err_pid364.log: https://pste.ch/tayuhivale

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Closed due to no debug code.
