### ISSUE TITLE
Issues with FTB App- cannot connect to minetogether when logging into Stoneblock 3 modpack. Also some thumbnails are missing when launching the ftb app.

### ISSUE THREAD

**Issue by Savvy0787** [FTBTeam/FTB-App#780]
heres my debug code: FTB-DBGOKEWAXIPAC

**Comment by covers1624** [comment]
Minetogether verification issues need to be reported to the MineTogether Github issue tracker.

As for your missing thumbnails, do you have any screenshots of this? It's literally impossible to help you if you just say 'its broken'.

**Comment by manmaed** [comment]
This is for App Issues only! Please use the Modpack issue Tracker Here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
