### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ludvigfg** [FTBTeam/FTB-App#781]
### What Operating System

Windows 10

### App Version

202211151621-329441ed6d-release

### UI Version

329441ed6d

### Log Files

![download](https://user-images.githubusercontent.com/119788858/205486751-b8ef7679-bc1f-4637-bafb-309a226699b1.png)
Share code for the instance for sky factory 3  "K9E6x"

### Debug Code

 FTB-DBGAJITUFESEQ

### Describe the bug

when i launch Sky factory trough the ftb app and i try to join my friends server i always get the error message "Internal Exception: java.io.IOException: an existing connection was forcibly closed by the remote host"

### Steps to reproduce

1. open ftb app and download sky factory 3 mod
2. launch the mod 
3. go to multiplayer and slect join server
4. use the ip address to my friends server which is 31.214.161.90:6969
5. then i get the error message and it wont let me join

### Expected behaviour

Whats expected to happen is that i load into the server then i join the server without any problem 

### Screenshots

![Skjermbilde (2)](https://user-images.githubusercontent.com/119788858/205487275-fcdd047c-810a-4521-9952-89720367144e.png)
![Skjermbilde (3)](https://user-images.githubusercontent.com/119788858/205487283-db55935f-0e79-4ac5-878c-27fa4409475a.png)
![Skjermbilde (3)](https://user-images.githubusercontent.com/119788858/205487286-c476c270-ba83-46d1-99fb-fa030ded9513.png)
![Skjermbilde (5)](https://user-images.githubusercontent.com/119788858/205487293-ccf4bd56-d79c-400d-9c77-b01435014b3d.png)
![Skjermbilde (7)](https://user-images.githubusercontent.com/119788858/205487301-c7177ee7-5a36-4f3f-bafe-bba3fde7edf1.png)

![Skjermbilde (9)](https://user-images.githubusercontent.com/119788858/205487315-2ce3cec4-ddb3-4c4a-867e-18c47f27fa48.png)
![Skjermbilde (10)](https://user-images.githubusercontent.com/119788858/205487322-7ed16c08-ad22-48ce-a528-813592e57fe0.png)
![Skjermbilde (12)](https://user-images.githubusercontent.com/119788858/205487328-0850b783-90e8-471b-b4ea-2e313a7aca09.png)

### Information

- [X] I have provided as much information as possible

**Comment by tommyrobot666** [comment]
it's a normal minecraft thing (happened to me a lot) so if you reload minecraft (quit the game and reopen the game) it should start working

**Comment by manmaed** [comment]
This is for App Issues only! Please use the Modpack issue Tracker Here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
