### ISSUE TITLE
[Bug]: Json? PLEASE I WANT TO PLAY 

### ISSUE THREAD

**Issue by Laniff** [FTBTeam/FTB-App#782]
### What Operating System

Windows 10

### App Version

1.4.1

### UI Version

329441ed6d

### Log Files

https://pste.ch/jupomogubi

### Debug Code

FTB-DBGODOSAGANUL

### Describe the bug

i have no idea what it is i just want to play the game but every time I load the mod it just gets to validate client then crashes 

### Steps to reproduce

I dont know never seen this or had this issue before tried looking it up but doesnt help

### Expected behaviour

N/a

### Screenshots

![ftb ss validate client](https://user-images.githubusercontent.com/120015075/206147959-8a0a728a-406a-4664-b150-ae76db0cfc7c.png)

### Additional information

Every time I load FTB Revelations it starts to load then stops once the loading log gets to validate client I've updated both java, Microsoft, ftb, over wolf. everything thing that I could think of what connects to FTB but nothing works. please help me.

### Information

- [X] I have provided as much information as possible

**Comment by rozbrajaczpoziomow** [comment]
`java.io.IOException: Cannot run program "C:\Users\ethan\AppData\Local\.ftba\bin\runtime\jdk8u312-b07-jre\bin\javaw.exe"`

**Comment by MichaelHillcox** [comment]
Looks like the pack was installed whilst the app was in Admin mode. Please reinstall the pack without the app running as admin
