### ISSUE TITLE
[Bug]: Stone Block 2 - Hammercore crash

### ISSUE THREAD

**Issue by SometimesClueless** [FTBTeam/FTB-App#783]
### What Operating System

Windows 10

### App Version

1.4.1

### UI Version

329441ed6d

### Log Files

[crash-2022-12-07_21.35.17-client.txt](https://github.com/FTBTeam/FTB-App/files/10180213/crash-2022-12-07_21.35.17-client.txt)

### Debug Code

FTB-DBGUTESOROZEK

### Describe the bug

Game crashed

### Steps to reproduce

I was in the middle of connecting my ME drives to power to connect them to my ME terminal. 

I had placed down ME dense smart cables (I'm under the assumption that they work faster than the normal flux cables) and had placed a dense energy cell down, when the game crashed and said Hammer core/something crash.

### Expected behaviour

To connect my ME drives to my ME ternimal to access them

### Information

- [X] I have provided as much information as possible

**Comment by covers1624** [comment]
This issue tracker is for issues with the FTBApp, not modpacks. Please go here: https://go.ftb.team/support-modpack
