### ISSUE TITLE
[Bug]: Stoneblock 3 can't start/crashing on start up

### ISSUE THREAD

**Issue by Awyh1113** [FTBTeam/FTB-App#784]
### What Operating System

Windows 10

### App Version

1.3.0 to 1.4.2

### Log Files

https://pste.ch/hutimigujo

### Debug Code

FTB-DBGQOFUGEROJO

### Describe the bug

When press play, it will load and open minecraft but immediatly close itself

### Steps to reproduce

1. Press play
2. Wait loading
3. Minecraft crash

### Expected behaviour

Launch Normally

### Information

- [X] I have provided as much information as possible

**Comment by Heckro001** [comment]
the same issue
1. Press play
2. Wait loading
3. minecraft saving world then shut down minecraft
4. crash
crash report file
[https://mega.nz/file/C0w3UJrD#vCRrkF0A7Vz0TXLRZlMubziTyLmK--ywvFCebgMgGaE](url)

**Comment by BobSolo** [comment]
Same issue for me. Gets to Saving World then crashes :(

[crash-2022-12-09_11.35.30-client.txt](https://github.com/FTBTeam/FTB-App/files/10190273/crash-2022-12-09_11.35.30-client.txt)

**Comment by Wangus85** [comment]
I'm having the same issue; I even reinstalled the entire pack + files still crashes on the load screen.

**Comment by andrewjbennett** [comment]
This bug is from "BetterThanLlamas", which has an "Easter Egg Day" on the 1st of April and 9th of December (with a bug that prevents the game from loading). You can work around it by changing your computer's date, waiting until tomorrow to play, or just removing the mod entirely. 

https://github.com/iChun/BetterThanLlamas/issues/3

**Comment by wormwoodworms** [comment]
This solution worked. Crashed 5 times today, found this, removed the BetterThanLlamas mod, and it just booted up nicely on the first try. Thank you o/.

**Comment by dittymargoo** [comment]
Thank you for the solution.  I'd tried a few things after 3crashes and only this worked...bye bye 'BetterThanLlamas".

**Comment by imZelos** [comment]
just delete betterthanllamas mod

**Comment by BobSolo** [comment]
> This bug is from "BetterThanLlamas", which has an "Easter Egg Day" on the 1st of April and 9th of December (with a bug that prevents the game from loading). You can work around it by changing your computer's date, waiting until tomorrow to play, or just removing the mod entirely.
> 
> [iChun/BetterThanLlamas#3](https://github.com/iChun/BetterThanLlamas/issues/3)

andrewjbennett you are a god amongst men. Thank you.

**Comment by covers1624** [comment]
This issue tracker is for issues with the FTBApp, not modpacks. Please go here: https://go.ftb.team/support-modpack
