### ISSUE TITLE
[Bug]: Windows 11 StoneBlock3 ALT+TAB Stuck

### ISSUE THREAD

**Issue by tmobilyalari** [FTBTeam/FTB-App#785]
### What Operating System

Windows Insider Preview

### UI Version

f02f4914-d454-4b7d-95f3-16c4f3158615

### Debug Code

FTB-DBGSOHIMUROTU

### Describe the bug

If you are using Windows 11 Developer Edition Build Number: 25252.1010 and Custom Minecraft Launcher(TLauncher) and Alt + Tab, you cannot return to the game.

### Steps to reproduce

Event start priority order:
1. Launch the launcher and the game.
2. Create new world.
3. Enter the world.
4. Start playing.
5. Do the Alt+Tab combination to switch to the background.
6. Repeat step 5 while on the desktop or in another program.
and there's no going back as you'll see because something automatic is blocking it.
Sequence of workaround steps:
1. Close the launcher.
2. Reopen the launcher.
3. Keep playing.

### Expected behaviour

solve this bug.

### Information

- [X] I have provided as much information as possible

**Comment by covers1624** [comment]
This issue tracker is for issues with the FTBApp, not modpacks. Please go here: https://go.ftb.team/support-modpack

**Comment by tmobilyalari** [comment]
i found problem mod and solve this please. problem mod is chipped 2.0 and deleted mod solved problen
