### ISSUE TITLE
[Bug]: StoneBlock 3 1.4.2 Crashes at start up.

### ISSUE THREAD

**Issue by onsidekiller** [FTBTeam/FTB-App#786]
### What Operating System

Windows 10

### App Version

202211151621-329441ed6d-release

### UI Version

329441ed6d

### Log Files

https://pastebin.com/ZHmhPhac

### Debug Code

FTB-DBGIWOQASUGAK

### Describe the bug

Game crashes before it gets to main menu.

### Steps to reproduce

Start the game and it crashes.

### Expected behaviour

To be able to play.

### Additional information

This is on verison 1.4.2 but i've also tried to unistall it delete the instance and redownload with 1.3.0 and it still crashes. Earlier i was able to play for a few hours in a server with friends, so im not sure why this is happening now.

### Information

- [X] I have provided as much information as possible

**Comment by malro57** [comment]
Hi, I have exactly the same error.

**Comment by osapqwe** [comment]
Hi i have same .

**Comment by skyfyx** [comment]
Hi , same here, maybe something with Mojang ?

**Comment by GogumaYummy** [comment]
Sadly, I have the same

**Comment by malro57** [comment]
We're able to start it by removing the mod file BetterThanLlamas-1.18-1.1.1.jar

**Comment by barks1** [comment]
> 
This works for me.

**Comment by asteriqz** [comment]
> Having the same issue after using the beta version Log file suggests that betterthanllamas.toml under the instance folder/config is causing the issue? If I change the setting in betterthanllamas.toml : applyOn = 0 instead of = 3 to disable it,. then the pack starts fine Not suggesting this is a fix as I am unsure if this would cause any issues? Backup your world always if you want to try! I am sure they will fix this in an upcoming version

Thanks mate, this has worked for me - I can now play FTB with my mate Ming.

**Comment by manmaed** [comment]
This is for App Issues only! Please use the Modpack issue Tracker Here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
