### ISSUE TITLE
[Bug]: Stoneblock 3 Crashing on startup

### ISSUE THREAD

**Issue by barks1** [FTBTeam/FTB-App#787]
### What Operating System

Windows 10

### App Version

202211151621-329441ed6d-release

### UI Version

329441ed6d

### Log Files

[crash-2022-12-09_08.51.24-client.txt](https://github.com/FTBTeam/FTB-App/files/10193306/crash-2022-12-09_08.51.24-client.txt)
[crash-2022-12-09_08.46.39-client.txt](https://github.com/FTBTeam/FTB-App/files/10193307/crash-2022-12-09_08.46.39-client.txt)

Crash.39 is after I uninstalled mine together
Crash.24 is with mine together
Same Issue

### Debug Code

FTB-DBGOBUYUFELOS

### Describe the bug

Minecraft Launcher crashes after clicking play.

### Steps to reproduce

1. Boot FTB
2. Click Play 
3. Let the console run etc
4. MC launcher boots
5. then stops responding on mojang screen
6. then crashes and get a red error pop up on ftb app saying instance crashes or was externally closed.

Snapshot just before it crashes

![mojang crash](https://user-images.githubusercontent.com/120171083/206666026-04f38c73-66ef-4bce-8909-90efad42156c.png)

### Expected behaviour

For it to boot.

### Additional information

Tried to uninstall mine together as some people thought it was the problem, Didn't help.
Tried adding additional ram to see if it made a difference, Didn't help. 

### Information

- [X] I have provided as much information as possible

**Comment by biohazzz** [comment]
I have the same issue as you do. I have done the same by uninstalling and reinstalling . 
![Desktop Screenshot 2022 12 09 - 21 02 41 31](https://user-images.githubusercontent.com/120175226/206676887-d6716cdf-8bdb-43df-aaf9-825f0886bfda.png)

**Comment by barks1** [comment]
"Having the same issue after using the beta version
Log file suggests that betterthanllamas.toml under the instance folder/config is causing the issue?
If I change the setting in betterthanllamas.toml : applyOn = 0 instead of = 3 to disable it,. then the pack starts fine
Not suggesting this is a fix as I am unsure if this would cause any issues? Backup your world always if you want to try!
I am sure they will fix this in an upcoming version"

Found this on another thread and it fixed the issue.

**Comment by biohazzz** [comment]
Thank you will give it a go now

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by biohazzz** [comment]
Sweet its working fine now thanks heaps

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Eacaw** [comment]
https://github.com/FTBTeam/FTB-App/issues/787#issuecomment-1344104204

☝️  Can confirm this fix worked for me too.

**Comment by gregdixon99** [comment]
Had same crashing issue.  Can confirm that changing

applyOn = 0 instead of = 3

in betterthanllamas.toml worked for me as well.

**Comment by barks1** [comment]
glad it helped guys an update realised today may of fixed the issue.

**Comment by manmaed** [comment]
This is for App Issues only! Please use the Modpack issue Tracker Here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
