### ISSUE TITLE
[Bug]: direwolf20 1.18.2 crashing at start up

### ISSUE THREAD

**Issue by NMP3D** [FTBTeam/FTB-App#788]
### What Operating System

Windows 10

### App Version

direwolf20 1.18.2 1.10.2

### Debug Code

FTB-DBGUSEJOBAWIG

### Describe the bug

when I try to start it after the red screen and the word save world the modpack crash

### Steps to reproduce

1.click play
2.wait for launch minecraft
3.appear red minecraft preview
4.screen whit word "saving world"
5.crash

### Expected behaviour

start the modpack

### Screenshots

![Knipsel](https://user-images.githubusercontent.com/80418088/206680305-6a86af43-6f07-4813-915c-d2160d8ca5bc.PNG)

### Information

- [X] I have provided as much information as possible

**Comment by manmaed** [comment]
This is for App Issues only! Please use the Modpack issue Tracker Here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
