### ISSUE TITLE
[Bug]: Stoneblock 3, failed render overlay, cant fix

### ISSUE THREAD

**Issue by CoCuCoH41k** [FTBTeam/FTB-App#789]
### What Operating System

Windows 10

### App Version

202211151621-329441ed6d-release

### UI Version

329441ed6d

### Log Files

https://pastebin.com/nyG1bUd8

### Debug Code

FTB-DBGDILERECOLA

### Describe the bug

In loading main menu of Stoneblock 3 i have a crash render overlay

### Steps to reproduce

1. Start Stoneblock 3 ModPack
2. While wait for load final, im getting crash of render overlay

### Expected behaviour

Game didnt crash

### Information

- [X] I have provided as much information as possible

**Comment by JanKarcher** [comment]
I'm having the same issue. Tried re-downloading the Lama mod. No clue what to try to fix this issue.

**Comment by JanKarcher** [comment]
@CoCuCoH41k There are other issues opened for this topic. This did the trick for me:
https://github.com/FTBTeam/FTB-App/issues/786#issuecomment-1344071167
Still wondering why it appears now. Neither the modpack nor the mod seems to have changed from yesterday (it worked back then).

**Comment by DewdleNoodle** [comment]
@JanKarcher  remove the llama mod. It directly is causing the bug because of the date. You could change your Pc's date.

**Comment by manmaed** [comment]
This is for App Issues only! Please use the Modpack issue Tracker Here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
