### ISSUE TITLE
[Bug]: Direwolf20 1.18 1.10.2 Crashing upon startup

### ISSUE THREAD

**Issue by Skegfod** [FTBTeam/FTB-App#790]
### What Operating System

Windows 10

### App Version

1.4.1

### Log Files

[crash-2022-12-09_09.41.54-client.txt](https://github.com/FTBTeam/FTB-App/files/10194698/crash-2022-12-09_09.41.54-client.txt)
[crash-2022-12-09_11.10.44-client.txt](https://github.com/FTBTeam/FTB-App/files/10194699/crash-2022-12-09_11.10.44-client.txt)
[crash-2022-12-09_11.48.35-client.txt](https://github.com/FTBTeam/FTB-App/files/10194700/crash-2022-12-09_11.48.35-client.txt)
[crash-2022-12-09_11.52.22-client.txt](https://github.com/FTBTeam/FTB-App/files/10194701/crash-2022-12-09_11.52.22-client.txt)
[crash-2022-12-09_11.56.21-client.txt](https://github.com/FTBTeam/FTB-App/files/10194702/crash-2022-12-09_11.56.21-client.txt)
[crash-2022-12-09_12.27.45-client.txt](https://github.com/FTBTeam/FTB-App/files/10194703/crash-2022-12-09_12.27.45-client.txt)

### Debug Code

FTB-DBGLEGALESUCO

### Describe the bug

Minecraft is crashing to desktop upon booting up. "Saving world" can be seen briefly.

### Steps to reproduce

1. Go to Libary
2. Click on FTB Presents Direwolf20 1.18
3. Click Play
4. Wait
5. Crash after "Saving world" appears breifly

### Expected behaviour

Minecraft to load and reach the main menu.

### Screenshots

![image](https://user-images.githubusercontent.com/120183636/206702513-04d6c9fe-1bb1-4c5c-83f5-8ebd40905671.png)
![image](https://user-images.githubusercontent.com/120183636/206703044-6e956969-8681-449c-95c1-a31065fab30d.png)

### Additional information

This issue has only started overnight, during that time there was no change in the version or software/hardware.
Briefly before minecraft crashes "Saving world" is seen for approximatley 0.5s.

### Information

- [X] I have provided as much information as possible

**Comment by Skegfod** [comment]
I actually figured out a solution it earlier today (Currently working). The Mod which is causing the issues for me was "BetterThanLlamas-1.18-1.1.1". Moving this out of the mod folder then restarting the FTB app seemed to fix the issue entirely.

Fingers crossed it work for you too.

**Comment by DewdleNoodle** [comment]
Its the llama mod. It's an intentional easter egg

**Comment by vchapandrews** [comment]
Cheers guys!

**Comment by manmaed** [comment]
This is for App Issues only! Please use the Modpack issue Tracker Here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
