### ISSUE TITLE
[Bug]: StoneBlock 3 V1.4.2 crash at end of loading screen

### ISSUE THREAD

**Issue by rubenh2905** [FTBTeam/FTB-App#791]
### What Operating System

Windows 10

### Log Files

[log.txt](https://github.com/FTBTeam/FTB-App/files/10195278/log.txt)

### Debug Code

FTB-DBGIMUVUJEWIP

### Describe the bug

crash after progress bar at loading screan tuch the end

### Steps to reproduce

1. download StoneBlock 3 V1.4.2 on FTB App From Overwolf
2. launch StoneBlock 3 V1.4.2 from any launcher ( FTB it self or use MultiMC )
3. it worked last night ( 8 December 2022 ) but today crashing at loading screen you can see on log files
4. i even tryed to delete .ftb folder and reboot pc and re download game but still same crash

### Expected behaviour

i expected launch game with MultiMC and play like last night without problem

### Information

- [X] I have provided as much information as possible

**Comment by ZealousChaos** [comment]
mine is doing the exact same. its almost as if stoneblock 3 woke up and chose war this morning.

**Comment by uffsdfsf** [comment]
mine never work rly, i just can start the game with luck and i cant start it for hours and then it starts 1 time and crash again if i close it and starts again to see if its fixxed

**Comment by Zenith-One** [comment]
I have the same issue, with identical log, particularly the exception itself:
`java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.m_46658_()" because "p_21369_" is null`

I'm on 1.3.0 though

**Comment by DewdleNoodle** [comment]
OKAY I FOUND THE ISSUE. @rubenh2905 @Zenith-One @uffsdfsf  @ZealousChaos  

It's an easter egg from the llama modpack. Go into it and delete it. That should work. On April 1st and December 9th it intentionally causes the game to be unable to launch. I looked into previous closed bugs and it shows it's proof haha

**Comment by DewdleNoodle** [comment]
Today is llama day I noticed from Microsoft

**Comment by rubenh2905** [comment]
my game fixed on 1.4.3 update

**Comment by tmobilyalari** [comment]
OK. I found victim. Problem is chipped mod. Mod is broken.

**Comment by manmaed** [comment]
This is for App Issues only! Please use the Modpack issue Tracker Here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
