### ISSUE TITLE
[Bug]: Stoneblock 3 V 1.3.0 Crashes on launch or loads until instance is killed

### ISSUE THREAD

**Issue by Bard37** [FTBTeam/FTB-App#792]
### What Operating System

Windows 10

### App Version

V 1.3.0

### Debug Code

FTB-DBGVOQESEZIHI

### Describe the bug

Whenever I try to launch Stoneblock 3 from the FTB app, most of the time it just crashes after a couple of seconds and says that it crashed or was externally closed. Less often, when I try to launch it, it just loads forever and never gets anywhere. (I've let it run for over an hour before and it still did nothing)

### Steps to reproduce

1. Open FTB app
2. Select Stoneblock 3
3. Press Play
4. Wait for it to crash or load continuously 

### Expected behaviour

When I press Play, I expect it to open Stoneblock 3

### Additional information

I tried making sure that I had the right version of Java (17) for Stoneblock 3 and even ran the Jarfix but neither of that helped.  Also, my OS is actually Windows 11, but I just chose Windows 10 because Windows 11 wasn't an option

### Information

- [X] I have provided as much information as possible

**Comment by Bard37** [comment]
Also, it didnt let me put Windows 11 as my OS, so I just chose Windows 10

**Comment by DewdleNoodle** [comment]
I too have started experiencing this as of today. Was playing all this week. The crash description was given as: Rendering overlay
Version 1.4.3 works but not version 1.3.0
I have Java 18 developer kit// Windows 10 home x64 bit// operating with a 3060ti 
I increased the accessible ram to 16gb and it changed nothing.
uninstalled and reinstalled.
started this up from a fresh pc reset.
reduced cache timer to 900 seconds just in case that would effect something.

Adding crash report below.


[crash-2022-12-09_09.57.04-client.txt](https://github.com/FTBTeam/FTB-App/files/10197208/crash-2022-12-09_09.57.04-client.txt)

Here is the crash report. Hopefully this helps <3. Ill be on standby for more questions

**Comment by DewdleNoodle** [comment]
OKAY I FOUND THE ISSUE. @Bard37  It's an easter egg from the llama modpack. Go into it and delete it. On April 1st and December 9th it intentionally causes the game to be unable to launch. l m a o

**Comment by manmaed** [comment]
This is for App Issues only! Please use the Modpack issue Tracker Here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
