### ISSUE TITLE
Direwolf20 1.18 1.9.1 instance crash after Minecraft redscreen

### ISSUE THREAD

**Issue by xGeno17** [FTBTeam/FTB-App#793]
What Operating System
Windows 10

App Version
1.9.1

UI Version
No response

Log Files
[crash-2022-12-09_21.55.17-client.txt](https://github.com/FTBTeam/FTB-App/files/10198350/crash-2022-12-09_21.55.17-client.txt)
[crash-2022-12-09_22.00.24-client.txt](https://github.com/FTBTeam/FTB-App/files/10198351/crash-2022-12-09_22.00.24-client.txt)
[crash-2022-12-09_22.41.48-client.txt](https://github.com/FTBTeam/FTB-App/files/10198352/crash-2022-12-09_22.41.48-client.txt)
[crash-2022-12-09_22.50.03-client.txt](https://github.com/FTBTeam/FTB-App/files/10198353/crash-2022-12-09_22.50.03-client.txt)

Describe the bug
Minecraft is crashing to desktop upon booting up.

Steps to reproduce
Go to Libary
Click on FTB Presents Direwolf20 1.18
Click Play
Wait
Crash at Minecraft red screen loader (sometime before lauching minecraft)

Expected behaviour
Minecraft to load and reach the main menu.

Screenshot :
<img width="1916" alt="crash ftb" src="https://user-images.githubusercontent.com/108180376/206801700-3bb30883-83eb-481d-9c3e-c2b9e2fd2698.png">

**Comment by manmaed** [comment]
This is for App Issues only! Please use the Modpack issue Tracker Here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
