### ISSUE TITLE
FTB Direwolf20 1.19

### ISSUE THREAD

**Issue by Punkenhead** [FTBTeam/FTB-App#795]
### What Operating System

Windows 11

### Debug Code

w

### Describe the bug

When i host a lan game wife cant connect 

### Steps to reproduce

w

### Expected behaviour

w

### Screenshots

![Screenshot (130)](https://user-images.githubusercontent.com/120287879/206882375-0ed8b284-8450-4c82-89a8-43338a7f5414.png)

**Comment by manmaed** [comment]
This is for App Issues only! Please use the Modpack issue Tracker Here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
