### ISSUE TITLE
Direwolf20 1.19

### ISSUE THREAD

**Issue by elijahward** [FTBTeam/FTB-App#796]
### What Operating System

Windows 10

### Debug Code

FTB-DBGUDAWIVADER

### Describe the bug

Storage Drawers Not Showing Items

### Steps to reproduce

The storage drawer isn't showing saplings, apples, or sticks. There may be more.

### Expected behaviour

You should be able to see the items

**Comment by manmaed** [comment]
This is for App Issues only! Please use the Modpack issue Tracker Here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues

**Comment by elijahward** [comment]
Thank you, I will create a new post
