### ISSUE TITLE
minecraft skin not loading

### ISSUE THREAD

**Issue by Cujoplays** [FTBTeam/FTB-App#798]
### What Operating System

Windows 10

### Debug Code

FTB-DBGARIXOLUYES

### Describe the bug

minecraft skin wont load in any mod pack

### Steps to reproduce

open FTB App 
load pack

### Expected behaviour

minecraft skin to load

### Screenshots

![image](https://user-images.githubusercontent.com/49764587/207098511-419a4041-1ecd-4f08-8a60-695fce53d4fb.png)

Skin Also doesnt show on profile tab

### Additional information

i have tried to log out and log back in, delete the ftb app and reinstall it and i still can't get it to load my skin for any mod pack

**Comment by manmaed** [comment]
This should now be resolved
