### ISSUE TITLE
Linux download

### ISSUE THREAD

**Issue by zetosuru** [FTBTeam/FTB-App#8]
I tried a few times back to back, but the ability to download the linux launcher seems to be lacking. I'm presented with what seems to be a .sh script. I copy that, and attempt to run it then presented with nata.

**Comment by Cloudhunter** [comment]
Please right click on the link and click Save-As for now.

**Comment by CH-Paul-T** [comment]
We're planning an rpm, a deb, a tar.gz and continuing with the installer.

**Comment by Gaz492** [comment]
Hi, while we do offer an rpm and a .deb now there appears to be an issue with them, I will close this issue and link it to the issue open regarding the problems with the .deb/rpm #305
