### ISSUE TITLE
duplicate

### ISSUE THREAD

**Issue by ufika2005** [FTBTeam/FTB-App#800]
### What Operating System

Windows 11

### Debug Code

noting

### Describe the bug
stoneblock 3

alchemical bag full netherite block and you have to put an energy condenser in it and the duplication is complete

### Steps to reproduce

alchemical bag full netherite block and you have to put an energy condenser in it and the duplication is complete

### Expected behaviour

I don't expect much, I just tried it by accident

**Comment by covers1624** [comment]
This is for App Issues only! Please use the Modpack issue Tracker Here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
