### ISSUE TITLE
Inventory crash 

### ISSUE THREAD

**Issue by Rider7417** [FTBTeam/FTB-App#801]
### What Operating System

Windows 11

### Debug Code

FTB-DBGMUNOPOJOSU

### Describe the bug

Every time I open my Inventory my game freezes than crashes 

### Steps to reproduce

load up the world and open your inventory 

### Expected behaviour

the game crashing

**Comment by manmaed** [comment]
This is for App Issues only! Please use the Modpack issue Tracker Here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
