### ISSUE TITLE
Typo in package.json

### ISSUE THREAD

**Issue by Gaz492** [FTBTeam/FTB-App#802]
### What Operating System

Windows 11

### Debug Code

N/A

### Describe the bug

There is a typo in the package json

### Steps to reproduce

https://github.com/FTBTeam/FTB-App/blob/bb1250a38b3420fdb8ccb4197f509efcbdf6a31f/package.json#L6

### Expected behaviour

yes

**Comment by covers1624** [comment]
This was fixed last release.
