### ISSUE TITLE
[Bug]: Stoneblock 3 server constantly crashing when trying to startup after trying to use Create's schematic cannon

### ISSUE THREAD

**Issue by Dan-Mizu** [FTBTeam/FTB-App#807]
### What Operating System

Windows 11

### Debug Code

FTB-DBGIPULARIRUR

### Describe the bug

I run a Stoneblock 3 server. Has been running perfectly fine. I am now in the endgame (only need to automate polonium and ethereal slates) and was trying to move one of my machines with the schematic feature in create but when i tried to use the Schematic Cannon it crashed the server, and now it fails to startup producing the same crash log everytime.

### Steps to reproduce

1. Craft Schematic Cannon
2. Place Schematic in the Schematic Cannon
3. Press the "play" or "start" button on the Cannon.
4. Server should crash, and continue to crash everytime it tries to start up.

### Expected behaviour

I expected the server to stay up and not crash due to the usage of the Schematic Cannon in the Create mod.

### Additional information

**Crash Log:**
[https://pastebin.com/EGcbk5nj](https://pastebin.com/EGcbk5nj)

**Comment by covers1624** [comment]
This is for App Issues only! Please use the Modpack issue Tracker Here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
