### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by GNiessen** [FTBTeam/FTB-App#809]
### What Operating System

Windows 11

### Debug Code

FTB-DBGGAZEGAVUQE

### Describe the bug

After I click play it crashes with a crash report after about a minute

### Steps to reproduce

Click Play
Wait for white screen to appear
Wait mods to load
When it gets to createaddition-1.19.2-20221124a.jar it will crash
[crash-2022-12-20_20.20.09-client.txt](https://github.com/FTBTeam/FTB-App/files/10274054/crash-2022-12-20_20.20.09-client.txt)

### Expected behaviour

For the Start Menu to appear

**Comment by GNiessen** [comment]
I forgot to mention that I had played to game many times in the last week, since the last update.  And was able to get it to run once after rebooting.  But then it crashed again after exiting and restarting.

**Comment by covers1624** [comment]
This is for App Issues only! Please use the Modpack issue Tracker Here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
