### ISSUE TITLE
Server installer creates broken startup script

### ISSUE THREAD

**Issue by jikuja** [FTBTeam/FTB-App#81]
Third line in the script just does not work. It should be something like:

```
#!/bin/bash
echo "Do you agree to the Mojang EULA available at https://account.mojang.com/documents/minecraft_eula ?"
read  -n 1 -p "[y/n]" EULA
if [ "$EULA" = "y" ]; then
    echo "eula=true" > eula.txt
fi
java -server -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx8092M -Xms3072M -jar forge-1.15.2-31.1.36.jar nogui
```

But this is not really user friendly because eula question is done every time server is being started

Also I recommend adding `pause` at end of the start.bat. This keeps command prompt open when game crash and gives users access to logs through command line. This is at some cases better for troubleshooting than access log files.

**Comment by Jake-E** [comment]
No version provided.

**Comment by jikuja** [comment]
If we start nitpicking which version should I provide? Pack version or installer version?

What happened pending feedback label?

**Comment by jikuja** [comment]
Omnia 1.1.0 with 13c20a7 server installer has not syntaxically corrent start.sh but

third line is still problematic. Read command returns nothing to stout and therefore EULA environment variable will be entry and creation of eula.txt is skipped even user enters **y** as input:

```
~/omnia-tmp$ bash -x start.sh
+ echo 'Do you agree to the Mojang EULA available at https://account.mojang.com/documents/minecraft_eula ?'
Do you agree to the Mojang EULA available at https://account.mojang.com/documents/minecraft_eula ?
++ read -n 1 -p '[y/n] '
[y/n] y+ EULA=
+ '[' '' = y ']'
+ java -server -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx8092M -Xms3072M -jar forge-1.15.2-31.1.36.jar nogui
[22:32:20] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 31.1.36, --fml.mcpVersion, 20200307.202953, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, nogui]
```

**Comment by Jake-E** [comment]
I believe the server installer updated should have solved this.

**Comment by aqw00** [comment]
Hi jikuja,
I had the same problem but found a solution for you're problem. First start the normal server with putting `java -Xmx4096M -Xms2048M -jar minecraft_server.jar nogui` in the terminal. Then just open the start.sh and it souldn't crash anymore after you typed y
