### ISSUE TITLE
Stoneblock 3 wont load

### ISSUE THREAD

**Issue by romanceizdead** [FTBTeam/FTB-App#810]
### What Operating System

Windows 11

### Debug Code

FTB-DBGWIDUWICUPI

### Describe the bug

Game wont load up past reading world data before freezing and crashing

### Steps to reproduce

1. start the ftb app.
2. launch stoneblock 3
3. click play
4. try to join my only world available
5. sait for game to crash before world loads in.

### Expected behaviour

to be able to join the world ive been working on for weeks

### Screenshots

n/a

### Additional information

n/a

**Comment by covers1624** [comment]
This is an Issue tracker for FTBApp issues only. For further assistance, please see the issue tracker for Modpack issues: https://github.com/FTBTeam/FTB-Modpack-Issues/issues

However, after looking at your logs, your ProjectE server config is corrupt, you may want to re-install the modpack, or delete this file and let a fresh config be generated: https://pste.ch/ahowuhadof.md
