### ISSUE TITLE
why i can't play with friends that play with tluncher?

### ISSUE THREAD

**Issue by nicecer1** [FTBTeam/FTB-App#811]
### What Operating System

Windows 10

### Debug Code

FTB-DBGIZEJIJODIH

### Describe the bug

can't connect to multiplayer

### Steps to reproduce

when click server it crashed

### Expected behaviour

crashed after click join server

### Screenshots

![image](https://user-images.githubusercontent.com/120147947/208939582-3aec832f-2a22-4c19-9ba9-6e577ff5c533.png)

**Comment by covers1624** [comment]
This is an Issue tracker for FTBApp issues only. For further assistance, please see the issue tracker for Modpack issues: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
