### ISSUE TITLE
The downloaded Server Files are incomplete

### ISSUE THREAD

**Issue by zaaazaaza** [FTBTeam/FTB-App#812]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3

### Describe the bug

I'm going to have these two problems when I download,"Server Files provided,will face this problem"Error downloading https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.2%2B8/OpenJDK17U-jre_x64_windows_hotspot_17.0.2_8.zip: Get "https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.2%2B8/OpenJDK17U-jre_x64_windows_hotspot_17.0.2_8.zip": read tcp 192.168.1.103:61287->20.205.243.166:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."and",I can't solvethis problem by redownloading

### Steps to reproduce

1.Open the serverinstall_100_2298,let it run until it runs out,and you'll see the first problem
2.Open the Start,let it run until it runs out,and you'll see the second problem

### Expected behaviour

Successfully download the first file and let the second program run

### Screenshots

![屏幕截图 2022-12-21 092015](https://user-images.githubusercontent.com/121138512/208800325-2e048edb-f83d-448e-b3eb-cd4f8c877e51.png)
![屏幕截图 2022-12-21 082453](https://user-images.githubusercontent.com/121138512/208800357-a947ece5-20a9-444e-a482-9bf00a8f1caf.png)

**Comment by covers1624** [comment]
It appears the modpack installer has failed to download both the Minecraft server jar and a Java runtime.

You will need to ensure that both Mojang's servers and Github are not blocked by your country's DNS. It is also possible that an unstable internet connection is causing your issues as both of these files are quite large.

You can skip downloading the java runtime with the `--nojava` argument if you wish.
