### ISSUE TITLE
The downloaded Server Files are incomplete,and I downloaded the required file,he failed to recognize,even the program crash.

### ISSUE THREAD

**Issue by zaaazaaza** [FTBTeam/FTB-App#813]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3

### Log Files

[eula.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10283015/eula.txt)

### Describe the bug

![屏幕截图 2022-12-22 091750](https://user-images.githubusercontent.com/121138512/209035915-9c7f45de-8293-47dd-a13c-1ab858b6a087.png)

### Steps to reproduce

1.
![屏幕截图 2022-12-22 091929](https://user-images.githubusercontent.com/121138512/209035942-3bae0d5b-8539-4302-8ef1-f5b155f1db5d.png)
2.
![屏幕截图 2022-12-22 091852](https://user-images.githubusercontent.com/121138512/209036012-7b84506f-154c-4206-85f2-925558f0f2d7.png)
3.
![屏幕截图 2022-12-22 091623](https://user-images.githubusercontent.com/121138512/209036083-7ed43eb9-abc1-4020-8576-4660c16918a1.png)
4.
![屏幕截图 2022-12-22 091750](https://user-images.githubusercontent.com/121138512/209036107-67132d3d-5b34-4897-a0be-84a745cdefd8.png)

### Expected behaviour

start.bat runs properly

### Screenshots

![屏幕截图 2022-12-22 091929](https://user-images.githubusercontent.com/121138512/209036535-cfd8aafd-4165-434b-b469-dbcce2afeca9.png)
![屏幕截图 2022-12-22 091852](https://user-images.githubusercontent.com/121138512/209036549-e8f55f43-faa5-440c-a40b-975a1d31be80.png)
![屏幕截图 2022-12-22 091623](https://user-images.githubusercontent.com/121138512/209036575-88512c9c-3a3b-411a-afbc-fb1bf84d9108.png)
![屏幕截图 2022-12-22 091750](https://user-images.githubusercontent.com/121138512/209036588-6ff8156b-49f2-49bf-8bc3-7a43c46d7775.png)

**Comment by CoryNB** [comment]
your using Japanese language. using English first before changing it should help resolve it because english is simpler to computers due to the 26 instead of unique code for language.

**Comment by MichaelHillcox** [comment]
Not an app issue. Please report here https://github.com/CreeperHost/modpacksch-serverdownloader/issues
