### ISSUE TITLE
when loading the app it tells me to try again and a error occured i try again doesnt work reinstall doesnt work im not sure why this is happening

### ISSUE THREAD

**Issue by weamsabri** [FTBTeam/FTB-App#814]
### What Operating System

Windows 10

### Debug Code

FTB-DBGAZIMANAKIJ

### Describe the bug

im not exactly sure the app just tells me to try to open it again and a problem has occured

### Steps to reproduce

it happend when i opened the app first time

### Expected behaviour

i expected it to load into the app normally without a popup 

### Screenshots

![image](https://user-images.githubusercontent.com/95435129/209303634-5b99588b-3c85-4678-b686-af1da818d295.png)

**Comment by MichaelHillcox** [comment]
Compacting to #890
