### ISSUE TITLE
windows clock halt

### ISSUE THREAD

**Issue by Wingnut24** [FTBTeam/FTB-App#816]
### What Operating System

Windows 10

### Debug Code

FTB-DBGTUWUWEMURO

### Describe the bug

windows tray clock not working while playing

### Steps to reproduce

open ftb app
click on modpack you wish to play (my case Direwolf20 1.19)
from the time the modpack starts loading the windows tray clock stops
it will refresh when clicking onto windows desktop, sometimes by running cursor over the clock also refreashes the clock.

### Expected behaviour

why would windows clock stop?

### Additional information

clicking back into game stops clock again.

**Comment by covers1624** [comment]
This is nothing the FTBApp does intentionally, and it definitely sounds like a Windows issue. Some quick googling shows that this is a known issue and happens with other software running.
