### ISSUE TITLE
Error stoneblock 3 (1.5.0)

### ISSUE THREAD

**Issue by dragonnss** [FTBTeam/FTB-App#817]
### What Operating System

Windows 11

### Debug Code

FTB-DBGBEPIQUWISA

### Describe the bug

Good evening, following the new update of the FTB StoneBlock 3 (1.5.0) I can no longer start the mod. I attach the error log files. I want to clarify that if I use the previous version it doesn't give me any problems, but having an aternos server with my friends I can't enter with a previous version. Waiting for an answer, I wish you happy holidays.

### Steps to reproduce

1. start new game or old save with version 1.5.0

[hs_err_pid9416.log](https://github.com/FTBTeam/FTB-App/files/10300215/hs_err_pid9416.log)

### Expected behaviour

that the mod works.

### Screenshots

![error 2](https://user-images.githubusercontent.com/121351219/209473605-13d7b0d4-3815-42b2-883b-3bead015e301.jpg)

other times it tells me this unlike the above error in the logs

**Comment by covers1624** [comment]
This is an Issue tracker for FTBApp issues only. For further assistance, please see the issue tracker for Modpack issues: https://github.com/FTBTeam/FTB-Modpack-Issues/issues

**Comment by Talidorn** [comment]
If you are running on AMD...

Open configs -> flywheel-client.toml

change:

backend = "INSTANCING"
to
backend = "OFF"
