### ISSUE TITLE
adding mods to modpacks not working.

### ISSUE THREAD

**Issue by CoryNB** [FTBTeam/FTB-App#818]
### What Operating System

Windows 11

### Debug Code

unable to get debug

### Describe the bug

finding mods not working

### Steps to reproduce

any modpack, search for xray or even optifine. some fps fixers/adjusters for in game stablility/stablizers.

### Expected behaviour

to find those mods popping up to be installed.

### Additional information

this has been happening for a while now.

**Comment by covers1624** [comment]
Closing in favor of https://github.com/FTBTeam/FTB-App/issues/819

**Comment by CoryNB** [comment]
I'd like to ask, how come stoneblock 3 has not been ported over yet?
