### ISSUE TITLE
high ms request time for finding mods

### ISSUE THREAD

**Issue by CoryNB** [FTBTeam/FTB-App#819]
### What Operating System

Windows 11

### Debug Code

data for ms for request inconsisency 

### Describe the bug

the long periods to find mods.

### Steps to reproduce

any modpack profile, under mods, add more mods.
issue is related to stoneblock profile and also optifine mod. 
search for opti, xr, ex, or even chest.
the excessive ms is greater than 10,000 ms. for loaded in and total loaded. should be lower than 1,000 ms. 

### Expected behaviour

for mods to quickly pop up after searching for it, but don't appear for certian words for 1.18 modpacks.

**Comment by covers1624** [comment]
We are unable to assist without a debug code.

Also, please do not go around our issue tracker posting off-topic comments, etc.

**Comment by CoryNB** [comment]
debug code didn't trigger. I'm afraid when i tried it it failed.

**Comment by MichaelHillcox** [comment]
Closing due to missing debug code. Please open a new issue if this is still an issue
