### ISSUE TITLE
Cannot launch FTB Revelation with the new launcher

### ISSUE THREAD

**Issue by retke** [FTBTeam/FTB-App#82]
Hello there, first of all, thank you for that amazing launcher, it already looks really good, and I'm willing to help you!

Now, I just ran into a weird issue, I installed FTB Revelation with the launcher fine, launched it, which redirected me to the Minecraft launcher with an "FTB Revelation" profile as expected, but when I launch it, the game instantly crashes (the window doesn't even appear) and I'm shown this :
![image](https://user-images.githubusercontent.com/23153234/79017143-e8c50100-7b70-11ea-8bfe-df0463233954.png)

The error is really weird, never seen it before :
```
Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
```

Full log (it's pretty short) : [latest.log](https://github.com/FTBTeam/FTB-App/files/4463045/latest.log)

Edit : I can launch FTB Revelation fine on the legacy launcher.

**Comment by Cloudhunter** [comment]
Can you try deleting the instance and creating it again?

**Comment by retke** [comment]
Reinstalling the modpack didn't work. However, uninstalling the launcher, removing FTBA and ftb-app in AppData/Roaming, then reinstalling everything fixed it! Thank you
