### ISSUE TITLE
FTB Stoneblock 3 (1.5.0) Crashing On World Load

### ISSUE THREAD

**Issue by vburnin8tor** [FTBTeam/FTB-App#820]
### What Operating System

Windows 11

### Debug Code

FTB-DBGQUQUVAVINA

### Describe the bug

Loading my world in 1.5.0 does not work

### Steps to reproduce

1. Load World in 1.5.0

### Expected behaviour

The world to load

### Additional information

Log attached
[hs_err_pid10936.log](https://github.com/FTBTeam/FTB-App/files/10304412/hs_err_pid10936.log)

**Comment by covers1624** [comment]
This is an Issue tracker for FTBApp issues only. For further assistance, please see the issue tracker for Modpack issues: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
