### ISSUE TITLE
(Version 1.5.1) Waiting for response... auth issue, profile button disappeared, instances never showing, app crashes, cant download anything

### ISSUE THREAD

**Issue by GalacticTurtle01** [FTBTeam/FTB-App#822]
### What Operating System

Windows Insider Preview

### Debug Code

FTB-DBGYITOGAZIRO

### Describe the bug

I cant log in with microsoft on ftb because it gets stuck on waiting for response or on the rare occasion it puts an error. The profile button on the sidebar is missing but still clickable (the one that shows a pop up of your account and mine together), my instances never appear no matter how long I wait while the ftb debug app still recognizes my instances, and the app occasionally crashes around 5 minutes of opening it.

### Steps to reproduce

1. Open FTB App
2. Go to instances to play a modpack (instances don't appear)
3. Redownload the instances and other instances that I want to try playing later. (I cant even download anything its stuck at 0 percent even if I don't have the instance prior)
4. Checked to make sure my files are in place and do multiple reinstalls deleting the ftb app data folder several times. (I made a backup of it on my desktop)
5. Opened the FTB App multiple times and while looking around I see a pop up saying accounts (the button was invisible so I accidentally found it while dragging my mouse around.)
6. Noticed I'm not signed into FTB App so I go through the login process until it tells me to go back to FTB App because I'm now signed in.
7. After I go back to the FTB App it just shows Waiting for response... with a continual spinning circle.
8. I keep repeating this trying to flush my dns, redownload several more times, use a vpn, using different browsers, and incognito.
9. On the rare occasions it doesn't show Waiting for response... it shows the error screen where it says I'm under 18, don't own Minecraft, or I need to relog into the official launcher if I use the game pass. 

### Expected behaviour

I expected to be able to play my modpacks which disappeared on the app while I still have them in the folder. The profile button shouldn't be invisible and should be a question mark that shows when you are not signed in. I should be able to download instances I believe but I can not. Also throughout all the steps my app has been crashing occasionally after 5 minutes or less of running. 

### Screenshots

![image](https://user-images.githubusercontent.com/72573516/210158868-7d614ed2-a2ed-4dff-9a54-1c60dac45544.png)

![image](https://user-images.githubusercontent.com/72573516/210158888-ad9c96a1-3e55-4c59-80dd-39eb080afa63.png)

![image](https://user-images.githubusercontent.com/72573516/210158892-316203bd-ab65-4228-9739-5339ea0c5334.png)

### Additional information

Windows 11 Insider Preview (Installed build: 22623.1037 ni release) 

1st screenshot shows my instances not appearing in app and the profile button disappeared but still technically working.
2nd screenshot shows the log in process succeeding and telling me to go back to my FTB App
3rd screenshot is after the 2nd screenshot where it says Waiting for response... until I close out of it or the app crashes which is common for me.

Occasionally for 1 second after the you're in screen appears the app shows a different screen logging me in then changes it back to Waiting for response... extremely quickly after.

**Comment by GalacticTurtle01** [comment]
I've also seen a similar issue with the Waiting for response... but it was closed as fixed when in reality at least for me it wasnt.

**Comment by deathofattack** [comment]
i have the same problem but it doesn't even give me an error

**Comment by GalacticTurtle01** [comment]
Just wanted to leave a comment that this still happens to make sure its active

**Comment by GalacticTurtle01** [comment]
accidentally closed

**Comment by MichaelHillcox** [comment]
Should be fixed in the latest version, let me know if it's still an issue
