### ISSUE TITLE
StoneBlock 3 1.5.0 has crashed

### ISSUE THREAD

**Issue by EironHawk** [FTBTeam/FTB-App#823]
### What Operating System

Windows 10

### Debug Code

FTB-DBGBUPEQUFIFO

### Describe the bug

I was trying to use the FTB Ultimine and it crashed.

### Steps to reproduce

[crash-2023-01-01_14.34.12-client.txt](https://github.com/FTBTeam/FTB-App/files/10329425/crash-2023-01-01_14.34.12-client.txt)

### Expected behaviour

That it select the area and mine the selected area.

**Comment by manmaed** [comment]
This is not an app issue please report it to FTBTeam/FTB-Modpack-Issues/issues
