### ISSUE TITLE
Error with getting Profile data

### ISSUE THREAD

**Issue by SneakyDuck414** [FTBTeam/FTB-App#824]
### What Operating System

Windows 10

### Debug Code

FTB-DBGOYOVUBOFIJ

### Describe the bug

cant play online and says unable to gather profile data

### Steps to reproduce

1. open launcher
2. start mod pack
(i dont think this can be remade by the looks of it might be a server issue)

### Expected behaviour

launching a mod pack and play on my server 

### Screenshots

![Screenshot 2023-01-03 113026](https://user-images.githubusercontent.com/121887454/210400747-66e24dc0-e817-4ba4-98d2-ccf501f938ae.png)
![Screenshot 2023-01-03 113107](https://user-images.githubusercontent.com/121887454/210400785-ad89df22-ddc3-4922-b232-79efcfd9a615.png)
![Screenshot 2023-01-03 113133](https://user-images.githubusercontent.com/121887454/210400796-fc547fed-ddb2-44ba-ac12-b3cad0d61db6.png)

### Additional information

In the screenshot of something went wrong i tried to re add my account.

**Comment by SneakyDuck414** [comment]
also by the looks of it there are others having the same issue

**Comment by Calou42** [comment]
I have the same problem ... Any solution ???

**Comment by MichaelHillcox** [comment]
Should be sorted in the latest release, let us know if it's not
