### ISSUE TITLE
Stoneblock 2 version 1.22.0 can't be started without Clean Install

### ISSUE THREAD

**Issue by Items3Sacred** [FTBTeam/FTB-App#825]
### What Operating System

Windows 11

### Debug Code

FTB-DBGMIGAYOWOBE

### Describe the bug

Everytime I want to Play Stoneblock 2 1.22.0 I have to do a clean Install of the Modpack before Pressing Play otherwise it won't Work.

### Steps to reproduce

1. Go to Stoneblock 2
2. Select version 1.22.0
3. Press Play
4. Wait till Minecraft is Fully Loaded (screen with Survival, Multiplayer etc.)
5. Quit the Game
6. Try Playing again

### Expected behaviour

It will start to Load, but will Crash before Minecraft Opens

### Additional information

https://paste.feed-the-beast.com/view/9a017deb

**Comment by MichaelHillcox** [comment]
Not an app issue
