### ISSUE TITLE
Cant run optifine on stoneblock 3 can anyone help me

### ISSUE THREAD

**Issue by LamTuanPhi111** [FTBTeam/FTB-App#826]
### What Operating System

Windows 10

### Debug Code

FTB-StoneBlock 3

### Describe the bug
Cant run optifine on stoneblock 3 can anyone help me
### Steps to reproduce

123124123

### Expected behaviour

1231213

### Screenshots

123123

### Additional information

123123

**Comment by manmaed** [comment]
This is Not an App Issue, please report to https://github.com/FTBTeam/FTB-Modpack-Issues
