### ISSUE TITLE
Allow changing forge version

### ISSUE THREAD

**Issue by macks2008** [FTBTeam/FTB-App#828]
### What is your suggestion?

(going to put this into a clean "user story" format)
**As a server administrator** hosting for friends...
**I would like** to be able, after downloading a modpack, to change the version of forge it is using EASILY...
**so that** I can make updates to the pack I am hosting without having to explain, to my less tech savvy friends, manually installing new MCforge versions

### Alternatives ideas

update your packs more frequently, even if it's just a few bug fixes, so the newer forge versions can be downloaded on the app in that (roundabout) way

### Additional information

Edit: Someone on the Direwolf20 discord mentioned the risk of changing forge versions breaking a curated pack. While that's certainly worth considering, not all of your packs are using things like quests etc., and Forge, to my knowledge, only makes major breaking changes between Minecraft versions. In any case, I accept this risk, and if doesn't load due to dependencies (à la dependency hell), I'll hopefully realize that when I test-load the client and revert the change rather than applying it to my server (but I keep lots of server world backups anyway).
I also want to mention that if this isn't implemented at some point, my friends and I might go back to packs I can find on Curseforge as those are easier for me to adjust to my liking. Curseforge has a Modloader version switcher built-in. I love your packs, but I need more flexibility

**Comment by macks2008** [comment]
why did I just get an email (apparently from some Github Actions bot) about a debug code? There was nothing about debug codes in the Feature Request form.

**Comment by macks2008** [comment]
I also accept the risk that this may break the more carefully-woven packs, but I think it would be useful for packs that don't have quests or any special advancements to worry about. If something doesn't load due to dependencies (à la dependency hell), I'll realize that when I test-load the client and revert the change rather than applying it to my server.
(I also want to mention that if this isn't implemented at some point, my friends and I might go back to packs I can find on Curseforge as those are easier for me to adjust to my liking. Curseforge has a Modloader version switcher built-in. I love your packs, but I need more flexibility)

**Comment by MichaelHillcox** [comment]
This will likely be implemented at some point but requires some upfront usability improvements on instances as a whole so I've backlogged the issue for a future update.

Thanks for the detailed request
