### ISSUE TITLE
Plexiglass mountain incents not instaling 

### ISSUE THREAD

**Issue by elz2kewl** [FTBTeam/FTB-App#829]
### What Operating System

Windows 11

### Debug Code

ftb-debug-arm64.exe 

### Describe the bug

whenever i try to install 1.2.4 it says fatal exception well Loding modpack installation 

### Steps to reproduce

 go to Plexiglas Mountain
click install 
see if you get an error 

### Expected behaviour

i updated the mod pack to 1.2.4

### Screenshots

![FTB App 1_8_2023 6_14_52 PM](https://user-images.githubusercontent.com/122243216/211231622-5b3ec9fd-0e58-47fe-a362-371adb89beee.png)

**Comment by MichaelHillcox** [comment]
Closing as no debug code supplied
