### ISSUE TITLE
Direwolf20 1.19 update pack update from 1.0.4 to 1.1.0 (released today)

### ISSUE THREAD

**Issue by dalgrim** [FTBTeam/FTB-App#830]
### What Operating System

Windows 10

### Debug Code

FTB-DBGIDEKADAQAB

### Describe the bug

Pack will not update. Error: Fatal exception whilst preparing modpack installation

### Steps to reproduce

1. Open FTB app.
2. click "Library" 
3. select Direwolf20 1.19 Update Available version 1.0.4
4. click the orange Update button.
5. Click Confirm

### Expected behaviour

Would expect the pack to update

### Screenshots

![image](https://user-images.githubusercontent.com/12730893/211337593-1b7b4afb-4f14-4f89-a13f-66ea9e4d1408.png)

**Comment by richhuff** [comment]
I am having the same problem updating to 1.1.0
My system specifics are attached
I do have my FTB instances on my D: drive instead of the default C: location
![Capture](https://user-images.githubusercontent.com/24701215/211348227-d53bc30e-5f0c-4d02-992a-9989fd75ebd8.PNG)

**Comment by MAJ-Stubble** [comment]
Same here but i managed to get it to download and now it just crashes on loading world screen as soon as it reaches 100%.

**Comment by MichaelHillcox** [comment]
Root issue seems to be fixed, let me know if it's still causing issues
