### ISSUE TITLE
Direwolf 1.1.0 update Server connection failure

### ISSUE THREAD

**Issue by Berylcross** [FTBTeam/FTB-App#831]
### What Operating System

Windows 10

### Debug Code

FTB-DBGLESITATANA

### Describe the bug

cannot connect to server world after update

### Steps to reproduce

Update direwolf from 1.0.4 to 1.1.0 beta.
Attempt to connect to friend's minecraft server that I played on from 1.0.4 beta.
minecraft attempts to load game and crashes to desktop upon loading into the world, or right after loading terrain shows up on the screen and hangs for a few minutes.
repeated uninstall and reinstall does not fix the issue.
Even updated java.
Other friends are able to access server with no issue.

### Expected behaviour

Expected to connect to friend's server.

**Comment by MAJ-Stubble** [comment]
I have the same issue, crashes just as loading world. I'm on my own server, so not a server issue.

**Comment by master-sushi** [comment]
I have the same issue, crashes as loading world. Single player instance.

**Comment by Berylcross** [comment]
A friend managed to find out the fix from another help source apparently.  In the configs directory there is a flywheel-client.toml

Under it there is a backend= "Instanced" that you want to change to Backend= "OFF"

That fixed the server issue I was having.

**Comment by master-sushi** [comment]
Thanks for the possible solution, but changing this file doesn't solve my problem.

**Comment by MichaelHillcox** [comment]
Not an app issue
