### ISSUE TITLE
FTB Launcher Consistently Uses Data - Causing cap of ISP Limits

### ISSUE THREAD

**Issue by bschultz0** [FTBTeam/FTB-App#833]
### What Operating System

Linux (Debian)

### Debug Code

doesnt work

### Describe the bug

FTB Launcher Consistently Uses Data - Caps ISP Limit

### Steps to reproduce

This month my ISP (which has a 1.2TB monthly limit) reported I am using a ton of data.  I turned on traffic monitor on my router and installed PortMaster to troubleshoot.  I found that the FTB Launcher consistently uses between .5MB/s to 5MB/s when open in a very consistent pattern. (see screenshot)  At an average of only 1MB/s that comes to 86GB a day in usage just for leaving the app open in the background.  I don't know if it is RE-downloading the little stupid video in the bottom corner or what but it is unacceptable to consistently use data to get the same data over and over multiple times a minute and use people's data for no reason.  This needs fixed asap.  Unfortunately, the Launcher needs to be open when I am playing and that means it is constantly wasting my data in the background.  

### Expected behaviour

Download the data needed once and not every minute over and over

### Screenshots

![ftb-app-traffic](https://user-images.githubusercontent.com/25989223/211883904-c9d52d94-f2fa-424f-9a4c-731671ff242a.png)

### Additional information

I verified the traffic instantly stops when closing the FTB Launcher and instantly returns with the exact same pattern the second the launcher is opened once again.  This past month I have been playing a lot of FTB Revelation and either leaving the game loaded and running to prevent waiting for another 5 minute load time or leaving the launcher open after closing the game.  I had 'assumed' the little video that repeatedly plays was downloaded a single time and not EVERY time.  I don't know for sure if that is the cause of the data usage, but SOMETHING in the launcher is repeatedly using the same data over and over and wasting data usage for users.

**Comment by MichaelHillcox** [comment]
Caused by some quirk on the web side causing the video not to cache. Should be a relative simple fix to implement.
