### ISSUE TITLE
FTB app strange text font

### ISSUE THREAD

**Issue by KurooNekomata** [FTBTeam/FTB-App#836]
### What Operating System

Windows 10

### Debug Code

FTB-DBGASIRIDUPEJ

### Describe the bug

today I opened the app and it was with this strange text font that it hasn't had before, already tried uninstalling and installing again but did not work, even deleted the files but no luck

### Steps to reproduce

just launched the app

### Expected behaviour

the normal and readable app font

### Screenshots

![image](https://user-images.githubusercontent.com/78846831/212529241-6dd4094a-313c-4850-af49-ce8bdb524c1b.png)

**Comment by MichaelHillcox** [comment]
Does updating the app fix this?
