### ISSUE TITLE
unknown XSTS error

### ISSUE THREAD

**Issue by markolol21** [FTBTeam/FTB-App#837]
### What Operating System

Windows 10

### Debug Code

FTB-DBGOWEFEKADAG

### Describe the bug

on FTB app trying log in with microsoft account. On browser say's everthing is ok but on FTB app shows Unknown XSTS error

### Steps to reproduce

not sure if u can but 
1. open the ftb app
2. try to log in
3. log into microsoft account
and then on ftb app got the error

### Expected behaviour

on FTB app trying log in with microsoft account. On browser say's everthing is ok but on FTB app shows Unknown XSTS error

### Screenshots

![error](https://user-images.githubusercontent.com/122737990/212550160-ad1b44c3-da4f-4d55-bded-aa8c2d3e5065.PNG)

**Comment by MichaelHillcox** [comment]
It's saying that your account has an Enforcement ban? Likely an issue with account ages? Let me know if this is still an issue
