### ISSUE TITLE
Not authorized to download server files

### ISSUE THREAD

**Issue by EPostill** [FTBTeam/FTB-App#84]
I was told to put this here instead of in Omnia where I originally found the issue
Servers for all other modpacks work fine for me, only issue is with omnia

* **Modpack Version**: FTB Omnia 1.1.0

* **Issue**: after clicking on a server type to download, a webpage opens with an Authorization failed error
This is the webpage I am directed to: https://api.modpacks.ch/public/modpack/undefined/46/server/windows
this one is for windows but all versions give the same error

* **Is it Repeatable?**: yes

**Comment by Cloudhunter** [comment]
Fixed in the next build
