### ISSUE TITLE
Stoneblock 3 ,failed to validate assets

### ISSUE THREAD

**Issue by helixbtw** [FTBTeam/FTB-App#840]
### What Operating System

Windows 11

### Debug Code

FTB-DBGOYIMOXATAM

### Describe the bug

Stoneblock 3, failed to validate assets

### Steps to reproduce

1. Launch Stobnelock 3 (v1.5.0)
2. Launcher starts
3. Error after few seconds like on screen below 

### Expected behaviour

successfully launch Stoneblock 3

### Screenshots

![image](https://user-images.githubusercontent.com/48182352/214651090-ead1976e-0ac4-431f-abc0-0a315bcc6ac5.png)

### Additional information

none

**Comment by MichaelHillcox** [comment]
https://appsdl-overwolf-com.akamaized.net/prod/apps/cmogmmciplgmocnhikmphehmeecmpaggknkjlbag/1.23.622.1340/app.opk

Please try with this version of the app. Make sure your current version of the app is closed. Let me know if you have any more issues.
