### ISSUE TITLE
Instances launched through the FTB app keeps crashing when going from windowed to fullscreen

### ISSUE THREAD

**Issue by PianoHallvard** [FTBTeam/FTB-App#841]
### What Operating System

Windows 10

### Debug Code

FTB-DBGGULUFEZULI

### Describe the bug

Game crashed on F11 (fullscreen button)

### Steps to reproduce

1. Get the FTB app
2. download any pack
3. launch the pack
4. go from windowed to fullscreen a handful of times
5. crash the game

App version: 1.22.1215.2008 (it was latest 2 days ago)

Increasing the ram usage did nothing, so I'm kinda lost here
Cheers

### Expected behaviour

let me go fullscreen without crashing

**Comment by PianoHallvard** [comment]
I think Discord somehow messes with the game instances. Closed Discord down and now it's not misbehaving.

**Comment by PianoHallvard** [comment]
nope, that didn't fix it

**Comment by PianoHallvard** [comment]
NOT AN FTB APP ISSUE LIKE I THOUGHT

It was a GPU thing, all fixed now

**Comment by CoryNB** [comment]
gpu is used for the graphics of the app, wow. remeber to properly set your settings
