### ISSUE TITLE
Stoneblock 3 1.5.0 Crashing

### ISSUE THREAD

**Issue by Kill3rTravo** [FTBTeam/FTB-App#842]
### What Operating System

Windows 11

### Debug Code

FTB-DBGFOKURIMURU

### Describe the bug

Game crashes when opening the game. I think I've isolated the problem down to when I open my inventory. I can open the game, run around and interact with the world, but the game instance crashes after opening my inventory.

### Steps to reproduce

1. Open the game
2. Open inventory
3. Crash

### Expected behaviour

I expected to open my inventory without crashing

### Screenshots

![Screenshot 2023-01-25 183105](https://user-images.githubusercontent.com/123606077/214726280-09f04f2a-6d33-4d4a-bd48-186c3248b0ad.png)

**Comment by manmaed** [comment]
This is Not an App Issue, please report to https://github.com/FTBTeam/FTB-Modpack-Issues
