### ISSUE TITLE
porting over new modpacks to curseforge

### ISSUE THREAD

**Issue by CoryNB** [FTBTeam/FTB-App#844]
### What is your suggestion?

I recently noticed that ftb modpackas fail to get ported or or even pushed to install into curseforge, which use overwolf as well.
mods not found currently in curseforge are ftb stoneblock 3, dierwolf20 1.18, dierwolf20 1.19, ftb legends of the eyes, ftb inferno, ftb plexiglass mountian, and ftb one.

### Additional information

I recently noticed no version appearing from curseforge from ftb. could someone explain why.

**Comment by CoryNB** [comment]
this isssue has been going on since 1.18 was released.

**Comment by manmaed** [comment]
Hello FTB no longer publishes modpacks on the curseforge website. To get the packs please use our app @ https://go.ftb.team/app
