### ISSUE TITLE
Fatal exception whilest installing modpack

### ISSUE THREAD

**Issue by iiMostafaX** [FTBTeam/FTB-App#845]
### What Operating System

Windows 10

### Debug Code

FTB-DBGBEYABEFISE

### Describe the bug

Failure downloading Stoneblock 3

### Steps to reproduce

1. Start up FTB APP
2. Click on discover / browse
3. Select Stoneblock 3 1.5.0
4. Select download / get.
5. Installation will fail.

### Expected behaviour

Successful installation of the modpack

### Screenshots

![image](https://user-images.githubusercontent.com/63116485/215266139-045f8b68-85ba-414d-b82e-f6993ef3a83d.png)

### Additional information

I had the modpack before on 1.4.0 and I get this issue on updating it and the issue continues after reinstalling ftb app.
EDIT: It happens to any modpack

**Comment by Gavote** [comment]
Same problem updating from 1.5.0 to 1.6.1 on Stoneblock 3.
Further investigation shows that I cannot update or install ANY instances.

**Comment by pepe515** [comment]
me too from 1.5.0 to 1.6.1

**Comment by MichaelHillcox** [comment]
Looks like the forge installer crashed... Should be fixed by now, give it another go and let me know if you have any more issues
