### ISSUE TITLE
stoneblook3 dont work

### ISSUE THREAD

**Issue by angryfish64** [FTBTeam/FTB-App#847]
### What Operating System

Windows 11

### Debug Code

ftb

### Describe the bug

cant open world on stoneblook3

### Steps to reproduce

1. go to ftb app
2. open stoneblook
3. open world
4. loading
5. game closed

### Expected behaviour

open the world

**Comment by manmaed** [comment]
This is Not an App Issue, please report to https://github.com/FTBTeam/FTB-Modpack-Issues
