### ISSUE TITLE
Experience Obelisk - Unregistered Fluid

### ISSUE THREAD

**Issue by moneyblind** [FTBTeam/FTB-App#848]
### What Operating System

Windows 10

### Debug Code

No Code Provided

### Describe the bug

Unable to pump fluid in and out of the obelisk

### Steps to reproduce

Place obelisk, deposit exp
Place Tank
Put @pipez fluid pipe between blocks.

Moving Exp out of the obelisk results in the tank being filled with "fluid_type.unregistered_sadface" fluid in the tank.

Moving liquid experience (cyclic) to the obelisk does not work.

I believe that the storage type of the obelisk is not ore-dictionary to a exp fluid.

### Expected behaviour

Ore dictionary to Experience liquids

**Comment by manmaed** [comment]
This is Not an App Issue, please report to https://github.com/FTBTeam/FTB-Modpack-Issues
