### ISSUE TITLE
Backend error, restarted pc and reinstalled launcher but no luck.

### ISSUE THREAD

**Issue by Binxx2222** [FTBTeam/FTB-App#85]
![image](https://user-images.githubusercontent.com/63514553/79051341-92ff6000-7c27-11ea-9d3a-0a58d1840ea7.png)

**Comment by Binxx2222** [comment]
When trying to load from the file directly instead of the pinned icon i get this error 
![image](https://user-images.githubusercontent.com/63514553/79051469-5849f780-7c28-11ea-92fc-18711544ade5.png)

**Comment by Cloudhunter** [comment]
Please provide logs - also in the .installer folder

**Comment by Nexadon** [comment]
The same thing happens to me every time I try to run it as well.  "Issues connecting to backend... Please wait or relaunch."

**Comment by Binxx2222** [comment]
I fixed it by uninstalling and reinstalling the launcher and mod packs. I
haven’t closed the app since reinstalling so don’t actually know if it’s
fixed.

**Comment by Cloudhunter** [comment]
Is this still an issue on the latest build? Pinned icons should now work as expected.

**Comment by Joshua1526** [comment]
if you wait a while it just wipes the whole launcher and deletes your progress its happened 3 times to me

**Comment by Binxx2222** [comment]
> 
> 
> Is this still an issue on the latest build? Pinned icons should now work as expected.

Appologies for not replying, we moved to a different mod pack and launcher but it WAS fixed after the update. Thanks

**Comment by Nexadon** [comment]
Yes, it has also been fixed for me as well.  Thanks!
