### ISSUE TITLE
FTB App - Sharing & Uploading instance provides an unusable share code

### ISSUE THREAD

**Issue by hunter527** [FTBTeam/FTB-App#851]
### What Operating System

Windows 10

### Debug Code

FTB-DBGPEQOQIDOKU

### Describe the bug

Through the FTB App, sharing your instance uploads it and provides a share code to easily import later. After uploading my instance (takes 15-30min) i receive a share code. Upon using it, it does not work. I have tried this same procedure 3-4 times in two days with same issue

### Steps to reproduce

1. Goto FTB App
2. Navigate to Library and choose the instance you want to upload
3. I verified my instance folder is only 350MB in size
4. After selecting the instance, click the '...' for additional options and click 'Share Instance'
5. The instance takes 15-30min to upload and provides you an unusable share code (in my case)

### Expected behaviour

An unusable share code is given that cannot be imported, as no share instance was found with that code

**Comment by MichaelHillcox** [comment]
Screenshot?

**Comment by HugKitten** [comment]
Go to mod packs and there should be an import option
