### ISSUE TITLE
Direwolf20 1.19 pack Instance crash.

### ISSUE THREAD

**Issue by Thanoskoll** [FTBTeam/FTB-App#852]
### What Operating System

Windows 11

### Debug Code

FTB-DBGFEMEQIVETI

### Describe the bug

I downloaded the pack and when i tried to launch it an error message popped up. I tried uninstalling it and installing it again but this didnt work either. 

### Steps to reproduce

1.Download the Direwolf20 1.19 pack (On any version)
2.Click play 
3. Wait for it to initialize 
4. Then the error message pops up

### Expected behaviour

Open the pack

### Screenshots

![20230208_190504](https://user-images.githubusercontent.com/124813998/217618235-0494ec4d-011f-4527-b223-d51dd763224a.jpg)

**Comment by MichaelHillcox** [comment]
https://appsdl-overwolf-com.akamaized.net/prod/apps/cmogmmciplgmocnhikmphehmeecmpaggknkjlbag/1.23.622.1340/app.opk

Please try with this version of the app. Make sure your current version of the app is closed. Let me know if you have any more issues.
