### ISSUE TITLE
Cant start any packs

### ISSUE THREAD

**Issue by Michalexb** [FTBTeam/FTB-App#853]
### What Operating System

Windows 11

### Debug Code

java.io.IOException

### Describe the bug

Modpacks dont even launch, the  first thing to pop up is the java.io.IO.Exception: Failed to execute asset update task

### Steps to reproduce

1. Open Launcher
2. Download  any pack
3. Open the Pack
4. Error

### Expected behaviour

I expected the game to start lol

**Comment by konnextv** [comment]
This workaround worked for me: [https://www.reddit.com/r/feedthebeast/comments/10qx5vn/comment/j7kimpb/](https://www.reddit.com/r/feedthebeast/comments/10qx5vn/comment/j7kimpb/)

**Comment by MichaelHillcox** [comment]
Closed due to no debug code
