### ISSUE TITLE
Failed To Prepare Instance

### ISSUE THREAD

**Issue by ColeStolt12** [FTBTeam/FTB-App#854]
### What Operating System

Windows 11

### Debug Code

FTB-DBGUVUVUKUYUT

### Describe the bug

When I try to launch the Stoneblock 3 Mod pack. During the validating assets section its abruptly stops says that it has failed to prepare the instance

### Steps to reproduce

1. Open FTB App
2. Click play on Stoneblock 3
3. Then its does it.

### Expected behaviour

I wanted to be able to play the game

### Screenshots

![FTB App 2_9_2023 3_02_40 AM](https://user-images.githubusercontent.com/124873644/217765907-9430c887-881f-4f86-aec5-4f0e5f627abe.png)

**Comment by Rjames13** [comment]
I get a similar error

**Comment by MichaelHillcox** [comment]
Should be fixed with the latest version of the app. Go here https://appsdl-overwolf-com.akamaized.net/prod/apps/cmogmmciplgmocnhikmphehmeecmpaggknkjlbag/1.23.622.1340/app.opk

Run the file after you have close the FTB App
