### ISSUE TITLE
Modpack no longer showing

### ISSUE THREAD

**Issue by thegoldenA** [FTBTeam/FTB-App#859]
### What Operating System

Windows 11

### Debug Code

FTB- Unknown

### Describe the bug

I went to go play on Direwolf20 version 1.1.1 which is in beta. I have a server with a few friends and when the launcher loaded it was saying how i no longer have the modpack installed or anything. Its saying how i need to reinstall it for 0 reason because i had it installed before. I've had the modpack for nearly a week at this point and never had this issue before. I've also used the launcher before as well and never encountered this issue.

### Steps to reproduce

1. Launch FTB
2. modpack went poof from my library

### Expected behaviour

I expected my modpack to show in my library instead of me having to redownload it.

### Additional information

Before anyone says i messed with the folder for it or anything. I didnt at all. the folder for the modpack is still showing up within the instances of FTB but isnt showing up within the launcher itself. I already logged out and back in and restarted my pc as well to fix this issue and the modpack still isnt showing. The debug code isnt showing for me as well so i have no idea what it is.

**Comment by Th3C0D3R** [comment]
same for me, everything is removed from the app, cant see my profil image, cant set my resolution or threads to download. and installing does not work
Win11 Insider Build

**Comment by SlipperySlipper25** [comment]
I was playing Stoneblock 3 most of yesterday and into the morning today, i slept for a few hours and when i woke up around 10am:EST and launched the FTB App, it showed that i had no modpacks in my library

**Comment by Crook3r** [comment]
Same here, looks like global problem after update? With installed modpacks, same is with settings, ale my settings fields are empty (even resolution).

**Comment by SlipperySlipper25** [comment]
Turns out someone on the discord posted a link that will install the older previous version of the FTB App and it fixes this issue

**Comment by lolpop9009** [comment]
I have this issue, but i just exit the app and restart it, and if that doesn't work i just restart my pc.

**Comment by MichaelHillcox** [comment]
Closing due no debug code but we can help more in the discord if you're still having this issue.
