### ISSUE TITLE
Failure to launch any packs (failed to execute asset update task)

### ISSUE THREAD

**Issue by CrumbGuzzler** [FTBTeam/FTB-App#860]
### What Operating System

Windows 11

### Debug Code

FTB-DBGQILAFIVUMA

### Describe the bug

Have tested with Direwolf20 1.19 (multiple builds, beta and release), FTB One 1.3.0, and Vanilla 1.19.2. Any pack launched will fail in the validate asset stage (see screenshot)

### Steps to reproduce

1. Go to any modpack (issue discovered with Direwolf20 1.19 beta 1.2.1)
2. "Play"

### Expected behaviour

While validating assets, the file size being validated appears to pass the limit (for example, will 'verify' up to 100mb out of 30mb, and will fail in this stage even on clean installations.

### Screenshots

![PXL_20230214_011333649](https://user-images.githubusercontent.com/125326726/218614639-6271e22c-5c02-4534-b5bb-c0960eeff2ff.jpg)

![PXL_20230214_011321525](https://user-images.githubusercontent.com/125326726/218614658-df0cf893-12dc-4128-b3e1-bdae32e783bc.jpg)

### Additional information

I have encountered this issue on two different PCs, one running Win10 and the other running Win11.

**Comment by MichaelHillcox** [comment]
https://appsdl-overwolf-com.akamaized.net/prod/apps/cmogmmciplgmocnhikmphehmeecmpaggknkjlbag/1.23.622.1340/app.opk

Please try this app version, let me know if it doesn't work
