### ISSUE TITLE
I cant install any modpack

### ISSUE THREAD

**Issue by JailowyPL** [FTBTeam/FTB-App#863]
### What Operating System

Windows 11

### Debug Code

I cant. Picture with bug bellow.

### Describe the bug

I cant install modpack, because i have error

### Steps to reproduce

1. Just try to install modpack
2. 
![image](https://user-images.githubusercontent.com/44643762/219949425-6b71f926-80d8-4531-baa8-43ce6c35dc1f.png)

I cant put log here look -> 
![image](https://user-images.githubusercontent.com/44643762/219949709-e5ceb56a-78c7-4a61-990a-045d2422f27d.png)

### Expected behaviour

just install modpack

### Screenshots

![image](https://user-images.githubusercontent.com/44643762/219949448-b1e4724c-cfc3-4007-a3cc-fcf555f205bc.png)

**Comment by MichaelHillcox** [comment]
Can you try the debugger again but it looks like your network is blocking the traffic.
