### ISSUE TITLE
Can't launch any ftb mods

### ISSUE THREAD

**Issue by Alean90** [FTBTeam/FTB-App#867]
### What Operating System

Windows 10

### Debug Code

FTB - Can't launch any modpacks

### Describe the bug

Can't launch any FTB modpack

### Steps to reproduce

I have tried reinstalling, allowing minidumps and updating the grapics driver and Java, nothing has worked so far.

![Crashlog](https://user-images.githubusercontent.com/126393120/221409647-9e9ce60f-7ab7-44d1-b08b-c905ff18a44c.png)

### Expected behaviour

I would like to be able to launch the game

### Screenshots

![Crashlog](https://user-images.githubusercontent.com/126393120/221409758-ec801d27-0e92-4cf6-9225-6a17f0bd9878.png)

**Comment by CoryNB** [comment]
mhz issue has been the main problem, change it to be reduced by 1 to 100 mhz by what is your maximum mhz your ram can do.

**Comment by MichaelHillcox** [comment]
Likely needs more ram but not an app issue so closing
