### ISSUE TITLE
it wont get past "setting up" and when i try to use the debug code it just shows the code

### ISSUE THREAD

**Issue by corrupt7581** [FTBTeam/FTB-App#869]
### What Operating System

MacOS (Latest)

### Debug Code

________________________

### Describe the bug

it wont get past "setting up" and sometimes it doesnt even open the window but it says its open

### Steps to reproduce

1. press open
2. wait until window shows or if it never shows restart your entire computer
3. you have entered where im stuck

1. download debug code
2. if doesnt allow you to open it just right click on it 
3. press open
4. press open in the menu
5. it opens the code not runs the code

### Expected behaviour

app load and code run

### Screenshots

![Screen Shot 2023-02-28 at 7 51 56 PM](https://user-images.githubusercontent.com/126633562/222024446-8a834e60-4bfe-4942-87ca-8295b52bf2ce.png)
![Screen Shot 2023-02-28 at 7 52 03 PM](https://user-images.githubusercontent.com/126633562/222024453-f69c6c67-f93b-4f6f-ab40-ae1ea006e442.png)

**Comment by jackbucinskas** [comment]
Hi, I ran into the same issue and got it to work with this, try launching via the terminal: `/Applications/FTB.app/Contents/MacOS/JavaApplicationStub`

When running through the `.../FTB.app/Contents/Resources/app/bin/ftbapp.app/Contents/MacOS/ftbapp` the logs said "Could not find the binary to launch backend"

**Comment by corrupt7581** [comment]
It seems like the issue had fixed itself after I had completely deleted the
application from both the files and dragged it to the delete bin and
waiting a week to redownload
