### ISSUE TITLE
[BUG] "Fatal Exception Whilst Installing Modpack"

### ISSUE THREAD

**Issue by AVNGDeadpool** [FTBTeam/FTB-App#870]
### What Operating System

Windows 10

### Debug Code

FTB-DBGUYEZICOYUJ

### Describe the bug

whenever i try to download a modpack that has a beta version, i get an error that says "Fatal exception whilst installing modpack". I have tried uninstalling and reinstalling both the FTB App as well as Overwolf as a whole. Ive even reinstalled Java to see if somehow that was the issue and still nothing. The only length I havent gone to is reinstalling windows, but im willing to if that could fix it.

### Steps to reproduce

1. Click install on any modpack that has beta versions (bug still occurs on stable versions, as long as beta versions exist)
2. install gets to the "Installing Modloader" step then the error pops up

### Expected behaviour

I expected that the modpack would just install, as it has on any other computer ive used FTB on.

### Screenshots

![image](https://user-images.githubusercontent.com/127245547/223527347-17686e31-d584-43a5-86b9-792d1fe2155f.png)

**Comment by MichaelHillcox** [comment]
Please delete this folder `C:\Users\injur\AppData\Local\.ftba\bin\runtime` and try again

**Comment by BrunoOno0410** [comment]
> Please delete this folder `C:\Users\injur\AppData\Local\.ftba\bin\runtime` and try again

doesn't work

**Comment by MichaelHillcox** [comment]
Can you create a new debug code please
