### ISSUE TITLE
[BUG] Fatal Exception while Preparing Installation

### ISSUE THREAD

**Issue by NorielSylvire** [FTBTeam/FTB-App#871]
### What Operating System

Linux (Debian)

### Debug Code

FTB-DBGFEFIMUVIMU

### Describe the bug

Modpacks cannot be installed or updated

### Steps to reproduce

1. Launch the app without root permissions
2. Select an installed modpack to update, or a not installed modpack to install
3. Click Install/Update

### Expected behaviour

The modpack should get installed or updated

### Screenshots

![Screenshot_20230309_225130](https://user-images.githubusercontent.com/39311030/224168574-737d592e-266b-49c2-ade2-4f8a1180dab1.png)

### Additional information

When I run the program as root, it tells me it cannot be ran as root without --no-sandbox.

Very well, I also ran it with --no-sandbox, but it still stopped and said it cannot be ran as root without --no-sandbox.

I tried running the launcher with jdk 8, not possible because it needs a more recent version.
I tried running the launched with jdk 17, stopped and said I need to run it with --no-sandbox.

**Comment by MichaelHillcox** [comment]
Try updating the app https://apps.modpacks.ch/FTBApp/release/202305040918-ddf5bac63d/FTBA_unix_202305040918-ddf5bac63d.sh

**Comment by MichaelHillcox** [comment]
Closed due to no response
