### ISSUE TITLE
Can't search for any mods to add to modpack

### ISSUE THREAD

**Issue by HoodedKatso** [FTBTeam/FTB-App#872]
### What Operating System

Windows 11

### Debug Code

FTB-DBGATAJALOZUL

### Describe the bug

Nothing happens when I try to search for mods to add to a modpack, not even a "no mods found" message.

### Steps to reproduce

1. Go onto seemingly any downloaded mod pack in your library
2. Go onto it's page and click the "Mods" category
3. Click "Add more mods"
4. Search anything, and the launcher will simply get stuck on "Searching..."

### Expected behaviour

I expect for the mod I'm searching for to appear, or a message saying it no compatible version exists

### Screenshots

<img width="813" alt="image" src="https://user-images.githubusercontent.com/127792919/224825793-e03fbac3-6d10-47b9-9768-59579f9a8f90.png">

### Additional information

I'm not sure if it simply won't load at all, but I know it won't load anything after ~5 minutes. Even while filling this out, the search has been loading the entire time with nothing appearing. I tried it with other mod packs with the same effect- indefinite searching. I can add mods manually by going to the CurseForge site, but it's difficult to make sure I'm downloading the compatible version of the mod when some modpack pages don't show the exact version of the game

**Comment by HoodedKatso** [comment]
So it appears that the mod search option is working with some mod packs and not with others, particularly Legend of The Eyes, Ultimate Origins Modpack, and DarkRPG

**Comment by TNoStone** [comment]
Anyone figure out how to fix this?
