### ISSUE TITLE
mod not finishing starting

### ISSUE THREAD

**Issue by Ultare** [FTBTeam/FTB-App#873]
### What Operating System

Windows 11

### Debug Code

these aren't working

### Describe the bug

I try to open an instance and it fails to get past finishing up mantle

### Steps to reproduce

I try to open the instance

### Expected behaviour

it to open the instance

### Additional information

[https://pste.ch/vumemopure](url) logs

I've played this mod pack for the last few days but then was playing on a local server with 4 others. one person changed the mipmap level and their game crashed. whenever they tried to load back in it got stuck trying to launch a new instance. Once the rest of us closed revelations later on we had the same issue when trying to launch it again.

**Comment by Ultare** [comment]
[console.log](https://github.com/FTBTeam/FTB-App/files/10969435/console.log)

**Comment by CoryNB** [comment]
i recently tried installing and building mods for a known curseforge modpack. but mineforge was also not downloading for me. i uninstalled the atm7sky and it crashed the app.

**Comment by MichaelHillcox** [comment]
Closing due to no debug code. Please reopen your issue if this is still happening
