### ISSUE TITLE
atm7sky crashed while booting up, but crash app while uninstalling it.

### ISSUE THREAD

**Issue by CoryNB** [FTBTeam/FTB-App#875]
### What Operating System

Windows 11

### Debug Code

App crash, no debug

### Describe the bug

uninstalling atm7sky crash and unable to load 

### Steps to reproduce

searched for ex compression and xray for my modpack. 

### Expected behaviour

for mods to work with modpack without crash.

### Additional information

if this still happens, then there must be a bug within one of the mods installed and should be investigated if it could corrupt the app without warning.

**Comment by MichaelHillcox** [comment]
Closing due to no debug code supplied
