### ISSUE TITLE
can't connect with microsoft (we can't find the FTB app) (i fixed it)

### ISSUE THREAD

**Issue by BAKAsdems** [FTBTeam/FTB-App#877]
### What Operating System

Windows 10

### Debug Code

FTB-DBGINORIBASOH

### Describe the bug

when i try to connect via a modpack or the sign in feature at the bottom left it gives me the options i click the one i use redirect me on the internet page but don't find the app

### Steps to reproduce

1 either connect by the sign in feature or trying to launch a modpack (stoneblock 3 and vanilla in my case)
2 connect microsoft (redirect to the web page)
3 : We can't find the FTB app!

### Expected behaviour

open the web page to let me connect via microsoft

### Additional information

i fixed it while writing this : the launcher worked fine before i tryed to update to WIN11 (on a shadow desktop) caused a lot a bugs for different things / games so i got it back to windows 10 tryed to reconnect FTB and there's the bug tryed different things ,when i was writing this i tried to log in another time , redirection to a page with (nothing) no ads but looking like one still where blocked , it was the ad-block (strict) not permitting the comunication with the app ,now i can connect.

**Comment by MichaelHillcox** [comment]
Glad you got it fixed.
