### ISSUE TITLE
Direwolf instances missing

### ISSUE THREAD

**Issue by rbwood** [FTBTeam/FTB-App#878]
### What Operating System

Windows 10

### Debug Code

This app is unverified, and I am not comfortable running it

### Describe the bug

FTB App no longer showing my direwolf instances.

### Steps to reproduce

Run the FTB App

### Expected behaviour

Shows the instance I've been playing for the past 3 months

### Screenshots

![image](https://user-images.githubusercontent.com/21110207/228052460-6f3a4193-22d0-4edb-988c-946ae11301d1.png)
![image](https://user-images.githubusercontent.com/21110207/228052565-4c10d446-8414-4307-b22f-8b312e9e200f.png)

### Additional information

The app shows FTB One, which I installed months ago, and it shows 2 different instances of Direwolf 20 that I installed today, but it does not show my other Direworlf 20 instances, one of which I was just playing last night.  When I open the new Direwolf20 instances, they will not let me open the world I was playing last night on the instance that is missing.

This has happened before, but restarting the app brought my instances back.  I restarted the app several times toeday, and it continues to show only FTB One, and the 2 new instances I installed today.

**Comment by CoryNB** [comment]
the modpack draws alot of ram and processor resources. max out your ram and processiing resources before upgrading your storage drives. go for filling your pcie slot with either sata. gpu, usb, or even useful pcie cards as well to increase your computer storage/function. check your settings and reduce pixels to below 1000 to 1000 pixels, make sure you max out your allowed ram for instance.

**Comment by MichaelHillcox** [comment]
Please completely ignore them... That's... honestly just stupid.

Your issue is that your instance.json is corrupt. I can walk you through fixing it if you'd like.

**Comment by rbwood** [comment]
Yeah, that was my feeling as well.

 That would be great, thanks!

**Comment by MichaelHillcox** [comment]
Please can you attach both the working instance.json from one of the duplicate direwolf instance folders (app -> direwolf pack -> 3 dots next to play -> open -> instance folder -> drop the instance.json into github). 

Then find the instance.json file for the pack not working. You can do this by repeating the above steps to find all the instance folders that the app can see, the remaining instance folder will be the one will be the broken one. Provide the folder name of that instance. Should look a bit like `0cc070e8-ca5d-4d3d-bb8e-e37717e0c97d`
