### ISSUE TITLE
no download manager

### ISSUE THREAD

**Issue by morteza20deris** [FTBTeam/FTB-App#880]
### What Operating System

Windows 10

### Debug Code

FTB-DBGAZUVIKOFOG

### Describe the bug

if you start downloading a mod pack and exit the download screen you can't see the process anymore

### Steps to reproduce

go to any mod pack
click download then exit that page
you can't get the download page anymore

### Expected behaviour

a way to get back to the download process screen

**Comment by MichaelHillcox** [comment]
Screenshots please?
