### ISSUE TITLE
I somehow BROKE the app

### ISSUE THREAD

**Issue by strikes-cat** [FTBTeam/FTB-App#882]
### What Operating System

Windows 10

### Debug Code

FTB-DBGCEVEXAXUCI

### Describe the bug

I can't launch the ftb app

### Steps to reproduce

1. click on the app shortcut on my desktop
2. click it again right after the first click
3. wait at set up screen 
4. tells me something when wrong

### Expected behaviour

I expect to be greeted by my mod packs and instances of minecraft

### Additional information

the only setting I changed on my computer was enabling CPU virtualization, so I could try and utilize google play games (for pc beta), after failing to launched, that I went to play Minecraft and discovered a issue of not being able to launch a modpack due to an invalid java augment. so I restarted my pc, turned off CPU virtualization and then I manually tried to change the augment now I cant do anything

**Comment by iosonoagenda** [comment]
I talk really directly: Your own OS has bugs, your app has bugs, you may understand when these two collaborate each other to not working, well... good luck mate!

**Comment by MichaelHillcox** [comment]
Looks like the app was run as an admin. Please reinstall the modpack whilst the app is not running in admin mode
