### ISSUE TITLE
FTB App has crashed

### ISSUE THREAD

**Issue by beliboba** [FTBTeam/FTB-App#883]
### What Operating System

Windows 11

### Debug Code

FTB-DBGOKOCEYITUS

### Describe the bug

I try to open FTB app, it crashes

### Steps to reproduce

1. Launch ftb app

### Expected behaviour

Ftb app launches, i play minecraft

### Screenshots

![image](https://user-images.githubusercontent.com/73661136/229561441-7ce1555d-ca55-4f42-a00e-4785eff3916f.png)

### Additional information

Reinstalling java didnt work for me

**Comment by MichaelHillcox** [comment]
Looks like two versions of the app were open at the same time. Try a pc restart and see if it fixes itself.
