### ISSUE TITLE
App keeps trying to authenticate with Mojang for my Microsoft account

### ISSUE THREAD

**Issue by Luxinaut** [FTBTeam/FTB-App#884]
### What Operating System

Windows 11

### Debug Code

FTB-DBGUWEKEJOCEQ

### Describe the bug

The app keeps trying to authenticate my Microsoft account with Mojang which understandably locks me out of multiplayer. This happens at random but seems to be becoming more frequent and I don't know why.

### Steps to reproduce

I wouldn't know how to reproduce the error because it just randomly occurs as I try to load up an instance.

### Expected behaviour

I expected the app to log in my Microsoft by authenticating with Microsoft and not Mojang for some reason.

**Comment by MichaelHillcox** [comment]
Not sure what you mean by this, looks to have worked fine, Let me know if this is still an issue.
