### ISSUE TITLE
Modinstaller Fatal Exception

### ISSUE THREAD

**Issue by IrishConartist** [FTBTeam/FTB-App#886]
### What Operating System

Windows 10

### Debug Code

FTB-DBGCAZIJEGEQA

### Describe the bug

Mod Installer won't load - Modpacks won't install

### Steps to reproduce

1. Open FTB App
2. Try to install a modpack
3. Pack begins to download, screen now says installing modloader
4. App is unable to move past installing the modloader, after several minutes it fails claiming "fatal exception while installing modpack"
5. This issue persists on any modpack
6. Attempted various installs and reinstalls of the FTB, Java and PC restart, no success.

### Expected behaviour

Modpack and modinstaller would install and be playable

### Screenshots

<img width="1159" alt="1" src="https://user-images.githubusercontent.com/87912800/230199740-97472477-b7c7-423f-87ef-607c8e0f8253.png">
<img width="1151" alt="2" src="https://user-images.githubusercontent.com/87912800/230199745-c6168822-1b21-4654-9644-bd82be38ea95.png">
<img width="1160" alt="3" src="https://user-images.githubusercontent.com/87912800/230199748-eeb725ba-d38a-49f6-ba01-88b04d4cc625.png">

### Additional information

Debug tool gave the error code supplied above while also saying: 

Uploading chat.html.log: failed to open file
          open C:\Users"user"\AppData\Local\Overwolf\Log\Apps\FTB App\chat.html.log: The system cannot find the file specified.

**Comment by CoryNB** [comment]
have task manager up and running, constantly check that while it is occuring. sometimes specs of your computer can affect how well it operates.

**Comment by Teaunimm** [comment]
you should try to reinstall FTB app with another appinstaller.
delete appinstaller and download again its should work

**Comment by IrishConartist** [comment]
> 

I tried to install the Stone Block 3 modpack with the TM open, nothing changed and nothing I noticed was different.

**Comment by IrishConartist** [comment]
> you should try to reinstall FTB app with another appinstaller. delete appinstaller and download again its should work

I got the installer from their website, is there some other place I can go to get the appinstaller for the FTB?

**Comment by Teaunimm** [comment]
> 

Just delete and reinstall from their website

**Comment by IrishConartist** [comment]
> > 
> 
> Just delete and reinstall from their website

I said in my original post I have deleted and reinstalled the FTB app several times, each time I get the same issue.

**Comment by Teaunimm** [comment]
> 

No no you need delete ftbappinstaller.exe and download another one I did like that

**Comment by IrishConartist** [comment]
I just went to the .ftba folder and deleted it, I even refreshed the cache in the app.

I've just swapped where I want it to install the instance to see if anything chances. If it installs, I'll move it back
