### ISSUE TITLE
[Bug] Integrity Check Timeout on instances.

### ISSUE THREAD

**Issue by Coppertine** [FTBTeam/FTB-App#89]
**Operating System:**
OS: Windows 10 Home 1909

**Installer Version:**
Installer: 1.0.6

**App Version:**
App: 1.0.6

**UI Version:**
UI: c84af858

**Log Files:**
[Sky Odyssey](https://pste.ch/ahatijuvid)
[Sky Adventures](https://pste.ch/fuyuqaxuzi)
[Sky Odyssey after re-installation of app](https://pste.ch/equwinitum)
[Pyramid Reborn 3.0 (after re-installation of app)](https://pste.ch/imoxocuzud)

**Describe the bug**
When ever I try to download a modpack as a new instance, it goes to around 20-30% until the message "Error Installing {MODPACK NAME} - timeout - " with a retry button that doesn't function. More information below;

**To Reproduce**
Steps to reproduce the behaviour:
1. Open FTBApp
2. Find modpack to install
3. Click download button
4. Click install
5. Wait for timeout.

**Expected behaviour**
Instance should have been fully installed without the timeout error showing.

**Screenshots**
https://cdn.discordapp.com/attachments/695329867037933609/698796687191441508/unknown.png (Before Reinstall)
![image](https://user-images.githubusercontent.com/37494321/79065655-703b7d00-7cf5-11ea-8c9b-2701598a7f61.png) After reinstall

**Additional context**
Installation folder was installed on a drive that is NOT the boot drive, which works well for the two modpacks I had previously installed (FTB Interactions and FTB Academy). However, when ever I try to install anything else, I always get a timeout.

Another issue is with the timeout error not allowing you to click on the "Retry" button which forces you to close down the app and reopen it. Making the modpack appear in the "My Modpacks" folder. However, when launching the game, it finds that not all of the mods are correctly installed:
https://cdn.discordapp.com/attachments/557262538752917534/698793245173481612/unknown.png

**Comment by Gaz492** [comment]
Hi,

Do you still have this issue with newer versions of the app?
