### ISSUE TITLE
App won't open "Oh this doesn't look right"

### ISSUE THREAD

**Issue by CiaranB09** [FTBTeam/FTB-App#890]
### What Operating System

Windows 11

### Debug Code

FTB-DBGROROXUKOLA

### Describe the bug

the app wont open and say "Oh this doesn't look right"

### Steps to reproduce

Trying to open the app

### Expected behaviour

the app to open

### Screenshots

![ftb app issue](https://user-images.githubusercontent.com/60655466/231572212-03ed5270-825e-4717-bdb0-02d380a79516.PNG)

### Additional information

Tried multiple times and restarted the computer multiple times. Also tried uninstalling and reinstalling, still persists.

**Comment by iosonoagenda** [comment]
Seems like something got broken, give more information to community, please.

**Comment by Jens-Willadsen** [comment]
Are there any connection servers that are down?,  I have the same problem!

**Comment by thearwie** [comment]
At this time, there is no services problems on Feed The Beast Ltd status.
But I have the same error as the others.
![image](https://user-images.githubusercontent.com/15324983/231844624-70f392e2-9e9e-4350-b7a8-271d8fc8d50b.png)

**Comment by CiaranB09** [comment]
https://forum.feed-the-beast.com/threads/ftb-app-doesnt-start.303048/

this works for me but I need to do it every time I restart. not a solution but it helps short-term

**Comment by JasonWBridgeTown** [comment]
I have the same problem.  FTB app worked for months just fine.   I mainly play Sky Factory 3.   A couple days ago I started getting the same error that CiaranB09  posted above.

**Comment by Hyrla** [comment]
Same issue here. Is there any way to see debug info ? It's VERY frustating to have a stupid "Oh... This doesn't look right..." message instead of usefull error message :)
