### ISSUE TITLE
Modpack crashing on boot

### ISSUE THREAD

**Issue by Infitheta** [FTBTeam/FTB-App#891]
### What Operating System

Windows 10

### Debug Code

FTB-DBGFUCAPUBASE

### Describe the bug

Whenever I try and launch a modpack I get the error "looks like the instance has crashed during startup or whilst running"

### Steps to reproduce

Whenever I press play on a modpack (I've downloaded a few and they're all doing the same thing I get an error saying that the instance has crashed. I've attached a screenshot and the [crashlog](url)

[hs_err_pid32216.log](https://github.com/FTBTeam/FTB-App/files/11238848/hs_err_pid32216.log)

### Expected behaviour

The game to launch

### Screenshots

![image](https://user-images.githubusercontent.com/113709850/232200463-25d4a2a0-0139-463c-afc2-03b72fbb8f79.png)

**Comment by MichaelHillcox** [comment]
Not an app issue, please use the modpack issue tracker https://go.ftb.team/support-modpack
