### ISSUE TITLE
Не можу приєднати акаунт до FTB

### ISSUE THREAD

**Issue by zander1024** [FTBTeam/FTB-App#894]
### What Operating System

Windows 10

### Debug Code

FTB-DBGORAVOHIRED

### Describe the bug

Видає помилку при підключені акаунта

### Steps to reproduce

При приєднані акаунта Microsoft видає помилку та каже спробувати ще раз.

### Expected behaviour

Хочу приєднати акакунт

### Screenshots

![image](https://user-images.githubusercontent.com/130917518/232322961-e3c9ece1-c25a-4754-8596-fef023be720e.png)

**Comment by MichaelHillcox** [comment]
Please use the discord for authentication issues
