### ISSUE TITLE
It looks like something went wrong with the App

### ISSUE THREAD

**Issue by mrowek** [FTBTeam/FTB-App#898]
### What Operating System

Windows 10

### Debug Code

FTB-DBGEKEDIJAVUY

### Describe the bug

FTB App refuses to launch

### Steps to reproduce

1. Launch FTB-App
2. Wait till will end loading 
3. Oh... This doesn`t look right...
4. Little tear of misery

### Expected behaviour

FTB-App should launch and allow me to play modpacks

### Screenshots

![2023-04-18_10h37_31](https://user-images.githubusercontent.com/46714144/232721597-2476e349-428c-4731-8cf2-ac7c3484aa92.png)

### Additional information

One day it was working fine, another stopped working.
PC was not restarted, no changes done. Nothing.
Tried restart PC, reinstal FTB-App

**Comment by habeebX34** [comment]
I have the same problem as you 
did you fix it 
if you fix who

**Comment by Yamijro** [comment]
I had the same issue and i tried everything mentioned above. Which didnt work. Then i uninstalled overwolf and everything related to it on my pc. While installing it again i chose even a new directory for the ftb app to be installed in and now it seems to be working fine again.

**Comment by MichaelHillcox** [comment]
Compacting to #890
