### ISSUE TITLE
Enhancements for non-technical users.

### ISSUE THREAD

**Issue by fuhrriel** [FTBTeam/FTB-App#9]
#### Context
Many players of modded Minecraft are non-technical users whose technical prowess may end at pressing download and play. Some enhancements to default values and GUI would limit their possible problems. 

#### Problem 1:
Default memory in settings defaults to 512mb, which is probably not enough for even 'litest' of modpacks.
![image](https://user-images.githubusercontent.com/49496299/78289571-ac672480-7522-11ea-8a90-9e5509dc2262.png)

##### Proposed solution:
Increase default ram to higher value  

#### Problem 2: 
No indication that modpack version can be changed on download screen. 
![image](https://user-images.githubusercontent.com/49496299/78290411-04eaf180-7524-11ea-8585-6e55fc43ee95.png)

##### Proposed solution:
Add any symbol pointing down like: ▾, to indicate that it's a dropdown menu.

**Comment by Gaz492** [comment]
Removed memory setting from settings page as each modpack instance has its own memory setting located under the settings tab of the instance
