### ISSUE TITLE
Context menus

### ISSUE THREAD

**Issue by Poopooracoocoo** [FTBTeam/FTB-App#901]
### What is your suggestion?

Settings and folders are multiple clicks away. It may not be clear that users can do anything other than click play when interacting with an instance.

A context menu would solve that.

### Additional information

UI version: 91bb027b9e
App version: 202304121437-91bb027b9e
Overwolf client version: 0.221.0.4
Windows 10 22H2
FTB debug code: FTB-DBGOMAYIYAZOK

**Comment by MichaelHillcox** [comment]
This has been released now :+1:
