### ISSUE TITLE
Titlebar does not appear different when window is inactive

### ISSUE THREAD

**Issue by Poopooracoocoo** [FTBTeam/FTB-App#902]
### What Operating System

Windows 10

### Debug Code

FTB-DBGOMAYIYAZOK

### Describe the bug

Titlebar does not appear different when window is inactive

### Steps to reproduce

1. Open FTB App
2. Make the FTB App lose focus by clicking elsewhere

### Expected behaviour

When inactive, the FTB App's titlebar would change color, and the caption buttons and title would be dimmed. 

### Additional information

UI version: 91bb027b9e
App version: 202304121437-91bb027b9e
Overwolf client version: 0.221.0.4
Windows 10 22H2

**Comment by Poopooracoocoo** [comment]
**Actual behaviour:**
FTB App active:
![image](https://github.com/FTBTeam/FTB-App/assets/51363864/3e039d15-8fe2-4125-b920-738171cab528)
FTB App inactive:
![image](https://github.com/FTBTeam/FTB-App/assets/51363864/3ca69067-5fd4-4c8b-8500-6a958c725e12)

**Expected behaviour:
Example: Notepad**
Notepad active (with accent coloured titlebars and window borders enabled in Windows)
![image](https://github.com/FTBTeam/FTB-App/assets/51363864/96608e38-16ca-4118-8a0a-80e360d63385)
Notepad active
![image](https://github.com/FTBTeam/FTB-App/assets/51363864/a7d72cab-5d34-4d20-b79b-dc4c477fe1fd)
Notepad inactive
![image](https://github.com/FTBTeam/FTB-App/assets/51363864/b471efbb-9c46-4126-9ffb-0fbe0d0b6dc3)

**Example: Google Chrome**
Chrome active (with accent coloured titlebars and window borders enabled in Windows)
![image](https://github.com/FTBTeam/FTB-App/assets/51363864/0c556f2a-611f-4b27-ba69-d1d29c90c6f6)
Chrome inactive (with accent coloured titlebars and window borders enabled in Windows)
![image](https://github.com/FTBTeam/FTB-App/assets/51363864/c1a2edf9-4249-4f7d-a45a-3a3d74ff434c)
Chrome active
![image](https://github.com/FTBTeam/FTB-App/assets/51363864/c5cd4cd1-0c21-4f5d-b3dd-499d9ad008ce)
Chrome inactive
![image](https://github.com/FTBTeam/FTB-App/assets/51363864/3a4055b5-602e-4542-afae-4c020b889604)

**Example: VS Code**
VS Code active
![image](https://github.com/FTBTeam/FTB-App/assets/51363864/7668c17c-b153-42a8-8a19-eadfca9cf7fc)
VS Code inactive
![image](https://github.com/FTBTeam/FTB-App/assets/51363864/e65e83b0-9581-4af8-ac42-5797611607e8)

**Comment by MichaelHillcox** [comment]
Interesting, thanks for getting back to me, I can look into getting this sorted out
