### ISSUE TITLE
App Crashing on Boot... Unplayable

### ISSUE THREAD

**Issue by SunTouno** [FTBTeam/FTB-App#906]
### What Operating System

Windows 10

### Debug Code

FTB-DBGAROWOKUPUN

### Describe the bug

App Crash on Boot

### Steps to reproduce

1. Open App
2. App Fails
3. "Oh... This doesn't look right..."
![Blaghh](https://user-images.githubusercontent.com/131628668/233877460-a92223d9-07f9-45ab-9f23-a90de144e3b9.jpg)

### Expected behaviour

I expected the app to load normally

### Screenshots

![Blaghh](https://user-images.githubusercontent.com/131628668/233877478-ae497bc1-af9c-4869-83e2-47593a6a8db9.jpg)

**Comment by MichaelHillcox** [comment]
Is this still an issue?

**Comment by MichaelHillcox** [comment]
Compacting to #890 please reply there
