### ISSUE TITLE
Update information could not be downloaded from...

### ISSUE THREAD

**Issue by Ezechiel357** [FTBTeam/FTB-App#907]
### What Operating System

MacOS (Latest)

### Debug Code

Unable to provide a code

### Describe the bug

Update information could not be downloaded message. The impossible to start any instances

### Steps to reproduce

1. Click on FTBApp
2. Get 
(Message:
The update information could not be downloaded from
https://apps.modpacks.ch/FTBApp/release.xml
Please check your network connection.)
![Screenshot 2023-04-25 at 15 38 52](https://user-images.githubusercontent.com/9285605/234294774-7ef5610e-90c9-48fd-bc49-b3c222b28f1e.png)

### Expected behaviour

Not the regular window. Only uploaded modpacks are showing up.

### Screenshots

![Screenshot 2023-04-25 at 15 40 34](https://user-images.githubusercontent.com/9285605/234295424-379d37f4-d8bd-4f15-99e0-d331163e8cb0.png)

From then, impossible to start any modpacks or any instances.

**Comment by MichaelHillcox** [comment]
Welp, that URL definitely exists and is working, make sure your firewall isn't blocking it. Can't do much our end with that error, sorry. Let me know if you need any help debugging but our Discord might be the best place to go for support of that nature.

https://go.ftb.team/discord
