### ISSUE TITLE
[Bug] Ads overlay on top of version select screen

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-App#908]
### What Operating System

Windows 10

### Debug Code

N/A

### Describe the bug

Ads overlay on top of version select screen

### Steps to reproduce

1. get add
2. go to modpack version window
3. see ad overlays

### Expected behaviour

Not to do that

### Screenshots

![](https://ss.manmaed.net/1682547675.png)

**Comment by MichaelHillcox** [comment]
This is kinda meant to happen but definitely not ideal. I can sort this.
