### ISSUE TITLE
[Bug] Contents of frameworks in Mac launcher are duplicated

### ISSUE THREAD

**Issue by dgelessus** [FTBTeam/FTB-App#91]
**Operating System:**
OS: macOS 10.14.6

**Installer Version:**
Installer: ?

**App Version:**
App: 1.0.6

**UI Version:**
UI: c84af85886609817d5af5a51677f6f0d583661f5

**Log Files:**
n/a

**Describe the bug**
The files in the frameworks in the Mac launcher (under FTBApp.app/Contents/Resources/app/bin/ftbapp.app/Contents/Frameworks) are duplicated - all files exist once in the root directory of the framework and once under the Versions/A directory.

Normally, the files and directories in the root directory of a Mac framework should not be regular files, but symbolic links that point into the Versions subdirectory. For example, this is how it looks in macOS's /System/Library/Frameworks/CoreFoundation.framework:

```
$ cd /System/Library/Frameworks/CoreFoundation.framework
$ ls -al . Versions/ Versions/A/
.:
total 0
drwxr-xr-x    5 root  wheel   160  8 Jun  2019 .
drwxr-xr-x  150 root  wheel  4800  4 Sep  2019 ..
lrwxr-xr-x    1 root  wheel    31  8 Jun  2019 CoreFoundation -> Versions/Current/CoreFoundation
lrwxr-xr-x    1 root  wheel    26  8 Jun  2019 Resources -> Versions/Current/Resources
drwxr-xr-x    4 root  wheel   128  8 Jun  2019 Versions

Versions/:
total 0
drwxr-xr-x  4 root  wheel  128  8 Jun  2019 .
drwxr-xr-x  5 root  wheel  160  8 Jun  2019 ..
drwxr-xr-x  5 root  wheel  160 25 Mär 13:59 A
lrwxr-xr-x  1 root  wheel    1  8 Jun  2019 Current -> A

Versions/A/:
total 21168
drwxr-xr-x   5 root  wheel       160 25 Mär 13:59 .
drwxr-xr-x   4 root  wheel       128  8 Jun  2019 ..
-rwxr-xr-x   1 root  wheel  20808496 19 Mär 00:33 CoreFoundation
drwxr-xr-x  44 root  wheel      1408 25 Mär 13:59 Resources
drwxr-xr-x   3 root  wheel        96 25 Mär 13:59 _CodeSignature
```

Note that everything in the root directory (except the Versions directory) is a symlink pointing into Versions/Current. Versions/Current is a symlink pointing to Versions/A, and Versions/A contains the actual files.

In contrast, here's how a framework looks in the FTBApp (this is Electron Framework.framework):

```
$ cd FTBApp.app/Contents/Resources/app/bin/ftbapp.app/Contents/Frameworks/Electron Framework.framework
$ ls -al . Versions/ Versions/A/
.:
total 229392
drwxr-xr-x   6 user  staff        192 10 Apr 00:37 .
drwxr-xr-x  10 user  staff        320 10 Apr 00:37 ..
-rw-r--r--   1 user  staff  115438352 10 Apr 00:37 Electron Framework
drwxr-xr-x   7 user  staff        224 10 Apr 00:37 Libraries
drwxr-xr-x  63 user  staff       2016 10 Apr 00:37 Resources
drwxr-xr-x   3 user  staff         96 10 Apr 00:37 Versions

Versions/:
total 0
drwxr-xr-x  3 user  staff   96 10 Apr 00:37 .
drwxr-xr-x  6 user  staff  192 10 Apr 00:37 ..
drwxr-xr-x  5 user  staff  160 10 Apr 00:37 A

Versions/A/:
total 250320
drwxr-xr-x   5 user  staff        160 10 Apr 00:37 .
drwxr-xr-x   3 user  staff         96 10 Apr 00:37 ..
-rw-r--r--   1 user  staff  115438352 10 Apr 00:37 Electron Framework
drwxr-xr-x   7 user  staff        224 10 Apr 00:37 Libraries
drwxr-xr-x  63 user  staff       2016 10 Apr 00:37 Resources
```

Here, the files and directories in the root directory are not symlinks, but regular files/directories. Their contents are identical to the same files under Versions/A, but because they are separate files, they take up twice the disk space.

This is especially noticeable with Electron Framework.framework, which is already 160 MB large normally, and is now 320 MB large because of this issue.

**Comment by Gaz492** [comment]
Hi,

I believe this issue was fixed, in one of the latest updates to the app.
If the issue still exists please open a new issue.
