### ISSUE TITLE
MacOS launch error

### ISSUE THREAD

**Issue by 1John5vs7** [FTBTeam/FTB-App#910]
### What Operating System

MacOS (Old)

### Debug Code

(neither MacOS version returned a code, just a notepad full of gibberish)

### Describe the bug

When launching from MacOS X 10.12.6, launcher returns error "ftbapp cannot be opened because of a problem"

### Steps to reproduce

1. Downlaod FTB app from FTB website
2. Install
3. Attempt to launch

### Expected behaviour

Expected the app to launch instead

### Screenshots

![image](https://user-images.githubusercontent.com/15369416/235563244-5016e995-6512-4881-9e6a-a0e7818ce813.png)

### Additional information

Here's a pastebin link to the full error report if that helps:

https://pastebin.com/SBycMpDN

I should note, I'm remotely assisting my partner in trying to launch FTB App. I'm on a PC, but she's running on a Mac. She has successfully launched FTB App in the past but now cannot get it to launch for some reason. She tried both versions of the MacOS Debugger (The normal and the Arm64) and both gave her a notepad full of wing-dings and bizarre symbols rather than a code. I am not able to help her further because I know very little about Macs other than that they make a very, very satisfying sound when hitting concrete from several stories up.

**Comment by MichaelHillcox** [comment]
Looks like the correct solution would be to update the MacOS version
