### ISSUE TITLE
Issue connecting to server ive been playing on

### ISSUE THREAD

**Issue by Punimation** [FTBTeam/FTB-App#912]
### What Operating System

Windows 11

### Debug Code

FTB-DBGTIWUPEROZU

### Describe the bug

cant join server

### Steps to reproduce

log into FTB APP 
Click Play on Modpack
When I got to click on a server in multiplayer I was playing on it tells me unable to log in

### Expected behaviour

Be able to log into server

### Screenshots

![image](https://user-images.githubusercontent.com/132419447/235824020-59ba0e90-a60e-47dc-a959-14321f5183f4.png)

**Comment by MichaelHillcox** [comment]
This should be fixed, let me know if it's not
