### ISSUE TITLE
Unable to fetch profile

### ISSUE THREAD

**Issue by Yaemi9725** [FTBTeam/FTB-App#913]
### What Operating System

Windows 10

### Debug Code

FTB-DBG

### Describe the bug

I can't fetch my Minecraft Account (no id found) but on every other client it works.

### Steps to reproduce

1. Start the App
2. Sign in to your Minecraft Account
3. Choose Microsoft
4. Log in to the Microsoft - Mojang Account
5. FTB-App: Failed to login due to: Unable to fetch profile from Minecraft account (no id found)

### Expected behaviour

I expect that the FTB App runs with my Minecraft acc

### Screenshots

![image](https://user-images.githubusercontent.com/132685331/236493345-8f82a7ed-bea8-40c2-a26b-5f9d314db803.png)

### Additional information

My Account runs with Curseforge, TechnicLauncher, ATLauncher, etc. but not with FTB

**Comment by MichaelHillcox** [comment]
This should be fixed, make sure your app is up-to-date and let me know if it still fails
