### ISSUE TITLE
Failed to execute assest update task.

### ISSUE THREAD

**Issue by LoewenGold** [FTBTeam/FTB-App#914]
### What Operating System

Windows 11

### Debug Code

FTB-DBGIQIKOFUXOS

### Describe the bug

i cant start a modpack

### Steps to reproduce

this error happens when i try to start a modpack
i tried it with FTB Skies and Direwolf20 1.19 and in both instances an error shows with

An Error Occurred Whilst Launching
Failed to prepere instance FTB Skies (...) because..java.io.IOException: Faild to execute asset update task.

### Expected behaviour

the modpack should normaly start

### Screenshots

<img width="350" alt="Screenshot 2023-05-13 214402" src="https://github.com/FTBTeam/FTB-App/assets/133536872/da4b0002-cccd-4dd3-9d14-63fe2090f3d8">

**Comment by iosonoagenda** [comment]
Throw PC out of window and buy another

**Comment by MichaelHillcox** [comment]
Please try with the latest version of the app:

https://appsdl-overwolf-com.akamaized.net/prod/apps/cmogmmciplgmocnhikmphehmeecmpaggknkjlbag/1.23.622.1340/app.opk

Make sure the FTB App is closed before using this link
