### ISSUE TITLE
Failed to retrieve essential information, first time startup of Stoneblock 3.0

### ISSUE THREAD

**Issue by beartrapsound** [FTBTeam/FTB-App#915]
### What Operating System

Windows 10

### Debug Code

FTB-DBGCAPOTODABE

### Describe the bug

Failed the retrieve essential information after logging into microsoft account

### Steps to reproduce

Go to FTB App

Click Play Button for Stoneblock 3.0

Click Microsoft Login button, browser window opens

I successfully log into my microsoft account

FTB App says "Failed to retrieve essential information, please try again."

### Expected behaviour

Expected game to launch for the first time

**Comment by Popcorncraft** [comment]
This also happens with Windows 11 and when you use the code that's given in the browser instead of allowing it to open a link to the FTB app it just says "We're just checking the credentials, one moment please." and doesn't do anything else.

**Comment by Popcorncraft** [comment]
I just realized that it was trying to sign me into a Microsoft account that didn't have minecraft purchased. Make sure you are signing into the correct microsoft account.

**Comment by manmaed** [comment]
From what I can see, your Microsoft account that you are using to sign in with doesn't own Minecraft, please make sure you are signing in to correct Microsoft account.
