### ISSUE TITLE
Failed to login due to:Failed to authenticate with Xbox

### ISSUE THREAD

**Issue by Set1475** [FTBTeam/FTB-App#917]
### What Operating System

Windows 10

### Debug Code

*

### Describe the bug

I can't Sign microsoft accout i have error Failed to login due to:Failed to authenticate with Xbox

### Steps to reproduce

Pls help

### Expected behaviour

I can't Sign microsoft accout i have error Failed to login due to:Failed to authenticate with Xbox

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/135463424/e881a0f0-8a0c-45c9-98ea-acf6a031f557)

### Additional information

Pls help me i don't know how to fix it

**Comment by manmaed** [comment]
## Please do the following

Please use the link below to download and run the FTB Debug tool. This is a tool built by our App Developers and will provide you a code that you need to attach to this issue. Please either edit your original issue or add a comment with this code. If you need more help running this tool, you can [follow our guide on how to use the FTB Debug tool](https://go.ftb.team/ftbdbg-support).

[Windows](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe) // [MacOS](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos) // [Linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux) // [Windows (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-arm64.exe) // [MacOS (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos-arm64) // [Linux (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux-arm)

**Comment by Set1475** [comment]
FTB-AUTH-000001

**Comment by manmaed** [comment]
also please make sure you are signing in to correct Microsoft account that owns Minecraft. Thats not a code that the Debug tool outputs

Please Follow:
> Hay, thanks for the issue! Unfortunately it looks like you've not provided a `Debug code`... We require this as it helps us find your issue as quickly as possible.
> ## Please do the following
> 
> Please use the link below to download and run the FTB Debug tool. This is a tool built by our App Developers and will provide you a code that you need to attach to this issue. Please either edit your original issue or add a comment with this code. If you need more help running this tool, you can [follow our guide on how to use the FTB Debug tool](https://go.ftb.team/ftbdbg-support).
> 
> [Windows](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe) // [MacOS](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos) // [Linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux) // [Windows (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-arm64.exe) // [MacOS (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos-arm64) // [Linux (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux-arm)

**Comment by manmaed** [comment]
can you update the app (https://appsdl-overwolf-com.akamaized.net/prod/apps/cmogmmciplgmocnhikmphehmeecmpaggknkjlbag/1.23.608.1410/app.opk) and try to login with that

**Comment by MSeanBattisti** [comment]
I have same issue with a Mac OS (12.6.6)
debug code
FTB-DBGATUHEBAVAX

**Comment by manmaed** [comment]
> @MSeanBattisti 
> I have same issue with a Mac OS (12.6.6) debug code FTB-DBGATUHEBAVAX

do you have any parental controls on OS or firewall that would block our domains?

**Comment by MSeanBattisti** [comment]
@manmaed 
I have had the app working properly for quite a while until something changed with FTB.  No settings changes on my end.

**Comment by PyjamallamaAU** [comment]
> Hay, thanks for the issue! Unfortunately it looks like you've not provided a `Debug code`... We require this as it helps us find your issue as quickly as possible.
> ## Please do the following
> 
> Please use the link below to download and run the FTB Debug tool. This is a tool built by our App Developers and will provide you a code that you need to attach to this issue. Please either edit your original issue or add a comment with this code. If you need more help running this tool, you can [follow our guide on how to use the FTB Debug tool](https://go.ftb.team/ftbdbg-support).
> 
> [Windows](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe) // [MacOS](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos) // [Linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux) // [Windows (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-arm64.exe) // [MacOS (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos-arm64) // [Linux (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux-arm)

App logs from my FTB App that will not log in -
https://pste.ch/satodohuca

and Code from the FTB Debug tool -
FTB-DBGDONADIMOBO

The error relates to not being about to communicate with the Xbox Live Auth server but when I looked at the status page for Xbox Live they are up and running.

**Comment by PyjamallamaAU** [comment]
> > Hay, thanks for the issue! Unfortunately it looks like you've not provided a `Debug code`... We require this as it helps us find your issue as quickly as possible.
> > ## Please do the following
> > Please use the link below to download and run the FTB Debug tool. This is a tool built by our App Developers and will provide you a code that you need to attach to this issue. Please either edit your original issue or add a comment with this code. If you need more help running this tool, you can [follow our guide on how to use the FTB Debug tool](https://go.ftb.team/ftbdbg-support).
> > [Windows](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe) // [MacOS](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos) // [Linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux) // [Windows (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-arm64.exe) // [MacOS (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos-arm64) // [Linux (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux-arm)
> 
> App logs from my FTB App that will not log in - https://pste.ch/satodohuca
> 
> and Code from the FTB Debug tool - FTB-DBGDONADIMOBO
> 
> The error relates to not being able to communicate with the Xbox Live Auth server but when I looked at the status page for Xbox Live they are up and running.

Funny after a several attempts of trying to log in I decided to paste the above and I thought I would try once more before closing the app - suddenly I can now log in despite making not changes to the App and there is no change to the statuses on Xbox Live...

**Comment by MichaelHillcox** [comment]
Due to the original author not replying with a valid debug code. I'm gunna close this. Always ensure you're using the correct Microsoft account when logging into the app!
