### ISSUE TITLE
Missing world in Stoneblock 2

### ISSUE THREAD

**Issue by FeelingBowl2131** [FTBTeam/FTB-App#918]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.12.2

### Describe the bug

When I launched the FTB App it and went to my Libary it said that I had nothing installed even though I have had Stone Block 2 installed for a few days now. I reinstalled the Mod pack and once it finished loading none of my world were there. I still have the world in my files, but I am unsure of what to do with the file/ if there is anything I can do with my world file.

### Steps to reproduce

I have no clue how to reproduce the issue.

### Expected behaviour

I expected to see Stoneblock 2 in my Libary.

**Comment by FeelingBowl2131** [comment]
@Raidobw2 which channel should I @ you at?

**Comment by Raidobw2** [comment]
Any will do! 🙂

**Comment by Raidobw2** [comment]
Some information for the app devs:

The `instance.json` file that was accompanying the old StoneBlock 2 instance appears to be corrupted.
It is made of 137986 null characters `\0` (or bytes).

**Comment by MichaelHillcox** [comment]
Thanks, we've sorted this and it's currently phasing out at 50% on overwolf, should be 100% in the next day or so.
