### ISSUE TITLE
[Bug] Text is barely visible in the installer

### ISSUE THREAD

**Issue by egor100500** [FTBTeam/FTB-App#92]
**Operating System:**
OS:Ubuntu 18.04.4

Installer text is very-very light gray on white

![image](https://user-images.githubusercontent.com/33977079/79114119-27360800-7d8b-11ea-8bfc-02a1e6fcd425.png)

**Comment by MichaelHillcox** [comment]
This isn't something we're able to fix, we've contacted Install4j but we don't have an ETA for a fix. Sorry about this.
