### ISSUE TITLE
Fabric Mod Searching not working in the app

### ISSUE THREAD

**Issue by BobPoppy** [FTBTeam/FTB-App#920]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.7.0

### Describe the bug

i am not able to search any mods to add to the modpack using the built in add more mods feature nor does the modapack recognize any new mods i add. this happens with this and a select few other modpacks but ive tried with FTB skies and the feature works on there.

### Steps to reproduce

1.Download Legend of the eyes modpack
2. Go to the mod instance page
3. go on the mods tab
4. click the add more mods button beside the search bar
5. search a mod like ultimine
6. page gets stuck searching for infinity

### Expected behaviour

When a mod is searched, the mod with that name or something close to it shows up so you can add it

**Comment by MichaelHillcox** [comment]
Note to self: This also needs fixing in the app as when no results are found, that should be shown to the user
