### ISSUE TITLE
Cannot download modpacks on Steam Deck

### ISSUE THREAD

**Issue by DDzwiedziu** [FTBTeam/FTB-App#922]
### What Operating System

Linux (Arch)

### Debug Code

FTB-DBGSIMASABITI

### Describe the bug

"Exceptional error" when trying to download a pack

### Steps to reproduce

1. Install FTBA on a Steam Deck.
2. Try to download a modpack (I've tried the latest Skies and Direwolf20).
4. The download dialog appears, but there's no progress and it quickly disappears. An "Error installing modpack Exceptional error preparing installation task" appears. 

Log:
[FTB_bork_2023-06-15T191737.log](https://github.com/FTBTeam/FTB-App/files/11779843/FTB_bork_2023-06-15T191737.log)
 
Tried asking on the Discord, but no avail. I've only excluded DNS problems (as much as one can exclude DNS problems) following some conversations that had similar errors.

### Expected behaviour

Install a modpack

### Additional information

Steam Deck, SteamOS 3.4.8

**Comment by CoryNB** [comment]
run in linux or windows emulator that the os emulates with interface. the steam deck overheats easily so versions before 1.7 to 1.5 or before should be more stable due to less size in minecrafr modpack size. ftb legacy launcher era or curseforge era of modpack launcher based commands.

**Comment by DDzwiedziu** [comment]
I've got on a rant train, so I'll make a TL;DR:
- Steam Deck is Linux,
- not overheating (more logs),
- "go back to MC 1.7.x/1.5.x" - lol, no,
- "to big to handle on Steam Deck" - no,
- me being insightful or annoyed (for sure sarcastic here).

I can barely understand this message, so I'll try to take it apart.

> run in linux or windows emulator that the os emulates with interface.

Steam Deck *is* Linux. I've run FTBA from Desktop Mode, as I don't plan to
run it from Game Mode (FTBA doesn't start in GM anyway).

If the workaround to play on the SD by downloading on a separate machine
and then copying the FTBA folder structure (here I'd like to point out that
asking for the `FTBA` path at installation and then installing to `.ftba`
anyway is a bit on the users' nose to say at least) to SD doesn't work (at
least on the first try with Synching).

> the steam deck overheats easily (…)

I'm *very* tempted just to slap “hersay” here, as the problem is repeatable
(attached two more log files, from two separate days) and we're talking
about initializing transfers, not gameplay.
If the SD overheated at this point, then I'd probably return it after
receiving. And I've already installed more GiB's of games than GiB's of
Minecraft (and the problem is, I repeat, with *initializing* a transfer)
and played both of “types” of GiB's.

So, I'm just going to slap a “non sequitur” here.

> so versions before 1.7 to 1.5 or before should be more stable due to less
size in minecrafr modpack size. ftb legacy launcher era or curseforge era
of modpack launcher based commands.

If you're trying to “downgrade” me to Minecraft versions 1.7.x or 1.5.x,
then I have bad news there, *buddy*. I installed Prism Launcher, and played
*current* versions of Vanilla MC, or packs from Modrinth, ATLauncher and
even Curse Forge (did not try Technic yet).

Also this coincides with the decision to cut off 3rd party launchers whole,
instead of just restricting access. I may hack away a solution, but that's
time not spent playing.
Even the next hack I'll try (separate computer, MultiMC FTB import, ZIP
export, transfer, Prism import) is already too much steps on the drawing
board, and I don't even mention getting to the upgrade *workflow*.



pon., 19 cze 2023, 01:51 użytkownik CoryNB ***@***.***>
napisał:

**Comment by MichaelHillcox** [comment]
That's... That's a strange issue... I'll add it to my list...

**Comment by Gaz492** [comment]
We have made quite a few changes to the app since this issue was opened, including how the app is installed on linux.
Somewhere between this issue being opened and now, it looks like the issues you reported have been fixed, as I was able to install and play both the packs mentioned and other packs.

You may need to download a fresh copy of the app. https://feed-the-beast.com/ftb-app

**Comment by DDzwiedziu** [comment]
I probably won't be able to test in the coming days, so if you have tested
it working, then feel free to close this ticket.
