### ISSUE TITLE
When selecting java version, it looks for Java, instead of java.

### ISSUE THREAD

**Issue by gegoxaren** [FTBTeam/FTB-App#924]
### What Operating System

Linux (Debian)

### Debug Code

FTB-DBGBAXUVEVEHI

### Describe the bug

Looking for `Java` instead of `java`.

### Steps to reproduce

1. go to an instance
2. go  to settings -> java version -> Browse.
3. navigate to where a java version is installed
4. can not see anything.

### Expected behaviour

You should be able to see the java executable.

### Screenshots

![Skärmbild från 2023-06-18 11-52-10](https://github.com/FTBTeam/FTB-App/assets/58400667/9c1f59bf-7e58-4453-911f-e61d1260df14)
![Skärmbild från 2023-06-18 11-52-59](https://github.com/FTBTeam/FTB-App/assets/58400667/cd76187a-9f8c-437b-aa16-21a18de6a5dc)

### Additional information

This error occurs because FTBApp is looking for `Java` instead of `java` (look at the case of the letters).

**Comment by MichaelHillcox** [comment]
Hmm, interesting, I'll look into this :+1:

**Comment by MichaelHillcox** [comment]
Hi, can you confirm if this is still an issue? We don't actually tell the OS what file to expect, logically you can put anything in there. Not really sure how Linux has figured out it should be `Java`...

**Comment by gegoxaren** [comment]
It is still present in version `202310071959-918caed003`.

**Comment by MichaelHillcox** [comment]
Very interesting... ![](https://c.mikey.pro/scr/f8Z5J1u7.png) Looks like I've found why it's saying `Java` but it's specifically saying any file time so it might be an issue in the fact that it should be `*` instead
