### ISSUE TITLE
jei cheat mode soft lockout

### ISSUE THREAD

**Issue by CoryNB** [FTBTeam/FTB-App#925]
### What Operating System

Windows 11

### Debug Code

N/A modifier bug of minecraft

### Describe the bug

the bug affects in game login and logout

### Steps to reproduce

changes to jei cheat mode keybinds break interface of minecraft

### Expected behaviour

behavior should work without clicking conflict between op warn/chat warn.

### Screenshots

no screenshots, discovered in all the mods 7 sky under jei cheat mode commands. found under that in key binds command.

### Additional information

I recently discovered this today. it is a softlock that forces user to close application.

**Comment by MichaelHillcox** [comment]
Not an app issue
