### ISSUE TITLE
Cannot download any modpack

### ISSUE THREAD

**Issue by pirateofthepixels** [FTBTeam/FTB-App#927]
### What Operating System

Windows 11

### Debug Code

FTB-DBGAYIMOXILIV

### Describe the bug

Fatal exception while trying to download modpack

### Steps to reproduce

1. Select a modpack
2. Try to download
3.  Download fails

### Expected behaviour

Modpack should download

### Screenshots

![Screenshot 2023-06-20 122500](https://github.com/FTBTeam/FTB-App/assets/127605652/6e06d9b1-4a14-4db7-ae0e-4febb4c49864)

### Additional information

(https://pste.ch/timafacexa) Line 955 may help

**Comment by MichaelHillcox** [comment]
Can you try with this version of the FTB App and let me know if this continues to happen?

https://appsdl-overwolf-com.akamaized.net/prod/apps/cmogmmciplgmocnhikmphehmeecmpaggknkjlbag/1.23.622.1340/app.opk

Please make sure the FTB App is closed before opening this link.

**Comment by pirateofthepixels** [comment]
> 

Im sorry but I don't know how to run opk files on Windows.

**Comment by MichaelHillcox** [comment]
Should be as simple as double clicking the opk file. if it does not work, try opening with overwolf

**Comment by MikeyM3thodic4l** [comment]
Having the same issue. Had to enable developer options in overvolf then manually load through the settings>about>development options menu in overwolf (double clicking it or "open with" overwatch just threw errors even with developer options on) and even after getting that build loaded I am still unable to load any packs.

**Comment by awildsnorlax1** [comment]
I'm having the same exact issue. Everything seems to be going fine then Fatal exception whilst installing modpack.

**Comment by pirateofthepixels** [comment]
The only packs that i can donwload are the FTB unstables

**Comment by MichaelHillcox** [comment]
Attach a debug code please

Windows
[ftb-debug.exe](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe)
MacOS
[ftb-debug-macos](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos)
Linux
[ftb-debug-linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux)

**Comment by awildsnorlax1** [comment]
FTB-DBGROKUKADALA

**Comment by MichaelHillcox** [comment]
> FTB-DBGROKUKADALA

You're not on the latest app version @awildsnorlax1 https://appsdl-overwolf-com.akamaized.net/prod/apps/cmogmmciplgmocnhikmphehmeecmpaggknkjlbag/1.23.622.2252/app.opk Use that one instead

**Comment by awildsnorlax1** [comment]
is 1.5.5 not the latest?

**Comment by awildsnorlax1** [comment]
yep. just updated to 1.5.6 and I can install again.

**Comment by MichaelHillcox** [comment]
Awesome!

**Comment by pirateofthepixels** [comment]
> yep. just updated to 1.5.6 and I can install again.

im on 1.5.6 and i still cant install anything

**Comment by MichaelHillcox** [comment]
Please attach a new debug log on the latest version

**Comment by pirateofthepixels** [comment]
> Please attach a new debug log on the latest version

https://pste.ch/agayapigip

**Comment by MichaelHillcox** [comment]
Sorry for the really delayed response. Is this still happening?

**Comment by pirateofthepixels** [comment]
Yes, the issue persists

**Comment by Swat99Swat** [comment]
I have the same or a similar situation. Modpak or immediately blows an error, or download some files and later blows an error, well, and sometimes downloading just does not happen.  FTB-DBGCENIGUSARA   202310071959-918caed003
![Screenshot_1](https://github.com/FTBTeam/FTB-App/assets/17888700/7787cded-f65b-4c6f-b102-47781244d6b0)
![Screenshot_2](https://github.com/FTBTeam/FTB-App/assets/17888700/7e5fcc7c-1165-4293-b3e0-c55a6d77fa41)
![Screenshot_3](https://github.com/FTBTeam/FTB-App/assets/17888700/98155753-119e-4e7e-a424-9017adbb2459)
![Screenshot_4](https://github.com/FTBTeam/FTB-App/assets/17888700/42a41dbf-225c-40cc-8205-1a98574b0031)

**Comment by Swat99Swat** [comment]
I solved the problem by installing a VPN on my computer. And everything works and downloads fine.
