### ISSUE TITLE
Can't download anything

### ISSUE THREAD

**Issue by lemnex** [FTBTeam/FTB-App#928]
### What Operating System

Windows 11

### Debug Code

FTB-DBGXILUFEYAJI

### Describe the bug

Can't install any modpack

### Steps to reproduce

Click on install (any modpack)

### Expected behaviour

Fatal exception whilst installing modpack

### Additional information

![Unbenannt](https://github.com/FTBTeam/FTB-App/assets/62899687/2a16f7af-ff2e-4b8f-bafd-872ed0b02f51)

**Comment by iiPharo** [comment]
same here

**Comment by Yhwsup** [comment]
Same here tried: stoneblock3, unstable 1.20

**Comment by MichaelHillcox** [comment]
Can you try with this version of the FTB App?

https://appsdl-overwolf-com.akamaized.net/prod/apps/cmogmmciplgmocnhikmphehmeecmpaggknkjlbag/1.23.622.1340/app.opk

Please ensure the FTB App is closed before opening that link.

**Comment by lemnex** [comment]
Unfortunatly doesn't work.

**Comment by MichaelHillcox** [comment]
Can you run the debug tool again please

**Comment by lemnex** [comment]
FTB-DBGUPOROCUDID

thanks for the quick reply btw :)

**Comment by MichaelHillcox** [comment]
I've forwarded this to our developer, I'll get back to you once we have an answer! Thanks for the speedy debug code.

**Comment by pirateofthepixels** [comment]
> same here

I cant download anything except the FTB Unstable packs

**Comment by MichaelHillcox** [comment]
Update your app https://appsdl-overwolf-com.akamaized.net/prod/apps/cmogmmciplgmocnhikmphehmeecmpaggknkjlbag/1.23.622.2252/app.opk
