### ISSUE TITLE
Cannot get my world back after app randomly forgot my instance

### ISSUE THREAD

**Issue by wrchh** [FTBTeam/FTB-App#929]
### What Operating System

Windows 10

### Debug Code

FTB-DBGQOZIKUPUZU

### Describe the bug

Adding world backups to the saves folder does not bring the world up in game.

### Steps to reproduce

I click on "Show instance folder" and copy my backed up world save into the saves folder and it does not show up in the game.

### Expected behaviour

Adding saved world to saves folder should make the save appear in the game.

### Additional information

So my app randomly forgot that I have Interactions downloaded, all my play time is gone, like I never had it. In my AppData folders, the old saves and instance are still there, the app just doesn't recognize them. I redownloaded the pack and it created a new instance without any save data. I took the old world saves and put them into the new instance, thinking I could simply get my world back that way, but when I open the game there is nothing in the menu. New worlds I create, which show up right there, next to my copied save, in the saves folder, do appear. What am I doing wrong? I have a zipped world backup from last night, which would only put me back about 2 hours. Can I load into that somehow?

**Comment by MichaelHillcox** [comment]
Hi, is this still an issue for you? We've recently shipped a fix that should stop this happening
