### ISSUE TITLE
[Bug] Installation script doesn't detect openjdk Java 8 version

### ISSUE THREAD

**Issue by egor100500** [FTBTeam/FTB-App#93]
**Operating System:**
OS: Ubuntu 18.04.4

**Installer Version:**
Installer: 1.0.5

**Describe the bug**
Installation script is not able to detect Java 8 OpenJSK installed thus Java 11 downloaded and set as default preventing MC from launch.

```
user@comp:~/Downloads$ sudo update-alternatives --config java
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
  2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: 2
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java to provide /usr/bin/java (java) in manual mode
```

**Comment by Cloudhunter** [comment]
The app should not be installing OpenJDK 11 - it should only be installing its own version for its own purposes. Are you sure that it was our app which installed it? If it is, it is a bug - not sure how much power I have in order to work round this, but I will definitely look into it.

The app requires at least Java 11.0.5, hence why it uses its own OpenJDK 11.

**Comment by drcrazy** [comment]
Yes, installation of OpenJDK 11 was mentioned in console due to not found java.

**Comment by egor100500** [comment]
FTB App install script haven't detected OpenJDK 8 and installed OpenJDK11. During installation of OpenJDK11 was set as default by it's own installation script, I suppose.
