### ISSUE TITLE
Stuck in Validation

### ISSUE THREAD

**Issue by ArtsyRedhead4** [FTBTeam/FTB-App#930]
### What Operating System

Windows 11

### Debug Code

unsure. tool would not open

### Describe the bug

FTB Skies and OceanBlock- downloaded both and both will get stuck on the third step of validating assets. It will not load up any further than that. This usually results in a complete freeze of the FTB app or it will stop the process and send me an error message.

### Steps to reproduce

1. Open FTB app
2. Click on Skies or OceanBlock
3. Click Play
4. Starts load up sequence and gets stuck on Validating Assets

### Expected behaviour

Both packs look like they are super fun to play. I'd love to be able to get them to play

### Screenshots

![Screenshot (2)](https://github.com/FTBTeam/FTB-App/assets/137584930/bec7cbc8-4d13-4704-935f-2fcc45d29265)

### Additional information

I have StoneBlock 3 which works perfectly, but these two just will not open. I have tried restarting my computer. I have tried deleting and redownloading the app. I have tried to delete and redownload both packs. I have even tried deleting and redownloading Minecraft Java. Nothing has resolved the issue. Kill instance does not work to close the process when it gets stuck.

**Comment by manmaed** [comment]
close the app
goto %localappdata%\.ftba\bin
remove the folder assets
open ftb app and try again
