### ISSUE TITLE
Wrongfully uses SOCK5 instead of SOCKS5 for proxies

### ISSUE THREAD

**Issue by nea89o** [FTBTeam/FTB-App#931]
### What Operating System

Linux (Other)

### Debug Code

FTB-DBGARIVIFAKEJ

### Describe the bug

Wrongfully uses SOCK5 instead of SOCKS5 for proxies

### Steps to reproduce

1. Have a SOCKS5 proxy running
2. Set that SOCKS5 proxy as SOCK5 proxy in the proxy settings tab
3. Stall all downloads and get this error log: https://pste.ch/udonowetub
4. Notable excerpt:
	```
	java.lang.IllegalArgumentException: Unknown proxy type 'sock5'. Expected one of 'http', or 'socks5'.
		at net.creeperhost.creeperlauncher.util.ProxyUtils.loadProxy(ProxyUtils.java:85) ~[launcher-202306222252-df78a8cfe7-all.jar:?]
		at net.creeperhost.creeperlauncher.util.ProxyUtils.loadProxy(ProxyUtils.java:63) ~[launcher-202306222252-df78a8cfe7-all.jar:?]
	```

### Expected behaviour

To connect to that socks5 proxy and 

### Additional information

Btw, your debug code is wrongly checking for my java home. it is listing my local java home, not the one that is used by the app that i installed systemwide.

**Comment by MichaelHillcox** [comment]
We've fixed this! :D
