### ISSUE TITLE
Can't update, download, or play any modpacks.

### ISSUE THREAD

**Issue by VIcolf** [FTBTeam/FTB-App#932]
### What Operating System

Windows 10

### Debug Code

FTB-DBGOJICICUXEC

### Describe the bug

Can't update or download any modpacks, nor can I play any that I already have.

### Steps to reproduce

Attempt to download any new modpack get error, "fatal exception whilst installing modpack"
Attempt to update an already downloaded modpack get error, "fatal exception whilst installing modpack" 
Attempt to play any already downloaded modpack. it begins and works until it goes to validate client, then stops and returns to application to the screen before I pressed play; and does not provide error code or launch the modpack.

### Expected behaviour

expected to download, update, or launch packs 

### Screenshots

![fifth](https://github.com/FTBTeam/FTB-App/assets/138536610/4973e061-e1c3-4f21-be8a-54c655018139)
![forth](https://github.com/FTBTeam/FTB-App/assets/138536610/67e08c39-3a30-4aa1-a00a-103bcc2f3dbb)
![third](https://github.com/FTBTeam/FTB-App/assets/138536610/ec53e68a-543b-44e1-a386-533cf7e0d38b)
![second](https://github.com/FTBTeam/FTB-App/assets/138536610/3f4b8e66-488a-4c75-b788-76bebc979b6d)
![first](https://github.com/FTBTeam/FTB-App/assets/138536610/39840426-0978-4f38-9185-08cb5ce9e726)

### Additional information

This is the app log url thats created when I press the "upload app log" button.
https://pste.ch/jorexiramu 

I have also uninstalled and reinstalled FTB app and overwolf twice already.

**Comment by MichaelHillcox** [comment]
Can you confirm if this is still an issue for you?

If it is, can you confirm if "C:\Users\lvjew\AppData\Local\.ftba\bin\runtime\jdk8u312-b07-jre\bin\javaw.exe" exists?

**Comment by VIcolf** [comment]
The file "Local.ftba" and everything inside, does not exist. Is it a plausible idea for me to manually create the folders for this?
