### ISSUE TITLE
Update for specific CurseForge modpack fails

### ISSUE THREAD

**Issue by NorthLake** [FTBTeam/FTB-App#937]
### What Operating System

Windows 10

### Debug Code

FTB-DBGUVUHEDOXAK

### Describe the bug

Update for CurseForge modpack fails: `InvalidPathException: Illegal char <:> at index 12: config/Users:juneasis:Documents:cu.textClipping`

### Steps to reproduce

1. Install Mystical Block 2.4
2. Try updating to 2.5

### Expected behaviour

The pack is updated

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/20684682/a2ea0dde-ef37-4eb8-b988-a1310de271c1)

### Additional information

The changelog couldn't load either. It kept trying to fetch.

**Comment by MichaelHillcox** [comment]
This looks to be fixed in a recent update :+1:
