### ISSUE TITLE
Ads in app

### ISSUE THREAD

**Issue by sznur7** [FTBTeam/FTB-App#938]
### What Operating System

Windows 10

### Debug Code

FTB-DBGYERAZAZIXO

### Describe the bug

Cant click the downgrade button

### Steps to reproduce

i dont know

### Expected behaviour

Downloading an older version of a modpack to test it

### Screenshots

https://github.com/FTBTeam/FTB-App/assets/139303131/9a9b57fb-b5f9-4b8a-998b-5cd12913a180

**Comment by manmaed** [comment]
This should now be fixed in new version as ads dont overlay the version window ![](https://ss.manmaed.net/1694045951.png)
