### ISSUE TITLE
More often than not the Browse section does not load any FTB Packs

### ISSUE THREAD

**Issue by Souliboi** [FTBTeam/FTB-App#940]
### What Operating System

Windows 10

### Debug Code

FTB-DBGTOYIKOMIDE

### Describe the bug

As the title suggests, more often not opening the FTB App and going to the Browse section doesn't display any FTB Packs

### Steps to reproduce

1. Launch FTB App
2. Click on Browse

### Expected behaviour

FTB Packs at least should load and be displayed

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/106060704/c3f35a46-00aa-4485-ac8a-88f87c905847)

### Additional information

If it matters, the setting to close Overwolf on Exit is enabled.

**Comment by Maloxer** [comment]
I had the same problem juts fixed it try to install new java if u dont have it i think this a issue and then reinstall app and restart computer
