### ISSUE TITLE
Can't Close Versions Window

### ISSUE THREAD

**Issue by kingofaces2** [FTBTeam/FTB-App#941]
### What Operating System

Windows 10

### Debug Code

FTB-DBGLOFANUCESI

### Describe the bug

Opening any version of a modpack in a small window makes the close button not work.

### Steps to reproduce

1. Open FTB
2. Go to Library
3. Click on Modpack
4. Click on Versions
5. The x button in the Versions tab does not work.

### Expected behaviour

Pressing the X button in Versions should bring you back to the modpack page.

**Comment by MichaelHillcox** [comment]
That's weird, is this still an issue for you?

**Comment by kingofaces2** [comment]
Seams to be only an issuse on my main pc. Can not recreate it on my laptop.

**Comment by MichaelHillcox** [comment]
What version of the app is your main machine on? You can check by going to settings and hovering the version in the bottom left
