### ISSUE TITLE
Never mind the modpacks

### ISSUE THREAD

**Issue by Adrianxd3** [FTBTeam/FTB-App#942]
### What Operating System

Windows 11

### Debug Code

I don't know

### Describe the bug

No matter curseforge mod packs

### Steps to reproduce

I give import modpack

I select the modpack

I select the modpack

And I see the Error

(https://github.com/FTBTeam/FTB-App/assets/139749369/9e5f1603-89b4-49a0-b503-8df8df9d4997)

### Expected behaviour

 what does the modpack matter

### Screenshots

![Captura de pantalla 2023-07-17 102838](https://github.com/FTBTeam/FTB-App/assets/139749369/05b8ad2f-d85d-404e-9303-e94d9f2788db)

### Additional information

No work

**Comment by MichaelHillcox** [comment]
Closing due to no debug code
