### ISSUE TITLE
ads show on top of version page

### ISSUE THREAD

**Issue by RyanvanEs** [FTBTeam/FTB-App#944]
### What Operating System

Windows 11

### Debug Code

FTB-DBGUZIYOGILOD

### Describe the bug

when you open the page to change to version of a modpack the ads block part of the information.

### Steps to reproduce

1. Install a modpack.
2. Go to library.
3. Click on the modpack to open its page.
4. Click on the version button to change the modpack version.
5. Ads will be on top of the page.

### Expected behaviour

I expected the page to show on top of the ads. Instead of the ads showing on top of the page.

### Screenshots

![afbeelding](https://github.com/FTBTeam/FTB-App/assets/124669566/82d35da3-c74b-461b-bf60-26e4c3f52996)

**Comment by manmaed** [comment]
This should now be fixed in new version ![](https://ss.manmaed.net/1694045951.png)
