### ISSUE TITLE
 "When downloading, an error is displayed."

### ISSUE THREAD

**Issue by sishousenpai** [FTBTeam/FTB-App#945]
### What Operating System

Windows 11

### Debug Code

FTB-DBGGIPOFAWEBI

### Describe the bug

 "When downloading, an error is displayed."

### Steps to reproduce

![image](https://github.com/FTBTeam/FTB-App/assets/75687288/e155e48e-2308-495a-86c9-13535dcfd5b1)
![image](https://github.com/FTBTeam/FTB-App/assets/75687288/c682eb9c-6c6b-4b32-a2de-d7d84e1f4935)
![image](https://github.com/FTBTeam/FTB-App/assets/75687288/c19d1cfc-8b1c-42c9-b853-99befc92a0b9)
![image](https://github.com/FTBTeam/FTB-App/assets/75687288/f47625eb-1a03-42b9-8984-cbf7d8490c72)

### Expected behaviour

"I want it to be made playable."

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/75687288/1b7686eb-2d57-4160-b3ba-25e1b6c00dad)

**Comment by dragonmann1998** [comment]
I had the same problem. I just downloaded the Java runtime environment manually. After that, I can install modpacks now.

Link to Java Runtime Environment: https://www.java.com/de/download/manual.jsp

**Comment by MichaelHillcox** [comment]
Thanks for the report. Gunna close as it's related to #965
