### ISSUE TITLE
FTB APP Crashed after loading Unstable 1.20 Forge v1.40

### ISSUE THREAD

**Issue by Zfilez** [FTBTeam/FTB-App#946]
### What Operating System

Windows 11

### Debug Code

FTB-DBGUVIWOXAHOT

### Describe the bug

a bug that is crashing the FTB APP after some time spamming with some nice words Also got a Log for you to read down below

### Steps to reproduce

i just start the add and start the client and the app crashed no stapes needed.

### Expected behaviour

it not to to crash as you tend not to expect programs/apps to crash randomly specifcily after an update.

### Screenshots

https://pste.ch/cuxeqaduna The Log

### Additional information

This issue happend after i updated with the new mods and its EnderIO that is causing it so i removed it from the mod folder and it seemt to fix the crashing issue

**Comment by IamStig** [comment]
I am playing v1.5.0 of the Unstable pack and having the same issue. It is not affecting playing but the message comes up after the loader is ready. 

![App crash](https://github.com/FTBTeam/FTB-App/assets/20489424/d8e98d56-0168-4974-a909-20fb75cd25a7)

**Comment by MichaelHillcox** [comment]
Thanks for the report. Gunna close it in preference for #970 as it's the same issue :D
