### ISSUE TITLE
FTB App Ad Placement

### ISSUE THREAD

**Issue by SniketTheLlama** [FTBTeam/FTB-App#947]
### What Operating System

Windows 11

### Debug Code

FTB-DBGINEYOXAZEV

### Describe the bug

Terrible placement for ads blocks the X button and "Server Files" button.

### Steps to reproduce

Laptop, scale to 150%, then try to navigate the app fullscreen. Even at 100%, you can see the ads start to block portions of the UI.

### Expected behaviour

dedicated viewing window for ads that don't block app usage.

### Screenshots

![FTB_App_AdPlacement](https://github.com/FTBTeam/FTB-App/assets/13948688/d791698b-71f6-4336-89d0-8b6cc3f11579)

**Comment by manmaed** [comment]
This should now be fixed in new version ![](https://ss.manmaed.net/1694045951.png)
