### ISSUE TITLE
Failed to retrieve essential information, please try again

### ISSUE THREAD

**Issue by MSeanBattisti** [FTBTeam/FTB-App#948]
### What Operating System

MacOS (Latest)

### Debug Code

FTB-DBGWAFARAKEPU

### Describe the bug

FTB fails to log in to profile

### Steps to reproduce

see below screen shots.

### Expected behaviour

profile loads and able to play FTB

### Screenshots

<img width="1432" alt="Screen Shot 2023-07-21 at 9 29 51 PM" src="https://github.com/FTBTeam/FTB-App/assets/136191600/2340670b-c66d-4b4b-a79e-761afd6532e0">
<img width="1362" alt="Screen Shot 2023-07-21 at 9 30 51 PM" src="https://github.com/FTBTeam/FTB-App/assets/136191600/6a5e97d1-0eff-466a-8bcd-49e27ee58965">

**Comment by MSeanBattisti** [comment]
Are we just getting ignored for those who have MACOS?

**Comment by MichaelHillcox** [comment]
Definitely not. Is this still an issue? @MSeanBattisti

**Comment by MSeanBattisti** [comment]
@MichaelHillcox Yes, it is.

**Comment by MichaelHillcox** [comment]
Could you confirm the version number of your app?
