### ISSUE TITLE
microsoft account cant connect

### ISSUE THREAD

**Issue by LostAstronaut175** [FTBTeam/FTB-App#949]
### What Operating System

Windows 10

### Debug Code

FTB-AUTH-000006

### Describe the bug

when trying to link app to microsoft account error show up 

### Steps to reproduce

open the app 
try to link account to microsoft 
error pops up 
ownership and profile set up

### Expected behaviour

link to microsoft account

**Comment by MichaelHillcox** [comment]
Please make sure you are using the correct Microsoft account. Please let me know if this is still an issue
