### ISSUE TITLE
[Bug] - Server files have incorrect URI

### ISSUE THREAD

**Issue by Drjoachim** [FTBTeam/FTB-App#95]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: Latest 

**App Version:**
App: 1.0.6

**UI Version:**
UI: c84af858

**Log Files:**
https://pste.ch/otasoceful

**Describe the bug**
If you install an offical modpack and go to the newly installed modpack, click on the versions tab and try to download the server files it re-directs to an incorrect URI:

**To Reproduce**
For example for the Omnia pack:

Steps to reproduce the behaviour:
1. Download the modpack
2. Click on 'My Modpacks'
3. Click on the three dots 
4. Click on the versions tab
5. Click on 'Download Server'

> This redirects to : https://api.modpacks.ch/public/modpack/**undefined**/46/server/linux

**Expected behaviour**
> Redirect to https://api.modpacks.ch/public/modpack/**6**/46/server/linux

**Screenshots**
NA

**Additional context**
NA

**Comment by Rushmead** [comment]
Fixed in the next build :)

**Comment by Drjoachim** [comment]
Damn, that was fast 👍
