### ISSUE TITLE
We can't find the FTB App!

### ISSUE THREAD

**Issue by gilates** [FTBTeam/FTB-App#950]
### What Operating System

MacOS (Latest)

### Debug Code

FTB-DBGINORIBASOH

### Describe the bug

When trying to log in via Microsoft Account I get this message

### Steps to reproduce

1 - Open FTB APP
2 - Select Mod Pack and select Play
3 - Login via Microsoft Account

### Expected behaviour

I expected to have a login screen from Microsoft

**Comment by MichaelHillcox** [comment]
What message?
