### ISSUE TITLE
Instance & app crashes after sleep/hibernate

### ISSUE THREAD

**Issue by MohamdSaan** [FTBTeam/FTB-App#951]
### What Operating System

Windows 10

### Debug Code

FTB-DBGXIXOHAMIHI

### Describe the bug

Instance & app crash after i turn on pc from sleep or hibernate

### Steps to reproduce

1. Start any modpack
2. Go to sleep/hibernate
3. turn on pc again

### Expected behaviour

the instance shouldnt crash

### Screenshots

![ftb_issue](https://github.com/FTBTeam/FTB-App/assets/70522339/c893aab7-7510-400c-a35c-0b4bd957b1df)

**Comment by mexmer** [comment]
you don't even need modpack running.
launch FTB app and wait until it loads
put computer to sleep or hibernation
wake up computer
check "running" FTB app, it did crash as show on OP image.

**Comment by lost-RD** [comment]
This is really annoying. I hibernate regularly and it's getting on my nerves. About to start looking for a way to run a pack in a different launcher.

**Comment by WouterButers** [comment]
I have the same problem after I wake up my pc from sleep the FTB app gives the error. But my game instance of the game(modpack direwolf20 1.20) still works fine.

**Comment by mexmer** [comment]
@WouterButers yes the issue is not about game, it's about ftb launcher instance.
game (if we talking minecraft here) runs in separate process and in java, while ftb launcher is native windows app running on top of overwolf framework. so there should be no relation between launcher and game.

**Comment by lost-RD** [comment]
@WouterButers actually, for me, it's both the game and the launcher.

I can instead import the pack into a third party launcher, run it, hibernate, resume, and neither the game nor the launcher has crashed. So  in my case, the FTB launcher is crashing and brining the game down with it.

**Comment by mexmer** [comment]
that is interesting. for me minecraft doesn't crash, when FTB launcher crash. just quick question, are you using minetogether? that's the first mod i remove from any pack i play
