### ISSUE TITLE
Ftb academy 1.16.5

### ISSUE THREAD

**Issue by KretzV2** [FTBTeam/FTB-App#954]
### What Operating System

Windows 10

### Debug Code

https://bytebin.lucko.me/WgOOVWpfOD

### Describe the bug

https://bytebin.lucko.me/WgOOVWpfOD

### Steps to reproduce

https://bytebin.lucko.me/WgOOVWpfOD

### Expected behaviour

https://bytebin.lucko.me/WgOOVWpfOD

### Screenshots

https://bytebin.lucko.me/WgOOVWpfOD

**Comment by manmaed** [comment]
This is the FTB App Issue Tracker you want the https://github.com/FTBTeam/FTB-Modpack-Issues/issues and the link doesn't work
