### ISSUE TITLE
App not letting me connect my Java account

### ISSUE THREAD

**Issue by GoosieTTV** [FTBTeam/FTB-App#956]
### What Operating System

Windows 11

### Debug Code

FTB-DBGOBADUTIHOS

### Describe the bug

When I try to link my account to the FTB launcher, it doesn't let me and says my account is under 18 years old. I am almost 19.

### Steps to reproduce

1. Click the Sign in to your minecraft account button in app
2. Click the Microsoft button
3. Sign into Microsoft account through web tab
4. Click on FTB app again and screenshot text.

### Expected behaviour

I am almost 19, I will be at the end of August and I should be able to link my account. Curseforge works fine and as soon as I tried with the FTB app it just does not work.

### Screenshots

![Screenshot 2023-08-07 121208](https://github.com/FTBTeam/FTB-App/assets/38023228/31834bc3-df7f-4991-bf27-de38ef723a2f)
![Screenshot 2023-08-07 121453](https://github.com/FTBTeam/FTB-App/assets/38023228/694d506e-91e5-40fd-9165-0295f0d459ff)

### Additional information

I don't know what the issue is so any ideas or tips or help would be appreciated.

**Comment by MichaelHillcox** [comment]
Is your account linked to a family account?

**Comment by xJakeySenpaii** [comment]
> Is your account linked to a family account?

I don't know how to tell if it is or isn't

**Comment by xerri04** [comment]
I have the same problem as well

**Comment by XShaDoWX1** [comment]
how can i solve this issue i am 20 and cant login
