### ISSUE TITLE
FTBApp dont start after update to 1.5.10

### ISSUE THREAD

**Issue by belovres** [FTBTeam/FTB-App#958]
### What Operating System

Windows 10

### Debug Code

FTB-DBGJOFAQUDOJO

### Describe the bug

FTBApp dont start after update to 1.5.10

### Steps to reproduce

1. Install 1.5.9 from FTB site
2. Launch and close app
3. Retry launch app
4. error

### Expected behaviour

Launch the app and play minecraft

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/1362380/32885c0c-b7b8-4d2d-8a67-0d1445895d44)

**Comment by KrtekCZ** [comment]
I got aroud it by removing windows accout from Admin group via manager - local users and goups "your acc" properties and tab when remove admins group.

**Comment by belovres** [comment]
That is, in order to play Minecraft, I have to remove administrator rights from my user?!  For what?  Why not add the ability to run with administrator rights to the application.  For example, this window appears, it would be possible to put a checkbox: "I am aware of everything, launch it anyway", and after selecting, launch the application?!

**Comment by belovres** [comment]
![Screenshot_2023-08-12-12-10-27-15_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/FTBTeam/FTB-App/assets/1362380/f34851a3-f432-45e5-a91f-a36fc2b3009c)
The code comments say "Show error and on confirm close the app", but pressing ANY button closes the app anyway.

**Comment by KrtekCZ** [comment]
I just added quick solution for someone who want to play immediately and do not want to wait for program fix. I am not saying its clever solution but it worked for me. Other solution can be to create additional windows  acc without admin rights.

**Comment by castel-int** [comment]
> I just added quick solution for someone who want to play immediately and do not want to wait for program fix. I am not saying its clever solution but it worked for me. Other solution can be to create additional windows acc without admin rights.

can u please elaborate a little more on what u did

**Comment by belovres** [comment]
Fixed.  Commit: ea2ac91
