### ISSUE TITLE
Unable to get Minecraft profile

### ISSUE THREAD

**Issue by florian1105** [FTBTeam/FTB-App#959]
### What Operating System

Windows 11

### Debug Code

FTB-AUTH-000006

### Describe the bug

Error when I try to connect with my microsoft account

### Steps to reproduce

1. Go to sign in to your minecrafgt account 
2. Connect with microsoft informations 
3. Error displayed : 
FTB-AUTH-000006
We've been unable to get your Minecraft profile and we've been unable to check your accounts entitlements. This means you almost definitely don't own Minecraft on this account. 

### Expected behaviour

Connect to my account 

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/43952610/ae1f0f9d-c30f-4d7a-bdcc-760d01ba1d77)

### Additional information

I can launch minecraft with no problems on the xbox app and minecraft launcher.

**Comment by Hawkmoon66** [comment]
i have this exact same issue

**Comment by MichaelHillcox** [comment]
Please make sure you're using the correct account

**Comment by DaphneOdera17** [comment]
I got the same problem
