### ISSUE TITLE
Cant login to Minecraft

### ISSUE THREAD

**Issue by suravit0** [FTBTeam/FTB-App#962]
### What Operating System

Windows 11

### Debug Code

FTB-AUTH-000005

### Describe the bug

It looks like you own XBox Gamepass for PC or have only recently bought Minecraft Java Edition, this is great! Unfortunately, before we can log you in, you'll need to start the Vanilla Launcher at least once and run Minecraft. Once you have done this, try again

### Steps to reproduce

open the app
try to login to microsoft account
login on microsoft successful
error pops up during the final stages of authentication in the app

### Expected behaviour

app authenticating my microsoft account with no issues

### Screenshots

<img width="476" alt="image" src="https://github.com/FTBTeam/FTB-App/assets/144223881/6721fcef-f868-4b57-9a25-9831f506b3a6">

### Additional information

The error states

"It looks like you own XBox Gamepass for PC or have only recently bought Minecraft Java Edition, this is great! Unfortunately, before we can log you in, you'll need to start the Vanilla Launcher at least once and run Minecraft. Once you have done this, try again"

**Comment by manmaed** [comment]
Please make you have logged in to the vanilla Launcher and launched minecraft

**Comment by manmaed** [comment]
im going to close this and move it to #960

**Comment by tobico** [comment]
This error is not very helpful when you're on Fedora and there is no official way to install the vanilla launcher.

After doing some research I downloaded the Prism launcher flatpak instead which allowed me to log in without issue.
