### ISSUE TITLE
Fatal Exception Whilst Installing Modpack

### ISSUE THREAD

**Issue by momoring96** [FTBTeam/FTB-App#963]
### What Operating System

Windows 11

### Debug Code

FTB-DBGIKUSUGAMUS

### Describe the bug

Fatal Exception Whilst Installing Modpack

### Steps to reproduce

1. Launch FTB App
2. Attempt to install Modpack 
3. Install fails at the last step of the process

### Expected behaviour

Install is successful

### Screenshots

![ftberror](https://github.com/FTBTeam/FTB-App/assets/144396063/e852f8bc-92df-4282-89a7-069558aced02)

### Additional information

Log Files:
https://pste.ch/jifisuyequ

**Comment by dragonmann1998** [comment]
I had the same problem. I just downloaded the Java runtime environment manually. After that, I can install modpacks now.

Link to Java Runtime Environment: https://www.java.com/de/download/manual.jsp

**Comment by MichaelHillcox** [comment]
That's very strange. Try again and see if it happens again. It looks to be a one time thing though. Please let me know if it happens again
