### ISSUE TITLE
Fresh install - FTB can't connect.

### ISSUE THREAD

**Issue by JLeif** [FTBTeam/FTB-App#967]
### What Operating System

Windows 10

### Debug Code

FTB-DBGMIJIMUYARE

### Describe the bug

Tried to Open FTB Connection Failed

### Steps to reproduce

Start FTB.
- Oops, Something went wrong...
- App Ver 1.5.13
- UI 1903496f17
- Sub Ver 202308291248-1903496f17
- Reconnect tries: 25+

### Expected behaviour

FTB to launch and i can view and choose mod packs

**Comment by davidp234** [comment]
![image](https://github.com/FTBTeam/FTB-App/assets/20927052/ce4c3d1a-51f2-4e91-b0f8-1601d84f64b6)
im getting this error when trying to install the launcher (just downloaded the installer from the site so i do have internet

**Comment by MichaelHillcox** [comment]
Looks like your system already had a version of the app running in the background. A simple system restart should resolve this
