### ISSUE TITLE
crach FTB

### ISSUE THREAD

**Issue by Ironarc-corp** [FTBTeam/FTB-App#968]
### What Operating System

Windows 11

### Debug Code

FTB-DBGJOLEKAJAHO

### Describe the bug

lancheur crach

### Steps to reproduce

I launch my Minecraft instance after a while randomly in time the launcher lags and crashes

### Expected behaviour

a voir les code car depuis 2 jour je n'arrive plus a rentrer dans mon mode et je voudrais savoir pourquoi

### Screenshots

![Capture d'écran 2023-09-26 220516](https://github.com/FTBTeam/FTB-App/assets/108798657/d65b29c2-e630-4e1c-aa0e-c5a2e34d9b23)
![Capture d'écran 2023-09-26 220614](https://github.com/FTBTeam/FTB-App/assets/108798657/1298ae89-16d4-4d55-9630-35291402859f)

**Comment by MichaelHillcox** [comment]
Closing in preference of #970
