### ISSUE TITLE
FTB App - Cannot Install Launcher "Check internet connection"

### ISSUE THREAD

**Issue by bryan8392** [FTBTeam/FTB-App#969]
### What Operating System

Windows 10

### Debug Code

FTB-DBGAMUMEGAPIQ

### Describe the bug

Cannot install launcher due to installer thinking I have no internet connection

### Steps to reproduce

1. Downloaded FTB App Installer from feed the beast website.
2. Double click FTB App Installer to install.
3. Clicked Next.
4. Waited a few seconds and a pop up says "Connection error. Please check your internet connection and try again".

I'm connected to the internet (how I'm posting here). I added the installer to windows firewall exceptions. No other antivirus or anything. I also tried running as administrator. 

### Expected behaviour

Expected to install FTB launcher

### Screenshots

[https://i.imgur.com/9N513Jb.png](https://i.imgur.com/9N513Jb.png)

**Comment by GreenRanger316** [comment]
Same issue except i am on windows 11

**Comment by muchachoTAKO** [comment]
I'm having the exact same issue (using Windows 10).

**Comment by GreenRanger316** [comment]
Found a work around.  Downloaded overwolf and then downloaded FTB App from Overwolf and it worked

**Comment by muchachoTAKO** [comment]
Ok, Thanks so much!
