### ISSUE TITLE
FTB Academy 1.1.0 incorrect changelog

### ISSUE THREAD

**Issue by jamierocks** [FTBTeam/FTB-App#97]
**Operating System:**
OS: n/a

**Installer Version:**
Installer: n/a

**App Version:**
App: n/a

**UI Version:**
UI: n/a

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app
n/a

**Describe the bug**

The changelog for FTB Academy 1.1.0 is simply just `Changelog`.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://api.modpacks.ch/public/modpack/1/2/changelog
2. See the value of `Content` is simply just `Changelog`
3. See https://www.curseforge.com/minecraft/modpacks/ftb-academy/files/2792364
4. See the changelog there isn't simply `Changelog`

**Expected behaviour**
A full changelog - like the one on CurseForge.

**Screenshots**

**Additional context**

**Comment by Rushmead** [comment]
Thanks for reporting this, this should now be resolved but it could take some time to propagate through the caches. I saw your messages in discord and I'll add that providing the modpack id, version id and what the changelog should be reduces the time it takes for the issue to be resolved. I'd ask that in any future API related issues that you provide this information :)

**Comment by jamierocks** [comment]
👍 

Though there does seem to be an issue with the data, specifically `^M` at the end of each line.

**Comment by jamierocks** [comment]
I've formatted the changelog to match `1.2.0`'s and removed the `^M`s if you'd like to use it - https://ftb.neptunepowered.org/pack/ftb-academy/version/1-1-0/.
