### ISSUE TITLE
After FTB app update, MacOS instances have issues with using their own java installations

### ISSUE THREAD

**Issue by atealein** [FTBTeam/FTB-App#972]
### What Operating System

MacOS (Old)

### Debug Code

FTB-DBGGEBICENAQE

### Describe the bug

A new attempt to install instance of the direwolf20 modpack is failing at loading the instance (after installing it) with error that it cannot use it's own java installation.

### Steps to reproduce

1. Load FTB app (version 1.5.14) - there are no instances active.
2. Install a modpack - in my case FTB Presents Direwolf20 - the instance installs successfully
3. Click to play the instance - get error message. 
![Screenshot 2023-10-06 at 19 14 54](https://github.com/FTBTeam/FTB-App/assets/25322782/4f66679f-fd9e-4578-98e1-66821ce3b795)

### Expected behaviour

I expect the FTB app to be able to use the java instance it has just installed for a new modpack

### Additional information

I believe the issue might be connected with the new "better" MacOS support for Arm, however my MBP is an Intel one and shouldn't be affected by the new changes. I have tried a number of things, including deleting entirely the new java directory so the FTB app will have to download and install it fresh. This is an issue from today - yesterday I installed the modpack and was running fine, I wanted to test a new installation and that's when the issues began - and since it is something wrong with the new java directory the old instance that was working perfectly 12 hours ago, now is no longer running either.

**Comment by atealein** [comment]
I am sorry for the lack of Debug Code, but after clicking the "MacOS" link in the form, the downloaded "tool" was not an executable file or program and couldn't be run directly by my (Catalina 10.15.7) MacOS

**Comment by atealein** [comment]
Trying to point the instance to use an older java directory ( "jdk-17.0.7+7-jre" instead of the newly installed "jdk-17.0.7+7-jre_x64" ) worked and loaded the instance. So there is definitely an issue in the installation and use of the new java directory.

**Comment by atealein** [comment]
I got confirmations from other players reporting the same issue - it seems to be cross-MacOS - different versions, Intel and M1/M2.

**Comment by Yoshi325** [comment]
I'm experiencing the same behavior.

(I'm on an Intel Mac)

**Comment by LilacLAdy222** [comment]
I'm experiencing the same thing as well. I'm on the M1 MacOS

**Comment by atealein** [comment]
Workaround guide: 

How to work around it depends if you already have valid instance of java installation (from previous modpack you have played maybe) or not (in which case you will have to install manually).

Step 1: Check if you have a valid java installation in your .ftba folder which can be used: you can find the folder within your /Users/$USER/Library/Application Support/.ftba/bin/runtime directory. 
If you have directories that look like:
jdk-17.0.7+7-jre
and
jdk-17.0.7+7-jre_x64

you can use your older version of the java ("jdk-17.0.7+7-jre"). In that case go to Step 3.

Step 2: If you don't have such java installations, you will have to install one manually (no guide provided here) 

Step 3: Make sure you delete the instance that failed to install in the FTB app and you close the app (don't delete it or attempt to reinstall or it will lose your old java installation). Go to the java directory in the .ftba/bin/runtime and delete the "jdk-17.0.7+7-jre_x64" directory and potentially any 17.0.7.tar.gz file that might be there. Then start the FTB app and try to install the instance anew. DO NOT START IT, just install. 
(if this goes okay the ftb app will install the "jdk-17.0.7+7-jre_x64" folder anew, but it is still broken so don't try to start the instance)

Step 4: After installation, go to the instance settings and manually set the path to the java version to be custom path to either the old "jdk-17.0.7+7-jre/Contents/Home/bin/java" or your manually installed java that is located elsewhere.

Step 5: Start the instance and good luck. If you get over the "Validation of java" step, you should be good to play!

**Comment by Yoshi325** [comment]
Thank you very much for the workaround steps @atealein !

I have been trying to get the files from https://adoptium.net/ to work, but haven't reached the end of that path yet.

**Comment by Markintosh** [comment]
Your post was a godsend as I sat down to play on a rainy day and discovered this issue. Thank you!

**Comment by MichaelHillcox** [comment]
We've released a hotfix that should fix this, please let me know if anyone has any more issues
