### ISSUE TITLE
App won't authenticate

### ISSUE THREAD

**Issue by Shaistrong** [FTBTeam/FTB-App#978]
### What Operating System

Windows 11

### Debug Code

FTB-DBGKAVOGAMIPI

### Describe the bug

the app won't authenticate with my Minecraft account.

### Steps to reproduce

try to install the app and sign in to your Minecraft account.

### Expected behaviour

the expected behavior is for the app to work..

### Screenshots

![Screenshot 2023-10-11 210650](https://github.com/FTBTeam/FTB-App/assets/73827899/7eb49bf7-c4ce-4f2c-a24d-a467e4c127a6)

### Additional information

the app used to work for me before. I formatted my PC a while ago due to other reasons, and I wanted to play the game again. it won't authenticate for some reason; I've tried to reinstall Minecraft entirely and starting a world before reporting this- didn't do anything.

**Comment by waffles912** [comment]
Having a similar issue. Can't seem to authenticate through microsoft, though I can login on the official MC launcher.

**Comment by MrDKGE** [comment]
Just wanted to confirm that I have the issue as well.
Unable to authenticate at all using a Microsoft account.
And since that I didn't have a mojang account before I am unable to use the app at all.
Even with the token you can capture from the network traffic and manually enter in the client.

**Comment by GodUbar** [comment]
I got the exact same Problem aswell
