### ISSUE TITLE
I recive a fatal error whilst trying to download a modpack

### ISSUE THREAD

**Issue by OhItchy** [FTBTeam/FTB-App#979]
### What Operating System

Windows 10

### Debug Code

FTB-DBGAZENUNEWIL

### Describe the bug

I recive a fatal error whilst trying to download stoneblock 3

### Steps to reproduce

1. Open FTB app
2. Go to install stoneblock 3
3. Says "installing the Modloader"
4. Error saying "Fatal exception whilst installing modpack"

### Expected behaviour

install modpack

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/148128331/c0f0f8c3-5227-4559-93e4-31c04fd8b206)

### Additional information

This does not only happen whilst trying to install stoneblock. I tried to update a different modpack, which had the same error

**Comment by mhork** [comment]
I had the same error trying to download the new Direwolf20 modpack as well
