### ISSUE TITLE
[Bug] FTB Omnia 1.2.0 Linux server fails when downloading forge

### ISSUE THREAD

**Issue by AKTheKnight** [FTBTeam/FTB-App#98]
**Operating System:**
OS: Linux

**Installer Version:**
Installer: FTB Omnia 1.2.0

**Log Files:**
https://pste.ch/pesufetewa.sql

**Describe the bug**
Omnia 2.1.0 Linux installer fails with a 404 when trying to download forge

**To Reproduce**
wget https://api.modpacks.ch/public/modpack/6/48/server/linux -O serverinstall_6_48
chmod +x serverinstall_6_48
./serverinstall_6_48

**Expected behaviour**
It should manage to install Forge

**Screenshots**
![image](https://user-images.githubusercontent.com/7502848/79382380-51d6bb00-7f5b-11ea-9d39-1f87fcac1613.png)

**Comment by AKTheKnight** [comment]
https://github.com/FTBTeam/FTB-Omnia/issues/31

**Comment by Cloudhunter** [comment]
This should now be resolved.
