### ISSUE TITLE
Panic: Runtime Error for Server Installer on ARM

### ISSUE THREAD

**Issue by Bts0** [FTBTeam/FTB-App#986]
### What Operating System

MacOS (Latest)

### Debug Code

FTB-DBGABESEZACER

### Describe the bug

Panic during any server install on ARM64

### Steps to reproduce

1. Download any ARM64 FTB Server Installer executable to a Mac M1+ device.
2. Mark executable. `chmod +x <serverinstall_...>`
3. Run the executable `./<serverinstall_...>`

### Expected behaviour

Server installer to run and create files as intended.

### Additional information

Here is an instance where I downloaded the Direwolf20 Server and attempted to run the Server Installer:
```
file serverinstall_119_6957
serverinstall_119_6957: Mach-O 64-bit executable arm64
```

```
./serverinstall_119_6957
panic: runtime error: index out of range [86] with length 86

goroutine 1 [running]:
main.getKey()
	/builds/creeperhost-core/creeperhost-launcher/frontend/ftbserverdownloader/util.go:452 +0x2b0
main.init()
	/builds/creeperhost-core/creeperhost-launcher/frontend/ftbserverdownloader/main.go:57 +0x54
```

**Comment by MichaelHillcox** [comment]
Please report the issue here https://github.com/CreeperHost/modpacksch-serverdownloader/issues
