### ISSUE TITLE
[Bug] FTB Omnia 1.2.0 Windows Installation fails

### ISSUE THREAD

**Issue by Hejle** [FTBTeam/FTB-App#99]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: Omnia 1.20

**App Version:**
App: 1.0.8

**UI Version:**
UI: fa03e62e

**Log Files:**
Put links to your logs here
[error.log](https://paste.feed-the-beast.com/view/e1dc3c66)
[launcher.log](https://paste.feed-the-beast.com/view/20daaa40)
how to find logs: https://faq.ftb.world/books/ftb-app

**Describe the bug**
When installing Omnia 1.20 the installation fails.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open FTB-app
2. Choose to install Omnia 1.20
3. Installation Fails

**Expected behaviour**
Omnia 1.20 should get installed

**Comment by Hejle** [comment]
https://github.com/FTBTeam/FTB-Omnia/issues/32

**Comment by AKTheKnight** [comment]
I am having this issue too

**Comment by Rallysports** [comment]
This affects the MacOS client as well.

**Comment by AKTheKnight** [comment]
This should now be fixed, try again and let us know if it doesn't work :)

**Comment by Rallysports** [comment]
> This affects the MacOS client as well.

I can confirm that this has resolved the issue for me.  Thanks.

**Comment by Hejle** [comment]
And also works for me :)
Thanks!

**Comment by Cloudhunter** [comment]
Closing as resolved
