### ISSUE TITLE
Can't download/update/play modpacks

### ISSUE THREAD

**Issue by Sn0oZemc** [FTBTeam/FTB-App#991]
### What Operating System

Windows 11

### Debug Code

FTB-DBGELIGUTOQID

### Describe the bug

I can't download nor update modpacks nor play modpacks

### Steps to reproduce

1. Open the FTb app
2. click on any modpacks to install/update or even play
3. It'll say ''fatal exception preparing installation task''

### Expected behaviour

being able to play, update and install modpacks

### Screenshots

![ftb error](https://github.com/FTBTeam/FTB-App/assets/149637585/71dac0e1-18cc-4497-9921-e527bd998f89)

### Additional information

I did reinstall the app and also deleted all FTB related files. The problem stays...

**Comment by bringrainfire** [comment]
I had the same issue, deleting and reinstalling did not fix it. However, 2.11 installed fine. That means there's an issue with the current version of 0.2.12 right now.

**Comment by jmeggitt** [comment]
I am also encountering this issue. #995 is likely caused by the same problem and includes more info.
