### ISSUE TITLE
Fatal exception installing ATM9

### ISSUE THREAD

**Issue by paradust7** [FTBTeam/FTB-App#994]
### What Operating System

Windows 10

### Debug Code

FTB-DBGQOCIDOTIGA

### Describe the bug

ATM9 will not install or update to 0.2.14

### Steps to reproduce

1. Open FTB App
2. Install ATM9 0.2.14

The log file shows that FTB App is trying to download:

https://edge.forgecdn.net/files/4844/931/embeddium-0.2.7%252bmc1.20.1.jar

Instead of the real file:

https://edge.forgecdn.net/files/4844/931/embeddium-0.2.7%2bmc1.20.1.jar

This is the result of double encoding "+", first to "%2b", then to "%252b"
(The same happens with 4 other files)

### Expected behaviour

It should install successfully

**Comment by hvdklauw** [comment]
Create: Haven Adventures:
https://pste.ch/janaqazevi

https://edge.forgecdn.net/files/4836/196/Steam_Rails-1.5.3%252bforge-mc1.20.1.jar should be https://edge.forgecdn.net/files/4836/196/Steam_Rails-1.5.3%2bforge-mc1.20.1.jar

**Comment by hvdklauw** [comment]
I tried downloading the file myself and putting it in the mods folder where it's finding the other files, but that doesn't seem to work

**Comment by hvdklauw** [comment]
Even using all the options in the filenames doesn't work, something funky is going on.. it's nog even finding the file when it's there. 

Tried:

- Steam_Rails-1.5.3%2bforge-mc1.20.1.jar
- Steam_Rails-1.5.3%252bforge-mc1.20.1.jar
- Steam_Rails-1.5.3+forge-mc1.20.1.jar
- Steam_Rails-1.5.3 forge-mc1.20.1.jar

**Comment by leagris** [comment]
> Even using all the options in the filenames doesn't work, something funky is going on.. it's nog even finding the file when it's there.
> 
> Tried:
> 
>     * Steam_Rails-1.5.3%2bforge-mc1.20.1.jar
> 
>     * Steam_Rails-1.5.3%252bforge-mc1.20.1.jar
> 
>     * Steam_Rails-1.5.3+forge-mc1.20.1.jar
> 
>     * Steam_Rails-1.5.3 forge-mc1.20.1.jar

`Steam_Rails-1.5.3+forge-mc1.20.1.jar` is the name for the file in the `mods` folder. Though keep in mind that the issue is for the FTB Team to track and fix the problem, not to provide support for applying work-around the bug.

**Comment by paradust7** [comment]
@hvdklauw For personalized help, join the FTB discord. Most likely you're also missing the other file too, https://edge.forgecdn.net/files/4834/490/curios-forge-5.4.2%2b1.20.1.jar
