### ISSUE TITLE
Modpack doesn't load up if online

### ISSUE THREAD

**Issue by nicolas5852** [FTBTeam/FTB-App#996]
### What Operating System

Windows 10

### Debug Code

FTB-DBGMUVATAVAHI

### Describe the bug

Whenerver I try to load certain packs that previously worked fine, they don't work unless I load then offline

### Steps to reproduce

1. Launch App
2. Select a modpack and click play

### Expected behaviour

Loading up the modpack properly so I could play the game online

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/101266003/0bc358e7-9880-4dc0-9396-7d5fe27f54de)

**Comment by tlannigan** [comment]
Not an FTB App bug. You need to update your AMD drivers or make sure you're using your discrete GPU and not your integrated GPU.

https://github.com/tlannigan/modded-minecraft-help#my-game-crashed-and-i-have-a-file-called-hs_err_pidxxxxlog-in-my-modpack-folder-now
