### ISSUE TITLE
Modpacks do not work

### ISSUE THREAD

**Issue by BleckOZW** [FTBTeam/FTB-App#999]
### What Operating System

Windows 11

### Debug Code

FTB-DBGBEFIQUBIVA

### Describe the bug

Modpack not working. 
No matter what modpack I use - it do not work. As example see screenshot.

### Steps to reproduce

1. Instal modpack
2. Press Play
3. Error

### Expected behaviour

Working app

### Screenshots

<img width="788" alt="image" src="https://github.com/FTBTeam/FTB-App/assets/150679810/c78aeba9-4174-49ad-9647-f346bfcc6cc1">

**Comment by Snuffar** [comment]
same problem here except I am on windows 10

**Comment by wintermute1972** [comment]
Same issue here on Ubuntu 23.10 too!
